### ISSUE TITLE
Investigar Como App

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#1]
Marce, estuve probando una plataforma para generar Apps de forma muy intuitiva y permite insertar código HTML. Lo que necesito saber es cuáles son las limitaciones de la app que podríamos crear con eso. Por ejemplo:
1. Se puede insertar funciones con geolocalización?

Y otras limitaciones que vos veas o se te ocurran. Yo la probé y permite mucho, incluso subir directo a Google Play o AppStore e insertar código HTML.

abrazo

**Comment by mkreyness** [comment]
```
No tengo idea, decime cual es esa plataforma y pruebo. En general
todas las que yo vi alguna vez eran muy pedorras, pero fue hace
tiempo.

El 04/02/2015 a las 12:32,
  LeandroBraier escribió:


  Marce, estuve probando una plataforma para generar Apps de
    forma muy intuitiva y permite insertar código HTML. Lo que
    necesito saber es cuáles son las limitaciones de la app que
    podríamos crear con eso. Por ejemplo:

    Se puede insertar funciones con geolocalización?

  Y otras limitaciones que vos veas o se te ocurran. Yo la probé
    y permite mucho, incluso subir directo a Google Play o AppStore
    e insertar código HTML.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perdon, no te pasé el link.

es http://www.como.com/

Si querés te presto mi usuario donde tengo creada una app de prueba.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-04 12:41 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
me hago una y pruebo de cero, quiero ver como es el proceso.

El 04/02/2015 a las 12:56,
  LeandroBraier escribió:

Perdon, no te pasé el link.

  es http://www.como.com/

  Si querés te presto mi usuario donde tengo creada una app de
  prueba.



  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-02-04 12:41 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > No tengo idea, decime cual es esa plataforma y pruebo. En
  general
  > todas las que yo vi alguna vez eran muy pedorras, pero fue
  hace
  > tiempo.
  >
  > El 04/02/2015 a las 12:32,
  > LeandroBraier escribió:
  >
  >
  > Marce, estuve probando una plataforma para generar Apps de
  > forma muy intuitiva y permite insertar código HTML. Lo que
  > necesito saber es cuáles son las limitaciones de la app que
  > podríamos crear con eso. Por ejemplo:
  >
  > Se puede insertar funciones con geolocalización?
  >
  > Y otras limitaciones que vos veas o se te ocurran. Yo la
  probé
  > y permite mucho, incluso subir directo a Google Play o
  AppStore
  > e insertar código HTML.
  > abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/1#issuecomment-72877141.
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
```
Listo, no parece muy diferente a cualquier otro (para decirlo
finamente) generador de "apps" pedorro.

Lo que genera no son Apps, el app es simplemente un custom browser
fijo al que le adosan contenido.
Si bien podes escribir el source HTML,  es solo para formateo, no
corren scripts asi que en la practica NO se puede programar, ni
insertar ningun widget que requiera javascript, probablemente porque
ese browser encubierto directamente no soporte javascript.

O sea, esta muy bueno si lo que necesitas armar esta DENTRO de lo
que hace (lo cual incluye muchas cosas piolas para un mobile app,
pero ni en pedo puede encapsular la funcionalidad de un sitio web
real, solo paginas estaticas que tenes que mantener desde el editor
y republicar cada vez), y no podes agregarle ninguna funcionalidad
no prevista por ellos, porque estas restringido dentro de un
(verdadero) app que tiene un conjunto fijo y acotado de
posibilidades.

Estuve buscando en el blog y la documentacion y no veo referencia
alguna a la geolocalizacion. A lo sumo te explican que importante es
que muestres en un mapa donde esta tu negocio, pero sabemos que eso
no es lo mismo.


El 04/02/2015 a las 14:25, Marcelo
  Kreyness escribió:



  me hago una y pruebo de cero, quiero ver como es el proceso.

  El 04/02/2015 a las 12:56,
    LeandroBraier escribió:

  Perdon, no te pasé el link.

    es http://www.como.com/

    Si querés te presto mi usuario donde tengo creada una app de
    prueba.



    Leandro Braier
    Producción Audiovisual & Social Media
    Benteveo Producciones <http://benteveo.tv>
    Móvil 1158717399

    2015-02-04 12:41 GMT-03:00 mkreyness <notifications@github.com>:

    >
    >
    >
    >
    >
    > No tengo idea, decime cual es esa plataforma y pruebo. En
    general
    > todas las que yo vi alguna vez eran muy pedorras, pero fue
    hace
    > tiempo.
    >
    > El 04/02/2015 a las 12:32,
    > LeandroBraier escribió:
    >
    >
    > Marce, estuve probando una plataforma para generar Apps de
    > forma muy intuitiva y permite insertar código HTML. Lo que
    > necesito saber es cuáles son las limitaciones de la app que
    > podríamos crear con eso. Por ejemplo:
    >
    > Se puede insertar funciones con geolocalización?
    >
    > Y otras limitaciones que vos veas o se te ocurran. Yo la
    probé
    > y permite mucho, incluso subir directo a Google Play o
    AppStore
    > e insertar código HTML.
    > abrazo
    > —
    > Reply to this email directly or view
    > it on GitHub.
    >
    > —
    > Reply to this email directly or view it on GitHub
    >
    <https://github.com/LeandroBraier/Klaukol/issues/1#issuecomment-72877141>.
    >
    —
      Reply to this email directly or view

        it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ok, gracias Marce!! Voy a seguir buscando apps de ese estilo. Conocés
alguna que nos permita hacer esto que te pido?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-04 14:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, busco yo tambien a ver que encuentro.
Aparte de la geolocalizacion se te ocurre alguna otra caracteristica que 
deberia tener ?

**Comment by LeandroBraier** [comment]
No en particular, podría ser subir una foto, un avatar, subir contenido,
hacer e commerce, pero tomá de referencia la app de la Marca Weber, que es
la competencia de Klaukol.

http://goog_1328742415
https://play.google.com/store/apps/details?id=com.fourdmedia.weberar

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-04 17:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Features de redes sociales parece que tienen todos, lo deben hacer 
usando las APIs de c/u.

**Comment by mkreyness** [comment]
Este me gusta porque tiene un API, dice que maneja javascript, etc.
Parece mucho mas profesional. Tiene geofencing.

https://mobileroadie.com

El problema es que es un poco CARITO !!!
Version CORE u$s149/mes (o u$s1500/año)
Version PRO u$s799/mes !!! (o  u$s8000/año).

Tiene un free trial por supuesto.
Lo que no tengo claro es si pagas 1 mes y despues no pagas mas (por 
ejemplo porque no vas a desarrollar nuevas apps) si el app sigue 
funcionando o automaticamente se cae.

**Comment by LeandroBraier** [comment]
Está bueno Marce!

La versión PRO no nos conviene, tenemos gente que la hace más barata que
eso a la app. pero con la Versión Core nos arreglamos vos decís?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-04 18:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Por lo que veo aca el API y geo-fencing son PRO.

https://mobileroadie.zendesk.com/hc/en-us/articles/200092036-Core-vs-Pro-App-Packages

**Comment by LeandroBraier** [comment]
Gracias Marce! Entonces creo que nos quedamos con lo que tenemos.

Es así: Un equipo local de desarrolladores nos pasó 32.000 pesos aprox para
la app. Seguramente si aKlaukol le resulta mucho hacemos una más simple,
sin geolocalización, basada en algo tipo Como, que cuesta mucho menos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-04 18:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Puede haber cosas intermedias, es cuestion de seguir buscando, pero de 
todos modos $32000 pesos por versiones iOS+Android (si funcionan bien) 
con soporte local me parece un buen precio.

**Comment by LeandroBraier** [comment]
Exacto. Y son gente copada con la que hablo Eze y están en Argentina y hablan español. Eso vale también no? jeje abrazo
