### ISSUE TITLE
Juego BuscaMinas Klaukol en Flash

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#101]
@mkreyness ya tengo la primera versión del diseño del juego del BuscaKlaukol en Flash.

https://www.wetransfer.com/downloads/b8dfc4eac1331cc794e8898989e2dece20150715201953/f06698

Todavía lo estoy corrigiendo y revisando pero te lo paso para que me digas cómo proceder para

1)  Qué necesitás que exporte o diga para que le sumemos puntos al usuario cada vez que pasa de nivel.

2) Qué necesitás para subirlo a la plataforma.

abrazo

**Comment by mkreyness** [comment]
Supongo que el puntaje a sumar podria llegar a ser variable en funcion de como le fue, no ?
Las interfaces deberian ser que a esto se lo pueda llamar con 3 parametros, que me tiene que incluir tal cual se los paso, mas uno adicional con el puntaje.
O sea, por ejemplo si esto se lo framea como juego.swf en una pagina, yo quisiera poder poner (no se si es la sintaxis correcta, ni idea de flash) algo tipo

juego.swf?callback=<ALGO>

por ejemplo,

juego.swf?callback="/cgi-bin/sumarpuntos.pl?usuario=marcelokreyness&clave=pepe&juego=123"

Probablememente los simbolos vayan URL-encoded, algo asi:

%2Fcgi-bin%2Fsumarpuntos.pl%3Fusuario%3Dmarcelokreyness%26clave%3Dpepe%26juego%3D123

Y que cuando el juego termine, el flash llame al url que le pase como "callback", de esta manera:

/cgi-bin/sumarpuntos.pl?usuario=marcelokreyness&clave=pepe&juego=123&puntos=100

o sea agregandole los puntos obtenidos.

Una vez que se implemente esto, lo embeddeamos en algun nuevo template (eso lo tendria que preparar Fede) que se activaria ante determinado tipo "juego" que le pongamos en el CMS.

**Comment by LeandroBraier** [comment]
Gracias MK!!

@FAAREIA me ayudás con eso que pide MK y me decís qué le tengo que pedir al diseñador flash para ayudarte con esto?

abrazo

**Comment by LeandroBraier** [comment]
Buen dia @FAAREIA ! Esto es ultraprioridad hoy porfa. Avisame qué necesitamos y empecemos a hacer pruebas porque mañana tiene que quedar online este juego.

abrazo

**Comment by mkreyness** [comment]
Yo estuve mirando documentacion sobre Flash y las dos cosas que pido son factibles, lo que tenes que pedirle al diseñador Flash es que tome la variable "callback" que le voy a pasar en el URL (Flash acepta leer el "query string" que viene en su propio URL) y despues cuando termina el juego haga un navigateURL(callback + '&puntos=' + x)  donde x es el puntaje obtenido en el juego.

**Comment by FAAREIA** [comment]
Ahi lo pongo en un HTML asi hacen las pruebas necesarias

**Comment by LeandroBraier** [comment]
Genial. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/vendedores/juego-busca.html
Hay un biblioteca que capas pueda servir, pero no me la puse a leer por completo ni esta embebido asi el SWF, https://code.google.com/p/swfobject/

**Comment by LeandroBraier** [comment]
Fede, la limitación de que no pierdas cuando detectás la bomba tiene que ver con el flash no?

Se lo pido a Juan a eso.

**Comment by FAAREIA** [comment]
Aca en firefox y Chrome no pierdo ni gano nunca. ¿A vos te tira un cartel?
Si hay que arreglar algo, hay que hacerlo desde el archivo flash si o si

**Comment by LeandroBraier** [comment]
Ok.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-16 13:46 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Lo veo con el diseñador flash gracias Fede!

**Comment by LeandroBraier** [comment]
@mkreyness, porfa mandame un link donde se explique esto que me decís de documentación Flash, si puede ser paso a paso mejor. El diseñador no termina de ver cómo hacerlo.

**Comment by mkreyness** [comment]
Passing data to Flash with URL query strings:

http://blog.swishzone.com/?p=4541

navigateToURL:

http://www.republicofcode.com/tutorials/flash/as3link/

**Comment by mkreyness** [comment]
Aca ya implemente un "tema" que se llama "BuscaKlaukol", con una unica actividad, de tipo "Juego", que tiene dentro el flash. Le saque un poco de elementos al cuete (el titulo era redundante porque ya dice "Busca Klaukol" dentro del Flash). Obviamente falta la parte de como sumar los puntos, y no se exactamente cuantos puntos serian los que el juego otorgaria de maxima.
Ademas estoy suponiendo que se puede jugar una sola vez, lo cual no se si en ESTE caso tiene sentido, confirmame.
Aca esta el link:

http://parexklaukol.com.ar/cgi-bin/jugar.pl?id=6&usuario=marcelokreyness&clave=pepe

NO esta habilitado al publico real.
Habria que hacer algun snapshot del juego empezado para poner como thumbnail cuando se muestra la lista de temas.

**Comment by mkreyness** [comment]
Bueno ya esta todo resuelto lo del SWF, pero me tiro un par de errores de conversion con los textos que me obligo a comentariar un par de lineas con lo que ya no avanza el reloj y sale feo el texto de "PERDISTE" o "GANASTE". Igual te paso por mail lo que hay que agregar al original si queres recompilarlo vos en Mac y mandarme el swf.
Se puede entrar al juego por el URL que ya puse arriba, ya tiene todas las variables y suma puntos (puse que el puntaje sea proporcional a las bombas, o sea, si jugas el dificil (35 bombas) te da los 100 puntos [o lo que sea que vayamos a dar] y si son menos bombas, menos puntos.
Ojo si lo probas teniendo ya 95 o mas puntos, no vas a ver que te sume, como siempre, porque estamos "suspendidos".

**Comment by LeandroBraier** [comment]
Lo de los puntos pongamoslo así MK:

Muy fácil: Suma 5 puntos

Fácil: Suma  10 puntos 

Moderado: Suma 25 puntos

Difícil: Suma 50 puntos

En total sumaría 75 puntos por todo el juego.

abrazo

**Comment by mkreyness** [comment]
O sea, le dejamos volver a jugarlo hasta que llegue a 75 y despues no mas ?

**Comment by LeandroBraier** [comment]
Exacto.

**Comment by mkreyness** [comment]
Listo, ya esta sumando asi, maximo total del juego 75. Ojo en los lugares donde dice cuanto sumas puse que diga 50 PTS (que es lo maximo que podes sacar en una jugada), pero no es vinculante, el verdadero puntaje NO sale de lo que diga el CMS sino de este algoritmo en base a la cantidad de bombas.

**Comment by LeandroBraier** [comment]
jaja Hice mal el cálculo!

El total serían 95 puntos, no?

5 +10 + 25 + 50 = 95

En total serían 95 en todo el juego. En el slideshow pongo 95. El 50 que pusiste dejalo así, está bien.

Creo que vos no tenés que modificar nada si a cada nivel le pusiste el valor correcto.

**Comment by LeandroBraier** [comment]
@FAAREIA en qué horario estás trabajando vos hoy? 

Dentro de la mañana tenemos que subir el juego y el slide perteneciente al juego. Te voy a pasar el SWF en un ratito, pero confirmá con MK si hay algo que va por fuera del SWF que él ya dejó impactado en el HTML. 

Necesito que a la tarde ya esté subido el juego y el slide y podamos probarlo, así cuando viene MK a las 16 hs le puedo pedir cualquier corrección o si hay algun bug.

No quiero que corramos como nos viene pasando los últimos viernes hasta ultima hora.

abrazo

**Comment by mkreyness** [comment]
Tengo que ajustar a 95 el limite que puse en el programa, pero es una pavada, ya esta.

**Comment by mkreyness** [comment]
el path al SWF esta puesto como "video" del tema en el CMS (el actual dice img/gamesweeper_game_mk.swf, pero se le puede poner cualquiera, lo importante es ademas de ponerlo en el servidor, ajustar eso en el CMS) 
Y les recuerdo que falta algun snapshot del juego empezado para poner en la lista de temas. Eso va puesto como "imagen" del tema en el CMS.
Todo lo externo al swf (FlashVars etc) ya esta puesto en el template juego-juegoT.html (si, el nombre es ridiculo pero los otros se llamaban juego-trivia, juego-video, etc.) y, salvo que cambien las dimensiones del recuadro, no habria por que tocarle nada.

**Comment by LeandroBraier** [comment]
Perfecto Marce! Yo cargo el preview en el CMS cuando subamos el juego entonces.

Solo quedaría pasarle a @FAAREIA el SWF cuando esté listo y que quede subido ahí.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA , te pasé el juego por gmail. Avisame si te llegó. Ya tiene el mismo nombre que el que puso Marce en el CMS como video. Solo habría que subirlo a la carpeta /img lo antes posible.

Avisame cuando esté porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya subi el archivo SWF a la carpeta img.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA!

@mkreyness estoy probandolo y jugar juega pero al final no me lleva a ningun lado al ganar y no me permite volver a empezar. Es algo en el código, porque si pierdo si vuelvo. Hay que seguir trabajando el Action Script.

http://parexklaukol.com.ar/cgi-bin/jugar.pl?id=6&usuario=marcelokreyness&clave=pepe

**Comment by LeandroBraier** [comment]
@mkreyness Te mando por mail en un txt el código tal como lo puse. Confirmma si está bien y sino pasamelo en un txt, no en el mail, porque me lo modifica al código.

**Comment by mkreyness** [comment]
Lo estas usando DENTRO de la pagina del juego ? Porque si no no tiene el contexto de las FlashVars, lo que yo deje puesto estaba andando bien, sumaba los puntos (hasta 75) y despues volvias a poder jugar.

**Comment by LeandroBraier** [comment]
Fede, mientras espero que vuelva MK, te paso el thumbnail para que lo subas a /img/

![thumbnail-busca-klaukol](https://cloud.githubusercontent.com/assets/6719872/8756916/57fa9e18-2cac-11e5-8b24-b8b1878c6523.jpg)

Avisame cuando está subido porfa.

abrazo

**Comment by FAAREIA** [comment]
La imagen tiene que ir dentro de flash.

**Comment by LeandroBraier** [comment]
Fede, este thumbnail para el listado de temas, no para la página del juego mismo. Fijate, ese no va en el flash.

**Comment by LeandroBraier** [comment]
Fede, te mando por mail el link del slide del juego, con las variables correctas.

abrazo

**Comment by mkreyness** [comment]
Ya subi yo la imagen, no podia aguantar ver el simbolo de link roto !

**Comment by LeandroBraier** [comment]
jaja Gracias!

**Comment by mkreyness** [comment]
Tambien esta puesto que hasta que completes los 100 puntos NO diga "jugado".
A nivel TEMAS se me complica porque existen casos (como el KIP) que haber ganado menos puntos que el maximo igual te inhabilita a jugar. Jode si lo dejo asi ? Si no tengo que dedicarle un rato a discriminar en la lista de temas de que tipo de juego se trata.

**Comment by mkreyness** [comment]
Habria que arreglar en el juego lo que pasa cuando llegas a CERO baldosas, se da vuelta a 4294 millones y por eso sigue dejar jugando.

**Comment by LeandroBraier** [comment]
Yo me ocupo de eso, Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 18:19 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Chicos, cierro el ticket. La semana que viene actualizamos el SWF cuando pueda corregir ese detalle.

abrazo
