### ISSUE TITLE
Bug de signos de preguntas en novedades

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#102]
http://www.parexklaukol.com.ar/novedades/como-mantener-un-ambiente-calido-durante-la-estacion-invernal.html

MK, te fijás qué puede estar pasando acá?

**Comment by mkreyness** [comment]
No veo ningun signo de pregunta, donde deberia estar ?

**Comment by LeandroBraier** [comment]
jaja no sé qué pasó. Ahora no están. Perdón, eran esos signos de errore de caracter, como cuando pones una ñ o algo asi.

lo debo haber corregido yo intentando emprolijar el html. Gracias!

abrazo
