### ISSUE TITLE
Modificaciones Newsletter Julio. 16/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#103]
@braulio-evangelisti , te paso capturas gráficas de los cambios que pidieron para este news. Son solo cuestiones de contenidos y detalles.
<img width="626" alt="captura de pantalla 2015-07-16 a la s 16 19 08" src="https://cloud.githubusercontent.com/assets/6719872/8732609/08da71c8-2bd5-11e5-9d1e-f5c43e45d27a.png">
<img width="724" alt="captura de pantalla 2015-07-16 a la s 16 19 12" src="https://cloud.githubusercontent.com/assets/6719872/8732611/0a6a4356-2bd5-11e5-8fae-c5a32f544a58.png">
<img width="723" alt="captura de pantalla 2015-07-16 a la s 16 19 25" src="https://cloud.githubusercontent.com/assets/6719872/8732612/0cf7f3de-2bd5-11e5-9de1-d504df808d55.png">
<img width="724" alt="captura de pantalla 2015-07-16 a la s 16 19 47" src="https://cloud.githubusercontent.com/assets/6719872/8732615/0f5f548c-2bd5-11e5-907c-02ce515f5487.png">

Confirmame si lo podés tener para hoy.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahora me pongo Lea, lo del logo de revear a que se refiere que quede igual a los demas?

**Comment by LeandroBraier** [comment]
Está más chiquito que los otros. Comparalo con el pie de este posteo:

![20-07-dia-del-amigo](https://cloud.githubusercontent.com/assets/6719872/8734619/9aaa11ce-2be1-11e5-9e68-323bce9369cf.png)

Te paso logos en alta por mail.

**Comment by braulio-evangelisti** [comment]
Perfecto

**Comment by braulio-evangelisti** [comment]
Lea, la mitad  o mas de los clientes de email mas usados no soporta fuentes customizadas. Tendria que pasar todo a imagen.

**Comment by LeandroBraier** [comment]
Ok, Brau. Modificá el resto de las cosas nomás. Consulto con el cliente por este tema.

**Comment by braulio-evangelisti** [comment]
Ademas del logo de revear mandame la foto de la mujer de por lo menos 640px de ancho que no esta en la novedad de la pagina

**Comment by LeandroBraier** [comment]
aqui va

https://cloud.githubusercontent.com/assets/6719872/8236032/02b4eca8-15bc-11e5-9493-e5429ffa12d7.png

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Obvio recortalo lo que sea necesario.

**Comment by braulio-evangelisti** [comment]
http://parexklaukol.com.ar/_mailing/novedades-julio/novedades-julio.html

Si mañana me pasas el logo de revear se lo agrego en mejor calidad, ahi le cambie el tamaño al que estaba.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias!

Pero te lo pasé por mail, no te llegó?

**Comment by LeandroBraier** [comment]
Confirmame si te llego. Te paso una foto para que cambies la foto de Capacitaciones ahora que nos cambiaron la provincia.

![foto-capacitaciones-tucuman](https://cloud.githubusercontent.com/assets/6719872/8738196/fd575e7e-2c01-11e5-878a-4f5afb8bdfff.png)

abrazo

**Comment by braulio-evangelisti** [comment]
Ahora la cambio. No el logo de Revear no me llego por mail.

**Comment by LeandroBraier** [comment]
Te lo volví a enviar. Confirmame si te llegó. Fue en esta misma cadena de mensajes pero directo a tu mail de gmail.

**Comment by braulio-evangelisti** [comment]
Llego perfecto :+1:

**Comment by LeandroBraier** [comment]
Genial. Te paso los links de las notas en el orden en que van:

http://www.parexklaukol.com.ar/novedades/como-mantener-un-ambiente-calido-durante-la-estacion-invernal.html

http://www.parexklaukol.com.ar/novedades/ahora-estamos-en-facebook.html

http://www.parexklaukol.com.ar/novedades/fachadas-en-un-solo-paso-con-parex-estilo-4d--un-mortero-monocapa-color.html

http://www.parexklaukol.com.ar/novedades/porcellanatos--diversidad-de-propuestas-para-lograr-ambientes-originales-y-calidos.html

El de las capacitaciones que lleve al Facebook directamente:

http://www.facebook.com/parexklaukolarg

abrazo

**Comment by LeandroBraier** [comment]
Braulio, un detalle. El logo de Club de Colocadores ponelo en gris, porque no está habilitado todavía. Ponelo en gris y sin link.

abrazo

**Comment by braulio-evangelisti** [comment]
Actualiza ahi y fijate si estan todos los cambios o se me paso algo por alto.

http://parexklaukol.com.ar/_mailing/novedades-julio/novedades-julio.html

Abrazo

**Comment by LeandroBraier** [comment]
Quedó perfecto Braulio! Gracias!

abrazo
