### ISSUE TITLE
Nuevos Slides en Slideshow y reordenamiento

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#104]
Fede, te paso dos slides nuevos y te los pongo en el orden en que irían en el slideshow:

1) Este lleva a la página del Juego

![slide-juego-final](https://cloud.githubusercontent.com/assets/6719872/8756273/7106f4e2-2ca7-11e5-8b8d-b710ef4ee3ed.png)

2) Slide del Premio

3) Sumar este, que va sin link

![slide-sumate-facebook](https://cloud.githubusercontent.com/assets/6719872/8756265/629ee680-2ca7-11e5-80c2-b0c134f201a4.png)

Los demás slides quedan ordenados así:

4) Trivia Porcellanato

5) Subi foto de tu corralon

6) Tu muro suma

7) Ganador de Junio

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias Fede!!!

abrazo
