### ISSUE TITLE
Agregado a la Página HTML del Juego BuscaKlaukol. FECHA: 20/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#105]
En vez de 1 solo Jugar x 100 puntos, que diga

Nivel Muy Fácil 
Jugar x 5 puntos

Nivel Fácil 
Jugar x 15 puntos

Nivel Moderado 
Jugar x 25 puntos

Nivel Difícil 
Jugar x 50 puntos

Esto para el lunes tranqui, sin apuro.

Aprovecho a preguntar aparte, hay forma de que la URL que registra los puntos redireccione al siguiente nivel? (Intuyo que no)

**Comment by LeandroBraier** [comment]
@FAAREIA no sé si esto te corresponde a vos o a Marce.

**Comment by FAAREIA** [comment]
@mkreyness

**Comment by mkreyness** [comment]
1) El texto habria que maquetarlo un poco distinto, tengo miedo de romperlo.
Fede podras en un template separado abrirme el icono de "Jugar por 100" en 4 iconos que queden bien ? Yo despues lo convierto en iterativo y lo paso al oficial ?

2) Se podria hacer que avance si tenes forma de tocar en el Actionscript que dependiendo de un parametro que yo le pase entre directamente a jugar a ese nivel, pero igual me parece mal, porque lo metes al tipo a jugar sin que el sepa, tendria que mostrarle mejor un cartel que diga "ganaste xx puntos en esta ronda, queres seguir por xx puntos mas ?". Y encima si el tipo entro jugando por el dificil, no tendria forma de sumar mas puntos.
Tampoco nada impide jugar 20 veces al de 5 puntos y asi hacer 100.

La otra seria (tocando bastante el actionscript) que el juego directamente (sin llamar al URL) avance y siga acumulando, y que recien al final de todo llame a mi URL con el total de bombas sumadas y en base a eso yo saber cuantos puntos ponerle (O mejor, que me pase los puntos en vez de las bombas).

**Comment by LeandroBraier** [comment]
1) Genial. Avisenme nomás cuando esté.

2) MK, vamos por la segunda opción, la que requiere tocar bastante el actionscript pero te envía el total de puntos recién al final, es decir, cuando el usuario ya ganó los 4 niveles o bien la primera vez que pierde, no?

Para hoy podrías corregir eso en el código? Yo en paralelo voy a estar investigando ese error en el Action Script que hablamos el viernes de limitar la cantidad de K que se pueden poner para corregirlo yo, pero necesitaría que vos me resuelvas esta otra parte. Me confirmás porfa?

**Comment by mkreyness** [comment]
Humm, no me termina de convencer: si pierde deberia poder volver a hacer el mismo nivel. Imaginate uno que empieza por el dificil. O no le dejariamos elegir ?
Y tambien puede pasar que alguien abandone (por ej, que cierre la pagina, aunque tenga puntos sumados sin acreditar), o que no quiera seguir jugando el siguiente nivel.
Me parece que se complicaria bastante el flujo.

**Comment by LeandroBraier** [comment]
Tenés razón. Cada vez que termina un nivel debería decirle "Ganaste x puntos", mandarlo a tu URL para sumarle los puntos y volver al nivel siguiente. Se puede eso?

**Comment by mkreyness** [comment]
Para eso justamente hay que implementar la primer opcion, ya que cada vez que "va y vuelve" vuelve a empezar el juego. Tendria que ver como hacer (si ya viniera como parametro) el maximo nivel ganado) que lo lleve directo a jugar ese nivel, pero por otra parte, deberia empezar siempre por el nivel 1, porque si no se va a perder de sumar esos puntos.
No creo que pueda resolver bien todo esto hoy, ni siquiera se como mostrar el cartel de "ganaste x puntos".

**Comment by LeandroBraier** [comment]
Ok, para mañana puede ser?

**Comment by mkreyness** [comment]
Supongo que si. Mañana ES el gran dia (despues de tomar 3 semanas de antibioticos) que por fin me sacan el diente maldito.

**Comment by LeandroBraier** [comment]
Crucemos los dedos y no los dientes MK!!! Fuerza!! abrazo

**Comment by LeandroBraier** [comment]
La parte 1 también está para mañana?

**Comment by mkreyness** [comment]
Dependo de Fede, pero es muy simple eso, si.

**Comment by FAAREIA** [comment]
Hola @mkreyness , ahi ya actualicé lo necesario. Lo que restaría es que en el loop que hagas pongas en vez del tradicional "VIDEO +20":

Muy Fácil +5

Fácil `<br>`+15  (aca va el BR sino queda mal. Podes ponerle el `<br>` a todos si queres)

Moderado +25

Difícil +50

**Comment by LeandroBraier** [comment]
Gracias Fede! Avisen cuando esté final.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ok ahora estoy yendo al dentista, cuando vuelvo lo resuelvo (me salio en versito)

Enviado desde mi iPhone

**Comment by mkreyness** [comment]
Listo lo de los textos, quedo medio chancho porque es algo particular de este juego. Si aparecen mas juegos con esta escala de puntos lo voy a tener que generalizar en el CMS de alguna manera.

Lo de que el juego arranque en un segmento determinado ya lo tengo listo a nivel SWF, pero tengo que hacer lo correspondiente en la pagina para que le cambie los flashvars.
Ojo que mi compilacion como siempre sale horrible asi que te voy a pasar por mail Lean los cambios en el codigo para que lo compiles vos.

**Comment by mkreyness** [comment]
Ya quedo implementado en la pagina, le agrega el parametro "empezar" que depende de cuanto fue el maximo de puntos que saco en este juego hasta ahora (le pone el nivel siguiente, salvo que haya llegado a hacer el de 50, que vuelvo al nivel de 50 pero igual nunca le suma mas de 100 en total y se desactiva despues.

**Comment by mkreyness** [comment]
Lo que falta es que compiles con lo que te mande y me lo mandes para reemplazar el swf.

**Comment by LeandroBraier** [comment]
Gracias MK! Consulta: podrás revisar los otros dos temas en el código? porque estoy con mil cosas y aún no lo pude revisar. Serían:

1) Limitar la cantidad de K en cada nivel

2) Chequear que siempre que diga que hay 3 K alrededor sea efectivamente así. Algunos usuarios dicen que en los dos niveles más dificiles a veces dice que hay 3 y resultan haber 4.

Confirmame, sino lo reviso yo más tarde.

abrazo

**Comment by mkreyness** [comment]
Ah, a esto te referias, no lo habia visto.
Mira, a mi tambien me parece que varias cosas del juego andan mal, por ejemplo a veces toco una "bomba K" sin haber prendido el icono de arriba y no explota.
Voy a tratar de resolver primero el tema ese que se da vuelta la cuenta y se pasa a 4000 millones, porque es demasiado evidente. 
Lo del 2) me parece que va a ser muy dificil de debuggear, despues te digo.

**Comment by LeandroBraier** [comment]
Gracias MK! Esto es prioridad frente a lo demas. Abrazo

**Comment by mkreyness** [comment]
Creo que ya lo tengo resuelto pero lamentablemente no lo puedo probar. Como en mi compilacion saltan esos errores por variables no definidas de tiempo y cantidad de bombas (que son justamente las que se muestran en pantalla, pero no se como se hace para darles ese nombre.
Te mando por mail el cambio.

**Comment by LeandroBraier** [comment]
Genial, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-21 16:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No te garantizo que ande, pero es logico no seguir restando si ya llego a 0

**Comment by LeandroBraier** [comment]
@mkreyness la verdad no queda prolijo así. No se puede poner cada nivel como un elemento distinto y que por eso cada uno sume puntos distintos?

**Comment by mkreyness** [comment]
Estamos hablando de la lista de puntajes ?
A mi tambien me parece feo, pero capaz entendi mal lo que dijo Fede (de ponerle brs).
Ahora te lo cambio a que sea una lista, HORIZONTAL

**Comment by mkreyness** [comment]
No entran bien las 4, fijate con este link (no esta en produccion esto)

http://www.parexklaukol.com.ar/cgi-bin/jugar2.pl?usuario=marcelokreyness&clave=pepe&id=6

**Comment by LeandroBraier** [comment]
Exacto, a eso me refería. Hagamos una segunda línea entonces aunque quede
con un solo nivel, no hay problema.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-21 18:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Creo que quedan mejor 2 y 2, fijate ahora. Lo que no logro es que se separen lo suficiente, estas cosas las tiene que tocar Fede en realidad.
http://www.parexklaukol.com.ar/cgi-bin/jugar2.pl?usuario=marcelokreyness&clave=pepe&id=6

**Comment by LeandroBraier** [comment]
Entiendo. Mañana Fede acomoda eso. Tené en cuenta igual que vamos a agregar un pequeño PDF en instructivo de como jugar (lo pidió el cliente).

Esto va a ser mañana calculo.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA cuando puedas no te olvides de acomodar eso. abrazo

**Comment by mkreyness** [comment]
Ojo que el template es GENERICO para "cualquier" juego, no habria que poner nada fijo, sino una variable que tendria que llenarse desde el CMS.
Fede: la separacion entre lineas yo ahora la estoy forzando POR PROGRAMA metiendo un /ul para cerrar y otro ul para abrir. Yo por ahora lo saco (o sea que quedan las 4 en una linea) para que quede todo en un solo nivel y vos lo acomodes desde CSS.

**Comment by mkreyness** [comment]
Y velo con este link que no esta en produccion:
http://www.parexklaukol.com.ar/cgi-bin/jugar2.pl?usuario=marcelokreyness&clave=pepe&id=6
Cuando se vea bien avisame y lo paso a produccion (que lo que hay es un asco).

**Comment by FAAREIA** [comment]
Lo que falta para los 4 esten en 1 linea es que el tag del LI cierre pegado al otro, ahora cada uno abre y cierre en su propia línea.
@mkreyness

**Comment by mkreyness** [comment]
Listo, se ve bien todo en una linea ahora.
Lo paso a produccion.

**Comment by LeandroBraier** [comment]
Gracias a los dos!!! Buen trabajo ahí! Cuando tengo el PDF con el instructivo se los paso

abrazo
