### ISSUE TITLE
Editor HTML Novedades KLAUKOL. 23/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#106]
MK, para el Jueves que viene podríamos tener un editor HTML como los que hay en los programas de mail para editar las notas de novedades de Klaukol?

**Comment by LeandroBraier** [comment]
MK, subí el que me dijiste que ya tenías puesto para Cadena de Mails porfa.

abrazo

**Comment by mkreyness** [comment]
Lo tengo que "integrar" mas que subir. Ok.

**Comment by mkreyness** [comment]
Me recordas como accedian para ingresar lo de la Cadena de Mails ? Lo estoy buscando y no lo encuentro.

**Comment by LeandroBraier** [comment]
Aqui va:

Paso 1) Ingresá a http://www.benteveo.tv/cgi-bin/cms.pl

Paso 2) Logeate como _admin_ y la contraseña _benteveo_.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Claro, eso estoy haciendo, pero ya no tiene el editor HTML, fijate que hay un campo HTML que no hace nada.
En algun cambio de algo parece que eso se pisó. No te preocupes, busco en mis backups.

**Comment by LeandroBraier** [comment]
Genial. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-25 22:02 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, fijate como lo ves. Acordate que el HTML esta en una segunda solapa (y se genera automaticamente en base a cambios de los datos de la primera solapa, pero lo pueden customizar en la segunda.

**Comment by LeandroBraier** [comment]
Buenisimo MK! Lo veo bien, tendríamos que probarlo por las dudas, vos lo
probaste?

Consulta: no hay posibilidad de sumar opción para modificar Color del
Texto? Eso sería buenisimo

**Comment by mkreyness** [comment]
No quise crear una novedad nueva (valga la redundancia) porque saldria publicada, hay que probarlo cuando haya algo nuevo para poner, pero en definitiva lo unico que hace es editar HTML, no agrega nada raro.
El tema del color parece que esta version del CKEditor (gratuita) no lo incluye. Hay una version full que no se bien si hay que pagarla o que. Voy a ver si se puede bajar una version por tiempo limitado y vemos.

**Comment by mkreyness** [comment]
Listo el color, la version full tambien es gratis.

**Comment by mkreyness** [comment]
dale F5 si tenias algo abierto.

**Comment by LeandroBraier** [comment]
Che, le di F5 y ahora no me aparece nada en el modo HTML. Qué pasó?

<img width="1334" alt="captura de pantalla 2015-08-26 a la s 09 53 47" src="https://cloud.githubusercontent.com/assets/6719872/9493519/9916e7a0-4bd6-11e5-9b97-0ab25bb53646.png">

**Comment by mkreyness** [comment]
a mi me anda bien, con colores, etc.
Hace control F5 o cerra/borra cache, te debe haber quedado cacheada la version vieja del plugin.

**Comment by mkreyness** [comment]
![foto-con-html](https://cloud.githubusercontent.com/assets/6135791/9493608/2a752176-4bd7-11e5-8df6-9ed142640efc.JPG)

**Comment by LeandroBraier** [comment]
Es cierto, funciona. Yo estaba buscando en notas viejas que quizá no tienen generado el HTML, no?

Genial entonces, gracias!

**Comment by mkreyness** [comment]
Ah, eso puede ser.
