### ISSUE TITLE
CMS Slideshow Vendedores. 24/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#107]
Marce, para el viernes que viene lo podremos tener activado? Asi no lo jodo a Fede con el reordenamiento y la subida de nuevos slides cada viernes.

abrazo

**Comment by mkreyness** [comment]
Si, seguro.

**Comment by LeandroBraier** [comment]
Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Listo, todavia no esta en produccion, pero podes acceder via CMS (esta en el menu de Vendedores) y podes mirar sus efectos aca:

http://www.parexklaukol.com.ar/cgi-bin/mainvendedores2.pl

(o loggeandote con un usuario y cambiando mainvendedores.pl por mainvendedores2.pl

Confirmame que ves todo bien, proba de agregar un slide con una foto cualquiera, despues lo despublicamos y cuando vos me digas lo paso a produccion.

**Comment by LeandroBraier** [comment]
Quedó perfecto Marce! gracias! Lo único que no me funciona es el link. FIjate que probé con la trivia vieja, pero no funca puede ser?

**Comment by LeandroBraier** [comment]
También estaría bueno si puedo cargar yo mismo los thumbnails, así no los tengo que molestar también por eso. Lo podrás agregar?

**Comment by mkreyness** [comment]
Es porque no le pusiste las variables de usuario y clave en el URL. Fijate como lo cambie, dejandolo como los otros que tienen link (en el listado no se ven porque justamente son comentarios html)

Que thumbnails no podes cargar ? No deberia haber ninguno que no este en el CMS.

**Comment by LeandroBraier** [comment]
El thumbnail de cada tema en el listado.

**Comment by LeandroBraier** [comment]
Perfecto lo demás, ahora entendí porque no funcionaba. Lo dejo suspendido hasta el viernes.

Espero lo del thumbnail mañana sin apuro, todo bien.

abrazo

**Comment by mkreyness** [comment]
Esta como URLs, el tema es que cada URL apunta a un lugar diferente.
Para manejarlo por CMS tendria que moverlas todas a una sola carpeta y a partir de ahi puedo "dejarte subirlas".

**Comment by LeandroBraier** [comment]
Ok. Se puede? Yo para no molestarlos a uds por estas pavadas.

**Comment by mkreyness** [comment]
Si, copio los thumbnails de los videos a la misma carpeta de imagenes (con distintos nombres, porque ahora ambos se llaman hqdefault creo), y lo convierto.
Te aviso despues.

**Comment by LeandroBraier** [comment]
Dale, no hay apuro, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-22 22:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
MK, mañana a la mañana podré tener donde cargar esos thumbnails?

**Comment by LeandroBraier** [comment]
MK, necesito que lo pases a producción. Ya publiqué La Trivia de hoy y el slide. Subilo. Los thumbnails se los paso a Fede por ticket mientras tanto. URGENTE porfa.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness te queda pendiente solo el tema de los thumbnails. Puede ser para el lunes o martes muuuy tranqui.

abrazo

**Comment by LeandroBraier** [comment]
MK, la prioridad mañana es habilitarme la posibilidad de subir thumbnails e imágenes varias a las carpetas /vendedores/img/temas/ y /vendedores/img/

Por ejemplo, esta semana necesito subir una Trivia llamada Trivia de Novedades Facebook Julio, la cual lleva imagen en lugar de video y no sé donde subirla.

![imagen-preview-trivia-novedades-facebook](https://cloud.githubusercontent.com/assets/6719872/8948336/7cd5fc72-357c-11e5-8959-b90ac0638d8b.png)

abrazo

**Comment by mkreyness** [comment]
Es lo que ya habiamos hablado de unificar lo que ahora esta disperso (incluyendo posters de youtube) y se administra como URLs en la parte de TEMAS ?
Yo diria que usemos una unica carpeta para todo lo que tenga que ver con temas, que sea "vendedores/img/temas". Para que necesitarias subir cosas a vendedores/img ?
Los sildes van todo a vendedores/img/premios (aunque no siempre sean premios).

**Comment by LeandroBraier** [comment]
Claro, a eso me refería, a tener acceso a subir fotos como thumbnails y como imagen de tema.

Eso sería prioridad porque esta semana tengo mucho para subir y lo tengo que subir mañana misma

abrazo y buenas noches!

**Comment by mkreyness** [comment]
Con los thumbnails no hay problema, pero hay una mezcolanza de videos e imagenes en lo que se muestra dentro del tema que voy a tener que separar en campos separados porque no vas a uploadear videos, y eso implica no solo tocar el CMS sino el sitio. Voy empezando con los thumbnails para que puedas ir cargando.

**Comment by mkreyness** [comment]
Bueno listo, entonces en el campo VIDEO solamente van realmente videos y eventualmente algun .swf , que tiene que cargarse a mano. O podemos mejorar eso con un poco de tiempo (porque si lo pongo que lo subas como imagen el CMS no sabe como mostrarlo).
Separe un campo de THUMBNAIL y otro de IMAGEN.
El de IMAGEN es el que va en los temas que no tienen video (como los de trabajabilidad y seguiridad).
El THUMBNAIL siempre va  para la lista de temas que se muestra al entrar en "empeza a jugar aca".

**Comment by LeandroBraier** [comment]
Muchas gracias MK!! Cierro este ticket ya entonces.

abrazo
