### ISSUE TITLE
Torneo de Potenciados #5 Bugs finales 20/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#108]
1) Resolvamos el lunes qué pasa en esa barra del mes cuando se supera el 100% como ocurre en este caso:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=materiales-pedraza1311&clave=125745&torneo=1&tipo=C

2) Falta que las barras y velocímetros de los corredores funcionen:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=JavierVasquez&clave=111281&torneo=1&tipo=C

Con eso ya practicamente quedaría cerrado Torneo de Potenciados.

abrazo

**Comment by mkreyness** [comment]
```
2) esta lleno de datos truchos fijos, antes todo eso estaba en
variables, pero habran sido pisadas.
Lo reviso con cuidado mañana.

Ojo, esta mal pasar tipo=C para corredores. Ahi era tipo=R, igual
eso ya no se usa, sale automatico del codigo de usario.

El 17/07/2015 a las 21:17,
  LeandroBraier escribió:


  1) Resolvamos el lunes qué pasa en esa barra del mes cuando se
    supera el 100% como ocurre en este caso:
  http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=materiales-pedraza1311&clave=125745&torneo=1&tipo=C
  2) Falta que las barras y velocímetros de los corredores
    funcionen:
  http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=JavierVasquez&clave=111281&torneo=1&tipo=C
  Con eso ya practicamente quedaría cerrado Torneo de
    Potenciados.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Claro, no le den bola a eso que es un link que armé yo rápido.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 22:02 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ahi hice los ajustes para que los datos salgan bien, pero en el caso de este Vazquez tiene todo en cero.

Fijate con este Nicolas Sale, que hace honor a su apellido y algo vende:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=NicolasSale&clave=123001&torneo=1

Hay cosas feas, me parece que hay que achicar el font del numero de puesto porque PUEDEN aparecer cosas en puestos de 3 (o 4!) cifras.
Me parece que habria que poner los puntos, porque los porcentajes son tan chicos que no dicen nada.
Esto esta ordenado por PORCENTAJE descendente, y dentro de igual porcentaje, por puntaje descendente.
El tema es que (segun aparentemente pidieron) se mezclan las categorias, pero como el PUESTO depende de la categoria, entonces se ven desordenados los puestos.

**Comment by LeandroBraier** [comment]
Buenisimo. Ahora se ve más real, si. Lo de los puestos dejemoslo así por ahora, no me parece mal.

Ahora lo que no entiendo es por qué no funciona el velocimetro. El -76% tiene la aguja en el mismo lugar que el -100%. No?

<img width="133" alt="captura de pantalla 2015-07-18 a la s 11 33 26" src="https://cloud.githubusercontent.com/assets/6719872/8761915/5b5ed144-2d3f-11e5-8a89-e768133ceda0.png">

**Comment by mkreyness** [comment]
Si porque son apenas 5 grados reales en el velocimetro de Fede, por mucho que tenga 20 rayitas.
Los posibles son: -2, -1, 0, 1, 2, correspondientes a:
-67% o menos
entre -66% y -34%
entre -33% y 33%
entre 34% y 66%
67% o mas

**Comment by LeandroBraier** [comment]
Ah, ok. Perfecto. Si el cliente pregunta le explico eso, todo bien.

Lo que no entiendo es, si bien están mezcladas las categorías, porqué aparecen desordenados los puestos. No sería mejor que viera solo los puestos que están en el top 10?

**Comment by mkreyness** [comment]
Viste que no se entiende ? Por eso digo que si se vieran los puntos capaz se entenderia mejor, porque se veria que a igual porcentaje, son descendentes (ninguno llega al 0.1%, por eso todos salen como 0.0%).

Lo que se muestra son siempre los distribuidores del PROPIO CORREDOR, o sea, son los top 10 PORCENTAJES, de cualquier categoria.  Eso no significa que entren en el "top 10" de cada categoria, son los top 10 del corredor.

Lo que se ve arriba es LO MISMO que se ve abajo, tal como en algun momento definieron que fuera, lo cual tampoco para mi tiene mucho sentido.

**Comment by LeandroBraier** [comment]
Ahhhhh. OJo, porque en realidad lo que necesitamos es que el corredor vea en qué puesto de Cada Categoría está Cada Corralón. Eso es lo que le sirve. Porque si es el nº1 de su top 10 va a pensar que ganó, pero quizá en su categoría es el número 2 y no gana nada, entendés?

Habría que corregirlo a eso. Que ponga el puesto en que está cada corralón en su propia categoría, esto tanto en la Tabla de Posiciones como en Tus ventas. Ahi no creo que sean números de 4 cifras seguro.

Respecto de mostrar puntos o porcentajes me parece agregaría los Puntos Obtenidos pero en la Tabla de Ventas. Qué decís?

**Comment by mkreyness** [comment]
El "puesto" es exactamente eso que decis. El lugar que ocupan los corralones dentro de sus propias categorias, pero solo muestro aquellos corralones que le son PROPIOS, no muestro corralones ajenos.
Recapitulando: muestro los MEJORES 10 CORRALONES QUE TIENE, ordenados por porcentaje descendente, y muestro cada uno de ellos en QUE PUESTO ESTA de la categoria correspondiente.

Exactamente por eso es que se ve DESORDENADO por puesto, porque esta ordenado por PORCENTAJE, y cada porcentaje representa un numero puesto diferente DENTRO de su categoria.
Lo que es seguro que si te figura en tu top 10 algo que esta en puesto 100 es porque NO TENES nada mejor en esa categoria.

Puntos: Claro, yo digo ponerlos al lado del objetivo, y el objetivo se muestra en la tabla de ventas.

**Comment by FAAREIA** [comment]
Ya esta corregido el tema de puestos de 3 o 4 digitos, achiqué la tipgrafía y la comprimí en el interletrado.

**Comment by LeandroBraier** [comment]
Gracias Fede! Hecho entonces, no?
