### ISSUE TITLE
Posible Bug en puntos del Juego Flash Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#109]
@mkreyness puede ser que el filtro de no poder sumar varias veces por el mismo nivel no esté funcionando? Estoy viendo varios casos como este:

<img width="1403" alt="captura de pantalla 2015-07-20 a la s 14 59 22" src="https://cloud.githubusercontent.com/assets/6719872/8782853/77bc746c-2eee-11e5-9d56-eba1a0f28212.png">

**Comment by mkreyness** [comment]
Nunca existio tal filtro, la unica condicion es que no se pase de 100 el 
total, por lo tanto si quiere puede jugar 20 veces al mismo nivel.
Si hubiera puesto un filtro por cada puntaje, no hubiera sido necesario 
el control por total, era mas facil.

**Comment by LeandroBraier** [comment]
OK, dejemoslo así por ahora entonces. No había entendido que era así, pero es más democrático. Dejemoslo así, cualquier cosa te aviso.

abrazo
