### ISSUE TITLE
Backup Sitios Paraguay y Uruguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#11]
Fede, necesito que vayas bajandote toda la info de estos dos sitios antes que ellos lo migren todo a nuestro servidor, por las dudas. Confirmame porfa apenas lo tengas backupeado.

http://www.parexuruguay.com.uy/
http://www.parexparaguay.com.py/

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, el backup ya nos los mandaron ellos. Es lo que bajé hace 1 semana.
Si me bajo lo que hay online, quedaría un sitio HTML estático, sin base de datos ni programación alguna.

**Comment by LeandroBraier** [comment]
Entiendo. Me que3do tranqui entonces. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-25 10:42 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, para ir ganando tiempo, pensemos que seguramente nos van a pedir que armemos los sitios a mano con lo que podemos tomar del Front. Vamos a tener tiempo, pero vamos a necesitar tener algo que subir el miércoles, por más que aún no esté todo el sitio. Todo lo que puedas avanzar en cuanto a estos sitios de Paraguay, Uruguay, Revear, todos haganlo. Me refiero a ir bajando el material, organizándolo y demás, para meterlo en la maqueta que ya armamos. Es muy probable que no nos den más materiales que los que tenemos del sitio. El proveedor anterior es un estafador.

abrazo

**Comment by FAAREIA** [comment]
Ok perfecto Lea. Sumo a MK al issue.

**Comment by LeandroBraier** [comment]
Genial, gracias!

Seguramente hoy durante el día nos confirmen qué hacer con esto. Lo que
creo es que vamos a tener que pensar una forma elegante de tener algo listo
y subido el miércoles, que parezca que el sitio está renovado y haya cierto
nivel de contenidos pero obviamente no va a estar TOOOODO el sitio subido,
eso ya lo sé. Yo ya me preparo para laburar el finde. Confirmenme si uds
pueden. Obviamente si después Fede necesitás que te dejemos libre algun
otro dia por compensación no hay problema, pero estas son fechas críticas
en el tema Klaukol.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
No obvio, es imposible tener todo subido. Lo que se puede hacer para safarla, mientras se labura en serio, es bajar el HTML completo y visualmente el cliente va a ver lo mismo que antes pero estático, sin funcionamiento.

**Comment by LeandroBraier** [comment]
Exacto. Vayamos haciendo eso Fede, me parece buena alternativa. Pensá que
son 7:
1. Home ParexKlaukol
2. Klaukol
3. Parex
4. Lanko
5. Revear
6. Home ParexKlaukol Paraguay
7. Home ParexKlaukol Uruguay

Estaría genial tener los HTML bajados para que se vea algo, aunque sea
estático, con el video nuevo corriendo y la nueva hoja de estilos. Con eso
ya se va a ver algo diferente.

De los temas de tiempos de delegación del dominio ya me ocupo yo, pero me
parece que el deadline para hacer la delegación del dominio sería este
domingo 12/04 a la noche si ellos quisieron tener el miércoles 15/04 todo
online, verdad?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-09 10:59 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Asi es, son 48hs para que se propague al 100%.
Mañana habría que analizar si los sitios de uruguay y paraguay tienen algo diferente al original.

**Comment by LeandroBraier** [comment]
Dale, hagamos eso mañana.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
