### ISSUE TITLE
Thumbnails Sitio ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#110]
@braulio-evangelisti Estamos intentando publicar los links de noticias en Facebook pero no se cargan thumbnails al ingresar las URLs. 

Esta herramienta devuelve un análisis de lo que Facebook levanta de las mismas. 

https://developers.facebook.com/tools/debug/og/object/

Con esta información habría que revisar el código y encontrar una solución para que Facebook reconozca las imágenes al publicar el link en la página de ParexKlaukol.

**Comment by braulio-evangelisti** [comment]
@mkreyness como puedo hacer para recuperar la url completa de la imagen de la novedad en el template novedad.html? probe  y no imprime nada,  imprime solo la imagen, y por lo que vi en la ruta varia segun localidad ...wyg/**Noticias-AR**/IMG...

**Comment by mkreyness** [comment]
No vas a poder desde el template, tenes que agarrar una novedad real (del sitio real) y ahi vas a ver el path completo. Los comentarios estos son reemplazados por un programa cuando generan las paginas reales.

**Comment by mkreyness** [comment]
Cada pais tiene una carpeta separada (todo horrible porque lo tomamos tal cual vino del backup)

**Comment by braulio-evangelisti** [comment]
Lea ya estaria esto, no se cuanto tiempo tarda facebook en renovar la informacion que tiene relacionada a cada link, si no cambia voy a tener que darle al boton de traer nueva informacion en el debugger a cada novedad por separado

**Comment by LeandroBraier** [comment]
Gracias Braulio! No hace falta. Cuando se actualice lo tneemos Cualquier cosa te aviso.

abrazo grande

**Comment by LeandroBraier** [comment]
Braulio, te fijarías por qué puede ser que las novedades siguientes no tengan el thumbnail en el debugger?

http://www.parexklaukol.com.ar/novedades/fachadas-en-un-solo-paso-con-parex-estilo-4d--un-mortero-monocapa-color.html
http://www.parexklaukol.com.ar/novedades/porcellanatos--diversidad-de-propuestas-para-lograr-ambientes-originales-y-calidos.html

**Comment by braulio-evangelisti** [comment]
La de "fachadas" segun el debugger es porque el nombre de archivo del thumbnail de la novedad tiene espacios, se llama **0108 casa multi.jpg**

> URL 'http://www.parexklaukol.com.ar/media/wysiwyg/Noticias-AR/0108 casa multi.jpg' for property 'og:image:url' of the object at 'http://www.parexklaukol.com.ar/novedades/fachadas-en-un-solo-paso-con-parex-estilo-4d--un-mortero-monocapa-color.html' is invalid because it contains whitespace characters.

La de "porcelanatos" ya la agregue.

Nose porque no tenian las etiquetas ambos archivos y el resto si. No conozco en profundidad como funciona el cms, capas le puedo pasar los tag al programador o que me oriente un poco a ver si los puse donde iban.

**Comment by LeandroBraier** [comment]
Ok, fijate entonces de subir siempre las imagenes sin espacios por las
dudas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-22 18:01 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
No las subi yo, es el contenido que esta cargado en el sitio de cada nota.

**Comment by mkreyness** [comment]
Son las cosas que vinieron de los backups.

**Comment by LeandroBraier** [comment]
Se puede corregir eso automáticamente? Reemplazando los espacios por
guiones x ejemplo ?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Lo correcto (para no tener que andar renombrando cientos de archivos sueltos y tener que tocar todo en el CMS) es reemplazar los blancos por "%20".
No entiendo cual es el procedimiento por el cual estan haciendo esto. Las paginas de novedades se regeneran automaticamente todo el tiempo en base a lo que esta en el CMS. Esto de los og: esta puesto como variables ? Puedo hacer que se reemplacen los blancos por "%20" en el programa que las produce y listo.

**Comment by LeandroBraier** [comment]
Dale, hagamos eso.

Lo estamos haciendo para que Facebook levante las imagenes como thumbnails.
Parece que no lo hace cuando el nombre del archivo tiene espacios.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-22 19:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
listo pero ojo que esa pagina que estan mirando esta mal y no se va a regenerar, porque hubo un cambio en el titulo (se saco un blanco de mas o algo asi) y ahora el URL es asi:
http://www.parexklaukol.com.ar/novedades/fachadas-en-un-solo-paso-con-parex-estilo-4d-un-mortero-monocapa-color.html
o sea donde habia dos guiones va uno solo.

**Comment by LeandroBraier** [comment]
Marce, ese link ya salió en el newsletter del mes, no podemos cambiarlo. No podés restituirle el nombre al anterior?
