### ISSUE TITLE
URL interna para mostrar juegos al interior de la empresa 21/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#112]
Chicos, necesitamos subir el Juego BuscaKlaukol a una URL como esta:

www.parexklaukol.com.ar/juegos-vendedores/

Que esté montada minimamente sobre la misma estética del sitio web de la marca pero no aparezca linkeada en ningun lado. Es solo para uso interno, para que el cliente se lo muestre al resto de la empresa y todos lo puedan jugar, sin sumar puntos claro.

abrazo

**Comment by mkreyness** [comment]
@braulio-evangelisti hacete un view source de esto

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?usuario=marcelokreyness&clave=pepe&id=6

y fijate como aparece aca el HTML que circunda al SWF y metelo en un HTML (avisame como se llama)

Yo despues le cambio el contenido a las FlashVars para que al terminar de jugar vuelva a entrar a la misma pagina.

**Comment by braulio-evangelisti** [comment]
Subi un index a la direccion que tiro Lea.

http://www.parexklaukol.com.ar/juegos-vendedores/

Abrazo

**Comment by mkreyness** [comment]
Ok, ahora le saco de FlashVars todo lo que sobra porque si no cuando ganas me suma puntos a mi :)

**Comment by LeandroBraier** [comment]
Excelente Braulio! Gracias MK!

Cuando actualices el otro SWF actualizá este también porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness cuando quede final el SWF actualizalo acá también porfa.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness probé el juego en este link:

http://www.parexklaukol.com.ar/juegos-vendedores/

Y nunca me muestra el mensaje de Ganaste. Yo ya gané y el juego se queda ahí, no termina. Me parece que tiene que ver con que ahi no suma puntos entonces habría que quitarle una parte del código. Cuando puedas decime cuál sería porfa.

abrazo

**Comment by mkreyness** [comment]
Te da un error porque la variable "empezar" en ese caso no existe, es a proposito porque si no te obligaria siempre a jugar el mismo nivel. Entonces no pasa por ninguno de los 4 casos.
Yo diria que en ifwin, despues de hacer:

var empezar:Object=this.root.loaderInfo.parameters.empezar;

y antes del "switch" agregues

if (empezar != null) {

y lo cierres despues de que termina el "switch", porque el empezar.toString() da error cuando empezar es null.
Y en realidad para que muestre ALGO antes de volver a empezar, tendria que tener tambien

else
    {
    // lo que hacia inicialmente con el winTXT que solo dice "GANASTE".
    }

**Comment by LeandroBraier** [comment]
Gracias MK! Este else donde iría?

**Comment by mkreyness** [comment]
despues del cierre que haces del if (empezar != null), resumiendo:

if (empezar != null)
    {
   switch(...)
      {
      case (...):
      break ;
      case (...):
      break ; 
      ....
      }
   }
else
  {
  // GANASTE
  }

**Comment by LeandroBraier** [comment]
Perfecto. Hecho!

Ahi te paso el SWF por mail. Vas a reemplazar los dos o solo el de esta URL?

**Comment by mkreyness** [comment]
los dos, tratemos de tener solo una version del programa, deberian ser compatibles.

**Comment by LeandroBraier** [comment]
Perfecto. Ahi te mandé. Avisame cuando esté final.

abrazo

**Comment by mkreyness** [comment]
Ahi lo subi a produccion, yo me estoy yendo y vuelvo despues del mediodia, probalo que ande bien.

**Comment by LeandroBraier** [comment]
Parece funcionar bien. En los niveles dificiles hay incoherencias propias del juego que vamos a tener que revisar más adelante si el cliente las ve pero me parece que no valen la pena, ya surgirá.abrazo y gracias MK!
