### ISSUE TITLE
Newsletter Benteveo de Agosto. 22/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#113]
@braulio-evangelisti necesito darle contenido al newsletter de Benteveo que ya tenemos diseñado.

El diseño es este:

http://www.benteveo.tv/mailing/benteveo-tv/benteveo-tv.html

Lo que necesito es subirle estas 3 notas con 2 GIFs animados y una imagen que figuran acá:

https://docs.google.com/document/d/1rtHpCOUQpuRRR5ywEn9M2YPHptLJdvIPBp_z5ahuv3Q/edit

Los links no están todavía, cuando los tengo te los paso.

Los dos GIF y la imagen fija, necesito que los recortes circularmente como en el template. Vas a tener que retocar un poco. Si necesitás los archivos originales o algo avisame. 

abrazo

**Comment by braulio-evangelisti** [comment]
Lea si, si tenes los originales de las imagenes/gifs pasamelos.

En cada artículo tiene un boton de leer mas la maqueta y los textos tienen al final links "haciendo click aquí", como lo queres resolver a eso?

**Comment by LeandroBraier** [comment]
Dale Brau. Al mediodia te puedo pasar eso. Respecto del texto nuestro frente a botón de Leer más gana el botón ya diseñado.

Me olvidé de pedirte una cosa mas. Al pie de las 3 notas necesitaria que haya otro botón circular que diga Vuela! con el logo de Benteveo

Lo podes ver al final del video de autoplay que hay en la home de la web de Benteveo.

**Comment by braulio-evangelisti** [comment]
Fijate ahí el botón de btv al final. No lo hice mas grande para no superar en jerarquía al contenido.

http://www.benteveo.tv/mailing/benteveo-tv/

Cuando me mandes las imágenes las agrego.

Abrazo

**Comment by LeandroBraier** [comment]
Ahi te estoy mandando por wetransfer las imágenes.

El botón de vuela agrandalo. Que no supere pero iguale en jerarquí a las imágenes. De hecho los círculos de las imagenes hacelos más grandes también, porque sino por el círculo va a quedar mucho afuera.

abrazo

**Comment by LeandroBraier** [comment]
Ya se enviaron las imágenes:

https://www.wetransfer.com/downloads/5147de8c5ef637f2671ff8c66e82cd0e20150722155049/2ac318

**Comment by braulio-evangelisti** [comment]
Buen día Lea

Fijate ahora
http://www.benteveo.tv/mailing/benteveo-tv/

Me llevo mucho tiempo enmascarar los gif en circulos, redimensionar todo y comprimirlos un toque para que no pesen tanto. La tercer imagen es en la mejor calidad que la consegui, la que me pasaste por el doc de google era mas chica y no encontre como descargarlas desde ahi tampoco.

No encontre el logo de benteveo en mas tamaño que 10x10 sin la palabra Benteveo abajo para el boton de "Vuela!", el que habia usado antes era el favicon del sitio. Si me pasas el pajaro solo lo reemplazo.

Abrazo

**Comment by LeandroBraier** [comment]
Buen día Brau!

Pasame por wetransfer los PSD de esos gifs adaptados por vos y te los reduzco más. Yo le sacó uno de cada dos frames, para que se reproduzca más rápido y pese menos. Pasamelos y yo lo hago nomás. El recorte quedó muy bien, excelente te diría.

Respecto de la foto de la campaña usá esta mejor que está en mejor calidad.

http://www.godsavethebrief.com/wp-content/uploads/2015/06/god-save-the-brief-creatividad-car-one-leoburnett-argentina-solfestival-festival-sol1.png

En cuanto al botón, no es ese al que me refiero. Es este:

<img width="393" alt="captura de pantalla 2015-07-23 a la s 08 56 01" src="https://cloud.githubusercontent.com/assets/6719872/8849590/4888c436-3117-11e5-8c61-54995585dc49.png">

Aparece al principio del video de la intro de la web. Te paso acá el logo en alta así lo podés reproducir bien.

![logo_benteveo-2015](https://cloud.githubusercontent.com/assets/6719872/8849606/5d025814-3117-11e5-9aca-9f88a80bb2f0.png)

Lo tengo en illustrator también si te sirve.

abrazo

**Comment by LeandroBraier** [comment]
Te mando el ilustrator por mail abrazo

**Comment by braulio-evangelisti** [comment]
Ahi te estoy subiendo los dos psd de los gif por WT. Subi la otra imagen para la tercer nota. El boton de btv tiene sombras, relieve, reflejos, textura, es muy realista para el diseño de la news que es todo flat. No va a quedar medio desubicado? Si te parece pruebo de armarlo como los gifs, que son todas formas planas en colores pasteles, el circulo rojo con el pajaro solamente y el ¡VUELA! abajo en texto.

**Comment by LeandroBraier** [comment]
Claro, probalo así, adaptalo a la estética del news, totalmente.

Respecto de los gifs los recibí y comprimí. Aca van de vuelta.

![nota-1](https://cloud.githubusercontent.com/assets/6719872/8858853/39e405a6-3150-11e5-8cc2-178caf568663.gif)

![nota-2](https://cloud.githubusercontent.com/assets/6719872/8858854/3c94b1b0-3150-11e5-960c-f90e9d873691.gif)

**Comment by braulio-evangelisti** [comment]
Perfecto. 
Ahi puse los gifs, creo que el primero tiene un marco blanco de 1px, avisame si lo ves tambien o es mi pc.

Abrazo

**Comment by LeandroBraier** [comment]
Si, lo veo. Y está en el GIF. Ahi lo recorté. Fijate si ahora funciona. Quedaron medio cortados los bordes.

![nota-1-b](https://cloud.githubusercontent.com/assets/6719872/8859522/2eac09fa-3154-11e5-9637-1c80ea4f1351.gif)

**Comment by braulio-evangelisti** [comment]
Acá con el fondo blanco se nota un poco pero fijate en la news con otro color de fondo pasa bastante desapercibido.

**Comment by LeandroBraier** [comment]
Exacto, Braulio. Lo veo muy bien. Y el botón nuevo que subiste ahora quedó
buenísimo. Gracias!

Te aviso cuando tengo los links.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-23 17:15 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
Brau, lo mostré a Eze y me dio un feedback. Le gustó, pero hay pequeños cambios:

1) Acortar los textos de la descripción de cada nota. 

Descripción Nota 1: 
Desde hace un tiempo escuchamos que “el consumidor” se convirtió en “Prosumidor.”  Pero... ¿esta nuestra empresa preparada para hablarle a un Prosumidor?

Descripción Nota 2: 
En tan solo 2 minutos, descubri los próximos pasos para que tu marca no quede afuera en el mundo digital. 

2) Encontramos un news de referencia del cual queremos tomar el footer. 

http://mkt.donweb.com/campaign/htmlversion?AdministratorID=49390&CampaignID=135&StatisticID=84&MemberID=253009&s=e3f8e7ad9b767eea42c3362871c7b3f7&isDemo=0

Fijate que el footer tiene a la izquierda redes sociales y a la derecha otras formas de contacto: chat, mail y teléfono, los cuales nosotros tenemos habilitados, los podés sacar de nuestra web.

Respecto del botón, está bien pero fijate que en esta refe hay un texto que invita a clickear en el botón. Agreguemosle algo parecido. Para mi sería:

¿NECESITÁS ASESORAMIENTO O QUERÉS CONSULTARNOS ALGO?
Contactate en segundos con nuestro equipo.

Que el botón de Vuela tenga forma de globito de chat como el de esta refe y que en lugar de llevar a la web lleve a la web pero ya con el chat de abajo a al derecha abierto. Se puede hacer eso?

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahora Lea. Lo del link al sitio de btv con el chat abierto no encontré si se puede, en general no suelen venir los chats con este tipo de opcion. Le pregunte a Fede y me dijo que el chat lo armo el programador de btv, a lo mejor el sabe si hay alguna manera enviando algun parametro por la url o entrar directamente a una url que sea "para chatear" por decirlo de alguna manera como la que envia el de la referencia.

**Comment by LeandroBraier** [comment]
Quedó buenísimo Brau! Agregale igual el globito de diálogo abajo a la derecha en grisesitoc on el link a la web y en la parte de redes agregá Instagram y Google Plus.

https://instagram.com/benteveotv

https://plus.google.com/110137000127192370115/about

abrazo y gracias!

**Comment by braulio-evangelisti** [comment]
Hecho.

Abrazo!

**Comment by LeandroBraier** [comment]
Perfecto, Braulio!

Cuando tengo los links te los paso y ahi hacemos los ajustes finales.

abrazo

**Comment by LeandroBraier** [comment]
Brau: van los links para incorporar al newsletter. Porfa confirmame apenas lo tengas.

http://www.parexklaukol.com.ar/novedades/parexgroup-miembro-de-argentina-green-building-council-.html

http://www.parexklaukol.com.ar/novedades/edificios-verdes--certificacion-leed-en-argentina.html

http://www.parexklaukol.com.ar/novedades/se-viene-la-xv-bienal-internacional-de-arquitectura-de-buenos-aires.html

http://www.parexklaukol.com.ar/novedades/un-adhesivo-de-alta-performance-para-colocaciones-exigente.html

abrazo

**Comment by braulio-evangelisti** [comment]
Recien me doy cuenta que este issue esta dentro de klaukol pero es de btv jejeje. Te aviso por las dudas. Estos links son de la news de agosto de klaukol. 

Ahi lo subi:

http://www.parexklaukol.com.ar/_mailing/novedades-agosto/novedades-agosto.html

Abrazo

**Comment by LeandroBraier** [comment]
Si, Es verdad!

Excelente laburo Brau!

Gracias.
