### ISSUE TITLE
Mensajes de Ganaste en BuscaKlaukol. 22/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#114]
@mkreyness fijate cómo podríamos hacer para que muestre un mensaje diferente al ganar cada nivel.

Los mensajes serían los siguientes:

¡Ganaste 5 puntos! Ahora Nivel Fácil.

¡Ganaste 15 puntos! Ahora Nivel Moderado.

¡Ganaste 25 puntos! Ahora Nivel Difícil.

¡Ganaste 50 puntos!

Estuve investigando el código y resulta que el mensaje es una imagen llamada "winertxt" que aparece mencionada en las siguientes líneas del ifwin:

```
    var msg:WinerTXT = new WinerTXT();

    msg.name = "msg";    //Show a message for the winner
    msg.x =(stage.width-msg.width)/2;
    msg.y =(stage.height-msg.height)/2;
    addChild(msg);
```

Intuyo que podrías atar los 4 mensajes a las variables que predefiniste para que lleve al siguiente nivel no?

Esto es prioridad.

**Comment by mkreyness** [comment]
Te mande hace un rato un mail con como hacerlo, pero no puedo probarlo.

**Comment by LeandroBraier** [comment]
MK, fijate el código que te mando mañana a la mañana a ver qué puede estar mal ahi con ese error de sintaxis.

El resto ya lo resolví.

abrazo
