### ISSUE TITLE
Juego BuscaKlaukol: Instructivo en PDF. 23/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#115]
Por favor @FAAREIA subí un PDF instructivo con esta imagen al tema de BuscaKlaukol

![instrucciones-busca-klaukol](https://cloud.githubusercontent.com/assets/6719872/8841426/b94d18ec-30c3-11e5-90dd-cd214afcc297.png)

abrazo

**Comment by mkreyness** [comment]
ojo Fede que el template juego-juegoT.html no tiene previsto el lugar para descarga de archivos.
Agregaselo como en el juegoT.html comun y pasame el URL de donde bajaste el PDF asi lo vinculo en el CMS.

**Comment by FAAREIA** [comment]
el PDF es un archivo a parte o es la misma imagen?
Donde esta el PDF?

**Comment by LeandroBraier** [comment]
Es esa imagen en realidad. Quise poner PNG es una sola caratula nomas.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=6&usuario=marcelokreyness&clave=pepe

A la imagen la estiré unos pixeles asi entraba en el ancho de caja

**Comment by mkreyness** [comment]
Ah pero lo metiste fijo en el template, yo entendi que tenia que ser un link, no una imagen embedded. 
Bueno despues a la tarde lo paso a una variable asi el template me sirve para otros juegos como debe ser.

**Comment by LeandroBraier** [comment]
No, pará. El pedido ES un link. Ahí compite mucho con el juego, no queda bien.

Ponelo como link, que abra un pop up o que lo abra ahí mismo como está pero que haya que clickear. El botón tiene que decir "Instrucciones para jugar"

abrazo

**Comment by mkreyness** [comment]
Ademas el texto esta mal, tiene INSTRUCCIONES AL DISEÑADOR !!
Dice cosas como "Poner imagen de donde clickear para ponerlo" !!!

**Comment by LeandroBraier** [comment]
Es cierto MK. No lo había visto.

Lo corrijo y lo vuelve a enviar. Disculpen.

**Comment by FAAREIA** [comment]
Ya esta hecho, solo falta cambiar la imagen ahiora

**Comment by LeandroBraier** [comment]
Ahora quedó genial. Te paso imagen corregida.

![instrucciones-busca-klaukol](https://cloud.githubusercontent.com/assets/6719872/8850727/c0300676-3120-11e5-8732-a186e19e4667.png)

abrazo

**Comment by FAAREIA** [comment]
subido

**Comment by LeandroBraier** [comment]
Gracias Fede! Yo sigo viendo el viejo puede ser?

**Comment by LeandroBraier** [comment]
Subilo a producción directamente

**Comment by FAAREIA** [comment]
Esta en producción ya. Dale F5

**Comment by LeandroBraier** [comment]
Nope. Sigo viendo el mismo che.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Estas cacheado, yo ya la comparé y es la última.
Hacele click derecho a la imagen, dale ver imagen y si ves la vieja, dale F5.
Obviamente que el usuario común al no haber visto la versión anterior, no le va a pasar esto

**Comment by LeandroBraier** [comment]
Buenisimo Fede! Gracias!
