### ISSUE TITLE
Nuevos Thumbnails en Temas de Comunidad de Vendedores. URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#116]
@FAAREIA , te paso 3 thumbnails a subir a 3 temas de Comunidad de Vendedores. 2 temas ya están o sea que solo hay que reemplazar los que están. El tercero es uno que acabo de publicar y aún no tiene thumbnail.

Trivia Klaukol Porcellanato Fluido

![thumbnail trivia porcellanato](https://cloud.githubusercontent.com/assets/6719872/8877406/bc7f89d0-31fb-11e5-9d5a-a01a1383e168.png)

Busca Klaukol

![thumbnail busca klaukol](https://cloud.githubusercontent.com/assets/6719872/8877408/bfbf60e8-31fb-11e5-9604-aa7ac25c6f85.png)

Trivia Parex Estilo 4D

![thumbnail-trivia-parex-estilo-4d](https://cloud.githubusercontent.com/assets/6719872/8877411/c334ec66-31fb-11e5-9cc1-66aff1ffc4de.png)

Esto es prioridad porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi va el nombre de los archivos asi los pnes en el CMS:

thumbnail-busca-klaukol.png
thumbnail-parex-4d.png
thumbnail-porcellanato.png

**Comment by LeandroBraier** [comment]
genial Fede!

Puede ser que la de busca-klaukol como se llama igual no la retomó?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
una es .jpg y esta es .png

**Comment by LeandroBraier** [comment]
Gracias Fede! Tenés razón.

abrazo
