### ISSUE TITLE
Bug en Trivia Parex Estilo 4D

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#117]
@mkreyness me pregunta el cliente por qué está en gris como "inactiva" la opción del PDF apenas entrada. Habilitala porfa hasta que la persona haya leido el PDF o de ultima que queden las 3 opciones habilitadas siempre y listo.

abrazo

**Comment by mkreyness** [comment]
Segun las instrucciones que recibi en su momento, recien tiene que habilitarse una vez que el vendedor se haya DESCARGADO el pdf.
La secuencia es:
- si contesta la trivia por algun otro medio, NUNCA se habilita.
- si no contesto la trivia y DESCARGA el Pdf, se habilita.
- cuando despues de eso contesta la trivia, se vuelve a deshabilitar porque ya esta jugado.

**Comment by LeandroBraier** [comment]
Ok, MK. Entiendo lo que decís pero saquemos ese comando entonces, que estén siempre habilitadas las opciones porque el cliente no lo entiende más a eso.

Me avisas cuando está hecho porfa?

**Comment by mkreyness** [comment]
Listo, pero no era un "bug", era un "feature".

**Comment by LeandroBraier** [comment]
Gracias MK!

abrazo
