### ISSUE TITLE
Modificaciones en Web ParexKlaukol Argentina, Paraguay y Uruguay. 27/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#118]
Fede, necesito tres pequeños cambios para ir dando imagen de empresa mundial:

1) que agreguemos en las tres homes los links de los otros países.. poner arriba las banderitas de Paraguay, Uruguay, así estamos conectados!! 

2) En los logos de ParexGroup que el link lleve a Parexgruop en el mundo, no a la misma de ParexKlaukol: http://www.parex-group.com/ 

abrazo

**Comment by FAAREIA** [comment]
Ya esta implementado Lea.
@mkreyness habría que fijarse porque tarda tanto en responder el dominio: http://www.parexuruguay.com.uy/
No conecta

**Comment by mkreyness** [comment]
Me parece que no le pasaron a la gente que maneja el DNS en Uruguay el IP actual desde que Duplika nos cambio de server.
Hay que avisarles que es 69.46.27.236, y no 69.46.27.34 como tienen puesto actualmente.
Con el de paraguay el cambio esta correctamente hecho.

**Comment by LeandroBraier** [comment]
Buen día Fede! Gracias!

Ya estoy en contacto con la gente de uruguay esperando que me pasen consultas. Les volví a pasar el IP que me dieron uds pero no le encuentran la vuelta. El que les pasé es el 234. Les paso el 236 entonces?

Me habías dicho que iba el 234 MK. Te acordás?

**Comment by mkreyness** [comment]
Si, yo tampoco entiendo la ambiguedad entre 234 y 236, capaz el mismo servidor tiene 2 placas de red. Con 236 esta funcionando ar y py sin problemas.

**Comment by mkreyness** [comment]
Ojo que habian puesto "34", no "234".

**Comment by LeandroBraier** [comment]
Gracias MK!

Y gracias Fede por los cambios. Los veo perfectos.

abrazo a ambos y buen comienzo de semana
