### ISSUE TITLE
Anuario Klaukol 2015

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#12]
Fede, necesito que me digas si llegás a hacer una pequeña maquetación.

Tenemos una pared donde están subidos todos los empleados de la empresa Klaukol, como el que podés ver aquí:

![captura de pantalla 2015-03-30 a la s 21 36 50](https://cloud.githubusercontent.com/assets/6719872/6910042/ea4fbea8-d723-11e4-89a9-91d0465aea0f.png)

Básicamente lo que necesito hacer es tageo mediante fragmentos de la imagen. Enviaremos un newsletter interno que lleve a una página (alojada en nuestro servidor de Benteveo) en la que aparece un pop up. El pop up tiene un fragmento de la foto aumentado donde se ve a 1 empleado de Klaukol. El usuario debe poner el nombre y cargo del empleado para ver la foto general. Una vez que lo hace, ve la foto del edificio donde están todos los empleados y, debajo de los que ya fueron registrados, un cartel con su nombre marcado tipo Anuario Escolar. Al pie, pueden descargarse o imprimirse la imagen y, además, tienen acceso al álbum de fotos completo del evento con todas las fotos reales del evento.

La pregunta es: ¿Es algo simple o es mucho desarrollo?

abrazo

**Comment by FAAREIA** [comment]
No entendí al 100% todo, pero por lo que leí va a llevar tiempo, no se liquida en 3 días. Además Marce K. va a tener que hacer su parte también.

Esto es lo que entendí:
- Le llega un email al usuario
- Abre el mail, hace click en un link que le lleva a la página con un pop-up en donde completa sus datos.
- Una vez completado, ve la foto que me enviaste, la completa....¿? O sino ve un anuario con los registrados hasta el momento.
- Se puede descargar e imprimir la imagen y ¿demas?. ¿Que otras cosas pueden descargar o imprimirse?
- ¿Desde donde se puede acceder a las fotos del evento?

**Comment by FAAREIA** [comment]
También tengan en cuenta que una imagen asi de alta va a generar un gran scroll.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Por las dudas calculame cuántas horas de laburo te llevaría.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
De maquetación ponele 30hs, pero con diseño ya definido.
Habría que definirlo bien bien, tengo algunas dudas todavia. Fijate en mi post anterior

**Comment by LeandroBraier** [comment]
Anotado. Gracias!!
