### ISSUE TITLE
Bug en Juego

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#120]
Feliz domingo @mkreyness !

Te copio captura de comentario de un usuario que ejemplifica bien dos tipos de problema que todavía tiene el juego.

Según pude verificar son 2 problemas. La captura que te adjunto es para la segunda.

1) A veces dice que hay 3 bombas alredededor y hay 4 (o hasta 5)

2) A veces tocás una celda y no se da vuelta, ni para mostrar número ni para mostrar bomba. No sale nada y no permite ganar.

<img width="1383" alt="captura de pantalla 2015-07-26 a la s 17 37 38" src="https://cloud.githubusercontent.com/assets/6719872/8895762/7d4fcbc8-33bb-11e5-91c5-780bcc2de8a3.png">

Esto ponelo como prioridad para resolver mañana temprano si te es posible. Estuve revisando el código de AS pero no supe encontrar el problema. Cualquier cosa en que te pueda ayudar me decís?

abrazo

**Comment by mkreyness** [comment]
Mandame completo de nuevo el proyecto porque todo lo que tengo ya esta muy desactualizado.
El tema de que no subia de 3 lo habiamos arreglado, capaz se te perdio en algun cambio.
Lo otro espero poder reproducirlo para entender en que situacion pasa, a mi nunca me paso pero no llegue al ultimo nivel.

**Comment by mkreyness** [comment]
Ojo que tambien hay una cosa confusa: suponete que yo puse un "Klaukol" en un lugar que no iba, porque crei que ahi habia una bomba y arriba decia "1". Despues toco en la de al lado de mi K y explota y veo algo asi (marco con "!" la que "exploto"):
- 1 -
- K K!

entonces digo AHHH, esta mal porque decia 1 y habia dos !!!
No es cierto porque en realidad un de esas K la puse YO mal.
Tendria que diferenciarse las K reales de las puestas mal (obviamente al terminar el juego, no durante el juego).
Me explico ? Mucha gente en vez de pensar que desperdició una "K", piensa que habia una de mas  y que el juego "no le avisó".

**Comment by LeandroBraier** [comment]
Entiendo MK. Eso sería para el Punto 2. Lo que habría que hacer es que, en ese caso, La K falta aparezca sin color. Si vos ponés una referencia a una imagen así con un nombre tipo "false-bomb" yo la subo a la librería una vez que me pases el código corregido.

Respecto del Punto 1 tenés idea qué puede ser?

Ahi te estoy mandando adjunto el FLA por mail.

abrazo

**Comment by mkreyness** [comment]
pero el asunto es que si haces eso DURANTE el juego es una gran ayuda. Habria que hacer una barrida al final (al perder) marcando todas las false bombs.
Igual por lo que veo ya existe eso, fijate que algunas "K" tienen como una sombra gris debajo, y otras no. Las falsas son las que no. De hecho cuando perdiste las falsas siguen siendo "clickeables".
Es cuestion de enfatizar un poco mas en el icono de las falsas.

Acabo de llegar al punto muerto que dice el tipo: hay una casilla que queda "no clickeable", con o sin flag, no responde al click.

**Comment by mkreyness** [comment]
listo, te mande codigo. Yo lo unico que te sugeriria es destacar un poco mas que el button5.png sea diferente al button4.png

**Comment by LeandroBraier** [comment]
Gracias MK!

Ya te pasé el SWF corregido.

abrazo
