### ISSUE TITLE
Vendedores Issue #1: Tickets correlativos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#121]
Buen día MK! Tengo el siguiente problema. Cuando me bajo los tickets obtenidos a partir de Julio para el sorteo de este viernes veo que arrancan del 271, es decir, son correlativos de Junio.

1) Por qué es así?

2) Me confirmás que los que tienen tickets de número menor a 271 no tienen el ticket en su plataforma?

3) Cómo evitamos que vuelva a ocurrir y empiecen desde el 1 para el mes de agosto?

**Comment by mkreyness** [comment]
La numeracion se conserva, pero los tickets visibles para la gente son solo los vigentes, Mientras no haya sorteo, sigo mostrandolos (el dia del sorteo) para que vean con que numeros estan participando.

Una vez q vos me avisas que hiciste el sorteo yo corro un proceso que los cancela (existen pero no se ven). 

Vos tenes que sortear dentro del rango que corresponde al periodo de sorteo, no "desde el nro 1".

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Ok.

Pero siempre va a ser así? Siempre van a ser correlativos?

[image: Benteveo TV] http://benteveo.tv
LEANDRO BRAIER
BENTEVEO
Guatemala 5582 - Piso 2 (CABA) Argentina
_T._ +54 11.52.54.73.63
_E._ leandro@benteveo.tv
_W._ www.benteveo.tv

2015-07-28 9:30 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Y si, es un numero creciente que le asigna la base de datos, si no 
corremos el riesgo de que se duplique un numero.
Para que empiece de nuevo de 1 tendria que borrar toda la historia, y no 
podria mostrarla el dia del sorteo.

**Comment by LeandroBraier** [comment]
Entiendo. Queda así entonces.
