### ISSUE TITLE
Vendedores Issue #2: Filtro de Estado

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#122]
MK, necesito diferenciar, dentro de los usuario de la Comunidad de Vendedores que están ACTIVOS, aquellos que ingresaron por primera vez de aquellos que nunca ingresaron a la comunidad.

Dónde me puedo bajar esa info?

Lo ideal sería que estuvieron en la columna de Estado de la lista de Vendedores, así tengo todos los datos de ellos.

abrazo

**Comment by mkreyness** [comment]
Lo que pasa es que actualmente el estado activo es el que permite saber que ya le mande el mail a los que tienen mail, independientemente de si entraron. Y si te pongo una columna con el puntaje? El que tiene 0 no entró nunca.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Perfecto MK. Con eso me arreglo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-28 9:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Avisame porfa cuando lo tengas MK

abrazo

**Comment by mkreyness** [comment]
en un rato

**Comment by mkreyness** [comment]
Listo. Tene en cuenta que es el puntaje TOTAL, porque no puedo estar tomando solo lo vigente para este mes, ya que lo que queremos saber es si alguna vez (en cualquier mes) entró.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!
