### ISSUE TITLE
Sitio Web Parex Paraguay y Uruguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#123]
@mkreyness cómo va?

Consulta. Yo veo bien el sitio pero en Paraguay les aparece como aparecía en Uruguay cuando el IP estaba mal delegado. Qué causa puede ser? Allá no tienen a nadie de sistemas y les pedi que chequen si el IP es el correcto a la que están redireccionando el dominio y nadie entiende un soto.

Respecto de Uruguay pasa algo más raro todavía. El dominio me lleva a la página de Agencia La Provincia (?)

parexuruguay.com.uy

Probalo. Qué está pasando ahi? Es algo nuestro, de Duplika o de ellos?

abrazo

**Comment by mkreyness** [comment]
Paraguay a mi me anda perfecto, que es lo que ven ? No puedo reproducir el problema.
Uruguay:
agencia la provincia es el maldito .234 que duplika nos habia pasado en el mail, pero en la practica esta mal. Se ve que cambiaron el .34 por .234, pero habia que cambiarlo por .236 como te dije en el ultimo mail sobre esto.

**Comment by mkreyness** [comment]
cuando digo "cambiaron" me refiero a los uruguayos, no a Duplika.
Porque primero habian  puesto .34 y tenian que cambiarlo por .236.

**Comment by LeandroBraier** [comment]
No te puedo creer que es eso. OK, les aviso. EL cliente no se dio cuenta
aún.

Gracias!

Lo de Uruguay yo tampoco se. Les aparece el mismo cartel que le aparecía
antes a Uruguay, cuando decía .34 en lugar de .234

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-29 23:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Querras decir "Lo de paraguay".

**Comment by LeandroBraier** [comment]
Exacto. Lo de Paraguay ahora en Paraguay se ve como se veia Uruguay con el ip equivocado.

**Comment by mkreyness** [comment]
Que raro, por que cambiaria algo si andaba bien ? El IP aparece bien, y yo lo veo bien, vos lo ves mal o solo te dijeron que DESDE Paraguay se ve mal ?

**Comment by LeandroBraier** [comment]
Si, y me pasaron una captura de pantalla del mensaje de error y era el
mismo que el de Uruguay de antes.

No te preocupes, si a vos no te se ocurre igual yo ya les dije que se
aseguren de que están bien delegado al IP correcto y listo. Yo solo te
consultaba para que, si nosotros podemos saber algo antes, lo sepamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Gracias MK! Ya fue solucionado este tema gracias a los datos que me pasaste.

abrazo
