### ISSUE TITLE
Newsletter Klaukol de Agosto

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#124]
Buen día @braulio-evangelisti !

Cómo estás? Te paso el contenido para el newsletter de Agosto de Klaukol, que ya lo tenés maquetado, solo faltaría cambiarle los contenidos y ponerlos en este orden (la nota 2 ya la tenés maquetada incluso del mes pasado).

https://docs.google.com/document/d/1gKlcI998-lixZVrk7jJY-3sNcxHcTdCykSS4W0Wzv1c/edit

Confirmame si lo podés tener para hoy a la tarde.

abrazo

**Comment by braulio-evangelisti** [comment]
La de la bienal la pongo en las novedades chicas de abajo bajo el titulo "Eventos"?

Quedarian 2 grandes arriba(AGBC y edificios verdes) y 2 chicas abajo (Eventos y producto)? O dejo algunas de las otras?

Creo que habia una grande de flex fluido, la busco en local que tengo algunas cosas del sitio cuando se bajo el viejo para backup.

Abrazo

**Comment by LeandroBraier** [comment]
Genial Brau! Si, así como decís tal cual.

Si encontrás una más en alta de Flex Fluido o de otros productos pasamelos
así no te jodo más y ya la próxima te lo paso bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-30 14:25 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Fijate ahi Lea

http://www.parexklaukol.com.ar/_mailing/novedades-agosto/novedades-agosto.html

Abrazo

**Comment by braulio-evangelisti** [comment]
Hecho:

http://www.parexklaukol.com.ar/_mailing/novedades-agosto/novedades-agosto2.html

**Comment by LeandroBraier** [comment]
Excelente Brau!

Te confirmo si hay cambios del cliente.

abrazo

**Comment by LeandroBraier** [comment]
Seguimos con la landing de Paty ahora entonces. Para la tarde puede estar?

**Comment by braulio-evangelisti** [comment]
Ayer tuve problemas todo el dia para descargar el wetransfer, quedaba fijo en un procentaje, recien ahora agarro y especificamente con una navegador. Apenas lo tenga veo de que se trata el cambio a ver cuanto va a llevar.

**Comment by LeandroBraier** [comment]
Dale, gracias Brau!

**Comment by LeandroBraier** [comment]
Brau, te paso cambios para el news a hacer para el lunes

Título nota 1 cambia a: PAREXGROUP CON SUS MARCAS KLAUKOL, PAREX, LANKO , REVEAR SE UNE A LA ARGENTINA BUILDING COUNCIL 

Copete cambia a: ParexGroup  se une a la Argentina Green Building Council (AGBC) para contribuir en el crecimiento de una industria cada vez más sustentable, desarrollando productos ambientalmente responsables. Enterate mas aquí!

Titulo nota 2 cambia a: PAREXGROUP SUMA CREDITOS LEED

La foto cambia a esta:

![nota-2-edificios-verdes](https://cloud.githubusercontent.com/assets/6719872/9015993/b6998b44-37a3-11e5-96a3-ecdbdc2c18e8.png)

Nota de Flex:

Cambiar título a: Probá Klaukol Flex Fluido

Cambiar copete a: Con esta mezcla adhesiva con propiedades de anclaje físico y químico podés hasta pegar cerámico sobre cerámico.

Footer:

Sacar logo Club de Colocadores y el 0800 con la web esta muy grande. 
Ponerlo asi: 

<img width="133" alt="captura de pantalla 2015-07-31 a la s 17 42 04" src="https://cloud.githubusercontent.com/assets/6719872/9016758/d310ee10-37a9-11e5-8d30-1f2d1db81724.png">

Osea en un bloque, todo en gris y con la tipografia derecha. Mas sobrio.

**Comment by braulio-evangelisti** [comment]
Buen lunes Lea, estoy con esto apenas este listo lo subo y te aviso.
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Buen lunes!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-03 8:31 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Fijate ahi lea

http://parexklaukol.com.ar/_mailing/novedades-agosto/novedades-agosto2.html

**Comment by LeandroBraier** [comment]
Excelente Brau! gracias!
