### ISSUE TITLE
Torneo de Potenciados #5: Ajustes Versión de Corredores 04/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#125]
Chicos, les paso correcciones puntuales para la Tabla de Tus Ventas y la Tabla de Posiciones

TABLA DE TUS VENTAS
1. Pasar el Puesto a la Izquierda de todo.
2. Agregar columna llamada “Ventas para subir 1 puesto” que diga cuantas bolsas equivalentes o puntos le tiene que vender para pasar de posicion”
3. Agrupar x categorías y dsp las posiciones ordenadas de mayor a menor. Que entre cada categoría haya una linea divisoria clara.
4. El titulo de Objetivo que se llame "Objetivo Total" y abajo chiquito diga "puntos".
5. En lugar de Velocidad en el Titulo que diga “Como vengo hasta ahora" y ahí muestre el porcentaje del objetivo conseguido pero no mensual, sino sumando los meses transcurridos desde que comenzó el concurso. Por ejemplo: Si estamos en Agosto, que me sume los objetivos de Julio y Agosto y sobre eso me calcule el porcentaje.
6. En lugar de Ventas/Objetivo que diga “% de objetivo total”. Esta columna debe estar a la derecha de Objetivo.
7. En lugar de Clase que diga “Grupo” y quitar la palabra Categoria.

Las columnas quedarían así
PUESTO/VENTAS PARA SUBIR 1 PUESTO/OBJETIVO TOTAL/% DE OBJETIVO/COMO VENGO HASTA AHORA/ CORRALÓN/ DIRECCIÓN / GRUPO

TABLA DE POSICIONES
1. Hacer 6 tablas de posiciones del puesto 1 al 10. Una por cada Grupo. Que diga Tabla de posiciones Grupo A, Grupo B, Grupo C, etc
2. Quitar el velocímetro. Queda solo la barra.
3. Si el corredor tiene un corralón en el top 10 se le destaca con la misma estética que en la versión de dueños de corralones.
4. Si el corredor no tiene ningun corralón en el top 10 aparece un mensaje textual destacado debajo de donde dice TABLA DE POSICIONES GRUPO X. Ese mensaje dice: "Vendé XXX bolsas equivalentes a tu corralón XXX para entrar al TOP 10". El corralón XXX sería el que esté mejor posicionado de los suyos dentro de ese grupo.

@FAAREIA Confirmame si podemos tener las modificaciones para el martes 04/08 dentro del día.

abrazo

**Comment by FAAREIA** [comment]
pongo a @mkreyness que tiene bastante también.

**Comment by mkreyness** [comment]
Hace por favor los nuevos templates con otro nombre asi puedo probar los cambios sin romper nada.

**Comment by FAAREIA** [comment]
Oka

**Comment by mkreyness** [comment]
avisame cuando esten y como se llaman

**Comment by FAAREIA** [comment]
Listo, algunos detalles:

## Tabla ventas
- La clase que marca la separación entre categorías va en el primer TR de la categoría. La clase se llama "categoria-nueva".

## Posiciones
- Para destacar el puesto acordate que la clase del LI tiene que ser "activo"
- El mensaje inferior solo se renderizaría si no hay puestos a mostrar.

*\* El HTML se llama "con-slideT-R-NUEVO.html" **

**Comment by mkreyness** [comment]
ok, esta noche me pongo con todo esto.

**Comment by LeandroBraier** [comment]
Gracias Fede!

MK, avisame cuando esté listo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-03 19:02 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Tengo una terrible duda: QUE ventas hay que mostrar en la tabla de abajo ? Porque si tomo solo lo mismo que sale arriba, al tipo que no tiene ninguna en el top ten no le saldria NADA.
Como era antes, las de arriba eran siempre SUS top ten arriba (que estoy de acuerdo en que era muy confuso) y por lo tanto siempre tenia lo que poner abajo, pero ahora no.

**Comment by LeandroBraier** [comment]
Buen día MK!

Hay que mostrar los mismos datos que ahora. El único lugar donde cambian
los datos que se muestran es en las tablas de posiciones.

Por favor confirmenme que llegamos con estas modificaciones para hoy.

2015-08-04 2:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si pero no llego a terminarlo antes de las 6 de la tarde.

**Comment by LeandroBraier** [comment]
Ok, MK, intentemos lo antes posible entonces. Para hoy si o si por favor.
Aunque sea a última hora. Pongamosle prioridad a esto.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-04 8:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
si, ya casi esta, me faltan un par de ajustes nomas.

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA el cliente ya lo vio y me pasó feedback. Les pido que lo miren y me digan para qué hora de mañana los podríamos tener impactados. Estos son urgentes.

. Categoria A:

Chequear que hay mas de 5 con puntos. FIjate @mkreyness en la última base que te pasé.

TABLA DE POSICIONES

. En la frase "Ultima actualización… 27/08 agregar el siguiente texto: "Vs Info Semestral"
. Que no diga números absolutos en la tabla de posiciones sino porcentajes.
. Cambiar el color destacado en lugar del color amarillo por el azul de Klaukol.
. Agregar nombres de corralones solo en cada Puesto que pertenece a ese vendedor.
. Agregar arriba de todo cuantos puntos para pasar al siguiente puesto igual que en la versión de corralones
. Cambiar el Height de la marca a "180"

TUS VENTAS

. Líneas divisorias de color naranja solo entre categoría y categoría, las otras que sean grises
. Cambiar "Ventas para subir un puesto" por "Puntos para subir un puesto"
. Que solo el título diga "Puntos" (la palabra entera, sin abreviatura). Después en el interior del chart van las cifras solas.
. Cambiar "Objetivo Total" por "Objetivo Semestral (puntos)"
. Quitar columna "Dirección" y hacer un poco más ancha la columna de "Nombre"
. Donde dice "% de objetivo total" debe decir "% de objetivo semestral" y en cada porcentaje debe incluir entre paréntesis el total de puntos alcanzados hasta el momento.
. Que en el "Como vengo hasta ahora", en cada cifra diga "41% de qué". EJ: Si pasaron 2 meses que diga "41% de 2 meses". Esto debería cambiar el cálculo también en programación.

---------Cambio para el viernes (no tan urgentes)

. Necesito separar la Tabla de Ventas de cada categoría debajo de la Tabla de Posiciones de su categoría, asi siempre el tipo ve: Tabla de Posiciones de Categoria A, Tus ventas de Categoria A, Tabla de posiciones de Categoria B, Tus ventas de Categorias B, así.
. Agregar Hover en Nombre de Corralón con datos.

abrazo

**Comment by mkreyness** [comment]
Bueno, te apuraste a mostrarlo porque yo no habia terminado. Habia muchos errores de datos en los puntos diferenciales porque no estaban tomando en cuenta justamente que suba el porcentaje (en algunos casos daba negativo). Eso ya esta arreglado.
Lo de las lineas divisorias entre categorias no estaba implementado, pero ahora esta.
El resto dejame que respire (porque estuve corriendo para llegar a esto a las 6) y lo chequeo.

**Comment by LeandroBraier** [comment]
Dale, no hay problema. Hoy solo necesito que me confirmes para qué hora de mañana lo podríamos tener.

El cliente me lo pidió tenerlo para la mañana, pero quedé en confirmarle una vez que hable con uds.

abrazo

**Comment by mkreyness** [comment]
De los 20 corralones con categoria "A" que me pasaste en el ultimo excel, solo 5 tienen OBJETIVO. Si no tienen objetivo, aca no pueden aparecer, no hay forma de calcular el %.
Acordate que me pasaste 32 corralones nuevos, pero sin objetivos, por lo tanto son la nada misma.

**Comment by mkreyness** [comment]
Hay muchas cosas que tiene que cambiar la maquetacion Fede supongo, no podemos estarlo tocando los dos a la vez.
Me parece que antes de la reunion de mañana no voy a poder avanzar con estos cambios salvo que Fede pueda hacer su parte ahora.
Hay algunas cosas que igual no entiendo bien, como va a caber el nombre del corralon en la tabla de posiciones ?

**Comment by LeandroBraier** [comment]
Ok. Espero respuesta de Fede.

Hagamoslo en varias lineas si es largo el nombre.

**Comment by FAAREIA** [comment]
Ahi meto mano

**Comment by FAAREIA** [comment]
@mkreyness desde que url estan probando?

**Comment by mkreyness** [comment]
Podes probar con varios para ver como cambian algunas cosas:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide2.pl?usuario=JavierVasquez&clave=111281&torneo=1

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide2.pl?usuario=nicolassale&clave=123001&torneo=1

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide2.pl?usuario=norbertocastello&clave=108811&torneo=1

**Comment by FAAREIA** [comment]
Ahi hice unos mini cambios, ahora me meto con el CSS. Igual ya estoy bastante mareado con las cosas, de última mañana lo vemos bien

**Comment by mkreyness** [comment]
Si, la verdad que el programa tambien me esta quedando una ensalada inentendible con tantas idas y vueltas y cambios de idea sobre los mismos elementos.

**Comment by LeandroBraier** [comment]
Muy bueno chicos! Gracias!

Mañana lo terminamos y lo vemos juntos en la reunión. Nos vemos a las 10.30 mañana?

**Comment by mkreyness** [comment]
10:30, si.

**Comment by mkreyness** [comment]
Fede avisame cuando puedo seguir tocando yo y si agregaste nuevas variables en el template que tengo que completar, como se llaman.

**Comment by FAAREIA** [comment]
Ahi esta hecha la actualización.
@mkreyness las variables para tocar son:
- `<!--objetivo-->` Que hay que agregarle entre parentesis los puntos
- Buscate la palabra `class="nombre-corralon"` y el contenido es una variable nueva.
- Después la de "41% de 2 meses"

**Comment by LeandroBraier** [comment]
Gracias Fede!

Me parece que faltan cosas aparte de lo que le pedís a MK. Por ejemplo, en
la tabla de posiciones iban los porcentajes, no los puntos, te acordás?
También te había pedido que pusieras cuántos puntos faltan para el próximo
puesto en los corralones destacados. La frase de cuánto falta para entrar
en el ranking está perfecta pero falta esto.

Revisá por las dudas que esté todo.

abrazo

2015-08-06 9:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Claro los puntos y porcentaje de objetivo habria que juntarlos en una sola columna, los datos estan, pero separados.
Al hover de corralon le sobra un cierre de div
Para lo de "41% de 2 meses", tenes que cambiarle el texto al titulo que dice "como vengo hasta ahora", pero no se bien que deberia decir. Yo estoy saliendo, al mediodia sigo.

**Comment by FAAREIA** [comment]
Ahi agregué eso de "+99789 paa subir un puesto".
Lo que sea de pasar puntos a % o viceversa, ya es programación.
@mkreyness lo de los puntos y porcentaje de objetivo había entendido que van asi, solo que falta meterle "(9228)" al lado del porcentaje.
Lo del título ese "como vengo hasta ahora" quedó indefinido, si me dicen cual es lo cambio.

**Comment by LeandroBraier** [comment]
Gracias Fede! Espero lo de MK entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-06 10:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
ahi complete lo de "para subir un puesto" de las tablas de posiciones.
Ahh, lo de los puntos que decis entre parentesis son los REALES, no el objetivo. Ok, ahora lo agrego, tengo que tocarlo en el template.

**Comment by mkreyness** [comment]
Listo todo, CREO, si falta alguna cosa diganme.

**Comment by LeandroBraier** [comment]
Gracias MK. Faltan estas dos cosas:

TABLA DE POSICIONES

. Que no diga números absolutos en la tabla de posiciones sino porcentajes.

TUS VENTAS

. Que en el "Como vengo hasta ahora", en cada cifra diga "41% de qué". EJ: Si pasaron 2 meses que diga "41% de 2 meses". Esto debería cambiar el cálculo también en programación.

**Comment by mkreyness** [comment]
TABLA DE POSICIONES 
- listo
  TUS VENTAS
  Ok, el calculo no tiene que ser el % de  "este mes" sino el acumulado sobre la cantidad de meses transcurridos, hecho. De todos modos como el dato mas nuevo que tengo es de julio, sigue siendo un solo mes asi que los numeros van a ser los mismos.
  Recien cuando te manden el acumulado a agosto va a ser 2 meses.
  Pero en CADA renglon que diga "de 1 mes" ? No deberia decirlo una sola vez en el titulo de la columna ? Si es lo mismo para todos.

**Comment by LeandroBraier** [comment]
Si se puede que lo diga cada vez mejor, ponelo así. Si no se puede avisame. 

Si la última actualización fue en julio que diga "de 1 mes" entonces.

**Comment by mkreyness** [comment]
Ya esta puesto, pero se ve horrible.

**Comment by LeandroBraier** [comment]
Yo lo veo bien!

Gracias MK!

Lo mando y les aviso el feedback. Abrazo y gracias a los dos!
