### ISSUE TITLE
Backups de todos los sitios terminados de Parex. 07/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#126]
@FAAREIA necesitaría un backup de los siguientes sitios pedido por el cliente:

. Sitio Web ParexKlaukol (Klaukol, Parex, Lanko)
. Sitio Revear
. Guía de Corralones
. Comunidad de Vendedores ParexKlaukol

No incluir el CMS.

abrazo

**Comment by mkreyness** [comment]
```
La guia de corralones y la comunidad son programas que leen (y
graban) info en una base de datos dinamicamente.
El backup hay que hacerlo de la base de datos del CMS, no hay
paginas estaticas backupeables mas que los templates.

El 02/08/2015 a las 22:10,
  LeandroBraier escribió:


  @FAAREIA necesitaría un backup de los
    siguientes sitios pedido por el cliente:
  . Sitio Web ParexKlaukol (Klaukol, Parex, Lanko)
    . Sitio Revear
    . Guía de Corralones
    . Comunidad de Vendedores ParexKlaukol
  No incluir el CMS.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto. Pasemosles los templates y las bases de datos bajadas del CMS.
COn eso estamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-02 22:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Sin los programas ? Porque los datos sin los programas que los usan, no sirven de mucho.

**Comment by LeandroBraier** [comment]
Si. Sin el cms. Como lo que hicimos para Danica. Te acordas?

**Comment by mkreyness** [comment]
En Danica todo estaba en paginas estaticas que se generaban desde el CMS. Aca hay mucha mas interactividad, solo los productos y novedades tienen paginas estaticas, todo lo demas tiene programas especificos  (que no son los del CMS en si), que son los que hacen el login, toda la interface de juegos, puntajes, etc. en el caso de vendedores, y la busqueda de corralones en el caso de la guia.

**Comment by LeandroBraier** [comment]
Ok. Todo lo que no sea CMS pasemoselo.

Abrazo

**Comment by mkreyness** [comment]
```
Entonces te hago un dump full de la base (ahi algunos datos del CMS
van a estar, pero sin los programas de CMS no sirven para nada).
Fede vos haces backup de las paginas/templates/etc ?
La zona gris es cada /cgi-bin, porque ahi hay un poquito del CMS.
Eso lo backupeo yo y le limpio lo del CMS.

El 02/08/2015 a las 23:16,
  LeandroBraier escribió:

Ok. Todo lo que no sea CMS pasemoselo.

  Abrazo
  El ago 2, 2015 11:07 p.m., "mkreyness"
  <notifications@github.com> escribió:

  > En Danica todo estaba en paginas estaticas que se generaban
  desde el CMS.
  > Aca hay mucha mas interactividad, solo los productos y
  novedades tienen
  > paginas estaticas, todo lo demas tiene programas especificos
  (que no son
  > los del CMS en si), que son los que hacen el login, toda la
  interface de
  > juegos, puntajes, etc. en el caso de vendedores, y la
  busqueda de
  > corralones en el caso de la guia.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/126#issuecomment-127098771
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
Ya tengo el de los programas y el dump de la base, como queres que te los pase ?
El de programas es un tar.gz que ocupa poco, el de la base es un .zip que ocupa 1 Mb.

**Comment by LeandroBraier** [comment]
Genial. Pasamelo por WeTransfer nomás.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA faltaría tu parte entonces.

@mkreyness falta algo más de lo tuyo?

**Comment by mkreyness** [comment]
No, porque los programas de Uruguay y Paraguay son una copia de los mismos de argentina que son los que te pasé.
Los procesos que corren en background (generando las paginas desde el CMS, y los que uso para mandar mailings) no se los mandaria porque no son "parte del sitio".

**Comment by FAAREIA** [comment]
Ok, los backups van a ser grandes pero quedan online.
Voy a tratar de ir limpiando todos los residuos que hayan quedado.

**Comment by FAAREIA** [comment]
Los backups viejos se pueden borrar ya?

**Comment by LeandroBraier** [comment]
Todavia no por las dudas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-03 16:45 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Ojo no se si estan hablando de los backups mandados por ellos, eso tiene todo el contenido de los sitios viejos EN USO de revear, apps viejas, etc, fotos y videos de los productos y novedades. Eso no debe borrarse.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Claro, por eso. Por las dudas no borremos nada. Además así se lo pasamos al
cliente también y ve cómo lo fue la data con la que trabajamos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-03 17:26 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi van los archivos, lo separé para no generar contenido duplicado y basura.

#### Parex AR, incluye mailings y micrositios.

http://www.parexklaukol.com.ar/parexklaukol.zip

#### Parex UY

http://www.parexuruguay.com.uy/parexklaukoluy.zip

#### Parex PY

http://www.parexparaguay.com.py/parexklaukolpy.zip

#### Archivos comunes a los 3 sitios

http://www.parexklaukol.com.ar/archivos-comunes.zip

#### Templates del sistema

http://www.parexklaukol.com.ar/templates.zip

#### Backups viejos, de los cuales tomamos archivos como imágenes o pdfs.
- http://www.parexklaukol.com/bkps/parexar.tar
- http://www.parexklaukol.com/bkps/parexpy.tar.gz
- http://www.parexklaukol.com/bkps/parexuy.tar.gz
- http://www.parexklaukol.com/bkps/revear.com.ar.zip

**Comment by LeandroBraier** [comment]
Gracias Fede!

Creo que con esto estamos, no? No falta nada.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA hoy en algún momento del día actualizá los backups que haya que actualizar y avisame así los descargo por las dudas.

abrazo

**Comment by FAAREIA** [comment]
Veo como voy con colocadores, pero no creo llegar.

**Comment by LeandroBraier** [comment]
Está bien, puede ser mañana o pasado, pero que no nos colguemos nada más.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 9:45 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lea, confirmame que ya te bajaste los backups que había hecho asi los borro y vemos de generar el backup completo

**Comment by FAAREIA** [comment]
Lea, acordate que no puedo hacer un backup completo sin borrar los backups existentes.

**Comment by LeandroBraier** [comment]
Están todos descargados por mi. Actualizalos tranquilo.

abrazo

**Comment by FAAREIA** [comment]
Perfecto, ahi borré los backups existentes. Ahora para generar el backup completo del sitio, que sería lo mismo que antes pero en 1 solo archivo y actualizado a hoy, tenés que:
- Entrar a http://www.parexklaukol.com.ar:2082
- Ir a "Backup", ubicado bajo el título "File", que es el primero que aparece.
- Hacer click en el primer botón que aparece que tiene como texto "Download a Full Website Backup"
- ~~Tené en cuenta que el sitio pesa 16GB, debe ser por los archivos de los sitios anteriores~~ Ahora ocupa 4, borré la papelera

**Comment by LeandroBraier** [comment]
Gracias Fede!

Solo te pido entonces que separes el backup de los sitios anteriores de los
sitios nuestros actualizados, así lo puedo ir descargando regularmente por
las dudas.

Si cada vez que quiero actualizar tengo que descargar 1 solo archivo de 16
gb seguro se me va a cortar el paquete antes y nunca lo voy a poder bajar.

Agregame la opción: bajar solo sitio completo actual.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-28 8:30 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya borré la papelera y el sitio ocupa 4GB, más razonable. Fijate ahora.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Ahi lo puse a generar, me va a avisar por mail cuando esté y te aviso. Gracias!

abrazo
