### ISSUE TITLE
Suscripcion al Newsletter de klaukol no te confirma

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#127]
@mkreyness fijate si podés qué pasa o qué necesitás de mi parte para activar esa confirmación.

Me refiero a la subscripción que está en la home de la web de ParexKlaukol:

http://www.parexklaukol.com.ar/

abrazo

**Comment by mkreyness** [comment]
bueno basicamente ese boton no hace nada, es un formulario que no lleva a ningun lado.
Que tendria que hacer, mandar un mail a alguna direccion ? Cual ?
O guardarlo en una base de datos consultable ?

**Comment by LeandroBraier** [comment]
Jaja pense que funcionaba. Si, que se almacenen los datos en una base que
quede en el cms. Y les llegue un mail de confirmación de subscripción.

Antes: hay forma de vincularlo con un formulario de mailchimp?

**Comment by mkreyness** [comment]
Ni idea, sigo sin saber como funciona mailchimp. Cuando tenga acceso al API sabre.
El mail de confirmacion de suscripcion, esta diseñado/maquetado ?

**Comment by LeandroBraier** [comment]
Nop. Necesitas un html?

**Comment by mkreyness** [comment]
Y si, si no va a ser muy fea la confirmacion solo texto.

**Comment by LeandroBraier** [comment]
Dale. Mañana te lo paso.

Abrazo

**Comment by mkreyness** [comment]
Ya implementé que lo que se tipee se guarde en una base (supongo que habria que hacer lo mismo con Uruguay y Paraguay por separado, no ? Al menos en la base ya lo deje previsto.
Solo falta el html del mail de confirmación. Acordate que no se pide nombre, asi que el subject no puede estar "personalizado".
Como no tenia un elemento donde mostrar el OK de la suscripcion le puse (por ahora, si le pasas a Fede se debe poder maquetar algo mejor) que en el campo de tipeo del mail al darle el submit diga "GRACIAS" (o "YA INGRESADO", si lo repetis).

**Comment by LeandroBraier** [comment]
OK, MK!

mañana te paso el mail de confirmación que usamos en MailChimp y lo adaptamos para esto.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness tardé un poco más de lo esperado pero ya tengo diseñado el mailing de confirmación.

Tenemos un diseñador que hizo un curso en "newsletter responsive" y lo armó así. La verdad, es algo nuevo, ni idea. Te lo mandé por mail, fijate cómo lo ves.

Si lo ves OK, subilo a la página o lo hablamos con Fede para que lo suba a la página. Y habría que hacer uno para Benteveo también no?

abrazo

**Comment by mkreyness** [comment]
A la tarde lo miro y te digo, no creo que haya problema, despues de todo no hay ningun dato variable, es el mismo mail para todo el mund

**Comment by mkreyness** [comment]
@FAAREIA necesitamos una pagina de landing para cuando el suscripto confirma su direccion (mediante un link que le llega en un mail, es totalmente asincronico con el momento en que ingresa su email en el form de newsletter).
Hay 2 posibilidades, no se si queres hacerlo en htmls separados o como una clase a modificar, ya que puede ser que entren de vuelta cuando ya estan confirmados o directamente sea un robot que intenta jorobarnos o validar una lista de mails.
En una tendria que decir algo tipo "Tu suscripción ha sido confirmada. ¡Muchas gracias!" y en el otro "Esta suscripción no se encuentra pendiente ¿Querés recibir nuestras novedades? Registrate aquí.", lo cual es suficientemente ambiguo para que el que lo lea no sepa si el mail esta anotado o no. En esta agregá el link al formulario de registro de la web.
Yo aloje el HTML que me paso Lean para el mail en _mailing/suscripcion_newsletter, si queres pone tambien ahi este HTML que te pido (ojo no le pongas justo el nombre de algo que ya este ahi o en su /img).

**Comment by LeandroBraier** [comment]
Corregí detalles del texto, Fede. Tomá la versión subida en la web.

**Comment by mkreyness** [comment]
ojo Lean que cuando Fede lo tenga yo tengo que hacer cambios en mi programa (segun como lo haya implementado), no me desasignes an rapido.
Esto no es el html del mailing propiamente dicho sino el feedback visual de que su confirmacion fue tomada cuando hace click en el link que llega en el mailing.

**Comment by LeandroBraier** [comment]
Tenés razón MK, te devuelvo el ticket. Gracias!

**Comment by FAAREIA** [comment]
Hola Marce, lo que yo haría es mandarlos al home del sitio pero con este parametro (ya funciona):
?s=1
?s=0

Es una buena solución sin generar una landing vacia para una línea de texto. El link de registrarse lo puse pero no va a ningun lado.

**Comment by LeandroBraier** [comment]
@mkreyness seguís vos desde acá?

**Comment by mkreyness** [comment]
Si,
Fede no entiendo a que te referis con "el link de registarse".
Esta bien lo de que vaya a la home, no tengo problema mientras tenga algun feedback.
Cual caso es s=1 y cual s=0 ?

**Comment by mkreyness** [comment]
Ah, ya vi, pusiste una frase de registrate en el cartel. Es medio confuso, si hace click ahi deberia llevar a la parte de abajo donde dice "NEWSLETTER PAREXGROUP".
Bueno mi programa ya esta tocado.
Lean queres probar con el mail que te mande anoche si el link te funciona bien ? Lo recibiste ?
Cuando me confirmes ambas cosas le mando los mails a la gente que se fue registrando estos dias y ya lo dejo operativo para los proximos que ingresen.

**Comment by LeandroBraier** [comment]
Funcionalmente está OK, pero la estética de ese recuadro no tiene NADA que ver con la de ParexKlaukol. Por lo menos fondo blanco y letras roja, puede ser?

Con eso ya estamos.

**Comment by mkreyness** [comment]
Eso es tema de @FAAREIA

**Comment by LeandroBraier** [comment]
@FAAREIA veo listo el recuadro rojo, falta que el link de Registrate lleve al formulario de newsletter o a esa sección de la home.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo todo.
Abrazo

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Gracias!!

abrazo

**Comment by mkreyness** [comment]
Aca esta el problema, se cerro por algo pendiente de Fede, pero quedo todo lo mio pendiente igual y nadie mas se acordo del tema hasta ahora.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Resolvamoslo igual ya en el otro ticket.
