### ISSUE TITLE
Mailing Invitación Pura Tierra Río Ancho. 05/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#128]
Brau, te paso un psd editable por WeTransfer para que armes un mailing para Rio Ancho.

La versión final es la V7, pero el único PSD con texto editable qur tengo es el v6. Igual las diferencias son mínimas.

abrazo

**Comment by LeandroBraier** [comment]
https://www.wetransfer.com/downloads/4f835ec55d1d78d92645387c1f0e747b20150804011036/c973f7

**Comment by braulio-evangelisti** [comment]
Lea fijate ahi, todavia no esta terminada pero para que vayas viendo y pasando feedback. Me falta el titular principal, estoy viendo como lo resuelvo para que quede como texto y no tener que pasar todo a imagen.

http://www.rioanchocolonia.com/mailing/viaje-de-sabores/

El resto de los textos busque la tipografía mas acorde.

Abrazo

**Comment by LeandroBraier** [comment]
Vamos bien Brau. Las tipografías no están buenas, buscá algunas un poco más finas aunque sean web y agregale lo que falta así lo mando al cliente y me dice si lo quieren así o quieren que lo adaptemos todavía más al formato mailing.

abrazo

**Comment by LeandroBraier** [comment]
Paso este ticket al proyecto de Rio Ancho, donde corresponde. Te aviso desde allá, abrazo
