### ISSUE TITLE
Eliminación o Suspensión de Usuarios en Torneo de Potenciados URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#129]
@mkreyness me pidieron urgente que eliminara un usuario del Torneo de Potenciados y descubrí que no tengo como hacerlo desde el CMS.

El usuario es el siguiente:

Número de usuario: 1490
Categoría: C
Nombre: LO BRUNO  ESTRUCTURAS S.A.  

Pero lo ideal sería que, apenas resuelvas esto urgente, habilites la opcion en el CMS para suspender usuarios.

abrazo

**Comment by mkreyness** [comment]
"Torneo de potenciados" es "Torneos" ?
A que llamas usuarios, corralones ?
Los corralones estan en la "Guia de Corralones", podes suspenderlo de ahi pero no saldria en la Guia de Corralones.
Y siempre podes sacarle el usuario y contraseña, con lo cual no tiene forma de ingresar, pero si el sitio no estaba en produccion todavia, no ?

**Comment by mkreyness** [comment]
Le force una password diferente, con eso no se va a poder loggear, pero no entiendo bien si eso es lo que quieren, o que no sume puntos para el torneo.
Confirmame y le borro los puntos.
Queres un editor de puntos en el CMS ?

**Comment by LeandroBraier** [comment]
Claro, no. Lo que quieren es que no participe directamente.

Dale de baja el usuario en el torneo, puede ser eso?

Quitale los puntos, si.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
es que no hay algo para torneo separado de lo que es la guia de corralones, pero le saco el codigo de usuario y password, y le borro los puntos, ok. 
Lo de usuario y password lo podes hacer siempre desde el CMS, lo de los puntos por ahora no hay como.

**Comment by LeandroBraier** [comment]
Perfecto enotnces. Entendido. Gracias!

**Comment by LeandroBraier** [comment]
Lo que quieren es que no participe del torneo pero dejalo ahi ahora. No te preocupes. Lo hablamos mañana en la reunion.

Como venis con los otros cambios de la version corredores?

**Comment by mkreyness** [comment]
Estoy en eso, hay cosas que todavia no me andan.
Si queres mirar (pero hay cosas mal):

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide2.pl?usuario=norbertocastello&clave=108811&torneo=1

**Comment by LeandroBraier** [comment]
Genial MK!

No te olvides que en la tabla de ventas deben aparecer todas las categorías.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-04 16:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si pero cuantos renglones ? Ponele que el tipo tiene 300 clientes, pongo los 300 clientes ?
No tenemos prevista paginacion.

**Comment by LeandroBraier** [comment]
Quise decir que se vean los primerso 5 de cada categoría.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ok, no hay problema.
Una cosa que no me gusta es que en el "Grupo A" hay solamente 27 corralones con objetivo, de los cuales tengo ventas informadas de solo 5, por eso aparecen 5, no estaran faltandonos datos ?

**Comment by LeandroBraier** [comment]
Son todos los que hay no te preocupes por eso.,

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-04 17:00 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Fijate ahora lo que pasa con Norberto Castello, como no tiene a nadie en la categoria "A", no le sale abajo, y en las 5 de arriba tampoco le puede decir cuantos puntos necesita para entrar.
En cambio si entras con Nicolas Sale, tiene 2 en el grupo A:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide2.pl?usuario=nicolassale&clave=123001&torneo=1

Los puntajes para subir un puesto a veces son 0 porque hay puestos empatados. Te parece que en ese caso le ponga +1 en vez de +0 ?

**Comment by LeandroBraier** [comment]
Exacto. En esos casos ponele +1.

Ahora te paso feedback de esto, ya lo vio el cliente.

Pero te lo paso en el ticket correcto jeje

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-04 17:15 GMT-03:00 mkreyness notifications@github.com:
