### ISSUE TITLE
Landing Interno "La Potencia de Klaukol"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#13]
Fede, necesito que me armes con la misma estética de fondo del Micrositio de Klaukol Impermeable Potenciado, una landing que tenga la imagen que te sumo acá y al pie un botón para descargarla y uno para imprimirla.

![muro final-klaukol-recovered](https://cloud.githubusercontent.com/assets/6719872/6931546/cca6dce4-d7e4-11e4-9c82-44900dd866ca.jpg)

Próximamente te voy a estar pasando dos fotos más. la idea es que sea un slideshow en loop y que se pueda pausar y descargar la foto elegida.

Si lo tenés armado para mañana al mediodía estamos ok. Decime el tamaño ideal que debería tener esta imagen para que se vea bien en las distintas resoluciones que contemplamos siempre.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_potencia_klaukol/
No hay botón de pausar, se puede agregar. Igualmente cuando pones el mouse encima de la foto o del botón, se pausa.

**Comment by LeandroBraier** [comment]
Genial Fede! Gracias!

Igual agreguemosle el Play y Pause en algún rinconcito. Respecto del fondo,
no debería quedar negro. Machealo con la estética del Micrositio de KIP.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-01 9:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Fijate ahora Lea, le puse el fondo que usamos para la otra landing.

**Comment by LeandroBraier** [comment]
Está perfecto. Agregale el rincóncito de ParexGroup abajo a la derecha y
estamos. Cuando tengo las fotos finales te las paso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, eso se lo agregué, fijate como quedó. En resoluciones en donde el logo se solapa con la imagen principal, lo oculté.

**Comment by LeandroBraier** [comment]
Está perfecto, Fede. Ahora te paso las fotos de todos los grupos así las sumás al SlideShow y ya queda esto.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya esta actualizada la landing. La cambié un poco porque la foto no era tan alta como antes.
Cualquier cosa avisame!
Abrazo

**Comment by LeandroBraier** [comment]
Fede, en la landing necesito que le sumes estas fotos al slideshow:

https://www.wetransfer.com/downloads/8448e83843f54312640fd8ebec25b66520150408033345/91b658df05ce41866a39f71219a4052c20150408033345/51e209

Además, necesito que abajo de todo pero arriba del footer, sumes el link al video tal cual el Newsletter. También si podés que sumés el "Mirá el Video" como un botón similar al "Descargá la foto" pero azul.

abrazo

**Comment by FAAREIA** [comment]
Ahi le puse el botón, te muestro como queda con el bloque ese del video del news en la landing. Para mi no va, queda raro, no cierra. Avisame si te parece OK lo que hice http://www.benteveo.tv/_potencia_klaukol/

![sin-titulo-5](https://cloud.githubusercontent.com/assets/6184969/7046928/785c4664-dddf-11e4-953f-aefcfcb86c47.jpg)

**Comment by LeandroBraier** [comment]
Está perfecto como vos lo hiciste, Fede. Tenés razón.

Recibiste las fotos que te mandé?

Ahora te las mando por mail solo los PNG porque el WeTRansfer tenía también
los PSDs. Subí esas fotos al final del slideshow y estamos joya con esto.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi ya esta subidas, cualquier cosa decime!
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede pero Nop.

Tenías que SUMARLAS a las que ya estaban, no reemplazarlas. Las que ya
estaban estaban bien, en el mismo slideshow A CONTINUACIÓN DE ESAS sumar
las nuevas.

Con eso estamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-08 13:09 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Solucionadooooo
