### ISSUE TITLE
Novedades ParexKlaukol en la web: Quitar visualización de "Etiquetas" 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#130]
Fede, me pidió el cliente que en la página de novedades quitemos la visualización de las etiquetas. Me avisás cuando lo hayas hecho porfa?

abrazo

**Comment by FAAREIA** [comment]
Hecho: http://parexklaukol.com.ar/novedades.html
Lo saque en la categoría Novedades de Parex Argentina. No lo saqué en la novedad en sí.

**Comment by LeandroBraier** [comment]
Gracias Fede, pero creo que no me entendiste bien.

Necesito que SOLAMENTE la parte de etiquetas no esté (tanto en novedades como en la novedad en sí). TODO LO DEMÁS si qué siga estando. Me refiero a:

"Últimas novedades" y "Categorías"

abrazo

**Comment by FAAREIA** [comment]
Osea que ni si quiera dejamos la lista de etiquetas que aparece en una noticia, y no me refiero al bloque del costado que se elimina, sino a la lista que aparece debajo de todo en una noticia.

http://parexklaukol.com.ar/novedades/klaukol-recibio-a-los-estudiantes-de-arquitectura-de-la-uba.html

**Comment by LeandroBraier** [comment]
Esas si querés dejalas. No molestan. El cliente me pidió la lista larga de la columna de la derecha nada más.

**Comment by FAAREIA** [comment]
Fijate en 1m, dale f5

**Comment by LeandroBraier** [comment]
Perfecto Fede!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
