### ISSUE TITLE
Torneo de Potenciados #6: Bases y condiciones diferenciadas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#131]
@FAAREIA y @mkreyness necesito que los corredores y los corralones de cada categoría vean bases y condiciones diferentes. Se las envié por mail . Lo amarillo no le den bola, son los textos finales.

Confirmenme porfa cuando lo pueden tener actualizado.

abrazo

**Comment by FAAREIA** [comment]
@mkreyness Ahi estuve viendo y en realidad en base a la categoría del usuario, hay que generar el link.
Hay 4 bases y condiciones.
- Cat. A y D
- Cat. B y E
- Cat. C y F
- Genéricas que no se a quien aplica ¿Lea?

**Comment by mkreyness** [comment]
En tal caso estariamos hablando de partir las Bases y Condiciones de corralones, pero las de corredores deberian seguir siendo una sola.

**Comment by LeandroBraier** [comment]
Exacto. Las genericas son de corredores.

**Comment by mkreyness** [comment]
Guardá cada template como -A.html, -B.html, etc y el de corredores seguiría siendo el R. Yo en un rato llego y hago el cambio en el programa para que en el caso de corralones discrimine por categoria.

Enviado desde mi iPhone

**Comment by mkreyness** [comment]
El programa ya lo esta tomando asi. Faltaria que los separes con esos nombres.
Avisame cualquier cosa.
Ojo que el LOGIN todavia lleva al programa viejo (torneo-con-slide.pl) y todo lo nuevo esta en torneo-con-slide2.pl, habria que ajustar el login, o pisar el programa viejo con el nuevo.

**Comment by LeandroBraier** [comment]
Buen día Fede! Avisame el lunes apenas tengas impactado esto porfa.

abrazo

**Comment by FAAREIA** [comment]
Pregunta. Hay frases tachadas, eso no va?

**Comment by LeandroBraier** [comment]
Claro. Lo tachado es lo que hay que sacar. Lo amarillo lo que hay que
agregar.

Si solo copiás y pegás y se formatea solo simplemente borrá lo tachado.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ok, el que lo tacha que lo saqué la próxima. Estamos haciendo doble laburo asi.

**Comment by FAAREIA** [comment]
@mkreyness estos son los templates que cree:
bases-condiciones-A-D-T.html
bases-condiciones-B-E-T.html
bases-condiciones-C-F-T.html
bases-condicionesT.html (corredores)

**Comment by mkreyness** [comment]
No por favor, renombralos como te dije

bases-condicionesT-A.html
bases-condicionesT-B.html
bases-condicionesT-C.html
bases-condicionesT-D.html
bases-condicionesT-E.html
bases-condicionesT-F.html
bases-condicionesT-R.html (este es el de corredores)

que es lo que el programa espera, ya que son datos que surgen del URL y de la base de datos.
Si A y D son iguales, etc. copialo 2 veces.
Es mucho mas logico que agregar toda esa inteligencia al programa.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!! abrazo grande
