### ISSUE TITLE
Web ParexKlaukol: Página LEED

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#132]
@FAAREIA , te envié por mail la info que va en la nueva sección de LEED y algunas imágenes que usamos en el news para graficarlo.

http://everstonefloors.com/graphics/logo-leed.jpg
http://catalystreview.net/wp-content/uploads/2009/05/Green-Building.jpg 
https://www.gbcsa.org.za/wp-content/uploads/2013/05/wgbc-page.jpg 

La estructura de la página sería similar a la página "Empresa", con dos apartados clickeables en un menú de la derecha.

La parte que alista productos debe llevar Link.
Te lo paso a vos porque ya tenías claro donde ubicar el link destacado dentro de la Home. El texto que tenés que poner ahi es:

Solo los productos ParexKlaukol permiten certificar construcciones sustentables LEED.
Más info (AQUI VA EL LINK)

Me parece que Braulio lo podría hacer muy rápido a esto. Lo ideal sería tener algo para mostrar mañana aunque sea a última hora.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA y @braulio-evangelisti ! Recibieron este pedido? Me confirmarían si podemos llegar a tenerlo para hoy aunque sea a ultima hora?

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ya esta listo. Lo podes ver en:
http://parexklaukol.com.ar/index2.html
De ahi navegas y listo.

Abrazo

**Comment by LeandroBraier** [comment]
Quedó excelente Fede! Gracias!! Muy bien diseñado.

Solo 1 detalle: faltan los links a los productos en el listado.

Con eso estamos.

abrazo

**Comment by FAAREIA** [comment]
Hecho, solo hay 1 que no está. Es el mismo de la vez pasada.

**Comment by LeandroBraier** [comment]
Perfecto, gracias Fede!

abrazo

**Comment by LeandroBraier** [comment]
Fede, quedó perfecto. El lunes a primera hora subilo a producción nomás. Quizá vengan pequeños cambios después pero lo quieren subido.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA 

Porfa dale prioridad a subir esto apenas arranques a laburar hoy.

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/

**Comment by LeandroBraier** [comment]
Excelente.Gracias Fede!

**Comment by LeandroBraier** [comment]
@FAAREIA muy pequeños cambios en esta sección.

1) Cambiar el logo de LEED en la home por el siguiente:

![leed](https://cloud.githubusercontent.com/assets/6719872/9173570/6bda946c-3f51-11e5-8526-f05d1c757cc4.png)

2) Cambiar el texto a: "Los productos ParexKlaukol permiten certificar construcciones sustentables LEED. Más info aquí" (sin el "solo" y sin los puntos suspensivos)

Sección LEED:

3) Poner el listado de productos como una nota más aparte, que diga Productos con Certificación LEED.

En esta nota, subdividí los productos también en Categorías. Es solo 5 filas que tenés que agregar a lo que ya está: Adhesivos, Pastinas, Fachadas, Morteros para la construcción, Impermeabilizantes.

<img width="838" alt="captura de pantalla 2015-08-10 a la s 13 26 26" src="https://cloud.githubusercontent.com/assets/6719872/9176461/d19f71c2-3f61-11e5-89c3-f82f5f32f76b.png">

Cualquier duda avisame
abrazo

**Comment by FAAREIA** [comment]
Hecho.
Ordené la tabla como aparece en la foto. El producto Klaukol Hiperflex Fluido no estaba pero lo incluí como "Adhesivos"

**Comment by LeandroBraier** [comment]
Gracias Fede!

1) Quitalo a Hiperflex por ahora de esta sección.

2) Fijate si podés destacar con algún color las secciones (adhesivos, pastinas, etc) para que sobresalga un pocomás como en el excel que te pasé.

abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

1) Quitalo a Hiperflex por ahora de esta sección.

2) Fijate si podés destacar con algún color las secciones (adhesivos, pastinas, etc) para que sobresalga un poco más como en el excel que te pasé.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo saqué y lo destaqué casi al mismo nivel que esta en el excel.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!!!

Quedó excelente.

abrazo

**Comment by LeandroBraier** [comment]
Fede, me volvieron a pedir cambios acá, muy simples:

HOME

1) Cambiar texto que lleva a Leed a: Nuestros productos otorgan puntos para certificación LEED de construcciones sustentables. 

SECCIÓN LEED

2) Que la lista de productos vuelve a estar donde estaba, pero sin quitar el link que subiste en el menú de la izquierda. Si se puede que ese link lleve a esa parte de la misma página mejor. Sino que quede como está.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! Quedó perfecto.
