### ISSUE TITLE
Mailing de Bienvenida de Agosto. 10/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#133]
Brau, necesitamos actualizar el header del mailing de bienvenida con los premios de Agosto.

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Los premios son estos:

![posteo-premios-agosto](https://cloud.githubusercontent.com/assets/6719872/9175838/0cdbfe6c-3f5e-11e5-9ff9-5ef2d127111c.png)

Te paso por wetransfer el editable en alta por las dudas.

https://www.wetransfer.com/downloads/7fa4284b57fb2228d7a04f6918d1a82820150810155047/7d3a31

abrazo

**Comment by braulio-evangelisti** [comment]
Lea fijate ahi.

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-ago.html

Abrazo

**Comment by LeandroBraier** [comment]
Bastante bien.

1) Fijate que el color rojo que usaste no es el mismo que en el resto del
mailing.

2) Se puede hacer sin el fondo gris, que quede sobre fondo blanco como el
resto del mailing?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Ahi lo pase al rojo klaukol y cambie el fondo gris por el blanco

Abrazo

**Comment by LeandroBraier** [comment]
Quedó perfecto., Brau. Gracias!
