### ISSUE TITLE
Mailing de Bienvenida Torneo de Potenciados. 11/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#134]
Buen día @braulio-evangelisti para hoy a la tarde necesitaría una adatpación del mailing de bienvenida de vendedores pero que sirva para el Torneo de Potenciados.

Por mailing de bienvenida de Vendedores me refiero a este:
http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

El Torneo de Potenciados es este:

http://www.parexklaukol.com.ar/torneo-corralones/login.html

El logo te lo paso acá:

![logo-torneo-potenciados-klaukol](https://cloud.githubusercontent.com/assets/6719872/9196939/94b883d4-4006-11e5-8435-e619203429de.png)

Es un Torneo virtual en el que se van sumando las compras que hacen los distintos corralones de los productos Klaukol. El que más crece porcentualmente en compras respecto del año pasado gana. Pero no solo gana él, sino también el representante comercial de Klaukol que le vendió.

Los corralones se dividen en 6 categorías: la A y la D tienen un premio, la B y la E tienen otro y la C y la F tienen otro premio. A su vez, el representante comercial cuyo corralón gana, obtiene el mismo premio que el corralón.

Por eso hay mails de bienvenida en versiones levemente distintas según las categorías. Por esto lo que necesito es 4 versiones.

1) Mailing de Bienvenida a Corralones A y D (Premio al Caribe y 100.000 pesos) -- Va con PSD slide-corralones-2A.psd
2) Mailing de Bienvenida a Corralones B y E (Premio a Brasil y 50.000 pesos) -- Va con PSD slide-corralones-2B.psd
3) Mailing de Bienvenida a Corralones C y F (Premio a Brasil y 25.000 pesos) -- Va con PSD slide-corralones-2C.psd
4) Mailing de Bienvenida a Representantes Comerciales -- Va con PSD slide-corredores.psd

El PSD del logo te lo paso junto con los PSD de los premios que van arriba para las diferencias versiones. La parte del PSD que es importante es "Premios para todos" + los 3 círculos de premios + "Cuantas más bolsas comprás, más crecés. ¡El que más crece, gana!

Aquí está todo:
https://www.wetransfer.com/downloads/431f78646c36cc8372cc4a613d256a4420150811121328/9a00bf

"""El texto debajo de los premios es el siguiente para las versiones 1, 2 y 3:"""

Bienvenido al

LOGO TORNEO DE POTENCIADOS

Una competencia donde si crecés en tus compras de productos Klaukol obtenés increíbles premios para vos y tus vendedores.

Hemos recibido tus datos personales y con ellos pudimos crear un acceso especial.

BOTÓN: HACÉ CLIC PARA LOGEARTE AUTOMÁTICAMENTE

Usuario:  
Contraseña:

¿Cómo participo?

¡Ya estás participando! Simplemente entrá a nuestra plataforma para ver cómo venís en el ranking y contactá a tu representante comercial para planificar tus compras de este semestre.

Debajo de estos van los mismos footer del mailing de bienvenida de vendedores:

Sección Facebook

Sección Guía de Corralones

Footer de 0800 + Parex Group

"""El texto debajo de los premios es el siguiente para la versión 4 para representantes comerciales:"""

Bienvenido al

LOGO TORNEO DE POTENCIADOS

Una competencia donde si crecés en tus ventas de productos Klaukol obtenés increíbles premios para vos y tus clientes.

Hemos recibido tus datos personales y con ellos pudimos crear un acceso especial.

BOTÓN: HACÉ CLIC PARA LOGEARTE AUTOMÁTICAMENTE

Usuario:  
Contraseña:

¿Cómo participo?

¡Ya estás participando! Simplemente entrá a nuestra plataforma para ver cómo vienen tus clientes en el ranking y contactalos para planificar tus ventas de este semestre.

Debajo de estos van los mismos footer del mailing de bienvenida de vendedores:

Sección Facebook

Sección Guía de Corralones

Footer de 0800 + Parex Group

Confirmame porfa si podés tener la versión 1 para hoy a la tarde.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti como venis con esto? Te lo pedí como prioridad junto con el otro mail de bienvenida.

**Comment by braulio-evangelisti** [comment]
Lea:

Categorias A y D:
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html

Categorias B y E:
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e.html

Categorias C y F:
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f.html

Representantes Comerciales:
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-r-c.html

Sigo con el #133 

Fede me dijo que si no lo ayudo con colocadores mañana y pasado, no llegamos para la fecha asi que voy a estar con eso jueves y viernes.

Abrazo

**Comment by LeandroBraier** [comment]
Brau, entiendo. Entonces recuperamos horas más adelante.

FEEDBACK MAILING BIENVENIDA: No me sirve ese header. Agarraste lo que te pasé y lo pegaste. Necesito que lo adaptes a un formato más mailing, no un bloque gigante que ya está diseñado. Entendés lo que te digo? porque lo mismo aplica en el de Vendedores. No copies y pegues, rediseñá.

abrazo

**Comment by braulio-evangelisti** [comment]
Perfecto Lea. Me pongo con rediseño. 
Por favor tené en cuenta se necesita mas tiempo para rediseñar.
Confirmame si va exactamente la misma informacion que esta en los headers.

Abrazo

**Comment by LeandroBraier** [comment]
La info está OK.

1) Fijate si podés hacer que el header quede orgánicamente bien con el
resto del mailing, parecen dos cosas distintas.

2) El fondo blanco sin nada queda muy desprovisto, como que las cosas
quedaran sueltas por ahí.

Buscá en el rediseño mejorar ambas cosas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-12 14:54 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Ahi estan Lea, son los mismos links.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Braulio! Están todos perfectos menos el de de RCD. Por favor sacale los 4 productos con fondo rojo que no quedan bien. Sacalo y listo, borrá ese espacio. Gracias!

abrazo

**Comment by braulio-evangelisti** [comment]
Listoooo

**Comment by LeandroBraier** [comment]
Gracias Brau!!

Pequeños cambios pedidos por el cliente:

""Categorias A y D:""
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html

Necesito que en el recuadro de Viaje al Caribe, donde dice "para el ganador" diga "hasta 100 mil pesos"

""Categorias B y E:""
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e.html

Necesito que en el recuadro de Viaje a Brasil, donde dice "para el ganador" diga "hasta 50 mil pesos"

Donde dice "en productos para 2º y 3º puesto" que diga "en productos para 2do al 5to puesto" 

""Categorias C y F:""
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f.html

Necesito que en el recuadro de Viaje a Brasil, donde dice "para el ganador" diga "hasta 20 mil pesos"

Donde dice "en productos para 2º y 3º puesto" que diga "en productos para 2do al 15to puesto" 

Confirmame porfa apenas lo tengas aplicado.

abrazo

**Comment by braulio-evangelisti** [comment]
en ByE esdel 2° al 5° y en C y F del 2° al 15°?

**Comment by LeandroBraier** [comment]
Si, así es. Me lo pidieron cambiar. Después les voy a tener que pedir
sumarlo a las bases y condiciones.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Listo Lea

Me pongo con colocadores con Fede

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

**Comment by LeandroBraier** [comment]
abrazo grande y gracias por el esfuerzo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti me pasás el linka actualizado del mailing de Representantes comerciales porfa? Es el único que me falta.

abraoz

**Comment by braulio-evangelisti** [comment]
Este era?

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-r.html

**Comment by LeandroBraier** [comment]
Exacto. Ese. Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti para el lunes temprano necesito una adaptación de los tres primeros mailings:

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e.html

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f.html

En lugar de la imagen del header, necesito que le diseñes un header que diga lo siguiente:

TITULAR GRANDE: Últimos días para la primer premiación!

No dejes de chequear tu posición en la tabla y avanzar para que tus vendedores ganen el primer premio trimestral.
Este 30/9 tu corralón puede potenciarse como nunca.

A más tardar a las 11 am del lunes lo necesitaríamos tener. Me confirmás porfa?

abrazo

**Comment by braulio-evangelisti** [comment]
Si, si la imagen del encabezado es igual para los 3 news llegamos bien.

Abrazo

**Comment by LeandroBraier** [comment]
Si, es igual Brau. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-25 19:55 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Buen dia Lea

Fijate si algo asi puede ir:

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d-2.html
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e-2.html
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f-2.html

Abrazo

**Comment by LeandroBraier** [comment]
Hola Brau!

Está muy bueno

Solo detalles:
1. Dale más color, yo lo veo muy gris. 
2. Que la tabla que se vea diga: "Tabla Trimestral" no "semestral"

abrazo

**Comment by LeandroBraier** [comment]
Brau, leiste mi feedback? Lo necesitamos hoy a esto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness , necesito que mañana a primera hora envíes a todos los corralones del Torneo de Potenciados esta versión del mailing de Bienvenida.

Categoría A y D
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d-2.html

Categoría B y E
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e-2.html

Categoría C y F
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f-2.html

abrazo

**Comment by mkreyness** [comment]
ok igual primero te mando uno de prueba de c/u esta noche, te parece ?

**Comment by LeandroBraier** [comment]
Dale perfecto.

**Comment by mkreyness** [comment]
```
anoche al final estuve a full con DelViento.
Ahora se me ocurrio probar esto antes de mandar y mira el link que
me ofrecio en el mail:
```

http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854

```
es de VENDEDORES, no de TORNEO.
Ahora arreglo todos los templates y vuelvo a probar.


El 28/09/2015 a las 20:06,
  LeandroBraier escribió:

Dale perfecto.
  El sep 28, 2015 7:41 PM, "mkreyness"
  <notifications@github.com> escribió:

  > ok igual primero te mando uno de prueba de c/u esta noche, te
  parece ?
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-143893986
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Menos mal MK!! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-29 8:18 GMT-03:00 mkreyness notifications@github.com:

> anoche al final estuve a full con DelViento.
> Ahora se me ocurrio probar esto antes de mandar y mira el link que
> me ofrecio en el mail:
> 
> http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
> 
> es de VENDEDORES, no de TORNEO.
> Ahora arreglo todos los templates y vuelvo a probar.
> 
> El 28/09/2015 a las 20:06,
> LeandroBraier escribió:
> 
> Dale perfecto.
> El sep 28, 2015 7:41 PM, "mkreyness"

**Comment by mkreyness** [comment]
```
Ahi te mande uno.
Lo que estoy viendo (y me cuesta creer que haya estado realmente asi
en su momento) es que los HTML de mailing anterior TAMBIEN estaban
diciendo esto.


El 29/09/2015 a las 8:35, LeandroBraier
  escribió:

Menos mal MK!! Gracias!

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-09-29 8:18 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > anoche al final estuve a full con DelViento.
  > Ahora se me ocurrio probar esto antes de mandar y mira el
  link que
  > me ofrecio en el mail:
  >
  >
  >
```

http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
      >
      > es de VENDEDORES, no de TORNEO.
      > Ahora arreglo todos los templates y vuelvo a probar.
      >
      >
      > El 28/09/2015 a las 20:06,
      > LeandroBraier escribió:
      >
      > Dale perfecto.
      > El sep 28, 2015 7:41 PM, "mkreyness"
      > notifications@github.com escribió:
      >
      > > ok igual primero te mando uno de prueba de c/u esta
      noche, te
      > parece ?
      > >
      > > —
      > > Reply to this email directly or view it on GitHub
      > >
      > <
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-143893986
      > >
      > > .
      >
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144029859
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
No te puedo creer. Me muero. NO puede ser que hayan cambiado alguna otra
cosa después? Yo los probé y andaban bien en su momento.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-29 8:38 GMT-03:00 mkreyness notifications@github.com:

> Ahi te mande uno.
> Lo que estoy viendo (y me cuesta creer que haya estado realmente asi
> en su momento) es que los HTML de mailing anterior TAMBIEN estaban
> diciendo esto.
> 
> El 29/09/2015 a las 8:35, LeandroBraier
> escribió:
> 
> Menos mal MK!! Gracias!
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> 2015-09-29 8:18 GMT-03:00 mkreyness
> notifications@github.com:
> 
> > anoche al final estuve a full con DelViento.
> > Ahora se me ocurrio probar esto antes de mandar y mira el
> > link que
> > me ofrecio en el mail:
> 
> http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
> 
> > es de VENDEDORES, no de TORNEO.
> > Ahora arreglo todos los templates y vuelvo a probar.
> > 
> > El 28/09/2015 a las 20:06,
> > LeandroBraier escribió:
> > 
> > Dale perfecto.
> > El sep 28, 2015 7:41 PM, "mkreyness"

**Comment by mkreyness** [comment]
```
Si, yo me imagino que debe haber sido algun toque reciente al estar
haciendo estos nuevos, porque obviamente lo primero que vos y yo
probamos al recibirlo es el link.

El 29/09/2015 a las 8:41, LeandroBraier
  escribió:

No te puedo creer. Me muero. NO puede ser que hayan
  cambiado alguna otra
  cosa después? Yo los probé y andaban bien en su momento.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-09-29 8:38 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Ahi te mande uno.
  > Lo que estoy viendo (y me cuesta creer que haya estado
  realmente asi
  > en su momento) es que los HTML de mailing anterior TAMBIEN
  estaban
  > diciendo esto.
  >
  >
  > El 29/09/2015 a las 8:35, LeandroBraier
  > escribió:
  >
  > Menos mal MK!! Gracias!
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-09-29 8:18 GMT-03:00 mkreyness
  > <notifications@github.com>:
  >
  > >
  > >
  > >
  > >
  > >
  > > anoche al final estuve a full con DelViento.
  > > Ahora se me ocurrio probar esto antes de mandar y mira
  el
  > link que
  > > me ofrecio en el mail:
  > >
  > >
  > >
  >
  >
```

http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
      > >
      > > es de VENDEDORES, no de TORNEO.
      > > Ahora arreglo todos los templates y vuelvo a probar.
      > >
      > >
      > > El 28/09/2015 a las 20:06,
      > > LeandroBraier escribió:
      > >
      > > Dale perfecto.
      > > El sep 28, 2015 7:41 PM, "mkreyness"
      > > notifications@github.com escribió:
      > >
      > > > ok igual primero te mando uno de prueba de c/u esta
      > noche, te
      > > parece ?
      > > >
      > > > —
      > > > Reply to this email directly or view it on GitHub
      > > >
      > > <
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-143893986
      > > >
      > > > .
      > >
      > > >
      > > —
      > > Reply to this email directly or view
      > > it on GitHub.
      > >
      > > —
      > > Reply to this email directly or view it on GitHub
      > >
      > <
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144029859
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144034147
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
```
y tambien esta el tema de "ver este mail online" que no funciona
porque el login da error, se lo elimino como hicimos la vez pasada,
ok ?

El 29/09/2015 a las 8:59, Marcelo
  Kreyness escribió:



  Si, yo me imagino que debe haber sido algun toque reciente al
  estar haciendo estos nuevos, porque obviamente lo primero que vos
  y yo probamos al recibirlo es el link.

  El 29/09/2015 a las 8:41,
    LeandroBraier escribió:

  No te puedo creer. Me muero. NO puede ser que hayan
    cambiado alguna otra
    cosa después? Yo los probé y andaban bien en su momento.

    Leandro Braier
    Producción Audiovisual & Social Media
    Benteveo Producciones <http://benteveo.tv>
    Móvil 1158717399

    2015-09-29 8:38 GMT-03:00 mkreyness <notifications@github.com>:

    >
    >
    >
    >
    >
    > Ahi te mande uno.
    > Lo que estoy viendo (y me cuesta creer que haya estado
    realmente asi
    > en su momento) es que los HTML de mailing anterior TAMBIEN
    estaban
    > diciendo esto.
    >
    >
    > El 29/09/2015 a las 8:35, LeandroBraier
    > escribió:
    >
    > Menos mal MK!! Gracias!
    >
    > Leandro Braier
    > Producción Audiovisual & Social Media
    > Benteveo Producciones <http://benteveo.tv>
    > Móvil 1158717399
    >
    > 2015-09-29 8:18 GMT-03:00 mkreyness
    > <notifications@github.com>:
    >
    > >
    > >
    > >
    > >
    > >
    > > anoche al final estuve a full con DelViento.
    > > Ahora se me ocurrio probar esto antes de mandar y mira
    el
    > link que
    > > me ofrecio en el mail:
    > >
    > >
    > >
    >
    >
    http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
    > >
    > > es de VENDEDORES, no de TORNEO.
    > > Ahora arreglo todos los templates y vuelvo a probar.
    > >
    > >
    > > El 28/09/2015 a las 20:06,
    > > LeandroBraier escribió:
    > >
    > > Dale perfecto.
    > > El sep 28, 2015 7:41 PM, "mkreyness"
    > > <notifications@github.com>
    escribió:
    > >
    > > > ok igual primero te mando uno de prueba de c/u
    esta
    > noche, te
    > > parece ?
    > > >
    > > > —
    > > > Reply to this email directly or view it on GitHub
    > > >
    > > <
    > >
    >
    https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-143893986
    > > >
    > > > .
    > >
    > > >
    > > —
    > > Reply to this email directly or view
    > > it on GitHub.
    > >
    > > —
    > > Reply to this email directly or view it on GitHub
    > >
    > <
    >
    https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144029859
    > >
    >
    > > .
    > >
    > —
    > Reply to this email directly or view
    > it on GitHub.
    >
    > —
    > Reply to this email directly or view it on GitHub
    >
    <https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144034147>
    > .
    >
    —
      Reply to this email directly or view

        it on GitHub.
```

**Comment by mkreyness** [comment]
```
ja ja, menos mal que se los saque, porque esos links de "ver online"
llevaban al texto del mailing VIEJO.
Bueno te mando un ULTIMO de prueba y con tu ok lo largo.

El 29/09/2015 a las 9:02, Marcelo
  Kreyness escribió:



  y tambien esta el tema de "ver este mail online" que no funciona
  porque el login da error, se lo elimino como hicimos la vez
  pasada, ok ?

  El 29/09/2015 a las 8:59, Marcelo
    Kreyness escribió:



    Si, yo me imagino que debe haber sido algun toque reciente al
    estar haciendo estos nuevos, porque obviamente lo primero que
    vos y yo probamos al recibirlo es el link.

    El 29/09/2015 a las 8:41,
      LeandroBraier escribió:

    No te puedo creer. Me muero. NO puede ser que
      hayan cambiado alguna otra
      cosa después? Yo los probé y andaban bien en su momento.

      Leandro Braier
      Producción Audiovisual & Social Media
      Benteveo Producciones <http://benteveo.tv>
      Móvil 1158717399

      2015-09-29 8:38 GMT-03:00 mkreyness <notifications@github.com>:

      >
      >
      >
      >
      >
      > Ahi te mande uno.
      > Lo que estoy viendo (y me cuesta creer que haya estado
      realmente asi
      > en su momento) es que los HTML de mailing anterior
      TAMBIEN estaban
      > diciendo esto.
      >
      >
      > El 29/09/2015 a las 8:35, LeandroBraier
      > escribió:
      >
      > Menos mal MK!! Gracias!
      >
      > Leandro Braier
      > Producción Audiovisual & Social Media
      > Benteveo Producciones <http://benteveo.tv>
      > Móvil 1158717399
      >
      > 2015-09-29 8:18 GMT-03:00 mkreyness
      > <notifications@github.com>:
      >
      > >
      > >
      > >
      > >
      > >
      > > anoche al final estuve a full con DelViento.
      > > Ahora se me ocurrio probar esto antes de mandar y
      mira el
      > link que
      > > me ofrecio en el mail:
      > >
      > >
      > >
      >
      > http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
      > >
      > > es de VENDEDORES, no de TORNEO.
      > > Ahora arreglo todos los templates y vuelvo a probar.
      > >
      > >
      > > El 28/09/2015 a las 20:06,
      > > LeandroBraier escribió:
      > >
      > > Dale perfecto.
      > > El sep 28, 2015 7:41 PM, "mkreyness"
      > > <notifications@github.com>
      escribió:
      > >
      > > > ok igual primero te mando uno de prueba de c/u
      esta
      > noche, te
      > > parece ?
      > > >
      > > > —
      > > > Reply to this email directly or view it on
      GitHub
      > > >
      > > <
      > >
      > https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-143893986
      > > >
      > > > .
      > >
      > > >
      > > —
      > > Reply to this email directly or view
      > > it on GitHub.
      > >
      > > —
      > > Reply to this email directly or view it on GitHub
      > >
      > <
      > https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144029859
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      > <https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144034147>
      > .
      >
      —
        Reply to this email directly or view


          it on GitHub.
```

**Comment by LeandroBraier** [comment]
Dale, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-29 9:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
saliendo

El 29/09/2015 a las 9:26, LeandroBraier
  escribió:

Dale, gracias!

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-09-29 9:07 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > ja ja, menos mal que se los saque, porque esos links de "ver
  online"
  > llevaban al texto del mailing VIEJO.
  > Bueno te mando un ULTIMO de prueba y con tu ok lo largo.
  >
  > El 29/09/2015 a las 9:02, Marcelo
  > Kreyness escribió:
  >
  >
  >
  >
  > y tambien esta el tema de "ver este mail online" que no
  funciona
  > porque el login da error, se lo elimino como hicimos la vez
  > pasada, ok ?
  >
  > El 29/09/2015 a las 8:59, Marcelo
  > Kreyness escribió:
  >
  >
  >
  > Si, yo me imagino que debe haber sido algun toque reciente al
  > estar haciendo estos nuevos, porque obviamente lo primero que
  > vos y yo probamos al recibirlo es el link.
  >
  > El 29/09/2015 a las 8:41,
  > LeandroBraier escribió:
  >
  > No te puedo creer. Me muero. NO puede ser que
  > hayan cambiado alguna otra
  > cosa después? Yo los probé y andaban bien en su momento.
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-09-29 8:38 GMT-03:00 mkreyness
  <notifications@github.com>:
  >
  > >
  > >
  > >
  > >
  > >
  > > Ahi te mande uno.
  > > Lo que estoy viendo (y me cuesta creer que haya estado
  > realmente asi
  > > en su momento) es que los HTML de mailing anterior
  > TAMBIEN estaban
  > > diciendo esto.
  > >
  > >
  > > El 29/09/2015 a las 8:35, LeandroBraier
  > > escribió:
  > >
  > > Menos mal MK!! Gracias!
  > >
  > > Leandro Braier
  > > Producción Audiovisual & Social Media
  > > Benteveo Producciones <http://benteveo.tv>
  > > Móvil 1158717399
  > >
  > > 2015-09-29 8:18 GMT-03:00 mkreyness
  > > <notifications@github.com>:
  > >
  > > >
  > > >
  > > >
  > > >
  > > >
  > > > anoche al final estuve a full con DelViento.
  > > > Ahora se me ocurrio probar esto antes de mandar y
  > mira el
  > > link que
  > > > me ofrecio en el mail:
  > > >
  > > >
  > > >
  > >
  > >
  >
```

http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?usuario=elcanadon&clave=127854
      > > >
      > > > es de VENDEDORES, no de TORNEO.
      > > > Ahora arreglo todos los templates y vuelvo a
      probar.
      > > >
      > > >
      > > > El 28/09/2015 a las 20:06,
      > > > LeandroBraier escribió:
      > > >
      > > > Dale perfecto.
      > > > El sep 28, 2015 7:41 PM, "mkreyness"
      > > > notifications@github.com
      > escribió:
      > > >
      > > > > ok igual primero te mando uno de prueba de c/u
      > esta
      > > noche, te
      > > > parece ?
      > > > >
      > > > > —
      > > > > Reply to this email directly or view it on
      > GitHub
      > > > >
      > > > <
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-143893986
      > > > >
      > > > > .
      > > >
      > > > >
      > > > —
      > > > Reply to this email directly or view
      > > > it on GitHub.
      > > >
      > > > —
      > > > Reply to this email directly or view it on GitHub
      > > >
      > > <
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144029859
      > > >
      > >
      > > > .
      > > >
      > > —
      > > Reply to this email directly or view
      > > it on GitHub.
      > >
      > > —
      > > Reply to this email directly or view it on GitHub
      > > <
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144034147
      > >
      > > .
      > >
      > —
      > Reply to this email directly or view
      >
      >
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/134#issuecomment-144039184
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Gracias MK!
