### ISSUE TITLE
Juego Pase de Gol. 14/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#135]
Buen día @mkreyness !

Ya tenemos el nuevo juego de Klaukol, a lanzar el lunes que viene. Descargá el swf armado y el FLA desde acá:

https://www.wetransfer.com/downloads/d60414cc94d9e8b3604e21c80465e39820150810180507/f3ca1561cde9c00e2287e4a351a8152220150810180507/8d7608

Esta vez parece ser más sencillo tomar los puntos. FIjate este código de ActionScript. Si me pasás la URL creo que ya está, pero confirmame:

"""stop();
Mouse.show();

_root.ambiance.gotoAndPlay("crowdoff");

set ("playerName", _root.playerName);
set ("playerEmail", _root.playerEmail);
set ("playerScore", gameScore);
set ("gameID", _root.gameID);
set ("playerUID", _root.playerUID);

// set scoreURL which is the URL that pushes the score to the database
set ("http://www.yoursite.com/gamescore/", _root.scoreURL);
//post the score to scoreURL
loadVariablesNum(scoreURL, 0, "POST");"""

abrazo

**Comment by mkreyness** [comment]
```
Bajado. Me quedan solo 4 dias de la version de prueba de Flash, me
parece que me va a joder justo cuando mas falta haga.

Cuando trato de abrirlo me dice que ActionScript 1.0 ya no esta
soportado, y que le va a hacer cambios, asi que no se cuanto veo
realmente de lo que hay, pero eso que pusiste ahi lo veo.

Por lo que vimos no sirve pasar la identificacion del usuario DENTRO
del URL, tiene que ir todo separado en variables "flashvars"
separadas.

Lo correcto seria reemplazar el "post to URL" por algo como esto,
pero no se que poner donde te marque como "OJO", que seria el
parametro que me trae el puntaje, porque ninguna de esas variables
que ponen en el "scoreURL" es el score propiamente dicho me parece.

        var callback:Object=this.root.loaderInfo.parameters.callback
;
        var usuario:Object=this.root.loaderInfo.parameters.usuario ;
        var clave:Object=this.root.loaderInfo.parameters.clave;
        var juego:Object=this.root.loaderInfo.parameters.juego;
        var urlVariables : URLVariables = new URLVariables ();
        urlVariables['usuario'] = usuario.toString();
        urlVariables['clave'] = clave.toString();    
        urlVariables['juego'] = juego.toString();    
        urlVariables['gameScore'] = gameScore; 

        var request : URLRequest = new URLRequest  (
callback.toString() );
        request.data = urlVariables;
        request.method = URLRequestMethod.GET;
        navigateToURL(request,"_self") ;

y despues me tenes que decir como interpretar el gameScore.

Fijate si podes compilar uno asi y yo hago la parte externa
correspondiente a las flashvars y lo sacamos andando esta tarde.


El 12/08/2015 a las 9:48, LeandroBraier
  escribió:


  Buen día @mkreyness
    !
  Ya tenemos el nuevo juego de Klaukol, a lanzar el lunes que
    viene. Descargá el swf armado y el FLA desde acá:
  https://www.wetransfer.com/downloads/d60414cc94d9e8b3604e21c80465e39820150810180507/f3ca1561cde9c00e2287e4a351a8152220150810180507/8d7608
  Esta vez parece ser más sencillo tomar los puntos. FIjate este
    código de ActionScript. Si me pasás la URL creo que ya está,
    pero confirmame:
  """stop();
    Mouse.show();
  _root.ambiance.gotoAndPlay("crowdoff");
  set ("playerName", _root.playerName);
    set ("playerEmail", _root.playerEmail);
    set ("playerScore", gameScore);
    set ("gameID", _root.gameID);
    set ("playerUID", _root.playerUID);
  // set scoreURL which is the URL that pushes the score to the
    database
    set ("http://www.yoursite.com/gamescore/",
    _root.scoreURL);
    //post the score to scoreURL
    loadVariablesNum(scoreURL, 0, "POST");"""
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Entiendo MK. Lo puedo cambiar, no hay problema. En un rato te lo paso y lo probamos.

Para mi el juego debería sumar 100 puntos de la Comunidad pero muuuy de a poco. Por ejemplo, que cada 200 puntos del juego sume 25 puntos de la Comunidad.

abrazo

**Comment by LeandroBraier** [comment]
MK, no me llegó cual es el parámetro que marcaste como "OJO". Sería el game score?

El gamescore interpretalo como te decía:

200 puntos en el juego = 25 puntos de la Comunidad.

Máximo de puntos de la Comunidad que puede conseguir con el juego = 100

Confirmame el código y lo compilo y te lo mando para probar.

abrazo

**Comment by mkreyness** [comment]
si, eso es lo unico que cambia de lo que hay en el codigo del 
minesweeper, habia empezado a escribir "ojo..." pero despues me 
arrepenti y lo borre.

**Comment by LeandroBraier** [comment]
Hecho. Aquí va:

https://www.wetransfer.com/downloads/eed07fe9b00590fdfd54d5cfd55f8c0d20150812180010/72b2f3

Probemoslo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-12 14:47 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
http://parexklaukol.com.ar/cgi-bin/jugar.pl?usuario=marcelokreyness&clave=pepe&id=11

Ojo que tiene un link abajo que dice "instrucciones para jugar". Lo 
parametrice (si no siempre iban las instrucciones del "BuscaKlaukol", 
habria que hacer algo similar con esto y poner el URL en el CMS como 
ahora puse el del BuscaKlaukol.

El juego anda barbaro, pero en ningun momento esta llamando al codigo, o 
sea que hay algun problema de logica (siempre vuelve a presentar el 
boton "Jugar").
Tampoco me da error.

**Comment by LeandroBraier** [comment]
Cómo hacemos entonces? Yo puse el código que vos me pasaste.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-12 16:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Es que pareceria que nunca esta siendo llamado.
Voy a ver si lo puedo debuggear con la poca vida que le queda a mi Flash.
Te aviso en cuanto sepa que cambiarle.

**Comment by mkreyness** [comment]
Si, porque ese lugar donde estaba era una inicializacion, pero no se ni 
como buscar donde realmente estaba siendo invocado.
Vos tenes idea en que fotograma o corno sea esta lo que muestra el puntaje ?
porque ahi es donde, en vez de poner el boton "jugar de nuevo" hay que 
pegar este codigo:

```
    var callback:Object=this.root.loaderInfo.parameters.callback ;
         var usuario:Object=this.root.loaderInfo.parameters.usuario ;
         var clave:Object=this.root.loaderInfo.parameters.clave;
         var juego:Object=this.root.loaderInfo.parameters.juego;
         var urlVariables:URLVariables = new URLVariables ();
         urlVariables['usuario'] = usuario.toString();
         urlVariables['clave'] = clave.toString();
         urlVariables['juego'] = juego.toString();
         urlVariables['gameScore'] = gameScore;

         var request:URLRequest = new URLRequest (callback.toString() );
         request.data = urlVariables;
         request.method = URLRequestMethod.GET;
         navigateToURL(request,"_self") ;
```

**Comment by LeandroBraier** [comment]
Ahi va de nuevo el SWF!!

https://www.wetransfer.com/downloads/b0e57773b5486fea0436a69628502c0520150812195829/12da6c

Solo le sacaste unas lineas del final por lo que vi pero como está más
prolijo el tema de espacios puede funcionar.

Decime.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-12 16:41 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, no me entendiste.
Esto que puse en el mail es lo que ya habia en lo que me mandaste, no le 
hice nada, solo copie del .fla y lo pegue en el mail.
Lo que digo es que "este codigo" es lo que hay que cambiar de lugar, a 
donde sea que se muestra el puntaje, hiciste ese cambio ?

**Comment by LeandroBraier** [comment]
Lo puse en el mismo lugar donde estaba. Porque ahí es donde se dicen los
puntos y donde estaba ubicado el código que te mandé inicialmente, donde
sugería el flash que enviaramos a una URL externa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-12 17:13 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Yo ni lo puedo depurar, me tira todo tipo de errores de compilacion 
porque esto es actionscript 1 y mi version es 3, asi que no se donde 
llega y que hace.

Proba de poner esto a ver si anda, yo lo que me temo es que en el 
proyecto no esta el URLRequest ese y no debe estar compilandote bien.
Aca hice un mix de mi tecnica para averiguar las FlashVars y la de ellos 
para llamar a un URL:

  var callback:Object=this.root.loaderInfo.parameters.callback ;
  var usuario:Object=this.root.loaderInfo.parameters.usuario ;
  var clave:Object=this.root.loaderInfo.parameters.clave;
  var juego:Object=this.root.loaderInfo.parameters.juego;
  urlVariables['gameScore'] = gameScore;

loadVariablesNum("http://www.parexklaukol.com.ar" + callback + "?" +
     "usuario=" + usuario.toString() +  "clave=" + clave.toString() +  
"juego=" + juego.toString() +
     "gameScore=" + gameScore.toString(), 0, "GET");

**Comment by LeandroBraier** [comment]
Aqui va de vuelta Marce:

https://www.wetransfer.com/downloads/fe8ba45a7a2a44a527f4dc332b1ce7ef20150812210538/5bbb13

Ojalá que ahora funcione pero sino lo seguimos mañana, no es tan urgente,
venimos bien.

**Comment by mkreyness** [comment]
No, es lo mismo. Nunca llama al URL, ni muestra ningun error.
No tenes forma de poner que muestre algun cartelito ?
Lo ideal seria que el flash TERMINARA despues de llamar al URL, porque, 
si estuviera realmente llamando a mi URL, el mio cuando termina vuelve a 
levantar la pagina del juego completa (para actualizar el puntaje, y 
volver a jugar).

**Comment by LeandroBraier** [comment]
MK, ahora reviso eso y mañana te respondo. Frenemos esto un toque que no es
urgente y fijate el mail que te mandé recién de Potenciados. ESO es lo
URGENTE.

Necesitaría poder resolverlo hoy mismo para enviar los mails de bienvenida
mañana.

abrazo

**Comment by LeandroBraier** [comment]
Marce, estuve revisando y no hay un lugar posterior. Estoy cargadno el código en el último frame, fijate la captura.

<img width="994" alt="captura de pantalla 2015-08-13 a la s 19 14 24" src="https://cloud.githubusercontent.com/assets/6719872/9262798/07ebae1a-41ee-11e5-9466-17eb794e2b1d.png">

No hay nada después. Me parece que tiene que ser algo del código. FIjate si algo del código que te pasé al principio te puede servir o dar una pista:

"""stop();
Mouse.show();

_root.ambiance.gotoAndPlay("crowdoff");

set ("playerName", _root.playerName);
set ("playerEmail", _root.playerEmail);
set ("playerScore", gameScore);
set ("gameID", _root.gameID);
set ("playerUID", _root.playerUID);

// set scoreURL which is the URL that pushes the score to the database
set ("http://www.yoursite.com/gamescore/", _root.scoreURL);
//post the score to scoreURL
loadVariablesNum(scoreURL, 0, "POST");"""

**Comment by mkreyness** [comment]
A ver proba cambiarlo por esto. Es todo a ciegas, porque no tengo como 
debuggear.

var callback:Object=this.root.loaderInfo.parameters.callback ;
var usuario:Object=this.root.loaderInfo.parameters.usuario ;
var clave:Object=this.root.loaderInfo.parameters.clave;
var juego:Object=this.root.loaderInfo.parameters.juego;
set (usuario.toString(), _root.usuario);
set (clave.toString(), _root.clave);
set (gameScore.toString(), _root.gameScore) ;
set (juego.toString(), _root.juego) ;
set ("http://www.parexklaukol.com.ar/cgi-bin/jugar.pl", _root.scoreURL);
loadVariablesNum(scoreURL, 0, "POST");

**Comment by LeandroBraier** [comment]
Aquí va corregido:

https://www.wetransfer.com/downloads/dce325043ad243cdd16089bcf7acf3f320150813222808/671f5e

Che, por qué se ven los puntitos locos detrás y las pelotas del costado?

<img width="675" alt="captura de pantalla 2015-08-13 a la s 19 38 18" src="https://cloud.githubusercontent.com/assets/6719872/9263177/579239ea-41f1-11e5-95d7-acc1340009a5.png">

**Comment by LeandroBraier** [comment]
Y por qué no se ve la plaquita de + 100 puntos?

Además no estaría bueno que se pudiera compartir un link a este juego?

**Comment by mkreyness** [comment]
ni idea el fondo raro ese, ademas esta en ingles, no lo habias traducido ?
Hay que solucionar el tema del boton de instrucciones tambien, que no lleva a ningun lado, compartir la pagina en que estas siempre se puede con un share que hay al costado creo.
La plaquita deberia aparecer, despues te digo.

**Comment by LeandroBraier** [comment]
Ya le subí una instrucciones, no te preocupes. Lo del inglés está traducido
al final, no ahi. Lo traduzco en la proxima version pero veamos si funciona.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 19:35 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
bueno, tenemos un AVANCE !
Esta dando un error:
http://www.parexklaukol.com.ar/templates/parexklaukol/vendedores/undefined Failed to load resource: the server responded with a status of 404 (Not Found)

O sea que esta tratando de llamar a un url "undefined" (todo lo demas se lo pegota de la direccion local).
Pero no sabemos como lograr que ese "undefined" contenga lo que queremos.
Pasame el fla de esta version, voy a tratar de hacerle todos los recortes necesarios para que me compile y poder debuggear que es lo que pasa (aunque el juego quede injugable).

**Comment by LeandroBraier** [comment]
BUenisimo MK!

Te paso el FLA:

https://www.wetransfer.com/downloads/65ea5c9b354b5065406176a7b90f124120150813230743/2c463f

abrazo

**Comment by mkreyness** [comment]
Bueno yo creo que todo el problema que tenemos es de incompatibilidad entre el ActionScript 1 en que esta escrito el juego, y el mundo real, que es Action script 3.
En ActionScript 1 NO EXISTE todo el tema de pasar argumentos por FlashVars, aparentemente no encuentro ningun metodo de pasar argumentos.
Por otra parte en ActionScript 3 no funcionan esos metodos que usa (ni casi nada) de como esta codificado el programa.
No tengo idea como migrar el codigo a ActionScript 3, ni como levantar variables en ActionScript1.
Una posibilidad (pero riesgosa si se comparte la maquina) seria usar cookies: yo seteo las cookies antes de llamar al juego, y vos le pones en el codigo que llame a un URL fijo (donde no vienen los datos del usuario, ni del juego, ni nada) pero yo tomo esos datos de la cookie.
No es muy prolijo.

**Comment by LeandroBraier** [comment]
MK, 
1. Tema ActionScript: ¿cuales son los riesgos de la versión "no prolija" de usar cookies?
2. Tema Bordes: Me parece que el problema de que se vean los globitos y las pelotas es el embed. Tiene mal puesto el width y height del juego. Te paso el que surge del HTML que publica el FLA como referencia.

`<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="650" height="400" id="PasedeGol-v2" align="middle">
                <param name="movie" value="PasedeGol-v2.swf">
                <param name="quality" value="high">
                <param name="bgcolor" value="#1a1d2d">
                <param name="play" value="true">
                <param name="loop" value="true">
                <param name="wmode" value="window">
                <param name="scale" value="showall">
                <param name="menu" value="true">
                <param name="devicefont" value="false">
                <param name="salign" value="">
                <param name="allowScriptAccess" value="sameDomain">
                
                <object type="application/x-shockwave-flash" data="PasedeGol-v2.swf" width="650" height="400">
                    <param name="movie" value="PasedeGol-v2.swf">
                    <param name="quality" value="high">
                    <param name="bgcolor" value="#1a1d2d">
                    <param name="play" value="true">
                    <param name="loop" value="true">
                    <param name="wmode" value="window">
                    <param name="scale" value="showall">
                    <param name="menu" value="true">
                    <param name="devicefont" value="false">
                    <param name="salign" value="">
                    <param name="allowScriptAccess" value="sameDomain">
                
                    <a href="http://www.adobe.com/go/getflash">
                        <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player">
                    </a>
                
                </object>
                
            </object>`

abrazo

**Comment by mkreyness** [comment]
1)
1.1) que la gente puede tener desactivado cookies, y no sumarle ningun punto, 
1.2) que pueden tener mas de una pestaña o ventana abierta en la misma maquina (dos jugadores, cada uno con un browser distinto) y ponerle los puntos de uno al otro, la cookie es por MAQUINA, no esta pensado que puede haber varias ventanas o browsers independientes.
2)
Bordes: ahi lo puse en 650 x 400 y se ven bien.
Como el template  es uno solo, ahora al juego de buscaminas le sobra un poco de espacio en blanco, pero no es la muerte de nadie.

**Comment by LeandroBraier** [comment]
Mmm, entiendo.

1) Entiendo los riesgos pero los asumo. Mandame el código nomás.

1.1) Si no le suma puntos y nos protestan en Facebook ya sabemos por qué es.
1.2) Como de máxima puede sumar 100 puntos cada jugador no hay problema.

2) Quedó perfecto. Ahora entiendo que los circulitos son el público jeje

abrazo grande

**Comment by mkreyness** [comment]
1) agarra el original tal como estaba y ponele en lugar del url "yoursite.com" que decia, esto:
"http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?juego=29"
Yo igual tengo que hacer unos cambios en los programas para que funcione obviamente.
2) claro, y hacen "la ola" cuando haces un gol.

**Comment by LeandroBraier** [comment]
1) Aquí va con ese cambio:

https://www.wetransfer.com/downloads/b25a38ec5479adee056ddd95b0f6486f20150814210120/0fe17f

2) jaja recién caigo

**Comment by mkreyness** [comment]
No, sigue llamando a "http://www.parexklaukol.com.ar/templates/parexklaukol/vendedores/undefined"
O sea que en la variable que sea que esta usando, no hay nada. No esta poniendo el URL.
Pasame ese pedacito del FLA por mail (no hace falta todo de nuevo) y te digo a ver que podemos probar.

**Comment by LeandroBraier** [comment]
Genial. Aquí va:

""// set scoreURL which is the URL that pushes the score to the database
set ("http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?juego=29", _root.scoreURL);
//post the score to scoreURL
loadVariablesNum(scoreURL, 0, "POST"); ""

**Comment by mkreyness** [comment]
Pareceria que scoreURL no es lo mismo que _root.scoreURL
Proba ponerlo fijo directamente asi

loadVariablesNum("http://www.parexklaukol.com.ar/cgi-bin/jugar.pl",0,"POST")

sin el "?juego=29", eso lo puedo pasar tambien por cookie de ultima.

**Comment by LeandroBraier** [comment]
MK, me parece que algo de las comillas que me pasaste está mal. Me tira error de compilación en esa línea. Dice "Wrong number of parameters; set requieres exactly 2.

**Comment by mkreyness** [comment]
tal vez se alteró el texto al pasarlo por aca, te lo escribo en un mail, pero es lo mismo de antes sin '?juego=29'

**Comment by LeandroBraier** [comment]
Nop. Si entiendo bien, lo mismo de antes sin '?juego=29' sería esto:

""// set scoreURL which is the URL that pushes the score to the database
set ("http://www.parexklaukol.com.ar/cgi-bin/jugar.pl", _root.scoreURL);
//post the score to scoreURL
loadVariablesNum(scoreURL, 0, "POST"); ""

**Comment by mkreyness** [comment]
no, no me refiero a TODO 'lo mismo de antes', me refiero solo al URL.
El metodo ese de 'set' NO funciona, siempre deja un valor undefined, por eso lo quiero poner directo en el 'loadVariablesNum'.

**Comment by LeandroBraier** [comment]
Ahora entendí. Va solo esa línea. Te lo mando de nuevo por email.

**Comment by mkreyness** [comment]
Ok, ahora no da el error, no se si lo llama bien, pero por lo menos no da lo de undefined.
Ahora me pongo con lo de las cookies y te aviso.

**Comment by mkreyness** [comment]
Che me equivoque. 
No era jugar.pl, sino sumapuntos.pl lo que tenia que decir...  jugar.pl es por el cual se juega.
cambiale jugar.pl por sumapuntos.pl y mandame de nuevo, sorry.

**Comment by LeandroBraier** [comment]
No hay problema MK. Enviado!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-14 18:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Y? Funcionó MK?

**Comment by mkreyness** [comment]
Esta empezando a tomar forma, ya llama a mi programa, pero lo llama DOS VECES cuando termina el juego, y suma(ria) el doble de puntos.
Digo sumaria porque en realidad no me llega el "playerScore" que se supone que viene. Ni playerScore, ni gameScore, ni nada.
No queda otra que tratar de agregarlo de nuevo en el URL, pero no nos funcionaba antes con el numero de juego.
Proba mandar el url asi:
"http://www.parexklaukol.com.ar/cgi-bin/sumapuntos.pl?gameScore=" + gameScore.toString()

Otro problema es que si SIGO jugando (sin recargar la pagina) no vuelve a llamar a mi programa nunca jamas. No tengo idea por que, puedo jugar 300 veces mas (sin recargar la pagina) y no vuelve a llamar a mi programa.
Fijate si ves por algun tema de la logica del flash si despues de la primera vez que se juega va por otro lado (capaz para evitar la introduccion).

**Comment by LeandroBraier** [comment]
OK, MK.

Decime como quedaría la línea entera. Así?

"""loadVariablesNum("http://www.parexklaukol.com.ar/cgi-bin/sumapuntos.pl?gameScore=" + gameScore.toString())"""

Respecto de lo otro que decís la verdad no termino de entender cómo funciona, pero me da la sensación de que si, saltea la introducción. Yo diría de hacer lo siguiente. Tenemos tiempo. Bajate una versión de Flash CS6 como la que tengo yo así podemos ir viendolo vos mejor. Te paso un link posible de descarga:

http://webcache.googleusercontent.com/search?q=cache:4pvHv4IFuOcJ:https://thepiratebay.mn/torrent/7227566/ADOBE_FLASH_PRO_CS6_%5Bthethingy%5D+&cd=1&hl=en&ct=clnk&gl=ar

abrazo y buen finde!!

Lo seguimos trabajando el martes. Que descanses!!

abrazo grande

pd: me quedo esperando los cambios de Torneo de Potenciados porfa, coordinen eso con Fede.

**Comment by mkreyness** [comment]
Si pero te falta el ,0,"POST" que siempre esuvo, antes de cerrar el parentesis.

**Comment by mkreyness** [comment]
Listo !!!! No servia para nada esa funcion loadVariablesNum, porque cachea, o sea que una vez que se la llamo con un URL, no lo vuelve a llamar nunca (se supone que se usa para precargar contenido, no para pushear resultados).
Encima tiene ese problema de que la llama 2 veces (y ahi SI estupidamente carga 2 veces, justo cuando uno no quiere).

Reemplaza TODO el codigo del fotograma 50 (el de siempre) por solo esto:

stop();
Mouse.show();
_root.ambiance.gotoAndPlay("crowdoff");

getURL("http://www.parexklaukol.com.ar/cgi-bin/sumapuntos.pl?gameScore=" + _root.gamescore.toString(),"_self","GET");

Con esto ya funciona como el de BuscaKlaukol, o sea que termina Y RECARGA TODA LA PAGINA.
Obviamente esto no es lo mas agradable para volver a empezar, pero por lo menos te actualiza tu puntaje visible. Tambien habria que ponerle algun delay para que se vea el cartel antes de irse, y sacarle el boton de "Jugar de nuevo".

Lo ideal seria ademas que cuando se recarga no empiece con toda la introduccion, pero la verdad que en esta version pedorra de actionscript no hay como pasarle un parametro externo que nos diga que lo debe saltear..
Lo que SI se podria, y ahi si aplica lo de usar el getVariablesNum, es hacer una URL que le devuelva si ya jugo alguna vez a este juego, y en tal caso saltear la introduccion.

**Comment by mkreyness** [comment]
PD: No hace falta que me lo pases (salvo que agregues vos algo mas al codigo), la version que esta instalada ya tiene este codigo cambiado.
Podes verlo con
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?usuario=marcelokreyness&clave=pepe&id=11

**Comment by LeandroBraier** [comment]
Buenisimo MK! Gracias! Me quedo con el código igual porque nos pidieron unos pequeños cambios de diseño dentro del flash para la semana que viene. Ahi lo aplico con este script y te lo mando de nuevo. 

Abrazo grande y buen finde!

**Comment by mkreyness** [comment]
Claro, ademas hay cosas en ingles que traducir. Yo le pondria un delay para que se vean los goles antes de reiniciar.

**Comment by LeandroBraier** [comment]
Me parece bien eso. Esa parte me parece que te la voy a pedir a vos jeje

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-15 10:45 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
MK, te pasé por mail el juego con el código nuevo que me pediste y todas las correcciones estéticas del cliente, incluido lo de ingles que faltaba traducir. No sé como frenarlo unos segundos como vos decías, decime si te parece que hace falta.

Te paso una versión autonóma con el código original del juego para subir a una página independiente no linkeada dentro del sitio de ParexKlaukol. Me piden siempre tener el juego por fuera de Comunidad de Vendedores para poder mostrarlo internamente. Cuando la tengas subida pedile a @braulio-evangelisti que arme una URL así como hizo ya para BuscaKlaukol.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA Buen día Fede!

Necesito que me des una mano con algo muy simple. MK alojó el flash del Juego en esta web:

http://www.parexklaukol.com.ar/juegos-vendedores/gol.html

Y por el formato de la página no respecto el width y el height del embed y se ven cosas a los costados que no deberían. Podés ajustarlo en esta página en particular?

Desde ya muchas gracias

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!

abrazo
