### ISSUE TITLE
Envio de Mailing de Bienvenida Torneo de Potenciados. 13/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#136]
@mkreyness necesito que te vayas preparando. Cuando te de el OK necesito que envies los mailings de bienvenida a los corralones y representantes comerciales. Hay 4 HTML, uno para cada tipo de envio:

Corralones Categoria A y D
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html

Corralones Categoria B y E
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e.html

Corralones Categoria C y F
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f.html

Representantes Comerciales
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-r-c.html

Vas revisando para que esté todo funcionando?

**Comment by mkreyness** [comment]
yo me estoy yendo ahora, recien tipo 13:00 con suerte me vuelvo a conectar como para ver algo rapido y a las 16:00 estoy en mi oficina ya como para ocuparme full.
Igual el programa para que los mande lo hago copiando otro asi que me lleva 2 minutos.

Lo importante siempre con los mailings es que me definas el "Asunto" y el sender.
Acordate tambien que no se pueden mandar mas de 300 por hora, decime en que orden preferis que se manden (obvio los representantes son poquitos y voy a empezar por ahi).

**Comment by LeandroBraier** [comment]
Perfecto, entiendo.

Te paso esos datos así ya los tenés cuando te de el OK final. Calculo que
va a estar para que arranques a enviar a las 13 hs.

From: klaukol.marketing@klaukol.parex.com

Asunto: Ya estás participando del Torneo de Potenciados Klaukol! Encontrate
en el ranking

abrazo

**Comment by mkreyness** [comment]
En los templates estan todos mal los links, llevan al club de vendedores en vez del torneo de potenciados.
Ahora lo arreglo.

**Comment by LeandroBraier** [comment]
Perfecto, por eso te decía.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 18:43 GMT-03:00 mkreyness notifications@github.com:
