### ISSUE TITLE
Favicon Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#137]
@FAAREIA apenas puedas subile el Favicon con la copita amarilla que venimos usando.

Esto puede ser para mañana tranqui.

abrazo

**Comment by LeandroBraier** [comment]
Además del Favicon, fijate que diga Torneo de Potenciados, en lugar de lo que dice ahora (Torneo de Corralones).

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! Fijate que solo falta cambiar el nombre a "Torneo de Potenciados" en el login. Lo demás perfecto.

abrazo

**Comment by FAAREIA** [comment]
Hecho
