### ISSUE TITLE
Torneo de Potenciados. Bugs y Modificaciones Finales. URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#138]
@FAAREIA  y @mkreyness : sigue habiendo cosas a corregir y modificar antes del lanzamiento. Necesito que paren con lo que están haciendo para Benteveo que no sea esto y nos sentemos a terminarlo bien antes de seguir con otras cosas. Si se demora un poco Club de Colocadores se demora un poco.

´´´VERSIÓN CORRALONES´´´

1) El cuadro de "Cómo vengo este mes" debe decir "Cómo vengo hasta ahora". Los datos deben ser los del acumulado. Es decir:
a. En la columna Objetivo debe decir el Objetivo Semestral.
b. En la columna Conseguiste debe decir el total de puntos acumulados hasta el momento. 
c. En la columna Te Faltan debe decir cuantos puntos le faltan para llegar al Objetivo Semestral.
d. En la columna Alcanzaste debe decir lo mismo  que en la columna "Como vengo hasta ahora" de la tabla de ventas del Representante Comercial. Por ejemplo: 26% de 2 meses.
e. Donde dice "Agosto" arriba debe decir "Puntos conseguidos en X meses" donde X es la cantidad de meses transcurridos (el mismo dato que se toma para el Acumulado)
1. En la Tabla de Posiciones: 
   a. Donde dice Última actualización de pedidos facturados está vacío. Deben actualizarlo como está en la versión de vendedores: ÚLTIMA ACTUALIZACIÓN DE PEDIDOS FACTURADOS VS. INFORMACIÓN SEMESTRAL: 10/08
   b. Cuando un corralón no entra en el ranking debería aparecer, tal como aparece en la versión de representantes comerciales, cuantos puntos le falta para entrar al ranking.

´´´VERSIÓN CORRALONES Y REPRESENTANTES COMERCIALES´´´

2) Cómo se muestran los puntos. (Esto aplica para TODO. Es decir, en la versión de ventas también.)

a. Por qué en la tabla de posiciones de la versión Representantes Comerciales dice que faltan (por ejemplo) 95 puntos si faltan 9.523 puntos para subir? (El ejemplo es de Ceramisur)  Eso es un BUG.
b. Me pidió el cliente agregar el punto de los miles. Por ejemplo donde dice 19740 debe decir 19.740. 

Confirmenme recepción por favor.

abrazo

**Comment by mkreyness** [comment]
A mi me aparecen 9523 puntos "para subir" en Ceramisur.
Pasame el URL con el que estas viendo eso.

**Comment by LeandroBraier** [comment]
Es en la versión de representantes comerciales:

http://parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?torneo=1&usuario=JavierVasquez&clave=111281

**Comment by mkreyness** [comment]
Entonces eso es lo que esta bien, son 95 puntos, lo que esta mal es lo que aparece en el corralon.

**Comment by mkreyness** [comment]
Ahi arregle lo que salia mal en el corralon. Faltaba dividir por 100 porque es un delta de porcentajes aplicado al objetivo. Ya verifique las cuentas, con 95 puntos mas pasa a tener 24.97 que es mas que los 24.96 que tiene el del puesto 6 (se muestra redondeado a 1 cifra, pero estos son los numeros).

**Comment by LeandroBraier** [comment]
No te olvides del punto 2.b)

Eso aplica a todos los números de más de 3 cifras.

**Comment by mkreyness** [comment]
tengo que revisar por todos lados eso, mientras fijate si esto lo ves bien, este es un caso de uno que no entra al top 10:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1

y este uno que si:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=ceramisur&clave=127848&torneo=1

**Comment by LeandroBraier** [comment]
Solo dos cosas sigo viendo mal:

1) Donde dice "Alcanzaste" falta el "de 2 meses". Por ejemplo, "73.4% de 2
meses". Sino no se entiende.

2) Los 553 que debe sumar Aldo Campanella para entrar son puntos, no bolsas
no? "Sumá 553 puntos para entrar al TOP 10"

**Comment by mkreyness** [comment]
0) ya esta lo de las comas.
1) ahi lo puse pero se rompe el formato, eso lo va a tener que revisar y arreglar @FAAREIA 
2) puesto asi, el calculo de todos modos es el mismo que en el caso del representante llamabamos "bolsas equivalentes".

**Comment by LeandroBraier** [comment]
Entiendo, pero ahora no decimos mas asi. O si? Quiero decir, en todos lados
tienen que decir puntos. Solo en las bases debe decir bolsas equivalentes.

**Comment by mkreyness** [comment]
En el de corredores sigue diciendo "bolsas equivalentes", si de ahi lo copie, por ej en javierVasquez dice:
"Vendé 80 bolsas equivalentes a tu corralón PLISUD S.A. para entrar al TOP 10."

**Comment by LeandroBraier** [comment]
Entonces que en ambos diga bolsas equivalentes, pero bolsas solo no.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Pongo "comprá bolsas equivalentes" en vez de "ganá puntos" en los corralones entonces ?

**Comment by LeandroBraier** [comment]
Sip, vamos con eso confirmado.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 18:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi arreglé eso de "-26% de 2 meses"

**Comment by mkreyness** [comment]
Estamos hablando de lo mismo ? Es en la parte DE ARRIBA, en el "Como vengo hasta ahora".
Fijate aca:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1

el cuadrado gris es mucho mas alto que los otros que tiene al lado.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Quedó perfecto.

MK: solo queda lo de los puntos. Vi que pusiste con comas. 19,356. Seguro
el cliente me va a protestar porque pidió puntos (19.356)

Se puede hacer?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
mmmm, si pongo puntos va a quedar raro el porcentaje, que tambien tiene punto, en tal caso al porcentaje habria que pasarlo a coma, no ?

**Comment by LeandroBraier** [comment]
Exacto.

**Comment by LeandroBraier** [comment]
Avisame cuando esté MK porfa. Los mails ponelos a enviar mañana temprano
nomás.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Sigo viendo las comas en lugar de puntos y puntos en lugar de comas en el
chart. A qué hora calculás tenerlo a eso?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-13 21:00 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

> Avisame cuando esté MK porfa. Los mails ponelos a enviar mañana temprano
> nomás.
> 
> abrazo
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> On Thu, Aug 13, 2015 at 8:23 PM, leandrobraier leandrobraier@gmail.com
> wrote:
> 
> > Exacto.
> >

**Comment by mkreyness** [comment]
Todavia no hice ningun cambio, solo te hice la pregunta. Cuando este todo cambiado te aviso.

**Comment by mkreyness** [comment]
Ahi hice todo el intercambio de puntos y comas.

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA el cliente me pidió más modificaciones y las necesitamos para hoy, a más tardar mañana a la mañana. Yo los entiendo, a mi también me está volviendo loco este ida y vuelta y ya lo hablé largamente con ellos. Es más simple si lo aplicamos y listo.

VERSIÓN CORREDORES

En el marco de "Cómo vengo hasta ahora" ahora me pidieron que estén dos líneas de datos: semestrales y trimestrales. Creo que la decisión es buena porque todo se simplifica. Vuela ese textito de "26% de 2 meses". La info quedaría así:

![img-20150814-wa0001](https://cloud.githubusercontent.com/assets/6719872/9281813/3be06c14-429e-11e5-8268-729f9b070365.jpg)

Confirmenme porfa si está claro con esta captura, cualquier duda me avisan.

VERSIÓN REPRESENTANTE COMERCIAL

Este cambio aplica en la versión de vendedores de la siguiente manera:

1) Columna de "Cómo vengo hasta ahora" vuela, con velocímetro incluido.

2) Se suman columnas de "Objetivo Trimestral (puntos)" y "% de objetivo trimestral".

Creo que es intuitivo para uds qué info va en cada columna, es igual que la semestral pero en total trimestre y porcentaje en base a ese total. Cualquier duda me avisan. 

Por favor confirmenme para qué hora lo podrían tener. Demás está decir que esto queda como prioridad número 1.

abrazo

**Comment by mkreyness** [comment]
Pero si los datos me los pasan acumulados, como voy a poder darle info del trimestre ?
Ahora es facil, porque estamos en el primer trimestre, pero cuando sea noviembre, me van a dar los 5 meses sumados, y que se yo cuanto es de cada trimestre ?

**Comment by LeandroBraier** [comment]
Es que el Trimestre se va a ver hasta fin de septiembre. Después quedan
solo datos semestrales.

No te preocupes por eso. Con los datos que tenés lo podés hacer.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-14 16:37 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Bueno, cuando Fede maquete los cambios lo aplico.
Acordate @FAAREIA que los templates en uso son:
con-slideT-C.html
con-slideT-R-NUEVO.html

PS: QUE BUENO que vuele ese velocimetro inentendible !

**Comment by FAAREIA** [comment]
Exactamente que tengo que hacer? La tabla de TUS VENTAS ahora lleva 2 valores del mismo campo pero uno semestral y otro trimestral?
No creo poder hacerlo hoy los cambios si llevan mucho tiempo.

**Comment by LeandroBraier** [comment]
Es solo cambiar el nombre de dos columnas de Tus Ventas y agregar unas líneas del cuadrito de Cómo vengo hasta ahora. Si lo tenés para mañana a la mañana o al mediodía máximo estamos bien.

**Comment by mkreyness** [comment]
falto volar lo de "de 2 meses" del template. Voy a intentar hacerlo yo sin que se rompa.
Tambien habria que agregarle la palabra "semestral" y "trimestral" en algun lado al cuadro de como vengo, si no no se entiende nada.

**Comment by mkreyness** [comment]
Segun veo en el template las palabras "semestral" y "trimestral" estan pero no se ven, y por mas que yo no ponga la "data-mes" en el parrafo de la clase "alcanzaste", sigue forzando la palabra "DE ".
Por favor tocalo sobre el template que ya esta bajado Fede porque le tuve que modificar varias cosas (basicamente los nombres de las variables trimestrales, que eran iguales a las semestrales).

Ver ejemplo aca:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?torneo=1&usuario=aldocampanella&clave=127847

**Comment by mkreyness** [comment]
Creo que ya quedo todo bien, Lean confirmame cuando sacar los mailings entonces.

**Comment by LeandroBraier** [comment]
Marce, sacalos de una vez por favor. Jeje te habia dicho que los mandaras igual ayer pero se ve que no nos entendimos. Mandalos por favor y confirmame cuando lo haces.

Abrazo

**Comment by mkreyness** [comment]
Pero no se podia mandar, estabamos modificando las paginas !
Ahora estoy en el cine, a la noche los mando.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Recibidos los mails MK!! Gracias a los dos!!! Quedó muy bien!!

Seguramente nos van a seguir pidiendo modificaciones, pero por lo menos ya está lanzado.

abrazo grande y buen fin de semana para los dos

**Comment by mkreyness** [comment]
Los mails a los corralones todavia estan saliendo.

**Comment by LeandroBraier** [comment]
@mkreyness tenemos un error grave en el Torneo de Potenciados.

En la tabla de Tus Ventas el porcentaje trimestral da la mitad del semestral, cuando debería ser el doble. ¿Lo corregís porfa lo antes posible?

<img width="1043" alt="captura de pantalla 2015-08-18 a la s 17 06 40" src="https://cloud.githubusercontent.com/assets/6719872/9341058/ea044634-45c9-11e5-8aff-c64da4fdd7d9.png">

abrazo

**Comment by mkreyness** [comment]
ups, cosas de la aritmetica. Ya lo arreglo.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by mkreyness** [comment]
Listo. 5 años en la Facultad de Ingeniería para equivocarme en esto...

**Comment by LeandroBraier** [comment]
jajaja No te preocupes MK, no le digo a nadie. Culpa de la aritmética.

abrazo grande

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-18 17:07 GMT-03:00 mkreyness notifications@github.com:
