### ISSUE TITLE
Torneo de Potenciados. Modificaciones en Bases y Condiciones 14/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#139]
Fede, para mañana tranqui necesito que reemplaces un párrafo en las bases y condiciones.

`VERSIÓN CATEGORIA B Y E:`

Donde dice: 

Los DISTRIBUIDORES que resultaran obtener el primer, segundo y tercer puesto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra sobre los productos participantes durante el periodo de la promo (este descuento solo será aplicable sobre entregas facturadas).

Debe decir:

Los DISTRIBUIDORES que resultaran obtener desde el primer al quinto puesto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra sobre los productos participantes durante el periodo de la promo (este descuento solo será aplicable sobre entregas facturadas).

`VERSIÓN CATEGORIA C Y F:`

Donde dice: 

Los DISTRIBUIDORES que resultaran obtener el primer, segundo y tercer puesto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra sobre los productos participantes durante el periodo de la promo (este descuento solo será aplicable sobre entregas facturadas).

Debe decir:

Los DISTRIBUIDORES que resultaran obtener desde el primer al decimo quinto puesto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra sobre los productos participantes durante el periodo de la promo (este descuento solo será aplicable sobre entregas facturadas).

`VERSIÓN CORREDORES:`

Donde dice:

Los DISTRIBUIDORES que resultaran obtener el primer, segundo y tercer puesto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra sobre los productos participantes durante el periodo de la promo (este descuento solo será aplicable sobre entregas facturadas).
Los DISTRIBUIDORES que resultaran obtener el primer, segundo y tercer puesto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra a ParexKlaukol S.A.

Debe decir:

Los DISTRIBUIDORES de Categoría A y D que resultaran obtener el primer, segundo y tercer puesto, los de Categoría B y E del primer al quinto puesto y los de Categoría C y F del primer al decimo quinto en el ranking al final del semestre que dure la PROMOCIÓN recibirán además un 5% de descuento en su próxima compra sobre los productos participantes durante el periodo de la promo (este descuento solo será aplicable sobre entregas facturadas).

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Fede, fijate que agarraste la versión del mail, no la actualizada acá en GitHub. La corregí después. Es una pavada, pero donde dice "del primer quinto puesto" debe decir "del primer al quinto puesto" y donde dice "del primer decimo quinto puesto" debe decir "del primer al decimento quinto puesto"

Puede ser para el martes esto, no hay apuro.

abrazo
