### ISSUE TITLE
Newsletter Simple "La Potencia de Klaukol"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#14]
Fede, necesito que diseñes un newsletter para el mediodía muy simple.

Tiene el siguiente texto arriba:

"En ParexKlaukol estamos orgullosos de que formes parte de nuestro equipo y queremos agradecerte por haber formado parte del lanzamiento de nuestro nuevo producto.

Hacé clic en la foto y conocé la verdadera potencia de Klaukol.

 y la siguiente foto abajo:

![grupo-0-en-muro](https://cloud.githubusercontent.com/assets/6719872/7022580/bfcee484-dd03-11e4-9b05-a15493ea719d.jpg)

La foto debe ser clickeable y llevar a la Landing Interna que hiciste el otro día.

De estos newsletter va a haber un total de 8, todos iguales en texto pero la foto va a ser diferente (muy similar pero con empleados distintos en la foto. Todas estas fotos, a su vez, deberían sumarse al slideshow de la landing interna.

Tené en cuenta colocar al pie del newsletter lo mismo que hay en el footer del Micrositio de Klaukol Impermeable Potenciado, Klaukol Potencia que une: Parex, Klaukol y Lanko en grisesito abajo y ParexGroup en la esquina. El Potencia que une va con la nueva estética, no la que hay actualmente en el Micrositio.

abrazo

**Comment by FAAREIA** [comment]
http://benteveo.tv/_mailing-parex/equipo/equipo.html
No esta linkeado a la landing, en donde va a estar alojada la landing?

**Comment by LeandroBraier** [comment]
En la misma url que está ahora. La de Benteveo.

Está bueno!

Falta el texto que diga: "Hacé clic en la foto y conocé la verdadera potencia de Klaukol."

**Comment by FAAREIA** [comment]
Ahi actualicé el news ;)

**Comment by LeandroBraier** [comment]
Ahi lo vi. Pero ponelo con un poco de onda. Algún tipo de botón, o algo
así, puede ser?

Más pro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
El botón que tiene que decir?
Justo ahora estoy haciendo una migración, en 1h más o menos espero terminarla

**Comment by LeandroBraier** [comment]
Fuck. Lo necesito urgente. El botón tiene que decir eso:

"Hacé clic en la foto y conocé la verdadera potencia de Klaukol."

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-07 15:23 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
exclente Fede! Gracias!

**Comment by LeandroBraier** [comment]
Fede, hubo devolución. Volvemos a la marcha. Van los cambios:

HEADER

Cambiar texto por el siguiente:

"(...)...queremos agradecerte por haber formado parte del lanzamiento de Klaukol Impermeable Potenciado. " Lo demás perfecto.

FOTO
Necesito que la foto del newsletter sea única y sea la que ya tenés del Muro Klaukol largo. Arriba queda todo igual, solo cambiá la foto por esa, aunque quede muuuuuy largo el newsletter.

ARRIBA DEL FOOTER

Un texto con link que diga: "Mirá el video completo del evento" que llevaría un link a un video de Vimeo. El link te lo paso más tarde.

FOOTER

Igual. Está perfecto.

Si lo podés corregir para mañana bien bien temprano tipo 8 am estamos bien. En un rato te subo pequeñas modificaciones también para la landing. Pero son pequeñas: agregar un link similar al del video y unas fotos más en el slideshow.

abrazo

**Comment by LeandroBraier** [comment]
Va el video, Fede:

https://vimeo.com/album/3339017/video/124367559

abrazo

**Comment by FAAREIA** [comment]
Ya me pongo con esto Lea

**Comment by FAAREIA** [comment]
Fijate ahora Lea: http://benteveo.tv/_mailing-parex/equipo/equipo.html

**Comment by LeandroBraier** [comment]
Gracias Fede! Estéticamente está perfecto. Pero la foto se me corta a la mitad, puede ser? Te sumo captura.
![captura de pantalla 2015-04-08 a la s 09 47 38](https://cloud.githubusercontent.com/assets/6719872/7045296/540b6800-ddd3-11e4-87d0-abac2a7dbfcf.png)

**Comment by FAAREIA** [comment]
Arreglado! Se me había ido internet y adelanté el morfi! Parece andar todo joya ahora.
