### ISSUE TITLE
Cambio de Título de Página de Guía de Corralones. 19/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#140]
Fede, necesito que el título de la página de Guía de Corralones pase de llamarse "Guía de corralones Klaukol" como está a "Guía de Corralones de Materiales"

Me avisás cuando está?

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias
