### ISSUE TITLE
Investigar Newsletter Responsive

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#141]
Fede, tranqui cuando puedas, fijate cómo está el html de este mailing:

_mailing/suscripcion_newsletter

Está hecho responsive por un diseñador que hizo un curso especialmente sobre eso. Decime qué te parece y si lo podemos aplicar al resto de nuestros mailings y news.

**Comment by mkreyness** [comment]
Para mi no tiene nada de responsive, ya que carece de javascript alguno.
Es simplemente que no tiene numeros fijos de pixels en las cosas sino que es todo por porcentajes, pero eso no es ser responsive, es ser proporcional.

**Comment by mkreyness** [comment]
Ah, claro que para que vaya en un mail no PUEDE tener javascript. Esta bien, es una forma de zafar.

**Comment by FAAREIA** [comment]
¿Cuál es el link?
Sin verlo igual te digo que no existe un newsletter responsivo, pero si que las cosas de los bloques vayan siendo más angostas a medida que se achica el ancho máximo. Pero esto no suele quedar bien en cualquier diseño.

**Comment by FAAREIA** [comment]
¿Cuál es el link? Todavía no pude verlo

**Comment by mkreyness** [comment]
http://www.parexklaukol.com.ar/_mailing/confirmacion_newsletter/confirmacion.html

**Comment by FAAREIA** [comment]
Ahi lo vi y no tiene nada de responsivo. De hecho si achico la ventana del navegador a la de un celular se rompe el newsletter a pesar de ser algo super-simple. Lo vuelvo a decir, no existen newsletters responsivos, las directivas de estilos para hacer algo responsivo las eliminan los correos. Adicionalmente, con la compejidad que nosotros manejamos en ciertos mailings, hacerlos escalables no queda bien.

**Comment by LeandroBraier** [comment]
Fede, entiendo que no es "técnicamente" responsivo, pero teniendo en cuenta que el curso que hizo este chico se lo vendió como responsivo, veamos qué podemos tomar de esto para aprender.

Por ejemplo, la imagen del fondo se altera con el tamaño, incluidos logos y demás. Todo menos el texto. No se rompe, creo que está pensado así. Estoy de acuerdo que no se puede aplicar para todos los mailings que tenemos, pero tomemos estos truquitos "simil responsive" del fondo para próximos newsletters. Solo eso digo.

abrazo

**Comment by FAAREIA** [comment]
Ok entiendo, pero hay algunos detalles por ejemplo:
- El fondo de azul y la forma blanca se rompen en resoluciones chicas y medianas. Si achicas el ancho del navegador lo ves.
- Los logos y eso se achican porque es todo una imagen. Osea que los 5 logos son 1 imagen, lo cual es negativo pero como positivo tiene eso de la escalabilidad.

Yo creo que si el mailing es simple, podemos sacarle el ancho fijo de 640 y hacer esos trucos de porcentajes, pero en los mailings de novedades la mejor experiencia es ponerle ancho fijo.
En los próximos newsletter vemos estos temas igual.

**Comment by LeandroBraier** [comment]
Dale, me parece bien lo que proponés Fede. Solo tomá lo que te sirva para resolver alguna cuestión. Si es imagen hace que sea más posible que caiga como spam, así que es una contra como vos decís.

Solo tomemos lo que nos sirva nomás.

abrazo y gracias
