### ISSUE TITLE
Fotos de Corralones a Borrar

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#142]
MK necesito que borres las siguientes fotos de la base:

http://www.parexklaukol.com.ar/vendedores/img/usuarios/DSC00585.JPG
http://www.parexklaukol.com.ar/vendedores/img/usuarios/CAM00062.jpg
http://www.parexklaukol.com.ar/vendedores/img/usuarios/images.png
http://www.parexklaukol.com.ar/vendedores/img/usuarios/001-Interior-Hallway-Main-570x400.jpg
http://www.parexklaukol.com.ar/vendedores/img/usuarios/IMG-20150414-WA0001.jpg
http://www.parexklaukol.com.ar/vendedores/img/usuarios/image.jpg

abrazo

**Comment by mkreyness** [comment]
Listo, queres que las elimine del server tambien ?

**Comment by LeandroBraier** [comment]
Dale, no sirven esas. Al final pusiste que no se puedan subir fotos con el
mismo nombre? Porque vi algunas repetidas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-21 16:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, vi.
Es un problema eso, se pisan, pero tambien es un kilombo pedirle a la 
gente que renombre su archivo y lo vuelva a seleccionar.
Lo que habria que hacer es guardarlas con un numero correlativo o algo 
univoco (fecha/hora/IP por ej)

**Comment by LeandroBraier** [comment]
Si querés resolvelo así, pero en realidad los nombres repetidos eran con la
misma foto exacta, osea que estaba bien que se pisaran en ese caso. Por eso
te consultaba.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-21 17:11 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero puede ser el mismo nombre de pura casualidad, o por ser un nombre 
tan generico que no dice nada.
En los casos que me pasaste abajo habia 2 tipos cuya imagen de corralon 
se llamaba "image.jpg", asi que se lo tuve que borrar a los dos porque 
necesariamente ambos estaban mostrando lo mismo.

**Comment by LeandroBraier** [comment]
Entiendo lo que pasó. Entonces hacé como dijiste. Sumale un numerito
aleatorio o algo asi

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-21 18:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ok, cuando lo tenga hecho y probado te aviso.
