### ISSUE TITLE
Sumar link a Torneo de Potenciados en la web. HOY

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#143]
@braulio-evangelisti, sumalo muy simple y bajo perfil, solo el titulo "Torneo de Potenciados" en esta sección:

<img width="1077" alt="captura de pantalla 2015-08-25 a la s 11 16 55" src="https://cloud.githubusercontent.com/assets/6719872/9471119/42cd200a-4b25-11e5-8b81-039c165455d0.png">

abrazo

**Comment by braulio-evangelisti** [comment]
@mkreyness desde el ftp puedo acceder a algunos archivos del sitio, pero muchos directorios (como "inc" donde estan el footer y sidebar, "css" o "js") figuran como accesos directos y cuando intento acceder no es posible. 

Es porque mi usuario no tiene permisos o estan situados en otro lado?

Gracias

**Comment by braulio-evangelisti** [comment]
Lea fijate ahi. Lo agregué en la primer columna donde estan el resto de desarrollos de este tipo.

**Comment by LeandroBraier** [comment]
Excelente Braulio!! Gracias!!! abrazo
