### ISSUE TITLE
Corrección en Mailing Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#144]
@braulio-evangelisti en la versión de los RCD necesito que cambies el pie del header por la siguiente frase:

"Será ganador del torneo el Representante Comercial que más crezca porcentualmente respecto del volumen de los productos participantes vendidos en el 2do semestre 2014."

abrazo

**Comment by braulio-evangelisti** [comment]
Listo

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-r.html

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! 

Pequeñas correcciones que tienen que ver con lo mismo en los demás mailings:

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e.html
http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f.html
1. "Será ganador del torneo el Distribuidor que más crezca porcentualmente respecto del volumen de los productos participantes comprados en el 2do semestre 2014."
2. "Viaje al Caribe hasta $50.000"

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html

"Viaje a Brasil hasta $25.000"

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-b-e.html

"Viaje a Brasil hasta $10.000"

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-c-f.html

Confirmame cuando esté listo porfa. abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahora como quedaron. Avisame cualquier cosa.

Abrazo

**Comment by LeandroBraier** [comment]
Perfectos. Muchas gracias!! abrazo
