### ISSUE TITLE
Corrección en Bases y Condiciones RCD Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#145]
@braulio-evangelisti necesito modificar la siguiente frase de las bases y condiciones pertenecientes a los Representantes Comerciales:

Donde dice:

El premio semestral para los DISTRIBUIDORES y REPRESENTANTES COMERCIALES de categorías A y D consistirá en 1 (un) viaje para 2 (dos) personas al Caribe por un valor total de hasta cien mil pesos.

Debe decir

El premio semestral de categorías A y D consistirá en 1 (un) viaje para 2 (dos) personas al Caribe por un valor total de hasta 50 (cincuenta) mil pesos para el DISTRIBUIDOR y otro viaje para 2 (dos) personas al Caribe por un valor total de hasta 50 (cincuenta) mil pesos para el REPRESENTANTE COMERCIAL.

Donde dice:

El premio semestral para los DISTRIBUIDORES y REPRESENTANTES COMERCIALES de categorías B y E consistirá en 1 (un) viaje para 2 (dos) personas a Brasil por un valor total de hasta cincuenta mil pesos argentinos (50.000) c/u. 

Debe decir:

El premio semestral de categorías B y E consistirá en 1 (un) viaje para 2 (dos) personas a Brasil por un valor total de hasta veinte y cinco mil pesos argentinos (25.000) para el DISTRIBUIDOR y otro viaje para 2 (dos) personas a Brasil por un valor total de hasta veinte y cinco mil pesos argentinos (25.000) para el REPRESENTANTE COMERCIAL..

Donde dice:

El premio semestral para los DISTRIBUIDORES y REPRESENTANTES COMERCIALES de categorías C y F consistirá en 1 (un) viaje para 2 (dos) personas a Brasil por un valor total de hasta veinte mil pesos argentinos (20.000) c/u. 

Debe decir:

El premio semestral de categorías C y F consistirá en 1 (un) viaje para 2 (dos) personas a Brasil por un valor total de hasta diez mil pesos argentinos (10.000) para el DISTRIBUIDOR y 1 (un) viaje para 2 (dos) personas a Brasil por un valor total de hasta diez mil pesos argentinos (10.000) para el REPRESENTANTE COMERCIAL.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahi Lea

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto, Brau. Gracias!
