### ISSUE TITLE
Torneo de Potenciados: No se visualizan Slides subidos via CMS para Corredores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#146]
@mkreyness fijate qué puede estar pasando. Los subí pero no se ven. Y de hecho en front end se ve que queda un hueco entre el primer slide y los siguientes.

**Comment by mkreyness** [comment]
Es que renombraron la carpeta de "torneo-corralones" a "torneo-de-potenciados" y el CMS no lo sabia (de hecho el programa propiamente dicho tampoco estaba actualizado, decia "torneo-corralones" por todas partes). 
Si subiste nuevos desde ese cambio, se perdieron, vas a tener que volverlos a subir.

**Comment by LeandroBraier** [comment]
Perfecto MK. Gracias!
