### ISSUE TITLE
Reenviar Mailings de Bienvenida Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#147]
Marce, necesito que lo reenvies mañana a la mañana.

@FAAREIA tenemos analytics en Torneo de Potenciados? Lo necesito apra saber quiénes siguieron el link del mailing. Me confirmás porfa?

abrazo

**Comment by mkreyness** [comment]
Vos me vas a pasar la lista de quienes deben recibirlo o lo remando a todos ?

**Comment by LeandroBraier** [comment]
A todos. Eso me pidió el cliente. Pero antes necesito que Fede me confirme
lo de Analytics. Aguantame un toque.

Tené en cuenta que hicimos cambios en los mailings de potenciados.
Revisalos mientras tanto y cualquier duda consultá con Braulio porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Mmmm, espero que hayan hecho los cambios sobre lo que estaba en el servidor, porque yo tuve seguramente que ajustarle varias cosas.

**Comment by LeandroBraier** [comment]
Exacto. A eso me refiero. @braulio-evangelisti le confirmás a MK si pudiste hacer los cambios sobre lo que estaba en el servidor?

**Comment by braulio-evangelisti** [comment]
Los cambios hechos esta semana sobre las 4 maquetas fueron solmente sobre imagenes, solo subi imagenes modificadas reemplazando las que estaban en el server pero los html no toque ninguno.

**Comment by mkreyness** [comment]
Ok, entonces no varia nada de lo mio.
Lean: igual yo siempre me mando uno de prueba de cada cosa, sobre todo si hubo algun cambio.

**Comment by FAAREIA** [comment]
Ahi actualicé el js de google analytics y le puse el código.

**Comment by LeandroBraier** [comment]
GraciasFede! Adelante MK!

Abrazo

**Comment by mkreyness** [comment]
"Adelante" ahora o mañana a la mañana ?

**Comment by LeandroBraier** [comment]
Mañana a la mañana (Hoy Viernes para ser más claros)

abrazo

**Comment by mkreyness** [comment]
ahi estan saliendo los de los representantes, en los que estas copiado.
El primero te va a llegar doble porque primero me lo mande a mi para probar (aunque diga Javier Vasquez), ahora hago uno de prueba de corralon y dejo corriendo el resto.

**Comment by LeandroBraier** [comment]
Recibidos MK!! Todo en orden, gracias!

Enviá todos nomás.

abrazo

**Comment by mkreyness** [comment]
todavia estan saliendo los ultimos, pero ya enseguida termina.

**Comment by LeandroBraier** [comment]
Gracias MK!!

abrazo
