### ISSUE TITLE
Bugs en Guía de Corralones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#148]
MK, cuando hago búsquedas en la Guía de Corralones por nombre de corralón pasan las siguientes cosas:

a) Si pongo una palabra en el buscador de corralón y presiono ENTER, me aparece un mensaje de google en inglés de "ZERO results". 

<img width="606" alt="captura de pantalla 2015-08-28 a la s 09 59 51" src="https://cloud.githubusercontent.com/assets/6719872/9546545/e0d0bd0c-4d69-11e5-9d5c-57e4871dfe19.png">

Debería aparecer un mensaje en español como cuando hago clic en Buscar.

b) No puede ser que busque la palabra "perez" y no arroje resultados siendo que está en el nombre de al menos 1 razón social de corralón. El buscador está andando mal. Debería buscar palabras dentro de los nombres de los corralones, cómo está seteado ahora?

abrazo

**Comment by mkreyness** [comment]
No estamos buscando en razones sociales, sino en los nombres "de fantasia".
Si queres agrego que busque TAMBIEN en razones sociales.
Acordate que la busqueda es DENTRO DEL RADIO, o sea, si hay un perez en rosario, no te va a aparecer, solo los perez de capital.
Pone ceramis, ampiale los km de busqueda y vas a ver que te aparecen un par de CERAMISUR en Quilmes.
Lo del zero results es algo interno del engine de geocoder que devuelve un error (podrian venir cosas como errores de conexion u otros) pero voy a ver como hacer que no muestre nada y listo.

**Comment by LeandroBraier** [comment]
Entiendo MK. Gracias!

**Comment by mkreyness** [comment]
Ya elimine eso que muestra, aparte no agrega nada que diga algun error que signifique que no encontro nada, igual despues sale el otro que dice que no se obtuvieron resultados.
Queres que agregue entonces eso de que tambien busque en las razones sociales ? Lo que pasa es que el dato que se muestra cuando haces click en el punto siempre es el de fantasia (que es el que la gente conoce).

**Comment by LeandroBraier** [comment]
Si, entiendo. Adelante. No hay problema por eso, agregale que busque en la Razón Social también y poné que, por defecto, les tire un radio de 100 km, así encuentran más corralones.

abrazo

**Comment by mkreyness** [comment]
LIsto, fijate que si pones en localidad  Villa Ballester y en nombre "mater", te aparecen unos que se llaman "SADA", esto es porque su razon social en realidad es "SADA MATERIALES SRL".

Tambien puse 100 km por default, la verdad que en Capital eso tira un hormiguero de corralones.

**Comment by LeandroBraier** [comment]
Mejor todavía! Que vean toda la potencialidad de la herramienta.

Gracias!
