### ISSUE TITLE
Newsletter Klaukol de Septiembre. 31/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#149]
Buen día Brau!

Necesito que armes el newsletter de septiembre. Aún no tengo los links pero sí todos los contenidos y fotos que van. Los subí y compartí en este doc como la otra vez:

https://docs.google.com/document/d/1Zu2bYW2bhSdk_dzzqLNqGI1mBLawO59EFBPLtf342wc/edit

Cualquier duda avisame, necesito que esté listo para el lunes si o si, confirmame si llegás porfa. 

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea

Si llego bien. Si podes pasame las imagenes por aca o por mail por favor.

Gracias
Abrazo

**Comment by LeandroBraier** [comment]
Está todo en el doc, fijate que de ahí lo podés descargar. Si necesitás
algo en un tamaño distinto pedimelo por este ticket con las medidas y te lo
armo en un toque.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Fijate ahi lea. 
http://parexklaukol.com.ar/_mailing/novedades-septiembre/novedades-septiembre.html
abrazo

**Comment by LeandroBraier** [comment]
Está perfecto Brau. Solo te pido que esta vez vuelvas a incluir el iconito
con link al club de Colocadores, ya que esta vez si va a estar lanzado para
cuando lo mandemos.

Con eso ya estamos y lo mando. De paso fijate si podés incorporar algo de
los truquitos responsive que usamos en este mailing:

http://www.parexklaukol.com.ar/_mailing/confirmacion_newsletter/confirmacion.html

abrazo

**Comment by LeandroBraier** [comment]
Buen día Braulio! Porfa dale prioridad a esto y avisame cuando le hayas agregado el logito.

abrazo

**Comment by braulio-evangelisti** [comment]
Hola Lea ahi le agregue le logo, baje el html por si le habian hecho algun cambio durante el finde y lo resubi con el cambio.

Veo lo del newletter de confimacion y te aviso.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-31 11:38 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
Brau, tuve feedback del news.
1. Cambiar titulo de la primera nota por "ParexGroup te invita a visitar Expo BuildGreen Argentina 2015" y la descripción a: "Acercate a nuestro stand en el evento más importante del año en Arquitectura y Urbanismo Sustentable el 6 y 7 de octubre en la Usina del Arte – La Boca. Enterate más aquí!
2. En la nota de la presentacion del libro cambiá la imagen por esta:

![imagen-bienal-2](https://cloud.githubusercontent.com/assets/6719872/9611506/6919a210-50b6-11e5-8199-572a28a50b50.jpg)
1. Agregar una nota chiquita arriba de la de Colocadores solo con el logo de la Bienal que diga: 

Ganá 2 entradas para las Conferencias Magistrales en la Bienal de Buenos Aires

Participá de nuestro concurso en Facebook y asistí gratis a estas exclusivas clases sobre el futuro de la Arquitectura Sustentable. Jugá ingresando aquí

![logo-bienal](https://cloud.githubusercontent.com/assets/6719872/9611602/f5cbb220-50b6-11e5-97bd-2e1b810b35bc.png)

Podrá estar para hoy a la noche o mañana temprano a la mañana?

abrazo

**Comment by braulio-evangelisti** [comment]
Perfecto. Termino lo de Francisco y acomodo esto para hoy.

**Comment by braulio-evangelisti** [comment]
Actualizá Lea.

No las puse en 2 columnas contiguas porque ambas imágenes (logo de colocadores y el de la bienal) son muy apaisados y se ven muy chicos y perdidos en mucho fondo gris si los tengo que acomodar al ancho de las imágenes que tenían los news anteriores que eran imágenes mas bien verticales

Abrazo

**Comment by LeandroBraier** [comment]
Así está perfecto. Simplemente te pido que cambies el logo de Bienal por este:
![logo-bienal-2](https://cloud.githubusercontent.com/assets/6719872/9620876/4559c860-50f6-11e5-9daa-f14fdc2b5bab.png)

Con eso ya estamos.

abrazo

**Comment by braulio-evangelisti** [comment]
Acualizá Lea, ya le cambie el logo

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Abrazo

**Comment by LeandroBraier** [comment]
Brau, te faltó un cambio de los que te pedí. 

El de la descripción de la nota de ExpoGreen. Debe decir así: "Acercate a nuestro stand y conocé lo último sobre construcción sustentable en el evento más importante del año sobre el tema. 6 y 7 de octubre en la Usina del Arte – La Boca. Enterate más aquí!"

Confirmame cuando esté hecho porfa.

**Comment by braulio-evangelisti** [comment]
Ahi esta. Disculpa se me paso.

**Comment by LeandroBraier** [comment]
Gracias Brau!

**Comment by LeandroBraier** [comment]
Ahora pusiste el texto que te pasé antes, no el de hoy. Pone el de hoy porfa.

**Comment by braulio-evangelisti** [comment]
jaja ahora?

**Comment by LeandroBraier** [comment]
AHora si. Pará que chequeo con el cliente un minuto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@braulio-evangelisti van los links de las notas en el orden en que van:

http://www.parexklaukol.com.ar/novedades/parexgroup-te-invita-a-visitar-la-expo-buildgreen-argentina-2015.html

http://www.parexklaukol.com.ar/novedades/parexgroup-presenta-el-libro-ventanas-al-futuro-10-anos-en-la-apertura-de-ba15.html

http://www.parexklaukol.com.ar/novedades/piletas-modernas-y-confortables.html

 Ell link que lleva a "Ganá 2 entradas...":

https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/779746295481050/?type=1&theater

http://www.parexklaukol.com.ar/novedades/si-sos-colocador-sumate-a-nuestro-equipo.html

http://www.parexklaukol.com.ar/novedades/visitaremos-mendoza-rosario-y-buenos-aires-con-el-centro-de-formacion-tecnica.html

abrazo

**Comment by LeandroBraier** [comment]
Brau, a qué hora podés tener listo esto?

Te paso ya el link que te faltaba, el de "Ganá entradas para la Bienal":

https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/779746295481050/?type=1&theater

**Comment by braulio-evangelisti** [comment]
Lea puede ser que falte el link de "PILETAS MODERNAS Y CONFORTABLES" y el de "Visitaremos  Mendoza, Rosario y Buenos Aires con el Centro de Formación Técnica".

En la lista que pusiste ahi, hay un link de wetransfer con un zip que se llama "fotos FUCA"

**Comment by LeandroBraier** [comment]
Ahi te actualicé Brau, fue mala mia. Perdon.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo ahi subi el news con los links

Sigo con la news de colocadores

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!
