### ISSUE TITLE
Enviar HTML en mail via LotusNote

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#15]
MK, sabés algo de LotusNote?

Hicimos un newsletter html y ahora el cliente me dice que sólo puede enviarlo desde LotusNote, con lo que tengo que indicarle cómo hacerlo y sin tener ni idea de cómo funciona esa programa. Vos sabés algo?

**Comment by mkreyness** [comment]
Lo unico que sé es que se inventó hace 20 años y nadie lo usa desde hace 
10...

http://es.wikipedia.org/wiki/Lotus_Notes

Segun dice ahi si tienen la version "Domino" deberia manejar HTML.
Pero es un mundo desconocido, tiene mas sentido que le pregunten a la 
gente que les da soporte de Lotus Notes como hacer.

**Comment by LeandroBraier** [comment]
Gracias MK! Entiendo. Cualquier cosa te consulto pero les estoy pidiendo la lista de mails para que lo podamos enviar nosotros al newsletter directamente.

abrazo
