### ISSUE TITLE
Torneo de Potenciados: Modificaciones en Bases y Condiciones URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#150]
Buenas noches Braulio! Mañana a primera hora necesito que modifiques el primer párrafo de todas las bases y condiciones de Torneo de Potenciados. Arriba de todo dice "Comunidad de Vendedores ParexKlaukol" y debe decir "Torneo de Potenciados Klaukol".

Por favor hacelo bien temprano a la mañana en todas las versiones pero primero en la de Representantes comerciales.

abrazo

**Comment by braulio-evangelisti** [comment]
Actualizá las bases de las categorias y fijate si corregí lo que era.

Se puede acceder a Torneos publicamente o con algun usuario de prueba para chequearlo?

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Excelente.

Se puede acceder con usuarios nomás, te paso algunos links para que pruebes.

http://www.parexklaukol.com.ar/cgi-bin/torneo-bases-condiciones.pl?usuario=aldocampanella&clave=127847&torneo=1&tipo=C

http://www.parexklaukol.com.ar/cgi-bin/torneo-bases-condiciones.pl?usuario=norbertocastello&clave=108811&torneo=1&tipo=R

http://www.parexklaukol.com.ar/cgi-bin/torneo-bases-condiciones.pl?usuario=ceramisur&clave=127848&torneo=1&tipo=C

abrazo

**Comment by braulio-evangelisti** [comment]
Gracias. Era para que, en el futuro, si tengo que hacer otro cambio, poder comprobarlo. Abrazo.

**Comment by LeandroBraier** [comment]
Genial. Gracias otra vez! abrazo
