### ISSUE TITLE
Mailing de Bienvenida Colocadores.

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#151]
@braulio-evangelisti , necesito que maquetes el mail de bienvenida de Colocadores.

La estructura que sea la misma que el de Vendedores. La estética es distinta, adaptala de este flyer:

https://www.wetransfer.com/downloads/4bacd00f73716d1dd0393873ea741ab220150828135455/f18b1f

Acá también tenés los textos para reemplazar los que hoy tiene el mailing de bienvenida de vendedores. 

Club de Colocadores Klaukol.
Donde se reunen los que más saben.
Un espacio donde los mejores colocadores del país se capacitan, intercambian consejos y se divierten obteniendo grandes beneficios.
Hemos recibido tus datos personales y con ellos pudimos crear un acceso especial.
HACER CLIC PARA LOGEARTE AUTOMÁTICAMENTE
Nombre de usuario:
Contraseña:
¿Cómo participo?
Entrá a nuestra página www.parexklaukol.com.ar/colocadores/ o acercate a tu Corralón Potenciado Klaukol más cercano.

Abajo el mismo pie que en Vendedores: Seguinos en Facebook + Guia de Corralones + 0800 + logo ParexGroup.

abrazo

**Comment by LeandroBraier** [comment]
Buen día Brau! cómo venís con esto? Necesito hoy ver primer versión.

abrazo

**Comment by braulio-evangelisti** [comment]
Hola Lea. En el transcurso de la tarde te paso el link de una primera version.

Abrazo

**Comment by braulio-evangelisti** [comment]
Lea te paso un par de links:

http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre.html
http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre-b.html

Abrazo.

**Comment by LeandroBraier** [comment]
Está muy bien Brau.

Vamos con la A. Simplemente:
1. Fijate que la palabra "mejores" (...colocadores del país...) tiene un espacio de más-
2. Cambiá el texto de Guia de Corralones por el siguiente:

Nueva Guía de Corralones Klaukol 
Encontrá en segundos donde comprar materiales cerca de tu obra.
Con un sencillo sistema de geolocalización podrás salir de cualquier apuro. 
¡Simplemente ingresá a 
www.parexklaukol.com.ar/guia-corralones!

abrazo

**Comment by braulio-evangelisti** [comment]
Ok. Lo del espacio del punto uno es en la version "B". Lo acomodo o usamos la otra?

**Comment by LeandroBraier** [comment]
Acomodemos en las dos y le presento las dos al cliente por las dudas. Lo ideal sería reducir la cantidad de imagenes al mismo porque por ejemplo el mailing de Bienvenida de Torneo de Potenciados está teniendo MUY poca recepción.

Te pido hacete una tercer versión mucho más minimalista pero sin imagenes, basada en este que te pasé la otra vez:

http://www.parexklaukol.com.ar/_mailing/confirmacion_newsletter/confirmacion.html

Y tomá de referencia este también:

http://parexklaukol.com.ar/_mailing/sumarme/

Esos dos le están llegando a más gente, caen menos en el spam.

abrazo

**Comment by braulio-evangelisti** [comment]
Perfecto.

**Comment by braulio-evangelisti** [comment]
Lea ya estan corregidos los dos puntos de la version A y B. Aca te paso la C. Bajo de 9 a 4 imágenes.

http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre-c.html

Abrazo

**Comment by LeandroBraier** [comment]
Excelente laburo Brau! Muy buena la versión C, con menor cantidad de imagenes. Le voy a proponer las 3 al cliente, aclarando el tema técnico para evitar ir al spam.

Solo te pido un detallecito: se podrá hacer que el último bloque donde está el 0800 sea todo azul el fondo? Así la esquina blanca de ParexGroup queda aplicada sobre eso?

Solo eso. 

abrazo

**Comment by braulio-evangelisti** [comment]
Algo asi decis?
![image](https://cloud.githubusercontent.com/assets/11272253/9789929/49976f40-57a9-11e5-8bdb-8104097d25cb.png)

**Comment by LeandroBraier** [comment]
Exacto asi!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Actualizá nomas. Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! Lo podrás aplicar a eso del azul en la versión a y b también porfa?

Con eso ya estamos con Colocadores y necesitaría que corrijas el de Vendedores con el premio de septiembre.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti , el cliente elegió la versión C, la que tiene menos imagenes para no caer al spam. Vamos con esa. El único cambio que me pidió es sacar el segmento de "Como me sumo".

abrazo

**Comment by braulio-evangelisti** [comment]
Done!

**Comment by LeandroBraier** [comment]
Perfecto Brau! Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti como va? Necesitaría que hagas una versión D de este mailing y le agregues una imagen que transmita la idea de un Carnet de Socio de un Club de Verdad, como en esta referencia:

![ejemplo giff 1](https://cloud.githubusercontent.com/assets/6719872/10623029/b82dfe38-7761-11e5-82dc-3be9ea2fcddc.JPG)

Si se te complica el diseño avisame y lo pido al equipo de diseño, pero por cosas que te vi hacer creo que te puede quedar lindo.

abrazo

**Comment by braulio-evangelisti** [comment]
Hola Lea. 

Dale ya me pongo. La imagen iría como imagen principal donde esta el logo ahora o sumada en una sección como las de abajo? Va a ser imagen una vez definida o se va a tener que maquetar después?

Abrazo

**Comment by LeandroBraier** [comment]
Es una imagen principal que iría en lugar del LOgo del Club, porque claramente la tarjeta incluiría dicho logo.

Ahora lo segundo que vos me preguntás me lo estaba preguntando. Hay forma de maquetar la imagen para que el número de socio de cada tarjeta sea distinto?

**Comment by braulio-evangelisti** [comment]
Si calculo que no va a haber problema, por eso te preguntaba para ya ir teniendolo en cuenta al armarla. Apenas tenga una imagen te lo paso asi vamos puliendo sobre eso y luego armo la maqueta.

**Comment by LeandroBraier** [comment]
Excelente Brau. Muchas gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-20 19:51 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
@braulio-evangelisti cómo venís con este mailing? Lo necesitaría tener mañana a la mañana. Llegás?

**Comment by braulio-evangelisti** [comment]
Buen dia Lea

En un rato lo subo

**Comment by LeandroBraier** [comment]
Gracias Brau! Ya les volvió la luz? Anoche recién me enteré del apagón en
Rosario.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Fijate si te parece que puede ir ahi. Cuando me confirmes paso a texto la parte de los datos.

http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre-d.html

Si volvió anoche a última hora, parecía que se venia el apocalípsis jaja TODA la ciudad a obscuras y varias localidad de santa fe y el norte de bsas dicen los diarios.

**Comment by LeandroBraier** [comment]
Quedó buenísimo Brau!!! Gracias!! Lo veo con el cliente y te confirmo.

Si, tengo familia allá y me contaban eso, tremendo!! Qué suerte que ya
volvió.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-22 8:19 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA reabro este ticket porque el mailing necesita un cambio:

El texto que dice:

"Hemos recibido tus datos personales y con ellos pudimos crear un acceso especial. "

reemplazarlo por:

"¡Gracias por sumarte al Club de Colocadores Klaukol! A partir de ahora ya tenés tu carnet de pertenencia al club y podés ingresar online haciendo clic en el siguiente acceso especial:"

Lo necesitaría para hoy junto con la versión responsive.

Esto lo estaba haciendo Braulio, seguro lo modifica en dos segundos.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea ahi subi el cambio y la tarjeta maquetada en vez de imagen.

**Comment by LeandroBraier** [comment]
@FAAREIA : El cliente pidió un cambio más de texto. Tengamoslo junto con el Club a este cambio.

Arriba de la tarjeta que diga:

"¡Bienvenido al Club de Colocadores Klaukol!"

Debajo de la tarjeta, donde ahora dice:

"DONDE SE REUNEN LOS QUE MÁS SABEN
Un espacio donde los mejores colocadores del país se capacitan, intercambian consejos y se divierten obteniendo grandes beneficios."

Reemplazar por:

"Ya formás parte del Club donde se reúnen los que más saben. En este espacio te vas a poder capacitar para perfeccionar tu trabajo, intercambiar consejos y divertirte obteniendo grandes beneficios junto a los mejores colocadores del país."

Del texto de abajo quitar la frase que dice "¡Gracias por sumarte al Club de Colocadores Klaukol!"

También quitar la frase que dice: "Hacé click acá para logearte automaticamente"

abrazo

**Comment by LeandroBraier** [comment]
Ojo que actualicé el ticket, tomalo de la web al texto

**Comment by FAAREIA** [comment]
Asi?
http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre-e.html

**Comment by LeandroBraier** [comment]
Perfecto Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA y Brau!

Me pidió el cliente hacer una versión F de este mailing en el cual el logo de Club de Colocadores Klaukol  esté arriba del carnet, debajo del texto de "Bienvenido al...". Es para evitar que un colocador imprima la tarjeta y trabaje en nombre de la marca.

Quedaría así el mailing:

"Bienvenido al" + LOGO"+ Carnet del Club sin logo

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahí Lea

http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre-f.html

Abrazo

**Comment by LeandroBraier** [comment]
Lo veo bien Brau! Quedate ahí atento que lo hago aprobar y te confirmo.

abrazo

**Comment by LeandroBraier** [comment]
Está aprobado Brau!! Gracias!

http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-septiembre-f.html

Se lo paso a @mkreyness para que haga el primer envío a todos los registrados hasta ahora en el club. Porfa ayudalo en lo que necesite para poder lanzarlo hoy o a más tardar mañana a la mañana temprano.

abrazo

**Comment by mkreyness** [comment]
no entiendo, por que se llama "septiembre" ?

**Comment by mkreyness** [comment]
Me parece que aca hay conceptos del "torneo de potenciados" mezclados, porque esta abierto por categorias.
Esto tiene que ser siempre un mismo mailing fijo, no ? 
Tomo ese (septiembre-f) y lo renombro como colocadores-bienvenida.html, ok ?

**Comment by LeandroBraier** [comment]
Exacto, no le des bola a esa nomenclatura. El Club de Colocadores nunca se lanzó y no hay categorías de colocadores. Es solo ruido de la URL que fue quedando.

**Comment by mkreyness** [comment]
Ok @braulio-evangelisti elimino el resto de htmls que hay en la carpeta colocadores-bienvenida para sacar todo ese ruido, y renombro el septiembre-f como colocadores-bienvenida.html y lo toco un poco.

**Comment by mkreyness** [comment]
Repasando este tema porque lo tenia bastante olvidado, el mail que estariamos mandando mas que de bienvenida es de ACTIVACION, porque la gente ya vio un cartel que decia "pronto te vamos a mandar un mail para activarlo".
Otra cosa que veo es que la gente escribio sus propias passwords, por lo tanto no se si esta bien que se las mandemos, en todo caso habria que mandarlo sin password y si se la olvidó, que pida "olvidé mi password" (cosa que acabo de darme cuenta que NO esta funcionando, da un error 404).
Estoy primero arreglando esto y despues te mando un mail de prueba.

**Comment by braulio-evangelisti** [comment]
https://github.com/LeandroBraier/Klaukol/issues/151#issuecomment-155189045

OK

**Comment by mkreyness** [comment]
@LeandroBraier nos esta faltando algun HTML para el mailing de olvido de contraseña.
Ahora que active esa parte, no encuentro el mailing correspondiente. Si esta en algun lado y yo no lo veo por favor haganmelo saber.

Les pongo como ejemplo el que hay en el Club de Vendedores:

http://www.parexklaukol.com.ar/_mailing/vendedores-recordar/vendedores-recordar.html

Si no existe, habria que hacer algo asi acorde a la estetica/logos del Club de Colocadores urgente, porque lo primero que va a pasar (para esta gente que puso sus passwords hace meses) es que se las olvide.

**Comment by LeandroBraier** [comment]
Entiendo @mkreyness Por ahora hagamos lo siguiente:

1) @FAAREIA te pido que veas con Braulio la adaptación del HTML para mailing de olvido de la contraseña. En realidad es una versión abreviada del Mailing de Bienvenida.

2) Mientras tanto @mkreyness mandá el mail de bienvenida como siempre, contraseña incluida, aunque ellos la hayan escrito. De esa forma no necesitamos el mailing de olvido tan urgente. Entiendo por qué decís de no incluirla, pero en esta tanda y hasta que tengamos mailing de olvido dejá el mailing de bienvenida y el autologeo automático como siempre.

abrazo

**Comment by mkreyness** [comment]
2) ok, pero el link de "olvide mi contraseña" existe y lo pueden clickear, no tendriamos preventivamente que ocultarlo ?

**Comment by LeandroBraier** [comment]
Dale, preventivamente ocultemoslo porfa. Te referís al login del Club de
Colocadores no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si. Ahi lo saque.
Te mando un mailing de prueba.

**Comment by mkreyness** [comment]
Ah, me falto lo de sumar el numero. Ahora te mando otro.

**Comment by LeandroBraier** [comment]
Que suerte que mandaste pruebas Marce! Me llegaron las dos.

Mirá como veo los carnets:

<img width="860" alt="captura de pantalla 2015-11-09 a las 9 47 11 p m" src="https://cloud.githubusercontent.com/assets/6719872/11050947/66663f70-8729-11e5-8de3-3308a6484395.png">
<img width="882" alt="captura de pantalla 2015-11-09 a las 9 47 57 p m" src="https://cloud.githubusercontent.com/assets/6719872/11050948/672e4ede-8729-11e5-8498-90358f950f6a.png">

En el celu mejor ni te cuento cómo se ve.

**Comment by mkreyness** [comment]
Se corta el logo porque wrapea el texto ? Es un tema para que lo vean Fede/Braulio entonces, yo lo unico que hago es tener un nombre largo...

**Comment by LeandroBraier** [comment]
No, me parece que lo que ocurre es que, en lugar de mantener el tamaño de la tarjeta y que el texto arranque más arriba, lo que hace el html es prolongar la tarjeta "descropeando" una parte (con perdón de la palabra) de modo que luego no hay forma de que quede como una tarjeta contínua.

Tal cual @FAAREIA y @braulio-evangelisti esto es algo que van a tener que ver mañana a uds. Frenemos acá MK y que ellos lo retoquen. Si lo resuelven antes de las 10 am los podrás mandar a esa hora a los mailings?

**Comment by mkreyness** [comment]
Yo 9:30 a mas tardar me voy, pero despues en algun momento de la mañana puedo conectarme un ratito y mandarlos.

**Comment by braulio-evangelisti** [comment]
Tenía espacio para un solo reglón, cuando el texto armaba otro el fondo se repetía, se me pasó que podía haber alguien con un nombre tan largo. Ahí rearme la imagen de la tarjeta y le acomode el contenedor del nombre para que sea uno o dos reglones el fondo sea el mismo.

**Comment by LeandroBraier** [comment]
Gracias Brau! No lo habíamos pensado es cierto.

Buen día MK! Porfa mándame una nueva prueba asi podemos dejar enviando
antes de irte .

Abrazo

**Comment by mkreyness** [comment]
Ahi te mande.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness

@braulio-evangelisti parece que no está solucionado aún. Fijate que otra vez está repitiendo una parte del carnet. No podés hacer que el fondo del carnet sea independiente del texto que va arriba?

Les paso captura.

<img width="824" alt="captura de pantalla 2015-11-10 a las 9 04 16 a m" src="https://cloud.githubusercontent.com/assets/6719872/11061744/eb08642a-8787-11e5-82d6-dca0d79cbfc6.png">

**Comment by braulio-evangelisti** [comment]
Hice las modificaciones sobre el html que genero mk:

http://parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida.html

Tendria que estar bien, te paso como lo veo aca:

![image](https://cloud.githubusercontent.com/assets/11272253/11061941/7c3f35d0-8789-11e5-9c3c-1c5916a09a4b.png)

Si lo estas viendo del navegador proba de actualizar con ctrl+F5, reenviamelo si podes.

**Comment by LeandroBraier** [comment]
Lo estoy viendo en Gmail @braulio-evangelisti 

@mkreyness puede ser que hayas agarrado una versión anterior?

**Comment by mkreyness** [comment]
Hay una sola version desde que yo empece, la que Braulio paso. Todo el resto lo movi a otra carpeta precisamente para no confundir.

**Comment by LeandroBraier** [comment]
Ahi les reenvié el mail a uds asi me dicen como lo reciben. Brau, quedemonos trabajando en esto hasta que lo resolvamos, MK sale ahora.

@mkreyness a qué hora volvés?

abrazo

**Comment by mkreyness** [comment]
Yo lo veo bien, pero tendrias que mandarmelo a GMail a ver que pasa.
Yo tipo 13:30 probablemente me pueda conectar remoto como para mandar cosas, a mi oficina llego a las 4.

**Comment by braulio-evangelisti** [comment]
Yo tambien lo veo bien. Confirmame si hiciste lo de actualizar con ctrl+F5 que si no funcionó eso le cambio el nombre a las imagenes para que las cargue de cero en un nuevo envio

**Comment by LeandroBraier** [comment]
Si le di F5 yo. Pero proba cambiarlas por las dudas y probamos.

**Comment by braulio-evangelisti** [comment]
Ok. Ahi actualice el html con los nombres nuevos de las imágenes, en un nuevo envio tendria que verse bien.

Abrazo.

**Comment by LeandroBraier** [comment]
Gracias Brau!

@mkreyness cuando llegues 13.30 haceme una prueba más porfa.

abrazo

**Comment by mkreyness** [comment]
ahi te mande. No llegue, estoy conectado remoto.

**Comment by LeandroBraier** [comment]
Ahora se ve perfecto!!

![captura de pantalla 2015-11-10 a las 1 34 28 p m](https://cloud.githubusercontent.com/assets/6719872/11067906/988f90b2-87ad-11e5-871f-e43bd12d7599.png)

Adelante nomás.

**Comment by mkreyness** [comment]
Ok, mando todo.

**Comment by LeandroBraier** [comment]
Tal cual. Gracias a los dos!!!

**Comment by braulio-evangelisti** [comment]
:+1:

**Comment by LeandroBraier** [comment]
Gracias a
