### ISSUE TITLE
Bug Editor HTML Novedades KLAUKOL. 03/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#152]
@mkreyness necesito que el botón de subir fotos del editor html permita subir fotos también a la carpeta IMG. Tal como está ahora solo permite poner fotos via URL.

abrazo

**Comment by mkreyness** [comment]
Es que esa es la funcionalidad interna del ckeditor, no de mi programa, no creo que se pueda customizar, y mucho menos modificar el programa. No tiene para hacer upload. Habria que buscar si alguien desarrollo algun plugin para eso.

"La" imagen de la novedad (si es una sola) la deberias subir a traves de la primer solapa, donde figuran la "imagen chica" y la "imagen grande", que suben automaticamente a la carpeta de novedades correspondiente al pais  (no es "img", es /media/wysiwyg/Noticias-AR/ para Argentina, /media/wysiwyg/Noticias-PY/ para Paraguay, etc. lo hace solito.
Esta asi por compatibilidad con el backup recibido.
Una vez que lo subiste ahi te arma el HTML solo, y despues editas el resto.

**Comment by LeandroBraier** [comment]
Sisi, eso lo sé. Pero pensalo desde el punto de vista del usuario.

Hoy si quiero agregar una imagen más dentro del articulo tengo que subirla como slide "suspendido" en vendedores y chorear el link de ahi. Supongo que debe haber una manera más fácil de hacer eso no?

**Comment by mkreyness** [comment]
Hay que mirar en la documentacion del ckeditor a ver si tienen algo mas en una version paga o algo.
Mientras te puedo armar un repositorio de imagenes generico, pero siempre van a tener que copiar el URL al editor.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
Buen día MK! Avisame como venis con esto.

abrazo

**Comment by mkreyness** [comment]
CKEditor dice que eso no es posible por limitaciones de seguridad de los servidores, que el repositorio se lo tiene que armar uno. Si hay una cosa que se llama CKFinder (que es paga) que permite hacer una interfaz para uploads separada, pero para eso hago mi propio repositorio y listo, te parece ?
Lo que si van a tener que saber como referenciar las imagenes.

**Comment by LeandroBraier** [comment]
No hay problema, vamos con repositorio propio nomas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 11:58 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Hago repositorios separados por sitio y producto, ok ? (sitio: argentina/paraguay/uruguay, producto: klaukol/parex/lanko/revear)

**Comment by LeandroBraier** [comment]
Pero esto no era para novedades? Mejor sería solo por sitio, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ah, tenes razon, las novedades son multi-marca. Ok, por sitio entonces.

**Comment by mkreyness** [comment]
Listo, fijate que en el menu de novedades ahora hay 3 items de Imagenes (Arg/Py/Uy).
Eso deja las imagenes en las mismas carpetas donde hasta ahora se estaban poniendo las otras (el thumbnail de cada noticia). Pero ojo que no aparecen las que ya estan, solo van a ver aca las nuevas que vayan agregando.
Los URL que pongan tienen que ser del mismo tipo que como se ven las que ya estan, por ejemplo:

`/media/wysiwyg/Noticias-AR/expo.jpg`

es una de Argentina.
Ojo que si suben otra cosa que se llame justo expo.jpg, la pisan.

Los respectivos de Uruguay y Paraguay se llaman Noticias-UY y Noticias-PY

**Comment by LeandroBraier** [comment]
Ok, MK. Pero recordá que la idea era tener eso a mano cuando estamos
armando el artículo de novedades. No podés poner un acceso desde el mismo
fomulario donde estamos armando las novedades? Sino desde la funcionalidad
es un embole salir y volver a entrar solo para cargar una imagen.

Además pongamosle algo automático para que no se pisen las fotos porque
estoy tiene que ser a prueba de cliente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 12:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Entonces lo que habria que implementar es un repositorio POR CADA noticia, para que sea una solapa dentro del mismo formulario, y tal vez tener una carpeta propia por cada noticia asi no se pisan los nombres.
Lo que no puedo es interactuar con lo que hagan dentro del CKEditor, el URL que tienen que poner seria un poco mas complicado porque tendria que incluir el ID que se le asigne a la noticia.

**Comment by LeandroBraier** [comment]
Me parece perfecto MK. Adelante.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 15:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, quedo una solapa "Imagenes" dentro de cada noticia de cada uno de los sitios.
Cada repositorio es propio de la noticia asi que se aislan completamente unas de otras.
Se pueden poner todas las imagenes que hagan falta, y para ver el URL basta con hacer click en los "..." que aparecen debajo de la imagen (eso abre un popup con la imagen) y se puede copiar el URL de ahi.
El campo de descripcion lo puse obligatorio para que despues no queden las imagenes inaccesibles.

**Comment by LeandroBraier** [comment]
Excelente MK! Gracias!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 19:49 GMT-03:00 mkreyness notifications@github.com:
