### ISSUE TITLE
Bug Torneo de Potenciados. 03/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#153]
En un perfil de corredor aparece una leyenda que dice "Vendé 0 bolsas equivalentes para entrar". Por qué es eso?

<img width="1072" alt="captura de pantalla 2015-09-03 a la s 13 40 25" src="https://cloud.githubusercontent.com/assets/6719872/9664645/94ece816-5241-11e5-8ed7-9b7851b2754b.png">

Te paso link: http://parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=fernandogeller&clave=128616&torneo=1&tipo=C

Es un error? Corrijamoslo porfa.

**Comment by mkreyness** [comment]
Debe ser que estan iguales a nivel porcentaje, pero quedo detras por menores ventas totales.
En cuanto pueda le cambio a que diga 1, suponia que no iba a darse un caso tan extremo.
Pero igual primero lo voy a revisar, porque es raro.
En un par de horas llego a mi oficina y lo miro.

**Comment by LeandroBraier** [comment]
Dale, gracias. Ponele que mínimo diga 1 bolsa y listo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-03 13:58 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ahi le puse.

**Comment by LeandroBraier** [comment]
Gracias Marce!
