### ISSUE TITLE
Torneo de Potenciados- Base de datos Actualizada al 31-08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#154]
@mkreyness te pasé por mail la base. Avisame cuando pudiste actualizarla.

abrazo

**Comment by mkreyness** [comment]
LIsto, todo cargado.

**Comment by LeandroBraier** [comment]
Gracias MK!

Consulta: me dicen las chicas que nadie dice recibir los mailings de bienvenida de esta plataforma. Incluso en el analytics veo solo 24 visitas. Tenés idea qué puede estar pasando?

**Comment by mkreyness** [comment]
Vos estabas copiado en todos los mails que salieron a los corredores, se refiere a que los corredores no lo recibieron ? O habla de corralones ?
Cualquier rebote tiene que haberles llegado a la direccion de marketing.klaukol que me pasaron para usar.

**Comment by mkreyness** [comment]
En la casilla de default de la cuenta parexklaukol hay unos cuantos rebotes de cosas de Paraguay, pero no de esto.

**Comment by LeandroBraier** [comment]
Perfecto, entiendo. Entonces lo más probable es que caigan en Spam, verdad?

**Comment by LeandroBraier** [comment]
Perfecto, entiendo. Entonces lo más probable es que caigan en Spam, verdad?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones <http://benteveo.tv>
Móvil 1158717399

2015-09-03 17:02 GMT-03:00 mkreyness <notifications@github.com>:

**Comment by mkreyness** [comment]
Cuando se manda HTML con imagenes el riesgo de que eso pase es grande, si.
Pero vos recibiste los 20 mails de corredores, no ?

**Comment by LeandroBraier** [comment]
Sip, todos. Te consulto porque el cliente está preocupado por esto y habla con los dueños de corralones y dicen que no recibieron nada. Quizá tengamos que recurrir a MailChimp después de todo no?

**Comment by mkreyness** [comment]
Es muy raro, porque no hay ningun rebote por volumen ni nada. Eran miles, no puede ser que ninguno haya llegado.

**Comment by LeandroBraier** [comment]
Imposible de saber, porque tenemos Analytics de esa plataforma hace muy
poco, no? Pero solo veo 46 visitas en total.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-03 17:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ni idea, lo malo que como acá no se asignan puntos por entrar como en el de Vendedores, no tengo tampoco donde mirar yo.
