### ISSUE TITLE
Modificaciones en Bases y Condiciones de TODAS las Plataformas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#155]
Brau, necesito modificar detalles de todas las bases y condiciones de nuestras plataformas. Lease:

**_COMUNIDAD DE VENDEDORES**_
**_CLUB DE COLOCADORES**_
**_TORNEO DE POTENCIADOS**_ (todas las versiones)

Abajo de todo hay unos párrafos en gris en fuente más chica. Deberían quedar como te paso a continuación:
`Todos ellos y en su conjunto denominados los PREMIOS o individualmente como el PREMIO.
Los PREMIOS se asignarán conforme el procedimiento establecido en el apartado MECÁNICA DE PARTICIPACIÓN.
El ORGANIZADOR no se hará cargo de ningún gasto extra y/o adicional en que incurra el ganador.
El PREMIO no incluye cualquier otro gasto, ni ningún otro servicio o bien distinto del expresamente mencionado en las presentes BASES, como así tampoco ningún impuesto en que el ganador deban incurrir para la utilización de los PREMIOS. El PREMIO no podrá ser reclamado por otras personas que no sean los ganadores. Si el ORGANIZADOR tomara conocimiento que el PREMIO ha sido comercializado por el PARTICIPANTE ganador, podrá dejarlo sin efecto en forma automática, sin derecho a compensación alguna.`

abrazo

**Comment by mkreyness** [comment]
Braulio tene en cuenta que todos estos textos se muestran actualmente de sus respectivos templates `(public_html/templates/parexklaukol/<plataforma>/<archivo>T.html`

**Comment by braulio-evangelisti** [comment]
Perfecto, no los encontraba.

Descargué los templates recién y reemplacé en cada archivo solo las líneas que pusiste acá.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Fijate que abajo de todo, donde pusimos MECANISMO DE PARTICIPACIÓN aparecen unos signos raros, como de acentos fallidos. Te fijás porfa?

abrazo

**Comment by mkreyness** [comment]
Es porque salen del template justamente, se arma mucho lio con los cambios de encoding al subir y bajar. Lo mejor es usar HTML encoding (`&aacute;`, etc.)

**Comment by mkreyness** [comment]
En este caso que dice Lean hay que poner `&Oacute;`

**Comment by braulio-evangelisti** [comment]
Es en todos los acentos de las bases de todas las plataformas que subi recien? En Torneos aca lo veo bien, del colocadores y vendedores no tengo usuario para entrar y poder chequear.

**Comment by mkreyness** [comment]
No hace falta tener usuario, podes entrar a la de vendedores aca:

http://www.parexklaukol.com.ar/cgi-bin/basesycondiciones.pl

y a la de colocadores aca:

http://www.parexklaukol.com.ar/cgi-bin/basescondicionescolocadores.pl

**Comment by LeandroBraier** [comment]
Es en vendedores nomas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Muchas Gracias. Ahi lo acomodé.

**Comment by LeandroBraier** [comment]
Gracias Brau y MK!
