### ISSUE TITLE
Agregar Sección de Ganadores/ Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#156]
@FAAREIA necesito que armemos una sección con las fotos de ganadores de cada mes de la Comunidad de Vendedores. Pasame un mock up en jpg así lo hago aprobar y calculá tiempos para avisarme para cuando lo podríamos subir.

abrazo

**Comment by FAAREIA** [comment]
Ahi va el jpg Lea

![sin-titulo-1](https://cloud.githubusercontent.com/assets/6184969/9736614/a0605126-5618-11e5-9fff-ba936d23c524.jpg)

**Comment by LeandroBraier** [comment]
Gracias Fede! Justo estoy con el cliente, lo veo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA !

Te doy feedback de esto. Igual no es prioridad, puede ser para la semana que viene ponele, en algún hueco que tengan.

El diseño está aprobado, solo que con los siguientes aditamentos:
1. Que los Ganadores estén separados por título intermedio que diga "Ganadores de Julio" "Ganadores de Agosto" etc
2. Que en el CMS yo pueda cargar las fotos, que serían de dos tipos. Una chiquita para ese thumbnail que me mostrás en el mock up y una completa del tipo recibiendo el premio, que se vería al hacer clic sobre la primera.

abrazo

**Comment by LeandroBraier** [comment]
Buen día Fede!

Para cuando podríamos tener esto listo? Para el lunes llegás? Tendría que tener la forma de carga de fotos y demás a través del CMS:

**Comment by FAAREIA** [comment]
El lunes mismo lo puedo hacer, dependiendo cuanto me lleve vemos las fechas de academia.
Copio a @mkreyness para que vaya preparando todo.

**Comment by LeandroBraier** [comment]
Genial.

Igual evalualo.

Prefiero que si te atrasa la primer entrega de Academia lo entregues el
martes y tengamos primera versión de academia el lunes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-18 19:04 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/vendedores/ganadores.html

Ahi va vendedores. @mkreyness habría que hacerlo template y editable via CMS.

**Comment by mkreyness** [comment]
```
lo variable seria mes, puesto, vendedor, y un texto para describir
el premio en c/u ?

El 21/09/2015 a las 12:17, Federico
  Arena escribió:


  http://parexklaukol.com.ar/vendedores/ganadores.html
  Ahi va vendedores. @mkreyness
    habría que hacerlo template y editable via CMS.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Agrégale un numero de orden como en los slide shows. Y un espacio para
subir una imagen más grande que aparezca al hacer clic sobre la imagen
chica.

**Comment by mkreyness** [comment]
```
El puesto no determina el numero de orden ?

El 21/09/2015 a las 14:23,
  LeandroBraier escribió:

Agrégale un numero de orden como en los slide shows. Y
  un espacio para
  subir una imagen más grande que aparezca al hacer clic sobre la
  imagen
  chica.
  El sep 21, 2015 12:32 PM, "mkreyness"
  <notifications@github.com> escribió:

  >
  >
  >
  >
  >
  > lo variable seria mes, puesto, vendedor, y un texto para
  describir
  > el premio en c/u ?
  >
  > El 21/09/2015 a las 12:17, Federico
  > Arena escribió:
  >
  >
  > http://parexklaukol.com.ar/vendedores/ganadores.html
  > Ahi va vendedores. @mkreyness
  > habría que hacerlo template y editable via CMS.
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/156#issuecomment-142016524
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Nop, es solo info.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-21 14:25 GMT-03:00 mkreyness notifications@github.com:

> El puesto no determina el numero de orden ?
> 
> El 21/09/2015 a las 14:23,
> LeandroBraier escribió:
> 
> Agrégale un numero de orden como en los slide shows. Y
> un espacio para
> subir una imagen más grande que aparezca al hacer clic sobre la
> imagen
> chica.
> El sep 21, 2015 12:32 PM, "mkreyness"

**Comment by mkreyness** [comment]
```
otra duda: la foto es la foto que el tipo subio de si mismo u otra
que le van a sacar ustedes ?

El 21/09/2015 a las 15:44,
  LeandroBraier escribió:

Nop, es solo info.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-09-21 14:25 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > El puesto no determina el numero de orden ?
  >
  > El 21/09/2015 a las 14:23,
  > LeandroBraier escribió:
  >
  > Agrégale un numero de orden como en los slide shows. Y
  > un espacio para
  > subir una imagen más grande que aparezca al hacer clic sobre
  la
  > imagen
  > chica.
  > El sep 21, 2015 12:32 PM, "mkreyness"
  > <notifications@github.com> escribió:
  >
  > >
  > >
  > >
  > >
  > >
  > > lo variable seria mes, puesto, vendedor, y un texto para
  > describir
  > > el premio en c/u ?
  > >
  > > El 21/09/2015 a las 12:17, Federico
  > > Arena escribió:
  > >
  > >
  > > http://parexklaukol.com.ar/vendedores/ganadores.html
  > > Ahi va vendedores. @mkreyness
  > > habría que hacerlo template y editable via CMS.
  > > —
  > > Reply to this email directly or view
  > > it on GitHub.
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > >
  > <
  >
```

https://github.com/LeandroBraier/Klaukol/issues/156#issuecomment-142016524
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/156#issuecomment-142049128
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
La subimos nosotros a la foto.

**Comment by FAAREIA** [comment]
Ahi agregué al HTML la posibilidad de abrir una foto más grande al hacer click sobre la foto del premio.

**Comment by LeandroBraier** [comment]
Genial. Ya se pueden cargar los ganadores por cms entonces?

**Comment by mkreyness** [comment]
Yo tengo que cambiar eso de que la foto chica sea tambien uploaded.
Fede eso lo tocaste sobre tu pagina o sobre el template ?
El template es www/templates/vendedores/ganadoresT.html

**Comment by mkreyness** [comment]
perdon
www/templates/parexklaukol/vendedores/ganadoresT.html

**Comment by mkreyness** [comment]
Listo ya cambie yo el template.
Podes cargar en el CMS, Lean, ya hay un par de prueba que tendrias que modificar.
Ojo que los campos mes y año no estan validando nada.

El resultado se ve en

http://www.parexklaukol.com.ar/cgi-bin/ganadores.pl

@FAAREIA habria que enganchar esto en algun menu ?
Para que aparezca bien el encabezado hay que incluirle las variables

http://www.parexklaukol.com.ar/cgi-bin/ganadores.pl?usuario=`<!--usuario-->&clave=<!--clave-->`

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias chicos! Lo cargo desde el CMS, lo hago aprobar por el cliente y les aviso cuando esté OK lo agregamos en el menú de la home de la Comunidad.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness ahi cargué todos los ganadores y no se ven los de agosto. Te fijás que pudo haber pasado? Me fijé y cargué todos bien pero solo se ven Junio y Julio.

http://www.parexklaukol.com.ar/cgi-bin/ganadores.pl

abrazo

**Comment by mkreyness** [comment]
no tenian "prendido" el estado de publicar (que seguramente esta invisible). Ya se los prendi y lo puse por default asi no joroba mas.

**Comment by LeandroBraier** [comment]
Gracias MK!! @FAAREIA no entiendo por qué no aparecen número en las medallas de Agosto. Qué puede ser?

Ya podés ir agregando el link a esta sección en la home.

abrazo

**Comment by mkreyness** [comment]
Debe ser algo mio, porque no esta poniendo fisicamente el numero ahi. Ahora lo chequeo.

**Comment by mkreyness** [comment]
Si, habia un dato que era el numero de orden y otro separado del numero de puesto, porque en realidad se pueden REPETIR los puestos. Ahora te habilito bien esos campos en el CMS asi tenes el control completo de la situacion.

**Comment by mkreyness** [comment]
Ahi estaba el kilombo, tenia el "Estado" y el "Numero de Puesto" pisandose entre si, por eso no lo veias. Fijate que habria que corregirle entonces el numero de puesto porque en realidad es local a cada mes, no es que el tipo de julio es el puesto 2 y el de junio el puesto 1, eso estuvo mal puesto de movida. Ambos deberian ser "puesto 1" en su mes.

**Comment by LeandroBraier** [comment]
Gracias MK! Todo corregido!

abrazo
