### ISSUE TITLE
Bug Comunidad de Vendedores Datos RominaVeliz

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#157]
@mkreyness , me pasa con este usuario que le quiero guardar los datos y no los guarda.

http://www.parexklaukol.com.ar/cgi-bin/perfilvendedores.pl?usuario=RominaVeliz&clave=edel1976

Me parece que tiene que ver con la base. El usuario cambió su código de Login de EdelRominaVeliz a RominaVeliz. Cuando me bajé el excel hoy, sin embargo, me seguí figurando con el primero. Puede ser eso?

abrazo

**Comment by mkreyness** [comment]
Pero no existe "cambiarse el usuario", no es un campo habilitado al propio usuario.

**Comment by mkreyness** [comment]
Esta dos veces cargada en la base, con diferente nombre, una vez como rominaveliz con nombre Romina, y la otra como edelrominaveliz, con nombre Edel Romina.
Asi vino de origen, los emails son el mismo, pero yo no estoy impidiendo emails iguales (acordate que teniamos mucha gente con el mismo email).
Al ser codigos diferentes, a mi no me saltó duplicado.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Podemos unificarlo de alguna manera?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 16:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, pero capaz va a quedarle el mismo juego jugado mas de una vez y eso es trampa :0)
En cual lo junto entonces, en Romina ?

**Comment by LeandroBraier** [comment]
Dejame chequear y te digo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 18:04 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
No, unificalo en EdelRomina.

RominaVeliz nunca lo usó parece, así que podés borrarle cualquier actividad
que haya hecho ahí.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-07 18:10 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
Listo, entonces borre a RominaVeliz y solo existe EdelRominaVeliz

**Comment by LeandroBraier** [comment]
Perfecto. Igual le cargo el DNI a esa cuenta, pongo Guardar y luego no
aparece. Te fijás qué puede estar pasando?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Pasame que DNI ponerle

**Comment by LeandroBraier** [comment]
Probá con cualquier numero vas a ver.

El usuario lo sube y no se lo guarda. Eso es un BUG de la plataforma. Hay
que arreglarlo. La mina nos escribió por facebook.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Veo, ahora lo arreglo y te aviso.

**Comment by mkreyness** [comment]
Listo, no tomaba ese campo.
Capaz en un principio no se habia definido que fuera editable porque se iba a usar como codigo.
A esta chica le quedo puesto cualquier cosa, corregiselo o decile que lo cambie.

**Comment by LeandroBraier** [comment]
Perfecto. Le estaba pasando a todos?

Porfa chequeá que esté corregido en todos por las dudas.

abrazo

**Comment by mkreyness** [comment]
Le pasaba a cualquiera, casi no hay DNIs cargados. Los que hay deben ser que vinieron en alguna base.

**Comment by LeandroBraier** [comment]
Entendido. Gracias MK!

Si podés mañana revisá que no esté pasando en otros campos importantes algo parecido.

**Comment by mkreyness** [comment]
Aca en el de vendedores era el unico. Seguramente fue algo que se modificó sobre la marcha, por eso los cambios son peligrosos.
En el de COLOCADORES el DNI esta bloqueado, porque se pide en la registracion y despues no lo deja cambiar. Si en algun momento piden que se pueda cambiar, ahi hay que tenerlo en cuenta.
