### ISSUE TITLE
Mailing Bienvenida Vendedores Septiembre

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#158]
Buen día Brau!

Aproximadamente al mediodía te voy a estar pasando la estética de los premios de este mes, por lo que habría que hacer una adaptación al mailing de bienvenidsa con el premio de este mes.

Asi como te pedí con el mailing de colocadores, te pido que hagas aparte una versión minimalista, sin imágenes del mail, para probar como funciona.

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea. Ok, espero nomas. Abrazo.

**Comment by LeandroBraier** [comment]
Mejor andá haciendo las adaptaciones. Lo unico que tendrías que cambiar
cuando te pase el premio es el header. Asi vamos ganando tiempo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Brau, te paso en este wetransfer las dos estéticas posibles para que armes el header del mailing de bienvenida de Vendedores de Septiembre. Elegí la que te parezca que queda mejor en el mail y confirmame porfa cuando lo tengas.

https://www.wetransfer.com/downloads/efd80000300128e3418cc940ba7b2ed820150909181121/485235

abrazo

**Comment by LeandroBraier** [comment]
Brau, confirmame porfa. Hoy llegás con esto no?

**Comment by braulio-evangelisti** [comment]
Estoy con la adaptacion aun Lea. 
El slide que baje es igual al de agosto pero con la tablet en vez de campera y tarjeta, seria armar otra adaptacion diferente para septiembre pero partiendo de la misma estetica? o hay otro psd para que siga otra linea? o armo algo diferente totalmente con la misma info de aca: http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-septiembre.html ?

**Comment by LeandroBraier** [comment]
Está perfecto así, solo dos cositas. 

1) Donde dice TABLET SAMSUNG debería decir "UNA DE NUESTRAS 4 TABLETS SAMSUNG" y ponelo en un tamaño y estética diferente de "En septiembre participar por" y  "Bienvenido a la" para que se destaque.

2) Si podés hacer 3 tablets más detrás de esa, como en perspectiva, para que se vea que hay varias en sorteo genial.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahi lea

**Comment by LeandroBraier** [comment]
Perfecto Brau!! Gracias!!

abrazo

**Comment by LeandroBraier** [comment]
Brau, gustó mucho el mailing de colocadores. Vamos acá también con la versión con menos imágenes. Avisame cuando la tengas nomás.

abrazo

**Comment by LeandroBraier** [comment]
Brau, esto podrá estar para el lunes?

**Comment by braulio-evangelisti** [comment]
Si señor, entre colocadores y lo demas esto me quedo medio relegado.

abrazo

**Comment by LeandroBraier** [comment]
Perfecto, gracias Brau!

**Comment by braulio-evangelisti** [comment]
Buen dia Lea, te paso un link

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-septiembre-b.html

**Comment by LeandroBraier** [comment]
Está muy bueno, Brau. Gracias!!
1. Quitá la parte de Guía de Corralones.
2. Se podrá hacer que esta imagen también esté en formato como lo demás, sin imagen?

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/img/como-participo.jpg

Yo para evitar lo más posible esquivar el spam.

**Comment by braulio-evangelisti** [comment]
1 ok, para mañana temprano esta
2 va a quedar con fuente standard y fondos planos

**Comment by LeandroBraier** [comment]
OK. Genial.

**Comment by braulio-evangelisti** [comment]
Fijate ahi Lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Casi perfecto! Solo sacale el tilde a capaz y estamos.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahi esta, lo transcribi derecho de la imagen y quedo.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!
