### ISSUE TITLE
Bugs y Correcciones Web ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#159]
Brau, necesito que retoques cosas de la home de la web principal de ParexKLaukol, así que lo coppio a @FAAREIA por las dudas.

. En el footer, alinear a la derecha ParexGroup y colocar los otros 4 logos a la izquierda, pero con sus respectivos logos, no como están ahora.

. El logo de Club de Colocadores está mal. Colocar el correcto, que están usando en la plataforma.

. Las imágenes de las novedades siguen sin ser levantadas por facebook:

Por ejemplo: http://www.parexklaukol.com.ar/novedades/parexgroup-te-invita-a-visitar-la-expo-buildgreen-argentina-2015.html

Revisar por favor y corregir.

abrazo

**Comment by braulio-evangelisti** [comment]
Puntos 1 y 2 listos Lea.

El 3° punto la imagen que muestra cuando compartís el link es el thumbnail que se ve cuando se listan las novedades porque viene en un campo individual y puedo obtener el nombre de esa imagen para imprimirlo en los tags. 

@mkreyness puedo obtener la imagen de cada novedad de alguna manera en el template de novedad para reemplazar  ?

Saludos

**Comment by mkreyness** [comment]
Lo que pasa es que las novedades tienen toda una seccion que viene directamente EN html, entonces esas imagenes (sobre todo las de las novedades mas viejas) son un caos, no surgen de la base de datos en un campo.
Hay si un campo de imagen asociado a la novedad que PODRIA o PODRIA NO estar referenciada desde el HTML.
Yo agregue hace muy poco en el CMS que cada novedad pueda tener un repositorio de imagenes propio, para ser utilzadas dentro de ese HTML en el que arman el contenido. Pero no tengo forma de saber cual es la principal. Ademas esto va a aplicar a las NUEVAS novedades que se carguen, pero no a las anteriores, alguien tendria que tomarse la molestia de resubir al repositorio esas imagenes (las que correspondan a cada novedad) y en todo caso podriamos marcar una com la "principal" y pasarte eso en una variable.
O sea, por ahora imposible que puedas obtener ese dato hasta que se emprolije todo.

**Comment by LeandroBraier** [comment]
Ok, entiendo! Igual ahora si prueban ese link facebook lo indexó, no sé cómo la verdad.

Gracias a los dos!

abrazo
