### ISSUE TITLE
Modificaciones finales en Bases y COndiciones Torneo de Potenciados. 14/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#160]
Brau, necesitaría para mañana tranqui que modifiquemos los detalles marcados en los documentos que te adjunté por mail. Vas a ver resaltado en AMARILLO lo que hay que SACAR y en VERDE lo que hay que AGREGAR.

La que corresponde a Dueños de Corralones es un ejemplo con 1 categoria pero tendrías que hacerlo en todas. CUalquier duda con eso me avisás.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahi Lea. Revisalo por las dudas que se me haya pasado algo.

Abrazo

**Comment by LeandroBraier** [comment]
Está impecable Brau. Gracias! Ya lo mandé al cliente, cualquier cosa te aviso. abrazo

**Comment by LeandroBraier** [comment]
Brau, me pasaron pequeñas y muy puntuales correcciones para las versiones de bases y condiciones de categorías de corralones A y D y para B y E.

Esto para A y D:

<img width="881" alt="captura de pantalla 2015-09-11 a la s 19 39 27" src="https://cloud.githubusercontent.com/assets/6719872/9827908/99228f80-58bd-11e5-8fac-e1ddba123f24.png">

Esto para B y E:

<img width="879" alt="captura de pantalla 2015-09-11 a la s 19 39 37" src="https://cloud.githubusercontent.com/assets/6719872/9827922/c04fabc4-58bd-11e5-99a4-014702d422a9.png">

Puede ser para el lunes tranqui.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo, checkeá nomas. Abrazo.

**Comment by LeandroBraier** [comment]
Gracias Brau!
