### ISSUE TITLE
Analytics Guia de Corralones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#161]
Fede, puede ser que la guía de corralones no haya registrado ninguna visita o no tiene el código de analytics incorporado?

No la encuentro en el analytics. Te fijás porfa?

@FAAREIA 

abrazo

**Comment by FAAREIA** [comment]
No tiene, ahora le pongo. Igualmente fijate en analytics si esta URL te figura y ahi te tiene que decir las visitas: http://www.parexklaukol.com.ar/guia-corralones/

**Comment by LeandroBraier** [comment]
Claro, ese fue el problema. Me pidieron un informe y yo fui reconfiado que iba a encontrar esa URL y no está. 

Ojo que Club de Colocadores no me apareció tampoco. Por fuera de la web principal Argentina, Paraguay y Uruguay me aparece Torneo de Potenciados y Comunidad de Vendedores nomás.

**Comment by braulio-evangelisti** [comment]
Listo Lea, ya esta importado el codigo en la guía.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo
