### ISSUE TITLE
Pequeño error de texto en la web. 23/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#162]
@braulio-evangelisti sin apuro, solo esto:

En la página de Lanko 453
http://www.parexklaukol.com.ar/lanko/lanko-453.html

Donde dice: "impermeablididad" debería decir "impermeabilidad"

abrazo

**Comment by braulio-evangelisti** [comment]
@mkreyness el texto de la descripción se modifica por gestor para que cambie en la db o esta el texto en el html?

**Comment by mkreyness** [comment]
Esta todo en el CMS, @LeandroBraier  fijate entrando en la parte de productos, filtras Lanko y enseguida lo vas a encontrar.

**Comment by LeandroBraier** [comment]
Resuelto! Gracias!

abrazo
