### ISSUE TITLE
Cambio de Password FTP Paty y Danica URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#163]
@mkreyness necesitaría que cambies la contraseña a estos 2 ftp de paty y danica. Es por cuestiones de negociación nomás.

ftp.paty.com.ar 
patycoma  
d89Uje1zV5

ftp.danica.com.ar  
danicase  
7876mdrxYD
ftp.danica.servidoronline.net       

Avisame porfa cuando esté hecho. Debería ser hoy sin falta.

abrazo

**Comment by mkreyness** [comment]
esos son los que le tengo que poner o que cambiar por otros ?

**Comment by mkreyness** [comment]
Ah, eso es para entrar.
Mira, la unica cuenta que me deja cambiar FTP en danica es una en la que el usuario se llama
leandro@danica.servidoronline.net

Las otras (danicase y danicase_logs) son fijas del sistema y no me deja tocarles nada. 
Supongo que se acceden con la misma contrasenia general que se entra.
Si queres trato de cambiar la contrasenia general ?

**Comment by mkreyness** [comment]
En paty ni siquiera. Las cuentas de FTP son solo las default. Solo se podria cambiar la contrasenia general.

**Comment by LeandroBraier** [comment]
Perfecto, si. Cambiemos las contraseñas generales entonces. Se puede?

A esas nuevas pasamelas por mail porfa, no por github.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-16 18:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Estaba buscando, no, a mi no me deja desde el CPanel hacer eso.
Me parece que hay que caer en pedirles a Duplika, y ahi queda todo muy en evidencia.

**Comment by LeandroBraier** [comment]
Pero no es un tema con Duplika eh. Es un tema con nuestro cliente.

Se lo pedís vos entonces? Deciles que es por una cuestión de seguridad.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-16 18:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ya se, pero si el cliente le pregunta a Duplika por que no puede entrar, va a saltar.
Esto hay que hacerlo para cada cuenta por separado y lo tiene que hacer el que figura como contacto oficial de la cuenta, que supongo que sos vos ? (Yo seguro que no, no me darian bola).

**Comment by LeandroBraier** [comment]
Ok, MK. Gracias!
