### ISSUE TITLE
Es posible este concurso por whatssapp?

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#164]
Te paso el slide de la presentación (aun no presentado)

![slide-atc-02](https://cloud.githubusercontent.com/assets/6719872/9962878/85897c7c-5dfe-11e5-9e02-b6ce8980ce41.jpg)

¿Cómo lo haríamos?

Tenés un teléfono asignado para eso que, automáticamente, cuando el usuario se reporta, le envía un texto que le dice como pasarnos los datos. Por ejemplo: "Obra/ Nombre Constructor/DOmicilio/m2" AL enviarnos esa info, el teléfono envia el texto a una base de datos que lo lee como CSV y completa la base de datos diciendo además de qué numero provino la info.

Lo ves posible?

**Comment by mkreyness** [comment]
No entiendo como haria "el telefono" para enviar eso a una base de datos, eso es lo que tendria que programar yo ? Ni idea como, el API de Whatsapp que yo habia conseguido fue dado de baja por problemas legales. 
Lo unico que se me ocurre es que alguien forwardee cada mensaje recibido a una casilla leida por un programa que lo daria de alta en la base, pero igual nadie te asegura el formato en que la gente escriba o si pone pepe/pepep/pepepe/ppepepepe. Lo unico que se podria guardar en la base de datos es fecha/hora (del forwardeo probablemente)/no se si en el forwardeo figura el numero de telefono (espero que si)/contenido A ANALIZAR.

**Comment by LeandroBraier** [comment]
Aja, el API de WhatsApp no es más abierto entonces?

Viste la posibilidad de Web WhatsApp? 
web.whatsapp.com

Nosotros pensabamos que una máquina chupe los datos del teléfono a través de eso. Confirmame como lo ves a eso.

Obvio que no podemos asegurarnos de que esos datos vengan sin errores pero eso lo corregirá de última el cliente si acepta la propuesta.

**Comment by mkreyness** [comment]
Creo que no existe algo llamado "el API de WhatsAPP". Pero capaz ahora exista, no se, tengo que investigarlo. Me fijo y te digo.

**Comment by mkreyness** [comment]
Confirmado, no hay API.
Lo que se puede acceder por web es muy complejo de automatizar porque es contenido dinamico, no se puede chupar en modo texto o algo y parsear: las cosas aparecen a medida que vas clickeando.
Me parece un trabajo horrorosamente complicado (tipo hacker) y de dificil exito.

**Comment by LeandroBraier** [comment]
OK, MK. Entiendo. Gracias entonces!!

abrazo
