### ISSUE TITLE
Reunión Técnica/ Skype

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#165]
@FAAREIA y MK, tenemos un par de pedidos puntuales a realizar en poco tiempo (2 semanas). 

Son maquetaciones web muy puntuales pero requieren cierta logística de parte de uds (lease: equipo de desarrollo y maquetación) que nos permita a nosotros (lease: diseñadores+creativos+yo) ahorrarles la mayor cantidad de laburo posible.

RESUMEN:
Estamos hablando de:

. 2 landings para maratón Parex: una con formulario de inscripción y una customizada por usuario (tiene que ver con el sistema que ya hablamos con MK y no creo que haya problema con maquetación en eso, es muy simple comparado con el sistema que arma MK con FFMPEG). La estética vendría ya provista en un psd de los diseñadores.

. 1 página para un evento de Parex que se vería offline en un evento a través de un sistema de 3 monitores conectados como multipantalla. Esta página la idea es que consista únicamente en varias páginas sucesivas que aparecen simplemente con un clic del usuario. Esa es toda la interactividad. En cada pantalla habría un video o flash que nosotros armamos con el equipo de edición y que quedaría almacenado como toda la página en el disco local de la máquina.

Lo ideal sería hacer una reunión para hablar estos dos temas lo antes posible.

Propongo este jueves a las 11 hs, que es el horario que les conviene siempre a uds. Si no pueden ese día y horario organicemos al menos un skype para ir ganando tiempo. 

Espero sus respuestas.

abrazo

**Comment by FAAREIA** [comment]
Voy a estar a esa hora.

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Vos podés? Nos encontramos en la produ el jueves a las 11 entonces? O mejor hacemos un skype?

Por mi es igual.

**Comment by mkreyness** [comment]
El dia que yo puedo es el miercoles, no el jueves.
Si quieren miercoles a las 11 no hay problema. Prefiero en vivo porque queda todo mas claro.
Ojo como cae todo esto encima de las cosas que ya tienen fechas comprometidas (Academia y no se que mas)

**Comment by LeandroBraier** [comment]
Eso lo vemos en la reunión pero es más pensar que hacer para uds.

Mañana yo no puedo. Tiene que ser el jueves presencial o miércoles a la
tardecita por skype.

2015-09-22 13:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Mi compu tiene algo arruinado en el circuito de input (y no es el microfono, es algo interno), ya nos paso la ultima vez que no me oian. Yo puedo escucharlos y escribirles, pero no hablarles.

La otra es que intentemos con el skype del iPhone, la verdad que nunca lo usé.

Miercoles despues de las 4 puede ser entonces ?

**Comment by LeandroBraier** [comment]
No es seguro. Yo tengo reunión en parex a las 12 hs y suelen ser largas. A
las 18 hs seguro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-09-22 14:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
perfecto, me referia a que antes de las 4 yo no podia.

**Comment by FAAREIA** [comment]
Miercoles 18hs OK

2015-09-22 15:50 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Marce una vez usé el skype como aplicación de celular y va perfecto, es lo
mismo que la pc

2015-09-22 16:10 GMT-03:00 Federico Arena arena.federico@gmail.com:

**Comment by LeandroBraier** [comment]
Si, nosotros lo usamos sin problema también. Quedamos miércoles 18 hs entonces!!

abrazo

**Comment by mkreyness** [comment]
Yo no los tengo en skype, fijense si ustedes me ven a mi como "mkreyness"

**Comment by LeandroBraier** [comment]
@mkreyness ahi te pasé la solicitud. Dame el OK asi te llamo y armo la call.a brazo
