### ISSUE TITLE
Bug Vendedores: Error 100 al compartir videos de trivias

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#166]
@mkreyness te dejo captura. Me decis qué puede ser?

<img width="555" alt="captura de pantalla 2015-09-23 a la s 18 05 12" src="https://cloud.githubusercontent.com/assets/6719872/10058696/3afadf8e-621d-11e5-8ac3-e838f6ba048a.png">

El usuario es Sebastian Agustin Garcilazo

abrazo

**Comment by mkreyness** [comment]
no veo cual es el error, y ademas aca dice "corro con jonas" y es de FUCA...

**Comment by LeandroBraier** [comment]
Perdon, te pasé cualquier entonces.

Es esta la imagen:

![error-100-al-compartir-videos-de-trivias-eliminar](https://cloud.githubusercontent.com/assets/6719872/10059953/4590e888-6224-11e5-8067-09b2b166dd16.jpg)

**Comment by mkreyness** [comment]
Mmmm, dice "picture is not properly formatted", capaz esa foto tenga algo que a facebook no le gusta.
Es el del tema 13, voy a ver, despues te digo.

**Comment by mkreyness** [comment]
Solucionado Lean.
Le agregue el http://www.parexklaukol.com.ar absoluto delante a la imagen que se comparte porque estaba puesto como relativo y eso para Facebook no debe servir. Lo raro es que no haya saltado antes, capaz cambiaron alguna cosa del lado de Facebook y antes asumian que era del mismo dominio (otro parametro que se pasa).

**Comment by LeandroBraier** [comment]
Gracias MK!! Guardemos el aprendizaje pa la próxima

abrazo
