### ISSUE TITLE
Bug en Trivia Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#167]
@mkreyness por favor rechequeás que estén funcionando bien las trivias?

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=16&usuario=leanbraier&clave=parex
1. No me aparece el ícono de video arriba del texto "Mirá el Video y suma puntos" (si podés agregale el tilde a "sumá".
2. Al hacer clic en cualquier de los íconos azules lleva a la trivia. Cómo era la lógica de eso? Por qué el icono de PDF no lleva al pdf? Y el ícono del video por qué es clickeable? Creo que lo hablamos alguna vez pero sigue sin poco funcional para mi.
3. Confirmame que sumen puntos el "Me gusta" y el "Compartir" de abajo, que no estoy seguro si hice bien la carga de eso.

abrazo

**Comment by mkreyness** [comment]
1) El programa es siempre el mismo, si no te aparece la leyenda es porque falto cargar algo.
En este caso seguramente no le pusiste puntaje al juego de la trivia. El texto de "suma" despues lo arreglo. Terminemos de revisar esto.
2)  La logica es la que pidieron. ANTES, hasta que no bajaras el PDF (que puede ser mas de uno, y estan arriba) no se HABILITABA a contestar la trivia por documento, pero empezaron a quejarse de que "estaba deshabilitada" y me dijiste que la habilite siempre, con lo cual perdio el sentido. La trivia es la misma para cualquiera de los iconos, porque dijeron que no iban a escribir 3 trivias distintas (el tema tiene por lo tanto una unica trivia).
Cada icono es un "juego", y cada "juego" puede tener o no un puntaje diferente.
3) El "Me gusta" y "compartir" tambien son "juegos", vinculados con el tema. tenes que cargarlos con su puntaje y el tipo que corresponde "LIKE" o "COMPARTIR". Fijate los primeros temas cargados que ahi lo hicimos juntos y tienen todo lo que tienen que tener.

**Comment by mkreyness** [comment]
Si fijate que hiciste los juegos "CUESTIONARIO", "PDF", "LIKE" y "COMPARTIR" (esta todo bien eso) pero te falta el juego "VIDEO", por eso no aparece.

**Comment by mkreyness** [comment]
ya le agregue el acento a "sumá".

**Comment by LeandroBraier** [comment]
Si, eso ya lo vi, por eso me di cuenta que en otras trivias anteriores evidentemente no lo cargué. Más allá de eso, ya cargué también el juego VIDEO que me faltaba.

Gracias!

abrazo

**Comment by mkreyness** [comment]
La logica de las tres trivias es realmente confusa, porque haces una y se te deshabilitan las tres, porque son la misma.

**Comment by LeandroBraier** [comment]
Es que nunca va a haber varias trivias. Cada ícono debería vincularse con su tema: Video dar play a Video. PDF un link al PDF. La Trivia que te lleve a la trivia. Debería ser así intuitivamente no?

**Comment by mkreyness** [comment]
Pero en los 3 casos para ganar los puntos igual tenes que hacer la trivia. Ni ver el video ni descargar el PDF dan los puntos.
Por eso era mejor la idea de habilitar solo el boton de trivia de lo que hubieras hecho (si diste play al video, cosa que no podemos controlar) y lo de los PDF que si estaba hecho. Y la "trivia sin nada" no deberia existir.
Igual con todo lo que hay para hacer,  yo no me pondria ahora a andar tocando esto....

**Comment by LeandroBraier** [comment]
Tal cual MK. Anoto para tiempos de paz jeje

Gracias!! abrazo
