### ISSUE TITLE
BUG en Carga de Novedades via CMS

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#168]
@mkreyness desapareció el botón de Generar HTML en los nuevos posteos de novedades que generamos. Fijate lo que ocurre con este por ejemplo, que creó el cliente siguiendo todos los pasos previstos que ya funcionaron en veces anteriores:

http://parexklaukol.com.ar/novedades/techos-verdes--nuevas-tecnologias-para-mejorar-el-habitat-o-ahorrar-energia.html

**Comment by mkreyness** [comment]
Arreglado, movi algo de lugar por error al estar haciendo las novedades de academia ("capacitaciones") y afecto a esto. Ya quedo bien

**Comment by LeandroBraier** [comment]
Gracias por la velocidad MK!!

abrazo
