### ISSUE TITLE
Landing Stand de ParexGroup en Evento AGBC. 29/9

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#169]
Fede, te paso el pedido de lo que hablamos el otro día por skype para el Stand con interacción tipo Minority Report.

Eze me pidió que fuera un poco más sitio web que lo que yo quería, asi que no van a ser botones transparentes sino botones más reales, con texto clickable. Te paso el primer video.

https://www.wetransfer.com/downloads/961495a0c84cd1644879a74e9aa508c120150928162426/45488269d6c0e1e881379431c3c9cfac20150928162426/14f3d0

MOCK UP DEL VIDEO: ![pantalla-1-stand-agbc](https://cloud.githubusercontent.com/assets/6719872/10149464/294c5604-6610-11e5-86c4-871076708ca2.png)

Como ves en el video y el mock up, ahora de las 3 pantallas hay 2 laterales con video y una en el centro de fondo blanco. Sobre esa del centro van a ir los textos que tenemos que meter via web. Te paso el png con esos textos para que lo insertes directamente ahí.

![landing-pantalla-1](https://cloud.githubusercontent.com/assets/6719872/10149910/f2528724-6612-11e5-8810-03b11fe6c245.png)

Además de lo que esta pantalla que aparece en el centro, sobre las dos pantallas laterales debe aparecer abajo un texto clickeable que diga:

"Hacé clic acá para conocer más sobre nuestros productos." y al lado de ese texto (dentro del mismo botón) una mano animada que muestra el click como lo tendría que hacer el usuario con la tecnologia LEAP (Minority Reporte)

Yo te estoy armando el gif animado pero te paso el video de referencia.

https://youtu.be/tH_UnxiHFjk?t=19

Entiendo que el botón mismo sería un gif animado para que la mano se pueda mover. 

En las siguientes pantallas habría un botón similar a ese en los laterales pero en lugar de decir eso diría:

"Hacé clic acá para volver al inicio."

ESTÉTICA:
Para los botones seguir la línea del PNG que les pasé arriba y del tríptico que envío aquí. Usar las tipografías y demás que venimos usando para ParexKlaukol principalmente en la web www.parexklaukol.com.ar

![klaukol_orsustentacat](https://cloud.githubusercontent.com/assets/6719872/10149737/ce2a2d12-6611-11e5-91dc-1f22389c0882.jpg)

DESCARGA DE VIDEO:
https://www.wetransfer.com/downloads/961495a0c84cd1644879a74e9aa508c120150928162426/45488269d6c0e1e881379431c3c9cfac20150928162426/14f3d0

Necesitaríamos tener armada esta landing mañana para poder ver como queda y pedirles las siguientes landings, que van a ser 5 más con la misma estructura y funcionalidad. La única diferencia es que en una va a haber un menú de 4 botones en el centro en lugar de haber solo texto. Esos botones llevarían a las demás pantallas.

Confirmame si está claro como para tener esta primera página mañana y seguir avanzando.

Todas las pantallas las tendríamos que tener listas para el miércoles, a más tardar jueves. Aunque tengamos que posponer 1 día o 2 la entrega de Club de Colocadores y Academia.

Confirmame porfa si llegamos.

abrazo

**Comment by FAAREIA** [comment]
Ahi va un preview:
http://parexklaukol.com.ar/stand/
El video pesa 21MB asi como lo ves. Tendrías que mandarmelo en más calidad o probar vos de exportarlo con H.264 y AAC para ir probando y cuando te convenza la calidad mandarmelo y lo subo de una.

No creo que lleguemos para el Miércoles con todas las pantallas, son varias cosas a preparar, probar y aprobar.

**Comment by LeandroBraier** [comment]
Entendido Fede! Para el jueves puede ser?

Te paso feedback: 
1. La imagen del medio me queda muy chica en relación con las pantallas de los costados. Te lo mando acá en 16:9 para que te ocupe toda la pantalla

![landing-pantalla-1](https://cloud.githubusercontent.com/assets/6719872/10176362/a02d905c-66ca-11e5-86a7-ea8a4863097a.png)
1. ¿Podés hacer que el botón sea más fino y que el rojo sea intermitente al menos? para que no quede tan fuerte y tan diferente a la estética de la otra imagen. Incluso si podés usar una tipografía más parecida mejor, o que combine mejor con esa.

Cuando me lo mandes mandame el html en un zip por favor asi lo veo offline. 

abrazo

**Comment by FAAREIA** [comment]
Ahi subí una actualización, traté de animar la mano con svg pero no quise dedicarle tanto tiempo asi que lo aborté.
http://parexklaukol.com.ar/stand/
http://parexklaukol.com.ar/stand/stand.zip
http://parexklaukol.com.ar/stand/estilos.zip (Reemplazá el CSS porque el zip del stand tiene uno desactualizado)

**Comment by FAAREIA** [comment]
Olvidé decirte Lea, para confirmate si llegamos para mañana necesitaría saber qué es lo que falta hacer. Sé que hay varias pantallas más pero desconozco el contenido

**Comment by LeandroBraier** [comment]
Fede, entendido lo que decís. Yo creo que llegamos bien para mañana a más tardar el viernes y estamos bien.

Te estoy pasando por WeTransfer los videos siguientes porque son pesados. Mañana bien temprano tenés las indicaciones de en qué consisten las siguientes pantallas.

abrazo

**Comment by LeandroBraier** [comment]
Buen día Fede!

No sé si recibiste los videos, te paso de nuevo el link acá:

https://www.wetransfer.com/downloads/0095550fa692e9968eb21a508f7a1bc620151001021018/20d543

Lo que necesito para las pantallas es lo siguiente:

PANTALLA 1: CIUDAD SUSTENTABLE

a. Sigue quedando chica la imagen y el botón sobrando espacio alrededor en blanco. Hacé que la imagen ocupe todo. No te olvides que no tiene que ser responsive. Es para uso offline en un evento a pantalla completa.

b. Agregale un logito de ParexGroup chiquito tipo marca de agua en las pantallas de izquierda y derecha.

c. Quitale el cartelito que dice: "Pantalla izquierda" y "Pantalla derecha"

d. Acá te paso el GIF del gesto que hay que hacer con la mano para clickear. Ponelo bien grande y visible, señalando el botón:

![gif-manos-en-stand](https://cloud.githubusercontent.com/assets/6719872/10237874/5a193bf0-688e-11e5-84f6-6b572e60f39a.gif)

PANTALLAS 2 a 7: PRODUCTOS

En todas ellas hay un botón blanco titilante tanto sobre la pantalla izquierda como la derecha que dice "Hacer clic para volver al inicio". Ese botón lleva a la pantalla 1.

PÁGINA 2: MENU
Al hacer clic en el botón azul de la pantalla anterior, aparece una pantalla que muestra los videos de producto en el siguiente orden:

Parex pantalla adhesivos
Parex pantalla fachadas
Parex pantalla morteros
Parex pantalla impermeabilizantes

En el centro, hay que poner esta imagen arriba. 

![landing-pantalla-2](https://cloud.githubusercontent.com/assets/6719872/10220439/ecdc6b54-681d-11e5-9cec-370105f99b96.png)

En el espacio blanco sobre la imagen, van 5 botones que llevan a cada una de las categorías de producto:

Adhesivos (botón que lleva a la página 3)
Fachadas (botón que lleva a la página 4)
Morteros (botón que lleva a la página 5)
Impermeabilizantes (botón que lleva a la página 6)
Lanko 228 (botón que lleva a la página 7)

PANTALLA 3: ADHESIVOS

Va el video "Parex pantalla adhesivos"

En el centro blanco va esta imagen:

![landing-pantalla-3](https://cloud.githubusercontent.com/assets/6719872/10221111/9af2f2a4-6822-11e5-977c-7bb0eed0c0df.png)

PANTALLA 4: FACHADAS

Va el video "Parex pantalla fachadas"

En el centro blanco va esta imagen:

![landing-pantalla-4](https://cloud.githubusercontent.com/assets/6719872/10221136/dac21266-6822-11e5-9291-902eec3dabfa.png)

PANTALLA 5: MORTEROS

Va el video "Parex pantalla morteros"

En el centro blanco va esta imagen:

![landing-pantalla-5](https://cloud.githubusercontent.com/assets/6719872/10221138/de464452-6822-11e5-80a2-843994449722.png)

PANTALLA 6: IMPERMEABILIZANTES

Va el video "Parex pantalla impermeabilizantes"

En el centro blanco va esta imagen:

![landing-pantalla-6](https://cloud.githubusercontent.com/assets/6719872/10221141/e193119e-6822-11e5-8143-b60074100f69.png)

PANTALLA 7: LANKO 228 TERRAZAS VERDES

Va el video: "Parex 3 led loop terrazas"

La imagen que va en el centro blanco es la siguiente: 

![landing-pantalla-7](https://cloud.githubusercontent.com/assets/6719872/10237688/6d7655dc-688b-11e5-8059-77fc6e41c8ef.png)

abrazo

**Comment by LeandroBraier** [comment]
Fede, estamos testeando la tecnología para navegar y nos surge lo siguiente: necesitamos que la superficie clickeable de cada botón sea lo más grande posible. Por más que el botón visible sea más chico, no importa eso, sino la superficie clickeable. El problema de la tecnología esta es que no es tan preciso el clickeo, entonces mientras más margen de error tenga mejor.

abrazo

**Comment by FAAREIA** [comment]
Ahi le agregandé bastante el área de click, fijense si va bien.
Los videos aún no pude descargarmelos, sería ideal si me lo partis en 2 asi se hace más fácil la descarga. Pensá que se me crashea el navegador y pierdo la descarga.

http://parexklaukol.com.ar/stand/stand.zip
Bajate ese.
Algunos detalles:
- Las imágenes estiradas se ven mal, y al estirarlas al 100% ancho el alto queda excedido a la altura máxima de la pantalla. Ahora las img estan al 90% del ancho de la pantalla central.
- Si tenes los videos ahi, metelos en la carpeta "videos" con formato .mp4 (H264 AAC) y nombralos como "pantalla-0#.mp4" El numeral reemplaza el número de pantalla.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Las imágenes las veo perfectas así.  No necesitamos más calidad. Y probé con el sistema los botones y funcionan perfectisimo.

Hice lo que me dijiste de los videos pero:

1) Los videos no aparecen.

<img width="1627" alt="captura de pantalla 2015-10-01 a las 16 24 03" src="https://cloud.githubusercontent.com/assets/6719872/10231072/2a23a908-6857-11e5-9673-918c86cd15c8.png">

2) En la pantalla 2 los botones no aparecen y el video de fondo es incorrecto.

![Uploading Captura de pantalla 2015-10-01 a las 16.24.11.png…]()

Además, feedback de diseño:

1) El lugar donde ubicaste el botón de Hacer clic para volver al inicio no me gusta mucho. Fijate si queda mejor por abajo o algun otro lado pero que no quede justo en el medio de la imagen linda que queremos mostrar. 

2) Además, a ese botón dale un área clickeable más grande todavía.

abrazo

**Comment by LeandroBraier** [comment]
Fede, ya te subí en el ticket la imagen de la pantalla 7 y el gif de la manito para la pantalla 1.

por favor mañana a la mañana dejemoslo resuelto a esto.

abrazo

**Comment by LeandroBraier** [comment]
Mañana antes del mediodía lo necesitamos. abrazo

**Comment by FAAREIA** [comment]
Ahi ya estoy por terminarlo, pero creo que nunca tuve el video de la pantalla 2, puede ser? En el zip de 2GB no está

**Comment by LeandroBraier** [comment]
Es cierto. No está completo. Pone el mismo de la pantalla 3 y yo lo
reemplazo. Abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/stand/stand-2.zip

Ahi van las modificaciones, avisame si falta algo!
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

Estoy en la produ asi que me va a demorar en bajar. Lo veo y te confirmo.
Abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, ahi lo pude ver. Está bastante bien, pero 2 cosas:

PANTALLA 2 AL 7
1. Ponelo dentro de la mitad inferior al botón de volver al inicio. No ahí arriba que no queda lindo.

PANTALLA 2
1. Los botones no están buenos. Dale más buena onda y que sean más visibles las opciones. No sirve que diga IMPERMEABILIZANTES abajo a la derecha y queda desnudo y liso el resto del botón. hacelo bien como un clásico botón, con texto en el medio.

PANTALLAS 3 A 7
1. Que en estas pantallas, en lugar de volver al inicio vuelva a la Pantalla 2 y que el botón "Hacé clic para volver al inicio" diga "Hacé clic para volver atrás"

Lo podés tener para hoy, aunque sea tarde?

abrazo

**Comment by FAAREIA** [comment]
Lo puedo tener hoy, lo que necesitaría resolver es el tema de los botones. ¿Qué texto pongo? Si me pasan diseño sería más rápido también ^_^

**Comment by LeandroBraier** [comment]
El texto es ese: Adhesivos / Fachadas / etc

El tema es que se vea más grande. Agrandá los botones si es necesario.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-02 16:07 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi te lo mandé al mail lea. Reemplazá los archivos que veas

**Comment by LeandroBraier** [comment]
Gracias Fede! Lo recibí.

Te hago una consulta. Estamos haciendo prueba y posiblemente movamos todos los botones clickeables a la pantalla del centro. Eso lo puedo hacer yo desde Dreamweaver no?

Aviso: quizá te pida una versión más el finde para que la tengas para el lunes a la mañana. Es solo un aviso, ojalá no sea necesaria y ande todo bien. Sería una versión mucho más sencilla en la que estaría la pantalla del centro.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no creo que lo puedas hacer, es maqueta y css. Moverlos al centro también implicaría achicar un poco las img asi el botón no excede el alto máximo de la pantalla, ojo con eso.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Lo de la imagen entonces si te lo puedo ajustar yo. Entonces
ahora te paso ese pedido, porque lo de mover los botones al centro es
definitivo.

Lo otro es plan B: una versión de 1 sola pantalla donde se vean las
pantallas con fondo blanco y los videos de productos pero en 1 sola
pantalla.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-02 18:30 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, te paso el pedido definitivo que necesitamos para la versión actual:

. los botones de "volver al inicio" y "volver atrás" que vayan todos en la pantalla del centro, que no quede nada clickeable en las pantallas izquierda y derecha

. quitar el gif de la mano

Solo eso necesito tener bien temprano a la mañana.

PLAN B

Como plan B para el lunes a la tarde necesitaríamos tener una versión en la que todo se vea en 1 sola pantalla tradicional. Es decir, cuando arranco veo solo la pantalla 1 del centro con el botón de "ver productos". 

Una vez que hago clic en ese botón voy a la pantalla 2, en la que veo el menú de productos también solo la pantalla del centro.

Cuando hago clic en cada categoría de producto, en lugar de ver la pantalla del centro de pantalla 3, veo la pantalla derecha de pantalla 3. De la 4, 5 y 6 también. 

De la 7 se tendría que ver la pantalla del centro.

Con eso estamos. Cualquier duda avisame

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA , no te olvides que esta es nuestra prioridad de hoy para la mañana. Lo necesitamos urgente.

Consulta: Puede ser que vos igual volviste a recomprimir los videos que me mandaste para la landing o utilizaste los mismos que yo te había pasado?

abrazo

**Comment by FAAREIA** [comment]
Ok, ahora acomodo eso del gif y los botones.
Los videos si los volví a comprimir. Si quieren usar los de alta calidad, exportenlos desde el After como H.264 (codec video) y AAC (codec audio) y tampoco me los manden porque va a pesar como 2GB, subanlos al FTP. Si los suben, avisenme y yo de última los renombro y muevo asi estan donde deben.

Con respecto al plan B, según entendí:
- Pantalla 1, 2 y 7 quedan igual pero sin video.
- Las demás pantallas quedan igual que la 2 pero con el video de la derecha correspondiente a cada una?

**Comment by LeandroBraier** [comment]
Gracias Fede!

Entendiste todo bien salvo el segundo punto del Plan B, o no me queda claro
si lo entendiste bien. Por las dudas lo aclaro.

ACLARACIÓN: En las pantallas 3, 4, 5 y 6 queda solo el video de la derecha
en pantalla. No olvides incluir sobre estos videos sí el botón de "Volver
atrás", sino el usuario va a quedar varado en esos videos.

AGREGADO: Se me acaba de ocurrir algo más para que quede mejor. Además de
la versión anterior, hacé una de las pantallas 3, 4, 5, 6 y 7 en las que
queden igual pero sin video (es decir, como hiciste con la 1 y 2) pero que
el video correspondiente a cada una aparezca al hacer clic sobre cualquier
parte de la pantalla.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-05 9:04 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Aún no me queda 100% claro:

En el plan B, el video derecho de las pantallas 3, 4, 5 y 6 es el video derecho de la pantalla 2?

Lo del agregado me parece algo raro, habría que indicarle al usuario que haciendo click puede ver algo más y también una vez habilitado el video, habilitar el botón para volver. ¿Lo hago igual?

**Comment by LeandroBraier** [comment]
Es un plan B solamente, pero sí, hacelo igual. No te gastes mucho más en
eso.

Lo del video derecho me parece que sigue sin quedar claro.

De pantallas 3, 4, 5 y 6 necesito que se conviertan también en 16:9. En
este plan B todo es 1 sola pantalla como una web normal, verdad? Eso está
claro.

Entonces, en pantallas 1, 2 y 7 veo el menu web que ya tenemos sin video.
En cambio, en pantallas 3, 4, 5 y 6 en lugar del menu web veo directamente
un video. Qué video? El que aparece en la pantalla derecha en este momento
o el que te parezca que quede mejor. La idea de este plan B es que al hacer
clic en el botón "Adhesivos" en la pantalla 2, el usuario vea el video de
adhesivos y pueda volver al menu de Pantalla 2. Ahí hacé clic en el botón
"Fachadas" y ve el video de Fachadas.

Fui claro ahora? Sino avisame y te llamo, no hay problema.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-05 9:28 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi te mandé el Plan A y Plan B. En el plan B son los mismo videos de antes pero muestro la parte que corresponde.
El plan C lo hago?

**Comment by LeandroBraier** [comment]
Gracias Fede! Si hagamos el c por las dudas tambien.  Abrazo

**Comment by LeandroBraier** [comment]
Fede, quedó excelente todo. Gracias!!!

abrazo grande
