### ISSUE TITLE
Backup general + CFT Online

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#17]
Fede, necesito rechequear. Yo sé que soy pesado pero es ultra importante.

Tenemos el backup completo de TODOS los contenidos de TODOS los sitios?

Los que yo tengo en mente son 8 pero decime si no se me escapa ninguno:

ParexKlaukol general

ParexKlaukol Paraguay

ParexKlaukol Uruguay

Klaukol

Parex

Lanko

Revear

CFTOnline

Necesito confirmar esto.

abrazo

**Comment by FAAREIA** [comment]
Al ser un CMS los datos estan en las bases de datos pero los archivos como fotos y videos si los tenemos. Todo lo otro no.

**Comment by FAAREIA** [comment]
CFT Online no lo sé, tendría que buscarlo

**Comment by LeandroBraier** [comment]
Porfa confirmame eso.

Respecto de la base de datos del CFT no hay forma de tomarla desde el front
como todo el resto de los sitios? Aunque lleve tiempo, pero no es posible?

Porque está confirmado que el proveedor anterior no nos va a mandar NADA
más. Hay un conflicto con el tipo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
La base de datos no se va a recuperar, no sabemos ni lo que hay ahi. Pueden haber sitios muertos, intranets, o que se yo que. Marce K seguro lo va a saber explicar mejor.
Lo que se puede refabricar son los datos que estan expuestos online, eso si no hay drama alguno.
Igual me gustaría que Marce confirme lo que digo.

**Comment by LeandroBraier** [comment]
Ok, lo que necesito es asegurarme de que todo lo que está expuesto online
lo tengamos. El resto le aviso al cliente que no lo podemos tomar. Ya me
confirmaron que todo lo que es Intranets lo tienen internamente a Klaukol.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-10 8:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya estoy intentando bajarme los sitios completos. Yo se que hay que tratar de tenerlos, pero estoy viendo que son muchos links y encima los sitios de Argentina, Uruguay y Paraguay tienen datos diferentes. ¿Porqué no se puede usar la data online para ir rehaciendolo y hay que bajarlos tal cual? Osea, lo que esta online va a quedar online hasta que nosotros lo suplantemos. Lo cual debería de ser cuando tengamos terminado los nuevos sistemas para todos los sitios. Porque si nosotros supongamos que logremos bajarnos TODO (dificil, algo siempre va a faltar), igual a ellos los dejamos sin CMS y no van a poder cargar ni 1 novedad o producto.

**Comment by FAAREIA** [comment]
Estoy viendo y siento que organizar la data, trasladarla a varios CMS, va a llevar bastante tiempo.

Parex-Group tiene 3 variables, y cada una tiene otras 3: Klaukol, Parex y Lanko
- Tienen productos, con filtros.
- Tienen novedades, con categorías y tags.
- Tiene calculadores y generadores de fachadas

CFT Online
Entré al sitio y parece que es todo meramente programación.

Revear
- Tiene productos con filtros
- Tiene otro mapa de distribuidores
- Tiene un calculador de consumo.
- Tiene novedades

Los calculadores y eso vamos a tener que rehacerlos también.

Con todo esto que estoy viendo, me pregunto ¿qué es lo que hay que demostrar el miércoles?
Demostrar que tenemos bajadas las páginas de cada sitio, pero estáticas, sin funcionar y algunas rotas porque le falta la programación, no suma.
Ahora, según se, el plan era "mejorarles la estetica un poco". Si bajamos los sitios, las relinkeamos, le ponemos CMS para que ande novedades y productos, le rehacemos los calculadores, etc. Es una locura de trabajo en comparación a mejorarle la estetica minimamente.

**Comment by FAAREIA** [comment]
Otra cosa, el club de colocadores es un blog. Si se van las bases de datos, también habría que rehacerlo, no se puede dejar como html estático

**Comment by LeandroBraier** [comment]
Buenas noches, Fede. Lo antes posible necesitaría saber status de este backup.

1) Porcentaje de los sitios que tenemos backupeados.

2) Qué en particular nos está faltando y si te puedo dar una mano para llegar a backupearlo todo a tiempo.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, con Braulio estamos generando las hojas de datos que marce va a usar para recrear los sitios. Estamos con esto primero ya que hacerlo nos va a dar un conocimiento profundo de los sitios.
Con respecto a los backup en si, hay algunas cosas para ajustar pero aún no nos metimos de lleno en eso. Igual si ahora le damos 8hs al día va a ser otra cosa.
Por ahora lo único que faltaría es mirar y backupear CFT online

**Comment by LeandroBraier** [comment]
Gracias Fede. Entiendo lo que decís. No te olvides que esta semana es
prácticamente la última que tenemos para hacer el backup. Necesitaríamos
tener el backup SI O SI. Así que denle las horas que sean necesarias, tengo
la autorización de Eze y además contá conmigo en lo que necesites.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-20 9:22 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Esto ya está listo Fede entonces? Si me confirmás cierro el ticket?
