### ISSUE TITLE
Newsletter Klaukol de Octubre. 30/9

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#170]
@FAAREIA esto se lo pido siempre a Brau pero lo necesito para mañana y él no va a estar disponible por motivos familiares.

En este Google Doc tenés todos los contenidos, incluidos los textos, links de las imágenes y de las notas:

https://docs.google.com/document/d/17-5xBgMyPUSZHyJSVVmLVV5gB-nyXw-xeqctJ2NElJw/edit

El news armalo directamente en una maqueta igual a esta solo que con los nuevos contenidos de texto e imagen:

http://parexklaukol.com.ar/_mailing/novedades-septiembre/novedades-septiembre.html

La parte de Capacitaciones no va esta vez y el footer queda tal cual. Confirmame porfa si lo podés tener mañana dentro de la mañana o para el mediodía al menos.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/novedades-octubre/novedades-octubre.html

**Comment by LeandroBraier** [comment]
Buenisimo Fede! Solo un detalle. 

¿Podés hacer que queden las dos fotos del mismo tamaño? Solo tendrías que recortar la segunda para que quede como la primera.

**Comment by FAAREIA** [comment]
Hecho ;)

**Comment by LeandroBraier** [comment]
Gracias Fede! Perfecto!

Lo mando a aprobar y te aviso.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA van dos cambios muy simples en el news. Pueden ser para mañana sin problemas.
1. Esta foto subirla un poco, para que el techo no sea lo principal 

![foto actual](https://cloud.githubusercontent.com/assets/6719872/10170310/ad7e9a96-66aa-11e5-969a-22152c2f2d32.jpg)

que quede más así: 

![foto a cambiar](https://cloud.githubusercontent.com/assets/6719872/10170319/aff4d31c-66aa-11e5-81b6-207b2e857b3a.jpg)
1. En la de la expo cambiar el logo de Leed por esta fotito:
   http://www.graphicsdb.com/data/media/781/edificio_verde.png

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA apenas tengas esto avisame porfa.

abrazo

**Comment by FAAREIA** [comment]
Dale F5 Lea, ya esta listo.

**Comment by LeandroBraier** [comment]
Perfecto Fede!! MIl gracias!
