### ISSUE TITLE
Bug CMS Productos en la web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#171]
MK, me pidieron ocultar el producto "Pastina Klaukol Piscinas". Lo "suspendí" en el CMS pero me sigue apareciendo. Te fijás qué pasó? 

Puede ser para la tarde.

**Comment by mkreyness** [comment]
Sigue apareciendo en el listado de productos o sigue andando la pagina si ya la tenias en el browser ?
Porque obviamente la pagina NO se borra por suspenderla, pero deberia dejar de aparecer en las busquedas/listados.

**Comment by LeandroBraier** [comment]
Ambas dos. La primera no me moleta, pero no debería aparecer en el buscador.

**Comment by mkreyness** [comment]
Listo, el buscador realmente no le daba bola al estado. Aca como no se regeneran paginas por categoria, ya que es mucho mas dinamico (por multiples filtros complicados que se pueden aplicar) en realidad todo eso de publicar/publicado/suspender/suspendido termina no significando nada (en Danica por ej "publicar" y "suspender" eran ordenes para un robot que corre en background que regenera las paginas de categorias, y cuando termina pone respectivamente en "publicado" y "suspendido".
En definitiva aca ahora si le da bola al estado, solo muestra los que digan "publicado".

**Comment by LeandroBraier** [comment]
Excelente MK! Muchas gracias!

**Comment by LeandroBraier** [comment]
@mkreyness me volvió a pasar lo mismo. Puse como suspendidos 3 productos y me siguen apareciendo en la lista del buscador. Te fijás porfa qué es?

**Comment by mkreyness** [comment]
que productos son ?

**Comment by LeandroBraier** [comment]
Los de Linea Hogar. Pero Marce: no lo corrijas a mano. Necesitamos que
funcione el CMS como debe. Si te tengo que pedir a vos cada vez que quiero
sacar un producto no conviene. Arreglalo definitivamente porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
No corregi nada a mano la otra vez, agregue una condicion en el programa que busca, por eso quiero ver que tienen de diferente estos que el programa no los reconoce, es muy raro.

**Comment by mkreyness** [comment]
si pongo "linea hogar" en el buscador de la pagina principal, no me trae nada, vos como los estas encontrando ?

**Comment by mkreyness** [comment]
Me parece que, al reves que la vez pasada, no es en el buscador donde lo ves, es en la pagina estatica. Fijate que cualquier filtro que pongas ya no aparecen (por ejemplo, si haces click en "linea hogar".
El tema es que no lo va a regenerar hasta que o haya nuevos productos o lo pongas en "suspender", creo. Ahi le force un "suspender", a ver si me lo pasa a "suspendido" una vez que lo haya regenerado.

**Comment by mkreyness** [comment]
listo, ya quedo arreglado definitivamente. Habia 2 programas, uno estatico y uno dinamico.
El ajuste del otro dia fue sobre el dinamico, porque me PARECIO que el estatico estaba bien (que las cosas de piscinas no aparecian) pero capaz mire mal y estaban en otra hoja.

**Comment by LeandroBraier** [comment]
Gracias Marce!

igual la verdad no sé por qué pero los sigo viendo en la lista:

<img width="1385" alt="captura de pantalla 2015-10-08 a las 23 11 03" src="https://cloud.githubusercontent.com/assets/6719872/10384332/e84f29e4-6e0f-11e5-8df0-30a0aff479e8.png">

Le hice F5, Cmd + R, de todo. Sigue ahi.

**Comment by mkreyness** [comment]
volvieron !#@(\* !@~ o yo estoy ciego cuando creo que desaparecen, o algun otro programa loco los esta volviendo  a generar. Sigo revisando entonces.

**Comment by mkreyness** [comment]
A ver fijate ahora si desaparecieron. Habia un par de lugares en el programa que no tenian el filtro de estado todavia. 
El kilombo general viene de que cambiamos la estructura del sitio a medio hacer (cuando se delegaron los dominios) y las mismas cosas estan repetidas en un par de lugares, lo peor es que todas estan en uso, unas para lo que se hace automatico y otras para lo que se hace "dinamico" desde las busquedas en la web.

**Comment by LeandroBraier** [comment]
Ahora si MK!! Gracias!!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-08 23:06 GMT-03:00 mkreyness notifications@github.com:
