### ISSUE TITLE
Landing Inscripción Maratón 42K. 01/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#172]
@FAAREIA, te paso adjunto por mail el psd para la landing de la maratón. Necesito que lo armes y lo subas a la url:

www.parexklaukol.com.ar/maraton

Tomando de base la estética, podés mejorar el diseño todo lo que quieras.

Quizá ya está de vuelta Braulio para mañana y se lo podés pasar a él. Recordá que esto es un formulario que guarda datos en una base. Para eso hay que consultar con @mkreyness que ya está enterado de esta acción.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/maraton/

Habría que definir los textos de los mensajes:
http://www.parexklaukol.com.ar/maraton/?contacto=1
http://www.parexklaukol.com.ar/maraton/?contacto=2

Faltaría que me pases la imagen de facebook, tamaño 1200x630
Marce, habría que registrar al usuario en una base de datos. @mkreyness

**Comment by LeandroBraier** [comment]
Gracias Fede!! Quedó buenisimo!!

Te paso el texto para el pop up. A qué responde que haya un segundo pop up?

¡FELICITACIONES POR SUSCRIBIRTE!
KLAUKOL POTENCIARÁ TU MARATÓN.
RECIBIRÁS TU VIDEO UN DÍA DESPUÉS DE LA CARRERA.
¡ÉXITOS!

La imagen de Facebook qué sería?

**Comment by FAAREIA** [comment]
Hola Lea, la imagen del Facebook es por si comparten o nombran la URL en facebook

**Comment by LeandroBraier** [comment]
Ah, genial. Es el tamaño de cualquier preview de facebook no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
El tamaño es: 1200x630, facebook después la achica o la redimensiona/corta dependiendo si lo muestra horizontal o cuadrada

**Comment by LeandroBraier** [comment]
Entendido Fede! Te lo paso hoy a la tarde a eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Aqui va Fede!!

![preview-para-link-en-facebook](https://cloud.githubusercontent.com/assets/6719872/10201137/d211f020-6780-11e5-836c-2820cece7552.png)

Decime si sirve así.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA Esto si lo podemos tener listo y funcional para mañana estamos perfecto.

Ya tenemos el FTP donde vamos a subir los videos. Pedile a @mkreyness que haga que la base de datos se suba ya directamente al servidor que vamos a usar para la Maratón de la forma que le sea más conveniente a él para armar los videos.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/maraton/
http://www.parexklaukol.com.ar/maraton/?contacto=1
http://www.parexklaukol.com.ar/maraton/?contacto=2

Para debugear: https://developers.facebook.com/tools/debug/og/object/

Marce me dijo que a las 4 recien lo puede ver.

**Comment by LeandroBraier** [comment]
Perfecto todo Fede. Una sola consulta. No podés subir la foto del header en
PNG? Porque se ve bastante pixelada en mi compu. Si ya está en PNG
olvidate, pero si no subila en PNG porfa.

El resto perfecto. Gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Perdón, la acabo de chequear en mi celu y veo que aún no es responsive no?

Porfa dejala responsive ya porque la mayoria va a acceder a través de
mobile.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-01 9:33 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Esta en png pero tenés razón igual, se ve medio difuso. Capas que es una foto estirada, habría que pedir que la fabriquen de 0 si es asi.

**Comment by LeandroBraier** [comment]
Ok, lo pide al equipo y te la mando.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-01 9:35 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Meto el responsivo antes de lo del stand?

**Comment by LeandroBraier** [comment]
Mejor meté primero el stand, así te llego a mandar la imagen esta que me
pediste en mejor calidad.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Para la base de datos primero tengo que instalar software en el servidor alquilado, viene todo muy peladito.
Ahora hago eso y voy creando una base, pero no se que datos son los que estan pidiendo, me fijo en alguno de los links de arriba y cuando este les aviso (va a haber que agregar el destino del formulario que vaya directo a un IP, porque no tenemos un dominio asociado a ese servidor)>

**Comment by mkreyness** [comment]
Muchachos, otra vez nombreyapellido todo junto ?
No lo quieren separar, o ya es al cuete ?

**Comment by LeandroBraier** [comment]
Si, separémoslo mejor. Si en el excel que tenemos de prueba está separado
separemoslo por favor Fede.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Fede cuando quieras ponele este URL de destino al form:
action="http://52.88.4.91/cgi-bin/altamaraton.pl"
method="POST"
y ya estaria todo listo (asumo que al campo de Apellido le vas a poner como nombre "apellido" y que el de Nombre queda con nombre "nombre", valga la redundancia)

**Comment by FAAREIA** [comment]
Ok, ya separé Nombre de Apellido, el atributo "name" es el título pero en minúscula.
Al form le puse el action y method especificado.
También ya esta responsiva la pantalla.

Si falta algo avisen, habría que testearlo y ver si registra en la base de datos todo.
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!!

Me faltaba pasarte la imagen del header en alta. 

![logo 1](https://cloud.githubusercontent.com/assets/6719872/10260212/f0359560-6948-11e5-9e5c-8ff7040d6ae6.png)

Si está para el lunes a la tarde reemplazada estamos bien.

Gracias a los dos por el esfuerzo!!

abrazo y buen finde!!

**Comment by LeandroBraier** [comment]
Buen dia Fede!

Avisame cuando tengas listo esto por favor.

abrazo

**Comment by FAAREIA** [comment]
Ahi la actualicé ;)

**Comment by LeandroBraier** [comment]
Perfecto Fede!!

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness ahi probé crear una inscripción.

![Uploading Captura de pantalla 2015-10-05 a las 11.31.52.png…]()

Como accedo a los participantes? Donde se guarda la base? abrazo

**Comment by LeandroBraier** [comment]
Fede, necesito un cambio simple en el diseño de la landing, a pedido del cliente.

1- Los logos de Ñandu y Klaukol abajo, en el footer.

2- Cambiar el slogan de "potenciado por Klaukol" por "y compartí tu emoción"

3- Cambiar el titular "Potenciá tu Maratón" por "Capturá el momento de tu llegada"

4- El pop que diga lo siguiente:

¡FELICITACIONES POR SUSCRIBIRTE!
CAPTURAREMOS TU LLEGADA Y RECIBIRÁS TU VIDEO DESPUÉS DE LA CARRERA.
¡ÉXITOS!

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Buenisimo Fede!!

Solo te pido que saques el logo de facebook. En su lugar poné la url:

facebook.com/ParexKlaukolArg

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
@mkreyness esto está funcionando no? La gente ya se está inscribiendo, necesito que me pasen acceso a esa base que se crea y que pongan analytics a esta página por favor urgente.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness un pedido más: necesito que el campo de "número de corredor" deje de ser obligatorio. Solo ese campo.

A partir del día 9/10 necesito tenerlo otra vez obligatorio.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA para mañana al mediodía, tranquilo, necesito una adaptación de esta landing de inscripción pero en una url aparte (podría ser /_expomaraton/) y que solo contenga bien bien grande desde la parte que están los 3 íconos de Registrate + Corré + Compartí hacia abajo.

Lo necesitamos para que la gente se inscriba desde el siguit que va a estar colocado en la Expo que inaugura la maratón. Demás está decir que esta página debería enviar el formulario a la misma base que la otra landing, no?

Extra: aprovecho a pedirte que pongas el Favicon de ParexGroup en estas dos landings también.

abrazo

**Comment by LeandroBraier** [comment]
Consulta Fede más: Podemos poner un captcha en el formulario de inscripción?

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Pudiste ver esto? Te paso en limpio todos los pedidos y consultas para mayor simpleza:

PARA HOY
1. Que el campo de "número de corredor" deje de ser obligatorio. Solo ese campo.
2. adaptación de esta landing de inscripción pero en una url aparte (podría ser /_expomaraton/) y que solo contenga bien bien grande desde la parte que están los 3 íconos de Registrate + Corré + Compartí hacia abajo.
3. Un captcha en el formulario de inscripción?

PARA JUEVES
1. el Favicon de ParexGroup en estas dos landings también.

Confirmame porfa.

**Comment by FAAREIA** [comment]
Ok a todo, lo del captcha dejame verlo porque nunca aplique uno a mano.
Habría que confirmar con @mkreyness si desde el siguit, que debe tener internet, aceptar ir a un script de formulario externo.

**Comment by mkreyness** [comment]
estan hablando de la tablet Android ? Si, supongo que debe permitirlo, pero como cualquier cosa, hay que probarlo.

**Comment by LeandroBraier** [comment]
Gracias chicos! La versión del siguit no hace falta que tenga captcha si no
se puede poner en esa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Claro, ahi el captcha es un "hatcha" para cortarle la mano al gracioso.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/maraton/
http://www.parexklaukol.com.ar/expomaraton/

Lo de expo maraton creo que ya esta bastante grande, si es la misma tablet que antes, imagino que va a entrar justo o bien.

Lo del captcha lo investigo

**Comment by LeandroBraier** [comment]
Gracias Fede!!! Perfecto!!

Espero lo del capcha entonces.

**Comment by LeandroBraier** [comment]
Cancelemos Captcha que es complicado, vamos con el mail de confirmación.

**Comment by LeandroBraier** [comment]
@FAAREIA un pedido simple: estuvimos probando la landing de "expomaraton" en el siguit y se ve bien. El problema es que
1. cuando aparece el pop up final queda trabado ahí. No vuelve automáticamente ni se puede tampoco cerrar el pop up con una X. 
2. No solo eso, sino que el pop que aparece muestra detrás la otra landing, la de /maraton/, no la de /expomaraton/

Podrás corregir eso hoy porfa? Lo que necesito es que el pop aparezca solo 5 segundos y luego vuelva a cargar la landing como estaba, la de /expomaraton/. Me avisás cuando lo tengas porfa?

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA por favor necesito tener esto resuelto URGENTE. A las 11 am la gente lo está empezando a usar y todavía no está resuelto este tema!

Es simple. 

1) Que el pop aparezca sobre la landing de /expomaraton/
2) Que permanezca 5 segundos y luego se cierre o se refresque sola la página.

abrazo
