### ISSUE TITLE
Solo chequeo Juegos HTML5

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#173]
Marce: consulta. Nos quedan 2 juegos de acá a fin de año para Parex y según esta nota:

http://blog.nextperience.net/36351/

Chrome ya dejó este mes de respaldar Flash. Por ende, tenemos que hacerlo en HTML5. LO que necesito que me digas es si vos podrías retocar detalles o manejar la programación de estos juegos que te paso a continuación. Fijate como están armados, parece que usan COnstruct 2, vos lo manejás?

Solo necesito tu confirmación para ofrecer alguno de ellos. Si alguno te parece que va a llevar mucho tiempo avisame también. abrazo

Construí el piso en el momento justo
http://codecanyon.net/item/block-it-html5-casual-game/13066857
http://codecanyon.net/item/block-it-html5-casual-game/full_screen_preview/13066857

Saltar de techo verde en techo verde
http://codecanyon.net/item/hero-adventure/13027856
http://dev-zoom.com/construct-game/hero-adventure/phone/

Laser Shot: Pulverizar escombros
http://codecanyon.net/item/laser-shot/13044856
http://odiusfly.com/games/lshot/

Palabras de 4 letras relacionadas con ParexGroup
http://codecanyon.net/item/four-letter-words-html5-word-game/13032720
http://codecanyon.net/item/four-letter-words-html5-word-game/full_screen_preview/13032720

**Comment by mkreyness** [comment]
No tengo idea de "Construct 2", es la primera vez que veo ese nombre. Hasta que no compres alguno no creo que se pueda ver el codigo para determinar cuan facil o dificli sea.
Pareceria que implica instalar algun toolkit que no se si anda en cualquier browser, mira que podes tambien estar dejando mucha gente afuera por tener browsers viejos.

**Comment by mkreyness** [comment]
Ahi me estoy instalando una version free del construct2. No se si con eso se podra editar algo comprado, ojo. Capaz implica comprar una version full.
La licencia "Personal" (not for business) sale 130 dolares. La "business" sale 430 dolares.

**Comment by LeandroBraier** [comment]
Genial MK. Pero debe haber forma de crackearlo no?

**Comment by mkreyness** [comment]
No creo, si cobran tan caro deben haberlo protegido bien.
Eso ademas llevaria tiempo que terminaria costando SEGURO mas que 130 dolares oficiales.

**Comment by LeandroBraier** [comment]
Ok, chequeá las restricciones del Construct 2 gratuito porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Las restricciones mas relevantes tienen que ver con la cantidad de "eventos", "layers", y "efectos" que permite. Si alguno de los juegos usa mas de 100 "eventos" o mas de 4 "layers" o mas de DOS "efectos", ya no funca.
No podemos saber a priori esas caracteristicas de los juegos, pero "2 efectos" suena a algo muy limitado.

**Comment by LeandroBraier** [comment]
Entiendo MK. Genial porque esas características de los juegos si las sabemos. Por ejemplo, el que queremos usar dice esto:

FEATURES:

Mouse or touch control
Work on all HTML5 browser and mobile devices
Included Construct 2 file
Ability to use C2 Free Version since it has less than 100 events
Included assets (images and music)

Nos restringimos a juegos que nos permitan usar la free version y listo.

Gracias!
