### ISSUE TITLE
Solo chequeo: carga de datos para Maraton 42K offline

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#174]
MK, podemos tener una versión offline de la landing para inscribirse a los videos personalizados de la maratón pero offline?

Me refiero a algo que guarde los datos que carga la gente pero sin tener conexión a internet.

Solo decime si lleva mucha programación o se puede hacer con algo simple que tome esos datos y los almacene en un CSV o algo.

**Comment by mkreyness** [comment]
Todo depende del equipo en que va a estar corriendo ese browser.
Que ALMACENE localmente es imposible, los browsers simplemente tienen prohibido acceder al filesystem del equipo en el que corren.
A lo sumo podrian quedar algo en cookies u objetos similares internos del browser, pero me parece sumamente fragil.
Lo mejor para tener algo offline es que en el mismo equipo pueda correr un SERVER (o sea que el browser se conecta a LOCALHOST) y ahi si en el server podemos guardar cualquier cosa que querramos.

**Comment by LeandroBraier** [comment]
Entendido! Vamos a alquilar un 3G entonces para la Expo. Gracias MK!!

abrazo

**Comment by mkreyness** [comment]
pero que equipamiento van a usar ? Una macbook ?

**Comment by LeandroBraier** [comment]
La raspa de siguió y la hp smartouch de la oficina.
