### ISSUE TITLE
Posible Kiosco para Video en el Stand de AGBC

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#175]
Como lo ves a este MK?

http://porteus-kiosk.org/download.html

Ya sabemos que la compu que vamos a usar es PC y se trata de la HP SmartTouch que tenemos en la oficina.

Decime si lo ves potable me lo bajo.

abrazo

**Comment by mkreyness** [comment]
Mira que esto es un sistema operativo completo, es para bootear la PC desde ahi, no se como te va a andar el LEAP con esto, si lleva algun driver en la PC.

**Comment by LeandroBraier** [comment]
Mmmm... tenés razón. Entonces mejor olvidarlo. Voy a ver si puedo hacer algo para lockear el chrome, al menos para que con el movimiento del mouse no se activen el menú inferior y superior de la mac. Total el leap solo va a poder mover el curso y hacer clic. Se podrá eso?

**Comment by mkreyness** [comment]
Si, fijate aca:

http://www.sitepoint.com/google-chrome-kiosk-mode/

**Comment by LeandroBraier** [comment]
Gracias MK!!! Excelente esto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Marce, estoy viendo que esta función solo funciona en PC y justo hoy decidimos usar Mac porque Leap no anda bien en Mac.

Crees que podríamos hacer esto?

https://support.google.com/chrome/a/answer/3316168

**Comment by mkreyness** [comment]
O sea no anda bien LEAP en PC ?
La verdad nunca hice un Chrome App, no se si le dejan a cualquier andar subiendo apps. Cuanto tiempo queda para resolver esto ?

**Comment by mkreyness** [comment]
Ya alguien lo hizo:

https://chrome.google.com/webstore/detail/kiosk/afhcomalholahplbjhnmahkoekoijban

**Comment by LeandroBraier** [comment]
Está buenísimo Marce, recién lo probé, pero solo permite urls online. Cómo
hago con la url offline que tenemos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
file:/// y despues el path a la pagina
Por ejemplo si en mi PC pongo esto:

file:///C:/

me lista el contenido del disco C:
No se como funcionara en Mac, pero debe ser similar.

**Comment by LeandroBraier** [comment]
Probé con eso pero en el Kiosk no me funcionó, dice que solo habilita
direcciones con http.

Igual al probarlo vi que igual despliega el menú de arriba, así que es lo
mismo que el modo de presentación para nosotros. Nosotros sol habilitamos
mouse, no teclado, asi que no hay posibilidad de que nadie toque nada y se
salga del navegador.

Si encontras alguna otra cosa avisame que sigo buscando yo pero por lo
pronto no estamos tan mal.

Gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-01 23:46 GMT-03:00 mkreyness notifications@github.com:
