### ISSUE TITLE
Landing Video Maraton y Mailing Maraton. 06/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#176]
Buen día @FAAREIA y @braulio-evangelisti !

Les paso un pedido simple para mañana a la tarde.

En la misma estética que hicieron la landing de inscripcion de la maratón en: www.parexklaukol.com.ar/maraton

Necesito que armen la landing customizada en la que cada inscripto va a recibir su video y el mailing que recibirían y llevaría a esa misma landing.

Les adjunto los PSD via mail y aquí les paso las refes en jpg

![mail](https://cloud.githubusercontent.com/assets/6719872/10279505/95a2875c-6b3c-11e5-892c-b43172f9d677.jpg)
![landing-maraton-video](https://cloud.githubusercontent.com/assets/6719872/10279506/97245bbe-6b3c-11e5-82d9-03551685f079.jpg)

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA acá también va las modificaciones que pedimos para la landing de inscripción.

1- Los logos de Ñandu y Klaukol abajo, en el footer.

2- Cambiar el slogan de "potenciado por Klaukol" por "y compartí tu emoción"

3- Cambiar la frase "Por eso para nosotros esta fue maratón fue TU maratón... y este es TU video." por "Ahora reviví el momento de llegada en TU video:"

abrazo

**Comment by braulio-evangelisti** [comment]
Lea ahi va el link del mailing

http://parexklaukol.com.ar/_mailing/maraton/maraton.html

Lo acomodé al ancho que veníamos trabajando con el resto de los news que es un standard, porque estaba en 400px, esto es por algo en especial?

Te aviso apenas suba el landing.

Abrazo

**Comment by LeandroBraier** [comment]
gracias Brau!! Donde dice Maratón 42K no podés ponerlo más como la refe que te pasé? Más grande la tipo.

**Comment by braulio-evangelisti** [comment]
Fiajte ahi lea

News
http://www.parexklaukol.com.ar/_mailing/maraton/maraton.html
Landing video
http://www.parexklaukol.com.ar/maraton/video.html

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!!

La landing está bien.

El mailing te corrijo el texto.

DONDE DICE:

"Hola (nombre del concursante)!

Felecitaciones por haber llegado a la meta! 
Ya esta listo tu video personalizado de la Maratón potenciado por Klaukol.

DEBE DECIR:
"Hola (nombre del concursante)!

Felicitaciones por haber llegado a la meta! 
Ya está listo tu video personalizado de la Maratón donde podés revivir el momento de tu llegada."

El compartí aquí tiene que mostrar un thumbnail de video que lleve a la landing de video. Debajo ponele los botones de like y compartir de facebook.

**Comment by braulio-evangelisti** [comment]
En "Ingresa aqui" irial el thumb?

**Comment by LeandroBraier** [comment]
Si, ahi.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Fijate ahora el news lea

**Comment by LeandroBraier** [comment]
Brau, el thumb va entero, igual que en está en la landing. Ocupa todo el espacio. No hace falta poner el ingresá aquí. En lugar de eso va el thumbnail con el signito de play dentro del video para que al hacer clic piensen que se va a reproducir el video y en realidad los lleva a la landing.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahora

**Comment by LeandroBraier** [comment]
Está bueno Brau pero sigue quedando chico. Si quitando los botones de Like y Share podés agrandar un poquito más el video hacelo. Y con eso estamos!

Solo faltaría la parte de customización para que @mkreyness pueda automatizar los envíos.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahora?

**Comment by LeandroBraier** [comment]
Perfecto Brau!! Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti disculpá la hora, me piden un cambio. Puede estar para mañana o pasado, no hay problema. Esto se enviaría recién el lunes. Lo que necesito es que en estas dos piezas:

News
http://www.parexklaukol.com.ar/_mailing/maraton/maraton.html
Landing video
http://www.parexklaukol.com.ar/maraton/video.html

El logo de Klaukol Potencia que Une aparezca arriba de Maratón Buenos Aires 42K, es decir, en el header arriba de todo. Es el único pedido del cliente. 

Porfa confirmame si lo podés hacer en ese plazo. 

Es simple y tenés 48 hs tranqui para hacerlo. Hoy solo necesito tu confirmación.

abrazo

**Comment by braulio-evangelisti** [comment]
Ya esta aplicado en los dos lugares Lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! abrazo

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Como va? Tengo un par de modificaciones muy muy sencillas para hacer en la landing y mailing lo antes posible. Esta es la prioridad de hoy, debería estar para antes del mediodía.

Cambios en mailing y landing:
1. Agregar en el header Logos de la Maratón y de Ñandu a la derecha de Klaukol, Potencia que une.

![maraton-42k-arnet-buenos-aires-2015-v02- 1](https://cloud.githubusercontent.com/assets/6719872/10453378/e86691cc-7181-11e5-9cca-0debf3a1297d.png)
![logo-nandu](https://cloud.githubusercontent.com/assets/6719872/10453379/e9ca2740-7181-11e5-9389-cdb9653da776.png)

Modificaciones en landing:
1. Modificá el texto, donde dice "reviví el momento de llegada en TU video:" debe decir "reviví el momento de TU llegada:"
2. Modificá el texto que dice "Compartí". Donde dice "Compartí" debe decir "Compartí el video en tus redes sociales"
3. Que cuando termine el video aparezcan los 3 botones de Facebook, Twitter y YouTube pero sobre el mismo embed del video. Se puede esto? Sino coordiná a @mkreyness que te ayude a hacerlo.
4. @mkreyness, hagamos un campo de mail que arriba diga lo siguiente: "Si alguien corrió en la Maratón, todavía está a tiempo de tener su video personalizado. Invitá a tus compañeros aquí ingresando su dirección de mail". Y que en el campo puedan poner direcciones de mail. Con esos armamos una base para enviar un nuevo mailing.

ATENCIÓN: @mkreyness hizo cambios en la landing el fin de semana, asi que usá las versiones finales ya modificadas por él.

En el caso del mailing:

http://www.parexklaukol.com.ar/_mailing/maraton/maraton.html

y en el caso de la landing del video:

http://www.parexklaukol.com.ar/maraton/video2.html

Confirmame recepción Brau, por favor.

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia. Recibido Lea. Apenas este te aviso.

**Comment by braulio-evangelisti** [comment]
@LeandroBraier Lea fijate ahi. Creo que mas o menos es lo que se pedía. Avisame si hay algún cambio. El texto del punto 4 lo tuve que acomodar un poco para que no quedaran tan desparejas las líneas y no esta "tal cual". Avisame si es posible y si lo pongo exactamente como se pidio.

@mkreyness hay un div class="share" que esta oculto sobre el iframe en /video2.html. 
Llamando algo como esto cuando termina la reproduccion tendria que aparecer: _$('.share').fadeIn(800);_

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau! Va feedack:

MAILING: Está bien salvo que el logo del medio está muy chiquito ponelo parejo.

LANDING: 

1- Colocá los logos así:

<img width="888" alt="captura de pantalla 2015-10-13 a las 11 09 31" src="https://cloud.githubusercontent.com/assets/6719872/10456680/fe56891c-7198-11e5-96e7-68be57f257b4.png">

2- Por qué no se ve el video? Esa landing estaba armada para que ya se vea. No habrás pisado el código que estaba ahí no?

Confirmame porfa abrazo

**Comment by braulio-evangelisti** [comment]
Dale ahora acomodo los logos.

El "video2.html" lo descargue al online antes de hacer las modificaciones y trabaje sobre ese.  Por lo que veo en el codigo hay que pasarle algun parametro por la URL para que cargue un video u otro segun usuario puede ser? Por lo que entiendo si entras a la url pelada **http://www.parexklaukol.com.ar/maraton/video2.html** no carga ningun video por defecto.

**Comment by LeandroBraier** [comment]
@mkreyness ayudalo a brau con esto porfa.

**Comment by braulio-evangelisti** [comment]
Fijate ahi los logos.

Probé asi y me cargo un video:

http://www.parexklaukol.com.ar/maraton/video2.html?numero=3

esta bien?

**Comment by LeandroBraier** [comment]
En la landing están bien. En el mailing no lo veo corregido aun.

**Comment by braulio-evangelisti** [comment]
Fijate ahora

**Comment by LeandroBraier** [comment]
Está bien. Achicá porfa un poco el logo de Ñandú, para que no quede tanta diferencia con el logo de la Maratón. Más parecido a las proporciones que tienen en la landing.

**Comment by LeandroBraier** [comment]
Perdón, un detalle de la landing.

Que la frase "Compartí el video en tus redes sociales" esté más grande, que llegue hasta la otra punta de los logos. Que no quede todo junto ahi:

<img width="852" alt="captura de pantalla 2015-10-13 a las 11 47 23" src="https://cloud.githubusercontent.com/assets/6719872/10457814/25f6dfa8-719e-11e5-9cb1-7b5826cc1fe3.png">

**Comment by braulio-evangelisti** [comment]
Fijate ahora

**Comment by LeandroBraier** [comment]
Brau: perfecto. Un cambio nomás ene l pie .

1- Dar vuelta el texto para que quede de esta manera:
"INVITÁ A TUS COMPAÑEROS INGRESANDO SU EMAIL. SI ALGUIEN CORRIÓ EN LA MARATÓN, TODAVÍA ESTÁ A TIEMPO DE TENER SU VIDEO."

2- El texto del botón que dice "SUBSCRIBIRME" debe decir "ENVIAR"

**Comment by braulio-evangelisti** [comment]
Listo

**Comment by mkreyness** [comment]
Al video2.html solo se debe llegar desde el mailing, porque completa el URL de un video en particular.
Si quieren tener un landing generico para el que cae ahi por casualidad, tendria que ser el video.html como lo tenian.

**Comment by LeandroBraier** [comment]
Perfecto @braulio-evangelisti ! 

@mkreyness ya está listo para enviar.

**Comment by LeandroBraier** [comment]
No entiendo bien, pero uds lo dejan cerrado Brau?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-13 12:27 GMT-03:00 mkreyness notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Como cerrado?

**Comment by LeandroBraier** [comment]
Resuelto quiero decir. Dejenlo funcionando.

**Comment by LeandroBraier** [comment]
@mkreyness urgente, antes de que hagas los envíos de mails llamame.

En los links de compartir en redes no están los links correctos. Simplemente lleva a las redes de parex, pero esos botones tienen que permitir compartir el video en redes sociales. Por favor llamame ANTES de empezar el envío.

abrazo

**Comment by mkreyness** [comment]
Antes de mandar nada, ademas de hacer pruebas, tengo que hacer estos varios cambios.

Para compartir en redes sociales no estarian faltando datos de la pagina de klaukol y todo eso ?

**Comment by LeandroBraier** [comment]
A eso me refiero. En realidad los botones de compartir en redes tienen que poder compartir el video, y los links actuales no están preparados para eso. Los podés setear @mkreyness ? @braulio-evangelisti ayudalo porfa así lo resolvemos más rápido.

**Comment by braulio-evangelisti** [comment]
Revisen ahora, le cambie los links de los perfiles por los links para compartir a video2.html

Lea dentro de youtube no hay como compartir un articulo, le cambie el icono y link a Google+

**Comment by LeandroBraier** [comment]
Excelente Brau!!

Porfa poné el icono de Facebook a la izquierda, primero de todo y el de Google+ ultimo a la derecha.

Y revisá el link de Facebook, creo que no está bien. Gracias!

**Comment by braulio-evangelisti** [comment]
Ahi los di vuelta a los iconos.

Aca me andan bien los links de las 3 redes, si tenes iniciadas sesiones con cualquiera de ellas te abre el sharer respectivo con el link.

**Comment by LeandroBraier** [comment]
A mi tambien. Pero el link de facebook no me lleva al link correcto me parece. No importa,. dejalo asi y lo pruebo con el primero mail de testeo que me envie @mkreyness 

ya estamos listo MK! avisame nomás!

abrazo

**Comment by mkreyness** [comment]
Ok vamos por partes porque hay como 300 cosas dando vueltas.
Yo lo que voy a mandarte ahora es el mail normal, y que te llevaria a la pagina para ver el video.
TODAVIA no toque nada en esa pagina en cuanto a lo de mandar a los amigos.

**Comment by LeandroBraier** [comment]
@mkreyness ya que estás tocando eso, una consulta. Podés agregar en el texto de la landing el nombre del usuario?

Lo que me pide Eze es que donde dice 

"Ahora reviví el momento de TU llegada:"

que diga:

"Ahora MARCELO KREYNESS reviví el momento de TU llegada:"

Si podés hacerlo ahora que estás corrigiendo lo del mandar a los amigos hacelo porfa. Si es mucho lio no hace falta. Es un plus.

abrazo

**Comment by mkreyness** [comment]
Si a mi tambien me parecia que habria que mostrarle que sabemos de quien se trata, pero ojo que tambien va a entrar "el amigo" a verlo y ahi no es real que sea "TU llegada", es "LA llegada" de fulanito.
Mas alla de eso, lo que si es problema es que no tengo el dato del nombre ahi localmente en klaukol, tengo que ir a la base de datos en Amazon para levantarlo, y puede hacer que sea un poco mas lento el arranque de todo.

**Comment by LeandroBraier** [comment]
No importa, si podés hacelo igual. La verdad que carga muy rápido y sin
problema por ahora.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-13 16:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
En realidad es mas que eso, tengo que hacer un programa que ahora no existe, porque es solo HTML, tendria que agregarle AJAX o directamente reemplazarlo todo por un cgi-bin.
Pero bueno, si no hay GRAN apuro por empezar a mandar los mails (porque como todo programa, hay que probarlo, etc.), lo hago.

**Comment by mkreyness** [comment]
Lean ahi te mande el mail, el link por supuesto sigue llevando a lo mismo de siempre, todavia no hice esos cambios. Confirmame que el mail esta bien asi un tema esta listo y puedo pasar al siguiente (no mando nada a la gente hasta que este todo terminado y verificado, por supuesto).

**Comment by LeandroBraier** [comment]
Perfecto MK! El mailing está perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-13 17:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ok, ya estoy con lo del ajax para mostrar el nombre

**Comment by mkreyness** [comment]
fijaste este ejemplo que use para probar, ya que tiene acentos:

http://www.parexklaukol.com.ar/maraton/video2.html?numero=2396
