### ISSUE TITLE
Ajustes Landing Stand AGBC

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#177]
@FAAREIA 
Te cuento que se ve todo bastante bien en el stand. Solo hay un detalle. Por un tema de las pantallas en el stand tuvimos que ajustar la página al 75% para que se vean enteras. 

Ahora: todo funciona bien salvo el botón de "Volver al inicio" o "Volver atrás", que queda siempre abajo.

PEDIDO 1: Necesito que corrijas los html para que ese botón quede incluido dentro de la maquetación de la pantalla central, no flotando en una capa superior en una posición XY determinada.

¿ De qué manera lo integrás? Mediante un botón que solo diga: "Volver atrás" y tenga una flecha hacia atrás. Ubicala donde quede mejor, pero mientras más grande y visible sea el botón mejor.

Corregí eso y mandame los HTML por mail nada más. Con eso nos arreglamos perfecto. Gracias!

PEDIDO 2: Reemplazar las imágenes de las pantallas 1, 2, 3, 4, 5 y 6 por las siguientes:

![landing-pantalla-1](https://cloud.githubusercontent.com/assets/6719872/10295988/133bb27a-6b9b-11e5-9dde-af0524a065b7.png)
![landing-pantalla-2](https://cloud.githubusercontent.com/assets/6719872/10295989/15e9b17a-6b9b-11e5-92d2-4cdfc8294d6d.png)
![landing-pantalla-3](https://cloud.githubusercontent.com/assets/6719872/10295993/17fa7c74-6b9b-11e5-818b-c3e9e123fa91.png)
![landing-pantalla-4](https://cloud.githubusercontent.com/assets/6719872/10295994/19c8bf98-6b9b-11e5-9374-7fbaf7ab901f.png)
![landing-pantalla-5](https://cloud.githubusercontent.com/assets/6719872/10295998/1cffb694-6b9b-11e5-9658-c669d834de01.png)
![landing-pantalla-6](https://cloud.githubusercontent.com/assets/6719872/10296001/1e86f0cc-6b9b-11e5-9357-f752c2013f98.png)
![landing-pantalla-7](https://cloud.githubusercontent.com/assets/6719872/10296003/1ff9e734-6b9b-11e5-8069-8a530f091c32.png)

abrazo

pd: Por favor confirmame si podés corregir esto y mandarmelo hoy a la noche o mañana bien temprano a la mañana, tipo 8 am.

**Comment by FAAREIA** [comment]
Hola Lea, sobre que versión lo estan necesitando?

**Comment by FAAREIA** [comment]
Ahi te mandé un mail con eso.
Abrazo

**Comment by LeandroBraier** [comment]
Fede, lo que me mandaste está perfecto. Solamente: falla la pantalla index. En esa, el botón queda por fuera de la pantalla. Fijate:

<img width="1476" alt="captura de pantalla 2015-10-06 a las 13 55 31" src="https://cloud.githubusercontent.com/assets/6719872/10315367/463a1794-6c30-11e5-8d70-ece5a0d4d628.png">

Que quede dentro de la misma línea de los videos.

En esta pantalla en particular, hacé que toda la pantalla sea clickeable para ver más productos. Las áreas clickeables de las demás páginas están perfectas. 

abrazo
