### ISSUE TITLE
Sumar el pie "Desarrollado por Benteveo" con link a todos los sitios de Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#18]
Fede, necesito que sumemos esto al pie de todos los sitios que desarrollamos para Klaukol, como hacemos siempre.

**Comment by LeandroBraier** [comment]
Fede, confirmame si ya está esto en todos los sitios. En Comunidad de Vendedores sigue sin aparecer.

**Comment by LeandroBraier** [comment]
Fede, con esto como estamos? Lo podremos tener listo para el lunes en todos los sitios de Klaukol?

**Comment by LeandroBraier** [comment]
@FAAREIA Esto lo necesito impactado HOY SI O SI CUANTO ANTES.

Ya volvió Ezequiel del viaje y tiene que ver el Desarrollado en todos lados. Por favor. Pedile a @braulio-evangelisti o como sea pero tiene que estar. Hace casi dos meses y medio que está este pedido.

abrazo

**Comment by FAAREIA** [comment]
Ok, ahora voy a empezar a implementarlo

**Comment by FAAREIA** [comment]
Hecho en PAREX AR, UY, PY + Comunidad de vendedores + Landing KIP + Guía de Corralones.
Si faltó algun sitio avisa!

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Solo nos queda Revear para cuando se pueda.

abrazo

**Comment by FAAREIA** [comment]
Oka, igual ahi la veo más dificil. Son como 250 HTML, hay que pensar la forma de insertarlo fácil y listo.

**Comment by LeandroBraier** [comment]
No te preocupes. Lo agregaríamos cuando hagamos el trabajo fino de Revear, más adelante, cuando ya no sean 250 html. No te preocupes.

abrazo

**Comment by FAAREIA** [comment]
Ok joya, lo dejamos en el tintero entonces.

Abrazo
