### ISSUE TITLE
Mailing y Landing para ingresar Número de Corredor ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#180]
1. @braulio-evangelisti necesito armar una adaptación del mailing de confirmación como el de recién para pedirle a la gente que se inscribió antes de la maratón que nos llene su número de corredor.

El texto diría: "Graciar por suscribirte para recibir tu video personalizado de la maratón. Ahora que tenés número de corredor, por favor ingresalo así podemos registrar tu llegada."

Botón: "Ingresar tu número de corredor"
1. @FAAREIA además del mailing necesito la landing muy muy simple donde el usuario pueda ingresar su número de corredor. Necesitaríamos tener esto para mañana a última hora, a más tardar para el viernes temprano.

Confirmenme los dos por favor si estamos ok.

abrazo

**Comment by braulio-evangelisti** [comment]
http://parexklaukol.com.ar/_mailing/maraton/nrocorredor.html

**Comment by LeandroBraier** [comment]
Gracias Brau! Está perfecto. @FAAREIA avisame porfa cuando tengamos la landing.

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/maraton-numero/
http://parexklaukol.com.ar/maraton-numero/?contacto=1
http://parexklaukol.com.ar/maraton-numero/?contacto=2

**Comment by FAAREIA** [comment]
@mkreyness copio a Marce para que registre el número en la base de datos.

**Comment by LeandroBraier** [comment]
Claro. Y no olviden que el link tendría que ser customizado para cada
usuario, sino no vamos a saber donde pegar el corredor.

En mi opinión para mayor tranquilidad tendría que aparecer arriba el nombre
del usuario en cuestión, para que el usuario sepa que está completando el
número de corredor de ellos.

**Comment by mkreyness** [comment]
@FAAREIA podras completarle como dice Lean un lugar para mostrar el nombre de la persona ?
Yo voy a usar esto de template (metele unas variables de nombre y apellido) en un programa que va a recibir como parametro un codigo unico y encriptado para cada inscripto.

**Comment by FAAREIA** [comment]
Hecho.

**Comment by mkreyness** [comment]
Ok entonces voy a ir preparando el mailing y esta tarde te mando alguna prueba Lean.

**Comment by LeandroBraier** [comment]
Excelente MK. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-09 14:18 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ahi te mande a gmail, fijate.

**Comment by LeandroBraier** [comment]
Gracias MK! Está muy bien. Solo te pido agrandar varios cuerpos la
tipografía del nombre del usuario en la landing. Queda muy chiquito y no
llega a llamar la atención.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Estoy totalmente de acuerdo, pero asi me lo entrego @FAAREIA , no se como mejorarlo sin capaz romper la diagramacion. Fede lo podras revisar ? Es en el mismo index.html tuyo que le cambie el texto fijo por variables.

**Comment by mkreyness** [comment]
Que hacemos, lo mando igual ?
Una cosa que no tengo muy claro: se lo mando a TODOS LOS CONFIRMADOS, no ? O a los que vienen de la expo NO ?

**Comment by LeandroBraier** [comment]
A los que vienen de la Expo no.

Al resto si, pero agrandá vos la fuente en html lo que puedas sin que se
rompa y listo. No nos compliquemos por ese tema.

Programalo para mañana nomás.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ok, lo agrando como me salga y a la mañana lo mando entonces.

Enviado desde mi iPhone

**Comment by FAAREIA** [comment]
Ahi lo actualicé para el que abra hoy el email.

**Comment by LeandroBraier** [comment]
Gracias Fede! Te estoy pasando en un toque cambios finales para club de
colocado res y demás.  Abrazo
