### ISSUE TITLE
Subida de Banner en GIF a la Home de la Web de ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#181]
@FAAREIA para mañana necesito que esté subido este banner en la web de ParexKlaukol:

![banner-animado-maraton-klaukol-version-web-parex-klaukol](https://cloud.githubusercontent.com/assets/6719872/10352965/30f1c93c-6d29-11e5-879b-34fb198eba03.gif)

Iría antes del footer, debajo de los 3 logos de las comunidades de vendedores, colocadores y corralones.

abrazo

**Comment by FAAREIA** [comment]
Hecho:
http://www.parexklaukol.com.ar/

**Comment by LeandroBraier** [comment]
Gracias Fede!
