### ISSUE TITLE
Juego Colocá el piso con Klaukol. 16/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#183]
Buen día Marce!

Te adjunto por mail el code del juego del que hablábamos el otro día. Ya lo compramos. Te lo paso para que tengas tiempo de abrirlo con el construct 2 y ver cómo aplicar el tema de que sume puntos. Recordá que como máximo pueden sumar 100 puntos. No sé cuantos niveles tiene porque son muy cortitos, así que definí vos cuanto vale cada nivel según eso, o decime cuantos son los niveles y yo te digo. Yo en mac no puedo abrir Construct 2 porque no es compatible asi que la semana que viene recien voy a poder aplicar la estética de la marca (prácticamente solo vamos a modificar el fondo del juego).

Para el viernes que viene necesitaría tener impactado esto de los números y lo del cambio de fondo.

abrazo

**Comment by mkreyness** [comment]
Ok, cuando tenga un hueco lo empiezo a mirar.

**Comment by LeandroBraier** [comment]
@mkreyness el juego está aprobado por el cliente. Solo piden si podemos meter el logo de Klaukol de alguna manera permanente durante todo el juego, no solo al principio. 

Por ejemplo, arriba de todo a la izquierda del rectángulo que esté el logo. Lo ves posible?

**Comment by mkreyness** [comment]
Supongo que si, mandame el logo que quieras que agregue y lo pongo.

**Comment by LeandroBraier** [comment]
Va el logo MK!

![logo-klaukol-blanco-limpio- converted](https://cloud.githubusercontent.com/assets/6719872/10650777/aa027152-7821-11e5-9196-e9a5bd02fa16.png)

Gracias!

**Comment by mkreyness** [comment]
fijate (por si acaso vacia cache porque este tipo de cosas HTML5 quedan cacheadas).
Tuve que achicar un poco el logo para que entre dentro del recuadro, espero no haberlo deformado.
Muy lindo no queda porque el numero esta muy alto.

**Comment by LeandroBraier** [comment]
No queda tan mal pero quedó demasiado grande. Ponelo más chiquitito, de 1/3 del tamaño actual, y centrado. Con esto estamos.

abrazo

**Comment by mkreyness** [comment]
no se que se rompio, pero ahora no carga. Despues sigo y te aviso.

**Comment by mkreyness** [comment]
Habia que volver a borrar los datos guardados en el browser. Es bastante choto eso, una vez que un juego esta publicado no deberiamos tocarlo mas, o a lo sumo republicarlo con otro nombre para que ignore el cache viejo.
Fijate como lo ves vos.

**Comment by LeandroBraier** [comment]
Gracias MK! Pruebo con el cliente a ver si lo aprueba.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-21 21:00 GMT-03:00 mkreyness notifications@github.com:
