### ISSUE TITLE
Desarrollado por Benteveo en todas las landings y mailings de la Maraton.

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#184]
@FAAREIA y @braulio-evangelisti necesitamos sumar esto. Podrá estar sumado hoy, aunque sea a última hora?

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Excelente!

abrazo
