### ISSUE TITLE
Bug Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#185]
@FAAREIA y @mkreyness ahora que ya estamos asignando los premios trimestrales, surge un caso que no teníamos. En el chart trimestral en lugar de 0 puntos se borra el espacio del puntaje. Fijate:

<img width="1066" alt="captura de pantalla 2015-10-09 a las 20 54 18" src="https://cloud.githubusercontent.com/assets/6719872/10407776/1644e68e-6ec6-11e5-9070-4c86fe236672.png">

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=antonioprevedelloycia&clave=127887

Corrijasmolo para el martes porfa.

abrazo

**Comment by mkreyness** [comment]
En realidad no le falta comprar sino que le sobra, queres que en ese caso le fuerce 0? 
Ahi se deberia normalizar, creo que lo que no tiene previsto es manejar un negativo 

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Dale forcemos a 0 porfa.

Abrazo

**Comment by mkreyness** [comment]
listo, estaba para el semestral pero no para el trimestral.
