### ISSUE TITLE
Nueva versión Mailing Maratón

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#186]
@braulio-evangelisti necesito que adaptes este mailing:

http://www.parexklaukol.com.ar/_mailing/maraton/maraton.html

A una segunda versión (maraton-amigos.html por ejemplo) para enviarle a los amigos que sean invitados a través de la landing.

Son solo dos modificaciones en esta versión, además del agregado de los dos logos en el header que te pedí en el otro ticket:

1) Lo que cambia texto:

Donde dice:
"Felicitaciones por haber llegado a la meta! 
Ya está listo tu video personalizado de la Maratón donde podés revivir el momento de tu llegada."

debe decir:
"¡Felicitaciones por haber llegado a la meta! 
Uno de tus amigos ya tiene su video personalizado de la Maratón donde puede revivir el momento de su llegada. Si corriste, ¡vos también estás a tiempo de tener el tuyo!"

2) Debajo del texto y arriba del thumbnail del video un botón que diga: "Inscribirme para tener el video personalizado de mi llegada" y que lleve a www.parexklaukol.com.ar/maraton/

3) El thumbnail del video debe llevar al video del amigo que se lo envió.

Confirmame recepción porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Recibido Lea. Apenas este te aviso.

**Comment by braulio-evangelisti** [comment]
Fijate ahi Lea

http://www.parexklaukol.com.ar/_mailing/maraton/maraton-amigos.html

El link del punto 3 creo que queda igual de mi parte, que vaya al video del referido que le envio el news supongo que queda en manos de mk. Cualquier cosa sino me avisas.

Abrazo

**Comment by LeandroBraier** [comment]
Brau, está OK pero fijate que el link que lleva a inscripción está mal. Se te pegaron dos links juntos.

@mkreyness apenas vuelvas implementá ese link entonces en este nuevo mailing.

abrazo

**Comment by braulio-evangelisti** [comment]
Disculpa, lo copie de aca directamente y me olvide de agregarle el http:// adelante. Ahi tendria que andar bien.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Brau!

Ya queda del lado de @mkreyness entonces.

abrazo

**Comment by mkreyness** [comment]
No entiendo DESDE DONDE se estaria mandando es "mail al amigo".
Porque ahi es donde tengo que intervenir para que el URL incluya el numero del corredor que lo esta mandando.

**Comment by braulio-evangelisti** [comment]
desde aca seria

http://www.parexklaukol.com.ar/maraton/video2.html

**Comment by mkreyness** [comment]
Lean no se puede hacer eso. No podemos poner una pagina en un servidor alquilado como es Duplika, donde tenemos un limite de 200 mails por hora, permitiendo que un hacker puede usarnos para hacer ataques a cuanto servidor tenga ganas de tirar abajo (y al primero que va a tirar abajo es a nosotros).
De hecho desde ESE MISMO servidor tengo que mandar los mails yo mismo a 4000 tipos, y lo tengo que dosificar no mas de 200 por hora, asi que ni loco publico eso en los propios mails que estoy mandando porque la propia viralizacion nos va a tirar abajo.

**Comment by mkreyness** [comment]
Directamente no van a salir los mails, Duplika los va a rebotar.

**Comment by mkreyness** [comment]
Y ademas el mail se lo estaria mandando klaukol a alguien que ni sabe de que le hablan, lo pueden denunciar como spam.
Lo mejor seria proveerle un link a la gente para que COPIE en su propio cliente de mail y lo mande a los amigos que quiera, pero sin salir fisicamente desde nuestro server.

**Comment by LeandroBraier** [comment]
Y bueno, MK. 

¿No podemos hacer que el botón "Enviar" habrá un mail (via "mailto:") que ya incluya un título un cuerpo de texto?

**Comment by mkreyness** [comment]
Si, esa es justamente mi propuesta. Tambien puedo ponerle el destinatario que haya escrito ahi.
Tenemos intencion de conservar una copia de esas direcciones ?
Lo que NO puedo hacer es meterle un HTML lindo a ese mail, es solo un texto simple.

**Comment by LeandroBraier** [comment]
Si, está ok. Lo confirmé con Eze acá.

Título del mail: ¿Todavía no tenés tu video personalizado de la Maratón 42K?

Cuerpo del mail: Yo ya tengo el mío ¡y está buenísimo! En tu video personalizado podés revivir el momento de tu llegada. Si corriste, todavía estás a tiempo de tener el tuyo.

Simplemente inscribite con tus datos y número de corredor en http://www.parexklaukol.com.ar/maraton/

Saludos

**Comment by mkreyness** [comment]
Pero no va un link para VER el video de quien esta mandando el mail ?

**Comment by LeandroBraier** [comment]
Si se puede si!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ya esta funcionando lo del mailto y anda muy bien.
Podes probar por ejemplo con el de Don Giuseppe (ojo F5 por si lo llegas a tener cacheado):

http://www.parexklaukol.com.ar/maraton/video2.html?numero=4399

Confirmame que te anda ok. Los videos todavia se estan regenerando pero ya esta por terminar y ahi si te mando una prueba final del mail y largamos.
A mi se me corto Fibertel, creo que hay un problema general por el corte de luz de ayer.
Por suerte tengo otra conexion (arnet) y un router que autoswitchea, pero 6/1Mb no es lo mismo que 50/6 Mb.

**Comment by LeandroBraier** [comment]
Quedó excelente MK! El mail funciona muy bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-14 10:37 GMT-03:00 mkreyness notifications@github.com:
