### ISSUE TITLE
Consulta sobre Billing Amazon

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#187]
@mkreyness estamos revisando la factura de Amazon y vemos que nos cobra 295 hs de procesamiento. Revisás si esto es así? Efectivamente usamos todas esas horas?

Pide MS si lo podés revisar y asegurarnos que está todo bien. Puede ser a la tarde.

abrazo

**Comment by mkreyness** [comment]
Es probable que sea el tiempo transcurrido desde que se inicio el servidor, no se si en este plan esta por hora fisica o por hora de uso de CPU. Igual les digo que el FFMPEG come CPU a lo pavo, pero eso recien empezo a usarse tipo anoche a las 9p (y ya esta terminando y en el medio hubo muchas horas en que no se usó).
Despues entro a Amazon y me fijo

**Comment by mkreyness** [comment]
Ahora ya son 301 horas. Lo que cobran es por hora, se este usando o no.
Sale 1.73 la hora. Arrancamos el 30 sep, pasaron 13 dias, a 24 hs cada dia... Y cada dia que pasen van a ser 24hs mas, o sea 41 dolares mas.
Pero no habian hecho estos calculos cuando dimensionaron/eligieron el servidor ?
El dia que lo apaguemos todo, ahi dejan de cobrar.

**Comment by LeandroBraier** [comment]
Gracias MK. Ahora le digo a Eze que estoy reunido.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-13 13:37 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Gracias!
