### ISSUE TITLE
Bug en Comunidad de Vendedores: puntos y tickets

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#188]
@mkreyness cuando termines con lo de la maratón revisá este caso a ver qué puede estar pasando y si no nos pasará con otros usuarios también.

Usuario: Fabián Lopez
Puntos en Octubre: 315
Tickets: 2

No debería tener 3 tickets? 

Nos escribió reclamando.

**Comment by LeandroBraier** [comment]
buen día @mkreyness ! Apenas puedas revisá este caso a ver qué puede estar pasando en la comunidad con los puntos.

abrazo

**Comment by mkreyness** [comment]
Lo que tiene de raro es que le consumio parcial 10 puntos de un juego en que gano 30, entonces le quedaron como perdidos esos 20 y ahi es que no llega a la ficha.
Se lo arreglo a mano y le doy la ficha que le falta, despues estudio bien por que quedo ese agujero, porque despues le completo con puntos de actividades posteriores.

**Comment by mkreyness** [comment]
Listo, ya tiene 3 fichas.

**Comment by LeandroBraier** [comment]
Gracias MK!!! Avisame cuando te pongas a investigar qué pasó, para evitar
que pase con otros usuarios.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
a la tarde lo estudio, ahora estoy saliendo.

**Comment by LeandroBraier** [comment]
Dale, no hay apuro hoy con eso. abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness se acerca fin de mes, no te olvides de dejar esto resuelto porfa.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness el usuario que reclamó es este:

FabianLopez

**Comment by LeandroBraier** [comment]
El mismo que ya arreglaste antes.

**Comment by mkreyness** [comment]
Ahi le arregle.
El tema son los puchos que no los esta tomando, cuando canjea algo parcial parece que siempre empieza en los puntos de la siguiente vez, en vez de aprovechar el saldo parcial pendiente.
Teoricamente no deberia pasar, pero pasa. Ya sabiendo esto lo voy a arreglar esta noche.

**Comment by LeandroBraier** [comment]
Mil gracias MK!!

Cualquier cosa avisame.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-29 19:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día @mkreyness 
Porfa avisame cuando esté esto.

abrazo

**Comment by mkreyness** [comment]
Ya esta. 
Lo que encontre es que al momento de tener justo 100 puntos libres, el sistema esperaba a que hubiera alguno mas para acreditarle (o sea, 100 => nada, 105=> 1 ficha + 5).
Encontre solo 2 casos mas, y tienen saldo de 100 exacto (Nicolás Walter Costas y Erica Urquiza) lo cual refuerza mi teoria.
Ahora les agrego 1 ficha a c/u y se acabó.

**Comment by LeandroBraier** [comment]
Excelente MK! Lo descubriste finalmente jeje

Muchas gracias

abrazo

**Comment by LeandroBraier** [comment]
buenas tardes @mkreyness !

Parece que la teoría no contemplaba todo. Fabián Lopez sigue con los mismos problemas. Ahora tiene 715 puntos y 6 tickets nada más. Por favor fijate cuál es el problema de fondo así lo resolvemos.

abrazo

**Comment by mkreyness** [comment]
Es cierto, pero no es por el arreglo, el arreglo estuvo bien.
Lo que pasa es que del problema previo a este tipo le quedaron "canjeados" 50 puntos de mas (en un juego que gano 50, le "saque" 100 al darle una ficha a mano.
Entonces ahora el sistema le estaba siempre "cobrando" esos 50.
Ya normalice la situacion, y le di la ficha.

**Comment by LeandroBraier** [comment]
Gracias MK! Me alegro que sea sólo eso.

Abrazo
