### ISSUE TITLE
Modificación en Sección Productos Klaukol- Web ParexKlaukol ESPERANDO CLIENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#189]
@FAAREIA , te paso las modificaciones de las que ya habíamos hablado hace algunos meses.

Necesito que apliques estos cambios en la sección de productos de Klaukol. Una vez hecho quizá nos pidan para las otras dos marcas.

1) PÁGINA 1 GENERAL La visualización inicial de los productos de Klaukol debe ser por tipo de producto. Los tipos de producto son Adhesivos y Pastinas. Linea Hogar hay que eliminarlo, ya oculté esos productos en el CMS.

Aquí podés ver como queda esa primera página:

<img width="987" alt="captura de pantalla 2015-10-13 a las 21 54 43" src="https://cloud.githubusercontent.com/assets/6719872/10472143/8fbeee4e-71f3-11e5-96f6-25eb3acf37a6.png">

2) PÁGINA 2- CADA TIPO DE PRODUCTOS Al entrar en cada tipo, se tiene que ver como este ejemplo de Weber:

<img width="976" alt="captura de pantalla 2015-10-13 a las 21 55 41" src="https://cloud.githubusercontent.com/assets/6719872/10472253/c1715ca0-71f4-11e5-8544-2ccbd838d947.png">

El contenido de cada sección es este:

![despliegue-de-productos](https://cloud.githubusercontent.com/assets/6719872/10472385/3d749d20-71f6-11e5-9c23-5b5d0457ce5b.png)

La clasificación de los productos es la siguiente:

Adhesivo Klaukol Impermeable Potenciado para la colocación de cerámicos
Adhesivo Klaukol Porcellanato Fluido para la colocación de porcellanatos
Adhesivo Klaukol Grandes Piezas Porcellanato para la colocación de porcellanatos
Adhesivo Klaukol Flex Fluido para colocaciones específicas
Adhesivo Klaukol Blanco Pro para colocaciones específicas
Adhesivo Klaukol Refractario para colocaciones específicas
Adhesivo Klaukol Rápido para colocaciones específicas
Adhesivo Klaukol Grandes Piezas para colocaciones específicas
Adhesivo en pasta Klaukol Pla-K
Adhesivo en pasta Klaukol Ecostick

Pastina Klaukol Piezas Normales Fluidas
Pastina Klaukol Renovación Antihongos
Pastina Klaukol Alta Performance Fluida
Pastina Klaukol Junta Ancha
Pastina Klaukol Epoxi

Decime porfa para cuando lo podrías tener.

abrazo

**Comment by LeandroBraier** [comment]
Aprovecho a consultar algo, @FAAREIA y @mkreyness : podemos hacer que los productos se desplieguen en el orden que plantea el campo de "número de orden en el calculador?

**Comment by LeandroBraier** [comment]
@FAAREIA recibiste esto?

Ya cambié los nombres de los productos a pedido del cliente. Ahora necesito que se enlisten en el orden  del número de orden en el calculador. Eso lo podés hacer vos o lo ve MK?

Porfa respondeme lo antes posible. Mañana ya debería verse así.

abrazo

**Comment by mkreyness** [comment]
No hay nada que especifique el orden que aparecen, pero no hay ningun problema en agregarle ese dato y que le pongas via CMS el orden en que tienen que aparecer.

**Comment by LeandroBraier** [comment]
Perfecto. Si podés tomar el orden de esa casilla que te digo genial. Sino
agregame la casilla aparte y lo repito ahi.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-14 19:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
El calculador es una aplicacion en flash que tiene todo hardcoded, no hay un dato con el orden en el CMS.
Agrego un campo nuevo.

**Comment by mkreyness** [comment]
Sabes que el campo ya estaba ?
Lo agregue a la interface. El unico que lo esta usando es Paraguay, se ve que ahi habian pedido primero un cambio de ordenamiento.
Muchos tienen puesto 9999, no estoy seguro por que, pero modificalos a gusto, en definitiva las categorias y los buscadores de productos y las paginas completas todas se ordenan por ese campo (dentro del sitio y la marca, obviamente)

**Comment by LeandroBraier** [comment]
Gracias MK!

Ahi lo corrijo y te aviso si funciona.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-14 21:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Funcionó MK! Me los respeta en el primero listado, pero cuando selecciono a
la izquierda como tipo de producto "Adhesivos" me los desordena. Lo mismo
si selecciono "Pastinas". Se puede acomodar eso?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-14 21:57 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
Debe ser que hay algun programa que no usa el ordenamiento. Termino con lo de la Maraton y lo veo.

**Comment by mkreyness** [comment]
a ver probalo ahora de nuevo.

**Comment by LeandroBraier** [comment]
Perfecto ahora MK! Gracias!!

Fede, espero tu feedback del resto de los cambios.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi vi todo, el tiempo estimado para diseño + maquetación + responsivo es de 30hs.
@mkreyness habría que ir preparando un template de producto exclusivo de klaukol para cuando se necesite maquetarlo.

**Comment by LeandroBraier** [comment]
Excelente. Para cuando lo podríamos tener listo? martes que viene 20/10?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-15 9:40 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Yo diría para el viernes que viene, seguro aparecen cosas en el medio y se termina aplazando. Pensá que hoy ya esta liquidado con el tema de colocadores.
El diseño si podría estar para el martes que viene.

**Comment by LeandroBraier** [comment]
Perfecto Fede. Diseño el martes y maquetación el viernes no problem.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-15 10:08 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Algunos detalles:
- Las categorías son filtros
- Inicialmente no hay filtros seleccionados, por lo que no se ve ningun producto.
- Al seleccionar un filtro, aparecen los productos correspondientes. Aparecen y desaparecen usando un plugin, vean el ejemplo: http://isotope.metafizzy.co/
- Las fotos de las cajas de los productos estan mirando hacia la izquierda, hay que generar fotos que miren hacia la derecha, sino parece un sitio de medio oriente donde se lee de derecha a izquierda.
- A las fotos de las cajas, al ser verticales, le agregué una foto de fondo. Otra opción podría ser centrar la caja pero los tamaños de imagen que hay son muy chicos y si lo agrando se rompe feo.
- Habría que conseguir las fotos actuales del slideshow en grande.

Espero que guste, cualquier cosa decime
Abrazo

![parex-klaukol-filtros](https://cloud.githubusercontent.com/assets/6184969/10612208/288ec860-7726-11e5-8df2-cf1dd57d21b5.png)
![parex-klaukol-productos](https://cloud.githubusercontent.com/assets/6184969/10612209/288f7b70-7726-11e5-86bc-7764e5385468.png)

**Comment by LeandroBraier** [comment]
Me gusta Fede, pero necesitamos poner las fotos finales para que se vea bien como se va a ver. Decime los tamaños de las piezas e imágenes que necesitás para cada cosa así las creamos desde diseño.

abrazo

pd: Las fotos del slideshow no las tenés más grandes en el backup que nos dieron del sitio web viejo? Yo las busco en el mio por las dudas.

**Comment by FAAREIA** [comment]
Hola Lea, las fotos en el backup no creo que esten en grande. Las necesitamos en 1920px de ancho.
Por otra lado, habría que definir bien una imagen de cada filtro y sería ideal que nos pasen el 3D en grande de cada packing de los productos.
Las imágenes de los filtros capas que las podemos sacar de la producción de fotos que hicieron, la cual no tengo la versión completa, solo unas 3 o 4 fotos.

**Comment by FAAREIA** [comment]
Queres que vaya maquetando a pesar de no tener la aprobación del cliente?

**Comment by LeandroBraier** [comment]
Dale, vayamos maquetando en versión previa, no en producción.

Yo después te paso las fotos.

**Comment by LeandroBraier** [comment]
Fede, estoy viendo el tema de las fotos. Mañana te las voy a pasar porque es un trabajo detallado pasarte fotos de cada tipo de producto. De todas formas, estoy viendo que:

1) Las imágenes del slideshow no las tengo en grande. Por qué no te sirven como están?

2) No tiene sentido vincular una foto a cada producto si lo que queremos mostrar es el pack, pero sí tengo todos los packs en alta. Eso te lo estoy mandando por wetransfer. Decime si te falta alguno.

abrazo

**Comment by LeandroBraier** [comment]
Ahí se mandó todo Fede.

Aquí van todos los productos de Klaukol en alta:

https://www.wetransfer.com/downloads/96191bef98103799a032fde9eee3a8a620151021234948/162523

Acá van las imágenes para las 4 categorías de productos:

https://www.wetransfer.com/downloads/06d7bc7c15f834fdb7d6118f9173126120151021235728/c993be

Confirmame si recibiste todo bien.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi van las pantallas finalizadas. El pack de Klaukol Porcellanato Fluido no esta y varios más tampoco, necesitamos cada pack en un archivo diferente y mirando hacia la derecha. Hay un PSD que reune toda la familia pero es una imagen sola, no hay capas.
1. Las imágenes del slideshow si las agrando se rompen, estaría bueno tenerlas en alta. No es vital y solo en monitores "grandes" van a verse algo o muy pixeladas, depende el monitor.

![parex-klaukol-filtros](https://cloud.githubusercontent.com/assets/6184969/10665116/339afef2-789f-11e5-8f9c-42fb2271696e.png)
![parex-klaukol-productos](https://cloud.githubusercontent.com/assets/6184969/10665117/33ba0266-789f-11e5-8402-39aa1d68de65.png)

**Comment by LeandroBraier** [comment]
Buenisimo Fede! Lo mando a aprobar por el cliente. Mientras tanto
arranquemos a maquetar.

Más allá de eso, fijate que el texto "PRODUCTOS KLAUKOL. Nuestros productos
te garantizan calidad y seguridad." no se lee bien sobre la foto. FIjate
como podés hacer para que se destaque un poco más, que no se pierda.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-22 9:29 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
![parex-klaukol-filtros](https://cloud.githubusercontent.com/assets/6184969/10667366/6ecd26e0-78ad-11e5-8d4e-01c8cfc143b4.png)
![parex-klaukol-productos](https://cloud.githubusercontent.com/assets/6184969/10667367/6eeecaca-78ad-11e5-9337-42f03dd062ce.png)

**Comment by LeandroBraier** [comment]
Gracias Fede! Lo mando a aprobar así.

Igual vayamos maquetando.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA lo vimos hoy. Les gustó, más allá de que pidieron los siguientes cambios:

a. Agrandar las macrocategorías Adhesivos y pastinas, el texto no se lee.

b. Cambiar la foto de Cerámicos por esta:

![shutterstock_59117842](https://cloud.githubusercontent.com/assets/6719872/10807759/02d51960-7dc2-11e5-9ab5-1ced2b0b4f36.jpg)

c. Cambiar la foto grande de Productos Klaukol general por una de las siguientes, para que no se empaste el titular.

![depositphotos_24117391-happy-family-looking-at-the-camera-with-a-laptop](https://cloud.githubusercontent.com/assets/6719872/10807764/1259799e-7dc2-11e5-8687-f5ac379865a8.jpg)

![depositphotos_2839750-happy-family](https://cloud.githubusercontent.com/assets/6719872/10807766/16374b90-7dc2-11e5-8e34-8efdee571d20.jpg)

d. Más adelante vamos a agregar anexos tipo “También te va a servir utilizar…” para productos que se utilizan junto con otros. La gente Parex nos va a enviar esto, pero hay que tener en cuenta que para esto cada categoría debería poder tener sus productos anexos. Por ejemplo,

Impermeable Impermeable + Pastina Fluida
Flex Fluido + Pastina Junta Ancha

abrazo

**Comment by FAAREIA** [comment]
@braulio-evangelisti

**Comment by braulio-evangelisti** [comment]
Gracias Fede, estoy con estos cambios

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA @braulio-evangelisti a qué hora podemos tener estos cambios?

**Comment by braulio-evangelisti** [comment]
15hs puede ser?

**Comment by LeandroBraier** [comment]
Perfecto!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Lea ahi esta lo de la imagen grande y los demas cambios, me falta pasar los 4 botones de cada categoria a texto en vez de solo imagen, en un rato cuando este te vuelvo a avisar.

**Comment by LeandroBraier** [comment]
brau, adonde lo impactaste a esto?

**Comment by braulio-evangelisti** [comment]
Esta aca: http://parexklaukol.com.ar/prod-iso/ ya pase los 4 botones a texto

**Comment by LeandroBraier** [comment]
Queda bien Brau. 
1. Subila un poco más todavía a la foto si podés, para que haya más blanco detrás del texto y se lea mejor.
2. Cambiala por la versión comprada. Acá te la paso:

![depositphotos_2839750_original](https://cloud.githubusercontent.com/assets/6719872/10891218/5e040c6c-817b-11e5-8ade-707f9581eb35.jpg)
1. Donde dice "Para la colocación de ESPECÍFICAS" tiene que decir "Para colocaciones ESPECÍFICAS"

abrazo

**Comment by LeandroBraier** [comment]
Probá con otras dos fotos más de paso y mandame mock up de cómo quedarían estas otras dos también:

http://sp.depositphotos.com/42673917/stock-photo-boy-with-sister-playing-on.html?qview=42673917

http://sp.depositphotos.com/33879659/stock-photo-family-with-three-children-smiling.html?qview=33879659

abrazo

**Comment by braulio-evangelisti** [comment]
![captura1](https://cloud.githubusercontent.com/assets/11272253/10892611/2e878ef2-8183-11e5-8169-cfc5cccfbf1f.jpg)
![captura2](https://cloud.githubusercontent.com/assets/11272253/10892612/2e8aaae2-8183-11e5-8a6d-bd7abc7433f1.jpg)

La original ya esta implementada en la maqueta

**Comment by LeandroBraier** [comment]
Brau:

1) De las dos nuevas, hacé la primera, subilos un poco más para que el texto quede bien sobre el clarito de los cerámico y reemplazá la foto por la que te paso acá ya comprada:

![depositphotos_42673917_original](https://cloud.githubusercontent.com/assets/6719872/10893088/b2541866-8185-11e5-8d6d-ccfbe3f8d42a.jpg)

2) En http://parexklaukol.com.ar/prod-iso/ pusiste mal el texto: "Para colocaciones ESPECÍFICAS".

Con esas dos cosas pasame y lo mando a aprobar.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate de actualizar ahora lea. 
Abrazo

**Comment by LeandroBraier** [comment]
Si, pero sigue diciendo "Para colocaciónes ESPECIFICAS" cuando debería decir "Para colocaciones ESPECÍFICAS". Hay un tilde de más en la O de "colocaciones"

Corregí eso por favor y pasame el otro mock up. Con eso estamos.

abrazo

**Comment by braulio-evangelisti** [comment]
Cual otro? Con otra foto?

**Comment by LeandroBraier** [comment]
SI, el del punto 1 que te pasé antes,cuando te pedí lo siguiente:

Brau:

1) De las dos nuevas, hacé la primera, subilos un poco más para que el texto quede bien sobre el clarito de los cerámico y reemplazá la foto por la que te paso acá ya comprada:

depositphotos_42673917_original

[...]

Con esas dos cosas pasame y lo mando a aprobar.

abrazo

**Comment by braulio-evangelisti** [comment]
Lo del tilde ahi lo acomodé. La foto esa de los dos nenes ya esta aplicada cuando me pasaste la original

http://parexklaukol.com.ar/prod-iso/

**Comment by LeandroBraier** [comment]
Es que no entendiste. Necesito mostrar las 2 fotos!!! La de antes, la de
los 4 en el sillón y esta de los dos nenes.

O me pasás 2 links o 2 capturas de pantalla, pero necesito mostrar las dos.

Fijate si podés retocarla para no cortarle la cabeza a los nenes pero que
el texto quede sobre blanco. Trabajala un poco, no la dejes tal como está.
Intentá que se lea bien el texto sobre una parte de la foto que sea bien
límpida y blanca.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Ahora si, pense que lo querias ver vos nomas por eso lo habia preparado en imagenes

http://parexklaukol.com.ar/prod-iso/index.html
http://parexklaukol.com.ar/prod-iso/index2.html

Fijate la foto de los chicos si era algo asi lo que pensabas

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Index está perfecto.

Index2 mejora. El reencuadre está perfecto, dejalo así, pero lo demás no es
exactamente lo que necesitamos. Por un lado el retoque de color que hiciste
hace que parezca que los chicos tienen los labios pintados, volver atrás
con eso, dejalo como estaba manteniendo el nuevo encuadre. Además el blur
borra justo lo importante, que es que se vea que son cerámicos alrededor.
Podés dejar el blur en los márgenes si querés o quitarlo directamente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Fijate ahora el index2 Lea. 
Abrazo.

**Comment by LeandroBraier** [comment]
Gracias Brau! Lo mando a aprobar al cliente.

Igual mientras tanto necesito que modifiques "Colocación de PASTINAS" por "Línea de PASTINAS"

Eso solo. Fede en los mock ups lo ponía así, no sé qué pasó en el medio.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahí esta corregido en ambos index, fue descuido mio estaban bien los psd pero hice el primer botón y duplique el código para los demás y arrastré el mismo texto.

**Comment by LeandroBraier** [comment]
No problem, entendido. Gracias Brau!

Sigamos avanzando igual en la maquetación de esta sección en back. Más allá
de la foto la estructura está aprobada.

Si la aprueban hoy sería ideal ya pasarla a producción.

abrazo

2015-11-03 8:58 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by FAAREIA** [comment]
@mkreyness

**Comment by LeandroBraier** [comment]
@braulio-evangelisti mañana, cuando puedas, probá cambiar la foto de arriba por esta:

http://www.sdandbinternational.com/wp-content/uploads/2012/02/kitchen.jpg

Creo que va a quedar muy bien y está preaprobada por el cliente. Lo demás en principio pareciera estar bien.

abrazo

**Comment by braulio-evangelisti** [comment]
buen dia Lea.

Esa foto tiene 960px de ancho, (ocupa el ancho de los 4 botones de adhesivos y pastinas aprox en resoluciones promedio), la tuve que estirar un poco para que ocupe todo el encabezado en monitores grandes tambien, te pregunto por las dudas: ¿despues pasarian la imagen en alta?

http://parexklaukol.com.ar/prod-iso/index3.html

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Lamentablemente no, es la única que tenemos. Sino fijate una similar a esa. No quieren que haya personas, lo importante es que la palabra PRODUCTOS KLAUKOL aplique 100% sobre cerámicos blancos.

Podés usar el buscador de Google Images por Imagen o sino en Deposit con el acceso que les dimos. Como prefieras

abrazo

**Comment by braulio-evangelisti** [comment]
Actualizá ahi el index3, no se ve tanta habitacion como en la que pasaste pero si la foto no tiene mucho piso el texto se va arriba de los elementos de la foto.

**Comment by LeandroBraier** [comment]
Quedó buenísimo Brau! Gracias!

Dejame que chequee con el cliente ahora.

abrazo

**Comment by LeandroBraier** [comment]
Por ahora esto lo cancelamos hasta próximo aviso. abrazo grande
