### ISSUE TITLE
Delegación Paso a Paso Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#19]
Fede y MK, les explico cómo va a ser el proceso de delegación de Klaukol (complejo, como todo Klaukol).

Paso 1) Vamos a delegar el dominio parexklaukol.com a nuestro hosting.

¿Cómo, si no tenemos todos los sitios listos? Subiendo solo los sitios que sí tenemos listos y redireccionando a los demás a la misma url pero en el dominio .com.ar

Sin embargo, al entrar a ParexKlaukol.com, lo que va a aparecer antes del redireccionamiento es un mensaje tipo pop up que va a presentar la nueva campaña (como el que aparece ahora en la web de ParexKlaukol de una Pastina). En ese mensaje va a estar el link a parexklaukol.com/ImpermeablePotenciado, que es el Micrositio de KIP. Si el usuario no hace clic y, en cambio, cierra ese pop up, es redireccionado a la vieja web.

Paso 2) Una vez en este satus vamos subiendo los demás sitios creados por nosotros cuando estén aprobados:

. Guía de Corralones

. Comunidad de Vendedores

. Club de Colocadores

Paso 3) Los últimos días de abril (preferentemente el viernes que viene) cuando tenemos listos TODOS los sitios nuevos en versión 1.0, delegamos también los dominios .com.ar al mismo hosting Onyx nuestro y san se acabó.

Para los casos de sitios web que aún no tengamos listos (por ejemplo, el CFT Online) iría un cartel de "En remodelación" y un link al canal de YouTube de dicho sitio.

Lo que necesito de uds en este punto es que me digan cómo ven este proceso, si lo ven posible en función de:

1) Todo lo técnico.

2) En llegar con los tiempos.

abrazo

**Comment by mkreyness** [comment]
```
en cuanto a lo del popup y que al cerrarlo vaya al viejo sitio no
hay ningun problema.
Cuando se haga el paso 3 obviamente hay que sacarle esos
redireccionamientos porque si no va a entrar en loop.

El 17/04/2015 a las 20:58,
  LeandroBraier escribió:


  Fede y MK, les explico cómo va a ser el proceso de delegación
    de Klaukol (complejo, como todo Klaukol).
  Paso 1) Vamos a delegar el dominio parexklaukol.com a nuestro
    hosting.
  ¿Cómo, si no tenemos todos los sitios listos? Subiendo solo los
    sitios que sí tenemos listos y redireccionando a los demás a la
    misma url pero en el dominio .com.ar
  Sin embargo, al entrar a ParexKlaukol.com, lo que va a aparecer
    antes del redireccionamiento es un mensaje tipo pop up que va a
    presentar la nueva campaña (como el que aparece ahora en la web
    de ParexKlaukol de una Pastina). En ese mensaje va a estar el
    link a parexklaukol.com/ImpermeablePotenciado, que es el
    Micrositio de KIP. Si el usuario no hace clic y, en cambio,
    cierra ese pop up, es redireccionado a la vieja web.
  Paso 2) Una vez en este satus vamos subiendo los demás sitios
    creados por nosotros cuando estén aprobados:
  . Guía de Corralones
  . Comunidad de Vendedores
  . Club de Colocadores
  Paso 3) Los últimos días de abril (preferentemente el viernes
    que viene) cuando tenemos listos TODOS los sitios nuevos en
    versión 1.0, delegamos también los dominios .com.ar al mismo
    hosting Onyx nuestro y san se acabó.
  Para los casos de sitios web que aún no tengamos listos (por
    ejemplo, el CFT Online) iría un cartel de "En remodelación" y un
    link al canal de YouTube de dicho sitio.
  Lo que necesito de uds en este punto es que me digan cómo ven
    este proceso, si lo ven posible en función de:
  1) Todo lo técnico.
  2) En llegar con los tiempos.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Genial MK!

Gracias. Me dejás más tranquilo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-17 21:01 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Chicos, preparemonos para delegar el dominio ParexKlaukol.com a nuestro hosting. 

Solo consistiría en lo siguiente:

parexklaukol.com-----> muestra un pop up con un link y luego redirige a parexklaukol.com.ar
parexklaukol.com/ImpermeablePotenciado ----->  Allí subiríamos el sitio http://72.52.188.248/_ultima-tecnologia/

Solo preparense para cuando podamos hacerlo.

abrazo

**Comment by mkreyness** [comment]
Esta hecho el popup ? Porque ahi es donde tengo que intervenir para que redirija al cerrarse.

**Comment by LeandroBraier** [comment]
Todavía no. Mañana te lo paso. Entonces es solo eso?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
En este tema si, tengo que agregar un par de pavadas sobre ese popup y nada mas.

**Comment by LeandroBraier** [comment]
Marce, va el pop up. Avancemos a preparar todo para la delegación. 

![pop-up-klaukol-4](https://cloud.githubusercontent.com/assets/6719872/7284404/b0c8d5b4-e913-11e4-897d-7b0bebfe2565.png)

abrazo

**Comment by mkreyness** [comment]
pero eso no esta maquetado, es solo un png.

**Comment by LeandroBraier** [comment]
No necesitamos más que eso. Si hace clic en el png lo redirige al
Micrositio. Si hace clic en la X de cerrar el pop up, es redirigido a la
web actual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día Marce! Como vamos con este tema del pop up? Necesito hacer la delegación hoy.

**Comment by mkreyness** [comment]
Te dije ayer cuando me mandaste el png.
No puedo hacer nada hasta que maqueten el popup, no puedo agregarle 
codigo a una imagen, tiene que estar dentro de un html con los botones 
separados para poder clickear, etc.

**Comment by LeandroBraier** [comment]
Perdón, se lo paso a Fede entonces. 

Fede, por favor necesito maquetar este pop up en una web a la cual podamos delegar el dominio ParexKlaukol (fijate en el primer thread está bien explicado).

abrazo

**Comment by FAAREIA** [comment]
http://72.52.188.248/Banner.zip

Ahi debería estar, avisen!

**Comment by LeandroBraier** [comment]
Gracias Fede!!! Marce: fijate si con esa maquetación estamos. Necesitaría resolver esto urgente.

abrazo

**Comment by mkreyness** [comment]
Entonces repasemos:
parexklaukol.com va a apuntar a una pagina que no se bien todavia cual es.
Cualquier cosa que la gente pida

parexklaukol.com/algo

les va a mostrar algo de fondo y ENCIMA se va a mostrar esto como un 
popup ?

Y cuando lo cierra sigue camino hacia

parexklaukol.com.ar/algo

pero si hace click en algo que no sea cerrar va a ultima_tecnologia ?

**Comment by LeandroBraier** [comment]
Exacto.

Esa página que todavía no sabés cuál es habría que crearla.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 16:21 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Bueno entonces es indispensable ir creando esa pagina tambien, porque 
esa es la que va a recibir el URL y tiene que hacer la apertura del 
popup, con un parametro.
Yo puedo ir previendo eso de la redireccion pero si o si pasa primero 
por la pagina por ahora inexistente.

**Comment by LeandroBraier** [comment]
Entonces que esa página sea esta:

http://72.52.188.248/_backup/parexklaukol/

Pero obviamente con el pop up cambiado.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 16:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Esa que dice "Gleepa" abajo ? :)
No hay una ya limpiada ?

**Comment by FAAREIA** [comment]
Si hay pero habría que ir vinculandola y haciendola funcionar. http://72.52.188.248/_parex/
Necesito tiempooooooooo para eso!

**Comment by LeandroBraier** [comment]
No se apuren con eso, vamos con la que dice Gleepa abajo. No pasa nada.
Estamos simulando que es la misma página, no pasa nada. Vamos con esa.

La versión 1.0 que dice Fede la vamos a inaugurar la semana que viene.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 16:46 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Ok, entonces "intervengo" la que esta en _backup.

**Comment by mkreyness** [comment]
Ya casi estamos eh.
Lo que habria que intentar (a ver si se puede) cuando se delegue el 
dominio es que apunte a esta carpeta:

http://72.52.188.248/parexklaukol

Fijense que si copian cualquier URL del sitio viejo, por ej

http://www.parexklaukol.com.ar/simulador/images/casas/03.jpg

y lo ponen como

http://72.52.188.248/parexklaukol/simulador/images/casas/03.jpg

les aparece el popup con la pagina principal detras, y:
     - si hacen click en cualquier parte del banner, va a la pagina de 
"ultima tecnologia".
     - si hacen click en "cerrar", va a la que pidieron. MAGIA !!!

Ahora bien, esto va a pasar con CUALQUIER cosa que caiga aca, o sea, no 
hosteen nada que haya que acceder por parexklaukol.com que no sea esto, 
porque va a direccionarlo al .com.ar.

**Comment by LeandroBraier** [comment]
Grande MK!

Pero como hacemos con el Micrositio mismo? Porque ese debería estar subido
en parexklaukol.com/ImpermeablePotenciado

**Comment by mkreyness** [comment]
Habra que agregar una rule especifica para que se vaya por ese lado.
Pero todos los sitios deberian depender de esta carpeta. Si quieren 
pasarme una lista, voy agregando las rules y probando que funcionen.
Lo hice asi en una carpeta para que podamos seguir trabajando con las 
otras cosas via el IP sin que nos vuelva loco a redirecciones.

**Comment by LeandroBraier** [comment]
De qué seria la lista MK? Asi te ayudo con eso.

**Comment by mkreyness** [comment]
Los nombres de las carpetas que van a estar hosteadas dentro de 
parexklaukol.com

**Comment by LeandroBraier** [comment]
Fede, cómo venimos con esto? Se nos está haciendo REtarde para hacer la delegación.

**Comment by LeandroBraier** [comment]
Fede, cómo venimos con esto? Se nos está haciendo REtarde para hacer la delegación.

**Comment by FAAREIA** [comment]
No se iba a delegar el domingo o el lúnes a la mañana?
Vengo bien pero aún falta un poco, no esta cerrado al 100%.
