### ISSUE TITLE
Botón de "Descargar Video" en Página del Video de Maraton. 19/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#190]
@braulio-evangelisti y @mkreyness : tranqui para el lunes necesito que la página video2.html (donde aparece el video de cada corredor) tenga un botón de "Descargar Video", que les permita bajarse el mp4 del video.

Para el lunes necesitaríamos tener eso porque el 22/10 le vamos a dar de baja al servidor y se van a quedar todos sin video.

abrazo

**Comment by braulio-evangelisti** [comment]
Ok. Sigue siendo video2.html la pagina final? Porque veo que hay una _video3_ y _videoT.html_

Consulto por las dudas antes asi no hay errores.

**Comment by LeandroBraier** [comment]
Creo que si pero antes de meter mano coordina con Marcelo por las dudas.

Trabaja en /vídeo3/ como beta hasta que tengamos todo ULTRA chequeado y
funcional.

Abrazo

**Comment by mkreyness** [comment]
Lo real que se usa es videoT.html, hacete una copia del videoT.html con otro nombre para trabajar si queres, pero no volvamos para atras porque se van a romper las cosas que tuve que cambiar.

**Comment by braulio-evangelisti** [comment]
Perfecto.

**Comment by braulio-evangelisti** [comment]
Ahi subi 

http://www.parexklaukol.com.ar/maraton/videoTdescarga.html

En un rato subo el mailing.

@mkreyness faltaria ponerle el link al boton de descarga, como en el iframe se carga mediante js el video no quiero tocar por las dudas.

**Comment by mkreyness** [comment]
Ahora lo ajusto yo y les aviso.

**Comment by mkreyness** [comment]
LIsto, si se pone con el numero=XXXX en el URL ya funciona el boton de descarga, por ej

http://www.parexklaukol.com.ar/maraton/videoTdescarga.html?numero=1818

**Comment by LeandroBraier** [comment]
Quedó excelente Brau y MK!!! Muchas gracias!!!
