### ISSUE TITLE
Adaptación del Mailing de Video Maraton para que la gente se descargue el video. 19/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#191]
@braulio-evangelisti necesito que hagas una adaptación del mailing en el cual cambie el texto. 

Donde dice: 

"Felicitaciones por haber llegado a la meta! 
Ya está listo tu video personalizado de la Maratón donde podés revivir el momento de tu llegada."

Debe decir:

"¿Ya viste tu video personalizado de la Maratón?
Ahora ya podés descargarlo a tu computadora. Aprovechá esta semana que es la última semana de vigencia de la campaña."

Lleva al mismo link que antes, pero ya con el botón de "Descargar video" incorporado.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahi estaría lo pedido Lea

http://parexklaukol.com.ar/_mailing/maraton/maraton-video.html

Abrazo

**Comment by LeandroBraier** [comment]
Buenisimo Brau!! Muchas gracias! 

Solo un pedido: cambiale el thumbnail de la maratón de NY por alguna de estas dos, la que quede mejor:

<img width="769" alt="preview video maraton 42k" src="https://cloud.githubusercontent.com/assets/6719872/10581461/304c91ea-7659-11e5-8219-887394a91842.png">

![preview-v2-video-maraton](https://cloud.githubusercontent.com/assets/6719872/10581575/d3584802-7659-11e5-83ec-215e5ff77af8.png)

Una vez cambiado listo, pasaselo a @mkreyness para que le aplique lo funcional, lo testeamos y lo mandamos hoy mismo.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea

**Comment by mkreyness** [comment]
Lea seria para mandar a TODOS los que ya recibieron el mail ?
Ya una vez mandados no tengo forma de distinguir los que confirmaron su email o no original.
Y cual seria el Asunto: del mail ?

**Comment by LeandroBraier** [comment]
Perfecto MK. Si, a todos.

El asunto sería: Última semana para ver y descargar tu video personalizado de la Maratón de Buenos Aires.

**Comment by mkreyness** [comment]
Ahi te mande uno de prueba (esta a nombre de Ezequiel pero con direccion tuya).
Confirmame y lo pongo a salir.

**Comment by LeandroBraier** [comment]
Confirmado MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ya estan saliendo.

**Comment by LeandroBraier** [comment]
Gracias MK! AHora solo te pido que bajes un backup de todos los videos compilados finales. Serían 120 gb según mis cálculos. Es porque cuando demos de baja el server seguro algun colgado los va a pedir.

**Comment by mkreyness** [comment]
```
y a donde los bajo ? Yo no tengo lugar.

El 20/10/2015 a las 0:24, LeandroBraier
  escribió:


  Gracias MK! AHora solo te pido que bajes un backup de todos los
    videos compilados finales. Serían 120 gb según mis cálculos. Es
    porque cuando demos de baja el server seguro algun colgado los
    va a pedir.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Si te mandamos un disco externo podrías hacerlo?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-20 0:30 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ese calculo fue en base a los videos de 1 min o de los de 12 seg ?

Enviado desde mi iPhone

**Comment by mkreyness** [comment]
```
Los sume.
Los videos de 12 seg suman 44 Gb.
Los videos de 1min suman 80 Gb.
Hubiera esperado mas diferencia realmente.

El 20/10/2015 a las 10:07, Marcelo
  Kreyness escribió:



  Ese calculo fue en base a los videos de 1 min o de los de 12
    seg ?

    Enviado desde mi iPhone

    El 20 oct 2015, a las 10:03, LeandroBraier <notifications@github.com>
    escribió:



    Si te mandamos un disco externo podrías hacerlo?

      Leandro Braier
      Producción Audiovisual & Social Media
      Benteveo Producciones <http://benteveo.tv>
      Móvil 1158717399

      2015-10-20 0:30 GMT-03:00 mkreyness <notifications@github.com>:

      >
      >
      >
      >
      >
      > y a donde los bajo ? Yo no tengo lugar.
      >
      > El 20/10/2015 a las 0:24, LeandroBraier
      > escribió:
      >
      >
      > Gracias MK! AHora solo te pido que bajes un backup de
      todos los
      > videos compilados finales. Serían 120 gb según mis
      cálculos. Es
      > porque cuando demos de baja el server seguro algun
      colgado los
      > va a pedir.
      >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      > <https://github.com/LeandroBraier/Klaukol/issues/191#issuecomment-149417877>
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.
```

**Comment by LeandroBraier** [comment]
Claro, de ultima backupeá en principio todos los videos de 12 seg. Con ese
backup estamos bien. Ese si te entra? Nosotros te pasamos un disco para que
lo copies ahí y te liberes el espacio.

Sino pasanos un link para descargarlo nosotros pero que no sea 1 solo
archivo de 44 gb porque se nos va a cortar siempre.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-20 12:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Si, 44Gb puedo levantarlos. Pero si quieren bajarlo ustedes mejor,
ahi hice en la carpeta de upload un link a la carpeta videos, o sea
que entrando con el FileZilla lo pueden ver y levantar.
Cualquier cosa avisame.

El 20/10/2015 a las 12:10,
  LeandroBraier escribió:

Claro, de ultima backupeá en principio todos los
  videos de 12 seg. Con ese
  backup estamos bien. Ese si te entra? Nosotros te pasamos un disco
  para que
  lo copies ahí y te liberes el espacio.

  Sino pasanos un link para descargarlo nosotros pero que no sea 1
  solo
  archivo de 44 gb porque se nos va a cortar siempre.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-10-20 12:03 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Los sume.
  > Los videos de 12 seg suman 44 Gb.
  > Los videos de 1min suman 80 Gb.
  > Hubiera esperado mas diferencia realmente.
  >
  > El 20/10/2015 a las 10:07, Marcelo
  > Kreyness escribió:
  >
  >
  >
  >
  > Ese calculo fue en base a los videos de 1 min o de los de 12
  > seg ?
  >
  > Enviado desde mi iPhone
  >
  > El 20 oct 2015, a las 10:03, LeandroBraier
  <notifications@github.com>
  > escribió:
  >
  >
  >
  > Si te mandamos un disco externo podrías hacerlo?
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-10-20 0:30 GMT-03:00 mkreyness
  <notifications@github.com>:
  >
  > >
  > >
  > >
  > >
  > >
  > > y a donde los bajo ? Yo no tengo lugar.
  > >
  > > El 20/10/2015 a las 0:24, LeandroBraier
  > > escribió:
  > >
  > >
  > > Gracias MK! AHora solo te pido que bajes un backup de
  > todos los
  > > videos compilados finales. Serían 120 gb según mis
  > cálculos. Es
  > > porque cuando demos de baja el server seguro algun
  > colgado los
  > > va a pedir.
  > >
  > > —
  > > Reply to this email directly or view
  > > it on GitHub.
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > > <
  >
```

https://github.com/LeandroBraier/Klaukol/issues/191#issuecomment-149417877
      > >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/191#issuecomment-149594525
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Perfecto. Lo bajamos de ahi. El tema es que desde donde estoy ahora no
puedo hacerlo. Me da el mismo error de time out que antes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-20 12:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Aunque sea con UN video ?

**Comment by LeandroBraier** [comment]
O sea, no me puedo conectar al ftp desde acá de la produ. Voy a probar en
mi casa pero me quería asegurar de que fueran 4000 videos diferentes, no
todo en 1 zip pnele.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-20 13:11 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
no hay zips, es el directorio donde estan TODOS los videos, los 
"finalnumeroXXXX" (largos) y los "numeroXXXX" (cortos).
Si los ordenas y seleccionas por ej todos los numeroXXXX, son 44 Gb, 
pero si se te corta retomas del ultimo.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-20 15:54 GMT-03:00 mkreyness notifications@github.com:
