### ISSUE TITLE
Quitar Banner Maraton de WebParexKlaukol 21/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#192]
@FAAREIA el jueves necesito que quites el banner de la maratón de la web. Aprovecho que vas a tocar y te hago un par de consultas.

1) ¿Hay posibilidad de poner más grandes los íconos que llevan a Facebook y YouTube en la web?

2) ¿Hay posibilidad de poner los íconos como flotantes sobre la página, como el chat de la web de Benteveo?

3) ¿Hay posibilidad de poner Facebook Connect en la web? 

4) ¿Llevaría muchas horas agregar la posibilidad de que todos los contenidos sean likeados y/o compartidos en Facebook como teníamos en Dánica?

abrazo

**Comment by FAAREIA** [comment]
Hola Lea
1. Se puede, pero van a competir con las marcas y si agrandas las marcas para ajustarlo, hay que agrandar el logo.
2. Se puede pero no va a quedar bien, ese recurso esta bueno para sitios de una página pero en sitios comunes puede quedar confuso. Imaginate que estas viendo un artículo y tenes el facebook y el youtube volando, bajando con el scroll y en otro lado, estático, el Me gusta y Twittear.
3. Se puede, qué sería de Facebook Connect?
4. Se puede agregar y generar las variables, el tema es que alguien va a tener que generar las imágenes y descripciones de cada producto y cargarlas en el CMS. Algunas descripciones estan hechas, otras habría que achicarlas.

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Entiendo todo.

Por ahora dejemoslo asi a eso nomás. Entonces espero lo del banner: Bajalo mañana nomás sin apuro.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!
