### ISSUE TITLE
Versión VIETUR de Comunidad de Vendedores 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#193]
@FAAREIA te cuento una buena noticia. Logramos vender la Comunidad de Vendedores a una agencia de turismo, llamada Vietur. Felicitaciones!!

Encima justo sus colores son rojo y azul:

http://www.vietur.com.ar/

En principio va a tener todas las mismas funcionalidades que Parex salvo un juego con un agregado puntual. 
Por el momento solo necesito que me calcules tiempos de replicación de la plataforma con CMS incluido y adaptando el diseño (cambio de logo, cambio de algunos colores, bases y condiciones, etc). Todo lo demás que cambia son contenidos, incluyendo embed de facebook, embed del video instructivo, etc.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, felicitaciones por el nuevo cliente!
Yo creo que con 5 días dedicados se resuelve si es que no hay que hacer un cambio brusco de diseño o maqueta.
@mkreyness Copio a Marce para que diga sus tiempos.

**Comment by LeandroBraier** [comment]
BUenisima noticia! Yo le estimé más tiempo, asi que estamos bien con 5 días. Espero el OK de @mkreyness  y paso los tiempos.

abrazo

**Comment by mkreyness** [comment]
1) Felicitaciones por tener de cliente... al papá de Ezequiel
2) Se hostea en Duplika ? Si, replicar el CMS no puede llevarme mucho tiempo, pero ahora estamos medio apretados con otras cosas, no ?

**Comment by LeandroBraier** [comment]
1) Así es.

2) Se hostearía en otro hosting dentro de Duplika según entiendo. La fecha
no es urgente. Para noviembre sería, por ejemplo para mediados. Llegás bien
no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-21 13:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si no aparece nada raro, si. Con toda la furia replicar con adaptaciones minimas llevara 20hs.

**Comment by LeandroBraier** [comment]
Genial chicos. Les aviso cuando esté aprobado todo para arrancar.

abrazo
