### ISSUE TITLE
Ajustes footer Comunidad de Vendedores y header y footer Academia ParexKlaukol. 23/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#194]
@FAAREIA van dos pedidos:

1) FOOTERS me pidieron que el footer de Comunidad de Vendedores (que ahora no lo hay) sea idéntico al de la Web de ParexKlaukol. Lo mismo me pidieron para el footer de Academia ParexKlaukol. Podemos hacer eso?

2) HEADER: Me pidió el cliente que Academia ParexKlaukol deje de tener logo y de llamarse Academia ParexKlaukol. El header quedaría muy similar al de la web de ParexKlaukol, con el logo de ParexGroup a la izquierda y los otros logos de las marcas a la derecha. Solo se diferenciaría en que:

a) Tendría el título de "Cursos Online"
b) No tendría el link al micrositio de Klaukol Impermeable Potenciado
c) Obviamente tendría el menú de la Academia y la posibilidad de Ingresar a la misma.

Estos cambios pueden estar para el viernes si me confirmás que llegamos.

abrazo

**Comment by FAAREIA** [comment]
Ok a todo, creo que llegamos para el viernes al mediodía pero el adelantado del maquetado del nuevo diseño de los productos klaukol va a retrasarse.
Lo que no me quedó 100% claro es si el logo de la academia se mantiene y solo el texto interno pasa a ser "Cursos Online".

**Comment by FAAREIA** [comment]
No sería bastante raro entrar a un sitio que no tiene su propio logo?

**Comment by LeandroBraier** [comment]
Fijate bien el pedido.

Lo que yo te pedí que tenga el logo de ParexGroup a la izquierda y a la
derecha "Cursos Online". No es más un sitio propio, es una sección de la
web de parexklaukol.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-22 11:54 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok lo pruebo, pero no es una sección del sitio, es un micrositio, si fuese una sección más los estilos serían los mismo que el sitio original y el menú de secciones de la academia también estaría en parex.
Por esto mismo que te digo es raro que tenga un encabezado muy similar y sin logo propio

**Comment by LeandroBraier** [comment]
Entiendo. Probemos como queda y vemos qué dice el cliente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-22 12:03 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Algo asi?

![prueba-1](https://cloud.githubusercontent.com/assets/6184969/10669862/1076cc20-78b9-11e5-85ee-4d3392291890.png)
![prueba-2](https://cloud.githubusercontent.com/assets/6184969/10669863/109390e4-78b9-11e5-810e-7fddf8c57279.png)
![prueba-3](https://cloud.githubusercontent.com/assets/6184969/10669864/10c7dd5e-78b9-11e5-98a6-b14ffe7caafd.png)

**Comment by LeandroBraier** [comment]
Exacto!

Vamos con el de fondo azul. Le muestro ese al cliente y te confirmo.

abrazo

**Comment by LeandroBraier** [comment]
Fede, pasame ya directamente el header de Academia completo, con todos los cambios que te pedí:

Que sea IGUAL al header de la web de ParexKlaukol salvo que:

a) Tendría el título de "Cursos Online"
b) No tendría el link al micrositio de Klaukol Impermeable Potenciado
c) Obviamente tendría el menú de la Academia y la posibilidad de Ingresar a la misma. Te paso boceto sugerido por el cliente, vos adaptalo a una estética que combine con todo lo que venimos haciendo, que siga las mismas reglas gráficas:

<img width="890" alt="captura de pantalla 2015-10-26 a las 13 23 20" src="https://cloud.githubusercontent.com/assets/6719872/10734651/126fcc84-7be3-11e5-9a5c-4a5efeb7fc94.png">

abrazo

**Comment by FAAREIA** [comment]
Entiendo que no es idéntico pero creo que no da para que lo sea.
Lo extraño que tiene el encabezado de parex es que parece que no tiene secciones, tiene logos que llevan a secciones pero no sorprendería si llevan a un sitio aparte.
Ahora.....Academia tiene secciones y las marcas son algo terciario (ya bastante que estan en color). Lo principal son las secciones y el login/registro. Si mantengo el encabezado de parex y meto donde pueda las secciones y el login+registro va a quedar un hibrido raro y poco claro para el sitio.
A mi criterio los encabezados ya son bastantes parecidos, si nos fijamos en los bloques de contenidos, el logo esta a la izquierda, el menú y las marcas a la derecha.
¿Estas seguro que queres que lo haga identico?
¿Los sitios no estan perdiendo identidad por ese temor a "no se reconoce" haciendo que TODO sea MUY similar?

**Comment by LeandroBraier** [comment]
Entiendo pero en este caso particular es la idea que se pierda identidad.
Estamos hablando de ex academia, no de las demás plataformas. Hagamoslo
porfa y gracias por la sugerencia igualmente.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! a qué hora podemos tener el header corregido?

Estamos arrancando reunión con el cliente y sería ideal mostrarselo como quedaría.

**Comment by FAAREIA** [comment]
Estoy con eso. Cuando lo tenga se los paso pero en imagen, maquetado no.

**Comment by LeandroBraier** [comment]
No, claro. En imagen simplemente. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
![op1](https://cloud.githubusercontent.com/assets/6184969/10788239/13985338-7d55-11e5-999f-dfaed2001e5f.png)
![op2](https://cloud.githubusercontent.com/assets/6184969/10788240/13b88edc-7d55-11e5-963d-d728b6f6669e.png)

**Comment by LeandroBraier** [comment]
Buenisimo Fede!! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Está aprobado Fede. Simplemente me pidieron que quitemos la sección de Capacitaciones, lo demás queda así. Impactemos el nuevo header y cambiemos la URL de /academia/ a /cursos-online/

abrazo

**Comment by FAAREIA** [comment]
La sección capacitaciones se va por completo? Sacamos lo del home y todo lo relacionado, no?

**Comment by FAAREIA** [comment]
Cual header esta aprobado, el primero o el segundo?

**Comment by LeandroBraier** [comment]
Este sería:

https://cloud.githubusercontent.com/assets/6184969/10788239/13985338-7d55-11e5-999f-dfaed2001e5f.png

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/academia/
F5

**Comment by LeandroBraier** [comment]
Perfecto el header Fede!

Cierro el ticket y avisame por este otro cuando hayas quitado la parte de capacitaciones de la home:

https://github.com/LeandroBraier/Klaukol/issues/100

abrazo
