### ISSUE TITLE
Bug en Fechas de Novedades ParexKlaukol 26/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#195]
@mkreyness siguen estando las fechas mal en la lista de novedades de la página. Revisás qué pasa porfa? En el CMS están bien.

http://www.parexklaukol.com.ar/novedades.html

abrazo

**Comment by mkreyness** [comment]
listo. Estaba arreglado para las fechas que se muestran ENTRANDO a cada novedad, pero nunca se habia arreglado en el listado propiamente dicho.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness estoy viendo que todas las mejoras que aplicaste en el CMS de Novedades en cuanto a Fechas y insertar imágenes extra no aparecen en el usuario de "Mantenimiento". Deberían aparecer en todos los usuarios no?

**Comment by LeandroBraier** [comment]
@mkreyness cuando tengas esto solucionado me avisás porfa?

**Comment by mkreyness** [comment]
Ah, no vi que habias reabierto este ticket.
Entrando con que usuario ves las cosas bien ?
Lo que pasa con los CMS de novedades es que estan abiertos por PAIS, puede que falte aplicarlo a Paraguay/Uruguay, pero eso no deberia tener que ver con el usuario.

**Comment by LeandroBraier** [comment]
No, te hablo de Argentina y Usuario Mantenimiento.

En Usuario Admin lo veo bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 11:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Yo veo lo mismo entrando por cualquiera de los dos usuarios.
La unica diferencia es que como se guardan unas preferences del ordenamiento, por usuario, en un caso veo ordenado de mas viejo a mas nuevo y en el otro de mas nuevo a mas viejo.
Me copias el URL completo que te aparece en ambos casos asi veo si lo puedo reproducir ?

**Comment by LeandroBraier** [comment]
Me refiero específicamente a:
1. Corrección de ingreso de fecha de cada nota (en usuario "Mantenimiento" se siguen viendo mal como antes)
2. Agregado de imágenes extra en cada nota de novedades (acá en la solapa "Imágenes" solo está el botón de "Esportar excel" no el de "Agregar imagen"

abrazo

**Comment by mkreyness** [comment]
2) es una cuestion de nivel de permisos del usuario, ahi lo ajuste para que el usuario Mantenimiento pueda hacerlo.
1) no termino de entender, decis que las fechas de las noticias ingresadas por el usuario Mantenimiento salen mal en las paginas del sitio ? Eso no depende del usuario que las ingresa.
Mostrame un caso concreto asi puedo verlo.

**Comment by LeandroBraier** [comment]
2) Perfecto.

1) No en las páginas del sitio, en el listado que tira el CMS.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 11:58 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Yo veo las mismas fechas, solo que en admin estaban en orden de mas viejo a mas nuevo y en mantenimiento de mas nuevo a mas viejo, ahi puse tambien que admin las muestre de mas nuevo a mas viejo (me parece lo mas logico, porque es como se ven en el sitio), pero las fechas que veo son las mismas !

**Comment by LeandroBraier** [comment]
Ahora si. Gracias MK!!

**Comment by mkreyness** [comment]
tene en cuenta que las preferencias de ordenamiento siempre son por usuario (para que c/u lo ponga como mas le guste. Se ordena haciendo click en los titulos de las columnas, y podes ordenar por mas de una haciendo shift-click. Click de nuevo en la misma da vuelta la flecha, pero perdes lo que tuvieras marcado en las otras. shift-click en la misma da vuelta la flecha sin perder la seleccion de las otras columnas.

**Comment by LeandroBraier** [comment]
Ah, buenisimo el dato. Pensé que no funcionaba así esto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 12:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness revivo este ticket para no abrir otro.

En esta url: http://www.parexklaukol.com.ar/novedades.html el link del primer artículo no está bien. Sigue tomando una url ya modificada via cms.

No pasa en los listados de la columna derecha una vez que estoy dentro de una novedad.

abrazo

**Comment by LeandroBraier** [comment]
Lo mismo ocurre con la tercer nota de la lista:

http://www.parexklaukol.com.ar/novedades/revestimientos-acrilicos-texturados--una-solucion-decorativa-para-paredes-interiores-y-exteriores-.html

**Comment by mkreyness** [comment]
tienen unos guiones de mas en el URL.
Debe haber quedado un URL en el titulo safe que no es el real. Ahora los republico y seguro se arregla

**Comment by LeandroBraier** [comment]
Gracias MK! Lo que necesito es que se actualice solo eso porfa, dejalo ya
solucionado porque nos pasó un par de veces ya.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Obviamente, ademas NO se arreglo al regenerarlo.
Ya encontre el problema: el programa no estaba encontrando la url safe, la estaba regenerando a partir del titulo y le daba distinto. Una incoherencia de nombres internos. Ya ahora quedo bien, fijate.

**Comment by LeandroBraier** [comment]
Perfecto MK! GRACIAS!

Abrazo

**Comment by LeandroBraier** [comment]
@mkreyness fijate este artículo:

http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-haran-entrega-de-los-premios-ventanas-al-futuro-de-la-arquitectura.html

Yo lo corregí hace semanas para que las comillas del título del artículo no aparecieran en la url, pero en los listados de links (tanto en /novedades.html como en la columna derecha de otras novedades) aparece con comillas igual:

http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-haran-entrega-de-los-premios-%E2%80%9Cventanas-al-futuro-de-la-arquitectura%E2%80%9D.html

Me parece que está pasando lo mismo que en el caso que ya corregiste.

**Comment by mkreyness** [comment]
```
Lo que pasaba ANTES es que al generarse la pagina (un proceso
separado del CMS) no estaba mirando lo que decia en el "Titulo URL"
del CMS, sino que lo volvia a armar por su cuenta, con lo que
ignoraba tus ajustes.

En ESTE caso, en el CMS seguian teniendo las comillas en el titulo,
y en el URL.
Debe ser que despues hiciste algun toque adicional en el titulo y se
regenero el URL de nuevo y no te diste cuenta.

Ahi se las saque yo y en seguida se va a regenerar (solo) todo.

El 02/11/2015 a las 8:36, LeandroBraier
  escribió:


  @mkreyness fijate este artículo:
  http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-haran-entrega-de-los-premios-ventanas-al-futuro-de-la-arquitectura.html
  Yo lo corregí hace semanas para que las comillas del título del
    artículo no aparecieran en la url, pero en los listados de links
    (tanto en /novedades.html como en la columna derecha de otras
    novedades) aparece con comillas igual:
  http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-haran-entrega-de-los-premios-%E2%80%9Cventanas-al-futuro-de-la-arquitectura%E2%80%9D.html
  Me parece que está pasando lo mismo que en el caso que ya
    corregiste. 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Marce, yo se las había sacado ya y hace rato. Pero más allá de eso, no hay
forma de que el generador automático de URLs ignore las comillas y los
dobles espacios?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-02 8:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No me cabe duda que se las debes haber sacado, pero apenas le
cambias algo mas en el titulo se vuelve a generar y capaz no te das
cuenta.

Si, obviamente deberia ignorar comillas y dobles espacios, pero se
ve que no lo esta haciendo. 
En un rato lo reviso y se soluciona.

El 02/11/2015 a las 9:08, LeandroBraier
  escribió:

Marce, yo se las había sacado ya y hace rato. Pero más
  allá de eso, no hay
  forma de que el generador automático de URLs ignore las comillas y
  los
  dobles espacios?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Agencia Productora <http://benteveo.tv>
  Móvil 1158717399

  2015-11-02 8:54 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Lo que pasaba ANTES es que al generarse la pagina (un proceso
  > separado del CMS) no estaba mirando lo que decia en el
  "Titulo URL"
  > del CMS, sino que lo volvia a armar por su cuenta, con lo que
  > ignoraba tus ajustes.
  >
  > En ESTE caso, en el CMS seguian teniendo las comillas en el
  titulo,
  > y en el URL.
  > Debe ser que despues hiciste algun toque adicional en el
  titulo y se
  > regenero el URL de nuevo y no te diste cuenta.
  >
  > Ahi se las saque yo y en seguida se va a regenerar (solo)
  todo.
  >
  > El 02/11/2015 a las 8:36, LeandroBraier
  > escribió:
  >
  >
  > @mkreyness fijate este artículo:
  >
  >
```

http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-haran-entrega-de-los-premios-ventanas-al-futuro-de-la-arquitectura.html
      > Yo lo corregí hace semanas para que las comillas del título
      del
      > artículo no aparecieran en la url, pero en los listados de
      links
      > (tanto en /novedades.html como en la columna derecha de otras
      > novedades) aparece con comillas igual:
      >
      >
http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-haran-entrega-de-los-premios-%E2%80%9Cventanas-al-futuro-de-la-arquitectura%E2%80%9D.html
      > Me parece que está pasando lo mismo que en el caso que ya
      > corregiste.
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/195#issuecomment-152997689
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Gracias MK!
