### ISSUE TITLE
Bajada de videos de Maratón

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#196]
MK, estoy intentando descargarme los videitos y es un caos. El server se corta todo el tiempo, descarga un poco, se corta, vuelve a intentar. Está hace 24 hs en proceso y todavía no estoy ni lejos de bajar todo. 

Vos tenés una forma más eficiente de bajada? Yo mañana podría acercarte el disco a tu casa para que te desembaraces rápidamente de los 44 gb sin problemas y de paso te pido los pendrives que quedaron allí. Qué decís?

**Comment by mkreyness** [comment]
los 44gb no hay problema, eso lo puedo bajar. Los pendrives los tengo encima, en cualquier momento que combinemos se los paso. Igual por lo de DelViento va a haber mucho mas movimiento de materiales que esto.

**Comment by LeandroBraier** [comment]
Genial, MK: Porfa descargalos entonces y decime aq ué hora puedo pasar
mañana, ponele tipo 14 hs estás?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-21 21:02 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No, salgo de casa 9:30, y llego a mi oficina (cerca de la casa de
MS) tipo 3:30 o 4.
Ando en zona Santa Fe y Azcuenaga de 10 a 12:30 y zona Sarmiento y
Gallo de 1 a 3 o 3:30.

El 21/10/2015 a las 21:26,
  LeandroBraier escribió:

Genial, MK: Porfa descargalos entonces y decime aq ué
  hora puedo pasar
  mañana, ponele tipo 14 hs estás?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-10-21 21:02 GMT-03:00 mkreyness
  <notifications@github.com>:

  > los 44gb no hay problema, eso lo puedo bajar. Los pendrives
  los tengo
  > encima, en cualquier momento que combinemos se los paso.
  Igual por lo de
  > DelViento va a haber mucho mas movimiento de materiales que
  esto.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/196#issuecomment-150057753
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
Ahora ya llevo 1/3 bajado, y recien me avivo: estoy levantando todo doble, porque por cada "numeroXXXX" estan los 4 pedacitos (XXXX-1.mp4, XXXX-2.mp4, XXXX-3.mp4, XXXX-4.mp4) y el armado (XXXX.mp4). Si lo corto va a ser un kliombo retomar.
Despues los borro de mi maquina, neto va a ocupar 22 Gb en vez de 44.

**Comment by LeandroBraier** [comment]
Ok, genial. Paso después de la 4 por tu oficina entonces. Probablemente 18
hs. Me pasás la dire porfa?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-22 1:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Ya termino todo de bajar.
Ojo que los tengo bajados aca en mi casa, en mi oficina si que no
tengo espacio en disco ni para un alfiler.
Vos necesitas llevartelos en el momento o solo dejarme el disco ?

El 22/10/2015 a las 8:40, LeandroBraier
  escribió:

Ok, genial. Paso después de la 4 por tu oficina
  entonces. Probablemente 18
  hs. Me pasás la dire porfa?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-10-22 1:42 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Ahora ya llevo 1/3 bajado, y recien me avivo: estoy
  levantando todo doble,
  > porque por cada "numeroXXXX" estan los 4 pedacitos
  (XXXX-1.mp4, XXXX-2.mp4,
  > XXXX-3.mp4, XXXX-4.mp4) y el armado (XXXX.mp4). Si lo corto
  va a ser un
  > kliombo retomar.
  > Despues los borro de mi maquina, neto va a ocupar 22 Gb en
  vez de 44.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/196#issuecomment-150104829
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Te puedo dejar el disco, no hace falta que me los lleve en el momento.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-22 8:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Ok, igual ahora que lo limpie de "pedacitos" son 25 Gb, a mi no me
jode tenerlo. Vale la pena que me traigas un disco ?
Si es por los pendrives se los puedo entregar a quien me venga a
buscar las maquinas de delViento, que como te digo tambien tiene que
ser muy pronto.

El 22/10/2015 a las 8:56, LeandroBraier
  escribió:

Te puedo dejar el disco, no hace falta que me los
  lleve en el momento.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-10-22 8:52 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Ya termino todo de bajar.
  > Ojo que los tengo bajados aca en mi casa, en mi oficina si
  que no
  > tengo espacio en disco ni para un alfiler.
  > Vos necesitas llevartelos en el momento o solo dejarme el
  disco ?
  >
  > El 22/10/2015 a las 8:40, LeandroBraier
  > escribió:
  >
  > Ok, genial. Paso después de la 4 por tu oficina
  > entonces. Probablemente 18
  > hs. Me pasás la dire porfa?
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-10-22 1:42 GMT-03:00 mkreyness
  > <notifications@github.com>:
  >
  > > Ahora ya llevo 1/3 bajado, y recien me avivo: estoy
  > levantando todo doble,
  > > porque por cada "numeroXXXX" estan los 4 pedacitos
  > (XXXX-1.mp4, XXXX-2.mp4,
  > > XXXX-3.mp4, XXXX-4.mp4) y el armado (XXXX.mp4). Si lo
  corto
  > va a ser un
  > > kliombo retomar.
  > > Despues los borro de mi maquina, neto va a ocupar 22 Gb
  en
  > vez de 44.
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > >
  > <
  >
```

https://github.com/LeandroBraier/Klaukol/issues/196#issuecomment-150104829
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/196#issuecomment-150197531
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Perfecto. Hagamos así entonces. Guardame los22 gb unos días y te los paso a
buscar la semana que viene.

Gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness , -PARA CUANDO TERMINEMOS CON COLOCADORES-

MS está dando de baja el server de Amazon. Tendríamos que dar de baja la landing de /maraton/ en Duplika o al menos evitar que la gente se siga suscribiendo.

abrazo

**Comment by mkreyness** [comment]
Desde la pagina principal de Klaukol no veo links para entrar a los formularios de maraton.

Pero no puedo evitar que la gente haga click en links que tienen en sus mails, darlo de baja como para que les tire "404" es feo, hago que redirijan a la pagina principal de parexklaukol ? Si no habria que poner algun cartel medianamente decente.

**Comment by LeandroBraier** [comment]
Tal cual MK. Que redirija a Parexklaukol.

**Comment by mkreyness** [comment]
Listo, creo que todos los links quedaron ya redirigiendo bien.
Si tenes los mails de prueba (yo ya los borre) fijate que todos los links viejos vayan ahi

**Comment by LeandroBraier** [comment]
Perfecto MK! Probé los dos que tenía y me redirijieron perfecto. Abrazo!
