### ISSUE TITLE
5 corredores que no pueden ver el video

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#197]
@mkreyness hoy cuando vuelvas, fijate estos 5 casos, que parece ser gente que no confirmó su mail. En estos 5 casos demoselo como confirmado si es así y avisame cuando estén online así le digo al cliente que les responda con el link final.

Daniel Diaz  
5251

Ivan Popoff
230

Oscar Gonzalez
5493

Claudia Andrea Villaboa Barbetti
7293

Pablo Teysseire
7379

abrazo

**Comment by mkreyness** [comment]
No es eso, el problema es que esos numeros los ingresaron otras personas, y duplicados.
Por ejemplo, 5251 figura con dos nombres, y ninguno de ellos es ese. 
NO PUEDO madarle el mail, porque simplemente no lo tengo !
En este caso figuran estos dos posibles mails:
Orangel  Arias     ariasorangel@fibertel.com.ar 
Natal   Sanchez   natalsanchez@fibertel.com.ar 

y por lo que decis, ambos son FALSOS, hicimos bien en no procesarlos.
Si te lo genero, va a aparecer con alguno de esos nombres truchos, y no tengo el email.
Por que no se registra en la pagina (algo que nunca hizo) y pone su numero, asi puedo procesarlo ?

**Comment by LeandroBraier** [comment]
Ok, pasa lo mismo en los 5 casos? Confirmame eso y eliminá los mails a esos
usuarios falsos por las dudas que al inscribirse vuelvan a usar el mismo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-23 13:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
no, cada caso es otra cosa. 
El 5493 por ejemplo no figura en la lista de dorsales, los que pueda sacar adelante ahora los saco y despues te paso lo que son insalvables.

**Comment by LeandroBraier** [comment]
Ok, igual ya les pedí a todos que se vuelvan a inscribir con los datos
correctos. Los que sean 100% truchos saltarán ahi.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-23 16:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok, entonces vamos por ese lado porque si no voy a duplicar.
Pero eso no va a solucionar si un numero de dorsal no aparece en el excel, al no tener la hora, no puedo hacer el video.

**Comment by LeandroBraier** [comment]
Si el número de dorsal no aparece en el excel es porque no corrió o llegó
después de las 18 hs y no tenemos su video. En esos casos avisame cuál es
el usuario y le aclaro al cliente aparte.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-23 16:30 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
El que no tenemos dorsal es el 5493. Del resto si pero estan los problemas de duplicados.
