### ISSUE TITLE
Bug Calculador de Adhesivos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#198]
@mkreyness : el Flash del Calculador de Adhesivos dejó de funcionar y dice lo siguiente:

Deprecated: mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/parexkla/public_html/bkps/parexklaukol.com.ar/simulador/include/adodb/drivers/adodb-mysql.inc.php on line 364

http://www.parexklaukol.com.ar/aplicaciones/calculador.html

Supongo que tiene que ver con que los navegadores están dejando de soportar Flash pero fijate si podemos hacer un fix para que dure un poco más hasta que veamos cómo resolverlo.

Si tuvieras que armar este calcular en HTML5, sería mucho desarrollo? Si podés calculá un estimado muy aproximado de horas.

abrazo

**Comment by mkreyness** [comment]
No, el flash no tiene nada que ver con esto. Lo que esta dando error es la conexion entre PHP y mySQL.
Probablemente alguna actualizacion que hizo Duplika de los drivers de mySQL para PHP. Eso es uno de los problemas de tener un host virtual, que te instalan updates sin avisar/preguntar.
Dejame verlo, seguramente se pueda zafar.

**Comment by LeandroBraier** [comment]
Genial MK, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-26 11:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo.

**Comment by LeandroBraier** [comment]
Perfecto MK!! Gracias!!

abrazo
