### ISSUE TITLE
Modificación de Links en la web de ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#199]
@FAAREIA cómo andás?

Solo un detallecito de la web principal de ParexKlaukol. Originalmente les había pedido que el logo de ParexGroup del header llevara a la home y el logo de ParexGroup del footer llevara a parex-group.com

El problema es que actualmente está al revés. El header debe llevar a la home nuestra, a parexklaukol.com.ar

El logo del footer debe llevar a parex-group.com

Avisame porfa cuando esté corregido.

abrazo

**Comment by FAAREIA** [comment]
Hecho en todos los paises

**Comment by LeandroBraier** [comment]
Gracias Fede!! En Argentina lo veo bien.

En Paraguay desaparecieron los logos y los estilos. Ajustalo que quede igual que en Argentina:

<img width="463" alt="captura de pantalla 2015-10-27 a las 8 48 25" src="https://cloud.githubusercontent.com/assets/6719872/10756802/78ae3e20-7c85-11e5-994d-338c73d1b824.png">

En Uruguay están pero siguen con el estilo viejo. Ajustalo que el footer quede igual que en Argentina, mantengamos el estilo.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Perfecto Fede! Gracias!
