### ISSUE TITLE
Backup CFT Online

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#20]
Marce, estuve hablando con Fede. Necesitamos que nos des una mano con los backups, específicamente en páginas y puntos donde se requieren código o programación.

Respecto de CFT Online, necesitamos que intentes utilizar tu motor para backupear sus materiales. Si necesitás create un login, son de libre creación. 

Probalo y avisame si se puede y para cuando lo podríamos tener.

abrazo

**Comment by mkreyness** [comment]
Ok, pero a que te referis con "mi motor" ? No tengo nada especifico para levantar cosas.

**Comment by LeandroBraier** [comment]
La verdad ni idea. Este pedido lo iba a hacer Fede en realidad, él sabe a qué me refiero jeje

Acá lo copié.

**Comment by mkreyness** [comment]
Me consegui bajar una cosa que se llama HTTRACK a la PC, no consigo instalar (pero hay) una version en los linuxes que tenemos, porque tenemos muy restringida la instalacion de paquetes.

**Comment by mkreyness** [comment]
Con eso pude ver que esto es mucho mas complicado de lo que creiamos: el CFT esta implementado sobre una plataforma de enseñanza virtual (EVE.SISMATICA.NET), que es muy compleja porque es generica, esta toda hecha en ASP (o sea, programas corriendo en un servidor de un PROVIDER. Me parece que no tiene nada que ver con los que los estan abandonando, porque es una empresa aparte. Mira por favor esto:

http://www.sismatica.net/sismatica/#!{"H":{"N":"secc_nota","S":"73","SS":"78","C":-1,"HA":0}}

Habria que ver si los de Klaukol tienen contacto con los de Sismatica sin pasar por Gleepa o como se llamen.  No tendrian por que dejar de estar en relacion y podria seguirles funcionando tal como esta.

**Comment by LeandroBraier** [comment]
MK, no podemos hacer el backup igual?

Sismatica puede que haya participado de la página pero no es la que aloja el sitio. LOs que alojan son los mismos que no nos quieren dar nada. Tenemos posibilidad de tener los contenidos (solos los contenidos, no el sitio entero) para el jueves backupeado?

**Comment by mkreyness** [comment]
No, no hay forma, el contenido es dinamico y se obtiene ingresando manualmente y clickeando en cada pagina, no existe hasta que se lo pida, y aun asi no se puede avanzar si no se pasa un examen.

**Comment by LeandroBraier** [comment]
Entonces chequeemos el backup caotico que nos mandaron y que tiene Fede
bajado. Si están ahi los contenidos yo me sumerjo a organizarlos, no hay
problema.

Confirmenme esto por favor.

Abrazo

**Comment by mkreyness** [comment]
lo descomprimo y veo, pero dudo mucho que este ahi porque te insisto que el contenido esta en una base de datos de sistemica, no importa la interface que las muestra, es siempre la misma, el contenido son basicamente textos (instrucciones de como usar los productos) muy cortos pero que van apareciendo progresivamente a medida que avanzas en el curso.

**Comment by mkreyness** [comment]
No, no hay nada, precisamente porque NO esta hosteado en el server de donde mandaron backups.
Si te fijas cualquier imagen de las que se muestran en los cursos tiene como URL http://eva.sistemica.com/..., lo cual significa que NO estan en klaukol, estan en sistemica.
Lo unico que hay en el sitio de klaukol son los links para ir a cftonline.com.ar, pero nada de ahi.

**Comment by mkreyness** [comment]
Mi teoria es que CFTOnline.com.ar no va a dejar de andar si el actual hosting de parexklaukol se cae. Ni siquiera estan usando los mismos DNS. Para mi CFTOnline.com.ar no es mas que un front-end puesto por sistemica para Klaukol, y esa relacion no tendria por que romperse.  En la propia pagina de sistemica ponen como propaganda de si mismos haber hecho esto para Klaukol, no van a querer romper esa relacion.
