### ISSUE TITLE
Newsletter Klaukol de Noviembre. 27/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#200]
@braulio-evangelisti  En este Google Doc tenés todos los contenidos, incluidos los textos y links de las imágenes. 

https://docs.google.com/document/d/1ekJUItG0xRyXD2-W6fxBcM8QpsTcXZmjXVOu-6D9kj8/edit

El news armalo directamente en una maqueta igual a esta solo que con los nuevos contenidos de texto e imagen:

http://www.parexklaukol.com.ar/_mailing/novedades-octubre/novedades-octubre.html

El footer queda tal cual. Los links a las notas los sumo hoy a la tarde, apenas los tengo.

Confirmame porfa si lo podés tener mañana mismo aunque sea a la tarde genial.

abrazo

**Comment by braulio-evangelisti** [comment]
Dale Lea, apenas este listo te aviso.

**Comment by braulio-evangelisti** [comment]
Seria para noviembre?

**Comment by LeandroBraier** [comment]
La idea es mandarlo el 01 de noviembre pero necesitaría si lo podés
maquetar para mañana porque tenemos reunion con el cliente y así lo vemos
directamente ahí.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Sisisis queria saber si era la news de noviembre para la ubicacion y nombre de archivo nomas no por la fecha. La termino para mañana.

Abrazo

**Comment by LeandroBraier** [comment]
Sip, es News de Noviembre. Ahi ya tenés también los links de las notas en
el doc mismo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-26 17:30 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Lea cuando puedas pasame las imagenes por separado por favor.

**Comment by LeandroBraier** [comment]
Te las paso por acá:

![445](https://cloud.githubusercontent.com/assets/6719872/10757568/a70c9ffa-7c8a-11e5-8799-52a0a386161c.jpg)

![revestimiento-de-paredes-interiores-estante-curvado](https://cloud.githubusercontent.com/assets/6719872/10757578/b0b975a0-7c8a-11e5-8a4c-6547103d9816.jpg)

![cayc](https://cloud.githubusercontent.com/assets/6719872/10757584/b70eb0aa-7c8a-11e5-8846-2f33e91cac76.jpeg)

![logo-ok-club-colocadores-final-def](https://cloud.githubusercontent.com/assets/6719872/10757602/cf9b87b0-7c8a-11e5-8342-f4cb61b54703.png)

http://www.parexklaukol.com.ar/media/wysiwyg/Noticias-AR/PAREX_Decoflex_REN_AcrilicoTexturado.png

abrazo

**Comment by braulio-evangelisti** [comment]
Gracias Lea

Acá va el link
http://parexklaukol.com.ar/_mailing/novedades-noviembre/novedades-noviembre.html

Abrazo

**Comment by LeandroBraier** [comment]
Muy bueno Brau! Solo te pido si podes que vuelvas a cropear las fotos para
que las dos grandes queden del mismo tamaño.

**Comment by braulio-evangelisti** [comment]
Listo

**Comment by LeandroBraier** [comment]
Gracias BRau!!

Perfecto!
Envio al cliente y te aviso.

abrazo
