### ISSUE TITLE
Bug en Guía de Corralones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#201]
@mkreyness cuando busco por nombre de corralón de entrada (por ejemplo "Lo Bruno") sino tocar ningun otro seteo ni el autogps, no me muestra nada.

Usando el nombre de corralón y sin seleccionar lugar igual debería dar el resultado, verdad?

**Comment by mkreyness** [comment]
Ya no me acuerdo mucho, creo que todas las busquedas son en ALGUN contexto de lugar.
Viene una lista del lugar y dentro de eso filtro por nombre.
Me fijo cuando vuelva de DelViento.

**Comment by mkreyness** [comment]
La culpa la tenia un corralon sin coordenadas, que hacia pinchar todo.
Ya puse un filtro para que ignore las que no tienen coordenadas, si total no sabria donde ubicarlo en el mapa.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-26 22:20 GMT-03:00 mkreyness notifications@github.com:
