### ISSUE TITLE
Comunidad de Vendedores: Bajada de Excel unificado Vendedores + Actividades

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#202]
Puede ser para mañana aunque si está hoy genial.

abrazo

**Comment by mkreyness** [comment]
Listo, fijate, quedo como "Consulta de Actividades y Datos de Vendedores".

**Comment by LeandroBraier** [comment]
Gracias MK! Ahi lo descargué y me llegó vacio. Te fijás qué pasó?

abrazo

**Comment by mkreyness** [comment]
pero por pantalla aparecia ? Que rango pediste ?

**Comment by mkreyness** [comment]
recien pedi del 1-oct al 27-oct y me vino lo mas bien el excel.

**Comment by LeandroBraier** [comment]
Pedí el total. Es mucho?

**Comment by mkreyness** [comment]
Puede ser que el plugin que exporta a Excel tenga un limite, la verdad que no se.
Si pedis un rango mas corto probablemente ande, no tiene que ser un solo mes, pero capaz de a 3 meses ?

**Comment by LeandroBraier** [comment]
Gracias. Pruebo y te digo. Abrazo

**Comment by LeandroBraier** [comment]
Mirá, Marce. Intenté bajarme 3 meses juntos y después 1 mes y siempre que lo quiero abrir al excel me aparece este mensaje:

<img width="621" alt="captura de pantalla 2015-10-27 a las 13 25 46" src="https://cloud.githubusercontent.com/assets/6719872/10764460/1772741e-7cad-11e5-8f52-2704a6ee814c.png">

**Comment by mkreyness** [comment]
Entonces no es que no te baja, sino que el Excel Mac no lo puede abrir.
Yo no tengo control sobre los formatos, no se exactamente que hace el plugin, pero el Excel de PC los abre bien.
Si intentas abrirlo con Google Docs ?

**Comment by LeandroBraier** [comment]
A ver, intento.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-27 14:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Ahi con Google Docs lo pude abrir. GRacias!!

abrazo
