### ISSUE TITLE
Torneo de Potenciados: Modificación en Versión Representantes Comerciales o RCD

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#203]
@mkreyness me piden que en la tabla de abajo, el RCD vea TODOS sus corralones, no sólo un máximo de 20.

Decime si conviene paginar o directamente hacer un thread infinito, pero me dicen que tiene que estar.

abrazo

**Comment by mkreyness** [comment]
no hay un maximo de 20, lo que hay son los primeros 5 de cada categoria, lo cual podria dar como mucho 30.
No hay problema en poner todos, pero lo dejo asi ordenado y separado como esta por categoria, no ?

**Comment by LeandroBraier** [comment]
Si, dejalos ordenado por puesto y separado como está por categoría. Gracias
MK!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo.

**Comment by LeandroBraier** [comment]
Gracias MK!
