### ISSUE TITLE
Comunidad de Vendedores: Registrar hora de las actividades

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#205]
@mkreyness así como tomamos la fecha en que se realiza la actividad en la Comunidad, podemos registrar la hora también?

**Comment by mkreyness** [comment]
Se puede, pero no retroactivo.

**Comment by LeandroBraier** [comment]
Me imagino. Le advertí de eso al cliente. Empecemos entonces porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo, ya se esta empezando a guardar. La agregue en la consulta "completa", la que incluye datos de vendedor. Despues la agrego en el resto de lugares

**Comment by LeandroBraier** [comment]
Perfecto, gracias!
