### ISSUE TITLE
Actualizar hojas de seguridad Lanko y Klaukol en la Web de ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#206]
@braulio-evangelisti te paso nuevas hojas de seguridad para reemplazar en la web. 

https://www.wetransfer.com/downloads/fd301938c56e5f8ce7277ba8965dcca220151028182250/7e32ca

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea

Puede ser que esto se actualice desde el CMS? Si es asi nunca tuve acceso.

Abrazo

**Comment by LeandroBraier** [comment]
Tenés razón. LO puedo actualizar yo mismo. Perdón!

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA me decía Braulio que puedo subir yo al CMS estas hojas de seguridad pero en realidad no. Me pide directamente la URL. Por favor les paso aquí las hojas de seguridad de Klaukol y Lanko para que mañana las suban.

KLAUKOL

[Hoja de seguridad Refractario.pdf](https://github.com/LeandroBraier/Klaukol/files/26673/Hoja.de.seguridad.Refractario.pdf)
[Hoja de seguridad Pla-k.pdf](https://github.com/LeandroBraier/Klaukol/files/26672/Hoja.de.seguridad.Pla-k.pdf)
[Hoja de seguridad Pastina Junta Ancha.pdf](https://github.com/LeandroBraier/Klaukol/files/26674/Hoja.de.seguridad.Pastina.Junta.Ancha.pdf)
[Hoja de seguridad Impermeable Potenciado.pdf](https://github.com/LeandroBraier/Klaukol/files/26675/Hoja.de.seguridad.Impermeable.Potenciado.pdf)
[Hoja de seguridad Grandes Piezas.pdf](https://github.com/LeandroBraier/Klaukol/files/26676/Hoja.de.seguridad.Grandes.Piezas.pdf)
[Hoja de seguridad Flex.pdf](https://github.com/LeandroBraier/Klaukol/files/26677/Hoja.de.seguridad.Flex.pdf)
[Hoja de seguridad Ecostik.pdf](https://github.com/LeandroBraier/Klaukol/files/26678/Hoja.de.seguridad.Ecostik.pdf)
[Hoja de seguridad Blanco Pro.pdf](https://github.com/LeandroBraier/Klaukol/files/26679/Hoja.de.seguridad.Blanco.Pro.pdf)

LANKO

[Hoja de seguridad LANKO TECHOS 180.pdf](https://github.com/LeandroBraier/Klaukol/files/26681/Hoja.de.seguridad.LANKO.TECHOS.180.pdf)
[Hoja de seguridad LANKO PUENTE DE ADHERENCIA 162.pdf](https://github.com/LeandroBraier/Klaukol/files/26682/Hoja.de.seguridad.LANKO.PUENTE.DE.ADHERENCIA.162.pdf)
[Hoja de seguridad LANKO MORTERO 901.pdf](https://github.com/LeandroBraier/Klaukol/files/26683/Hoja.de.seguridad.LANKO.MORTERO.901.pdf)
[Hoja de seguridad LANKO IMPERFLEX 228 B.pdf](https://github.com/LeandroBraier/Klaukol/files/26684/Hoja.de.seguridad.LANKO.IMPERFLEX.228.B.pdf)
[Hoja de seguridad LANKO IMPERFLEX 228 A.pdf](https://github.com/LeandroBraier/Klaukol/files/26685/Hoja.de.seguridad.LANKO.IMPERFLEX.228.A.pdf)
[Hoja de seguridad LANKO IMPER 222.pdf](https://github.com/LeandroBraier/Klaukol/files/26686/Hoja.de.seguridad.LANKO.IMPER.222.pdf)
[Hoja de seguridad LANKO HIDROFUGO 322.pdf](https://github.com/LeandroBraier/Klaukol/files/26687/Hoja.de.seguridad.LANKO.HIDROFUGO.322.pdf)
[Hoja de seguridad LANKO DURAFLEX 453.pdf](https://github.com/LeandroBraier/Klaukol/files/26688/Hoja.de.seguridad.LANKO.DURAFLEX.453.pdf)
[Hoja de seguridad LANKO ADITIVO 751.pdf](https://github.com/LeandroBraier/Klaukol/files/26689/Hoja.de.seguridad.LANKO.ADITIVO.751.pdf)

abrazo

**Comment by mkreyness** [comment]
esto va como documentos adjuntos a los productos, no ?
EL CMS no puede hacer su propio upload porque los URLs viejos estaban distribuidos en multiples carpetas y no hay como representar eso.
POr ejemplo del KIP tienen un URL asi:

klaukol-impermeable-potenciado/img/ficha-tecnica-klaukol-impermeable-potenciado.pdf

o sea en una carpeta especifica del producto, dentro de eso img, y dentro de eso un pdf.
Si los subimos todos a la misma carpeta seria mas facil pegar en todos lados un URL uniforme, por ejemplo:

hojas-de-seguridad/[archivo]

lo que no me gusta es que los nombres de estos archivos no son safe y van a tener problema tarde o temprano.
Si podes renombrarlos con guiones donde hay blancos (tal vez sacarle la parte "hoja de seguridad" porque eso seria ya el nombre de la carpeta, y pasarmelos todos juntos en un zip, yo lo subo todo a esa carpeta "hoja-de-seguridad" y vos depues podes agregar los renglones de adjuntos a cada producto, poniendo esos mismos nombres safe, por ej

hoja-de-seguridad/Refractario.pdf

**Comment by LeandroBraier** [comment]
Entiendo MK!

En un ratito te paso el zip

abrazo

**Comment by LeandroBraier** [comment]
Aqui va el ZIP MK!

https://www.wetransfer.com/downloads/d0d9c2692602eb124a1cebecfc9bc7e620151104122021/f70c44

abrazo

**Comment by mkreyness** [comment]
ya esta todo subido en

http://www.parexklaukol.com.ar/hojas-de-seguridad

Lo unico que tenes que hacer es cambiar o agregar en la parte de documentos de cada producto los URLs correspondientes, que siempre son:

`hojas-de-seguridad/<archivo.pdf>`

Asi, sin nada ante de "hojas", para cada archivo que me pasaste.
Proba con uno si queres y verificamos.

**Comment by LeandroBraier** [comment]
Parece que no funciona. Probé el de refractario y me lleva acá:

http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar/hojas-de-seguridad/HS-Klaukol-Refractario.pdf

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-04 9:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ah, le esta forzando entonces ese path delante, bueno muevo la carpeta ahi entonces y listo.

**Comment by mkreyness** [comment]
Fijate ahora que movi toda la carpeta a ese lugar, anda bien.

**Comment by LeandroBraier** [comment]
Ahora si MK! Gracias!

Subo todas y te confirmo si funciona todo OK.

abrazo
