### ISSUE TITLE
Actualización de base de distribuidores Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#207]
@mkreyness tengo un excel con la base de distribuidores actualizada. Decime si se puede actualizar los datos de ese mapa o es un quilombo.

Te la adjunto acá.

[Sucursales REX (Oct 2015).xlsx](https://github.com/LeandroBraier/Klaukol/files/22768/Sucursales.REX.Oct.2015.xlsx)

abrazo

**Comment by mkreyness** [comment]
Kilombo no es, porque la base es mia y la puedo cambiar a gusto.
El asunto es que estoy contrarreloj con lo de DelViento que hoy MS me cambió varios tantos (para mejor) pero es urgente implementarlos.

**Comment by LeandroBraier** [comment]
Entiendo. Y para mañana a última o el viernes a primera podrías?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 19:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
si, en algun hueco lo hago, no te preocupes.

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
COnsulta @mkreyness : el link de la tienda online que aparece arriba de todo y pertenece a Pinturerías REX, se puede incluir en el apartadito de Pinturerías Rex para que la gente clickee dentro del mapa?

**Comment by mkreyness** [comment]
No habia mirado el contenido, esto es para AGREGAR a la lista de distribuidores, no ?
No puede ser "LA" lista de distribuidores, son muy pocos. O ahora es asi ?

No entiendo a que llamas "el apartadito de Pinturerias Rex", a lo que se despliega cuando clickean en el mapa, que EN EL CASO de ser una de estas aparezca ese link fijo y si VUELVEN a clickear les abra una ventana aparte ?

**Comment by LeandroBraier** [comment]
1) Claro, en realidad es para actualizar la lista de distribuidores. Si vos
me exportás la lista completa del sitio yo te actualizo estos datos y te la
vuelvo a pasar actualizada, no hay problema. Asi no tenés que hacerlo vos.

2) Respecto del apartadito me refiero sí a lo que vos decís, lo que se
despliega al clickear en el mapa. Y tal como decís lo que preguntan si se
puede es que dentro de eso aparezca el link fijo y al clickear lleve a una
ventana aparte. Se puede eso?

2015-10-29 1:21 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
1) Si son nuevos es mas lio a la larga, lo mejor seria que los usuarios entraran por el CMS y cargaran/modificaran lo que quisieran en la parte que dice "Distribuidores". No tengo claro si estos son nuevos o son cambios.
En definitiva, si son nuevos, lo hago yo, el excel no te aporta nada. 
Si son cambios, podes exportar el Excel desde el CMS y pasarmelo cambiado si queres.

2) Si, de todos modos para eso habria que agregar el dato de link a toda la tabla de distribuidores, y el que lo tenga que aparezca y el que no, no.

**Comment by LeandroBraier** [comment]
1) Perfecto. Lo actualizo yo en el CMS y listo, no?

2) Entiendo. Esto te llevaría muchas horas?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-29 9:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
1) si queres, mejor. Y lo mejor seria que lo haga la propia gente de
Klaukol.
2) No, 2h como mucho.

El 29/10/2015 a las 9:16, LeandroBraier
  escribió:

1) Perfecto. Lo actualizo yo en el CMS y listo, no?

  2) Entiendo. Esto te llevaría muchas horas?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-10-29 9:07 GMT-03:00 mkreyness
  <notifications@github.com>:

  > 1) Si son nuevos es mas lio a la larga, lo mejor seria que
  los usuarios
  > entraran por el CMS y cargaran/modificaran lo que quisieran
  en la parte que
  > dice "Distribuidores". No tengo claro si estos son nuevos o
  son cambios.
  > En definitiva, si son nuevos, lo hago yo, el excel no te
  aporta nada.
  > Si son cambios, podes exportar el Excel desde el CMS y
  pasarmelo cambiado
  > si queres.
  >
  > 2) Si, de todos modos para eso habria que agregar el dato de
  link a toda
  > la tabla de distribuidores, y el que lo tenga que aparezca y
  el que no, no.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/207#issuecomment-152158757
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
2) Perfecto, MK. Hacelo porfa sin apuro para el lunes tranqui.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-29 9:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, no se si ya actualizaste en el CMS pero a todas las Pinturerias Rex les puse el URL y ya se despliega en el mapa (y al clickear va a solapa aparte).
Se puede aplicar a todos los distribuidores que haga falta, el dato esta en el CMS.

**Comment by LeandroBraier** [comment]
Gracias MK!

Actualicé algunas pero no todas aún, así que ahora le sumo. Solo va a aparecer la URL o va a decir "COMPRAS ONLINE" y debajo la URL?

**Comment by mkreyness** [comment]
No sabia que tuviera que decir eso, si queres se lo agrego.

**Comment by LeandroBraier** [comment]
Dale, si se puede mejor. Para que se entienda que pueden comprar el
material en ese link y no sólo conocer más información. Ese link lleva a
"_blank" verdad? Eso sería importante también.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si, lleva a blank.
Ahora le agrego eso.

**Comment by mkreyness** [comment]
listo. Lo puse como parte del link (o sea, se puede clickear tanto en el URL como en la frase "COMPRAS ONLINE").

**Comment by LeandroBraier** [comment]
Excelente MK!! Mil gracias!

abrazo
