### ISSUE TITLE
Chat Benteveo no funciona

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#208]
@mkreyness recibimos consultas por chat de Benteveo y no podemos responderlas.

Teóricamente al responder a robotchat@benteveo.tv debía llegar el mensaje al chat verdad?

Pero no está funcionando.

**Comment by mkreyness** [comment]
Me parece que cuando migramos el conjunto de casillas del dominio benteveo.tv nadie se acordo de migrar esta...

**Comment by mkreyness** [comment]
Tal cual. Ahi la cree.
Prueben de nuevo.

**Comment by LeandroBraier** [comment]
Gracias MK! Probé y no me apareció la respuesta. Había que responder desde
un mail en particular no?

Tenés ahí como debería ser? Quizá estamos haciendo algo mal.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Lo unico que importa es escribir a robotchat@benteveo.tv

Por ejemplo ahora veo que llego un mail a esa casilla que dice asi:

CHAT con Leandro (#166/1)

eso esta bien, probablemente el problema este en algo de la pagina.
Voy a probar de mandar algo yo como usuario y veo con debugger.

**Comment by mkreyness** [comment]
No veo nada mal, salvo la logica: si en 1 minuto no contestaste, manda esa respuesta por default.
Si la gente no vuelve a tipear algo, aunque hayas respondido al minuto y medio, esa respuesta NO le va a llegar.
Contestame algo a las cosas que mande y avisame asi yo ahi escribo una mas y veo si ahi me llegan todas las respuestas juntas.

**Comment by LeandroBraier** [comment]
Entiendo, debe ser lo del minuto. El tema es que es poco tiempo un minuto.
Lo hablo con Eze para prolongarlo un poco más.

Igual pruebo una en tiempo real ahora a ver si llego a responderme.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 18:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
LO probé Marce y sigue sin funcionar en menos de 1 minuto. Creoq ue el tema
es otro. Seguro que se puede responder desde cualquier mail?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 19:08 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
Si, absolutamente se puede responder desde cualquier mail. Y tu respuesta me llego CUANDO YO VOLVI A ESCRIBIR, ese es el tema.

**Comment by mkreyness** [comment]
Lo subo a 5 minutos y probamos ?
La solucion seria que la pagina mientras esta viva se fije cada tanto si hay alguna respuesta, NO solo dentro del minuto de que el tipo escribio.

**Comment by LeandroBraier** [comment]
Exacto. Que el mensaje que aparece al minuto siga apareciendo, pero que
igual no inhabilite una respuesta nuestra posterior.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 19:15 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
bueno cuando me libere un poco de kilombos lo veo, hay que cambiar un poco la logica, pero mientras no queres que lo suba a esperar 5 min asi hay mas chance de que llegue una respuesta ?

**Comment by LeandroBraier** [comment]
Dale, por ahora hagamos eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-10-28 19:41 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
estoy viendo que en realidad eran 30 segundos, porque hacia un delay de 5 segundos y miraba 12 veces cada 2 segundos, un total de 29 y monedas.
Ahi le puse que mire 150 veces cada 2 segundos.

**Comment by LeandroBraier** [comment]
Gracias MK! Por ahora lo cerramos entonces.

abrazo
