### ISSUE TITLE
Club de Colocadores Responsive

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#209]
@FAAREIA y @mkreyness el cliente me pidió volver atrás y despublicar porque el sitio no está responsive. Volvamos a la versión de registro solamente.

Es cierto, el slideshow no se adapta, el footer tampoco y habría que ver más en detalle.

Por lo pronto vuelvan a despublicarlo por favor. Mañana lo hablamos para avancemos en la versión responsive.

abrazo

**Comment by mkreyness** [comment]
yo ya repuse lo anterior, cualquier cosa para revisar lo que no anda bien hay que hacerlo entrando por http://www.parexklaukol.com.ar/colo/

**Comment by LeandroBraier** [comment]
Gracias MK!!

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Por favor hoy demosle prioridad a este tema y dejemoslo responsive lo antes posible.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA !

Te cuento, el cliente nos quiere volver locos, pero te cuento: no lo va a lograr. 

Hablé varias horas con ellos el viernes y quedé que hoy te pasaba estos cambios y vos me confirmabas si llegamos a tenerlos impactadas para el miércoles. Yo modulé los pedidos para que pudiéramos llegar, pero de todas formas confirmame para más tranquilidad.

HOME
1. ~~Modificar TUS COMPRAS VALEN por "TU TRABAJO VALE"~~
2. Quitar sección Cómo Participo y botón de CANJEÁ TUS COMPRAS por un botón grande que diga: "REGISTRATE EN EL CLUB HACIENDO CLIC ACÁ". ~~El canje de compras quedaría totalmente afuera del Club de Colocadores por el momento. Totalmente. Dejalo totalmente inlinkeable y quitalo de todos los lados donde aparezca (por ejemplo, en la cajita de MI PERFIL dice "Mis canjes", eso vuela; también el box de productos a canjear que aparece a la derecha en distintas páginas también.~~
3. ~~La sección de Herramientas debe estar arriba de los videos.~~
   ~~Su título cambia a: "MEJORÁ TU TRABAJO CON KLAUKOL"~~
   ~~En lugar de "TARJETAS PERSONALES" que diga: "IMPRIMÍ TU TARJETA PERSONAL"~~
   ~~En lugar de "PRESUPUESTO ONLINE"  que diga "ARMÁ TUS PRESUPUESTOS"~~
4. ~~Cambiar "Cuánto sabés" por "Demostrá todo lo que sabés"~~
5. Agregar una sección igual a Novedades, que funcione igual también en el CMS, pero que diga "Conocé los productos Klaukol" y tenga un listado completo de los productos de Klaukol. Si hay que cargarlos uno por uno los cargo yo, no hay problema. La idea es que lleve a la página de cada producto en la web.

~~PÁGINA PRESUPUESTO~~
1. ~~En lugar del título PRESUPUESTO ONLINE poner "ARMÁ TUS PRESUPUESTO AQUÍ"~~
2. ~~Debajo un párrafo explicativo: "Dale la mejor imagen a tus presupuestos! Klaukol te ofrece esta herramienta para que puedas imprimir y presentar tus presupuestos a tus clientes de la mejor manera. Una herramienta mas para que sigas potenciando tu trabajo!"~~
3. ~~El botón de IMPRIMIR que esté rojo todo el tiempo mejor, así se ve más~~

~~PÁGINA TARJETA PERSONAL~~
1. ~~Agregar párrafo explicativo que diga: "Esta herramienta va a hacer que tus clientes te vean más profesional y puedan tener a mano tus datos. Un colocador potenciado nunca debe salir sin sus tarjetas personales."~~

~~SECCIÓN CUÁNTO SABÉS~~
1. ~~Cambiar título a "DEMOSTRÁ TODO LO QUE SABÉS" y agregar párrafo explicativo que diga: "Ponemos a prueba tus conocimientos. Mirá el video y demostrá cuanto sabes de cada uno de los tipos de colocación que hacés día a día.~~
2. ~~Al final de la Trivia, en el botón que dice "Seguí conociendo cuánto sabés" que diga "Seguí sumando puntos demostrando cuánto sabés"~~

En principio serían estos 11 puntos. Por favor confirmame vos y @mkreyness si llegamos a tenerlo entregable el miércoles al mediodía. Si no llegamos me avisás y negociamos con qué si y con qué no llegamos.

Espero tu respuesta.

abrazo

**Comment by FAAREIA** [comment]
Yo diría que para el jueves estaría bien, llegamos tranquilos
@mkreyness ?

**Comment by LeandroBraier** [comment]
El problema es que TIENE que ser para el miércoles al mediodía SI O SI.

De última decime hasta qué punto llegás para el miércoles al mediodía y con
qué no, para negociarlo. Si solo lo de MK queda para el jueves eso está OK.

**Comment by mkreyness** [comment]
1) @FAAREIA por favor modifica directo sobre los templates de /colo, asi no tengo que ponerme a rehacer todo
2) Si la seccion nueva es una replica (a nivel contenido) de lo que seria la pagina de productos de Klaukol normal, no deberia llevar mucho tiempo. Trata al maquetarla de dejarle ya las variables puestas asi no tengo que ponerme a investigar.

Bajo esas condiciones, y si no hay ningun otro incendio que apagar, lo podria hacer el miercoles a la noche.
Yo diria de todos modos si podes EMPEZAR por esta parte de la seccion nueva, mientras vos seguis con el resto yo puedo ir avanzando.

**Comment by LeandroBraier** [comment]
Excelente MK!

Punto 2) La sección nueva es una réplica de otra sección del Club de
COlocadores: la de novedades. Funciona exactamente igual, solo que en vez
de mostrar artículos de "/novedades.html" muestra artículos de
"/productos-klaukol.html/"

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-02 11:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Bueno, el miércoles. Yo creo que llegamos bien igual.

Con respecto a la nueva sección y para dejarlo bien claro:
- En el menú va a tener de título "Productos Klaukol"
- En la sección misma, el titútlo que va a figurar es "Conocé los productos Klaukol"
- Va a ser identica a Novedades en cuanto a estructura, foto a la izquierda y título, bajada y "ver mas" a la derecha
- El link del producto va a llevar al producto que esta en http://parexklaukol.com.ar/ , NO va a ser una página interna del Club

Confirmar si es asi Lea

**Comment by LeandroBraier** [comment]
Tal cual Fede. Es así.  Lleva en -blank a la pagina del producto en la web
oficial.

**Comment by FAAREIA** [comment]
Ahi actualicé el post tuyo lea, tachando lo hecho.
@mkreyness estaría bueno implementar lo del <head> que habíamos hablado asi se actualiza solo el CSS sin hacer refresh.

Abrazo

**Comment by mkreyness** [comment]
lo se, pero si vas a estar modificando los templates no podemos tocar ambos a la vez.

**Comment by FAAREIA** [comment]
Yo ya terminé por hoy, replicalo tranqui

**Comment by mkreyness** [comment]
si el "por hoy" incluye la noche, lo hare a la noche, porque el dia lo tengo bastante complicadito ya.

**Comment by FAAREIA** [comment]
Si marce, olvidate. Recien mañana a las 8 vuelvo a ponerme

**Comment by mkreyness** [comment]
y al final no tuve cuando. Avisame cuando "dejes" hoy a ver si ya puedo intervenir.

**Comment by LeandroBraier** [comment]
Chicos, no olviden: mañana al mediodía lo necesitamos aplicado a esto.

Hoy cambié las imágenes de los 2 slides del slideshow y me volvieron a dar error como la otra vez. Por favor revisenlo.

abrazo

**Comment by LeandroBraier** [comment]
Pasa lo mismo con cualquier imagen subida via CMS. 

<img width="678" alt="captura de pantalla 2015-11-03 a las 9 41 48 p m" src="https://cloud.githubusercontent.com/assets/6719872/10925966/98043c88-8271-11e5-9ddf-f1c19590fb88.png">

Debe ser el proceso que están haciendo uds, no se preocupen. Simplemente fijense que funcione mañana para la entrega.

abrazo

**Comment by LeandroBraier** [comment]
En cada tema sea solo video o incluya trivia, no olviden maquetar para que si hay un link al producto aparezca el botón.

abrazo

**Comment by mkreyness** [comment]
ya te copie las imagenes de colocadores a colo y se ven.
El CMS actua sobre el SISTEMA EN PRODUCCION (colocadores). Lo que hagas ahi no se puede reflejar en el sistema "EN DESAROLLO" (colo), porque es todo otro juego de carpetas. Me tenes que avisar para que lo copie.
Una vez que el que esta "EN DESARROLLO" pase a estar "EN PRODUCCION", ahi si lo que hagas en el CMS se va a reflejar.

**Comment by mkreyness** [comment]
ya esta la pagina de productos, faltaria @FAAREIA que lo enganches en el encabezado

`/cgi-bin/productoscolo.pl?usuario=<!--usuario-->&clave=<!--clave-->`

**Comment by mkreyness** [comment]
@FAAREIA ya estan todos los templates (en uso en colo) con el  `<!--inc-head-->`
y los headers estan en colo/headT.html

**Comment by LeandroBraier** [comment]
Gracias MK! Me había olvidado de eso.

Abrazo

**Comment by FAAREIA** [comment]
No estan, cuando este funcionando el include ya lo meto en todos los templates

**Comment by FAAREIA** [comment]
Ahi subi lo último que faltaba, habría que definir:
- La imagen de fondo que va en el boton de registrarse.
- El usuario logueado qué ve? Porque ese banner no le sirve.

**Comment by LeandroBraier** [comment]
Fede: ¿en donde veo los cambios? El botón lo veo y el "Tu trabajo vale" también, pero la sección de productos por ejemplo no la veo.

Te respondo las preguntas:
. La imagen de fondo que va en el botón está bien así por ahora. 
. El usuario logeado no debería ver ese botón, directamente ve las herramientas abajo y en el slideshow debería ver otra cosa. Habría que implementar en el CMS algo como lo que hicimos en el Torneo de Potenciados, que cada categoría de usuario ve un slideshow diferente. Llegamos con eso @mkreyness ? Te lo iba a pedir y se me pasó.

**Comment by mkreyness** [comment]
Y cuales son las "categorias de usuario" ?

**Comment by LeandroBraier** [comment]
En el caso de Club de Colocadores serían solo dos: registrado y no
registrado (es decir, sin logeo).

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Productos todavía no lo puse en el menú porque marce no confirmó que ya estaba listo. Más allá de eso, también habria que activarla cuando esten los productos cargados.

**Comment by LeandroBraier** [comment]
Entiendo. Avisenme nomás cuando puedo cargar los productos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-04 11:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya esta todo, estan cargados los productos =O

**Comment by LeandroBraier** [comment]
Fede, donde lo puedo ver a esto? Sigo sin ver la sección de productos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-04 14:27 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
tenes que loggearte con un usuario (siempre en /colo) y te va a aparecer al lado del menu "herramientas".

Lo que veo es que otra vez no se ven los slides, los cambiaste ? Avisame siempre mientras estemos en desarrollo asi los copio de la carpeta en produccion (la que accede el CMS) a la de desarrollo (la que accede /colo).

**Comment by LeandroBraier** [comment]
Los cambié ayer a la noche cuando les escribí por github. Porfa que se vean. No solo los slides, cargué videos nuevos con thumbnails que no se ven.

Ahí vi los productos y vi que la imagen de muchos productos no tiene trasparencia. Eso lo puedo cambiar yo desde el CMS no?

Otro tema es que los Productos no aparecen en la home. Necesito que aparezcan igual que las novedades, es decir, en la home también, debajo de últimas novedades.

El Cómo funciona dejemoslo abajo de todo, es probable que lo volemos pero no tengo confirmación del cliente. Cuando le muestra el Club terminado le consulto.

**Comment by mkreyness** [comment]
Ok, las copio en un ratito, lo tengo a MS en el telefono desde la heladeria con cosas.
Para que aparezcan en la home hay que maquetar eso, que yo sepa no esta.
@FAAREIA lo copio directamente de como es el de novedades y listo ?

**Comment by FAAREIA** [comment]
Si marce, copiate el section entero de ID "ultimas-novedades" y listo

**Comment by mkreyness** [comment]
Ahi lo hice pero queda un poco pegoteado, fijate que haya que arreglarle /templates/colo/mainT.html

@LeandroBraier pongo entonces una marquita en algun lado de los productos, como hice con las novedades, que diga cuales son los que van a la home de colocadores ? Le puse los 2 ultimos que haya por ahora.

**Comment by LeandroBraier** [comment]
@mkreyness si, ponele la marquita porfa. También en el slideshow. Avisame cuando esté así puedo seleccionar qué ve el usuario registrado y qué el no registrado ahi también.

Más allá de eso, va feedback:
1. yo había subido 2 slides al CMS y se ve uno solo. Es importante que se vean los dos y la versión que vamos a mostrar para aprobación es /colo/ asi que necesitaría que la suban también porfa.
2. Lo de pegoteado es la sección de productos en la home, no? No se puede solucionar poniendo un <br/> o algo asi?
3. En la foto de perfil de tu usuario falso, MK, necesito que pongas una fotito. Te paso una para que reemplaces la del auto que pusiste:

<img width="201" alt="captura de pantalla 2015-11-04 a las 7 38 51 p m" src="https://cloud.githubusercontent.com/assets/6719872/10953950/8c2e9076-8329-11e5-842d-49f3fd623f49.png">
1. Estoy viendo que los thumbnails de los productos no los puedo cambiar yo, no? Cómo hacemos? Queda mal ese recuadro blanco de fondo en algunos y en otros no.

Si me las pasás todas en un zip yo las corrijo y te las vuelvo a enviar todas en un zip con los mismos nombres.

abrazo

**Comment by mkreyness** [comment]
Ah que linda cara me elegiste... Entonces me voy a cambiar el nombre tambien.
Los thumbnails de los productos son los que estan en lo de klaukol oficial, cualquier cambio que haga afecta tambien ahi, no importa ?

**Comment by LeandroBraier** [comment]
No importa, es solo quitarles el fondo blanco y ponerlo transparente, lo cual no va a afectar la web oficial porque el fondo es blanco igualmente.

**Comment by mkreyness** [comment]
Ok, ahora te armo el zip

**Comment by mkreyness** [comment]
descargalo directamente de aca
http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar//media/catalog/product/cache/1/small_image/150x/imagenes.zip
lamentablemente esta organizado de una forma espantosa, todo repartido en carpetas, pero es preferible que los modifiques dentro de esta estructura y me lo rezippees asi, asi cuando los bajo estamos seguros de que cada cosa se reemplaza en el lugar que va.

**Comment by LeandroBraier** [comment]
Ok, no problem. Ahora te lo mando. Ya subí nuevos 2 slides al CMS versión para registrados, para que lo tengas en cuenta.

abrazo

**Comment by mkreyness** [comment]
Con eso de "Version para registrados" me estas contestando una pregunta que te hice hace unas horas sobre las categorias de usuarios ?
No vi si ya me lo habias contestado.
Entonces hay que poner una marca de si el video es para registrados/no registrados/ambos ?

**Comment by LeandroBraier** [comment]
Sip, exacto. Te lo había contestado y además lo recordé en el último thread mio de 4 puntos, por las dudas. 

En cuanto a imágenes estoy viendo que puedo mantener los nombres pero para que funcione la transparencia voy a tener que convertir los jpg a png. Eso te complica?

**Comment by mkreyness** [comment]
Habria que actualizar los nombres de c/u en la base de datos, un plomo.
Lo que puedo hacer es dejarlo como esta para Klaukol, agregar estos png que vos me pases y para colo tomar lo que diga el CMS y cambiarle el ".jpg" por ".png" asi lee el transparente, y no afectamos en nada el sitio general.

**Comment by LeandroBraier** [comment]
Excelente solución MK!! Sos un genio!!! jaja Así haremos.

**Comment by mkreyness** [comment]
ya te agregue un "Tipo de Usuario" en los slides, por ahora no le da bola pero si queres anda marcando cuales son cuales.
Ya copie los nuevos que cargaste.

**Comment by LeandroBraier** [comment]
Hecho MK! Gracias!

**Comment by LeandroBraier** [comment]
MK, te paso por mail las imágenes.

**Comment by mkreyness** [comment]
Listo ya estan las imagenes subidas e "interpretadas" on the fly en /colo
Me faltaria el tema de poner un tilde para saber cuales productos corresponde poner en la home.
O preferis que ponga 2 distintos al azar cada vez ? Va a ser mucho mejor que poner siempre los mismos dos.

**Comment by LeandroBraier** [comment]
Perdón por la colgada. Por ahora poné el tilde y yo los selecciono porfa. Le propongo al cliente lo de mostrarlos al azar, me parece bien pero que lo aprueben.

abrazo

**Comment by LeandroBraier** [comment]
Por otra parte:
1. Sigo viendo 1 solo slide
2. Productos sigue pegoteado
3. Algunas imágenes no lucen bien, pero eso lo podemos cambiar mañana no? No se nota tanto la verdad.

1 y 2 lo podrás dejar resuelto hoy @mkreyness ? Así mañana bien temprano puedo mandar el Club listo.

**Comment by mkreyness** [comment]
1. Cierto, no se por que pero igual eso lo voy a tocar todo ahora para que tome lo de tipo de usuario.
2. eso lo tiene que revisar Fede, yo la verdad no se como hacer porque es algo del CSS seguramente.
   Puedo hacer alguna chapuceada para zafar, pero igual mejor si el lo resuelve via CSS
3. No me doy cuenta.

**Comment by LeandroBraier** [comment]
Ok, Gracias MK!

Espero 1 de vos.

@FAAREIA porfa mañana tomá el punto 2, el espaciado arriba de "PRODUCTOS" en la home como prioridad a la mañana lo más temprano posible.

abrazo a los dos y gracias!

**Comment by mkreyness** [comment]
1. ya se por que es, no esta el javascript que hace la animacion. En los cambios de includes que necesitaba Fede se me fue algun renglon de mas. Ahora lo agrego.

**Comment by mkreyness** [comment]
Ya esta resuelto 1 y ya respeta los tipos de usuario.

**Comment by FAAREIA** [comment]
Ya esta resuelto el pt2. Estaría todo no?

**Comment by LeandroBraier** [comment]
Excelente MK y Fede! Gracias!

Lo único que no veo es la casilla en los productos para elegir si se
despliegan o no en el Club

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-05 8:09 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Si, anoche me caia de sueño. Ya esta, fijate. Marque los dos mas nuevos pero lo podes cambiar.

**Comment by LeandroBraier** [comment]
Gracias MK! Ahora sí.

@FAAREIA la barra del medio que dice REGISTRATE EN EL CLUB HACIENDO CLIC ACÁ no está responsive. Por favor resolvelo rápido.

Con esta presentación vemos si nos da el OK el cliente y ya pedimos lo que venga después en ticket aparte.

abrazo grande y gracias a los dos

**Comment by FAAREIA** [comment]
Ya esta responsivo

**Comment by LeandroBraier** [comment]
Gracias Fede!!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Tenemos el OK chicos!

@mkreyness porfa pasá a producción el sitio de Colocadores nomás.

Por favor chequeá antes que los slides y demás archivos del CMS se vean bien.

abrazo

**Comment by mkreyness** [comment]
listo, parece estar todo bien.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

Ya chequeé y está todo perfecto. Lo que me acabo de dar cuenta es de que hay que sacar del menú de arriba el link llamado "¿Dónde canjeo mis puntos?" Que en la versión no registrada se sigue viendo.

Podrás sacar eso nada más?

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA quizá es algo tuyo, no de MK

**Comment by mkreyness** [comment]
es de los dos, pero lo puedo tocar yo, ahora veo.

**Comment by mkreyness** [comment]
Ahi esta, ya no se ve en ninguna.

**Comment by LeandroBraier** [comment]
Genial, gracias MK!

@FAAREIA también necesitaríamos habilitar el link que lleva a Club de Colocadores en la web principal de ParexKlaukol apenas puedas.

abrazo

**Comment by LeandroBraier** [comment]
Gracias MK!!! Sos un genio!!

@FAAREIA apenas puedas habilitar ese link te lo agradezco.

abrazo grande y buen fin de semana para todos!

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! No te olvides de habilitar el logo del Club de Colocadores en la web de Parex porfa, así cierro este ticket.

abrazo

**Comment by FAAREIA** [comment]
Habilitado

**Comment by LeandroBraier** [comment]
Gracias Fede!!

abrazo grande
