### ISSUE TITLE
Programación en Sitio ParexKlaukol: Casa Interactiva y Calculador de Materiales

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#21]
Marce, necesito que backupees y reconstruyes en nuestro hosting los siguientes dos motores:

Casa Interactiva: 
http://www.parexklaukol.com.ar/casa-interactiva

Calculador de materiales (ParexKlaukol)
http://www.parexklaukol.com.ar/calculador

Fede hoy va a estar subiendo los backups que tiene de estos sitios al hosting Onyx de Klaukol, así que cuando los tengas backupeados podrías subirlos allí mismo y los probamos.

**Comment by mkreyness** [comment]
Veremos que puedo hacer, en realidad era Fede el que tenia un plugin que backupeaba. Lo agregas en este topic y le pregunto de donde bajarlo ?

**Comment by mkreyness** [comment]
Eso que mande recien en realidad lo tenia de antes y no habia salido.
Intento con el HTTTRACK que dije en el otro topico a ver que pasa.

**Comment by LeandroBraier** [comment]
Agregalo vos porfa. Hablen entre uds lo que necesiten. Te paso estas tareas para que le demos una mano a Fede que sino no va a llegar esta semana con todo.

**Comment by LeandroBraier** [comment]
Dale. Genial. Gracias.

**Comment by FAAREIA** [comment]
Buenas, el plugin se llama ScrapBook y es para firefox. Es gratarola.
Avisanos como te fue con el HTTTRACK y ahi lei lo de CFT, buenisimo si esta con otro proveedor.

**Comment by mkreyness** [comment]
```
Bien pero se fue de mambo y me estaba levantando todo un sitio
llamado "youtube.com" y algunos conexos.
Lo tuve que parar, porque me iba a quedar sin disco y no ibamos a
llegar en fecha.

Tengo mucho material (unos 250Mb comprimidos) para ir bajando al
servidor y de ahi podemos mas o menos recorrer y ver que funciona y
que no.
Seguro que lo que sean llamados a PHP no, pero en tu backup estaba
lleno de PHPs y los podemos llegar a buscar.

El 21/04/2015 a las 8:20, Federico
  Arena escribió:


  Buenas, el plugin se llama ScrapBook y es para firefox. Es
    gratarola.
    Avisanos como te fue con el HTTTRACK y ahi lei lo de CFT,
    buenisimo si esta con otro proveedor.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Joya, el server de benteveo.tv ya esta con 810MB de 1000MB, lo podrás subir a otro server eso? o sino pasarlo por wetransfer y vemos donde lo subimos.

**Comment by LeandroBraier** [comment]
Excelente noticia MK.

En lo que sea que los pueda ayudar me avisan.

Por ejemplo, cuando estén subidos los sitios al nuevo hosting, tal como los
backupearon, los puedo testear y marcar qué cosas faltan o no funcionan y
cuales de ellas son de versión 1.0 y cuales son para más adelante.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-21 8:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Usemos el Onyx de Klaukol, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-21 9:04 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
ah dale Me olvidé de ese!

**Comment by mkreyness** [comment]
```
Yo estoy bajando los backups mios ahi

El 21/04/2015 a las 9:05, Federico
  Arena escribió:


  ah dale Me olvidé de ese!
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
esto es lo que baje yo, todavia no me puse a recorrerlo pero de pinta pareceria estar, lo que no anda es justamente lo que deberia suceder al hacer el submit del calculador

http://72.52.188.248/_backup/revear
http://72.52.188.248/_backup/parexklaukol

**Comment by LeandroBraier** [comment]
Excelente MK!

Te paso a vos también el testing que hice del backup de Fede de Revear,
incluyendo referencia s a tu backup de ese mismo sitio también.

https://docs.google.com/presentation/d/1BumXn-WRYvtO3_Jd1GCsbo7TCIeKOyyGJgpdyogEFRA/edit#slide=id.g30311f1fa_0_51

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Estoy viendo el de ParexKLaukol y en un vistazo muy rápido creo que el que
hizo Fede está más completo. Pero les agradezco a los dos porque viendo
todo esto ya tengo más de la mitad de la tranquilidad que necesitaba.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-21 12:37 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
MK, cómo venís con el tema de este ticket (Casa Interactiva y Calculador de materiales)?

Tenemos posibilidad de tenerlo backupeado para el jueves? (Aunque no esté activo en el nuevo hosting, simplemente con toda la información segura a salvo en el hosting o en tu máquina)

**Comment by mkreyness** [comment]
Yo tengo backupeado todo lo backupeable, tanto en mi maquina como bajado en el servidor. Mas cosas no se pueden levantar, lo demas es aplicar los algoritmos que me dijiste modificando esas paginas. Estoy trabajando con el mapa de distribuidores que no me termina de andar, pero tener tengo todo lo necesario (incluyendo la base de distribuidores cargada en el mismo CMS de los corralones (diferenciando por marca).

**Comment by LeandroBraier** [comment]
Marce, estoy partiendo finalmente y no llegué a pasarte los criterios del calculador de materiales. Lo sí te confirme es que es un cruce de datos de las fichas técnicas de los productos. No sólo la tablita del rendimiento de cada uno según las distintas medidas de mosaico y absorción del material, sino también los tipos de soporte y tipo de obra en que se utiliza cada uno. 

Yo me capturé los nombres de las opcines de cada uno de los menú, pero supongo que eso vos lo pudiste chupar. Lo que faltaría es definir las variables de rendimimiento de cada uno. Eso lo vemos a la vuelta mia.

abrazo grande MK y gracias por todo. Cualquier cosa Eze ya está al tanto de todo el proceso.

**Comment by mkreyness** [comment]
```
Ok, buenas vacaciones.

El 27/04/2015 a las 7:40, LeandroBraier
  escribió:


  Marce, estoy partiendo finalmente y no llegué a pasarte los
    criterios del calculador de materiales. Lo sí te confirme es que
    es un cruce de datos de las fichas técnicas de los productos. No
    sólo la tablita del rendimiento de cada uno según las distintas
    medidas de mosaico y absorción del material, sino también los
    tipos de soporte y tipo de obra en que se utiliza cada uno. 
  Yo me capturé los nombres de las opcines de cada uno de los
    menú, pero supongo que eso vos lo pudiste chupar. Lo que
    faltaría es definir las variables de rendimimiento de cada uno.
    Eso lo vemos a la vuelta mia.
  abrazo grande MK y gracias por todo. Cualquier cosa Eze ya está
    al tanto de todo el proceso.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Marce, empiezo a reflotar estos temas de la versión 2.0, que son el próximo paso para nosotros en Klaukol.

Para cuando pueden estar listos y funcionando la Casa Interactiva y el Calculador de Materiales y cuántas horas te llevarían?

Necesitaríamos tener estos elementos de la versión 2.0  para la última semana de Junio máximo.

**Comment by mkreyness** [comment]
http://72.52.188.248/_backup/parexklaukol/casa-interactiva.html

La casa interactiva era todo en flash, si podemos dejarla tal cual y 
solo hacer que los links que trae (estan harcoded y no los puedo 
cambiar) lleven a las paginas nuevas de los productos no es tan grave.
El mayor problema para mi es que tal vez quieran AGREGAR productos o 
QUITAR productos de los que aparecen y ahi estamos recontrafritos.

El calculador de materiales es esto ?

http://72.52.188.248/_backup/parexklaukol/calculador.html

es lo mismo que el de Parex ?

**Comment by LeandroBraier** [comment]
CASA INTERACTIVA: Por ahora usemos ese Flash y listo. No nos pidieron que lo "rehagamos". Si me piden les digo que es un Flash y que es muy difícil cambiar productos, habría que reconstruyir el editable del flash y luego acomodar los errores que genere el programa de reconstrucción, etc. No te preocupes, MK, tenemos gente en el equipo que hace eso, no lo tendrías que hacer vos. Simplemente reutilizá ese flash y listo.

CALCULADOR: Es aquí donde va el Calculador, no en Parex. En Parex era otra cosa, fijate en ese ticket.

Respecto de este Calculador no logré decifrar la fórmula todavía. La puedo preguntar al cliente mañana y te la confirmo. Vayamos avanzando con la Casa Interactiva y los pendientes de Parex. Revear dejemoslo en 2do lugar. Si llegamos con Klaukol y Parex para fin de junio pero no con Revear no estamos tan mal.

abrazo

**Comment by mkreyness** [comment]
Ok. Lo que habria que hacer con la casa interactiva (que en realidad ya 
lo hiciste vos para verificar, pero no creo que hayas guardado la data) 
es poner a alguien a recorrer todos los links de productos que trae el 
flash en cada posible parte, y asociarlos (en 2 columnas de un excel por 
ejemplo) con los links correctos.
Eso me lo pasan y en 10 minutos lo sacamos andando.

**Comment by LeandroBraier** [comment]
Perfecto. Yo lo hago. Mañana te paso el excel nomás con Columna "Nombre de
producto" y "Link actual". Está bien así?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-10 19:21 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No es nombre, es el link, hay que hacer click (te va a dar error 404 por 
supuesto) pero necesito que me copien el link.

**Comment by LeandroBraier** [comment]
Ah ok. Entonces las dos columnas son:

"Link viejo"/ "Link actual"

mañana te lo paso

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-10 19:32 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Exacto, asi fuerzo que ese lugar inexistente apunte al correcto.

**Comment by LeandroBraier** [comment]
Perfecto. A la tardecita te paso el excel. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-11 15:38 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Tambien en esto tene en cuenta que Fede tiene que armar todo lo de 
alrededor de la casa, con esto en el medio:

<object width="980" height="470" 
data="media/wysiwyg/casa-interactiva.swf" 
type="application/x-shockwave-flash">
<param name="data" value="media/wysiwyg/casa-interactiva.swf">
<param name="src" value="media/wysiwyg/casa-interactiva.swf">
<param name="wmode" value="transparent">
</object>

**Comment by LeandroBraier** [comment]
Ok. Hagamos la parte dura primero, de programación, y después le pido a
Fede eso la semana que viene.

Ahora te paso la lista.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-11 16:48 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No hay nada que programar en la casa, solo son esos links que es
crear unos accesos directos en el server.

El 11/06/2015 a las 19:24,
  LeandroBraier escribió:

Ok. Hagamos la parte dura primero, de programación, y
  después le pido a
  Fede eso la semana que viene.

  Ahora te paso la lista.

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-11 16:48 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Tambien en esto tene en cuenta que Fede tiene que armar todo
  lo de
  > alrededor de la casa, con esto en el medio:
  >
  > <object width="980" height="470"
  > data="media/wysiwyg/casa-interactiva.swf"
  > type="application/x-shockwave-flash">
  > <param name="data"
  value="media/wysiwyg/casa-interactiva.swf">
  > <param name="src"
  value="media/wysiwyg/casa-interactiva.swf">
  > <param name="wmode" value="transparent">
  > </object>
  >
  >
  > On 11/06/2015 03:41 p.m., LeandroBraier wrote:
  > > Perfecto. A la tardecita te paso el excel. Gracias!
  > >
  > > Leandro Braier
  > > Producción Audiovisual & Social Media
  > > Benteveo Producciones <http://benteveo.tv>
  >
  > > Móvil 1158717399
  > >
  > > 2015-06-11 15:38 GMT-03:00 mkreyness
  <notifications@github.com>:
  > >
  > > > Exacto, asi fuerzo que ese lugar inexistente apunte
  al correcto.
  > > >
  > > > On 10/06/2015 08:02 p.m., LeandroBraier wrote:
  > > > > Ah ok. Entonces las dos columnas son:
  > > > >
  > > > > "Link viejo"/ "Link actual"
  > > > >
  > > > > mañana te lo paso
  > > > >
  > > > > abrazo
  > > > >
  > > > > Leandro Braier
  > > > > Producción Audiovisual & Social Media
  > > > > Benteveo Producciones
  <http://benteveo.tv>
  > > > > Móvil 1158717399
  > > > >
  > > > > 2015-06-10 19:32 GMT-03:00 mkreyness
  <notifications@github.com>:
  > > > >
  > > > > > No es nombre, es el link, hay que hacer
  click (te va a dar error
  > 404
  > > > por
  > > > > > supuesto) pero necesito que me copien el
  link.
  > > > > >
  > > > > > On 10/06/2015 07:25 p.m., LeandroBraier
  wrote:
  > > > > > > Perfecto. Yo lo hago. Mañana te paso
  el excel nomás con Columna
  > > > > "Nombre
  > > > > > de
  > > > > > > producto" y "Link actual". Está bien
  así?
  > > > > > >
  > > > > > > Leandro Braier
  > > > > > > Producción Audiovisual & Social
  Media
  > > > > > > Benteveo Producciones
  <http://benteveo.tv>
  > > > > >
  > > > > > > Móvil 1158717399
  > > > > > >
  > > > > > > 2015-06-10 19:21 GMT-03:00 mkreyness
  <notifications@github.com>:
  > > > > > >
  > > > > > > > Ok. Lo que habria que hacer con
  la casa interactiva (que en
  > > > > realidad ya
  > > > > > > > lo hiciste vos para verificar,
  pero no creo que hayas guardado
  > > > > la data)
  > > > > > > > es poner a alguien a recorrer
  todos los links de productos que
  > > > > trae el
  > > > > > > > flash en cada posible parte, y
  asociarlos (en 2 columnas de un
  > > > excel
  > > > > > por
  > > > > > > > ejemplo) con los links
  correctos.
  > > > > > > > Eso me lo pasan y en 10 minutos
  lo sacamos andando.
  > > > > > > >
  > > > > > > > On 10/06/2015 07:09 p.m.,
  LeandroBraier wrote:
  > > > > > > > >
  > > > > > > > > CASA INTERACTIVA: Por
  ahora usemos ese Flash y listo. No nos
  > > > > pidieron
  > > > > > > > > que lo "rehagamos". Si me
  piden les digo que es un Flash y
  > que
  > > > > es muy
  > > > > > > > > difícil cambiar productos,
  habría que reconstruyir el
  > editable
  > > > del
  > > > > > > > > flash y luego acomodar los
  errores que genere el programa de
  > > > > > > > > reconstrucción, etc. No te
  preocupes, MK, tenemos gente en el
  > > > > equipo
  > > > > > > > > que hace eso, no lo
  tendrías que hacer vos. Simplemente
  > > > > reutilizá ese
  > > > > > > > > flash y listo.
  > > > > > > > >
  > > > > > > > > CALCULADOR: Es aquí donde
  va el Calculador, no en Parex. En
  > > > > Parex era
  > > > > > > > > otra cosa, fijate en ese
  ticket.
  > > > > > > > >
  > > > > > > > > Respecto de este
  Calculador no logré decifrar la fórmula
  > > > > todavía. La
  > > > > > > > > puedo preguntar al cliente
  mañana y te la confirmo. Vayamos
  > > > > avanzando
  > > > > > > > > con la Casa Interactiva y
  los pendientes de Parex. Revear
  > > > > dejemoslo
  > > > > > en
  > > > > > > > > 2do lugar. Si llegamos con
  Klaukol y Parex para fin de junio
  > > > > pero no
  > > > > > > > > con Revear no estamos tan
  mal.
  > > > > > > > >
  > > > > > > > > abrazo
  > > > > > > > >
  > > > > > > > > —
  > > > > > > > > Reply to this email
  directly or view it on GitHub
  > > > > > > > > <
  > > > > > > >
  > > > > > >
  > > > > >
  > > > >
  > > >
  > >
  >
```

https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110932050
      > > > > > > > >.
      > > > > > > >
      > > > > > > > >
      > > > > > > >
      > > > > > > > —
      > > > > > > > Reply to this email directly or
      view it on GitHub
      > > > > > > >
      > > > > > > <
      > > > > >
      > > > >
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110935022>
      > > > > > > > .
      > > > > > > >
      > > > > > >
      > > > > > > —
      > > > > > > Reply to this email directly or view
      it on GitHub
      > > > > > > <
      > > > > >
      > > > >
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110935622
      > > > > > >.
      > > > > >
      > > > > > >
      > > > > >
      > > > > > —
      > > > > > Reply to this email directly or view it
      on GitHub
      > > > > >
      > > > > <
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110936863>
      > > > > > .
      > > > > >
      > > > >
      > > > > —
      > > > > Reply to this email directly or view it on
      GitHub
      > > > > <
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110941667
      > > > >.
      > > >
      > > > >
      > > >
      > > > —
      > > > Reply to this email directly or view it on GitHub
      > > >
      > > <
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111235153>
      > > > .
      > > >
      > >
      > > —
      > > Reply to this email directly or view it on GitHub
      > > <
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111235635
      > >.
      >
      > >
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111257488
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Ok, apenas puedo te paso el excel. Estoy medio a las corridas hoy, pero no
hay problema. Para la semana que viene está bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-12 9:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Yendo al tema calculador de materiales, ya hice tambien que ande del
backup.

http://www.parexklaukol.com.ar/aplicaciones/calculador.html

Lo unico feo es que (supongo que por un tema de encoding diferente
en la base de datos) salen mal los acentos, pero eso se corrige en
la base (ojo no es el CMS, es la base importada a los ponchazos del
backup).

Aca tambien cada producto que recomienda habria que hacer la
conexion link viejo -> link nuevo.
Pero seguramente sean los MISMOS links que (o muy parecidos a) los
que me estes pasando para la Casa Interactiva, asi que cuando me
pases ese excel matamos dos pajaros de un tiro.

Y tambien aca hay que maquetar lo de alrededor, por supuesto.
El contenido en si no es un frame que apunta  a este URL:
```

http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar/simulador/calculador.php

```
(pongo todas estas cosas para que le sirvan de referencia a Fede).

El 12/06/2015 a las 9:37, LeandroBraier
  escribió:

Ok, apenas puedo te paso el excel. Estoy medio a las
  corridas hoy, pero no
  hay problema. Para la semana que viene está bien.

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-12 9:31 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > No hay nada que programar en la casa, solo son esos links que
  es
  > crear unos accesos directos en el server.
  >
  > El 11/06/2015 a las 19:24,
  > LeandroBraier escribió:
  >
  > Ok. Hagamos la parte dura primero, de programación, y
  > después le pido a
  > Fede eso la semana que viene.
  >
  > Ahora te paso la lista.
  >
  > abrazo
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-06-11 16:48 GMT-03:00 mkreyness
  > <notifications@github.com>:
  >
  > > Tambien en esto tene en cuenta que Fede tiene que armar
  todo
  > lo de
  > > alrededor de la casa, con esto en el medio:
  > >
  > > <object width="980" height="470"
  > > data="media/wysiwyg/casa-interactiva.swf"
  > > type="application/x-shockwave-flash">
  > > <param name="data"
  > value="media/wysiwyg/casa-interactiva.swf">
  > > <param name="src"
  > value="media/wysiwyg/casa-interactiva.swf">
  > > <param name="wmode" value="transparent">
  > > </object>
  > >
  > >
  > > On 11/06/2015 03:41 p.m., LeandroBraier wrote:
  > > > Perfecto. A la tardecita te paso el excel. Gracias!
  > > >
  > > > Leandro Braier
  > > > Producción Audiovisual & Social Media
  > > > Benteveo Producciones <http://benteveo.tv>
  > >
  > > > Móvil 1158717399
  > > >
  > > > 2015-06-11 15:38 GMT-03:00 mkreyness
  > <notifications@github.com>:
  > > >
  > > > > Exacto, asi fuerzo que ese lugar inexistente
  apunte
  > al correcto.
  > > > >
  > > > > On 10/06/2015 08:02 p.m., LeandroBraier wrote:
  > > > > > Ah ok. Entonces las dos columnas son:
  > > > > >
  > > > > > "Link viejo"/ "Link actual"
  > > > > >
  > > > > > mañana te lo paso
  > > > > >
  > > > > > abrazo
  > > > > >
  > > > > > Leandro Braier
  > > > > > Producción Audiovisual & Social Media
  > > > > > Benteveo Producciones
  > <http://benteveo.tv>
  > > > > > Móvil 1158717399
  > > > > >
  > > > > > 2015-06-10 19:32 GMT-03:00 mkreyness
  > <notifications@github.com>:
  > > > > >
  > > > > > > No es nombre, es el link, hay que
  hacer
  > click (te va a dar error
  > > 404
  > > > > por
  > > > > > > supuesto) pero necesito que me
  copien el
  > link.
  > > > > > >
  > > > > > > On 10/06/2015 07:25 p.m.,
  LeandroBraier
  > wrote:
  > > > > > > > Perfecto. Yo lo hago. Mañana te
  paso
  > el excel nomás con Columna
  > > > > > "Nombre
  > > > > > > de
  > > > > > > > producto" y "Link actual". Está
  bien
  > así?
  > > > > > > >
  > > > > > > > Leandro Braier
  > > > > > > > Producción Audiovisual &
  Social
  > Media
  > > > > > > > Benteveo Producciones
  > <http://benteveo.tv>
  > > > > > >
  > > > > > > > Móvil 1158717399
  > > > > > > >
  > > > > > > > 2015-06-10 19:21 GMT-03:00
  mkreyness
  > <notifications@github.com>:
  > > > > > > >
  > > > > > > > > Ok. Lo que habria que
  hacer con
  > la casa interactiva (que en
  > > > > > realidad ya
  > > > > > > > > lo hiciste vos para
  verificar,
  > pero no creo que hayas guardado
  > > > > > la data)
  > > > > > > > > es poner a alguien a
  recorrer
  > todos los links de productos que
  > > > > > trae el
  > > > > > > > > flash en cada posible
  parte, y
  > asociarlos (en 2 columnas de un
  > > > > excel
  > > > > > > por
  > > > > > > > > ejemplo) con los links
  > correctos.
  > > > > > > > > Eso me lo pasan y en 10
  minutos
  > lo sacamos andando.
  > > > > > > > >
  > > > > > > > > On 10/06/2015 07:09 p.m.,
  > LeandroBraier wrote:
  > > > > > > > > >
  > > > > > > > > > CASA INTERACTIVA: Por
  > ahora usemos ese Flash y listo. No nos
  > > > > > pidieron
  > > > > > > > > > que lo "rehagamos".
  Si me
  > piden les digo que es un Flash y
  > > que
  > > > > > es muy
  > > > > > > > > > difícil cambiar
  productos,
  > habría que reconstruyir el
  > > editable
  > > > > del
  > > > > > > > > > flash y luego
  acomodar los
  > errores que genere el programa de
  > > > > > > > > > reconstrucción, etc.
  No te
  > preocupes, MK, tenemos gente en el
  > > > > > equipo
  > > > > > > > > > que hace eso, no lo
  > tendrías que hacer vos. Simplemente
  > > > > > reutilizá ese
  > > > > > > > > > flash y listo.
  > > > > > > > > >
  > > > > > > > > > CALCULADOR: Es aquí
  donde
  > va el Calculador, no en Parex. En
  > > > > > Parex era
  > > > > > > > > > otra cosa, fijate en
  ese
  > ticket.
  > > > > > > > > >
  > > > > > > > > > Respecto de este
  > Calculador no logré decifrar la fórmula
  > > > > > todavía. La
  > > > > > > > > > puedo preguntar al
  cliente
  > mañana y te la confirmo. Vayamos
  > > > > > avanzando
  > > > > > > > > > con la Casa
  Interactiva y
  > los pendientes de Parex. Revear
  > > > > > dejemoslo
  > > > > > > en
  > > > > > > > > > 2do lugar. Si
  llegamos con
  > Klaukol y Parex para fin de junio
  > > > > > pero no
  > > > > > > > > > con Revear no estamos
  tan
  > mal.
  > > > > > > > > >
  > > > > > > > > > abrazo
  > > > > > > > > >
  > > > > > > > > > —
  > > > > > > > > > Reply to this email
  > directly or view it on GitHub
  > > > > > > > > > <
  > > > > > > > >
  > > > > > > >
  > > > > > >
  > > > > >
  > > > >
  > > >
  > >
  >
```

https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110932050
      > > > > > > > > >.
      > > > > > > > >
      > > > > > > > > >
      > > > > > > > >
      > > > > > > > > —
      > > > > > > > > Reply to this email
      directly or
      > view it on GitHub
      > > > > > > > >
      > > > > > > > <
      > > > > > >
      > > > > >
      > > > >
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110935022>
      > > > > > > > > .
      > > > > > > > >
      > > > > > > >
      > > > > > > > —
      > > > > > > > Reply to this email directly or
      view
      > it on GitHub
      > > > > > > > <
      > > > > > >
      > > > > >
      > > > >
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110935622
      > > > > > > >.
      > > > > > >
      > > > > > > >
      > > > > > >
      > > > > > > —
      > > > > > > Reply to this email directly or view
      it
      > on GitHub
      > > > > > >
      > > > > > <
      > > > >
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110936863>
      > > > > > > .
      > > > > > >
      > > > > >
      > > > > > —
      > > > > > Reply to this email directly or view it
      on
      > GitHub
      > > > > > <
      > > > >
      > > >
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-110941667
      > > > > >.
      > > > >
      > > > > >
      > > > >
      > > > > —
      > > > > Reply to this email directly or view it on
      GitHub
      > > > >
      > > > <
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111235153>
      > > > > .
      > > > >
      > > >
      > > > —
      > > > Reply to this email directly or view it on GitHub
      > > > <
      > >
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111235635
      > > >.
      > >
      > > >
      > >
      > > —
      > > Reply to this email directly or view it on GitHub
      > >
      >
<https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111257488
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/21#issuecomment-111476744
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Marce, te envié el excel con los links nuevos via mail. Estoy viendo que algunos productos cambiaron asi que seguramente nos van a pedir modificar. Voy a ir averiguando con un especialista en Flash como podemos modificar los nombres de los productos que figuran en las listas pero es para otra etapa. Por ahora reemplacemos los links nomás.

abrazo
