### ISSUE TITLE
Agregado de Novedad y Producto Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#210]
@FAAREIA esto debería estar subido para el viernes 6/11. Es secundario después de Club de Colocadores.
1. Agregar novedad a Sitio Revear

Título: ParexGroup lanza “REVIVIDOR de colores REVEAR” 

Imagen:

Texto: El nuevo REVIVIDOR de colores Revear para texturados es apto para uso interno o externo

El mismo fue desarrollado para la renovación del color en revestimientos que se han envejecido por los agentes climáticos y el paso del tiempo.
Es de muy fácil aplicación, el producto forma una película mate de muy bajo espesor sin tapar la textura original, brindando una excelente protección y devolviendo a la superficie su apariencia original.

Los revestimientos texturados permiten dar color y terminación a las paredes internas y externas en un solo paso. Revear ofrece los siguientes tonos: gris estaño, marrón habano, verde mate, beige almendra, marfil bambú y salmón rosado.
1. Agregar Producto "Revividor de Colores Revear"

Revividor
Nuevo Revividor de Color para Texturados

Devuelve al color su apariencia original, sin tapar la textura del revestimiento. Renueva el color existente. Renueva el color existente en revestimientos envejecidos por los agentes climáticos y el paso del tiempo.

Excelente resistencia al lavado y la abrasión. Forma una película mate de muy bajo espesor SIN TAPAR LA TEXTURA.

Muy fácil aplicación.

RENDIMIENTO
12 a 14 m x kg por mano aprox. Se recomiendan 2 manos  o más de producto según la superﬁcie.
A soplete de aire 0,12 – 0,15 kg/m3 por mano.

PRESENTACIÓN
Envase de 4 kg / 20 kg.  

COLOR
Blanco y 6 colores de stock

Acá tenés los materiales para descargarte:

https://www.wetransfer.com/downloads/943f1fa7721c67415f547dc40c7556f520151029145643/e27481f70d6a007d4a9d12c3601c4db120151029145643/e3aa2c

Obviamente no hay video ni Ficha Técnica ni sección de Beneficios. Es una página con menor cantidad de elementos que los otros productos de Revear (al menos por el momento). El JPG debería ir linkeado como Ficha Técnica mientrás tanto. Te aviso si hay alguna novedad

abrazo

**Comment by FAAREIA** [comment]
http://www.revear.com.ar/productos.html
http://www.revear.com.ar/productos/linea-premium-2.html
http://www.revear.com.ar/productos/linea-premium-2/linea-premium-1.html

http://www.revear.com.ar/novedades.html

La verdad que todo esta más quintuplicado de lo que creia, lo que hice fue sacar los links de acceso a esas quintuplicaciones pero solo en las url trabajadas.

**Comment by LeandroBraier** [comment]
Está perfecto Fede!!

Solo te pido que quites la frase repetida. Donde dice: 

"Renueva el color existente. Renueva el color existente en revestimientos envejecidos por los agentes climáticos y el paso del tiempo."

Solo eso.

**Comment by FAAREIA** [comment]
Ahi lo vi.
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Te paso feedback del cliente. Solo el punto 1 necesito que lo hagas lo antes posible:
1. ~~PRIORIDAD EN LA HOME: Antes que nada te pido que por favor hagas el cambio del teléfono del Departamento Técnico, por favor poner el mismo que aparece en el showroom:  (011) 4782-1123~~
   Esto lo necesitamos a la brevedad.

El resto del feedback lo estoy confirmando con el cliente para ser más claro, así que no arranques todavía con el resto. Lo copio acá para después corregirlo nada más.
1. Respecto del producto Revividor:
- ~~Ubicación: corresponde que este en linea premium/revestimientos texturados.~~
- ~~En este link o sea dentro del arbol de productos 
  http://www.revear.com.ar/productos/linea-premium-2/linea-premium-1.html, 
  reemplazar el texto por 
  "Renueva el color existente en revestimientos envejecidos por los agentes climáticos y el paso del tiempo. Devuelve al color su apariencia original, sin tapar la textura del revestimiento"~~
- ~~Dentro del producto: 
  http://www.revear.com.ar/productos/linea-premium-2/revividor-colores-revear.html 
  reemplazar texto por
  "Desarrollado para la renovación del color existente en revestimientos texturados envejecidos por los agentes climáticos, y el paso del tiempo, o con manchas de polución, Uso interior y exterior, listo para usar."~~
- ~~Sacar el apartado de "la textura."~~
- ~~En rendimiento, separar Rodillo y pincel de Soplete, dejando en una linea cada uno, agregar los iconos en cada uno.~~
- ~~En color agregar la imagen de los colores de este flyer:
  https://www.wetransfer.com/downloads/0d2d8c3454fbb65b6777d3436a001b2520151110143639/72f9cb060710331d7cd58651e001ff5620151110143639/b9abc8~~
- ~~Poner lo siguiente debajo del pack Beneficios: (al igual que en Premium Marble, al no tener fotos subir la parte de beneficios para que no quede muy abajo)~~ 

"~~. Excelente resistencia al lavado y la abrasión.
. Forma una película mate de muy bajo espesor.
. Blanco y 6 colores de stock 
. Uso EXTERIOR / INTERIOR
. Muy fácil aplicación~~"

NOVEDADES
http://www.revear.com.ar/novedades/revividor-colores-revear/index.html#
- ~~Con respecto a novedades, sacar la frase "Los revestimientos texturados permiten dar color y terminación a las paredes internas y externas en un solo paso".~~

POP UP DEL INICIO
Te paso acá el PNG para poner como pop up de inicio que lleva a este producto.

![pop-up-flyer_revividor_500x500-rgb](https://cloud.githubusercontent.com/assets/6719872/11068039/49874ec8-87ae-11e5-85aa-42711da982f4.png)

abrazo

**Comment by FAAREIA** [comment]
Hecho lo del teléfono. Lo cambié por código porque esta en todas las páginas del sitio

**Comment by LeandroBraier** [comment]
Gracias Fede!

**Comment by LeandroBraier** [comment]
@FAAREIA ahi te actualicé el ticket con el pedido 2 en adelante. Cualquier duda avisame.

abrazo

**Comment by FAAREIA** [comment]
Todo hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!! Lo veo todo perfecto. Incluido pop up.

Solo pasa que no anda el link del título de Novedades. No lleva a ningún lado. Puede ser?

**Comment by FAAREIA** [comment]
Creo que estas clickeando el título de la novedad misma. Como sitio bien mal hecho, en el html de la novedad los títulos son links que no llevan a ningun lado. No se lo cambié por si se rompia algo.

**Comment by LeandroBraier** [comment]
Perfecto Fede. No hay problema. Queda así entonces. Gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA ya lo mostré al cliente y está todo joya. Solo me pidieron modificar un detalle del pop up. Acá te lo paso corregido:

![pop-up-flyer_revividor_500x500-rgb-4](https://cloud.githubusercontent.com/assets/6719872/11120963/f2134b76-8931-11e5-8c4b-4feb447d2977.png)

Avisame porfa cuando lo tengas modificado y ya cerramos el ticket.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!! abrazo grande
