### ISSUE TITLE
Reseteo Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#211]
@mkreyness por qué hay usuarios con 400 y 200 puntos en el ranking de la Comunidad de Vendedores? Eso no debería haber vuelto a 0?

abrazo

**Comment by mkreyness** [comment]
Te juro que no entiendo por que, pero hay toneladas de puntos liberados en este momento. No de octubre, de junio, julio, agosto y septiembre.
Voy a correr a mano el proceso que los cancela.

**Comment by LeandroBraier** [comment]
Debe hacer algo que hiciste cuando corregiste el error en el usuario Fabian Lopez, no?

**Comment by mkreyness** [comment]
No, todos esos puntos son cosas con 0 puntos en realidad, grabados al pedo, no afectan en nada.
Son del "Pase de Gol", debe ser de cuando se pasan de los 100 puntos en el juego.

No, esto que ves son puntos generados ahora en noviembre. 
Zorrilla hizo 160 puntos en el juego "Compartir posteo de cierre sorteo".  No se porque, pero ese tema esta definido asi, que paga 160 puntos.
Hizo tambien 80 puntos en un par de otros juegos, y entre pitos y flautas se le juntaron realmente 400.

**Comment by LeandroBraier** [comment]
Genial, me quedo tranquilo entonces.

abrazo
