### ISSUE TITLE
Registración Online Comunidad de Vendedores. ESPERANDO CLIENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#212]
@mkreyness como nueva dinámica de la Comunidad vamos a necesitar un espacio donde los usuarios puedan invitar a otros vendedores a sumarse. La base generada debería ser chequeada por el cliente antes de habilitar los usuarios. 

Ves posible que podamos tenerla para el martes que viene?

abrazo

pd: copio a @FAAREIA por cuanto a maquetación se refiere

**Comment by mkreyness** [comment]
Como seria la interface, un lugar para cargar una lista de emails ?

**Comment by LeandroBraier** [comment]
En realidad había pensado un formulario de registro como el de colocadores
sólo que el registrante tiene que cargar sus datos y además decir quién lo
recomendó.

Pero lo que decís parece interesante. Podría ingresar dni, nombre,
corralón  y mail verdad?

**Comment by mkreyness** [comment]
y pero si "el nuevo" escribe mal la direccion o el codigo de su amigo, no tenemos como asociarlo.
La mejor forma de que la info sea verificada es que el que ya esta registrado ponga la direccion de uno o mas amigos y haga click en un boton en el cual LE ABRIMOS SU MAIL para que les mande a todos un link para registrarse que ya tenga implicito quien lo recomendó.
Solo los que se den de alta via ese link le van a sumar puntos o lo que sea.

**Comment by LeandroBraier** [comment]
Perfecto. Me parece bien. Pero fíjate que tenga esos casilleros que te
decia: dni nombre corralón y mail. Ademas el mail no se mandaría automático
sino recién cuando le demos el ok interno con el cliente.

**Comment by mkreyness** [comment]
pero esos datos los cargaria QUIEN ?

**Comment by LeandroBraier** [comment]
El usuario ya inscripto, no el invitado.

Te explico: el cliente necesita chequear que sean vendedores reales.

**Comment by mkreyness** [comment]
Ok, y quien le daria el "nombre de usuario" ? La revision del cliente ? Me parece que lo complicado viene por esa interface mas que por el ingreso de estos datos.

**Comment by LeandroBraier** [comment]
Lo puedo hacer yo a ese chequeo siempre que le pueda pasar los datos
exportados al cliente para aprobar.

**Comment by mkreyness** [comment]
Entonces el "alta" real seria como fue siempre, me pasas un excel con el codigo de usuario, etc. para cargar ? Algo de prechequeo se puede hacer para evitar mails duplicados, pero podria pasar que 2 personas recomienden a un mismo tercero y ese todavia no esta en la base, asi que igual tendrias que chequear tambien.

**Comment by LeandroBraier** [comment]
Dale, me parece bien. Hagamos así entonces.

Para el caso específico: si dos personas recomiendan al mismo al mismo tiempo y el mismo es aprobado les sumamos a los dos, no pasa nada. Pero una vez que está subscripto ya no vale para el resto.

**Comment by mkreyness** [comment]
pero tendrian que tener usuarios distintos de todos modos.

**Comment by LeandroBraier** [comment]
El usuario del nombre lo inventamos nosotros como siempre, así que lo
chequearíamos. Simplemente quedaría en la landing de invitaciones:

Nombre y Apellido

DNI

Corralón: (a elegir de menú desplegable)

Mail:

Dos con el mismo DNI no puede haber.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Nahh, no le vas a pedir a alguien que de el DNI del amigo, yo no se el DNI de ningun amigo mio.

**Comment by mkreyness** [comment]
Y que maqueten "Nombre" y "Apellido" como dos campos separados.

**Comment by LeandroBraier** [comment]
Pero es un compañero de su mismo corralón.  Esta ahí mismo trabajando con
él.

**Comment by mkreyness** [comment]
Ah, entonces NO le tengo que pedir corralon, se asume que es del mismo y listo ?

**Comment by LeandroBraier** [comment]
Nop. Por favor incluí esos campos que te pido. A lo sumo si querés que le
aparezca por defecto su propio corralón y él de última lo pueda cambiar,
pero necesitamos la info de a qué corralón pertenece por las dudas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
pero vos sabes que los corralones que tienen puestos los vendedores son tipeados por ellos mismos, NO son los de la Guia. No puedo ponerle un desplegable de lo que otras personas escriban, puede decir cualquier guasada, y el propio NO necesariamente este en la lista de corralones conocidos.

**Comment by LeandroBraier** [comment]
No entiendo. No podemos desplegarle el mismo desplegable que hay en los
"Datos de mi corralón" dentro de la Comunidad? Por qué no?

Olvidate de que por defecto muestre nada, simplemente que elijan de esa
lista.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-11-03 22:26 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Mostrame donde esta ese desplegable... El unico que yo conozco es el desplegable de provincia.

**Comment by LeandroBraier** [comment]
Tenés razón, el desplegable no existe.

Y no podemos hacer un desplegable con la lista de corralones de la Guía de corralones?

**Comment by mkreyness** [comment]
Es que son casi 1900, para un desplegable es mucho !

**Comment by LeandroBraier** [comment]
Tenés razón. Y con autocompletar?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-04 9:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Me parece que igual seria muy lento al ser tantos. En Danica lo habiamos hecho pero eran proporcionalmente muchisimas menos recetas que lo que aca hay de corralones.
Lo que yo habia propuesto (y de ahi te quedo la idea pero nunca se implemento) es que eligiendo provincia desplegar localidades y eligiendo una localidad desplegar corralones, asi es progresivo. Pero igual si la localidad es CABA van a aparecer muchos. Algo es algo.

**Comment by LeandroBraier** [comment]
Dale, si podemos aplicar esta solución tanto en esta landing (para la
semana que viene) y en Comunidad de Vendedores (puede ser para más
adelante, en 3 semanas) estamos perfecto. Confirmame porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-04 9:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok, si no salta ninguna cosa rara en el fin de semana, se podria hacer.

**Comment by LeandroBraier** [comment]
Excelente. Es para la semana que viene, todo bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hay que hacer un http://www.parexklaukol.com.ar/vendedores/login.html pero con más campos?
Listado final de campos?

**Comment by LeandroBraier** [comment]
No, Fede. Es una landing nueva que diría como título:

Invitá a otros Vendedores a la Comunidad y sumá 220 puntos.

Los campos serían:

Nombre 

Apellido

DNI

Provincia (desplegable que al ser seleccionado permite elegir "Localidad" y al ser seleccionada Localidad permite elegir el Corralón de un desplegable)

Mail:

Botón de "Invitar" al final, que envía el formulario y guarda los datos en una base que podemos descargar como excel desde el cms.

abrazo

**Comment by FAAREIA** [comment]
Ahi va el diseño, espero que guste

![sumar](https://cloud.githubusercontent.com/assets/6184969/11000425/7b86161a-8480-11e5-9696-b6ccd37349e8.png)

**Comment by LeandroBraier** [comment]
Está bueno Fede. Vamos con las siguientes correcciones:

1) Me acabo de dar cuenta de que va a ser mejor que lo carguemos como un juego más de la Comunidad. Es decir, con un título, foto cuadrado, formulario debajo (tal como está) .

2) Como foto dejame que la cargue por CMS como siempre, pero te paso acá cual iría así podés armar el mock up:

![parexklaukol_0238](https://cloud.githubusercontent.com/assets/6719872/11000532/1ce93082-8481-11e5-9d2f-2a528b815e54.jpg)

3) Poner un captcha en el form. En caso de que no se pueda, que el sistema registre el horario y de ser posible el IP del usuario, para poder filtrar el spam y los usuarios hackers.

abrazo

**Comment by mkreyness** [comment]
Pero si este form lo va a llenar alguien que YA esta registrado, para que hace falta el captcha ?
Igual podemos por supuesto guardar el IP, y ademas no vamos a estar mandando en el momento ningun mail, asi que los mails que ponga los podemos analizar antes de hacer nada.
Para cuando lo maquetes @FAAREIA tene en cuenta que tanto provincia como localidad como corralon van a ser DESPLEGABLES que voy a armar dinamicamente en funcion de lo que tenemos en la base de corralones.
@LeandroBraier lo que no se que hacer si el tipo no encuentra el corralon y quiere dejarlo en blanco, deberiamos permitirlo o es obligatorio ?

**Comment by LeandroBraier** [comment]
Hagamoslo obligatorio MK. Por las dudas. El usuario quiere sumar puntos,
se va a comprometer en hacerlo bien.

Abrazo

**Comment by mkreyness** [comment]
No me refiero a que el usuario "no quiera" completarla, sino que el corralon que busca NO APARECE, porque no esta en localidad que cree, o no lo tenemos bien cargado/clasificado

**Comment by LeandroBraier** [comment]
Entiendo lo que decís, pero apuntemos a que si esté o a que ponga un
corralón equivocado de última, porque si no es obligatorio no lo va a poner
nadie.

Sino podríamos embeber el buscador de la Guía de Corralones directamente.
No se puede hacer eso? Incluso podría mostrarle el mapa de donde queda el
corralón para confirmarlo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-07 22:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Seria muchisimo mas complicado, tendria que ser a pantalla completa para que se vea algo, etc.
Yo lo que sugiero es poner una opcion "Otros" al final (sin que tipee nada, solo para decir que no es ninguno de esos).

**Comment by LeandroBraier** [comment]
Ok, me parece bien eso. Que el "otros" sea tipeado. Hay alguna forma de
restringir que el nombra no sea cualquiera?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-08 9:18 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Y no, con que criterio lo restringiriamos, por eso yo digo que si pone "Otros" simplemente signifique que no lo encontró, pero que no tipee nada.
Y que no sea la primera opcion, o sea, que para llegar ahi tiene que haber por lo menos pasado la vista por los que aparecen (en muchas localidades va a aparecer UN SOLO corralon, asi que el "Otros" igual va a estar ahi a la vista).

**Comment by LeandroBraier** [comment]
Entiendo. Entonces elige otros pero por lo menos elige Localidad. COn eso
estamos perfecto MK. Vamos así. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-08 11:05 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Exacto, y al lado de cada nombre de corralon le voy a mostrar el domicilio, porque si la localidad es grande (por ej, Ciudad de Bs As) un mismo corralon puede aparecer varias veces.

**Comment by LeandroBraier** [comment]
Dale, me parece bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-08 12:00 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
yo tengo listo todo lo que puedo tener listo, para ensamblarlo, necesito la maquetacion.

**Comment by LeandroBraier** [comment]
Ok, genial. Mañana Fede lo sigue entonces.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-08 14:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya maqueté el formulario, el archivo se llama `juego-invitacionT.html`
Marce fijate que dejé visible los mensajes de Error y Ok, ocultalos y mostralos cuando se necesite y poneles el texto que creas correcto.

**Comment by mkreyness** [comment]
ok, retomo la posta.

**Comment by mkreyness** [comment]
@FAAREIA, cuando trato de integrar todo dentro del contexto de los juegos se me rompe la maqueta, mira:

http://www.parexklaukol.com.ar/cgi-bin/jugarinvitacion.pl?usuario=marcelokreyness&clave=pepe&id=23

El template sigue siendo el que me dejast (juego-invitacionT.html), al cual le hice unas adaptaciones para lo de los popups, que anda bastante bien.

Fijate a ver si descubris por que se rompe y lo podes arreglar en el template.

Y ya que estas, habria que agregar un campito para que tipee el nombre de un corralon en caso de haber seleccionado la opcion 'Otros' en el desplegable (yo me ocupo de habilitarlo cuando corresponda, vos solamente agregame el campito en un lugar que quede bien, para mi tiene que estar  encolumnado con el desplegable de corralones.

 NO intenten "confirmar" en el formulario porque falta terminar/probar la logica de suma de puntos y validaciones varias.

**Comment by FAAREIA** [comment]
Ya esta solucionado. Fijate de ocultar el campo por defecto metiendo un `style="display: none"` y sacarle el ``display: none;` cuando necesite mostrarse.

**Comment by mkreyness** [comment]
ok, ya esta puesta la funcionalidad.
Me falta cerrar el tema de los puntos que no entiendo @LeandroBraier si se le acreditan apenas recomiende a alguien o solo si se verifica que esa persona confirma su inscripcion (tampoco se bien como, va con un mail de bienvenida especial ? Me perdi.

**Comment by LeandroBraier** [comment]
Los puntos mejor que se sumen una vez validados. Poneme la casilla en el cms para que yo te valide el usuario cuando el cliente me lo apruebe y ahi se sumarían los puntos. Por lo cual, cada vez que envien los datos del invitado, deberían ver un pop up que explique: "¡Gracias por invitar a un nuevo vendedor a la Comunidad! Cuando el nuevo usuario ingrese a la Comunidad sumarás 220 puntos."

La inscripción se haría con una mailing de bienvenida común y corriente.

abrazo

**Comment by LeandroBraier** [comment]
Cómo venimos con esto @mkreyness ?

**Comment by mkreyness** [comment]
Esta tarde (tirando a noche) lo liquido

**Comment by mkreyness** [comment]
bueno, ya esta todo bastante resuelto.
Habria que ponerle alguna foto al "tema".
Tanto el tema como el juego por ahora estan en "elaboracion", pero lo podes volver a ver por el link este:

http://www.parexklaukol.com.ar/cgi-bin/jugarinvitacion.pl?usuario=marcelokreyness&clave=pepe&id=23

controla que no este ya dado de alta ya sea como vendedor o como inviitado, por el DNI y por el mail.
Si todo ok avisa que se le van a acreditar los puntos cuando el invitado ingrese.
En el CMS tenes la parte de "Invitados" (dentro de Vendedores) donde te van a ir apareciendo todos, y cuando los pasas a "APROBADO", le acredita los puntos (220 por cada invitado).

Ojo que no es cierto entonces que los puntos se acrediten cuando el tipo realmente ingrese, es solo cuando vos lo estas aprobando.
Faltaria si hacer que esa aprobacion simultaneamente lo de de alta como vendedor y automatizar el envio de mails (que hasta ahora siempre es manual, como el alta).

**Comment by LeandroBraier** [comment]
Gracias MK!

http://www.parexklaukol.com.ar/cgi-bin/jugarinvitacion.pl?usuario=marcelokreyness&clave=pepe&id=23

Ahi agregué la imagen y queda todo claro. Ya puedo probar entonces cargar un usuario a ver si funciona?

**Comment by mkreyness** [comment]
Esto nunca te lo conteste, si, podes cargarlo y te tiene que aparecer  en el CMS en la parte de "Invitados" dentro de "Vendedores"

**Comment by LeandroBraier** [comment]
Perfecto gracias! Ya podes mandar los de potenciados también.

Abrazo

**Comment by mkreyness** [comment]
No puedo, porque esta mandando mas de 800 mails a vendedores.
Eso va a ocupar por unas 4 horas nuestra capacidad de envio de mails.
Estos 800 son solamente aquellos que NUNCA entraron.
Y despues faltan los que entraron pero no en noviembre. Antes de mandar esos puedo intercalar lo de torneos, pero va a ser de noche, lo hago mejor a la mañana ?

**Comment by LeandroBraier** [comment]
Dale. Mejor a la mañana. Gracias!
