### ISSUE TITLE
Detalles Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#213]
@mkreyness me piden cambios mínimos, lo que necesito saber es si llegamos para hoy. Sino les digo que sería para mañana.

1) Quitar la palabra "puntos", que no hable de puntos en las actividades y que en lugar de "comunidad" diga "club" . Por ejemplo: En lugar de "Marcelo Gonzalez ganó puntos por ingresar a la comunidad" que diga "Marcelo Gonzalez ingresó al club."

![modificacion chart de actividad](https://cloud.githubusercontent.com/assets/6719872/10974899/ea20d04c-83c2-11e5-8d21-e46ebdd13202.gif)

2) En el PDF de presupuesto no se lee Presupuesto arriba de todo. Debería decir "Presupuesto" arriba. Entiendo que esto es de @FAAREIA 

Me confirman si llegamos para hoy a la tarde?

abrazo

**Comment by mkreyness** [comment]
Los textos que aparecen ahi despues de "ganó puntos" son los que figuran en los "juegos", podes ponerle lo que quieras como nombre.
Pero la parte "ganó puntos" esta fija, se la puedo sacar del todo y asi tenes control 100% desde el CMS. Tardo 5 segundos en sacarlo, vas a tardar mas vos en corregir los textos.
El tema tambien es que esto figura en el sitio que esta VIGENTE, no me acuerdo si se muestra o no, pero los textos que cambies en el CMS van a afectar a ambos lados.

**Comment by mkreyness** [comment]
En realidad ahi decia Gano xx puntos, no dice los xx porque no deben estar cargados ?
Igual ya lo saque. Tenes todo el control del texto en el CMS.

**Comment by FAAREIA** [comment]
Hola Lea, estoy por salir y vuelvo tipo 21hs, mañana a la mañana lo liquido

**Comment by LeandroBraier** [comment]
Ok. Gracias a los dos! OK aviso al cliente que lo del presupuesto va a
estar mañana entonces.

Abrazo y gracias!

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Quedó perfecto.

Los nombres de las actividades ya los ajusté. Consulta: existe la posibilidad de cambiar lo siguiente?

POP UP DE BIENVENIDA:

Cambiar texto "Seguí sumando puntos con nuestros contenidos exclusivos, juegos, vídeos y completando tu perfil." por "Seguí disfrutando nuestros contenidos exclusivos, juegos, vídeos y completando tu perfil."

WIDGET DE "MI PERFIL"

Cambiar texto: "Completá tu perfil y ganá puntos!" por "Completá tu perfil"

<img width="326" alt="captura de pantalla 2015-11-06 a las 9 42 36 a m" src="https://cloud.githubusercontent.com/assets/6719872/10997048/9eef8842-8468-11e5-802f-50e2b4e501ac.png">

WIDGET DE TOP 5

Ocultar por el momento la cantidad de puntos de cada usuario.

Es posible dentro de la mañana hacerlo?

**Comment by FAAREIA** [comment]
Ahi hice todo excepto lo del top 5.
¿No sería mejor sacarlo antes que tener un top 5 basado en algo que el usuario no sabe qué es? Un top 5 sin referencia de como entrar en el o subir posiciones, no tiene sentido

**Comment by LeandroBraier** [comment]
Es que seguro después lo van a querer reponer y la columna va a quedar
desbalanceada. Por eso prefiero que se siga viendo pero ocultando el dato
de puntos. Después seguro piden que se vuelva a ver, me están volviendo
loco estas chicas jeje

abrazo y gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-06 10:07 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi esta listo

**Comment by LeandroBraier** [comment]
Mil gracias Fede!!
