### ISSUE TITLE
Mailing Bienvenida Vendedores Noviembre

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#214]
Buen día @FAAREIA ! Necesitaría que con Brau hicieron una versión actualizada de este mailing de bienvenida:

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-septiembre-b.html

Solo se trata de cambiar "En Septiembre participá por" por "En Noviembre participá por" y que el premio, en lugar de ser el de Septiembre sea la Notebook Asus de este mes. Te paso la imagen del premio así le dan la misma estética que en septiembre, que les quedó muy bueno.

![notebook-asus-premio-noviembre](https://cloud.githubusercontent.com/assets/6719872/11032710/70ec8728-86bc-11e5-898a-c48c82856a0f.png)

El texto sobre la imagen diría "Una Notebook Asus"

abrazo

**Comment by LeandroBraier** [comment]
Llegás con este para hoy @FAAREIA o @braulio-evangelisti ! Lo necesitaba para hoy, me olvidé de aclararles.

**Comment by braulio-evangelisti** [comment]
En 15 lo subo lea

**Comment by LeandroBraier** [comment]
Gracias Brau!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Se me hizo un poco mas largo la subida, las imágenes que había encontrado para el fondo cuando lo volví a ver antes de subirlo no me gustaban y busqué otras.

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-noviembre.html

Abrazo

**Comment by LeandroBraier** [comment]
Quedó buenísimo @braulio-evangelisti ! Gracias!

@mkreyness acá ya tenés el mailing para enviar a los nuevos usuarios de comunidad de vendedores también. Avisame si está todo OK.

abrazo

**Comment by mkreyness** [comment]
Está todo bien, le saque como siempre la parte de arriba de "ver online" porque no funciona si entra asi (va a una pagina estatica que no tiene sus datos de usuario/clave).
Lo mando o queres que te mande una muestra primero Lean ?

**Comment by LeandroBraier** [comment]
Mandalos nomás MK. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-09 19:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Gracias a los dos!! MK, ya queda este mailing para todo Noviembre.

abrazo
