### ISSUE TITLE
Detalles Club de Colocadores #2 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#215]
@FAAREIA y @mkreyness les paso un par de detalles para el Club de Colocadores. El punto 2 es el único más urgente, que si lo tenemos el miércoles todo bien.
1. Las Trivias Destacadas en la Home no tienen un máximo y aparecen todas por defecto. Lo probé cargando nuevas trivias en el CMS. @mkreyness deberíamos poder filtrar eso de alguna manera al igual que los videos pero por separado. Te explico: no siempre van a coincidir los 3 videos destacados con las 3 trivias. Por eso te lo pido, pero es sin apuro por ahora.
2. Sección Consejos:

Ya tenemos la primera info para sumar a Consejos. Es una lista de frases simples que son clickeables y cada una tiene un párrafo explicativo al clickear. Están todas agrupadas bajo un mismo gran consejo que es "¿Cómo dar un buen servicio?"

[Consejos 05.11.pptx](https://github.com/LeandroBraier/Klaukol/files/30101/Consejos.05.11.pptx)

Si tenemos una propuesta de cómo incluirlo para el miércoles estamos bien. 

abrazo

**Comment by mkreyness** [comment]
1) si, el "destaque" esta operando solo para los videos, pero puedo hacer que tambien aplique a las trivias, no hay problema, es un segundo.
2) Creo que se podria manejar como las preguntas frecuentes de la academia, no ? Una lista en el CMS como Pregunta/Respuesta, que en la pagina se despliegan al tocarlas.

**Comment by LeandroBraier** [comment]
1) Buenisimo!

2) Excelente. Me parece muy buena solución.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-09 15:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
1) ya esta aplicado.
2) ya esta creado en el CMS, cargue las primeras, y tengo el programa practicamente terminado como para hacerlo, solo necesito la maquetacion para aplicarlo.

**Comment by FAAREIA** [comment]
Ya esta listo el template, cuando este aplicado lo van a poder ver pero es igual al preguntas-respuestas de la Academia.
El template se llama `consejosT.html`

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-10 10:17 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA cuando puedas, para mañana si es posible mejor, necesitaría que habilites también el link a Club de Colocadores que hay en el micrositio de Klaukol Impermeable Potenciado.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!

Vi donde cargar los consejos en el CMS pero no vi la página de cómo se ven finalmente. Me pasás ese link? Total hasta que no esté aprobado por el cliente no habilitamos el link en la home.

**Comment by mkreyness** [comment]
falta mi parte que junte todo. Ahora en un rato te aviso.

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-11 9:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo

http://www.parexklaukol.com.ar/cgi-bin/consejoscolo.pl?usuario=marcelokreyness&clave=pepe

habria que volver  a agregar "Consejos" en el menu "Herramientas" y habilitar el link en la home loggeada, no ?

**Comment by FAAREIA** [comment]
Si, hay que agregarlo. En que lugar del menú va? antes o después de que sección?

**Comment by LeandroBraier** [comment]
Fede, iría dentro del menú de Herramientas, pero esperá a que esté aprobado.

Para mi habría que darle un poco más de "amigabilidad" queda re contra frío así como lo estamos mostrando.

Como título debería decir: Consejos para ser un Gran Colocador

¿Hay posibilidad de sumar una foto debajo del título y debajo de cada consejo? ¿O al menos usar una foto con texto incorporado en lugar del texto frío del consejo? El texto quedaría como text alt en todo caso.

**Comment by mkreyness** [comment]
Si queres poner una foto en cada consejo tengo que agregar un campo en el CMS para que la cargues.

**Comment by LeandroBraier** [comment]
Entiendo. Pero qué opinan uds? No queda muy frío de la forma que está
ahora? Es casi un poco absurdo transmitir esos consejos de esa forma, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si esta en plena aprobación no sería mejor esperar a ver que dicen?
Siempre hay mejores formas de mostrar las cosas, el tema es que haya contenido. Si hay fotos mejor, y si hay respuestas que no son frases de 5 palabras también. Tené en cuenta que si pones foto en 1, pones foto en todas. Para mi mejor si hay fotos

**Comment by mkreyness** [comment]
Igual para mi el "consejo" propiamente dicho esta explicito en cada titulo, lo que viene adentro es como una aclaracion adicional, pero cualquiera ya entiende con ver el titulo. 
Y si no habria que poner titulos mas misteriosos, porque nada me llama a abrirlos.
Yo pondria un thumbnail al lado de cada titulo, con independencia de que la gente los despliegue o no.

**Comment by LeandroBraier** [comment]
Gracias por las sugerencias chicos!
Le voy a pasar el link al cliente junto con nuestras sugerencias así me dice cómo seguir.
abrazo

**Comment by LeandroBraier** [comment]
Fede, el cliente estuvo de acuerdo. Ya estamos trabajando en esas imágenes con el equipo de diseño. Apenas las tengo te las paso.

Me dijo algo más. Creo que esto es más para @mkreyness Aparentemente va a haber varias categorías de Consejos. Estas no van a ser las únicas, por lo cual habría que armar el sistema para poder catalogarlas y que aparezcan agrupadas por estas categorías.

Por ejemplo, la categoría correspondiente a estos 8 consejos sería "Trato con el cliente". Empecemos a armar esa estructura mientras te paso las fotos. Puede ser para el lunes. abrazo

**Comment by LeandroBraier** [comment]
Consulta @mkreyness: Recién me inscribí en el Club de Colocadores. Está automático el envío de mails a los registrados?

**Comment by mkreyness** [comment]
No, y menos mal porque acabo de darme cuenta que estaba marcando cualquier cosa como "activados" (en los vendedores con igual numero a los colocadores).
Voy a ver si puedo determinar hasta donde habia mandado, los marco como activos y mando los siguientes.
Queres que deje automatico entonces que 1 vez por hora o algo asi se mande a los nuevos ?

**Comment by LeandroBraier** [comment]
Dale, dejalo automático. 1 vez por hora porfa.

**Comment by mkreyness** [comment]
Listo ya salieron todos y quedo autom  1 x hora.
Te llego el tuyo, no ?

**Comment by LeandroBraier** [comment]
Si! Lo recibí perfecto y todo en orden por ahora. Gracias!

**Comment by LeandroBraier** [comment]
Chicos, ya tenemos diseñadas las gráficas de los 10 consejos.

Subamosla así a terminamos esta sección:

![1- consejo- siempre saluda](https://cloud.githubusercontent.com/assets/6719872/11402773/55536932-9378-11e5-9bd0-fc6f75329514.jpg)
![2- consejo- brinda un trato amable](https://cloud.githubusercontent.com/assets/6719872/11402772/554fc66a-9378-11e5-8087-c371c4ceb509.jpg)
![3- consejo- ofrece un dato personalizado](https://cloud.githubusercontent.com/assets/6719872/11402774/55545de2-9378-11e5-921a-541bc026b041.jpg)
![4- consejo- atiende con rapidez](https://cloud.githubusercontent.com/assets/6719872/11402777/555576aa-9378-11e5-8684-c85ad663d097.jpg)
![5- consejo- nunca discutas con el cliente](https://cloud.githubusercontent.com/assets/6719872/11402775/5554ba26-9378-11e5-8f4e-e3c8e93761c0.jpg)
![6- consejo- se flexible](https://cloud.githubusercontent.com/assets/6719872/11402776/555550f8-9378-11e5-8418-572b52bda206.jpg)
![7--consejo--se-sincero](https://cloud.githubusercontent.com/assets/6719872/11402778/55711202-9378-11e5-90d2-b22e88fc3ef0.jpg)
![8- consejo- gracias](https://cloud.githubusercontent.com/assets/6719872/11402779/55723d4e-9378-11e5-845b-078c3acb885c.jpg)

**Comment by mkreyness** [comment]
Esto todavia habria que maquetarlo, no ? Porque en lo que habiamos armado me parece que no habia lugar para foto.

**Comment by FAAREIA** [comment]
si, hay que rediseñarlo y maquetarlo

**Comment by LeandroBraier** [comment]
Exacto. Habría que maquetarlo bien. Las imagenes se va a haber mucho más chicas de hecho, no? Avisen si quieren que las achique, yo siempre las mando en la mejor calidad.

**Comment by FAAREIA** [comment]
Si, las imágenes van a estar más chicas. El texto de abajo es redundante que este en todas y habría que ponerlo en html. Ahora pruebo con las imágenes estas pero seguro hay que retocarle eso.

**Comment by LeandroBraier** [comment]
Dale, me parece bien. Avisame nomas

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-26 9:40 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/colocadores-temp/consejos.html
- Las fotos las puse sin el texto que traia la imagen. El texto esta en HTML
- La bajada de clickear para ver ponerla más corta o sacarla.
- Pasarme en vector o reubicar el icono de la mano en la foto.

Todo esto es importante para tamaños mobile.

**Comment by LeandroBraier** [comment]
Gracias Fede, pero no lo entiendo del todo.

1) Cada imagen tenía que ver con el consejo. Entiendo que esto lo podría
cargar yo via CMS, no? Tanto texto como imagen relacionada. Si es así
genial.

2) Cuando hago clic en la imagen me despliega el texto abajo pero no se
entiende la relación. Me parece que no es clara la maquetación para el
usuario. De la forma que estaba antes, el botón desplegaba el texto debajo
de la imagen que está relacionada, así se entendía que era una expansión de
ese consejo.

3) A qué te referís por "la bajada de clickear"? Es al texto que está en la
imagen? Si la imagen se nota que es un botón no va a hacer falta, pero no
está claro ahora.

En términos generales, me parece que el diseño se tiene que adaptar al
contenido, no sacar contenido para que quede bien el diseño. Tendrías que
rediseñar la maquetación para que se entienda la navegación y se luzcan los
consejos. Yo los pondría uno debajo del otro como era antes. Por ahora
olvidemonos de esa bajada de abajo. Si queda bien diseñado y se entienda la
navegación la sacamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-26 11:16 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Entiendo lo que decis, el scroll automático al seleccionar una pregunta es para orientar al usuario, sino si que no se entiende.
Más allá de eso, fijate esta otra opción: http://parexklaukol.com.ar/colocadores-temp/consejos2.html
El tema es que o las imágenes la dejamos chicas asi el usuario puede ver rápidamente todos los consejos y expandirlos o lo hacemos como el que recien te lo mandé, en donde hay que scrollear mucho para ver todos los consejos.
En modo responsivo las 2 opciones van a quedar iguales me imagino: foto y debajo el texto, un consejo debajo de otro.

**Comment by LeandroBraier** [comment]
Genial. Gracias Fede! Maquetame los 10 consejos en ambas versiones así le
muestro al cliente y me dice cual le gusta más.

Abrazo

**Comment by FAAREIA** [comment]
Ok, necesitaría que me pases la imagen de cada consejo sin texto incialmente.
Después de la aprobación seguro maquete aparte la manito.

**Comment by LeandroBraier** [comment]
Dale, te los mando a la tarde. Gracias!

**Comment by LeandroBraier** [comment]
Fede, te paso un wetransfer con todos los editables en PSD:

https://www.wetransfer.com/downloads/4984bf9f89dae2be47d77fbd24d7d00e20151201185341/b570b60978123fc508e55aba2a4a10f820151201185341/2edc07

Podremos tener esto para el jueves listo?

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/colocadores-temp/consejos.html
http://parexklaukol.com.ar/colocadores-temp/consejos2.html

Acordate que en responsivo, las dos opciones van a ser iguales: título, foto y debajo el texto. Un consejo debajo de otro.

**Comment by LeandroBraier** [comment]
Gracias Fede!! La verdad quedaron muy bien las dos, pero vamos con la
segunda que se entiende mejor.

http://parexklaukol.com.ar/colocadores-temp/consejos2.html

Ponele los textos correspondientes en cada consejo y subilo directamente a
producción ya.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Marce, fijate que subí las fotos pero no las encuentro en el FTP. Las tiene que guardar en: "img/consejos/"
Con eso solucionado ya sale a producción

**Comment by FAAREIA** [comment]
Desde el admin vi la foto original y me llevó a: guia-corralones/images/corralones/06-consejo-flexible.jpg

**Comment by mkreyness** [comment]
Me falto cambiarle el path al que va en el CMS, ahora lo toco y te aviso, habria que mover los archivos de donde los puso a donde corresponde que vayan.

**Comment by mkreyness** [comment]
listo, ya los movi tambien, fijate si todo te aparece bien ahora.

**Comment by FAAREIA** [comment]
Ahi se ve perfecto, pero no aparece la sección y la incluí en el template del encabezado para el usuario registrado.
Pregunta: ¿El orden es el correcto? Creo que se esta ordenando de forma descendente.

**Comment by FAAREIA** [comment]
Lo del orden esta bien, me confundí yo

**Comment by mkreyness** [comment]
Por lo que veo en el programa, no esta usando 2 templates diferentes, siempre esta mirando el otro.
Es raro porque esto lo debemos haber estado tocando un monton en esa maraton de arreglos de cuando Leandro lo presento al cliente.

**Comment by mkreyness** [comment]
dije cualquier cosa, mire la version anterior.
Si usa dos versiones, pero algo debe estar fallando, en un rato lo reviso bien y arreglo.

**Comment by mkreyness** [comment]
El encabezado regT es el que se muestra DURANTE la registracion, no tiene nada que ver con el tema de estar registrado o no. Eso se maneja con el "--logueado--".
Ya lo habilite en el template normal.
Fijate que tambien hay que sacarle el "proximamente" en la pagina principal.

**Comment by FAAREIA** [comment]
Hecho, ya quedó todo perfecto.

**Comment by LeandroBraier** [comment]
Gracias chicos! Ya lo dejan en producción entonces?

Abrazo

**Comment by FAAREIA** [comment]
Ya esta en producción.

**Comment by LeandroBraier** [comment]
Gracias Fede! En la versión mobile el texto al hacer clic se muestra fuera
de ls caja y en blanco, no se si se va a leer bien. Mejor en negro y
corregile lo de la ubicación del texto porfa.

Abrazo

**Comment by FAAREIA** [comment]
Ahi le hice el resposive definitivo. ;)

**Comment by LeandroBraier** [comment]
Gracias Fede pero sigo viendo el mismo problema. Hacé el testeo mobile como
hacemos siempre porfa y lo vas a ver. Yo en android lo veo igual: texto en
blanco y fuera de la caja correspondiente.

**Comment by FAAREIA** [comment]
Fixed, me había olvidado de subir la última versión del css.

**Comment by LeandroBraier** [comment]
Ahora si Fede!!! Quedó excelente la verdad. Gracias!
