### ISSUE TITLE
Newsletter Benteveo de Noviembre. 13/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#216]
@FAAREIA te paso un newsletter que siempre viene haciendo Braulio y ya se lo compartí en google.

Aquí va el nuevo newsletter de Benteveo a diseñar:

https://docs.google.com/document/d/1sjV9ucb1vTQmDrPMWQJT8qQZNjfKIvzfSY6AyAie4kk/edit

Tiene ya los links incorporados, pero los dos primeros gifs tendrían que hacerlos circulares uds, porque sigo sin encontrar la forma de hacerlo mediante máscara en Photoshop.

Más allá de eso los gifs ya están dimensiados y el de la Maratón listo para recortar en el centro y que los textos de la imagen se lean igual.

abrazo

**Comment by braulio-evangelisti** [comment]
Buen día Lea. Cuando puedas mandame las imágenes por aca o por mail.

Abrazo

**Comment by LeandroBraier** [comment]
Buen día Brau!

Acá van adjuntas.

![nota-3-youtubevsfacebook](https://cloud.githubusercontent.com/assets/6719872/11145250/7591c47c-89e2-11e5-8f70-188f0fdfa2da.gif)
![nota-2-maraton](https://cloud.githubusercontent.com/assets/6719872/11145251/7591e3a8-89e2-11e5-9c25-bef295b1547b.gif)
![nota-1-stand](https://cloud.githubusercontent.com/assets/6719872/11145252/75949152-89e2-11e5-82f8-e31efda68c49.gif)

abrazo

**Comment by braulio-evangelisti** [comment]
Aca te paso el link Lea. Avisame cualquier corrección.

http://www.benteveo.tv/mailing/noviembre/

Abrazo

**Comment by LeandroBraier** [comment]
Quedó muy bueno Brau!

Lo único malo que le veo es el tercero gif que tiene como un artefacto raro alrededor. Le podrás blurear los bordes del círculo para que eso no pase? lo demás lo veo perfecto.

**Comment by braulio-evangelisti** [comment]
Actualiza ahora a ver si lo seguis viendo. Habia puesto el gif tal cual me lo pasaron.

Abrazo

**Comment by LeandroBraier** [comment]
Ahora si, perfecto Brau! Gracias!

abrazo
