### ISSUE TITLE
Mailing de Premios Trimestrales Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#218]
Brau, necesitamos que diseñes 6 mailings iguales al que te reenvié por mail y te paso captura acá.

Uno para cada grupo: A, B, C, D, E y F.

El que te paso acá es el de grupo E. Lo que necesito es que robes el HTML pero lo armes para que podamos enviarlo a toda la base de ese grupo con el autologin.

<img width="237" alt="captura de pantalla 2015-11-13 a las 8 48 49 p m" src="https://cloud.githubusercontent.com/assets/6719872/11160318/0a55df44-8a47-11e5-88fa-8379e4d00d3d.png">

Una vez hecho el del Grupo E, te pido que hagas el del Grupo D, haciendo los siguientes cambios:

1) Cambiá la foto por esta:

![imagen-mailing-ganadores-trimestrales-dlm-categoria-d](https://cloud.githubusercontent.com/assets/6719872/11160238/ed35bb7e-8a45-11e5-9f29-05878c4c76bb.png)

2) Cambiá el texto:

"Gracias a la excepcional performance de MATERCON S.A. este trimestre, sus vendedores se han hecho acreedores de AR$ 12.500"

Reemplazar por:

"Gracias a la excepcional performance de DLM Construcción S.R.L. este trimestre, sus vendedores se han hecho acreedores de AR$ 25.000"

3) Obviamente cambiar los datos de abajo por los correspondientes a categoría D y el autologin.

Esto lo necesitamos para el lunes bien temprano porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Buen día lea, aca te paso 2 links:

http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-e.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-d.html

Con respecto al punto 3, los datos de abajo serian los 3 bloques rojos solamente? y lo del autologin es lo del boton de Ingresar u otra cosa diferente?

Abrazo

**Comment by LeandroBraier** [comment]
Están perfectos los dos Brau!! @mkreyness podremos mandar cada mailing a toda la base de mails de corralones y representantes comerciales de la categoría correspondiente?

Me refiero a:

1) Enviar a base de mails de Grupo D:
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-d.html

2) Enviar a base de mails de Grupo E:
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-e.html

abrazo

**Comment by braulio-evangelisti** [comment]
:+1:

**Comment by mkreyness** [comment]
Duda: los representantes tienen corralones de todas las categorias.
Quiere decir que c/u va a recibir un mail por grupo D y OTRO por grupo E, correcto ?

**Comment by mkreyness** [comment]
Otra duda: Esta bien que en las fotos hable de 2do semestre de 2014 ? El famoso "objetivo" era eso ?

**Comment by LeandroBraier** [comment]
Es correcto que un representante comercial reciba un mailing distinto por cada grupo. Son ganadores diferentes.

Respecto del texto si. Leelo bien vas a ver que dice algo como "Gana el que más crezca porcentualmente respecto del volumen comprado en el segundo semestre de 2014".

abrazo

**Comment by mkreyness** [comment]
ok, te mando primero una prueba de c/u.

**Comment by LeandroBraier** [comment]
Dale, joya. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Que "Asunto:" le pongo a los mails ?

**Comment by mkreyness** [comment]
Algo no esta bien. El texto del mailing esta dirigido al REPRESENTANTE, no puedo mandarle al CORRALON  algo con este texto:
"entra a nuestra plataforma para ver como vienen tus clientes en el ranking".
Tienen que ser mailings diferentes.

**Comment by LeandroBraier** [comment]
Tenés razón MK. Están mezclados imagen de Premios para todos que corresponde a corralones y texto de "Cómo participo" que pertenece a RCD y a corralones.

@braulio-evangelisti necesitamos hacer dos versiones de cada grupo. Uno para representantes comerciales, con la imagen de "Premios para todos" que es para representantes comerciales y el texto de "Cómo participo" de representantes comerciales. Y un segundo con la imagen y el "cómo participo" de clientes.

**Comment by LeandroBraier** [comment]
Los subjects serían: 

GRUPO D
¡Felicitaciones DLM CONSTRUCCIÓN SRL por el Premio Trimestral!

GRUPO E
¡Felicitaciones MATERCOM S.A. por el Premio Trimestral!

abrazo

**Comment by mkreyness** [comment]
Ojo Braulio que los que estan en _mailing/torneo-premio-trimestral/ ya los modifique, porque estaban mal los links, no va "mainvendedores.pl" sino "torneo-con-slide.pl", y siempre le saco los "ver online" porque si entrara por ahi no le andarian los links.

**Comment by mkreyness** [comment]
Yo estoy esperando las novedades de Braulio para avanzar con esto.
Lean, lo que te llego fue copia de mi primera y unica prueba.

**Comment by LeandroBraier** [comment]
Perfecto, entiendo!

Brau, cuando lo tengas avisá porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-16 13:49 GMT-03:00 mkreyness notifications@github.com:

**Comment by braulio-evangelisti** [comment]
No se si entendi bien lo de las dos versiones, baje los dos html's modificados, y a partir de ahi generé dos versiones de D y dos de E, una con las imagenes que ya tenia y otra con las de representantes comerciales, asi era? Cualquier cosa avisame.

http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-d.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-d-rc.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-e.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-e-rc.html

Abrazo

**Comment by LeandroBraier** [comment]
Los dos de RC están OK. El de cliente tiene mal el Cómo participo. El Cómo
participo que va en los dos de cliente es este:

http://parexklaukol.com.ar/_mailing/torneo-bienvenida/torneo-bienvenida-a-d.html

Es solo eso, lo demás está ok.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-16 16:54 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Yo veo el mismo aca lea, proba de actualizar a ver si te carga la nueva imagen.

**Comment by LeandroBraier** [comment]
Nop, fijate. El texto dice:

<img width="610" alt="captura de pantalla 2015-11-16 a las 5 42 06 p m" src="https://cloud.githubusercontent.com/assets/6719872/11193758/2e74e806-8c87-11e5-8bbf-a176e078ae40.png">

No como el que está ahora en la versión de clientes, que es este:

<img width="598" alt="captura de pantalla 2015-11-16 a las 5 43 04 p m" src="https://cloud.githubusercontent.com/assets/6719872/11193783/4de9ab54-8c87-11e5-9ce4-ed4860dc0539.png">

El texto es diferente.

**Comment by braulio-evangelisti** [comment]
actualiza de nuevo, le cambie el nombre a los jpg's a ver si te carga los nuevos. confirmame por favor. abrazo

**Comment by LeandroBraier** [comment]
Ahora si perfecto. Gracias! Mandenme el de prueba nomás MK

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
INTENTE mandar el de prueba, pero al menos a mi no me llegó.
Supongo que debe estar encolado detras de los cientos que estan saliendo a vendedores, ya llegará (y si no, es para preocuparse).

**Comment by LeandroBraier** [comment]
Me acaba de llegar! Te lo reenvío.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-16 18:58 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
si, si, me llego tambien, esta ok ?

**Comment by mkreyness** [comment]
ahora pruebo con uno de corralon

**Comment by mkreyness** [comment]
bueno ya salieron las dos tandas de representantes, y estoy corriendo la primer tanda de corralones ("D").
Al mediodia me fijo si termino y largo la segunda tanda ("E").

**Comment by LeandroBraier** [comment]
Gracias MK!! Avisame nomás cuando termines.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-17 9:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ya termino todo. Ahora me falta largar el resto de vendedores (los que habian entrado alguna vez pero no en noviembre)

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by mkreyness** [comment]
ya termino eso tambien

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
@FAAREIA necesitamos que hagan para hoy dos mailings de estos más, cada uno con sus dos versiones de RC y de corralón.
1. Primer mailing para los ganadores de la categoría B, que es igual que el de la categoría E solo que cambia:

a. La foto por esta:

![imagen-mailing-ganadores-trimestrales-antonio-prevedello-categoria-b](https://cloud.githubusercontent.com/assets/6719872/11300731/10c68062-8f70-11e5-80f3-69546fdb9584.png)

b. Reemplazar MATERCOM S.A. en tl Subject del mail y en el texto arriba de la foto por ANTONIO PREVEDELLO Y CIA SRL
1. Segundo mailing para los ganadores de la categoría C, que incluye los siguientes cambios:

a. La foto por esta:

![imagen-mailing-ganadores-trimestrales-construcciones-2000-categoria-c](https://cloud.githubusercontent.com/assets/6719872/11300764/5f226488-8f70-11e5-8077-dce4bdcc9d06.png)

b. Reemplazar DLM CONSTRUCCIÓN SRL. en tl Subject del mail y en el texto arriba de la foto por CONSTRUCCIONES 2000 SRL

c. Reemplazar el monto del texto "hacen acreedores de..." por $5000

d. Reemplazar los datos de viaje y premio de vendedores por los correspondientes a la categoría C.

Avisenme porfa si los podemos tener dentro de la mañana.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea aca te paso los links:

http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-b.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-b-rc.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-c.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-c-rc.html

Chequea que todas las imagenes sean las correctas para cada categoria y avisame por favor.

Cualquier cosa desde aca tendrias que poder ver el listado completo junto a E y D:

http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/

Abrazo

**Comment by LeandroBraier** [comment]
Está perfecto Brau. Gracias!!

@mkreyness porfa el lunes a la mañana ponelos a enviar a estos a sus respectivos grupos: 

GRUPO B CORRALONES
GRUPO B REPRESENTACIONES COMERCIALES
GRUPO C CORRALONES
GRUPO C REPRESENTACIONES COMERCIALES

abrazo

**Comment by LeandroBraier** [comment]
buen día no peronista @mkreyness !! Espero que hayas andado bien el finde. Avisame cuando hayas enviado esto porfa.

abrazo

**Comment by mkreyness** [comment]
Creo que ni me habia dado por enterado de esto. Ahora veo y te mando prueba.

**Comment by mkreyness** [comment]
ahi te mande uno de c/u, confirmame si esta todo ok y lo largo.

**Comment by LeandroBraier** [comment]
Ahí los revisé. Los de categoría C están OK. Pero los de categoría B no. Está mal la imagen. Si te paso la imagen correcta la podés reemplazar?

![imagen-mailing-ganadores-trimestrales-antonio-prevedello-categoria-b](https://cloud.githubusercontent.com/assets/6719872/11340065/247134c8-91db-11e5-843a-8b5cf78e0425.png)

**Comment by mkreyness** [comment]
supongo que si, ahora veo.

**Comment by mkreyness** [comment]
no des bola todavia a lo que te llego, sigo trabajando en ello

**Comment by mkreyness** [comment]
ahora si, confirmame que te llego una ultima version bien de c/u de los "B".

**Comment by LeandroBraier** [comment]
Ahora si recibí y están perfectas. Mande nomás.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti necesitaría que hoy me armes nuevas versiones de estos mailings. Es para los premios del segundo trimestre.

Esta vez es así:

TANDA 1) Un mailing por grupo para corralones. 

TANDA 2) Un mailing solo para corredores.

#TANDA 1#

Tomo como referencia esta maquetación: 

http://parexklaukol.com.ar/_mailing/torneo-premio-trimestral/torneo-premio-trimestral-b.html 

##MAILING GRUPO A##

¡FELICITACIONES ZERAMIKO!

LOGO TORNEO DE POTENCIADOS

Gracias a la excepcional performance de OLAZ MARIA ROSA DEL VALLE - ZERAMIKO en el segundo trimestre, sus vendedores se han hecho acreedores de AR$ 25.000

![slide-ganadores-segundo-trimestre-grupo-a-corregido](https://cloud.githubusercontent.com/assets/6719872/11900065/28c56b6a-a582-11e5-81f5-d5986bea128d.png)

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales.

3 recuadros rojos con premios mayores de Categoría A

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

##MAILING GRUPO B##

¡FELICITACIONES CERÁMICA FIRENZE!

LOGO TORNEO DE POTENCIADOS

Gracias a la excepcional performance de CERÁMICA FIRENZE en el segundo trimestre, sus vendedores se han hecho acreedores de AR$ 12.500

![slide-ganadores-segundo-trimestre-grupo-b-corregido](https://cloud.githubusercontent.com/assets/6719872/11900157/b3b4e9f8-a582-11e5-97cd-4d54e3f89d90.png)

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales.

3 recuadros rojos con premios mayores de Categoría B

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

##MAILING GRUPO C##

¡FELICITACIONES CALIQUIS!

LOGO TORNEO DE POTENCIADOS

Gracias a la excepcional performance de CALIQUIS MARIELA ROSANA en el segundo trimestre, sus vendedores se han hecho acreedores de AR$ 5.000

![slide-ganadores-segundo-trimestre-grupo-c-corregido](https://cloud.githubusercontent.com/assets/6719872/11900175/d097513c-a582-11e5-90d6-f3119215dbe5.png)

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales.

3 recuadros rojos con premios mayores de Categoría C

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

##MAILING GRUPO D##

¡FELICITACIONES COPMACO LTDA!

LOGO TORNEO DE POTENCIADOS

Gracias a la excepcional performance de COPMACO LTDA en el segundo trimestre, sus vendedores se han hecho acreedores de AR$ 25.000

![slide-ganadores-segundo-trimestre-grupo-d-corregido](https://cloud.githubusercontent.com/assets/6719872/11900193/edc5f63c-a582-11e5-93e2-aece6fe2eae0.png)

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales.

3 recuadros rojos con premios mayores de Categoría D

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

##MAILING GRUPO E##

¡FELICITACIONES MATERCON S.A.!

LOGO TORNEO DE POTENCIADOS

Gracias a la excepcional performance de MATERCON S.A. en el segundo trimestre, sus vendedores se han hecho acreedores de AR$ 12.500

![slide-ganadores-segundo-trimestre-grupo-e-corregido](https://cloud.githubusercontent.com/assets/6719872/11900202/00505810-a583-11e5-85ca-cf419814e9a1.png)

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales.

3 recuadros rojos con premios mayores de Categoría E

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

##MAILING GRUPO F##

¡FELICITACIONES MATERIALES 2003 SRL!

LOGO TORNEO DE POTENCIADOS

Gracias a la excepcional performance de MATERIALES 2003 SRL en el segundo trimestre, sus vendedores se han hecho acreedores de AR$ 5.000

![slide-ganadores-segundo-trimestre-grupo-f-corregido](https://cloud.githubusercontent.com/assets/6719872/11900209/10537210-a583-11e5-853a-69bec8e0dd35.png)

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales.

3 recuadros rojos con premios mayores de Categoría F

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

#TANDA 2#

El mailing solo para corredores seria asi:

¡YA TENEMOS A LOS GANADORES DEL SEGUNDO TRIMESTRE!

LOGO TORNEO DE POTENCIADOS

![slide-ganadores-segundo-trimestre-corredores-final](https://cloud.githubusercontent.com/assets/6719872/11900927/722e9560-a587-11e5-9f97-d8bfba082c4d.png)

Conocé a los vendedores ganadores de cada grupo entrando a la plataforma del torneo:

<img width="648" alt="captura de pantalla 2015-12-18 a las 12 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900114/711444c2-a582-11e5-99f0-47bb5f7e5991.png">

¡Y AHORA ATENTOS! Este 31/12 anunciaremos los ganadores de los grandes premios semestrales de todos los grupos.

<img width="611" alt="captura de pantalla 2015-12-18 a las 12 42 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/11900946/8c83add8-a587-11e5-99b0-f4db46ca0b4b.png">

Confirmame porfa si podés tener esto para la tarde.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahora me pongo, te aviso apenas esten

**Comment by braulio-evangelisti** [comment]
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-a.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-b.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-c.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-d.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-e.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-f.html
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-corredores.html

**Comment by LeandroBraier** [comment]
Están muy bien @braulio-evangelisti ! Gracias! Solo 2 errores.

1) En los 6 primeros mailings, los de los corralones, falta un espacio después del primer párrafo de texto que empieza con "Gracias...."

2) En el mailing del grupo F, además de faltar el espacio, falta la primera G de Gracias:
http://parexklaukol.com.ar/_mailing/torneo-premio-trimestre-2/torneo-premio-trimestre-f.html

3) Una vez resuelto esto, avisale a @mkreyness por favor así pone a enviar los mailings a los corralones de cada grupo y el último a todos los corredores (es decir, representantes comerciales o RC)

abrazo

**Comment by braulio-evangelisti** [comment]
Listo.

@LeandroBraier 
@mkreyness

**Comment by LeandroBraier** [comment]
Gracias Brau!!! Buen finde!!!

@mkreyness porfa apenas puedas envialos.

abrazo

**Comment by mkreyness** [comment]
Estas seguro de que queres mandar mailings con usuario y clave puesto en las URLs ?

**Comment by LeandroBraier** [comment]
En este momento no tenemos alternativa, ¿no?

La semana que viene quizá ya pudieron aplicar el nuevo sistema pero para
hoy ya no llegamos.

2015-12-18 16:36 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ja ja, nuevo sistema, quien lo va a hacer ? Yo tengo que ocuparme del Toro Paty ahora.

**Comment by mkreyness** [comment]
se puede mandar sin user/pass que vayan al login y ahi tipeen lo que mandamos en el mailing, eso es mucho mas seguro que el URL ya armado.

**Comment by LeandroBraier** [comment]
Si, pero puede generar algún conflicto a esta altura. Mejor no MK. Total
este Torneo ya termina. A lo sumo ocultamos la página y cambiamos todas las
contraseñas después del 31.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ok

**Comment by mkreyness** [comment]
Cada mailing lleva un asunto diferente, con las felicitaciones que corresponden a c/u, no ?

**Comment by LeandroBraier** [comment]
Si, perdón. Siempre me olvido de eso.

Los 6 de corralones es "¡FELICITACIONES MATERIALES 2003 SRL! - Torneo de Potenciados Klaukol. Premios Segundo Semestre"

La de corredores es: "¡YA TENEMOS A LOS GANADORES DEL SEGUNDO TRIMESTRE! - Torneo de Potenciados Klaukol."

**Comment by mkreyness** [comment]
No entiendo, probe con un "A" y adentro dice otra cosa, para mi no se entiende, quien gano, MATERIALES 2003 o ZERAMIKO ?

**Comment by LeandroBraier** [comment]
En el A gano Zeramiko. En donde dice Materiales 2003?

**Comment by mkreyness** [comment]
En el texto que me escribiste vos...

**Comment by mkreyness** [comment]
Necesito que me digas quien gano en cada grupo

**Comment by LeandroBraier** [comment]
Ah ok. Dame un min.

**Comment by LeandroBraier** [comment]
#MAILING GRUPO A#

¡FELICITACIONES ZERAMIKO! - Torneo de Potenciados Klaukol

#MAILING GRUPO B#

¡FELICITACIONES CERÁMICA FIRENZE! - Torneo de Potenciados Klaukol

#MAILING GRUPO C##

¡FELICITACIONES CALIQUIS! - Torneo de Potenciados Klaukol

#MAILING GRUPO D##

¡FELICITACIONES COPMACO LTDA!- Torneo de Potenciados Klaukol

#MAILING GRUPO E##

¡FELICITACIONES MATERCON S.A.! - Torneo de Potenciados Klaukol

#MAILING GRUPO F##

¡FELICITACIONES MATERIALES 2003 SRL! - Torneo de Potenciados Klaukol

**Comment by mkreyness** [comment]
ok te mando uno de prueba de c/u

**Comment by mkreyness** [comment]
confirmame y los largo, son muchos y va a llevar muchas horas. O queres que lo largue sabado a la mañana ?

**Comment by LeandroBraier** [comment]
Están ok MK. Mandalos nomas pero te estás olvidando del mail de corredores.
Ese tambien va.

Tema aparte: Un poco tarde pero no estaba hecho el responsive de este
sitio? Al entrar desde mobile se descajeta todo.

**Comment by mkreyness** [comment]
```
No me olvido, pero eso se manda en 3 minutos porque son pocos, y
dijiste que iban al final, asi que es lo menos urgente.
Mientras estos estan saliendo (facil 5 horas) voy preparando el
otro.

El 18/12/2015 a las 20:05,
  LeandroBraier escribió:

Están ok MK. Mandalos nomas pero te estás olvidando
  del mail de corredores.
  Ese tambien va.

  Tema aparte: Un poco tarde pero no estaba hecho el responsive de
  este
  sitio? Al entrar desde mobile se descajeta todo.
  El dic. 18, 2015 7:55 PM, "mkreyness"
  <notifications@github.com> escribió:

  > confirmame y los largo, son muchos y va a llevar muchas
  horas. O queres
  > que lo largue sabado a la mañana ?
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/218#issuecomment-165915323
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
Los de vendedores ya terminaron de salir. Te mande copia de prueba de representantes (el original me lo mande a mi, y eso te copia automaticamente), confirmame OK y lo largo.
Yo ni idea lo de responsive, eso lo maneja todo @FAAREIA desde CSS.

**Comment by FAAREIA** [comment]
qué hay de responsive? Acuerdense que no existe eso en los mailing

**Comment by LeandroBraier** [comment]
Me refiero a la plataforma web del torneo de potenciados. Siguiendo el link
que yay en el mailing entro y se rompe todo.

**Comment by FAAREIA** [comment]
Tienen un link con usuario y clave para probar?

**Comment by LeandroBraier** [comment]
Ahí te pasé acceso vía mail Fede.

Igual la semana que viene termina el concurso. Solo te preguntaba si te
acordes de haberlo hecho responsive o no, porque me parece recordar que lo
habías hecho.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si tenés razón. Recuerdo haberlo hecho responsive también, pero capas que de tanto cambio que hubo quedó sin hacer la última versión. Hasta 768px de ve bien (tablets), excepto esos títulos larguisimos que se van de caja.
Queres que lo hagamos responsivo?

**Comment by FAAREIA** [comment]
Tené en cuenta tamvbién que son pantallas de mucho dato, verlo en celular va a ser muy tedioso.

**Comment by LeandroBraier** [comment]
No vale la pena ya, porque el 31 se cierra el torneo y va a haber que ponerlo en offline al sitio y que redirija a parexklaukol.com.ar

Yo les aviso cuando igual.

abrazo
