### ISSUE TITLE
Nuevos mailings Cierre del Sorteo Comunidad de Vendedores. 18/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#219]
Buen día @FAAREIA !

Te paso pedido nuevo. Necesitamos un mailing que diga "Faltan 3 días para el sorteo" y "Quedan 24 hs para el sorteo" otro en base a las gráficas:

![posteo-cierre-sorteo](https://cloud.githubusercontent.com/assets/6719872/11181844/8640519e-8c44-11e5-9251-e924cc7270cc.png)
 que te paso acá: 

![posteo cierre sorteo](https://cloud.githubusercontent.com/assets/6719872/11181792/086a108e-8c44-11e5-8b31-d0e08caaadc6.png)

Debajo seguiría con el resto del mailing de Bienvenida como hacemos siempre. 

En este wetransfer tienen los PSD editables (tanto para 3 días como para 24 hs):

https://www.wetransfer.com/downloads/27182208eaf838b7dba5baa20e84d64520151116122633/8dcb3f1862c02454e55f040a1edca01620151116122633/f79631

Esto no es urgente ni prioridad.

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-cierre-dias/vendedores-cierre-dias.html

http://parexklaukol.com.ar/_mailing/vendedores-cierre-horas/vendedores-cierre-horas.html

**Comment by LeandroBraier** [comment]
Es la imagen, Fede, pero falta todo el resto del mailing de Vendedores, con el autologin, etc. Este también sería una adaptación del mailing de bienvenida. Siempre debemos incluir ene stos mailings la posibilidad de que no entienda qué es la Comunidad y que si quiere entrar en ese momento está claro y sea solo mediante un clic.

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-cierre-dias/vendedores-cierre-dias.html

Asi lea?
Avisame y lo replico en el otro.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto asi! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/vendedores-cierre-dias/vendedores-cierre-dias.html
http://www.parexklaukol.com.ar/_mailing/vendedores-cierre-horas/vendedores-cierre-horas.html

**Comment by LeandroBraier** [comment]
Están perfectos Fede. Gracias!

Solo te pido si a estos dos le podés sacar la línea de BIENVENIDOS A LA .
Solo eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!! Lo mando a aprobar entonces.

**Comment by LeandroBraier** [comment]
Está aprobado!

@mkreyness necesito que lo programes para mandar a TODA la base de vendedores potenciados el día 27/11.

Confirmame porfa.

abrazo

**Comment by LeandroBraier** [comment]
No aclaré, pero sería este el que hay que enviar:

http://www.parexklaukol.com.ar/_mailing/vendedores-cierre-dias/vendedores-cierre-dias.html

**Comment by mkreyness** [comment]
El feriado? Nadie lo va a ver

**Comment by LeandroBraier** [comment]
El 26 entonces.

**Comment by mkreyness** [comment]
Pero si lo mando el 26, es mentira que faltan 3 dias para el sorteo... Hay que corregir la grafica.

**Comment by LeandroBraier** [comment]
No, está bien. Hasta que lo reciban, lo abran y todo ya está, son 3 días.
Sino mandalo el 27 y listo. O el 28 mismo. Alguien lo va a ver, no te
preocupes. Como te venga bien a vos 26, 27 o 28.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
A mi me da igual, si te parece 27 lo hago el 27. De todos modos son muchisimos, asi que va a estar todo el dia mandando mails.

**Comment by LeandroBraier** [comment]
Por eso decia!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ok

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! No te olvides de dejar mandando este mail.

abrazo

**Comment by mkreyness** [comment]
no habiamos quedado que lo mandara mañana 27 al final ? Por el tema de lo que dice de cuantos dias faltan.

**Comment by LeandroBraier** [comment]
Yo me lo había dejado para hoy. Te diría que lo pongamos a enviar hoy por las dudas a partir del mediodía, ya que mañana es feriado. Hasta que lo lean son 3 días.

**Comment by mkreyness** [comment]
ok, ahora lo preparo y te mando uno de prueba.

**Comment by mkreyness** [comment]
con que "Asunto:" sale esto ?

**Comment by LeandroBraier** [comment]
Asunto: ¡Te quedan 3 días para sumar puntos y participar por la Notebook Asus de Noviembre!

**Comment by mkreyness** [comment]
te llego el de prueba ? Confirmame que este ok (el user/pass es de un vendedor cualquiera) y lo largo.

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti !! Necesito que me armes la versión de diciembre de este mailing que dice que faltan 3 días. Lo necesito para el lunes 28 bien temprano a la mañana.

@mkreyness esto deberíamos enviarlo así:

1) A todos los que ya tienen tickets en el sorteo del mes, con el subject "Aprovechá! Te quedan 3 días para seguir sumando puntos para el Gran Premio del Año en la Comunidad de Vendedores ParexKlauko!"

2) A todos los que todavía no tienen tickets en el sorteo del mes, pero otros meses sí los tuvieron, con el subject "¿Qué esperás? Faltan 3 días para el sorteo del Gran Premio del Año en la Comunidad de Vendedores ParexKlaukol y todavía estás a tiempo de participar"

3) A todos los que nunca participaron en ningún sorteo con el subject: "Esta es tu oportunidad de sumarte con todo a la Comunidad de Vendedores: Hacé más de 1000 puntos en un día y obtené 10 chances en el sorteo"

Tendría que salir el lunes 28 si o si. Porfa confirmame si estamos bien con esto MK.

abrazo y felicidades para ambos.

**Comment by braulio-evangelisti** [comment]
Sería igual pero en vez de noviembre sobre el premio va diciembre? o también cambia el premio?

**Comment by LeandroBraier** [comment]
El premio sería el de diciembre, Brau, el que ya maquetaste acá:

http://parexklaukol.com.ar/_mailing/vendedores-premio-fin-anio/premio-fin-anio.html

Llegás a armarlos mañana a la mañana así lo empezamos a enviar?

Aparte: Yo estoy en Venado si podés en la semana nos juntamos a tomar un café.

**Comment by braulio-evangelisti** [comment]
Ese lo maqueto Fede, ahi le pedi que me mande el psd con el premio asi mañana temprano armo la de Diciembre.

Dale arreglemos, yo al final viajo el miercoles a Venado, te mando un mensaje y me decis si podes por esos dias.

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-premio-anio-nuevo/vendedores-premio-anio-nuevo.html

Fijate si esta bien Lea!

Abrazo

**Comment by LeandroBraier** [comment]
Está perfecto Brau! Gracias!

Solo cambiale lo siguiente:

Donde dice:

"Hemos recibido tus datos personales y con ellos pudimos crear un acceso especial. 
Hacé click acá para logearte automaticamente."

Debe decir simplemente:

"Hacé click acá para logearte automaticamente."

@mkreyness podremos empezar a enviar esto hoy apenas Brau corrija este detalle?

http://parexklaukol.com.ar/_mailing/vendedores-premio-anio-nuevo/vendedores-premio-anio-nuevo.html

Recordá como son los tres grupos de envíos:

1) A todos los que ya tienen tickets en el sorteo del mes, con el siguiente subject:
"Aprovechá! Te quedan 3 días para seguir sumando puntos para el Gran Premio del Año en la Comunidad de Vendedores ParexKlauko!"

2) A todos los que todavía no tienen tickets en el sorteo del mes, pero otros meses sí los tuvieron, con el siguiente subject: 
"¿Qué esperás? Faltan 3 días para el sorteo del Gran Premio del Año en la Comunidad de Vendedores ParexKlaukol y todavía estás a tiempo de participar"

3) A todos los que nunca participaron en ningún sorteo con el siguiente subject: 
"Esta es tu oportunidad de sumarte con todo a la Comunidad de Vendedores: Hacé más de 1000 puntos en un día y obtené 10 chances en el sorteo"

abrazo

**Comment by mkreyness** [comment]
ok, voy preparando esas 3 variantes y cuando Braulio avise te mando prueba de c/u antes de largarlo.
Otra cosa: los mando en ese orden (1,2,3) ? Porque simultaneo obviamente no puedo.

**Comment by LeandroBraier** [comment]
Claro, por supuesto.. Si en ese orden perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-28 9:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Hecho

**Comment by mkreyness** [comment]
Te mando las 3 pruebas, @LeandroBraier .

**Comment by LeandroBraier** [comment]
Excelente! Gracias a los dos!

**Comment by LeandroBraier** [comment]
Recibí los mails de prueba @mkreyness 

Están OK. Solo te pido un pequeño agregado al subject 2)

"¿Qué esperás para sumar puntos? Faltan 3 días para el sorteo del Gran Premio del Año en la Comunidad de Vendedores ParexKlaukol y todavía estás a tiempo de participar"

Con esa corrección en el subject envíen tomás. Está todo perfecto.

abrazo

**Comment by mkreyness** [comment]
cambio hecho. Ahora largo 1 que es cortito (80 mails), despues 2 (232 mails, va a llevar hora y media), y a la tarde mando el 3 que va a llevar todo el resto del dia habil (1080 mails).

**Comment by LeandroBraier** [comment]
Excelente MK! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-28 11:21 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
acabo de controlar el ultimo envio y por razones que desconozco me cortaron el acceso a la base de datos cuando apenas iban 300 de los 1080 que tenia que mandar. Mando el resto ahora y lo controlo mas seguido, ok ?

**Comment by LeandroBraier** [comment]
Dale. Porfa. Gracias por revisar!

**Comment by mkreyness** [comment]
ahi estoy mandando el resto. Fue muy raro, despues de esos primeros 300 que pudo hacer, no tuvo acceso a la base de datos durante unos 700 mas, pero los ultimos 80 pudo hacerlos.

**Comment by mkreyness** [comment]
ahi si ya terminaron de salir todos bien.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti necesito una versión de este mailing sin el fragmento del premio.

http://parexklaukol.com.ar/_mailing/vendedores-premio-anio-nuevo/vendedores-premio-anio-nuevo.html

Es para enviar hoy mismo. Me confirmás si llegamos?

@mkreyness la idea sería que apenas llegues a las 16 hs lo envies a todos los usuarios menos los nuevos a los que ya les enviaste mailing esta semana.

**Comment by mkreyness** [comment]
ok, si ya esta armado hago una prueba y lo mandamos, pero ojo que es mucha gente, va a tardar una bocha.

**Comment by LeandroBraier** [comment]
No hay problema. @braulio-evangelisti pudiste ver esto?

**Comment by braulio-evangelisti** [comment]
Recien lo veo lea estuve con el de VIE TUR.

Algo asi te sirve?

http://parexklaukol.com.ar/_mailing/vendedores-premio-anio-nuevo/vendedores-premio-anio-nuevo-sin-premio.html

**Comment by LeandroBraier** [comment]
Está perfecto Brau!! Gracias!!

@mkreyness ponelo a enviar nomás porfa.

abrazo

**Comment by mkreyness** [comment]
Con que asunto ?

**Comment by LeandroBraier** [comment]
Igual que el mes pasado pero levemente modificado:

1) A todos los que ya tienen tickets en el sorteo del mes, con el subject "Aprovechá! Te quedan 3 días para seguir sumando puntos para el Premio de Enero en la Comunidad de Vendedores ParexKlauko!"

2) A todos los que todavía no tienen tickets en el sorteo del mes, pero otros meses sí los tuvieron, con el subject "¿Qué esperás? Faltan 3 días para el sorteo del Premio de Enero en la Comunidad de Vendedores ParexKlaukol y todavía estás a tiempo de participar"

3) A todos los que nunca participaron en ningún sorteo con el subject: "Esta es tu oportunidad de sumarte con todo a la Comunidad de Vendedores: Hacé más de 1000 puntos en un día y obtené 10 chances en el sorteo de Enero"

Podés dejarlos enviando en ese orden también.

abrazo

pd: Para Febrero podríamos convertir estos en templates y enviarlos yo programados desde mailchimp?

**Comment by mkreyness** [comment]
che no estan saliendo los mails de Klaukol.
Ya probe varias veces y no me llega nada.

**Comment by LeandroBraier** [comment]
Oh thats the question! Que puede ser?

**Comment by mkreyness** [comment]
Ahi probe de mandarte uno de estos mailings a vos. Fijate si te llega.

**Comment by mkreyness** [comment]
Ahi probe de nuevo a mi cuenta Fibertel y me llego bien. Te mande ahora a vos a GMail.
Confirmame si te llego y largo todo (aunque ya no faltan 3 dias...)

**Comment by LeandroBraier** [comment]
@mkreyness esto no se podrá dejar automático también, siempre 3 días antes del sorteo?

**Comment by mkreyness** [comment]
No se, a mi me dio tantas veces que se desconectaba la base...
No va  a cambiar nada de un mes a otro ? Ni el HTML, ni el subject ?
Las categorias 1 y 2 no habria problema, pero la 3 es muy larga y habria que controlarla manualmente cada tanto (y ni que hablar que mientras no se puede mandar otra cosa).

**Comment by LeandroBraier** [comment]
Ok. La lista 3 no la hagamos automática.

Respecto del mailing el actual es atemporal, no habla de premios. Vamos con
ese.

**Comment by mkreyness** [comment]
ok, entonces: en febrero (este febrero) correria el dia 26, los meses de 30 el dia 27 y los meses de 31 el dia 28, ok ?

**Comment by LeandroBraier** [comment]
Exacto.

**Comment by LeandroBraier** [comment]
@mkreyness quedó automático este mailing al final? No te olvides que mañana tendría que salir el mailing.

abrazo

**Comment by mkreyness** [comment]
No, de hecho el subject tiene que cambiar tambien, tengo que parametrizarle el nombre del mes y las fechas que analiza para ver si tuvo o no actividad, todo eso por ahora esta fijo.
Y está el problema de la "lista 3" (los que nunca se conectaron) que es muy grande y siempre se corta.
A la mañana temprano corro las listas  1 y 2 y si todo anda bien intento la 3, o ni vale la pena ?

**Comment by LeandroBraier** [comment]
Genial MK! Si podes intentalo con la 3 pero si lleva mucho tiempo para vos
dejalo y listo. Les enviaremos otro mail mas adelante.

Abrazo

**Comment by mkreyness** [comment]
ya lo parametrice, mañana entonces lo pruebo y lo mando.

**Comment by mkreyness** [comment]
ya termino de salir la 1, esta saliendo la 2 y me estoy yendo. Mas tarde me conecto y si veo que la 2 termino bien intento mandar la 3.

**Comment by LeandroBraier** [comment]
Perfecto. Mil gracias MK!

**Comment by mkreyness** [comment]
Ahi largue la 3.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Me anoto recordarte enviar esto de nuevo el próximo mes.

abrazo
