### ISSUE TITLE
Programación en Sitio Parex: Cotizador + Simulador de Fachadas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#22]
En este caso, necesitamos que backupees y reconstruyas en nuestro hosting los siguientes dos motores:

Cotiza tu obra (Parex)
http://www.parexklaukol.com.ar/cotiza-tu-obra

Simulador de Fachadas (Parex)
http://www.parexklaukol.com.ar/simulador-de-fachadas

Este sitio también va a estar subido por Fede al hosting Onyx de Klaukol, así que cuando los tengas backupeados podrías subirlos allí mismo y los probamos.

abrazo

**Comment by LeandroBraier** [comment]
MK, cómo venís con esto?

Tenemos posibilidad de tenerlo backupeado para el jueves? (Aunque no esté activo en el nuevo hosting, simplemente con toda la información segura a salvo en el hosting o en tu máquina)

**Comment by mkreyness** [comment]
todo esto esta backupeado. Que funcione es otra historia.

**Comment by LeandroBraier** [comment]
Marce, para cuando pueden estar listos y funcionando el Cotizador y el Simulador de Fachadas y cuántas horas te llevarían?

Necesitaríamos tener estos elementos de la versión 2.0  para la última semana de Junio máximo.

**Comment by mkreyness** [comment]
Veo muy dificil TODO para la misma fecha. Puedo ir encarando de a un 
tema por vez, pero no tengo el tiempo material para hacer TODO de aca a 
fin de mes.

Se usa esto

http://72.52.188.248/_parex/calculador.html

o hay definida otra interface ?

Tenemos la formula de calculo ?
Aparentemente los parametros son:
     - donde
     - soporte
     - tipo de pieza
     - grado de absorcion
     - medidas
     - m2

Y para el simulador:
http://72.52.188.248/_parex/simulador.html#

Reusamos eso o hay otro diseño ?

Si bien tenemos todos los elementos sueltos, hay que entender como 
aplicarlos.

**Comment by LeandroBraier** [comment]
1) Estás confundiendo el calculador con el "cotiza tu obra"

Solía estar en esta URL:

http://www.parexklaukol.com.ar/cotiza-tu-obra

Decime que lo tenemos backupeado porfa.

2) El simulador tal cual. Reusamos eso que hay pero hagamoslo funcionar bien.

**Comment by mkreyness** [comment]
Tranquilo, todo esta backupeado, es esto ?

http://72.52.188.248/_backup/parexklaukol/cotiza-tu-obra.html

Sigue siendo un flash:

http://72.52.188.248/bkps/parexklaukol.com.ar/media/wysiwyg/calculador.swf

Siendo que no podemos cambiarle nada, lo podemos poner tal cual ?

**Comment by LeandroBraier** [comment]
Genial! Pongamoslo tal cual.

**Comment by mkreyness** [comment]
Ehh, si, pero todo lo de alrededor hay que darle el aspecto actual y los 
links correctos.
No es que yo quiera sobrecargarlo con mas trabajo a Fede, pero es solo 
un tema de maquetacion y que adentro tenga esto:

<object width="760" height="350" data="media/wysiwyg/calculador.swf" 
type="application/x-shockwave-flash"><param name="src" 
value="media/wysiwyg/calculador.swf"></object>

**Comment by mkreyness** [comment]
```
Del simulador de fachadas ya deje andando algo aca:

pero como te digo en los otros, es mas un tema de cambiar el
contexto que del contenido, que ni podemos tocar.
```

http://www.parexklaukol.com.ar/aplicaciones/simulador-de-fachadas.html

```
El 10/06/2015 a las 20:01,
  LeandroBraier escribió:


  Genial! Pongamoslo tal cual.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto. Entonces solo queda que Fede lo suba a la web?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-12 9:32 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Para mi primero hay que remaquetarle todo lo de alrededor, fijate que 
habla de gleepa y tiene links a cosas viejas.
