### ISSUE TITLE
Reenvío de Mailing de Bienvenida a todos los Vendedores que no entraron este mes

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#220]
Buen día @mkreyness ! Cómo fue el finde?

Consulta técnica: ¿podemos hacer un envío del mailing de bienvenida de este mes a todos los usuarios que no entraron ni 1 vez a la plataforma en Noviembre?

En caso contrario, deberíamos enviarlo a todos los que aún no le enviamos mailing de bienvenida este mes (es decir, a todos los usuarios "no nuevos")

abrazo

**Comment by mkreyness** [comment]
Bien en el sentido de que descansé un poco, mal en el sentido de que no avance con nada :(

Cuando decis que no entraron ni 1 vez en noviembre implica que si alguien entro por ultima vez el 31 de Octubre TENGO que madarselo ?

**Comment by LeandroBraier** [comment]
Mejor aún MK! Para nosotros es fundamental que descanses cada tanto, te queremos bien!! jaja

Respecto tu pregunta si, si entró por última vez 31 de octubre le mandamos igual.

**Comment by mkreyness** [comment]
Ok, y si alguien entro NUEVO en noviembre pero nunca entro (por ej, porque le mande el mail la semana pasada) TAMBIEN se lo remando ?

**Comment by LeandroBraier** [comment]
No, no. A los que ya les mandamos un mailing en noviembre no.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-16 10:04 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ok, tengo que ver cuales son porque no tengo en la base una fecha de alta. Que tiene prioridad, esto o lo de Torneo ? Porque puedo ponerme con uno de ellos ahora pero el otro va a tener que quedar para la tarde.

**Comment by LeandroBraier** [comment]
Prioridad ahora el de Torneos. Este puede quedar para la tarde sin
problema.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-16 10:37 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
como veo que lo de Torneos viene demorado voy a ir mandando esto, ok ? Te mando primero una prueba como siempre.

**Comment by mkreyness** [comment]
bah, en realidad el mailing es el de siempre, lo unico que tiene de especial es el conjunto de gente que lo recibe, si queres lo largo ya y listo.

**Comment by LeandroBraier** [comment]
Dale, de una.

**Comment by mkreyness** [comment]
Le mando primero a los que nunca entraron, que son mas de 800.

**Comment by LeandroBraier** [comment]
Perfecto.
