### ISSUE TITLE
Nuevos Juegos para Eventos Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#221]
@mkreyness te escribo solo para ir tanteando terreno. Propusimos una serie de juegos muy sencillos a la gente de Klaukol y quería ir calculando tus horas para desarrollar. En realidad son landings web muy sencillas.

EVENTO 1: Adjunto word con dos dinámicas, son de preguntas y respuestas que se responden via login en la landing y los resultados se mostrarían en una segunda parte de la landing.

[Propuesta Parex Debate_OK.docx](https://github.com/LeandroBraier/Klaukol/files/37225/Propuesta.Parex.Debate_OK.docx)

EVENTO 2: Te lo hago simple. Es un juego con makey makey que, al igual que ya hicimos, requiere que 5 personas se tomen de la mano y cierren el circuito para que una luz pase de roja a verde. Es prácticamente igual si bien la dinámica que las personas deben hacer presencialmente es diferente. 

Tirame un estimado de horas para cada juego solo para tener una idea.

Lo de Fede sé que no es demasiado porque la estética es muy simple.

abrazo

**Comment by mkreyness** [comment]
Le prometi a MS darle bola a DelViento esta noche, antes de meterme con mas cosas tengo que cerrar las que estan abiertas.  Te contesto esto mañana a la mañana puede ser ?

**Comment by LeandroBraier** [comment]
Por supuesto MK. No hay apuro. Mañana a la tarde tranqui.

Abrazo

**Comment by mkreyness** [comment]
Se canceló esto? Estuve a full con lo de DelViento (y tengo que seguir) y ni lo miré

**Comment by LeandroBraier** [comment]
Si no te preocupes. Eligieron otra opción que no lleva programación en
principio
