### ISSUE TITLE
Cuestión /novedades/

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#222]
@FAAREIA fijate lo que ocurre si voy a:

parexklaukol.com.ar/novedades/

Porfa hacé que reenvíe a 

parexklaukol.com.ar/novedades.html

abrazo

**Comment by FAAREIA** [comment]
Desde que link llegas a /novedades/ ? En la web no lo forma de acceso a esa url.
@mkreyness creo que el objetivo sería evitar ese enlistado de directorios y archivos.

**Comment by mkreyness** [comment]
El problema es que no hay un index.html en esos directorios.
se puede poner un index.cgi que redirija a /novedades/novedades.html mas que tirar un error.

**Comment by mkreyness** [comment]
listo, ya lo puse en el de klaukol arg, ahora lo replico en los otros.

**Comment by LeandroBraier** [comment]
Perfecto! Gracias a los dos!

En realidad es baja la posibilidad de que alguien llegue (a mi me pasó por un error en un link de Facebook por ejemplo) pero no cuesta nada redireccionar por las dudas no?

abrazo y gracias otra vez

**Comment by LeandroBraier** [comment]
Apa, @mkreyness ojo que en Argentina está redireccionando a:

http://www.parexklaukol.com.ar/novedades/novedades.html

Y debería redireccionar a:

http://www.parexklaukol.com.ar/novedades.html

No sé por qué pero se ven noticias viejas en el otro.

**Comment by mkreyness** [comment]
ah, ok, ahora lo cambio. Entonces directamente el /novedades/novedades.html no tendria que existir.

**Comment by LeandroBraier** [comment]
Tal cual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
