### ISSUE TITLE
Comunidad de Vendedores: Agregado de Sección Ganadores en home. 20/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#223]
@FAAREIA necesitaríamos agregar una sección arriba del video de "Cómo funciona", es decir, debajo del slideshow, donde se vean siempre los últimois 4 ganadores de la página de ganadores. 

El título de esta sección sería ÚLTIMOS VENDEDORES PREMIADOS y el link llevaría a la página de ganadores.

Podrás tenerlo subido para el viernes? 

abrazo

**Comment by FAAREIA** [comment]
Ahi te mando el ejemplo Lea, ya esta maquetado pero oculto actualmente. Si esta OK habría que meterle la programación @mkreyness 
![prueba](https://cloud.githubusercontent.com/assets/6184969/11274558/27372daa-8eb8-11e5-9c62-ad45548f37f7.png)

**Comment by LeandroBraier** [comment]
Buenisimo Fede!!

Lo mando a aprobar y les digo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-19 12:22 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Está OK Fede! El cliente confirmó. Agreguémosle un link abajo de la sección que diga: "Conocé todos los ganadores de la Comunidad." que también lleve a la sección de ganadores. Avancemos.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya esta listo.
@mkreyness fijate que en mainT.html esta el bloque nuevo con clase `ultimos-ganadores` pero con un `style="display: none"`.
Habría que traer los últimos 4 ganadores en los `<li>`

Una vez preparado, sacarle el `style="display: none"` y listo

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Espero a @mkreyness ahora entonces.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness como viene esto?

**Comment by mkreyness** [comment]
Acabo de enterarme. Y yo como se quienes son los ganadores ? Es un sorteo no ?

**Comment by mkreyness** [comment]
Habria que agregar en el CMS algo que permita ingresar la lista de ganadores, con el mes, es uno por mes o podrian ser varios ?

**Comment by LeandroBraier** [comment]
Marce, eso ya existe en el CMS. Yo ya los cargué todos. Esto es sólo agregado en la home para que se vean los 4 últimos ganadores y se linkee esa sección.

**Comment by mkreyness** [comment]
La Cerveza Altzheimer me esta pegando fuerte.
De alguna manera lo estabamos mostrando ya en algun lado, no ?
Despues de la reunion lo agrego en la home.

**Comment by LeandroBraier** [comment]
jajaj si!

Acá:

www.parexklaukol.com.ar/cgi-bin/ganadores.pl

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-25 15:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, ya quedo andando

**Comment by LeandroBraier** [comment]
@mkreyness no lo subamos a producción todavía. NO está OK. 

1) Las fotos se muestran mal, donde cargo la foto adaptada?

2) Los títulos que muestra está mal. Sacalo de producción urgente porfa.

**Comment by mkreyness** [comment]
Ahi lo escondi.
Las fotos son las que estan en el CMS para ganadores, queres que agregue un campo para una foto diferente ?
Los titulos son los que estan cargados en el CMS, los mismos que se ven cuando entras en ganadores.pl

**Comment by LeandroBraier** [comment]
SI, el titulo que estaba mal ya lo corregí en el CMS pero la imagen que tomás es la incorrecta. Debés tomar el thumbnail, que es más chico, no tiene carteles y muestra limpia la cara del ganador.

**Comment by LeandroBraier** [comment]
Dejame verlo antes de publicarlo. Si eso no funciona automáticamente para todos avisame y abrime un espacio en el CMS apra subir esa foto aparte.

**Comment by mkreyness** [comment]
fijate ahora, esto es version de prueba:
http://www.parexklaukol.com.ar/cgi-bin/mainvendedores2.pl?usuario=Marcelokreyness&clave=pepe

**Comment by LeandroBraier** [comment]
Si ahora si! Gracias!

**Comment by mkreyness** [comment]
lo pongo en produccion entonces ?

**Comment by LeandroBraier** [comment]
Ponelo nomás.  Abrazo

**Comment by FAAREIA** [comment]
Lo veo que esta ahi pero oculto, lo pongo visible?

**Comment by LeandroBraier** [comment]
Dale, subilo nomás Fede. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
estaba oculto porque cuando lo puse visible no le gusto lo que vio :)

**Comment by mkreyness** [comment]
Yo veo que sigue oculto. Ahora lo pongo visible.

**Comment by FAAREIA** [comment]
Ahi ya lo vi, gracias marce. Me ganaste de mano ^^

**Comment by LeandroBraier** [comment]
Gracias a los dos!!! Quedó muy bien ahora.

abrazo
