### ISSUE TITLE
Reunión via Skype Mañana

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#224]
@braulio-evangelisti podrás sumarte a reunión por skype mañana dentro de la mañana? Tipo 11 am por ejemplo?

**Comment by braulio-evangelisti** [comment]
Si Lea. voy a estar conectado a esa hora. Abrazo.

**Comment by LeandroBraier** [comment]
Joya Brau. Quedamos a esa hora entonces.

abrazo
