### ISSUE TITLE
Consulta DEFINITIVA por Posteos Compartidos en Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#225]
@mkreyness me pasa lo siguiente.

Siempre me recontra mareo cuando tengo que cargar un posteo a compartir de vendedores. Me pasa tanto con los posteos de imagen como los posteos de LINK. Me lleva siempre mucho tiempo cargarlos porque nunca recuerdo como hacerlo. Me lo explicarías clarito?

Para ir a lo concreto, el tema en cuestión hoy es este:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=25&usuario=LeanBraier&clave=parex

El link que necesito que aparezca con el botón de compartir es este:

https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2Fparexklaukolarg%2Fphotos%2Fa.722794467842900.1073741830.692680497520964%2F795248717264141%2F%3Ftype%3D1%26amp%3Btheater&pnref=story

Qué url debería ingresar en el cms para que me aparezca ese link y funcione OK?

**Comment by mkreyness** [comment]
Es que no hay forma de forzar la foto en el link, FACEBOOK toma lo que figure como foto asociado a la pagina, no lo que vos pongas en el link. A VECES anda, pero no se de que depende.
Hay alguno anterior que este andando bien ?

**Comment by LeandroBraier** [comment]
Había.  Yo te pregunto porque me parece que el cms agrega un código al link
automáticamente.  Puede ser? Me pareció que le dejaste una parte de la url
que se agrega sola puede ser?

**Comment by LeandroBraier** [comment]
O sea, fíjate que el link ese que te pasé funciona solo. No veo por qué no
podríamos ponerlo en un botón. Por eso te aclaré también que no es igual el
posteo de link. Son links muy muy específicos de facebook. El posteo de
link es uno que si logramos que funcione (ver id=24) y Pero el de imagen es
distinto.

**Comment by mkreyness** [comment]
es que son urls encoded y embedded dentro de otros urls, y pasan por muchas etapas de interpretacion y en algun punto se corta. POR EJEMPLO, si la foto tiene un blanco en el nombre (cosa que siempre pido que no hagan) se corta y no lee el resto.
No yo, el sharer.php de facebook que estas invocando. Entonces al no encontrar una imagen ahi, toma la que esta en la pagina.

**Comment by mkreyness** [comment]
y el otro tema es que lo que vos tenes es un link, pero lo estamos poniendo en un BOTON, no es lo mismo.
Para que ese link tenga el ASPECTO del boton de facebook, va con una clase que le agrega otros atributos (como por ejemplo una imagen, que va la unica que el "juego" conoce, que no es la que vos estas poniendo embedded en el link.

**Comment by mkreyness** [comment]
ya entendi: habia un sharer.php de mas.
Vos no tenes que ponerlo en el URL, estas copiando cosas que EL BOTON (no yo) ya hace automaticamente. Fijate como quedo ahora y sobre todo fijate bien el URL que deje en el tema. NO dice sharer.

**Comment by LeandroBraier** [comment]
Claro, a eso me refería. Que el sistema le agregaba algo al principio pero
no sabía qué.

El problema es que ahora me comparte un posteo viejo, no el que quiero yo
que comparta, que es este:

https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/809238195865193/?type=3&theater

Como hago? reemplazo el suspuesto ID y me queda asi, pero igual no me
funciona:

https%3A%2F%2Fwww.facebook.com
%2Fparexklaukolarg%2Fphotos%2Fa.722794467842900.1073741830.692680497520964%2F809238195865193%2F%3Ftype%3D1%26amp%3Btheater&pnref=story

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-19 23:28 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No iba el de los dos tipos ? Yo puse eso porque era lo que venia en el link que me pusiste.

**Comment by LeandroBraier** [comment]
Claro ahi me equivoqué yo al pasarte ese posteo pero tipo de link estaba OK. Con lo cual pensé que cambiando el ID simplemente iba a funciona, pero no lo hizo.

Te fijás porfa qué pasa? El link final que necesito que le aparezca a la gente cuando presiona el botón es este:

https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2Fparexklaukolarg%2Fphotos%2Fa.722794467842900.1073741830.692680497520964%2F809238195865193%2F%3Ftype%3D1%26amp%3Btheater&pnref=story

Qué es lo que le agrega el botón? El sharer nada más? Sería todo esto entonces:

https://www.facebook.com/sharer/sharer.php?u=

No?

Confirmame porfa. Estoy probando solo con la parte restante de ese y no me funciona.

**Comment by LeandroBraier** [comment]
Che, ahora que estás de vuelta, podemos dejar resuelto esto?

**Comment by mkreyness** [comment]
Si, a ver dejame que yo lo cambio y veo.

**Comment by mkreyness** [comment]
Ahi lo puse (entre al link que pegaste arriba, copie DE NUEVO lo que figuraba en el URL despues del "?u=", y lo pegue en el TEMA. 
Al menos a mi me anda perfecto el "compartir" entrando al tema desde el sitio. Fijate vos.

**Comment by LeandroBraier** [comment]
Nop, me sigue apareciendo mal. Si lo que ves es esto no está bien:

<img width="600" alt="captura de pantalla 2015-11-20 a las 8 03 40 p m" src="https://cloud.githubusercontent.com/assets/6719872/11313918/9b4afa52-8fbf-11e5-9ccd-cc65eff5c757.png">

Lo que tiene que aparecer es esto:

<img width="1423" alt="captura de pantalla 2015-11-20 a las 8 06 33 p m" src="https://cloud.githubusercontent.com/assets/6719872/11313966/f7041d4c-8fbf-11e5-9a33-2b9ab9756cc1.png">

Yo lo despliego con este link:

https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.facebook.com%2Fparexklaukolarg%2Fphotos%2Fa.722794467842900.1073741830.692680497520964%2F809238195865193%2F%3Ftype%3D1%26amp%3Btheater&pnref=story

**Comment by mkreyness** [comment]
Entiendo. Aca hay una mezcla de cosas.
En realidad el boton no pone el "sharer" sino que llama al "feed" del API.
Pero eso tira un error.
Por eso le estamos forzando el sharer para evitarlo, pero esta mal.
Hay que estudiar bien ese error que tira, porque el feed deberia funcionar.
Dejame que lo veo mas tarde.

**Comment by LeandroBraier** [comment]
Sino no podemos forzarle el sharer y que no llame al feed del API? Que funcione como un simple link que lleve ahí? 

Lo que me gustaría es que dejemos esto resuelto de una vez porque nos pasó varias veces ya.

**Comment by mkreyness** [comment]
el problema de hacer eso es que no recibo el FEEDBACK que me permite sumar los puntos.

**Comment by LeandroBraier** [comment]
No podés tomarlo como un botón cualquiera? Tomar la imagen nomás del botón
de compartir pero usarlo como un botón cualquiera. No hace falta saber si
después compartió o no, simplemente si presiona el botón le sumamos los
puntos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si, pero Fede tiene que dibujar el boton, si uso ESE boton, siempre va a llamar al feed.

**Comment by LeandroBraier** [comment]
Si te paso este no te sirve?

https://www.mjf.com.uy/clientes/serorganico/compartir.png

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
si, ok.
Estoy al borde del desmayo, mañana lo hago.

**Comment by LeandroBraier** [comment]
Ok, MK. Que te mejores!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Gracias. Es agotamiento mas que dolor. Odio el mes de Jodiembre.

**Comment by mkreyness** [comment]
Miralo ahora!. Deje lo mismo de siempre pero puse el URL en el tema TOTALMENTE NORMAL, sin ninguno de esos  %2F%2F de porqueria que proponia el sharer de facebook y LE SAQUE toda referencia al sharer de facebook. Ahora, que esta hecho como estaba pensado desde un principio, funciona fantastico.
Confirmame si lo ves bien y hago el cambio en los URLs de todos los anteriores para que sean compatibles con haber sacado ese maldito sharer.php que no habria que haber usado jamas.

**Comment by LeandroBraier** [comment]
Quedó perfecto MK!! AL FIN LA SOLUCIÓN DEFINITIVA!! Gracias MK!

Ya lo corregí yo en los demás posts. Incluso en los de Link, es mucho más
simple ahora. Solo hay que colocar el link original del posteo y chau, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-21 9:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
EXACTO !

**Comment by LeandroBraier** [comment]
gracias una vez más MK!! abrazo y buen finde
