### ISSUE TITLE
Bug en CMS Torneo de Potenciados Slides

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#226]
@mkreyness subí una imagen para un mailing como slide pero en modo suspendido y aparece publicado. Te fijás qué pasa porfa?

abrazo

**Comment by mkreyness** [comment]
Estoy viendo que no le da bola al estado sino al numero de orden.
Preventivamente ponele numero de orden 0 y no va a salir. Despues con mas tiempo lo ajusto para que mire ambas cosas.

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-20 9:31 GMT-03:00 mkreyness notifications@github.com:
