### ISSUE TITLE
Mailing de Bienvenida de Diciembre Vendedores Potenciados. 23/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#227]
@FAAREIA y @braulio-evangelisti necesitamos un mailing más para Vendedores. Esto es para el lunes tranqui.

Les mando en este wetransfer la gráfica del flyer que estamos usando. Lo que tiene que decir la imagen del premio es "Como no paramos de crecer, cerramos el año con todo!" y GRAN PREMIO DE DICIEMBRE más la gráfica del premio con su detalle de que es cada cosa, como está en el flyer.

https://www.wetransfer.com/downloads/12ab3a5266dcf169a9e9d98a3ed7a9cc20151120142217/e6bc24de7230f107f008a6e9cb1c198220151120142217/923e12

Confirmenme si está todo OK. 

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-premio-fin-anio/premio-fin-anio.html

**Comment by LeandroBraier** [comment]
jajaja Lamentablemente no era tan fácil @FAAREIA jej Hablalo con @braulio-evangelisti : 

1) Es un mailing de la Comunidad de Vendedores. Todos los mailings de la comunidad son un mailing de Bienvenida adaptado, es decir, falta todo lo de abajo.

2) No enviamos más imágenes sueltas así como mailing, que corren gran riesgo de caer en spam. Las maquetamos adaptándolas con ciertos truquitos responsive que adquirimos en los últimos tiempos, te acordas? Como ese mailing de confirmación que te mandé hace mucho? 

Hablalo con Brau. Él sabe que yo le mando la gráfica en PSD para que él pueda adaptarlo a mailing, no solo pegando la imagen sino maquetandolo y haciéndola una adaptación pensada.

abrazo

**Comment by FAAREIA** [comment]
Ahora si:
http://parexklaukol.com.ar/_mailing/vendedores-premio-fin-anio/premio-fin-anio.html

Igual acordate que no existe lo responsive en los mailing. No hay posibilidad alguna de hacerlo responsive. Ahora si el mailing es puro texto con 1 logo, si se puede poner ancho máximo 640px y si es más chico que se adapte, pero cuando hay imágenes forzar eso hace que quede todo roto, y eso tampoco es responsive.

**Comment by LeandroBraier** [comment]
Perfecto Fede. Si lo recuerdo. Por eso digo "pequeños trucos responsive".

GRacias por el mailing! Lo hago aprobar y te digo.

abrazo

**Comment by LeandroBraier** [comment]
Está aprobado @FAAREIA ! 

Lo paso a @mkreyness para que programe el envío para el día 1 de diciembre, desde lo más temprano que pueda, tipo 8 AM.

abrazo

**Comment by mkreyness** [comment]
Recordame por si acaso un par de dias antes para que lo probemos.

**Comment by LeandroBraier** [comment]
@mkreyness te recuerdo: probemoslo así mañana lo enviamos.

abrazo

**Comment by LeandroBraier** [comment]
Recibí la prueba MK!!

Pero me llegó con un par de errores, mirá:

<img width="727" alt="captura de pantalla 2015-11-30 a las 8 02 20 p m" src="https://cloud.githubusercontent.com/assets/6719872/11486963/0dee7eac-979b-11e5-8a6f-649b6821d791.png">

<img width="983" alt="captura de pantalla 2015-11-30 a las 8 03 11 p m" src="https://cloud.githubusercontent.com/assets/6719872/11486970/1870dbea-979b-11e5-9b4f-64fba257c533.png">

Me parece que tiene que ver con el código HTML

**Comment by mkreyness** [comment]
Hay un par de imagenes mal porque estan puestas con URLs relativos en vez de absolutos.
Ahora lo arreglo yo y lo remando (y lo del final es lo de siempre, falta un enter, ya lo agrego).

**Comment by LeandroBraier** [comment]
Ahora si, perfecto el mailing MK!

Mañana empecemos a enviarselo de nuevo a toda la base.

abrazo

pd: si querés esperar, mañana a la mañana te paso acceso a mailchimp así
intentás llamar al api de mailchimp y dejás seteado para que yo pueda
enviar este tipo de mails customizados y te ahorre todo este engorro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
no me da el tiempo para mirar lo de mailchimp a la mañana, ya que me voy y no vuelvo hasta las 4.
Mejor lo largo como siempre.
Ademas hay una parte variable en cada mail (los datos del login) seguro que hacer eso con el mailchimp va a ser mas complicado que con mis propios programas.

**Comment by mkreyness** [comment]
ya estan saliendo a toda la base.

**Comment by LeandroBraier** [comment]
Gracias MK! Hasta que hora estas en tu casa? Asi te paso el codigo de
acceso de mailchimp que dura 45 segundos y ya te queda abierto el acceso.

**Comment by mkreyness** [comment]
a eso de las 4 estoy en mi oficina. Pero no entiendo, si dura 45 segundos, de que sirve ?

**Comment by LeandroBraier** [comment]
Despues te queda accesible por 10 días, pero el código de google
authenticator se regenera cada 45 segundos. En fin, lo dejamos para otro
día no te preocupes. En la próxima reunión de Siguit.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
