### ISSUE TITLE
Bug en Club de Colocadores: Carga de datos en perfil

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#228]
El usuario quiere actualizar sus datos y no se le guardan. Puede ser porque no tiene confirmado el usuario via mail de confirmación?

A mi me pasa lo mismo con tu usuario de "marcelokreyness"

**Comment by LeandroBraier** [comment]
@mkreyness cuando puedas fijate este bug porfa.

**Comment by mkreyness** [comment]
no lo habia visto. Ahora pruebo con el mio.

**Comment by mkreyness** [comment]
recien probe con el mio, le cambie el telefono y lo tomo lo mas bien. Lo que si hay campos que estan bloqueados, pero entiendo que eso es a proposito.
Que campo quisiste cambiar en mi perfil y no te dejó ?

**Comment by LeandroBraier** [comment]
El de fecha. Me pasó a mi y a un usuario.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ok, es cierto y ademas poner un mensaje equivocado. Ahora lo miro.

**Comment by mkreyness** [comment]
ya lo arregle pero igual le falta algo para que aparezca el date picker.
@FAAREIA que js habria que agregar aca para que aparezca ?
http://www.parexklaukol.com.ar/cgi-bin/perfilcolo.pl?usuario=marcelokreyness&clave=pepe

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Genial gracias!!!
