### ISSUE TITLE
Newsletter Klaukol de Diciembre. 25/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#229]
@FAAREIA En este Google Doc tenés todos los contenidos, incluidos los textos y links de las imágenes.

https://docs.google.com/document/d/1YijdDVOCZYcfBvKncYf1A3F40qm6c0JaTVJ4xg09BfI/edit

El news armalo directamente en una maqueta igual a esta solo que con los nuevos contenidos de texto e imagen:

http://parexklaukol.com.ar/_mailing/novedades-noviembre/novedades-noviembre.html

El footer queda tal cual. Los links a las notas los sumo esta semana, apenas los tengo.

abrazo

pd: Esto lo hace siempre Brau en un toque por si querés pasárselo a él.

**Comment by braulio-evangelisti** [comment]
Aca te paso el link Lea

http://parexklaukol.com.ar/_mailing/novedades-diciembre/novedades-diciembre.html

Le quedan los links a las notas cuando esten y listo.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! Te aviso cuando el cliente me de el OK

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Está OK el newsletter!!

Agregale los links que te paso a continuación y confirmame cuando lo tengas así ya lo enviamos.

http://www.parexklaukol.com.ar/novedades/arquitectura-sustentable-por-tyin-tegnestue-architects.html

http://www.parexklaukol.com.ar/novedades/qu%C3%A9-ten%C3%A9s-que-saber-antes-de-armar-una-parrilla.html

http://www.revear.com.ar/productos/linea-premium-2/revividor-colores-revear.html

http://www.parexklaukol.com.ar/novedades/parexgroup-y-el-cayc-entregaron-a-los-premiados-el-libro-%E2%80%9Cventanas-al-futuro-10-a%C3%B1os%E2%80%9D-.html

http://www.parexklaukol.com.ar/novedades/parexgroup-participo-en-el-encuentro-tendiez-experiencias-.html

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea. 

Ahi le agregue los links a la notas. Actualizá nomás.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-03 10:13 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti !

Necesito que hagas una segunda versión del news con las dos fotitos de las notas de abajo diferentes:

PAREXGROUP Y EL CAYC ENTREGARON A LOS PREMIADOS EL LIBRO "VENTANAS AL FUTURO 10 AÑOS"

![ventanas 2015-230](https://cloud.githubusercontent.com/assets/6719872/11579913/eb94c294-9a10-11e5-807c-4b6737c3c12c.jpg)

PAREXGROUP PARTICIPÓ EN EL ENCUENTRO TENDIEZ EXPERIENCIAS

![tendiez cordoba colmo el auditorio del hotel y111](https://cloud.githubusercontent.com/assets/6719872/11580015/14e39606-9a12-11e5-8d06-4fcac56b4e43.jpg)

Lo más temprano posible mejor.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea aca te paso el link
http://parexklaukol.com.ar/_mailing/novedades-diciembre/novedades-diciembre-2.html

Abrazo!

**Comment by LeandroBraier** [comment]
Está perfecto Brau!!! Gracias!!

abrazo
