### ISSUE TITLE
Programación en Sitio Revear: Calculador de Consumo + Buscador Distribuidores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#23]
Marce, en este caso necesito que backupees y reconstruyas estos dos motores:

Calculador de Consumo
http://www.revear.com.ar/calculador-de-consumo

Buscador Interactivo de Distribuidores (no es lo mismo que la Guía de Corralones, es otra cosa)
http://www.revear.com.ar/distribuidores

cuando los puedas subir al hosting los probamos.

abrazo

**Comment by mkreyness** [comment]
Esto lo veo mas dificil porque seguro en ambos casos accede a datos de la base de ellos, desde nuestro servidor NO tenemos permiso para hacerlo.

**Comment by LeandroBraier** [comment]
Respecto de Distribuidores:

Yo te consigo la base. Le puedo pedir la lista a la marca, pero no podés chupar el código de eso?

Respecto de Calculador de Consumo es similar al de Materiales. Ese lo podés chupar del front, no?

**Comment by mkreyness** [comment]
Si es codigo javascript, si, si es codigo php no, pero deberia estar en los backups que mandaron, eso lo tenia Fede en su maquina.

**Comment by mkreyness** [comment]
Por lo que pude ver el asunto es que el resultado que trae no es solo un calculo sino una lista de recomendaciones de productos. Sabemos que no son muchos, pero los criterios por los cuales decide recomendar uno u otro y por que una cantidad de uno y no otra cantidad de otro NO esta en el javascript, es una logica PHP que "chupando" el sitio no aparece, eso hay que buscarlo buceando en el backup gigante y lleno de basura que tiene Fede una vez que este pasado al servidor (no se si hay espacio suficiente).
Ademas todavia esta corriendo el programa que "chupa" todo, ni idea cuantas horas le falta para terminar pero ya se bajo tambien sus buenos 3.6Gb y no creo que haya hecho ni lamitad. Esto es de TODO lo accesible desde parexklaukol, incluyendo seguro mucha basura inusable, pero prefiero backupear de mas que de menos. Les cuento cuando termina.

**Comment by LeandroBraier** [comment]
Dale. Hagamos eso. Como hablamos con Fede en el skype de hace 2 semanas,
los criterios yo los puedo pedir. Además, sabemos que en las versiones 1.0
no van a estar estas herramientas. Lo importante es que el proveedor
anterior no se quede con nada importante nuestro, saquemos todo lo que
podamos. Después si nos lleva más tiempo reconstruirlo lo podemos resolver.
El tema es que a la hora de reconstruirlo no nos falten elementos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-21 8:18 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
La veo dificil buscar un arhivo PHP entre tantos GB de archivos. Más allá de eso, el mismo CMS puede tener una herramienta para meter código php ahi mismo, por lo que el código quedaría en la base de datos, ni siquiera en un template.

**Comment by mkreyness** [comment]
Es al reves, para acceder a la base de datos llama a unos php, los nombres son visibles en las paginas de calculador, una vez que este bajado el backup gigante al server (si es que esta ahi) yo lo encuentro, no te preocupes, lo que nunca va a funcionar es ejecutarlo

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
MK, estoy repasando estos elementos de Revear.

Te paso feedback para avanzar con cada uno.

CALCULADOR DE CONSUMO: Cada producto de Revear tiene una medida de rendimiento de kg por m2. Por ejemplo: Reveplastear rinde de 1 a 1,3 kg/m2. Cuando pongo en el Calculador 100 m2 me tira que necesito 130 kg de Reveplaster. Esto significa que toma el máximo dentro del rango y lo multiplica por los metros cuadrados simplemente. Con esto ya tenés la base para armar este calculador sin problemas. Simplemente tendrías que tener los rendimientos de cada uno de los productos que aparecen en el calculador. Yo te mando la lista en un toque.

BUSCADOR DE DISTRIBUIDORES: Si podés reponer la base como dicen con Fede genial. Sino necesito al menos que tengas generado el html o js del buscador para subirle la lista cuando el cliente me la mande. Ya se la pedí.

abrazo

**Comment by LeandroBraier** [comment]
MK: te paso la lista de rendimientos de cada uno de los productos para que puedas reconstruir el Calculador de Consumo sin problemas.

Base niveladora

2,1 kg/m2

Classic Stone

2,2 kg/m2

Enduido

0,5 lt/m2

Fijador

0,028 lt/m2

Frentes

1,2 kg/m2

Hormigón

0,125 kg/m2

Latex Cielorraso

0,1 lt/m2

Latex interior /exterior

0,07 lt/m2

Marble Fino

1,7 kg/m2

Marble Medio

1,9 kg/m2

Muros

1,2 kg/m2

Natural Stone

2,2 kg/m2

Paddle

0,75 kg/m2

Reflex

0,125 kg/m2

Revebase

2 kg/m2

Reveglaze

0,2 kg/m2

Revegrain

1,3 kg/m2

Revemastic

1,5 kg/m2

Revemor

2 kg/m2

Reveplaster

1,3 kg/m2

Reveprim

0,11 kg/m2

Revereco Planchado

2 kg/m2

Revereco Texturizado

1,2 kg/m2

Revex Fino Planchado

2 kg/m2

Revex Fino Texturado

1,2 kg/m2

Revex Medio Planchado

2 kg/m2

Revex Medio Texturado

1,2 kg/m2

Revoque Plástico Fino Flexible

1,2 kg/m2

Rustique Stone

4 kg/m2

RV2

2,5 kg/m2

Salpicado Planchado

2 kg/m2

Salpicado Texturizado

1,5 kg/m2

Siliconado

0,25 lt/m2

Stone a rodillo

1,5 kg/m2

Stuccado

0,7 kg/m2

Techos

1,5 kg/m2

Texturable

1,3 kg/m2

Transparente

0,25 kg/m2

Avisame si con eso ya alcanza.

abrazo

**Comment by mkreyness** [comment]
Ok, vos decis que trabaje sobre el backup de Fede ?
Yo creo que convendria tener un tercer lugar mas neutral y "definitivo" 
donde ir volcando las cosas tocadas.

En cuanto al buscador de distribuidores, entonces abro en nuestra base 
algo SIMILAR al de CMS de corralones klaukol pero separado.
La base la puedo chupar de lo que muestran, lo que habria que hacer con 
el CMS es recorrer c/u para que se generen las coordenadas correctas, y 
despues rellenar las listas con el engine del buscador de corralones 
adaptado a esta grafica distinta.
Todo va a llevar un tiempito pero seguro que se puede hacer.

**Comment by LeandroBraier** [comment]
Backup Revear: Fijate el doc. El tuyo está más acabado en realidad, pero
coordinen uds.

Buscador de distribuidores: adelante con esa técnica nomás. Lo importante
es tenerlo finiquitado esta semana.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-21 13:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
http://72.52.188.248/bkps/parexar.tar
Espero que se haya subido bien!

**Comment by LeandroBraier** [comment]
MK, cómo venís con esto?

Tenemos posibilidad de tenerlo backupeado para el jueves? (Aunque no esté activo en el nuevo hosting, simplemente con toda la información segura a salvo en el hosting o en tu máquina)

**Comment by mkreyness** [comment]
Vale la misma respuesta que en el otro thread. Esta todo backupeado, y con lo que estoy trabajando es el buscador de distribuidores de Revear.

**Comment by LeandroBraier** [comment]
Excelente. Esa es la info que necesitaba. Para reconstruir los motores tenemos más tiempo pero esta semana tenemls que asegurarnos de tener todo todo todo backupeado.

Gracias!

**Comment by LeandroBraier** [comment]
Marce, para cuando pueden estar listos y funcionando el Calculador de Consumo y el Buscador de Distribuidores y cuántas horas te llevarían?

Necesitaríamos tener estos elementos de la versión 2.0  para la última semana de Junio máximo.

**Comment by mkreyness** [comment]
Me habias pasado finalmente como se hacen los calculos ?
Van a reestilizar esa pagina horrible o queda lo que esta ?
Siempre dependo mucho de lo compleja o no que vaya a ser la interface.
Supongo que las cuentas son una pavada, pero no tenemos cargados los 
productos revear en ningun lado asi que no se de donde tomar la info.
Obvio tengo la base vieja de ellos y la puedo investigar.

El buscador de distribuidores lo podemos copiar del de corralones ?
Te pueden dar la base de datos o hay que tratar de extraerla de la base 
vieja ?

**Comment by LeandroBraier** [comment]
Estos dos programitas son lo que más cocinado teníamos antes de irme yo.

1) CALCULADOR: La formula es: calculan superficie seleccionada por el usuario multiplicada por el rendimiento del producto. Cada producto tiene un rendimiento distinto que te pasé más arriba. Te lo vuelvo a copiar:

Base niveladora

2,1 kg/m2

Classic Stone

2,2 kg/m2

Enduido

0,5 lt/m2

Fijador

0,028 lt/m2

Frentes

1,2 kg/m2

Hormigón

0,125 kg/m2

Latex Cielorraso

0,1 lt/m2

Latex interior /exterior

0,07 lt/m2

Marble Fino

1,7 kg/m2

Marble Medio

1,9 kg/m2

Muros

1,2 kg/m2

Natural Stone

2,2 kg/m2

Paddle

0,75 kg/m2

Reflex

0,125 kg/m2

Revebase

2 kg/m2

Reveglaze

0,2 kg/m2

Revegrain

1,3 kg/m2

Revemastic

1,5 kg/m2

Revemor

2 kg/m2

Reveplaster

1,3 kg/m2

Reveprim

0,11 kg/m2

Revereco Planchado

2 kg/m2

Revereco Texturizado

1,2 kg/m2

Revex Fino Planchado

2 kg/m2

Revex Fino Texturado

1,2 kg/m2

Revex Medio Planchado

2 kg/m2

Revex Medio Texturado

1,2 kg/m2

Revoque Plástico Fino Flexible

1,2 kg/m2

Rustique Stone

4 kg/m2

RV2

2,5 kg/m2

Salpicado Planchado

2 kg/m2

Salpicado Texturizado

1,5 kg/m2

Siliconado

0,25 lt/m2

Stone a rodillo

1,5 kg/m2

Stuccado

0,7 kg/m2

Techos

1,5 kg/m2

Texturable

1,3 kg/m2

Transparente

0,25 kg/m2

2) Como decís. Copiala nomás de lo que está ahora y que sea modificable por CMS. La base ya la pedimos y nos la va a pasar el cliente.

Esto entonces lo podemos tener rápido, no?

Confirmame porfa.

abrazo

**Comment by LeandroBraier** [comment]
Como te decía en el otro ticket, este sitio es segunda prioridad después de los otros dos. Igual es el que tenemos más cocinado quizás. Si te sirve para ganar tiempo mientras resolvemos lo del Calculador de Adhesivos de Klaukol andá avanzando.

abrazo

**Comment by mkreyness** [comment]
No, yo sacaria andando primero todo lo de flash que, como no se puede 
cambiar, esta "terminado" :)

**Comment by LeandroBraier** [comment]
@mkreyness , para cuando podríamos subir a producción estos dos?

**Comment by mkreyness** [comment]
Vos decis hacer lo mismo de poner lo viejo ?
Dejame que lo miro esta tarde a ver si funciona lo que hay, no recuerdo 
haberme fijado.

**Comment by LeandroBraier** [comment]
Dale, no hay apuro. IGual yo revisé todo el ticket y creo que ya los
tenemos masticados. Es un trámite.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 14:27 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
MK: Acá tengo la base de distribuidores enviada por el cliente. Decime si nos sirve como está para alimentar el Buscador de Distribuidores:

https://drive.google.com/open?id=1KDuYjhT4TbtrLiD7ORN9zkgZkj7DTg-YLphF55PSTrM&authuser=0

abrazo

**Comment by mkreyness** [comment]
Mira, el problema siempre con estas bases es que no tienen la geolocalizacion, yo puedo cargarla como la de corralones pero alguien va a tener que ir alimentando el feed que le pase en su momento a Ezequiel para ir resolviendo coordenadas.  De todos modos estoy tratando de hacer andar lo que esta en el sitio de Revear y parece que faltan cosas (justamente el motor que trae los distribuidores y lo que hace el calculador de consumo, no las encuentro en el backup. Le voy a dedicar un rato mas y si no tratare de adaptar lo que hay a que pueda consumir distribuidores de nuestra base como en mi aplicacion de corralones.

**Comment by LeandroBraier** [comment]
Te había entendido que lo teníamos todo bien backupeado a este, que no era
necesario demasiado trabajo. Fijate en los mensajes más al principio de
este ticket. Quizá ya lo habías desculado y te olvidaste.

Respecto de las coordenadas de geolocalización cómo hicieron con Eze?
Explicame. Eze está de viaje pero quizá si me explicás lo puedo hacer yo la
semana que viene.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 17:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, la parte estetica, las paginas web estan todas, lo que pasa es que falta algo del engine que en el backup mio no lo podia agarrar, y en el backup full lo estoy buscando, es gigante. De una forma u otra zafaremos. La pagina para resolver geolocalizacion es algo que arme para pegar direcciones y obtener coordenadas. Despues te la paso, igual no se pueden pedir de a muchas por vez porque Google te frena.

**Comment by mkreyness** [comment]
Bueno, ya tire la toalla con hacer andar lo viejo, porque lo fundamental es que en la base de datos que encontramos en el backup no hay nada de revear, con lo cual ni se como se tendrian que llamar los campos en la tabla.
Ya cargue la lista de distribuidores que me pasaste en el CMS, que preferis, hago directo una copia del sistema de los corralones con esta base de distribuidores asi ya queda todo "nuestro" ? (la estetica obviamente Fede la tendria que adaptar a "Revear")

**Comment by LeandroBraier** [comment]
MK, no termino de entender cual es el tema. Dejemoslo. El lunes lo
retomamos y vemos como lo podemos resolver.

abrazo y buen finde

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 21:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si pero yo tengo que laburar esto en el fin de semana, en la semana no tengo tiempo y no tengo otro material con que trabajar ya que avance todo lo posible con la base de datos de Torneos y ahora dependo de la maquetacion.

Con esto de Distribuidores tenemos dos alternativas:
1) tomar el sitio FEO de ellos, que dice REVEAR y levantar el contenido de nuestra base, haciendo cambios Fede en header/footer para compatibilizar, como se hizo con las apps de Klaukol.
Esto ademas lleva mas tiempo.

2) tomar el sitio LINDO de Corralones, que dice KLAUKOL, y levantar el contenido de nuestra base, haciendo cambios Fede para que en vez de tener estetica Klaukol tenga estetica REVEAR.
Esto a mi me lleva mucho menos tiempo y a Fede seguramente tambien, pero no queda "coherente" con la fealdad del Calculador de Consumo.

**Comment by LeandroBraier** [comment]
Entonces vamos por la opción 1 pero segunda prioridad después del Torneo de
Corralones.

Si el calculador de consumo ya está se puede subir o qué nos falta?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 21:38 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, no esta el calculador de consumo, tengo que programar el calculo de cero (en base a lo que me pasaste) porque tampoco estan los datos de eso en ninguna base, entonces queres que le de prioridad a eso ? Repito: No tengo con que mas avanzar de Torneos por ahora, hasta que reciba las maquetas de Fede.
Ojo que tampoco tengo idea de COMO tiene que mostrarse el resultado del calculo, le voy a poner que muestre supongo un numero de paquetes o algo asi, despues pulimos eso.

**Comment by mkreyness** [comment]
Bueno, ya esta el calculador de consumo andando, salvo los casos de litros que te pase, y los nuevos productos que me dijiste para los cuales no se el rendimiento que corresponde poner asi que cuando me los confirmes lo completo.
http://www.revear.com.ar/calculador-de-consumo.html

La consulta de distribuidores tambien estaria pero no la puse 100% online hasta que se completen las geolocalizaciones. Por ahora lo podes ver en:

http://www.revear.com.ar/distribuidoresmk.html

Para corregir las coordenadas lo mas prolijo para mi va a ser que lo hagan via el CMS asi de paso corrigen mucha cosa mal puesta entre Provincia de Bs As y Ciudad Autonoma, hay cosas cruzadas para ambos lados.
La idea es que si todo esta bien con solo entrar a cada distribuidor y darle Guardar se crean solas las coordenadas. En algun caso que no pueda va a salir un cartel (que viene asi de google) que dice 'ZERO RESULTS". En ese caso hay que manosear un poco el domicilio hasta que yendo a la solapa del mapa aparezca coordenadas (el propio mapa no se va a ver en ese momento, hay que guardar y volver a entrar para corroborar.
Si no salta el "ZERO RESULTS", te aseguro que se hace rapido.
Y si no, hay que aplicar un poco de ingenio y conocimientos.
Por ejemplo, en una sucursal de Pinturerias Rex de Maschwitz, el domicilio decia "PANAMERICANA RAMAL ESCOBAR KM 47" y la localidad  "MASCHWITZ".
Lo cambie a "PANAMERICANA  KM 47", "ING. MASCHWITZ" y ahi si lo engancho perfecto.

**Comment by LeandroBraier** [comment]
Perfecto MK!

Lo consulto con el cliente y te doy feedback. Queda totalmente de mi lado esto ahora.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness en este momento el buscador de distribuidores no anda online.

Si subís esta versión del buscador de distribuidores asi como está:

http://www.revear.com.ar/distribuidoresmk.html

Funciona?

Si es positivo hacelo de una. Y solo le tengo que pedir al cliente que revise via CMS la localización de cada uno para asegurarnos de que las direcciones están bien.

Confirmame porfa.

abrazo

**Comment by mkreyness** [comment]
Ambas cosas llevan a mi mismo programa, lo que esta en el CMS, se debe haber roto algo al migrar de servidor. Dejame que miro a ver como hacer que siga andando el truco que hice para que la interface vieja consulte MI programa.

**Comment by LeandroBraier** [comment]
Perfecto. Gracias MK!

abrazo

**Comment by mkreyness** [comment]
La verdad que no entiendo bien que pasó en que momento. 
Supuestamente yo habia hecho una truchada para engañarla con mis datos, asi que de todos modos a la mayoria le faltan las coordenadas. Sin embargo vos decis que hasta ahora andaba ?
Ahi puse la "distribuidoresmk.html" como "distribuidores.html" y funciona, pero con muy pocas que fueron las que yo recorri a mano. Lo que hay que hacer es entrar uno por uno a los distribuidores, dejar que el sistema les asigne las coordenadas, y guardarlo. En caso de que esas coordenadas esten mal o no traiga nada, hay que masajearle un poco los datos de domicilio hasta que pueda identificarlo.

**Comment by LeandroBraier** [comment]
@mkreyness acá veo que el calculador de consumo había quedado funcionando y yo lo vi funcionando hace poco. Ahora me dice …@FAAREIA que no anda y veo que es verdad. Revisarían qué pasó por favor?

abrazo

**Comment by mkreyness** [comment]
alguno de esos cambios raros de Duplika que hace que los redirects por htaccess no anden o algo asi.
A la tarde lo reviso.

**Comment by mkreyness** [comment]
Era lo de los cambios en el manejo de permisos. + tambien cuando cambiaron la base de datos quedaron todos mal los acentos, ya arregle eso tambien.
Pero veo que hay productos para los cuales no estan cargadas las presentaciones, esos dan error igual (no se ve un error, pero queda el producto que se haya mostrado antes y eso esta mal). Hago que quede vacio, no ?

**Comment by LeandroBraier** [comment]
Si porfa. Consultalo con Fede por las dudas. El esta backupeando el sitio.
Gracias!

**Comment by mkreyness** [comment]
esto esta en mi programa, dudo que este backupeando mi directorio.

**Comment by mkreyness** [comment]
El problema en realidad es que la pagina web hace referencia a productos que no estan en la base.
Capaz se eliminaron, pero entonces habria que eliminarlos tambien de la pagina, eso si ya es un tema de tocar el HTML, @FAAREIA , ojo con lo que estan backupeando tambien.
Yo encuentro que estos "numeros de producto" de la calculadora no se corresponden a ninguno de  nuestra base, capaz falta cargarles el dato a los que correspondan.

21
22
35
36
37

**Comment by LeandroBraier** [comment]
@mkreyness estoy probando y si bien encuentra el producto el cálculo no da nada. Da una barra sin número que dice "Cantidad necesaria" Después quiero hacer una nueva búsqueda y nome deja.

**Comment by FAAREIA** [comment]
Aclaro que no estoy backpeando el sitio, el sitio ya estaba backupeado de antes. Lo único que estuvimos haciendo con brau es recopilar los datos de productos por ej., en un archivo.
Con respecto a eliminar productos o agregar lo que fuese a algun producto, los HTML estan en muchos casos más que quintuplicados y distribuidos por varias carpetas. Necesitaría que me digan que producto tengo que tocar.

**Comment by LeandroBraier** [comment]
Por ahora estamos hablando del calculador especificamente. Mientras
tengamos todos los contenidos dispuestos oara subirlos a la nueva web
estamos ok. Recuerdo que esta quintuplicado pero guardemoslo una sola vez
no? Jeje

**Comment by mkreyness** [comment]
Te pase arriba una lista de IDs que trae la pagina del calculador de consumo, los tiene escritos asociados a algun texto en un select, esos productos entiendo que NI ESTAN en nuestra base, habria que sacarlos del popup, porque solo llevan a error.

**Comment by LeandroBraier** [comment]
Si, pero a mi no me anda ningun producto igual. Cuales si te andan?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-18 17:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ah el calculo decis, yo me referia a que ni me traia la foto del producto en esos casos porque no estaban cargados en la base.
Si, tenes razon, al lado de "Cantidad necesaria" no sale nada.
Bueno, con mi intermitente internet tratare de revisarlo.

**Comment by FAAREIA** [comment]
Marce ahi subi el HTML otra vez pero con las `<option>` que me dijiste que saque.

**Comment by mkreyness** [comment]
ahi arregle lo del calculo, pero ojo que si pedis cualquiera de los productos que no existen en la base, da error y te queda congelado el anterior que te mostro, por eso es importante eliminarlos de la pagina.

**Comment by FAAREIA** [comment]
No se si termino de entender aún, el HTML actual de http://www.revear.com.ar/calculador-de-consumo.html tiene los siguientes `option` comentados:
21
22
35
36
37

**Comment by FAAREIA** [comment]
Si esta ok, no deberían de aparecer esos productos

**Comment by mkreyness** [comment]
ah bueno, ahora si, pero yo tenia la pagina cargada de hace un par de horas y todavia los tenia.
Ok, entonces deberia estar todo funcionando bien ya

**Comment by LeandroBraier** [comment]
Buenisimo MK! Ahora funciona.

Solo no me funcionan los siguientes:

FIJADOR
RV2 (funciona pero no muestra imagen)
SILICONADO (muestra imagen pero no los datos)

Los demás todos perfectos.

@FAAREIA en la pagína nueva de Revear no podemos pegarlo tal cual al calculador, sin modificarlo?

**Comment by mkreyness** [comment]
"FIJADOR" y "SILICONADO" no tienen cargadas presentaciones en el CMS, no puede hacer los calculos.
"RV2" no tiene cargada imagen en el CMS

Todo se puede arreglar desde el CMS, teniendo los materiales/info necesaria (que no la tengo).

**Comment by LeandroBraier** [comment]
Ok. Entonces los puedo ocultar provisoriamente desde el cms?

**Comment by mkreyness** [comment]
No, la lista que se muestra en la pagina NO viene del CMS, lo que viene del CMS es el calculo.
Te los tiene que ocultar @FAAREIA en la pagina como hizo con los otros.

**Comment by LeandroBraier** [comment]
Ahi encontré la foto de RV2 y la subí. Funciona joya.

También cargué las presentaciones de Fijador y Siliconado y ya calcula el Consumo x m2, que debe estar en el script intermediario que vos hiciste @mkreyness 

Gracias a los dos!!

@FAAREIA para la web tené en cuenta que todos los productos ya están backupeados en el CMS, me había olvidado que estaban ahí, junto con los de Parex. Solo tendrías que descargarte todas las imagenes o (mejor) dejar las imagenes en el mismo lugar y tomar las fuentes. 

Confirmame cuando puedas si podés robar tal cual el Calculador y meterlo en la web nueva, aunque la estética no concuerde del todo.

abrazo

**Comment by FAAREIA** [comment]
Ok no hay drama, pero tené en cuenta que el nombre de esas imágenes es a veces algo como "0983204982394.jpg" no ayuda nada al posicionamiento de la imagen relacionada al producto.

**Comment by mkreyness** [comment]
En realidad no estan "backupeadas", el cms (por la forma en que tuvimos que arrancar con parex/etc solo estan REFERENCIADAS desde el CMS, apuntando a las ubicaciones y nombres horribles del backup gigante que nos dieron
