### ISSUE TITLE
Mailing Club de Colocadores MegaEvento

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#230]
Buen día @FAAREIA y @braulio-evangelisti !

Necesito una adaptación del Mailing de Bienvenida de Colocadores que comunique un posteo a compartir en Facebook que permite participar de un sorteo en especial.

TEXTO 1:
Si sos miembro del club, compartí este posteo y participás por un lugar en el Megaevento Exclusivo donde los que más saben se reúnen para divertirse y celebrar fin de año.

IMAGEN DEL POSTEO
(te paso el slide y el posteo en editable por las dudas también, pero el que va es este posteo)

![posteo-pauta-evento-colocadores4](https://cloud.githubusercontent.com/assets/6719872/11423047/dcf9a598-941f-11e5-8a81-ef9e258241e2.png)

EDITABLES:
https://www.wetransfer.com/downloads/09b90d5a8b6dd794caac551efee3474c20151126121800/9a8321

TEXTO 2:
Para participar de este sorteo hacé clic acá y compartí el posteo.
No olvides completar todos tus datos en tu perfil del Club de Colocadores así podemos contactarte.

A continuación de esto va todo lo mismo que en el mailing de bienvenida customizado pero sin la frase "¡Bienvenido al Club de Colocadores!"

Lo necesitaría para hoy sin falta a esto. Me confirman porfa si llegamos como para enviarlo a la tarde?

**Comment by braulio-evangelisti** [comment]
Lea la tarjeta de socio queda o la saco?

**Comment by braulio-evangelisti** [comment]
Bueno como lo necesitas rápido lea saque lo de la tarjeta, avisame cualquier cambio

http://parexklaukol.com.ar/_mailing/colocadores-evento/colocadores-evento.html

Abrazo

**Comment by LeandroBraier** [comment]
Perdon que demore Brau. Esta muy bien el mailing. Su mala el carnet porfa.
Con eso ya estaríamos

**Comment by braulio-evangelisti** [comment]
Ahi se lo volvi a poner. Abrazo.

**Comment by LeandroBraier** [comment]
Gracias Brau!!!!

@mkreyness podemos hacer el envío hoy de este mail a la base de 140 colocadores aprox que tenemos?

**Comment by mkreyness** [comment]
no puedo mandar nada hasta que termine el de vendedores, que recien va por la mitad, para cuando termine ya va a ser entrada la noche.

**Comment by LeandroBraier** [comment]
No podemos frenarlo y meterlo en el medio no?

Sino mañana a primera hora mandalo porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-11-26 16:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
es complicado saber por donde va, si bien graba un log, por cuestiones de buffering del linux el log se graba cada unos 20 renglones, con lo cual o le terminaria repitiendo el mail a 20 tipos, o capaz me como 20 tipos de mandar.
Mañana a primera hora lo mando (igual acordate que es feriado).

**Comment by mkreyness** [comment]
@LeandroBraier veo que el link donde dice hacer click incluye un URL a postear, que no se que tengo que poner ahi (Braulio lo dejo como una variable).
Si es algo fijo (porque no creo que dependa del destinatario del mail), yo diria de completarlo en el HTML.

**Comment by LeandroBraier** [comment]
Si, es algo fijo. Me olvidé de pasarle la URL. No se lo podés agregar vos? Es este:

https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/815005485288464/?type=3&theater

**Comment by mkreyness** [comment]
ahora le agrego y veo si anda.

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by mkreyness** [comment]
Creo que anda bien, fijate:

http://parexklaukol.com.ar/_mailing/colocadores-evento/colocadores-evento.html

**Comment by LeandroBraier** [comment]
Perfecto MK! Mande nomas.

**Comment by mkreyness** [comment]
Para eso primero tengo que mandar una prueba con los datos de login y todo eso.
Lo armo y te mando de prueba pero el real sale mañana quedamos, no ?

**Comment by mkreyness** [comment]
Asunto: ?

**Comment by LeandroBraier** [comment]
Si, perfecto.

_Asunto_: Compartí este posteo y participá por un lugar en el MegaEvento de
Fin de Año del Club de Colocadores

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Te mande prueba, confirmame si ok.

**Comment by LeandroBraier** [comment]
Perfecto!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ya termino de salir el de vendedores, si queres puedo mandar ya este. O si no a la mañana.

**Comment by LeandroBraier** [comment]
Dale, saquemoslo ahora. 

Pero tomá la base actualizada de ahora ya, porque recién acabo de sumar el email del cliente que me pidió que se lo pusiera en un usuario fake que creó. Quiere recibir el mailing.

**Comment by mkreyness** [comment]
la base se toma live de lo que hay. Ok, ya lo largo.

**Comment by LeandroBraier** [comment]
Genial! Gracias MK!
