### ISSUE TITLE
Nuevo Juego Diciembre Vendedores Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#231]
@mkreyness y @FAAREIA les paso el nuevo juego del mes para que lo vayan revisando y viendo cómo integrarlo a la plataforma. Los cambios van a ser muy simples, solo agregar el logo de Klaukol y colores como hicimos con el juego anterior.

https://www.wetransfer.com/downloads/5bacaa9e6ce94438ff0ea002afea9f2820151201025035/55214c

abrazo

**Comment by FAAREIA** [comment]
mmmm, yo nunca hice nada para los juegos, pero cualquier cosa me dicen
Abrazo

**Comment by mkreyness** [comment]
No creo que @FAAREIA tenga que hacer nada, es cuestion de que me pasese los graficos y yo los cambie como la vez pasada, + la definicion de como seria la escala de puntajes.

**Comment by mkreyness** [comment]
no logro hacer andar esto que mandaste, trae un monton de plugins sueltos que hay que instalar pero hay unos que venian zippeados que tirelos donde los tiren me salta error.
Vos lo pudiste hacer andar ? Hay algun instructivo de instalacion ?

**Comment by mkreyness** [comment]
Cierto, se cagó tambien lo que muestra el CMS, por ejemplo cuando pide contraseña sale mal la eñe.
Ahi le force un par de cosas para que ande igual, pero evidentemente hubo algun cambio de parte de Duplika que cambio algo en general.
Ahora veo como evitar el problema en el resto de cosas.

**Comment by mkreyness** [comment]
la explicacion es esta: Duplika cambio el motor de base de datos hace unos dias, de mySQL a una cosa que se llama MariaDB que se supone que es compatible. Pero parece que no tiene utf-8 por default, entonces todos los datos que estaban cargados en utf-8 los esta interpretando para el lado de los tomates.
Ya lo arregle para esto de los juegos (los retipee e hice un cambio en el programa), pero no se en cuantos otros lados puede haber afectado.
Voy a ver si hay algun seteo general que se pueda hacer desde el panel de control porque revisar y tocar decenas de programas es caotico.

**Comment by mkreyness** [comment]
No encontre. Toque todos los programas (o al menos eso creo).
Si ves char raros avisame donde y le aplico el correctivo.

**Comment by LeandroBraier** [comment]
Dale, perfecto MK. Mil gracias! Si veo algo más que sea raro te aviso.

Abrazo

**Comment by mkreyness** [comment]
Che se me cruzaron los threads!
Aca es lo del CONSTRUCT2, eso sigue mal. De donde vos compraste el juego, no venian instrucciones de instalacion ? A vos te anduvo ?

**Comment by LeandroBraier** [comment]
No lo probé yo porque el construct 2 es psra windows nomas. Que problema
teniamos con el construct? Este juego excede las limitaciones del trial?

**Comment by mkreyness** [comment]
No, es que usa unos plugins, MUCHOS en realidad. Supuestamente vienen incluidos, algunos me los deja instalar, pero otros que justamente vienen zippeados, no entiendo donde los tengo que poner. Ya probé descomprimirlos/no descomprimirlos en todas las carpetas y subcarpetas posibles y siempre me tira que faltan, o que son inválidos. Por eso te preguntaba si había un instructivo en algún lado.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Mirá MK, esto es lo que dice en la página, no habla de plugins pero dice que está todo incluido:

http://codecanyon.net/item/block-puzzle-v1/13453997?s_phrase=&s_rank=64

-“Block Puzzle made on Construct 2 game engine.
-Included all the source file ready to export for mobile and web game (html5, cordova, cocoonjs) and .CAPX file 
-Flexible event system

How To Play

NO NEED TO MAKE BLOCK MATCHING (color) Drag and Drop Pattern into Board to fill row or column to break all blocks in the line
Game over when the new pattern does not have right space to put.

Features

-Construct 2 212+
-Play on desktop and device
-Easy export to HTML5 for website
-Ready to export for Android, iOS with Cordova platform such as intel XDK, phonegap, CocoonJS – Ludei.
-AdmobAds integration
-Touch & Mouse
-Share on Facebook, Twitter, Google plus

**Comment by mkreyness** [comment]
Todo muy lindo pero Construct2 NO ME ABRE el proyecto, porque dice que faltan instalar los plugins. 
No puedo ni jugarlo ni verlo ni nada.
Las cosas estan, pero no se DONDE PONERLAS para que Construct2 las reconozca, ese es el tema.
Me pondre a investigar a ver si a otros les pasa lo mismo.

**Comment by LeandroBraier** [comment]
Frenalo a esto MK. Yo lo investigo esta noche bien y te digo como lo
resolvemos. Gracias MK! Abrazo

**Comment by mkreyness** [comment]
ok, igual yo con la instalacion de Caleta de DelViento tuve para entretenerme anoche y ahora a la tarde.

**Comment by LeandroBraier** [comment]
jajaj perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA me das una mano investigando esto la semana que viene?

El juego que compramos es este:

http://codecanyon.net/item/block-puzzle-v1/13453997

Y te lo subí acá también parece que ahora se puede:

[Block Puzzle V1.zip](https://github.com/LeandroBraier/Klaukol/files/52641/Block.Puzzle.V1.zip)

Dale una mano a @mkreyness para que pueda avanzar esta semana con el juego y poder tenerlo para la semana del 14.

abrazo

**Comment by mkreyness** [comment]
Para ver el problema primero tiene que instalarse la version gratuita del Construct2.
Pero esta mal armado el paquete del juego: no tiene instrucciones de como instalarse y por lo tanto no anda.

**Comment by FAAREIA** [comment]
Con marce llegamos al mismo final, no podemos abrir el juego porque falta 1 Plugin y unos Behaviours. Lo que habría que hacer en este caso es contactarse con el autor: http://codecanyon.net/item/block-puzzle-v1/13453997/support
Hay que loguearse y abrir un ticket.

**Comment by LeandroBraier** [comment]
Fede. Pedile esto en mail aparte a Eze porfa, que el tiene el user con el
que hizo la compra.

**Comment by FAAREIA** [comment]
Pedido

**Comment by LeandroBraier** [comment]
Tuviste respuesta de esto Fede? Sino decime y le insisto a Eze para el mes que viene ya.

**Comment by FAAREIA** [comment]
Me hiciste acordar Lea....le había mandado el issue en ingles al autor pero la respuesta la tiene que tener Eze. El mail al que responde es: ezequiel@crupnicoff.com
Preguntale si le llegó o que la busque en spam a ver si esta ahi...

Abrazo

**Comment by LeandroBraier** [comment]
Dale, le pregunto Fede! gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-16 16:59 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, me dice Eze que no ve respuesta pero tampoco tu pregunta. Vos por donde se la hiciste? por la plataforma o por mail?

**Comment by FAAREIA** [comment]
Le mandé mail por aca: http://codecanyon.net/item/block-puzzle-v1/13453997/support/contact
Ahora le pongo en los comentarios, asi lo escracho

**Comment by LeandroBraier** [comment]
jsjsjs Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi lo dejé bien asentado en un comentario. Me parece raro que el mail enviado por el link anterior no quede registrado en ningun lugar a pesar de que dice que son guardados.....aunque parecen no accesibles por uno al menos.

**Comment by LeandroBraier** [comment]
Perfecto. Esperemos la respuesta entonces. Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA al fin nos llegó la respuesta del programador para solucionar esto:

Inicio del mensaje reenviado:

De: crazy programmer so.crazy.programmer@gmail.com
Fecha: 19 de diciembre de 2015, 11:26:51 p.m. ART
Para: Ezequiel Crupnicoff ezequiel@crupnicoff.com
Asunto: Re: [CodeCanyon] Item Support Message sent from ezebenteveo

hi , 

thanks for purchase, in source you will find all the Plugin and Behavior inside folder after extract this: Plugins-Addon.zip 
or you can download here, in attach files

for plugin you just copy to :C:\Program Files\Construct 2\exporters\html5\plugins
and for Behavior copy to: C:\Program Files\Construct 2\exporters\html5\behaviors

for Share: after extract ShareAddon V3.zip --> then extract : SharePluginv3.zip, you will find the addon file : SharePluginV3.c2addon

to install addon, open construct then drag and drop this file into construct, then restart contruct

Regards,

**Comment by mkreyness** [comment]
@FAAREIA por favor probalo vos cuando puedas y avisame si sirve.

**Comment by FAAREIA** [comment]
Bien, soluciona el tema del plugin faltante pero faltan los Behaviors

**Comment by LeandroBraier** [comment]
En el mismo zip está.  Lo dice el tipo en el mail no?

**Comment by FAAREIA** [comment]
Expando la respuesta:
En el source los archivos faltantes no estan. El link de "download here" no aperece en el reenvío y por lo que veo en el comentario online dice algo del email.

**Comment by LeandroBraier** [comment]
Fede, porfa pedile lo faltante con el acceso que te pasé. abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-21 12:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Entiendo. Porfa deciselo al tipo online con el acceso que tenes. Asi nos lo
manda.

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias Fede! Esperemos respuesta ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, el tipo dice que en el email que le envío a eze hay un adjunto o algunos. Habría que decirle a eze que nos reenvie el mail tal cual, a mi me llegó sin links ni adjuntos

**Comment by LeandroBraier** [comment]
Lo recibiste Fede??

Te lo mandé por mail recién y te lo sumo acá.

[Plugins-Addon.zip](https://github.com/LeandroBraier/Klaukol/files/69819/Plugins-Addon.zip)

**Comment by FAAREIA** [comment]
Todavía faltan, era 1 behavior lo adicional del zip adjunto.

**Comment by LeandroBraier** [comment]
Yo creo que son 3. FIjate:

<img width="942" alt="captura de pantalla 2015-12-22 a las 4 49 04 p m" src="https://cloud.githubusercontent.com/assets/6719872/11964024/87b5c8dc-a8c9-11e5-856e-d8805262b973.png">

**Comment by FAAREIA** [comment]
Si son 3, antes eran 2 Todavía faltan 4, la verdad que el tipo no explica demasiado.

**Comment by LeandroBraier** [comment]
SI, es medio despiolado. Le podrías volver a pedir al tipo por la misma
plataforma? Yo le daría el detalle de exactamente lo que falta, así lo
resuelve más rápido.

Y pasale tu mail también o el mio, como prefieras, así no dependemos de
pedirle a Eze que reciba su mail.

abrazo

2015-12-22 17:01 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya le puse el detalle antes, ahora le mandé más detalle (autores del behavior). El tema de poner el mail ahi es el spam que podría llegar a llegarnos. Es un sitio muy visitado.

**Comment by LeandroBraier** [comment]
Entiendo. Ok, esperemos entonces. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-22 17:04 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness necesito subir este juego hoy. Como venimos?

**Comment by mkreyness** [comment]
Nunca tuve cuando ponerme a ver si todo eso que dicen anda. Para hoy no puedo prometerte nada, lo empiezo a ver a la tarde y despues te digo si funciona.

**Comment by LeandroBraier** [comment]
Dale, decime hoy pr lo menos para cuando puede estar.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Es que esto o anda, o no anda. Si no anda, no es cuestion de tiempo.

**Comment by LeandroBraier** [comment]
Entiendo. Con mas razón confirmame cuánto antes.

Abrazo

**Comment by mkreyness** [comment]
me recuerdan como diablos se llamaba este juego ? Ya no esta disponible el transfer y no lo encuentro en mi maquina porque Construct2 nunca lo pudo abrir, asi que no esta en la lista.
Lo tengo, pero no se ni como se llama.

**Comment by mkreyness** [comment]
ah ya vi, Block Puzzle. Es que todos se llaman "Block" algo...

**Comment by LeandroBraier** [comment]
Genial. Pudiste abrirlo?

Fijate que necesités tener el resto de los elementos que juntó Fede pidiendoselos al creador para abrirlo.

**Comment by mkreyness** [comment]
no, todavia no lo encontre, pero por lo menos se como se llama.

**Comment by LeandroBraier** [comment]
Igual no te preocupes, ya hablé con el cliente y recién lo necesitaríamos para Febrero. De todas formas sería ideal ya dejarlo resuelto esta semana si puede ser.

abrazo

**Comment by mkreyness** [comment]
Solo encuentro archivos cuyo nombre empieza con un puntito (como se ve en la PC cuando copias una carpeta de la Mac), pero nada de lo real.
Tenes forma de remandarme el wetransfer original ?

**Comment by LeandroBraier** [comment]
Acá te subo todos los materiales que pude recompilar a lo largo de todo el proceso. Creería que está todo.

[Juego Colocá los cerámicos en línea.zip](https://github.com/LeandroBraier/Klaukol/files/105769/Juego.Coloca.los.ceramicos.en.linea.zip)

**Comment by mkreyness** [comment]
genial gracias.

**Comment by mkreyness** [comment]
igual se me descomprime todo raro, hay carpetas comprimidas dentro de carpetas comprimidas con el mismo nombre... Es totalmente desorganizado. Espero poder reconstruirlo de los mails de Fede.

**Comment by LeandroBraier** [comment]
Fue así el proceso MK. El primer archivo es Block Puzzle V1, probá abrirlo y te va a pedir el resto de los archivos que le fuimos pidiendo uno a uno al desarrollador. @FAAREIA nos ayudó con eso.

**Comment by mkreyness** [comment]
Si, ya se, pero no se donde "poner" lo que dice que falta.
Por eso tengo que seguir todo lo que fue diciendome Fede y yo fui no dandole bola porque estaba con lo de Paty a full.

**Comment by LeandroBraier** [comment]
Ok, fijate eso porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ya lo tengo andando, tenes los materiales que habria que cambiar ?

**Comment by LeandroBraier** [comment]
Buenisimo MK! Lo estoy viendo por arriba y según estimo, lo único que haría falta es:
1. agregar con el nombre del juego y el logo de Klaukol a la derecha en la sección de donde se sacan las piezas.  
2. Aparte de esto, tendríamos que cambiar la gama de colores para que sea la de Klaukol. Se podrá hacer eso?
3. Los mensajes de win, game over, etc que haya dando vueltas. Esos me los tendrías que pasar y yo te los paso rediseñados.

abrazo

**Comment by mkreyness** [comment]
los colores son simplemente unos png que se llaman "particles1.png", "particles2.png" ,etc.
Pero son 8, muchos para la gama de Klaukol creo.
Hay un "gamelael-sheet0.png" que dice "BLOCK PUZZLE C2V1"
Hay un "levelfailed-sheet0.png" que dice "Game Over", y una serie de texto raros en imagenes que no creo que se usen que dicen "flat color", "flat icon", "noel"
Tenerlos los tenes todos porque estan seguro en las cosas que me mandaste, dentro de la carpeta html5/images

Lo que sea la marca Klaukol pasame un png y veo como injertarla, porque no hay una para reemplazar.

**Comment by LeandroBraier** [comment]
Entiendo, perfecto. Acá las tengo. Te las paso más tarde así ya podemos
dejar subido el juego para febrero.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-27 15:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Esto queda cerrado hasta próximo aviso. El cliente lo olvidó y nos complica la vida. Cambiamos de juego.

abrazo
