### ISSUE TITLE
Bug en Comunidad de Vendedores: tildes en títulos de temas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#232]
@FAAREIA te fijás qué pasa que no puedo utilizar tildes en los titulos de los temas? Antes podía, mirá como se ven ahora:

<img width="719" alt="captura de pantalla 2015-12-01 a las 6 19 27 p m" src="https://cloud.githubusercontent.com/assets/6719872/11514159/dddaada6-9855-11e5-9ef8-6759c2de49de.png">

**Comment by mkreyness** [comment]
Hay otros cargados con acentos y salen bien ? Debes haber cambiado tu encoding

**Comment by LeandroBraier** [comment]
jaja no sé cómo hacer eso pero estoy hablando de título que antes
funcionaban bien ahora no. Me parece que lo que cambió es algo en la
plataforma, no mi encoding, porque yo no los volví a cargar.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Nunca entendí como se manejan las tíldes. Hay veces que el template las toma y veces que no.
Osea, hay veces que guardo un html con tildes, lo subo y todo perfecto. Hay otras veces en que hago lo mismo y el navegador los muestra como resalta lea.
Habría que ver porque pasan esas cosas, aunque es un tema que parece dificil de rastrear

**Comment by mkreyness** [comment]
No, no, fue un cambio de motor de base de datos.
El problema no es con los HTML sino con la info levantada de la base.
El motor anterior (mysql 5.6) tenia como default traer las cosas en utf8, y este que instalaron sin nisiquiera avisar (mariaDB) tiene por default otro charset.
Tuve que agregarle a cada programa un forzado de charset en la apertura de la base para que todo vuelva a la normalidad.

**Comment by FAAREIA** [comment]
joya marce.

**Comment by LeandroBraier** [comment]
@mkreyness consulta: esto ya quedó resuelto en todos nuestros sitios de Duplika?

Me refiero a todos los de ParexKlaukol:

parexklaukol.com.ar/
parexklaukol.com.ar/klaukol-impermeable-potenciado/
http://parexklaukol.com.ar/cgi-bin/maincolo.pl
www.parexklaukol.com.ar/vendedores/
http://www.parexklaukol.com.ar/guia-corralones/

http://www.parexuruguay.com.uy/

http://www.parexparaguay.com.py/

http://www.revear.com.ar/

http://cuidateatiempo.org/

http://www.rioanchocolonia.com/

Yo no veo problemas pero por las dudas revisemos que no nos pase lo mismo en los otros.

abrazo

**Comment by mkreyness** [comment]
Las paginas que no salen de base de datos no se ven afectadas por el problema.
Yo actualice productos/novedades/vendedores/torneos/colocadores/corralones/distribuidores revear
Lo que no puedo modificar es lo de la base de datos vieja de Klaukol de donde las aplicaciones toman datos (calculador/fachadas/etc.) pero no vi tampoco que salgan cosas mal.

RioAncho no esta hosteado en Dupliika asi que no tiene nada que ver.

CuidateaTiempo ni me acuerdo como se accedia, voy a buscar y reviso.

**Comment by mkreyness** [comment]
En FUCA solo jorobaba en el CMS, ya lo ajuste.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by FAAREIA** [comment]
Marce, fijate que en la página del listado de productos Klaukol Parex Lanko en AR UY PY, salen mal los caracteres latinos. Es raro porque en el resto de las páginas se ve todo bien, solo afecta a las categorías esas.

**Comment by mkreyness** [comment]
Otra vez habran cambiado algo en la base de datos de Duplika. Yo ya habia adaptado todo para que salieran bien.

**Comment by mkreyness** [comment]
ahora chequeo

**Comment by mkreyness** [comment]
creo que ya quedo bien, faltaba tocar un lugar.

**Comment by FAAREIA** [comment]
Ahi lo vi y quedó perfecto
