### ISSUE TITLE
Nueva Dinámica Comunidad de Vendedores: Subir una foto

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#233]
@mkreyness y @FAAREIA necesito que me armen una dinámica que permita al usuario subir una foto y que esa foto se envié automáticamente por mail a klauko.marketing@klaukol.parex.com

Yo la semana que viene no voy a estar. Vuelvo el lunes 14/12 con todo, así que porfa necesito tener esto listo para ese día así podemos cargar una nueva dinámica. Confirmenme si llegamos porfa. 

abrazo

**Comment by mkreyness** [comment]
Es un limite de una unica foto por usuario ? Hace falta que la foto vaya attached o podemos hacer un link como con los castings ?
Recordá que no podemos mandar mas de 200 mails por hora, incluyendo cualquier mailing que pueda ser concomitante (pah!) con esto. Con lo cual si pudieramos evitar usar el mail, mejor.
Yo haria otra cosa, pondria en el CMS un listado de las fotos subidas por los usuarios para que la gente de Klaukol pueda mirarlas.

**Comment by LeandroBraier** [comment]
Dale, hagamos eso. El cliente me pidió que les llegue a un mail, pero lo
del CMS es mejor. Hagamos así. No creo que tengas más de 100 fotos en
total. Están entrando no más de 100 usuarios diferentes al mes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-04 18:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Y donde/como seria el boton para cargarlo, en el perfil ? @FAAREIA ya tenes claro donde poner que ?
Porque el resto mio es muy simple.

**Comment by LeandroBraier** [comment]
Excelente MK! Esperalo a Fede entonces y le aplicás lo tuyo al final.

El cargar la foto es un tipo de "tema" nuevo, como el de Compartir posteo,
el de Trivia, el de Juego, etc. Este seria un "Subir Foto" o algo así. En
diciembre se va a usar para invitar a la gente a subir una foto de cómo
está celebrando fin de año, pero después puede ser para otra cosa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-04 18:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ah, entonces si me involucra mas cosas porque eso implica sumar puntos, no ?

**Comment by LeandroBraier** [comment]
Exacto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ok, en definitiva esto es un "juego".
@FAAREIA entonces armalo basandote en alguno de los templates que hay de juegos, por ejemplo el de juego-embedT que es el mas sencillito.

**Comment by LeandroBraier** [comment]
Chicos: no se olviden que edto deberia quedar listo hoy para que lo pueda
modtrsr al cliente el lunes y ya lanzarlo ese dia. Como venimos?

**Comment by mkreyness** [comment]
Yo a partir de que @FAAREIA me avise el template en un rato hago lo que falta, pero tengo que trabajar sobre un template concreto que ya tenga todos los elementos.

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/vendedores/juego-subir-foto.html

Ahi va la base.
La idea era hacer algo no estático y darle algo de vida.
- Cuando el usuario elige una foto, se agrega la clase "progreso".
- Al seleccionar la foto, debería empezar el upload. Sería como un autosubmit.
- Si el tipo cambia la foto, se quita la clase "progreso" y deberia interrumpirse el upload.
- Cuando el upload se completa, se adiciona otra clase más: "finalizado".
- Todas las clases mencionadas se agregan/quitan del "div.subir"

**Comment by LeandroBraier** [comment]
Está bueno Fede. En el circulo puedo subir una foto desde el cms? Porque
necedito como siempre subir una imagen que explique la dinámica.

El botón deberia decir: "Seleccionar y subir foto"

**Comment by FAAREIA** [comment]
El fondo gris lo podes usar para poner una imagen con texto. Lo que si tenés que dejar el círcúlo del centro vacio porque el contenido que pongas ahi va a taparse.

**Comment by FAAREIA** [comment]
También se puede achicar el círculo rojo y sacar el botón que dice "subir foto y ganar puntos". Lo que si hay que mantener es el círuclo rojo a tamaño actual o más chico.

**Comment by mkreyness** [comment]
Ojo yo tengo que hacer submit para que se haga el upload, todo eso de las clases deja de verse inmediatamente con el submit. Lo unico que puedo hacer es volver a llamar a la misma pagina despues de haberlo subido y sumado los puntos y ahi forzarle la clase "finalizado" para que se vea. Lo ideal seria tambien que muestre directamente la foto subida no ?
El template sobre el que estoy trabajando ya adaptado es este, pero por ahora no toques nada, yo despues te aviso si necesito que intervengas:

/www/templates/parexklaukol/vendedores/juego-uploadT.html

**Comment by mkreyness** [comment]
Bueno ya esta masomenos todo, se puede usar por aca, no esta habilitado al publico todavia obviamente:

http://www/parexklaukol.com.ar/cgi-bin/jugar2.pl?usuario=marcelokreyness&clave=pepe&id=27

Ojo una vez que se sube una foto no deja subir mas. No se si deberia, si deberia mostrarla una vez subida, o cual es la idea. Tiene puesto que sume 100 puntos pero como yo estoy suspendido no me los suma, igual probe de dessuspenderme y anda bien.
Pueden probar con otros codigos de usuario si tienen.

Lean: en el CMS ya se puede ver la lista de fotos que los vendedores suban por aca.

**Comment by LeandroBraier** [comment]
Gracias MK! Lo veo bien, en el CMS se suben las fotos. No importa el peso se suben todas? 

Solo una modificación te pido Fede para mañana: No es una foto de perfil lo que les pedimos que suban, sino una foto de cómo festejaron el cierre de año en su corralón, por lo cual no debería ser un circulo con un icono de usuario lo del medio, sino un formato 16:9 donde pueda entrar una foto común y corriente.

abrazo

**Comment by mkreyness** [comment]
No estoy haciendo control de tamaño, siendo que c/u puede subir una sola foto esta bastante acotado.
Tampoco es que se manden por mail asi que salvo por el espacio en disco, que por ahora estamos bien, no jode.

**Comment by LeandroBraier** [comment]
Apa, me olvidé de decirte eso. Necesitaríamos que esas fotos se envíen por
mail al mail de Klaukol. Es un lio? Sino debería poder bajarlas todas
juntas en un zip con sus nombres de usuario y enviarlas yo manualmente.
Decime como te parece más fácil para que vos gastes menos esfuerzo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-13 13:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Fue lo primero que me dijiste y te planteé que eso era un problema, por lo cual te propuse que se vean por CMS, a lo que contestaste (ver arriba): "Dale, hagamos eso. El cliente me pidió que les llegue a un mail, pero lo del CMS es mejor. Hagamos así. "

Cual seria el MOMENTO de juntar todas y mandarlo ? Eso es algo que se hace a mano muy facil, y al pedo de automatizar si se va a hacer una sola vez.

**Comment by LeandroBraier** [comment]
Claro, a eso me refiero. No me acordaba que ya lo habíamos hablado.

Ponele que publicamos el lunes la dinámica, el miércoles a la tarde les
mando las fotos zipeadas o en un wetransfer para que me digan cuales están
OK y las publicamos de alguna manera.

La otra opción es que les demos acceso a esa sección dentro del CMS, al
usuario "mantenimiento". Lo único que necesito es poder descargarme las
fotos de un modo práctico, como me exporto el excel, no una por una con
botón derecho.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-13 13:41 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No hay ningun problema en darles acceso y que las miren directamente ahi, si queres agrego un tilde para que marquen las que les guste y podemos hasta hacer que AUTOMATICAMENTE se publiquen donde sea que se tengan que publicar (con el simple hecho de estar tildadas, en una pagina que entiendo que todavia no fue siquiera definida).
Hay si un problema y es que podrian pisarse, le voy a cambiar el nombre de la foto a que sea directamente el del usuario, te parece ?

Y si las fotos las quieren publicar en otro lado que no sea este server (no entiendo por que seria asi) te las bajo yo en un zip, no tiene sentido ponerme a programar una interface que zippee y descargue conjuntos de fotos via web.

**Comment by LeandroBraier** [comment]
Ok, entiendo MK. Las publicaríamos en Facebook, esa sería la plataforma externa. Porfa habilitale esa sección al usuario mantenimiento entonces. 

Aparte, es cierto que todavia falta una sección como la de ganadores donde se muestren las fotos seleccionadas. @FAAREIA avancemos con esa página porfa. Puede ser para el martes, no hace falta que sea para mañana.

abrazo

**Comment by mkreyness** [comment]
Hice lo siguiente: abri el menu del CMS de Club de Vendedores en dos partes: Administracion (solo visible para el usuario Admin) y "Fotos Subidas por Vendedores" que lo ven ambos. Si el dia de mañana aparecen mas cosas que puedan manejar desde "Mantenimiento" las agrego ahi.

Puse un tilde para que puedan marcar las que quieran.
Me falta lo de que el nombre del archivo se guarde igual al usuario.

**Comment by LeandroBraier** [comment]
Excelente MK. Mil gracias!!!

abrazo grande

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-13 18:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
buen día @FAAREIA y @mkreyness  !! No olviden que hoy tenemos que terminar esta dinámica.

Aparte quedaría la página donde mostraríamos todas las fotos subidas, eso puede ser para mañana.

@FAAREIA faltaría modificar el circulito del medio. No se trata de una foto de perfil lo que hay que subir. Para hacerlo más fácil y rápido te propongo lo siguiente: dejalo circular, pero cambiá el ícono que pusiste por un típico ícono de flechita para arriba que significa "Upload". Con ese ícono y el texto de abajo diciendo "Subir mi foto y sumar 100 puntos" ya se va a entender bien.

@mkreyness probé subir una foto de fondo en el cms y no se despliega en el fondo de la dinámica. Copié el link en el espacio de video, como me pedís siempre, pero no ocurrió: Te fijás qué estás pasando porfa?

Deberíamos poder resolver esto dentro de la mañana.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya le cambié el ícono y le meti los ajustes al template.

**Comment by LeandroBraier** [comment]
En qué URL lo actualizaste Fede?

Yo estoy mirando acá:

http://parexklaukol.com.ar/vendedores/juego-subir-foto.html

Y veo todo en blanco.

**Comment by FAAREIA** [comment]
Lo metí en el template online, hay que probarlo a ver si se anima. Prueben de subir un archivo de 1mb al menos

**Comment by LeandroBraier** [comment]
No me aparece nada Fede. Me aparece en blanco la página.  Ni el botón de
subir ni nada. Solo el titulo "Trivia Klaukol nos se cuanto" arriba y el
resto de lo que es columna derecha y footer gral de comunidad de vendedores.

Pero en la dinamica propiamente dicha veot odo en blanco. Estoy en Chrome.

**Comment by FAAREIA** [comment]
Si, marce tiene que habilitar la posibilidad de subir la foto base que tiene el juego. Al final la foto va a ser la subida también

**Comment by LeandroBraier** [comment]
Mirá, en el link que te decía lo veo así:

<img width="1201" alt="captura de pantalla 2015-12-14 a las 4 04 03 p m" src="https://cloud.githubusercontent.com/assets/6719872/11790363/21839f76-a27a-11e5-847d-92bb59b0ae2e.png">

En el online lo veo así:

<img width="1115" alt="captura de pantalla 2015-12-14 a las 4 05 54 p m" src="https://cloud.githubusercontent.com/assets/6719872/11790376/30c64c2c-a27a-11e5-8c92-db5c57b08b2b.png">

En ninguno lo tengo completo. Lo necesitaría urgente, porfa dale prioridad a esto que el cliente me lo está pidiendo para YA.

abrazo

**Comment by LeandroBraier** [comment]
Eso lo entiendo, Fede. El tema es que necesito que esto esté resuelto urgente y no entiendo por qué se está demorando. @mkreyness ayudanos porfa.

**Comment by mkreyness** [comment]
Ya esta hecho lo de que al final muestre la foto subida, pero cuando todavia no hay foto ahora NO SE VE EL FORMULARIO, o sea que no hay como cargar.

Fede miralo urgente, porque el form esta en el HTML, pero no se ve.

http://www.parexklaukol.com.ar/cgi-bin/jugar2.pl?usuario=marcelokreyness&clave=pepe&id=27

esta virgen de fotos.

**Comment by LeandroBraier** [comment]
Fede, hoy me dejaste bastante en banda con este tema. Por favor resolvelo para mañana bien bien temprano, porque necesito mandarlo terminado a las 9 am.

abrazo

**Comment by FAAREIA** [comment]
Hecho lo de la foto. En el tag del form puse un style con una url de background-image. La variable debe ser la ruta, ahora esta puesto estático.
@mkreyness

**Comment by LeandroBraier** [comment]
@FAAREIA ya lo publiqué, pero en los 2 mensajes internos del juego dice "Sumá 100 puntos". Debería decir "Sumá 200 puntos". y "Sumaste 200 puntos". Lo podrás cambiar lo antes posible porfa?

**Comment by mkreyness** [comment]
Ok, lo cambie por `<!--imagenjuego-->` como te dije en el whatsapp, asi toma lo que pone @LeandroBraier en el CMS.

**Comment by LeandroBraier** [comment]
Gracias a los dos!!! Al fin doy por finiquitada esta tarea!!! abrazo grande
