### ISSUE TITLE
Backup Videos Maratón Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#234]
@mkreyness consulta: todavía tenés videos de la maratón archivados? Necesitamos 3 de referencia nada más, para mostrarle a otro cliente los mejores ejemplos.

**Comment by mkreyness** [comment]
Si, en algun lado, busco y te aviso que tengo.

**Comment by mkreyness** [comment]
Ya los encontre, el asunto es como los eligen, son 24 Gb, mucho hasta para WeTransfer.
Son solo los bloques de 12 segundos, no tienen la parte intro ni final.
Pero son muchos... 4003 archivos.

**Comment by LeandroBraier** [comment]
Entiendo. Mandame por wetransfer 100 de los de 12 segundos que estén más o
menos a la mitad de los 4003.

De ahí yo hago una selección de 3. Si me falta alguno más te aviso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-14 10:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ja lo de "la mitad" es algo muy relativo, no tengo la hora de c/u, solo tengo el numero de participante.
Mandarte los "participantes con numeros del medio" no significa nada en realidad.
Tampoco la fecha de creacion del video dice nada.
Los videos se generaron en su momento todos juntos (salvo algun descolgado que se anotó despues)  en orden alfabetico, asi que despues del 10001 viene el 2, etc.
Tendria que armar algo intercalado con el excel que mandaron en su momento (la base de datos ya no la tengo), pero eso va a llevarme horas y me estoy yendo.
Te mando 100 cualquiera y elegis de ahi ?

**Comment by LeandroBraier** [comment]
Dale, de una.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2015-12-14 10:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Listo MK! Gracias!
