### ISSUE TITLE
Actualizar Fichas Técnicas de 3 productos en Web Argentina, Uruguay y Paraguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#235]
@FAAREIA esto por ahi lo podés pasar a @braulio-evangelisti 

Solo necesitamos actualizar las fichas técnicas de 3 productos en la web de Argentina, uruguay y Paraguay. En todas. 

Lanko 453
[Ficha Teìcnica LANKO 453.pdf](https://github.com/LeandroBraier/Klaukol/files/61637/Ficha.Teicnica.LANKO.453.pdf)

Lanko 901
[Ficha Teìcnica LANKO 901.pdf](https://github.com/LeandroBraier/Klaukol/files/61638/Ficha.Teicnica.LANKO.901.pdf)

Flex Fluido
[FT_Klaukol_flex_fluido_190215.pdf](https://github.com/LeandroBraier/Klaukol/files/61639/FT_Klaukol_flex_fluido_190215.pdf)

**Comment by braulio-evangelisti** [comment]
Lea nunca tuve acceso al CMS.

Abrazo

**Comment by FAAREIA** [comment]
Lea, al final eso se actualizaba desde el FTP o marce hizo un upload en el CMS? Sino reemplazamos los archivos en el ftp.

**Comment by LeandroBraier** [comment]
Fede, ya lo habíamos hablado en un ticket anterior a esto. Te copio lo que había dicho MK. En resumen, vos tenés que subir las fichas a la carpeta correspondiente y avisarme, yo desde el CMS completo el nombre correcto.

MARCE DIXIT:
Si las fichas tecnicas son los documentos adjuntos, de alguna manera ESTA todo en el CMS.
El asunto es que lo que no se puede es UPLOADEARLOS via el CMS, porque lo que nos vino en los backups estaba todo desperdigado.

Hay que subirlos a una carpeta accesible desde donde el sistema espera que esten, que por como vino todo mal parido es:

public_html/bkps/parexklaukol.com.ar/media/custom/upload/XXXX (o parexparaguay.com.py, etc.)

y en la parte de archivos adjuntos del CMS poner solo la parte XXXX

Por ejemplo ahora el del Porcellanato Fluido esta en

http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar/media/custom/upload/File-1402063506.pdf

y en el CMS (solapa Adjuntos) dice:

Nombre: Ficha Tecnica
URL: /pdf/productos/File-1402063506.pdf

porque asi vino en algun momento, pero el programa (asco total) reemplaza /pdf/productos por /media/custom/upload

O sea, no se si los archivos que tenes que cambiar conservan los nombres o tienen otros, pero si se bajan en

public_html/bkps/parexklaukol.com.ar/media/custom/upload/

y se cambian los nombres en el CMS, todo deberia salir andando.
Probemos con uno si quieren.

**Comment by braulio-evangelisti** [comment]
Ahi subi los 3 pdf en los 3 directorios de cada idioma. Los descargó de aca con estos nombres:

Ficha.Teicnica.LANKO.453.pdf
Ficha.Teicnica.LANKO.901.pdf
FT_Klaukol_flex_fluido_190215.pdf

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Brau!! Gracias!
