### ISSUE TITLE
Bug Casa Interactiva

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#236]
@mkreyness tenés idea por qué estos links no andan?

http://www.parexklaukol.com.ar/aplicaciones/casa-interactiva.html

Tenia la idea de que los habiamos dejado andando. Me suena a un cambio de duplika.

**Comment by mkreyness** [comment]
Faltan todos los links que habiamos hecho para convertir esos URLs en los productos actuales.
@FAAREIA vos estuviste moviendo cosas en la carpeta www/parexklaukol/aplicaciones ?

**Comment by FAAREIA** [comment]
Negativo. Ni idea que pudo haber pasado.

**Comment by mkreyness** [comment]
habria que generar todos los redireccionamientos de nuevo. 
Voy a buscar a ver si tengo el mail en el que me pasaste el relevamiento de todos los que usa, @LeandroBraier

**Comment by LeandroBraier** [comment]
Yo no lo encuentro pero me figura en github como q

**Comment by LeandroBraier** [comment]
Yo no lo encuentro pero me figura en github como q te lo mandé el 16 de junio

**Comment by LeandroBraier** [comment]
Acá los encontré!

[Uploading Nuevos Links La Casa Interactiva.xlsx…]()
