### ISSUE TITLE
Bug Video Instructivo en Comunidad de Vendedores y Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#237]
@FAAREIA lo antes que puedas necesitaría que cambies el embed del video instructivo de la Comunidad de Vendedores. Ahora lo subimos a otro canal de YouTube y cambió el embed. Te copio acá la URL nueva:

https://www.youtube.com/embed/DZoLAyO_IpQ

Abrazo

**Comment by LeandroBraier** [comment]
En Club de Colocadores pasa lo mismo. La URL de colocadores es:

https://www.youtube.com/embed/tRY4OJl3ugo

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea. Ya estan actualizados en los dos sitios.

**Comment by LeandroBraier** [comment]
Gracias Brau!!! abrazo
