### ISSUE TITLE
Bug Klaukol Refractario de Fabián Lopez

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#238]
@mkreyness se dio un caso en la Comunidad que nunca se había dado.

El usuario "fabianlopez" nos escribe esto en Facebook:

"Hola gente, les quería avisar que en la pagina de la comunidad hago la trivia del Klaukol Refractario pero no me suma los 60 puntos y aunque me diga que esta hecha , la puedo seguir haciendo y no me suma los puntos en ninguna ocasión."

Me fijé en el CMS y resulta que él ya dio Like y sumó 30 puntos, compartió el video y sumó otros 60 puntos y ahora hace la trivia y le pasa eso. ¿Puede tener que ver con que ya compartió el video y por eso no puede sumar otra vez 60 puntos?

**Comment by LeandroBraier** [comment]
@mkreyness viste esto?? Lo necesito urgente resolver.

**Comment by mkreyness** [comment]
No habia visto este thread. Una trivia ya hecha JAMAS va a volver a sumarle puntos. Asi esta programado, no entiendo cual es el "problema" en eso, seria ridiculo que por contestar las mismas preguntas una y otra vez le siguiera sumando puntos.

**Comment by mkreyness** [comment]
el like y el compartir son "juegos" diferentes, no influyen. Tiene que haber ganado puntos parcial

**Comment by mkreyness** [comment]
Bueno, Lopez tenia razon.
Si ANTES de jugar la trivia compartis, como hay 3 formas de jugar la trivia, al encontrar algo YA JUGADO por el mismo tema, creia que era alguna de las otras formas de la trivia.
Haciendo al reves (primero trivia y despues compartir) no pasaba.
Ya lo arregle.
Decile que conteste de nuevo que ahora si le va a sumar.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by mkreyness** [comment]
Gracias a Fabian Lopez que se molesta en encontrar bugs !
