### ISSUE TITLE
Bugs de Duplika impactando #3: Micrositio Klaukol Impermeable Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#239]
@FAAREIA fijate que dejó de funcionar el mouser over que activaba el GIF:

http://www.parexklaukol.com.ar/klaukol-impermeable-potenciado/home.html

Debe ser por estos cambios locos que hace Duplika. Porfa lo podrás resolver mañana a la mañana? Tenemos una reunión donde podríamos llegar a mostrar este sitio.

**Comment by FAAREIA** [comment]
desde ese link directo no me funciona, tenés que ir desde el Preloader:
http://www.parexklaukol.com.ar/klaukol-impermeable-potenciado/

Asi te precarga los gif.

**Comment by LeandroBraier** [comment]
Pero yo fui a esta url y me re dirigió a la otra.

**Comment by FAAREIA** [comment]
Te redirige cuando ya tenes todo cargado. En firefox y chrome lo veo bien.
Dale F5 por las dudas, capas que te quedó cacheado algo muy viejo.

**Comment by LeandroBraier** [comment]
No sé qué fue. Ahora lo pruebo y me lleva sin la home. Directo al /klaukol-impermeable-potenciado/

Raro pero lo importante es que anda. Gracias Fede!!
