### ISSUE TITLE
Revear Resubido

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#24]
Fede, acá te voy a avisar cuando tenga terminado el testeo. En principio lo veo impecable y que funciona mucho mejor que el sitio original (!!!). 

Me está tirando unos errores tremendos el sitio original. Me pide login, después no me pide. Tira errores 401. Te adjunto captura solo por curiosidad. El proveedor nos estará cachando?

![captura de pantalla 2015-04-21 a la s 10 28 35](https://cloud.githubusercontent.com/assets/6719872/7253049/0eeabf9a-e810-11e4-9cf4-87a2fb7dbd7a.png)

**Comment by FAAREIA** [comment]
Buenisimo Lea! Anda más rápido porque no hay base de datos, esta todo en los HTML puros.

Lo del error me ha pasado ya hace unas semanas, y no se que es pero es un bug del sitio. No creo que sea el proveedor, debe ser algo que dejaron mal hecho desde siempre.

**Comment by LeandroBraier** [comment]
Fede, en este doc tenés todas las observaciones de Revear. Incluyo referencias al Backup hecho por MK, que mandó recién.

https://docs.google.com/presentation/d/1BumXn-WRYvtO3_Jd1GCsbo7TCIeKOyyGJgpdyogEFRA/edit?usp=sharing

Cuando tengas el testeo de los otros sitios pasenmelos y le doy una revisada final por las dudas.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya subí los docs a revear. Cada producto tiene su PDF descargable ahora.
La foto de la novedad ahora la corrijo.

Lo que si me di cuenta es que esto de descargar el sitio es una solución temporal ya que hay muchas páginas duplicadas, que terminan duplicandose porque son accesibles desde varias rutas. Por ejemplo, un producto es accesible desde "productos" o sino también entrando a "productos" y aplicano un filtro.
Esto de los html duplicados tarde o temprano google lo sanciona
