### ISSUE TITLE
Mailing Premios Semestrales

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#240]
Brau, te paso los datos a incluir y comunicar:

INFORMACIÓN A INCLUIR

Torneo de Potenciados

¡Ya tenemos los ganadores semestrales!

1º Puesto: Matercon S.A.

Ganó un viaje al Caribe*

Sus vendedores ganaron $50.000

También su representante comercial y asistente técnico Klaukol ganaron un viaje al Caribe.

2º al 15º puesto**

Ganaron grandes descuentos en productos Klaukol

(letra chica)
- El primer premio consiste en 1 (un) viaje para 2 (dos) personas al Caribe por un total de hasta 50 (cincuenta) mil pesos para el DISTRIBUIDOR y otros 2 (dos) viajes de hasta 25 (veinticinco) mil pesos argentinos para el REPRESENTANTE COMERCIAL y el ASISTENTE TÉCNICO.
  *\* Obtuvieron un 5% de descuento en compras participantes los corralones del 2º al 15º puesto: XXXXXXXXXXXXX, XXXXXXXXX, XXXXXXXXXXXX, XXXXXXXXXXXXX,XXXXXXXXXXXXX,XXXXXXXXXXXX, XXXXXXXXXXXXX, XXXXXXXXXX XXXXXXXXXXXX, XXXXXXXXXXXXXX, XXXXXXXXXXXXX,XXXXXXXXXXXXX, XXXXXXXXXXXX, XXXXXXXXXX y XXXXXXX. 

Abajo te paso una captura de la versión que estoy haciendo yo pero buscale una vuelta distinta, más en la forma en que lo resolviste vos via mailing en los mailings de premios del Torneo de Potenciados.

<img width="832" alt="captura de pantalla 2016-01-04 a las 7 14 27 p m" src="https://cloud.githubusercontent.com/assets/6719872/12101725/116d0306-b315-11e5-8fb9-26a4d9cdbb69.png">

Cualquier duda avisame. Gracias por ayudarme, voy a estar hasta las mil con esto.

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Otra vez muchas gracias por el esfuerzo de ayer!

Aquí te copio las 6 imágenes para los mails a enviar a los 6 grupos. Dale prioridad apenas arranques hoy.

Porfa a todos agregales abajo el footer que veníamos incluyendo en los mails, que es este (te paso captura, vos usá el que ya tenés maquetado):

<img width="644" alt="captura de pantalla 2016-01-05 a las 9 02 24 a m" src="https://cloud.githubusercontent.com/assets/6719872/12114449/bd6ebdac-b388-11e5-8a8b-659ca2d1613c.png">

IMAGEN GRUPO A

![ganadores-semestrales-grupo-a](https://cloud.githubusercontent.com/assets/6719872/12114458/cfa025d8-b388-11e5-8b1e-86e02a675a2e.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Zeramiko ganó un viaje al Caribe (hasta $50.000). Sus vendedores ganaron $50.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $25.000). Del 1º al 3º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Olaz Maria Rosa Del Valle - Zeramiko, Eden Sanitarios y L.E. CER SRL.

IMAGEN GRUPO B

![ganadores-semestrales-grupo-b](https://cloud.githubusercontent.com/assets/6719872/12114541/7a58abbc-b389-11e5-8d3e-59309fffca6f.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Antonio Prevedello y Cia SRL ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $12.500). Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Antonio Prevedello y Cia SRL, Cerámica Firenze, Cerysan, Toba y Materiales Basualdo

IMAGEN GRUPO C

![ganadores-semestrales-grupo-c](https://cloud.githubusercontent.com/assets/6719872/12114565/a1176ea0-b389-11e5-9aa4-f0fdd9e57e0c.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Corvalan Silvia Susana ganó un viaje a Brasil (hasta $10.000). Sus vendedores ganaron $10.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $5.000). Del 1º al 15º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Corvalan Silvia Susana, Construcciones 2000, Caliquis Mariela Rosana, Oga Mat S.A., Schlatter Ruben Oscar, Dimasur, Lar Chilecito, Corralon San Lorenzo, Transporte Y Materiales Fyh, Corralon El Gaucho, Ladrisur S.A., Cosamar S.A., Corralon Ailla Winka S.R.L., Cristobal Parra Y Cia. y Pescio Julio R. - Aktual Revestimientos.

IMAGEN GRUPO D

![ganadores-semestrales-grupo-d](https://cloud.githubusercontent.com/assets/6719872/12114619/03b69dce-b38a-11e5-9c85-4f3ae024813e.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Balcarce 54 ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $12.500). Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Balcarce 54, COPMACO LTDA y DLM Construcción.

IMAGEN GRUPO E

![ganadores-semestrales-grupo-e](https://cloud.githubusercontent.com/assets/6719872/12114611/ebc2d174-b389-11e5-94db-1711948bb839.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Matercon SA ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $12.500). Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Matercon SA, La Noria S.H., Espeche Miguel Angel, Plisud y Calera San Justo.

IMAGEN GRUPO F

![ganadores-semestrales-grupo-f](https://cloud.githubusercontent.com/assets/6719872/12114595/d0124b12-b389-11e5-943d-a187c42019d0.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Mis Materiales SA ganó un viaje a Brasil (hasta $10.000). Sus vendedores ganaron $10.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $5.000). Del 1º al 15º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Mis Materiales SA, Materiales 2003, Dimaco, Pilares De Alejandria, Corralon El Clasico, Camerino Scarlatto, El Nuevo Corralon, Casamm, Gumy, Luciano Pablo Nestor Menendez Hnos., Bragagnolo Jose E Hijos, Belli Y Cia S.A., Construcciones Aquino S.A. y Grandes Almacenes Esperanza S.A.C.I.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti hay detalles de texto a corregir en imágenes y textos alt. Cuando los tenga confirmados te los mando finales pero vayamos avanzando.

**Comment by braulio-evangelisti** [comment]
http://parexklaukol.com.ar/_mailing/torneo-ganadores-semestrales/torneo-ganadores-a.html
http://parexklaukol.com.ar/_mailing/torneo-ganadores-semestrales/torneo-ganadores-b.html
http://parexklaukol.com.ar/_mailing/torneo-ganadores-semestrales/torneo-ganadores-c.html
http://parexklaukol.com.ar/_mailing/torneo-ganadores-semestrales/torneo-ganadores-d.html
http://parexklaukol.com.ar/_mailing/torneo-ganadores-semestrales/torneo-ganadores-e.html
http://parexklaukol.com.ar/_mailing/torneo-ganadores-semestrales/torneo-ganadores-f.html

**Comment by LeandroBraier** [comment]
Están perfectos Brau! Muchas gracias!

Te voy pasando las imágenes y correcciones de texto alt finales.

Solo te pido que la imagen tenga el vínculo que lleva al login automático. El mismo que ponemos siempre en el botón "Ingresar" Creo que es este:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=%3C!--usuario--%3E&clave=%3C!--clave--%3E

IMAGEN FINAL GRUPO A

![ganadores-semestrales-grupo-a](https://cloud.githubusercontent.com/assets/6719872/12116093/0b6ce346-b396-11e5-93da-44c7e9f3c09d.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Zeramiko ganó un viaje al Caribe (hasta $50.000). Sus vendedores ganaron $50.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $50.000). Del 1º al 3º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Olaz Maria Rosa Del Valle - Zeramiko, Eden Sanitarios y L.E. CER SRL.

IMAGEN FINAL GRUPO B

![ganadores-semestrales-grupo-b](https://cloud.githubusercontent.com/assets/6719872/12116095/12a08ce4-b396-11e5-9dfb-2212cd13d51a.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Antonio Prevedello y Cia SRL ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $25.000). Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Antonio Prevedello y Cia SRL, Cerámica Firenze, Cerysan, Toba y Materiales Basualdo

IMAGEN FINAL GRUPO C

![ganadores-semestrales-grupo-c](https://cloud.githubusercontent.com/assets/6719872/12121768/de2cd0a6-b3b5-11e5-8b69-f6a540795b80.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Construcciones 2000 ganó un viaje a Brasil (hasta $20.000). Sus vendedores ganaron $10.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $20.000). Del 1º al 15º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Construcciones 2000, Caliquis Mariela Rosana, Corvalan Silvia Susana, Oga Mat S.A., Schlatter Ruben Oscar, Dimasur, Lar Chilecito, Corralon San Lorenzo, Transporte Y Materiales Fyh, Corralon El Gaucho, Ladrisur S.A., Cosamar S.A., Corralon Ailla Winka S.R.L., Cristobal Parra Y Cia. y Pescio Julio R. - Aktual Revestimientos.

IMAGEN FINAL GRUPO D

![ganadores-semestrales-grupo-d](https://cloud.githubusercontent.com/assets/6719872/12116109/25a50a4a-b396-11e5-9554-baea11711bd4.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Balcarce 54 ganó un viaje al Caribe (hasta $50.000). Sus vendedores ganaron $50.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $50.000).  Del 1º al 3º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Balcarce 54, COPMACO LTDA y DLM Construcción.

IMAGEN FINAL GRUPO E

![ganadores-semestrales-grupo-e](https://cloud.githubusercontent.com/assets/6719872/12116130/46267f42-b396-11e5-8fdd-9b136cae9bf3.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Matercon SA ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $25.000). Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Matercon SA, La Noria S.H., Espeche Miguel Angel, Plisud y Calera San Justo.

IMAGEN FINAL GRUPO F

![ganadores-semestrales-grupo-f](https://cloud.githubusercontent.com/assets/6719872/12116138/5174c61a-b396-11e5-9119-444df25a21bd.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Mis Materiales SA ganó un viaje a Brasil (hasta $20.000). Sus vendedores ganaron $10.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje (hasta $20.000). Del 1º al 15º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Mis Materiales SA, Materiales 2003, Dimaco, Pilares De Alejandria, Corralon El Clasico, Camerino Scarlatto, El Nuevo Corralon, Casamm, Gumy, Luciano Pablo Nestor Menendez Hnos., Bragagnolo Jose E Hijos, Belli Y Cia S.A., Construcciones Aquino S.A. y Grandes Almacenes Esperanza S.A.C.I.

Abrazo

**Comment by LeandroBraier** [comment]
Ojo que cambié IMAGEN y Texto Alt de GRUPO C. Solo eso. Avisame porfa cuando lo tengas. TOmate las imagenes y textos actuales que te pasé en la entrada previa a este texto.

abrazo

**Comment by braulio-evangelisti** [comment]
No me la carga a la imagen C, si podes subila de nuevo por favor

Asi me aparece

IMAGEN FINAL GRUPO C

[Uploading Ganadores-Semestrales-Grupo-C.png…]()

**Comment by LeandroBraier** [comment]
Ahi la resubí Brau. Gracias!!

**Comment by braulio-evangelisti** [comment]
Ya estan las nuevas fotos con sus respectivos "alt's" Lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!

**Comment by mkreyness** [comment]
Ya se puede mandar o falta alguna aprobacion ?

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Gracias Brau! Están perfectos! Ahora te pido algo en ticket aparte.

**Comment by LeandroBraier** [comment]
Están OK pero aún no lo quieren enviar porque quieren que hagamos unos
ajustes en la página del Torneo antes de enviarlo. Yo te aviso.

Los ajustes van en ticket aparte para Braulio pero te copio a vos por las
dudas si podés facilitarle algo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-05 15:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@braulio-evangelisti va otro cambio de imagenes pedido por el cliente. No te preocupes que si a vos te están volviendo loco a mi ni te cuento.

GRUPO A

![ganadores-semestrales-grupo-a](https://cloud.githubusercontent.com/assets/6719872/12154149/ac502c76-b49c-11e5-8259-6938ae74c7d5.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Zeramiko ganó un viaje al Caribe (hasta $50.000). Sus vendedores ganaron $50.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje de hasta $25.000 cada uno. Del 1º al 3º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Olaz Maria Rosa Del Valle - Zeramiko, Eden Sanitarios y L.E. CER SRL.

GRUPO B

![ganadores-semestrales-grupo-b](https://cloud.githubusercontent.com/assets/6719872/12154170/cd33c2f4-b49c-11e5-96cb-fd2c39926b3e.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Antonio Prevedello y Cia SRL ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje de hasta $12.500 cada uno. Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Antonio Prevedello y Cia SRL, Cerámica Firenze, Cerysan, Toba y Materiales Basualdo

GRUPO C

![ganadores-semestrales-grupo-c](https://cloud.githubusercontent.com/assets/6719872/12153625/9b258bba-b499-11e5-82ce-c061d9eecbf7.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Construcciones 2000 ganó un viaje a Brasil (hasta $20.000). Sus vendedores ganaron $10.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje de hasta $10.000 cada uno. Del 1º al 15º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Construcciones 2000, Caliquis Mariela Rosana, Corvalan Silvia Susana, Oga Mat S.A., Schlatter Ruben Oscar, Dimasur, Lar Chilecito, Corralon San Lorenzo, Transporte Y Materiales Fyh, Corralon El Gaucho, Ladrisur S.A., Cosamar S.A., Corralon Ailla Winka S.R.L., Cristobal Parra Y Cia. y Pescio Julio R. - Aktual Revestimientos.

GRUPO D

![ganadores-semestrales-grupo-d](https://cloud.githubusercontent.com/assets/6719872/12154173/d269c246-b49c-11e5-8c7f-9037437cef27.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Balcarce 54 ganó un viaje al Caribe (hasta $50.000). Sus vendedores ganaron $50.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje de hasta $25.000 cada uno. Del 1º al 3º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Balcarce 54, COPMACO LTDA y DLM Construcción.

GRUPO E

![ganadores-semestrales-grupo-e](https://cloud.githubusercontent.com/assets/6719872/12154179/d6b0ff5e-b49c-11e5-9843-ad4f77789aaf.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Matercon SA ganó un viaje a Brasil (hasta $25.000). Sus vendedores ganaron $25.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje de hasta $12.500 cada uno. Del 1º al 5º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Matercon SA, La Noria S.H., Espeche Miguel Angel, Plisud y Calera San Justo.

GRUPO F

![ganadores-semestrales-grupo-f](https://cloud.githubusercontent.com/assets/6719872/12153641/b00dba3e-b499-11e5-96f8-e48cec926bf6.png)

Texto Alt= ¡Felicitaciones a los ganadores del Torneo de Potenciados! 1º Puesto: Mis Materiales SA ganó un viaje a Brasil (hasta $20.000). Sus vendedores ganaron $10.000. También su representante comercial y asistente técnico Klaukol ganaron un viaje de hasta $10.000 cada uno. Del 1º al 15º puesto obtuvieron un 5% de descuento sobre el total de las compras participantes del torneo: Mis Materiales SA, Materiales 2003, Dimaco, Pilares De Alejandria, Corralon El Clasico, Camerino Scarlatto, El Nuevo Corralon, Casamm, Gumy, Luciano Pablo Nestor Menendez Hnos., Bragagnolo Jose E Hijos, Belli Y Cia S.A., Construcciones Aquino S.A. y Grandes Almacenes Esperanza S.A.C.I.

**Comment by mkreyness** [comment]
ojo @braulio-evangelisti tambien yo hice cambios en los mailings para que los links apunten a /cgi-bin/ganadorestorneo.pl en vez de a torneo-con-slide.pl, si podes usa las versiones que estan online, si eso te complica mucho y trabajas sobre las tuyas, fijate de ponerle a todos  "ganadorestorneo" donde dice "torneo-con-slide"

**Comment by braulio-evangelisti** [comment]
no hay problema, en un rato bajo los online y reemplazo ahi

**Comment by braulio-evangelisti** [comment]
Ahi subi los cambios

**Comment by LeandroBraier** [comment]
Gracias Brau!!!

**Comment by LeandroBraier** [comment]
abrazo grande a los dos y hasta mañana! Les aviso cuando tengo el ok para los mailings. Supongo que será mañana.

**Comment by LeandroBraier** [comment]
@braulio-evangelisti andás por ahi?

Me llegó el mailing de prueba del Torneo de Potenciados. Dos cosas:

1) El link debería llevar a la página del Torneo, no a la página de Ganadores. Es decir, a la Home del Torneo:

www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=XXXXXXX&clave=XXXXXX

2) El footer se corta al medio en celulares. El corner de Parex Group queda abajo, no en la misma línea del 0800.

Porfa lo podremos acomodar hoy a eso? Coordinalo con @mkreyness para no perder lo que él haya hecho al aplicar cambios.

**Comment by mkreyness** [comment]
Eso de que vaya a la pagina de ganadores lo hice yo, pense que iba asi, porque no habia forma de acceder si no a los premios. Despues me entere que lo pusiste como slide.
Reponele entonces el torneo-con-slide.pl, no va XXXXXXX sino `<!--usuario-->` y `<!--clave-->` como siempre.

**Comment by braulio-evangelisti** [comment]
Ahora los bajo y acomodo

**Comment by braulio-evangelisti** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gtaciaa Brau!
