### ISSUE TITLE
Página de Ganadores Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#241]
@braulio-evangelisti necesitaría que replicaras la página de ganadores de la Comunidad de Vendedores pero en el Torneo de Potenciados.
1.  Que yo pueda cargar texto y fotos chicas y grandes desde el CMS como en la de Ganadores de la Comunidad. (para esto lo copio a @mkreyness 
2. Cambiando a la estética del Torneo de Potenciados.
3. Que en vez de los meses diga:

Premios Primer Trimestre

Premios Segundo Trimestre

Grandes Premios Semestrales

Confirmame si llegamos a tenerlo para mañana porfa.

abrazo

**Comment by mkreyness** [comment]
Braulio: trata de basarte en el template que ya existe en /templates/parexklaukol/vendedores/ganadoresT.html
Lo de los meses (que aca cambia por otros textos) es algo que pongo yo por programa, no te preocupes, para vos es un titulo nada mas.

**Comment by braulio-evangelisti** [comment]
@mkreyness Ahi subi un "ganadoresT.html" de prueba en **/public_html/templates/parexklaukol/torneos** basado en el template de vendedores pero no se donde tengo que ir para probarlo a ver si agarro bien

**Comment by mkreyness** [comment]
todavia no hay nada para probarlo, ahora lo armo en base a esto y vemos.

**Comment by LeandroBraier** [comment]
Gracias a los dos!! Avisenme cuando lo puedo ver así les doy feedback.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-05 18:49 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, tuve que hacer bastantes adaptaciones, pero ya podes verlo aca:

http://www.parexklaukol.com.ar/cgi-bin/ganadorestorneo.pl?usuario=XXXXX&clave=XXXXXX

ponele un usuario y clave que sepas, NO "XXXXXX", pongo asi para evitar lo de google.

En el CMS esta dentro de Torneos->Ganadores.
Para que figure como "Grandes Premios Semestrales" ponele trimestre 3 (los normales poneles 1 y 2).
Le puse que puedas elegir el corralon (previa seleccion de categoria), pero en realidad no se esta usando para nada, lo que toma es el texto que le escribas.

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Gracias!

Pongo un usuario y contraseña pero aún así no encuentra la página. Me lleva al login, puede ser?

**Comment by mkreyness** [comment]
yo uso esto y anda:
usuario=gilli-faudin&clave=127839

sacale donde dice XXXXXX, estoy poniendo asi para que no indexe Google

**Comment by LeandroBraier** [comment]
@mkreyness Lo se, pero yo puse otros nombres de usuarios y no funcionó. 
Probá con usuario=norbertocastello&clave=parexklaukol

@braulio-evangelisti ahora que lo veo te paso pequeño feedback del diseño: 

1) Porfa reemplazá el texto GANADORES DEL TORNEO DE POTENCIADOS por TODOS LOS GANADORES

2) Centrá ese texto.

abrazo

**Comment by mkreyness** [comment]
Estas usando un corredor y no un corralon. Creo que no anda con corredores, ahora lo agrego.
Ojo Braulio que el template esta recontratocado de lo que vos tenes, usa siempre lo que esta en el servidor por favor. Ese texto lo cambie yo porque decia "ganadores de la comunidad"

**Comment by braulio-evangelisti** [comment]
Si lo acabo de bajar al template recien para modificarlo :+1:

**Comment by mkreyness** [comment]
ya anda con corredores, @LeandroBraier

**Comment by braulio-evangelisti** [comment]
Listo los cambios del título

**Comment by LeandroBraier** [comment]
Ahora si perfecto!! Gracias a los dos!!

Les aviso cualquier cosa pero quedó resuelto.

abrazo

**Comment by mkreyness** [comment]
avisame cuando mandar los mails.

**Comment by LeandroBraier** [comment]
Dale MK. Yo te aviso, despreocupate.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@braulio-evangelisti estoy viendo que el título de la página de Ganadores del Torneo de Potenciados sigue diciendo Comunidad de Vendedores. El titulo debería ser "Ganadores Torneo de Potenciados".

Porfa lo modificás?

**Comment by mkreyness** [comment]
no estaras mirando algo viejo ? El actual dice "TODOS LOS GANADORES".

**Comment by LeandroBraier** [comment]
Me refiero al titulo de la página HTML, en la barra de arriba. Paso captura:

<img width="239" alt="captura de pantalla 2016-01-06 a las 5 38 27 p m" src="https://cloud.githubusercontent.com/assets/6719872/12153664/d815bc3e-b499-11e5-9ae2-13e1a4419036.png">

**Comment by mkreyness** [comment]
Pero el titulo de la pagina no es ese actualmente.
Es "Ganadores Torneo de Potenciados". Probaste dar F5 ?

**Comment by LeandroBraier** [comment]
Ahora si. Me confirmó Brau que lo corrigió. Gracias a los dos!!

abrazo
