### ISSUE TITLE
Bug en Trivia Comunidad de Vendedores. PARA 07/01

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#242]
@mkreyness fijate a ver si desentrañás qué pasa acá:

1) La foto se ve gigante, siendo que la subí en el mismo tamaño que en las últimas trivias.

2) El primer recuadrito (que generalmente dice video y ahora no lo dice) no debería aparecer porque no hay video para visualizar:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=30&usuario=LeanBraier&clave=parex

Esto se publica mañana, así que puede ser para mañana a la mañana sin problemas.

abrazo

**Comment by mkreyness** [comment]
A la mañana no estoy asi que tengo que hacerlo esta noche si o si. 
El problema es el TIPO de juego que le definis, el tipo que tiene ahora asume que lo que va ahi es un video, no una foto. Los tipos que llevan foto, no tienen trivia. Tengo que armarte un template que sea un mix de las dos cosas.

**Comment by mkreyness** [comment]
listo
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=30&usuario=LeanBraier&clave=parex
Le saque lo que habias cargado en video, ahora si no hay un juego video, no aparece el icono, y lo que toma es siempre la imagen.
El problema es que se pegotea la parte de documentacion. Si te parece que hay que arreglarlo habria que pedirle a @FAAREIA que toque el template juegosinvideoT.html

**Comment by LeandroBraier** [comment]
Muchas gracias @mkreyness ! Quedó perfecto ahora.

Tal cual, se pega la parte de documentación. @FAAREIA si podés dejarlo arreglado dentro de la mañana a eso ya estamos bien.

abrazo

**Comment by FAAREIA** [comment]
HECHO

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!
