### ISSUE TITLE
Ajustes en la Web ParexKlaukol. 04/02

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#243]
@FAAREIA para tu regreso de vacaciones te paso este pedido de revisión del sitio de Parex para ver qué podemos perfeccionar. La fuente es un informe enviado por Duplika. La mayoría está muy muy bien, pero estos son los puntos flojos y quiizá los podemos perfeccionar.

<img width="1037" alt="captura de pantalla 2016-01-11 a las 10 26 58 a m" src="https://cloud.githubusercontent.com/assets/6719872/12234424/b07be0a8-b84b-11e5-971f-03d6c037658d.png">
<img width="1035" alt="captura de pantalla 2016-01-11 a las 10 27 35 a m" src="https://cloud.githubusercontent.com/assets/6719872/12234425/b1b05986-b84b-11e5-9ccd-c645405ba3ce.png">
<img width="1050" alt="captura de pantalla 2016-01-11 a las 10 27 40 a m" src="https://cloud.githubusercontent.com/assets/6719872/12234429/b53c57ee-b84b-11e5-9ae5-fa6d6d8bb19a.png">
<img width="1046" alt="captura de pantalla 2016-01-11 a las 10 27 59 a m" src="https://cloud.githubusercontent.com/assets/6719872/12234430/b77a3012-b84b-11e5-8974-a8596e51447e.png">

abrazo

**Comment by FAAREIA** [comment]
Buen dia Lea, cómo andan? Ahi estuve hablando con Brau y me actualizó el estado de todo.
Con respecto a este issue, por ahora esta resuelto:
- Resolver www
- Robots.txt

Lo de "Resolver www" es que `http://parexklaukol.com.ar` redirige a `http://www.parexklaukol.com.ar`
En el robots.txt puse que el unico directorio a no inspeccionar es `/cgi-bin/`

Aclaro también que el código para la redirección de lo de www es:

```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{HTTP_HOST} .
  RewriteCond %{HTTP_HOST} !^www\. [NC]
  RewriteRule ^ http%{ENV:protossl}://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
 </IfModule>
```

Copio a @mkreyness para asi chequea estos 2 temas.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA !! Welcome back!! Espero que hayas tenido unas excelentes vacaciones!!

Por suerte con @braulio-evangelisti estuvimos laburando de 10 y nos ayudó muchísimo a cubrirte. Tengamos en cuenta que recupere horas estas semanas próximas ya que creo que estuvo laburando horas de más durantes tus vacas.

Excelente esto que mandás. Espero confirmación de @mkreyness para cerrar el ticket.

**Comment by mkreyness** [comment]
Si, esta todo bien.

**Comment by LeandroBraier** [comment]
Gracias a los dos!!

**Comment by FAAREIA** [comment]
Lo reabro que quedaron algunos puntos pendientes que van a llevar un tiempo

**Comment by LeandroBraier** [comment]
Ah, ok, no problem. Avisen nomás!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA 
1. Estoy viendo que el pop up del Equipo Klaukol obstruye totalmente la versión mobile del Sitio de Parex. Lo mismo ocurre en Revear.

Como podemos evitar eso?
1. Los títulos con los nombres de los productos en sus propias páginas se ven demasiado grandes en la versión mobile con respecto a la tipografía del resto del texto. Podremos emparejar un poco eso? Si querés incluilo dentro del rediseño de la parte de productos que estamos esperando que nos apruebe el cliente.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, lo de los banners del home ya esta solucionado.
Con respecto al tamaño de los títulos en la página de cada producto, queres que lo vaya retocando ahora mismo o esperamos al rediseño?

**Comment by LeandroBraier** [comment]
Gracias Fede! SI se puede ahora mejor.

Abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!! Excelente quedó.

abrazo
