### ISSUE TITLE
Extracto de Actividades Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#244]
Buen día @mkreyness ! Tenés la posibilidad de enviarme un excel con el extracto de actividad del Club de Colocadores? O no queda registrada?

**Comment by mkreyness** [comment]
Ahi agregue la opcion "Actividad de Colocadores" en el CMS, lo podes sacar de ahi.

**Comment by LeandroBraier** [comment]
Gracias MK!! Mil gracias!!

Ya que estás podrás agregar la otra que tenemos en vendedores? La que es Actividad + Datos del Vendedor de cada actividad, etc? Sino no hay problema.

**Comment by mkreyness** [comment]
Ahora ya no tengo como, hasta las 4 de la tarde que nos vemos voy a estar completamente desconectado.

**Comment by LeandroBraier** [comment]
Ok, no problem. Muchisimas gracias igual!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-12 9:29 GMT-03:00 mkreyness notifications@github.com:
