### ISSUE TITLE
Actualizar Hojas de Seguridad de la mayoría de los productos. 21/01

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#245]
@braulio-evangelisti necesitaría actualizar estas hojas de seguridad de la mayoría de los productos en el sitio de ParexKlaukol para mañana. 

[Hoja de Seguridad 01-2016.zip](https://github.com/LeandroBraier/Klaukol/files/97547/Hoja.de.Seguridad.01-2016.zip)

Confirmame porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Dale lea esta tarde los cambio

**Comment by LeandroBraier** [comment]
Genial! Gracias.

**Comment by braulio-evangelisti** [comment]
Lea este a cual de los productos pertenece?

**Hoja de seguridad Mestik.pdf**

Esta dentro de la carpeta Parex pero no encontre el producto con ese nombre

**Comment by LeandroBraier** [comment]
Es de Klaukol, pero va con Z, por eso no lo encontrabas.

Te paso el link:

http://parexklaukol.com.ar/klaukol/mortero-multiproposito-klaukol-meztik.html

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-20 17:34 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Gracias. 
Bueno creo que ahi estan todos actualizados. Si podes en algun momento pegale una revisada porque es la primera vez que hago este trabajo y estaban como divididos en dos carpetas diferentes las hojas de seguridad.

**Comment by LeandroBraier** [comment]
Las veo bien en principio. Les acortaste los nombres a los PDF puede ser?

El que se llamaba Hoja de Seguridad Klaukol Impermeable-Potenciado.pdf
ahora se llama HS-Klaukol-Impermeable Potenciado.pdf

Vos lo modificaste o estoy viendo aún los archivos viejos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-20 17:50 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Los cambie yo, les puse el mismo nombre de los que estaban online para reemplazar los que estaban y que los links tomen ese archivo directamente
Para que queden con los nombres tal cual me los pasaste tendria que, en algun lado como un campo en el gestor donde podes modificar todos los datos de cada producto, poder modificar los nombres de los pdf a mano para que los actualice en la base de datos y los links en el template

**Comment by LeandroBraier** [comment]
No, esta perfecto lo que hiciste, Brau. Solo chequeaba. Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti un detalle: actualizaste esto también para Paraguay y Uruguay?

Porfa confirmame. 

Además, te pido que actualices la ficha técnica y hoja de seguridad del producto Lanko 453. Aquí te las paso. Confirmame cuando esté todo porfa

[Ficha Técnica LANKO 753_POTENCIADOR.pdf](https://github.com/LeandroBraier/Klaukol/files/99725/Ficha.Tecnica.LANKO.753_POTENCIADOR.pdf)
[Hoja de seguridad LANKO 753 potenciador.pdf](https://github.com/LeandroBraier/Klaukol/files/99726/Hoja.de.seguridad.LANKO.753.potenciador.pdf)

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea. 
Ahora actualizo estos dos.

Solamente Argentina habia actualizado, subo los mismos para los otros dos paises?

**Comment by LeandroBraier** [comment]
Buen dia Brau. Si, todas estas actualizaciones son para todos los países.
Gracias

**Comment by braulio-evangelisti** [comment]
Perfecto, ya subi estas dos ultimas en ARG, apenas haya reemplazado en los otros dos paises te aviso.

**Comment by LeandroBraier** [comment]
Brau, avisame porfa cuando quede hecho esto.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea

Me llevo tiempo porque tuve que ir rastreando en cada producto de cada marca por país como se llama el pdf en cada caso porque tienen diferentes nombres en cada uno. Por gestor no hay manera de modificar estos archivos?

**Comment by LeandroBraier** [comment]
Hasta ahora no. Fede me pidió que le pidiera eso a MK en cuanto tuviera un
hueco pero pobre MK no tiene un hueco hace mucho. Calculo que es la última
vez que lo tenés que hacer, no te preocupes y muchas gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-22 20:03 GMT-03:00 Braulio Evangelisti notifications@github.com:
