### ISSUE TITLE
Averiguar Browser que corra HTML5 en Raspi

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#246]
O hay que cambiar a Mini android PC?

**Comment by LeandroBraier** [comment]
Averiguar cuanto sale un Mini Android PC aca y en Chile.

**Comment by mkreyness** [comment]
perdon que me meta, pero los browsers que corren en Raspi SON todos HTML5, pero no sirven para correr video, porque no aprovechan la GPU. Diego ya hizo toda esta investigacion.

**Comment by LeandroBraier** [comment]
jajaja Mirá que lo estuvimos probando recién con La Casa Interactiva y el
video embebido en la home de ParexKlaukol y de Benteveo y se ven bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-01-20 17:24 GMT-03:00 mkreyness notifications@github.com:
