### ISSUE TITLE
Chequear monitores para terminales

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#248]

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath Cómo quedó esto al final? Pudiste encontrarle la vuelta?

**Comment by ghost** [comment]
Lean! Me llevé el monitor a mi casa con la raspi y le encontré la vuelta.
Asi que mañana vuelvo a la ofi  y los testeo a todos

2016-01-28 8:44 GMT-03:00 LeandroBraier notifications@github.com:

> Buen día @valentinsabbath https://github.com/valentinsabbath Cómo quedó
> esto al final? Pudiste encontrarle la vuelta?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/Klaukol/issues/248#issuecomment-176139251
> .

## 

_Atte. Valentín Gavela._

**Comment by LeandroBraier** [comment]
Buenisimo Valen. Gracias! Qué bueno que lo resolviste!
