### ISSUE TITLE
Bug en Ganadores de Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#249]
@mkreyness fijate, no aparece la imagen del thumbnail ni la imagen grande del ganador de diciembre Qué puede ser?

http://www.parexklaukol.com.ar/cgi-bin/ganadores.pl?usuario=leanbraier&clave=parex

abrazo

**Comment by mkreyness** [comment]
ya anda github.
Arreglado.
