### ISSUE TITLE
Nuevo Newsletter Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#25]
Fede, para mañana necesitaría armar un newsletter con toda la misma estética del Micrositio KIP y bien sencillo. Estéticamente prolijo pero sencillo y que tenga el siguiente texto:

Subject: ParexGroup presenta: Nuevo Klaukol Impermeable Potenciado

Body: ParexGroup relanza su producto emblema de la marca Klaukol.  Klaukol impermeable se reformula y se renombra a KLAUKOL IMPERMEABLE POTENCIADO. 
Esta nueva formulación fue desarrollada por quienes más saben de adhesivos y pastinas en Argentina, con la última tecnología en adhesivos.  Ahora tiene mayor tiempo abierto, mayor adhesión y mayor trabajabilidad.
Klaukol entiende que cuando ponés todo para la realización de una obra, solo esperas lo mejor, y bajo este concepto desarrollo Klaukol Impermeable Potenciado. Un producto hecho para durar; sólido y confiable;  La nueva formulación otorga una mezcla cremosa, elástica, y homogénea. Gracias a sus retenedores de agua que aseguran el nivel justo de humedad, podes reacomodar y facilitar el trabajo, logrando excelencia en la colocación 
Una nueva fórmula, con aditivos de máxima tecnología que garantizan una perfecta adhesión. 
Es un producto que otorga créditos en las normas leed para apoyar construcción sustentable. 

Este re - lanzamiento, se apoya y  es impulsado desde una campaña 360° bajo el claim “POTENCIA QUE UNE”, el cual resume muy bien los valores de la marca. Así como Klaukol une los cerámicos,  también une y potencia las relaciones, experiencias, trabajos y la pasión por lo que se hace y se hace bien.

SIEMPRE POTENCIANDO LA UNIÓN EN LAS RELACIONES, CONOCIMIENTOS Y EXPERIENCIAS.

KLAUKOL, POTENCIA QUE UNE.

Adjunto al mail iría la ficha técnica del producto, que te la subí a la carpeta BENTEVEO MAQUETADOR/KLAUKOL/Newsletter KIP

Confirmame para qué hora de mañana lo podríamos tener.

abrazo

**Comment by FAAREIA** [comment]
Desconozco si el archivo adjunto puede enviarse con el mail, capas que algunos te lo rebotan. Lo mejor es poner un link externo. Consultale a marce por las dudas, ya me pongo con eso

**Comment by LeandroBraier** [comment]
Vamos directo con link externo. Subilo al hosting nuevo nomas.

**Comment by FAAREIA** [comment]
Si esta ok el diseño lo paso todo a imagen y lo mandamos. Si no lo pasamos todo a imagen y es todo HTML, habría que invertir mucho más tiempo en hacerlo y quedaría distinto a lo que te pasé ya que los fondos y las tipografías serían distintos.

Avisame!

![sin-titulo-1](https://cloud.githubusercontent.com/assets/6184969/7298101/b6315496-e9a3-11e4-9602-5863c9d28fb0.jpg)

**Comment by LeandroBraier** [comment]
Buenisimo Fede!

Lo mando a aprobar ya.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 10:31 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, a mi me gustó, pero el cliente pidió lo siguiente: necesita un formato de newsletter más institucional y que se pueda repetir con el mismo formato para futuras novedades que surjan. Este es el formato actual:

![formato newsletter actual](https://cloud.githubusercontent.com/assets/6719872/7303805/76893554-e9c9-11e4-8984-40f2b0144561.gif)

Estéticamente tendríamos que adaptarlo a la estética actual de los sitios 1.0, pero no más allá de eso. En el encabezado debe tener el logo de Parexgroup y en el pie los logos de todas las marcas klaukol Parex, Lanko y Revear) 

En el news n°1 vamos a comunicar el lanzamiento. En este primer news tendremos la suerte de tener todo el espacio para la noticia del lanzamiento, pero en los próximos ya no. 

Si tenés una nueva versión del diseño para mañana a la mañana estamos bien. No te mates mucho, emulá esta refe pero con el restyling nuevo y las imágenes del producto que usaste en la primera versión que me mandaste hoy.

abrazo

**Comment by FAAREIA** [comment]
Pero este sería un segundo newsletter?
Osea, el de hoy es un newsletter promocional y este que envias ahora es más para contar novedades.
Al de hoy le podemos poner el encabezado y footer, pero también hay que armar uno que tenga novedades adentro no?

**Comment by LeandroBraier** [comment]
Exacto. Yo también creo que el newsletter estaba excelente para lanzamiento
pero el cliente es tozudo. Le doy un Van Gogh y me pide un Nik de oficina.

Al Newsletter de hoy habría que agregarle el encabezado y pie pero también
la estructura que uses para el contenido adentro tendría que servir después
para novedades también.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 16:04 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, entonces preparo el encabezado y pie que vamos a incrustar en este que te mandé hoy pero también preparo un news de noticias con ese mismo encabezado y pie. Porque al que te mandé hoy lo veo inadaptable al formato que ellos enviaron que es de noticias

**Comment by LeandroBraier** [comment]
Dale, hagamos ambas y le mando las dos. Si está para mañana todo bien igual.

abrazo y gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 16:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://72.52.188.248/_mailing/ultima-tecnologia/novedades.html
http://72.52.188.248/_mailing/ultima-tecnologia/ultima-tecnologia.html

Fijate ahi Lea, si esta Ok corto bien la imagen de última tec y los separo por carpetas a los newsletters

**Comment by LeandroBraier** [comment]
Están muy bien los dos Fede!

Dejame que se los mando al cliente y los hago aprobar antes de avanzar.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día Fede!

El cliente nos pasó feedback nuevo del newsletter. Quieren algo recontra básico. Está muy bien detallado en este documento:

https://drive.google.com/file/d/0B_6ywYX9PGKLeG5xOVIxV19xdWNyQjVvMG03T3dpYUZ2SFFJ/view?usp=sharing

Lo más urgente es el Newsletter de Lanzamiento de Producto. Ese mandaselo a Eze el lunes a la tarde, cuando esté listo el tema Sitios 1.0, como segunda prioridad.

Lo segundo, la maqueta para futuros newsletters de novedades, mandaselo a Eze el martes o miércoles. Cuando llegues.

abrazo
