### ISSUE TITLE
Mailing de Bienvenida Genérico Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#250]
@braulio-evangelisti necesito una adaptación de este mailing sin la imagen de arriba:

http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-jul.html

Este mailing quedaría como mailing de bienvenida genérico para nuevos inscriptos hasta tanto no tengamos un premio definido. Cuando lo tengas listo le avisás a @mkreyness ?

Abrazo

**Comment by braulio-evangelisti** [comment]
algo así Lea?

http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

**Comment by LeandroBraier** [comment]
Está perfecto Brau!

@mkreyness apenas tengas un hueco hacé el envío de mails porfa.

abrazo

**Comment by mkreyness** [comment]
ahora te mando uno de prueba y si esta ok arranco con todos

**Comment by mkreyness** [comment]
Recibiste ? Largo ?

**Comment by LeandroBraier** [comment]
Si, largalo nomás @mkreyness  Lo veo OK. 

@braulio-evangelisti acordate cuando vuelva @FAAREIA  tenemos que revisar estos mailings para hacerlos lo más amigables posibles al mobile. Me parece que no está muy lejos hoy, pero se puede mejorar.

abrazo

**Comment by mkreyness** [comment]
saliendo
