### ISSUE TITLE
Despublicar Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#251]
@braulio-evangelisti y @mkreyness necesitaría que lo antes posible den de baja el sitio del Torneo de Potenciados. Me avisan cuando está?

**Comment by braulio-evangelisti** [comment]
Ahi le saque el link del footer en http://parexklaukol.com.ar, la verdad nose si se puede acceder desde otro lugar dentro del sitio general porque los agrego Fede a los links cuando se sumó lo del torneo, si te acordás donde hay otro link (si es que hay) avisame y lo saco también.

Lo de la baja general de la sección a lo mejor se podría renombrar el directorio, o armar una redirección por si se vuelve a necesitar en el futuro?

**Comment by LeandroBraier** [comment]
Claro, tendrían que redireccionar la URL del Torneo de Potenciados a la web principal de ParexKlaukol.

**Comment by mkreyness** [comment]
Yo hasta las 4 no me conecto, el acceso siempre fue por los mails, tendría que hacer que si entran por ahí los redireccione a la home de Klaukol?

Enviado desde mi iPhone

**Comment by mkreyness** [comment]
Listo.

**Comment by LeandroBraier** [comment]
En realidad necesitaria que el dominio en general redireccione
directamente. /torneo-de-potenciados/

A su vez todas las demas urls, claro.

**Comment by mkreyness** [comment]
listo /torneo-de-potenciados/

No creo que haya mas URLs que estas, el acceso siempre fue por torneo-con-slide.pl que ya lleva a la home, y del ultimo mailng ganadorestorneo.pl, que tambien hice ahora que redireccione a la home.

**Comment by LeandroBraier** [comment]
Gracias a los dos!!
