### ISSUE TITLE
Base de subscriptos a newsletter a través de la web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#252]
@mkreyness donde puedo ver esto?

**Comment by mkreyness** [comment]
CMS
   Novedades -> Suscripciones

**Comment by LeandroBraier** [comment]
Perfecto, gracias!

Consulta: Me suscribí y no me llegó Mail de confirmación. Puede ser?

**Comment by LeandroBraier** [comment]
Todos en la lista aparecen como pendientes

**Comment by mkreyness** [comment]
Ni me acuerdo como era, pero seguro que no podemos mandar nada masiva mente, mas hoy que hay que sacar ese otro mailing. Te encontraste en la lista?

**Comment by mkreyness** [comment]
Cual es el mail de confirmación? Capaz nunca me llego un html para eso y quedo eternamente postergado

**Comment by LeandroBraier** [comment]
Este es el mail:

http://parexklaukol.com.ar/_mailing/confirmacion_newsletter/confirmacion.html

Me acuerdo de haberlo testeado con vos.

**Comment by LeandroBraier** [comment]
@mkreyness ahora que anda de vuelta podemos enviar los mails de confirmación o chequear qué pasó con esto?

Deberían enviarse automáticos los mails de confirmación apenas alguien se suscribe, no?

**Comment by mkreyness** [comment]
No se mandan en el momento que el tipo da "Enviar", entran en una bolsa (la que ves en el CMS) y hay un programa preparado como para mandar cada tanto pero nunca lo pusimos a andar automatico el envio, seguramente porque no podria coexistir con los envios masivos que hacemos manualmente (no habria forma de coordinarlos).
Puedo poner a mandar lo acumulado, que es muchisimo, mientras no tengamos otra cosa para mandar, pero con los cortes de la base de datos y esas cosas lo mas probable es que requiera mucho control manual.
No seria mejor mandarlas desde mailchimp directamente ?

**Comment by LeandroBraier** [comment]
Si, claro. Cómo hacemos? Me tendrías que armar el template y yo lo mando,
no hay drama.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-01 17:53 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
hay que hacer 2 cosas: el template y la base de datos con el email y link de confirmacion.
Esta noche te armo todo y te aviso.
Igual el pegado de la base es totalmente manual.
Capaz sacado el grueso que es esto podamos poner una cuota diaria de mandar ponele 50 por noche automatico.

**Comment by LeandroBraier** [comment]
Claro, no te preocupes que Maichimp permite programar los envíos. Es re
fácil.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-01 18:09 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Eso Ok para el monstruo pendiente, pero digo para los que vayan entrando nuevos, no te vas a poner a exportar a mano todos los dias

**Comment by LeandroBraier** [comment]
Pero en esos casos sí conviene que sea automático. No es tanta la cantidad
de suscriptos por día la verdad. De última cuando enviemos mails de parex
lo frenamos, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-01 18:45 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Exacto, a eso me referia

Enviado desde mi iPhone

**Comment by mkreyness** [comment]
No pude hacer nada esta noche, llegue a casa retarde de una reunion y encima me tuve que poner a transcribir todo lo hablado. A la mañana te armo lo de MailChimp.

**Comment by mkreyness** [comment]
Uh, se me vencio el acceso. Ahi le pedi a Ezequiel que me pase un authenticator

**Comment by mkreyness** [comment]
che ahi arme todo pero estoy viendo que los suscriptos hasta ahora son 80 nada mas, los podria mandar perfectamente desde el servidor de Klaukol y listo.

**Comment by LeandroBraier** [comment]
Jaja buenisimo. Adelante nomas. De ultima queda armado para un futuro igual
no te preocupes. Gracias!

**Comment by mkreyness** [comment]
ok, ahi lo largue y despues cuando termine lo dejo automatico.

**Comment by LeandroBraier** [comment]
Gracias Marce!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
