### ISSUE TITLE
Adueñarnos del Dominio parexgroup.com.ar

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#253]
@mkreyness y @FAAREIA tengo una consulta: tengo a la persona dueña del dominio y quiero que esa página deje de existir y el dominio redirecciona a nuestra web: www.parexklaukol.com.ar

Me darían los DNS con los instrucciones de lo que tiene que hacer esta persona en Nic.Ar para hacerlo?

**Comment by mkreyness** [comment]
Para que ese dominio apunte al servidor de Duplika tenes que decirle que ponga los nameservers de duplika: ns1.duplika.com y ns2.duplika.com
Y tenemos nosotros que agregarlo en el panel de control de duplika para que apunte a la home parexklaukol.com.ar
Pero eso no te hace dueño del dominio, el dueño del dominio es el que figure registrado en nic.ar

**Comment by LeandroBraier** [comment]
Entiendo eso MK. Era una forma de decir.

Entonces no necesito los IP de ambas direcciones. Según las las instrucciones que da NIC.AR para esto sería así:

**En nuestro sistema, la Delegación es muy sencilla:
Ingresá a la sección "Mis dominios" desde tu Panel de Control. Seleccioná el/los dominio/s tildando el casillero de cada uno y hacé clic en la opción "Delegar". A partir de ahí, podés cargar nuevos DNS o modificar los actuales. 
Tené en cuenta que:

Si contrataste un servicio de hosting y querés subir tu página, ya no tenés que indicar las IP como antes; podés delegar el dominio directamente ingresando los DNS que te indique tu host.
Ejemplo:
ns1.dominodetuhosting.com
Para guiarte en el proceso, podés visitar nuestro tutorial de Delegación.**

@FAAREIA voss podrás ya agregar eso en el Panel de Control de Duplika así ganamos tiempo?

**Comment by mkreyness** [comment]
Los IPs solo son necesarios para cosas como mandar el MX (registro del mail) a otro servidor, porque es algo que se carga en el DNS, pero nunca para delegar el dominio directamente desde el NIC.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !!

Dejo para la próxima link a los instructivos de NIC

https://nic.ar/preguntas-frecuentes.xhtml#

https://www.youtube.com/watch?feature=player_embedded&v=RWs_BbHJg7E

abrazo

**Comment by FAAREIA** [comment]
En el issue no dice que se necesita hacer. ¿Qué dominio hay que delegar a donde?

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Te faltó leer el título del issue y mi primer thread:

*_Adueñarnos del Dominio parexgroup.com.ar *_

@mkreyness y @FAAREIA tengo una consulta: tengo a la persona dueña del dominio y quiero que esa página deje de existir y el dominio redireccione a nuestra web: www.parexklaukol.com.ar

**Comment by FAAREIA** [comment]
Pero hay algo que no entiendo, la persona que tiene parexklaukol es la misma que parexgroup, cuando el haga el cambio de DNS o nos pase los datos para hacerlo, que nos avise y al toque agregamos el dominio nuevo al panel de control del hosting asi se acepta la redirección

**Comment by LeandroBraier** [comment]
CLaro, eso estoy esperando. Pero antes de eso no se puede ir haciendo?

**Comment by FAAREIA** [comment]
Ahi ya le puse para que funcione la redirección. Habría que probarlo cuando ya se haga terminado la delegación

**Comment by LeandroBraier** [comment]
Excelente. Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-05 10:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA el cliente ya hizo el cambio. Hay algo más para hacer o solo nos queda esperar que la delegación se realice sola?

A parte de esto el cliente tiene en su poder el dominio www.clubdecolocadores.com.ar

Me pasarías los DNS que tendría que poner para que redirija a parexklaukol.com.ar/colocadores/ ?

abrazo

**Comment by FAAREIA** [comment]
Exacto, solo hay que esperar un máximo de 48hs para que finalice la delegación. A mi en telecentro ya me funciona bien.
Los DNS para colocadores son los mismos que antes. Ya agregué ese dominio para que cuando se finalice la delegación, que aún falta hacer, redireccione a la url actual de colocadores.

Abrazooo

**Comment by LeandroBraier** [comment]
Perfecto Fede. Entonces le pido que delegue a esos DNS también.

abrazo
