### ISSUE TITLE
Equipo Klaukol linkeado en la web de ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#255]
@FAAREIA necesito para mañana subir el logo del Equipo Klaukol de esta manera:

![mock-up-sitio-web](https://cloud.githubusercontent.com/assets/6719872/12858832/2adfae1c-cc31-11e5-9865-52cdf4727173.png)

Linkeando a esta playlist:

https://www.youtube.com/playlist?list=PLlOciJKjCRsb2khN-hcH6lDJxMbDx8CmL

Me confirmás si llegamos?

El logo es este:

![logo-equipo-klaukol](https://cloud.githubusercontent.com/assets/6719872/12858853/4704e422-cc31-11e5-8c37-37a21f305c76.png)

También te voy a pasar un POP UP diseñado para subir la semana que viene a la web.

**Comment by LeandroBraier** [comment]
@FAAREIA te paso acá lo que iría la imagen que iría en el pop up y llevaría al mismo link del logo de Equipo Klaukol.

![posteo-equipo-klaukol-lanzamiento-1](https://cloud.githubusercontent.com/assets/6719872/12863499/924f4cb4-cc55-11e5-97de-80c81b6a2829.png)

Si necesitás achicalo a 600x600.

abrazo y buen finde!

**Comment by FAAREIA** [comment]
Todo hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!  Quedó todo muy bien, pero fijate no sé por qué la X del pop up no cierra.

Uno puede salir haciendo clic fuera del mismo, pero igual molesta. Se podrá arreglar eso?

abrazo

**Comment by FAAREIA** [comment]
Hecho, era un bug de webkit

**Comment by LeandroBraier** [comment]
Buenisimo, muchas gracias!
