### ISSUE TITLE
Fotos Privadas que Facebook levanta de Comunidad de Vendedores y Club Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#256]
@FAAREIA lo antes posible fijate por favor que Facebook está levantando las fotos privadas como preview en redes.

<img width="447" alt="captura de pantalla 2016-02-05 a las 9 12 24 p m" src="https://cloud.githubusercontent.com/assets/6719872/12862463/a2db80ee-cc4a-11e5-80b1-63fc7147a588.png">

Sabés cómo modificar eso? las fotos privadas son privadas digamos, no puede verse ahi.

**Comment by FAAREIA** [comment]
Ahi esta solucionado.
@mkreyness 
https://developers.facebook.com/tools/debug/og/object/
En esa url pongan http://www.parexklaukol.com.ar/colocadores/ y vean que tira unos errores, alguna idea? A pesar de eso, la data sale bien ahora.

**Comment by mkreyness** [comment]
El index de colocadores es un redirect a maincolo.pl y a Facebook no le gusta, tiene que ser asi porque el contenido de la main es dinamico. Si fuera a un login estatico, no les molestaria, pero es menos atractivo para enganchar gente.

**Comment by mkreyness** [comment]
Y probablemente no pueda ejecutarlo porque prohibiste cgi-bin en robots.txt ?

**Comment by mkreyness** [comment]
y como dije alguna otra vez, en los metatags no hay que usar utf-8, eso no solo rompe cualquier intento de usar el sharer.php (cuando esta como titulo), sino que se ve horrible en los textos.
Hay que encodear las letras acentuadas, enies y signos de puntuacion no-ascii (abre pregunta, abre exclamacion) en html entities.

**Comment by FAAREIA** [comment]
No creo que sea lo del robots.txt, ese archivo lo respeta el que quiere.
Lo del UTF habría que verlo, hay que definir un charset si o si creo. Todos los otros sitios estan también con lo de UTF-8

**Comment by mkreyness** [comment]
Lo de UTF-8 yo tuve que irlo corrigiendo en los templates de las paginas que tuvieran botones de share, si no se rompia el URL directamente y daba error facebook.

**Comment by FAAREIA** [comment]
Ahi le saqué el UTF-8 y sigue tirando esos caracteres fallados. Raro

**Comment by mkreyness** [comment]
hay que esperara a que Facebook haga un refresh de los datos que tiene cacheados, o forzarlo desde el tool.

**Comment by LeandroBraier** [comment]
Ya está resuelto ese tema en Colocadores! Gracias!

Solo fijense que lo de UTF8 sigue estando raro con los tildes:

<img width="497" alt="captura de pantalla 2016-02-11 a las 7 15 01 p m" src="https://cloud.githubusercontent.com/assets/6719872/12992120/59916394-d0f1-11e5-9eef-8732b041d9e5.png">

En Vendedores aún no lo veo resuelto.

**Comment by mkreyness** [comment]
la scraped information sigue NO levantando de ahi el texto.
Vean lo que muestra esto:

https://developers.facebook.com/tools/debug/og/echo?q=http%3A%2F%2Fwww.parexklaukol.com.ar%2Fcolocadores%2F

Debe estar sin cambiar en algun otro lado de donde lo esta levantando.

**Comment by LeandroBraier** [comment]
Estoy viendo que nos pasa en todos los sitios esto. Los únicos que muestra una imagenes correctas ahora son Club de Colocadores y el Micrositio de Klaukol Impermeable Potenciado. 

El resto muestra imágenes al azar:

http://www.parexklaukol.com.ar/
http://www.parexklaukol.com.ar/guia-corralones/
http://www.parexklaukol.com.ar/vendedores/
http://www.revear.com.ar

**Comment by mkreyness** [comment]
el sitio de revear muestra basura abajo:

`/\=\s*([^'"\]]*)\s*\]/g`

**Comment by FAAREIA** [comment]
Bueno para resumir:
- El sitio de KIP tiene UTF-8 y facebook lo levanta bien. De hecho hay tildes sin pasarlas a un `&acute;` y se ven bien.
- El sitio de colocadores no tiene UTF-8 y facebook muestra en el código que lee que el sitio tiene UTF-8 (lo debe defaultear) y también lo muestra actualizado el html. Sin embargo el post generado no lo muestra actualizado. Por ejemplo ahora le agregué una "a" inicial al "Bienvenido..." y el post lo muestra sin "a" pero el html que dice que lee facebook lo muestra bien: "aBienvenido".
- El código basura que muestra revear en el fondo debe ser de algun script, en el HTML del index no está escrito.

**Comment by LeandroBraier** [comment]
Ok, @FAAREIA avisenme si necesitan algo de mi para esto, pero trabajemos para resolverlo. 

El que menos prioridad tiene es Revear porque igual lo vamos a hacer de vuelta en el corto plazo, pero recuerden esta cuestión para ya armar desde cero el sitio de Revear de esta manera porfa.

**Comment by FAAREIA** [comment]
Ya estan puestos y probados los Open Graph en:

http://www.parexklaukol.com.ar/
http://www.parexklaukol.com.ar/guia-corralones/
http://www.parexklaukol.com.ar/vendedores/
http://www.revear.com.ar
- Hay dos errores compartido en la url de colocadores y vendedores. "Circular Redirect Path" + "Could Not Follow Redirect"
- Al archivo "mainT.html" de Colocadores le cambié el encóding a UTF-8 y también cree un archivo nuevo y le pegué todo el código pero siguen apareciendo mal los caracteres con tilde. Voy a seguir investigando.

**Comment by LeandroBraier** [comment]
Gracias chicos!!!

Avisenme cuando resuelvan estos dos errores pero ya veo excelente todo en Facebook.

abrazo

**Comment by FAAREIA** [comment]
Solucionado el tema tildes en Colocadores.
Lo de los errores creo que son inevitables y no influyen en nada del post generado por FB, por lo que los pasaría por alto, excepto que @mkreyness diga lo contrario.

Abrazo

**Comment by mkreyness** [comment]
Esos errores son inherentes al hecho de que no son paginas estaticas, no creo que haya solucion.

**Comment by LeandroBraier** [comment]
Perfecto entonces. Ya está terminado! Gracias chicos!!
