### ISSUE TITLE
Mailing Lanzamiento Equipo Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#257]
Buen día @FAAREIA y @braulio-evangelisti ! Le envío a Braulio por WeTransfer un PSD editable para con el keyvisual para que lo adapten a un mailing.

Si logran hacerlo, estaría buenísimo agregar en alguna parte un GIF animado, tomado de los videos publicados:

https://www.youtube.com/watch?v=ZOyJSqcidRo&list=PLlOciJKjCRsb2khN-hcH6lDJxMbDx8CmL&index=2

Fijense como hacerlo, si necesitan ayuda con el GIF animado me avisan. 

Fede: te lo paso a vos para que coordines pero Brau venía manejando muy bien este tipo de maquetaciones.

abrazo

**Comment by LeandroBraier** [comment]
Les paso el link a WeTransfer por las dudas:

https://www.wetransfer.com/downloads/2c9755d7c9503dcedeef7d62911c865320160210124643/0709ae

**Comment by braulio-evangelisti** [comment]
Perfecto. A mi me llego por mail, ya casi esta terminando de descargarse.

**Comment by LeandroBraier** [comment]
Buenisimo Brau! Me avisás para qué hora podríamos tener el mailing listo?

**Comment by braulio-evangelisti** [comment]
Lea me esta pidiendo 5 fuentes. Me las pasas?

**Comment by LeandroBraier** [comment]
Si, no problem. Aquí van:

[exo_2.zip](https://github.com/LeandroBraier/Klaukol/files/125019/exo_2.zip)

[fingbanger.zip](https://github.com/LeandroBraier/Klaukol/files/125017/fingbanger.zip)

[frutiger-lt-std.zip](https://github.com/LeandroBraier/Klaukol/files/125012/frutiger-lt-std.zip)

Decime si falta alguna.

abrazo

**Comment by braulio-evangelisti** [comment]
http://www.parexklaukol.com.ar/_mailing/equipo/equipo.html

Lea el tema de los gif capas se pueden poner en los dos thumbs. 
Necesitaria los videos originales, o que me pasen los frames en buena calidad ya que el gif comprime bastante las imagenes y van a quedar mejor si partimos de los originales que de los videos de youtube.

**Comment by LeandroBraier** [comment]
Está buena la idea, pero por un tema de tiempos vamos a salir sin GIFs por ahora. El problema que tengo con esta versión son las fuentes.

1) Necesito que pongas los textos como imagen y con texto en "alt" porque el cliente se va a quejar de que no es la tipografía que elegimos.

2) Necesito que el cartel de "Mirá los episodios" diga "Mirá los episodios en" y que la url sea "parexklaukol.com.ar/EquipoKlaukol". Este cartel debe estar más grande y al centro del news, debajo del titular "Dos especialistas"

3) El Play de YouTube que está en esa línea debería ser el GIF animado. Por ejemplo, podría estar titilando o haciendo un leve scale in y out sutil, algo que tenga movimiento y quede lindo para llamar la atención. Con eso estaría. 

abrazo

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Cómo venís con esto? lo necesito lo antes posible.

abrazo

**Comment by braulio-evangelisti** [comment]
ya casi lo tengo, me falta el gif nomas que lo estoy probando pero queda muy trabado.

otra cosa es que al pasar el texto de "mira los episodios" mas arriba, el footer queda solamente con el bloque de fondo blanco a la derecha y vacio a la izquierda. Que otros datos puedo poner en ese lugar?

**Comment by braulio-evangelisti** [comment]
Fijate ahi la esquina inferior izquierda:

http://www.parexklaukol.com.ar/_mailing/equipo/equipo-2.html

Lo del gif quedaba medio raro.

**Comment by LeandroBraier** [comment]
Está muy bien Brau. Lástima lo del GIF no funcionó. Abajo en el footer reemplazá la parte repetida de la izquierda por el mismo footer de los newsletters habituales:

<img width="643" alt="captura de pantalla 2016-02-11 a las 10 04 38 a m" src="https://cloud.githubusercontent.com/assets/6719872/12976620/451a4c34-d0a4-11e5-85f0-4e19cfcd8a08.png">

Con eso estamos.

abrazo

**Comment by braulio-evangelisti** [comment]
Hecho!

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! Lo envio al cliente para aprobar.

**Comment by LeandroBraier** [comment]
@braulio-evangelisti el cliente respondió. Le gustó, pero dice que en mobile no se ven las fotos chicas ni el texto. Entonces:

1) Agrandá los textos rojo y azul a un tamaño de fuente igual a la frase "Mira sus episodios en"

2) Agrandá las 2 fotos lo más posible.

3) Achicá el footer lo más posible. Dice que el corner de ParexGroup lo ve enorme y no tienen necesidad de que sea tan grande. Achicalo nomás.

Con eso ya lo armo para enviar, asi que lo necesitaría lo más temprano posible.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahora Lea, fue lo maximo que me dio para agrandar fotos y texto

http://www.parexklaukol.com.ar/_mailing/equipo/equipo-2.html

**Comment by LeandroBraier** [comment]
Lo veo mejor Brau pero me parece que esta muy chico para mobile. Tendriamos
que aumentar de tamaño todo ese texto por lo menos 2 puntos desde Mira sus
episodios...hasta maxima potencia en adhesivos.
Gracias

**Comment by braulio-evangelisti** [comment]
Fijate ahora

**Comment by LeandroBraier** [comment]
Las fotos y textos estan bien pero:
1. El "Mira sus episodios..." sigue chiquito
2. La url dice EquipoKlukol

Con eso ajustado estamos.

**Comment by braulio-evangelisti** [comment]
jajaja se me escapo en la image

fijate ahora

**Comment by LeandroBraier** [comment]
Ahora si perfecto! Gracias Brau!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti urgente! Ya lo mandé al cliente y me acabo de dar cuenta de que el link no funciona. Me parece que es por las mayúsculas. Tiene que ser todo en minúsculas. Porfa corregilo lo antes posible.

abrazo

**Comment by braulio-evangelisti** [comment]
Si eran las mayusculas. Ya lo corregí

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti !

abrazo

**Comment by LeandroBraier** [comment]
El mailing sigue vivo @braulio-evangelisti !! El cliente volvió a responder y quiere más. 

Quiere lo siguiente:

Parte Superior) La imagen donde se presenta al equipo, e invitarlos a que vean sus episodios (tal como esta pero que clickeando en cualquier parte del mailing lo lleve al link).
Parte inferior) Luego de eso, una imagen en grande de cada uno los videos. 
Que la gente cliquee en cualquiera  para verlos.. que no necesite leer, que ya viendo la imagen le genere intriga. Las imágenes de los episodios serían 4 en cuadrícula ocupando todo el espacio que ahora ocupan las dos fotos y las frases. A la izquierda estarían las dos que están ahora pero más grandes. A la derecha dos fotos nuevas pero recortadas con ese mismo formato. Serían estas dos:

![foto-equipo-klaukol-boca-river](https://cloud.githubusercontent.com/assets/6719872/13017976/0c936f0a-d1a6-11e5-9935-94991bd6bdd1.png)

<img width="1680" alt="captura de pantalla 2016-02-10 a las 9 19 08 a m" src="https://cloud.githubusercontent.com/assets/6719872/13017980/0f8aa7b4-d1a6-11e5-81a7-211661c07d9c.png">

Parte abajo de la inferior) Habría una frase de cierre en rojo: "Ellos llevan los productos Klaukol al límite demostrando su máxima potencia."

Footer

Decime si lo podemos tener corregido para hoy así lo aprueban y lo mando el lunes a primera hora.

abrazo

**Comment by braulio-evangelisti** [comment]
No voy a llegar para hoy Lean, en un toque ya me estoy yendo a cursar.

**Comment by LeandroBraier** [comment]
Ok, no hay problema. Confirmame porfa si llegás para mañana, así la llegan a ver y dar feedback antes del lunes a la mañana que hay que enviarlo.

abrazo

**Comment by LeandroBraier** [comment]
Recordá que todas las imágenes lleven al mismo link.

**Comment by braulio-evangelisti** [comment]
si mañana no hay problema, abrazo

**Comment by braulio-evangelisti** [comment]
http://www.parexklaukol.com.ar/_mailing/equipo/equipo-3.html

**Comment by LeandroBraier** [comment]
Gracias Brau!!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen dia Brau! Ahora me piden subir la frase roja de abajo para que quede
arriba de las 4 fotitos. Ya que estamos achica esa fuente a 25px. Porfa
avisame apenas lo tengas.
Abrazo

**Comment by braulio-evangelisti** [comment]
Hecho!

**Comment by LeandroBraier** [comment]
Gracias Brau! Lo mando una vez más. Espero que esta vez quede final!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@braulio-evangelisti recién te mandé un test mail de como sale de mailchimp.

El diseño está aprobado, pero fijate que (si bien en mailchimp se ve bien) en mi mail se ven de distinto tamaño las fotos:

<img width="504" alt="captura de pantalla 2016-02-15 a las 3 53 23 p m" src="https://cloud.githubusercontent.com/assets/6719872/13057236/89a34718-d3f9-11e5-9da7-82e2795e1955.png">

Te fijás qué puede ser así lo arreglamos y ya lo mandamos?

abrazo

**Comment by braulio-evangelisti** [comment]
A mi me llego tambien la prueba y lo veo bien en Gmail en Chrome. Me estoy fijando por las dudas, mientras proba de actualizar el navegador con ctrl+F5 o Shift+5

**Comment by LeandroBraier** [comment]
sisi hice refresh. Supongo que tiene que ver con el cache. Probá cambiarle el nombre a esas 2 imagenes en el server y en el mailing. QUizá con eso ya está.

**Comment by braulio-evangelisti** [comment]
Ahi le cambie los 4 nombres por las dudas

http://www.parexklaukol.com.ar/_mailing/equipo/equipo-3.html

**Comment by LeandroBraier** [comment]
Ahora si. Perfecto, gracias!
