### ISSUE TITLE
/EquipoKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#258]
@FAAREIA podrás poner que la url:

www.parexklaukol.com.ar/equipoklaukol

redirija a esta URL:

https://www.youtube.com/watch?v=JdbcpV8ALMY&index=1&list=PLlOciJKjCRsb2khN-hcH6lDJxMbDx8CmL

Avisame para qué hora podrías estar hecho.

Gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA porfa esto con prioridad lo antes posible.

**Comment by FAAREIA** [comment]
Hecho, la declaración en el .htaccess fue:

> Redirect /equipoklaukol https://www.youtube.com/watch?v=JdbcpV8ALMY&index=1&list=PLlOciJKjCRsb2khN-hcH6lDJxMbDx8CmL

**Comment by LeandroBraier** [comment]
Gracias!!!
