### ISSUE TITLE
Bug en Video Comunidad de Vendedores. PARA HOY

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#259]
@mkreyness necesito subir un video a la Comunidad de Vendedores solo para que sea compartido. Este tipo de "tema" está ya habilitado en el Club de Colocadores, donde lo pude subir sin problemas, pero no en la Comunidad de Vendedores. Te paso el link del ejemplo:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34&usuario=LeandroBraier&clave=parexklaukol

Avisame porfa cuando ya está habilitado y OK. Lo necesito publicar hoy si o si.

abrazo

**Comment by mkreyness** [comment]
Pasame un link de ejemplo en el de COLOCADORES asi veo como lo habia implementado.

**Comment by LeandroBraier** [comment]
Aquí va!

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?usuario=marcelokreyness&clave=pepe&id=13

abrazo

**Comment by mkreyness** [comment]
Pero no es lo mismo, el que me pasaste de colocadores no tiene share, es un video pelado.
Tiene que ser un tema que tenga un juego de tipo share cargado.

**Comment by LeandroBraier** [comment]
AH, entonces no. Porque colocadores no tiene puesto eso (que debería
tenerlo ya que estamos jeje)

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Justamente ese template para SOLO VIDEO sin nada es lo que se elige cuando no hay NINGUN juego asociado al tema. Si le pones el juego va a tratar de poner una foto y no un video.
Resolvamos eso despues. 
Entonces lo que hace falta es algo que ME parece que no hay armado en ningun lado, video + share.

**Comment by LeandroBraier** [comment]
Exacto. Si obvio. La prioridad es Vendedores. Colocadores está bien así sin
apuro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-11 15:06 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ok, te aviso en un rato.

**Comment by mkreyness** [comment]
listo, fijate

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?usuario=leandrobraier&clave=parexklaukol&id=34

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!

A partir de ahora ya sale solo este template o yo le tengo que seleccionar
el template en el cms?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Toda vez que pongas un tema en Vendedores que solo tenga un juego de tipo "Compartir", te va a tomar este template.
Lo ideal en realidad seria que hubiera otro para cuando solo es foto.

**Comment by LeandroBraier** [comment]
De acuerdo MK. Cuando puedas anotate para hacerlo. Lo mismo en el Club de Colcoadores, asi no te jodo de apuro más adelante.

Gracias @mkreyness !

**Comment by mkreyness** [comment]
En el de colocadores de alguna manera ya esta funcionando esa parte con fotos, lo que pasa es que no cuando es video (no vi si tienen el juego share, pero en la pagina NO aparece el boton de share).
