### ISSUE TITLE
Estimado de horas invertidas en Maquetación para backup y sitios web 1.0 Klaukol hasta ahora

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#26]
Fede, necesito que me pases este cálculo sin incluir Micrositio KIP, Comunidad de Vendedores y Colocadores y Corralones.

abrazo

**Comment by FAAREIA** [comment]
Dejame hacer algunos cálculos, es dificil calcularlo cuando siempre se entrecruzan cosas para hacer. Desde ya te digo igual que hablamos de al menos 1 centena de horas.

**Comment by LeandroBraier** [comment]
Guau. Me sirve el dato, gracias.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 10:34 GMT-03:00 Federico Arena notifications@github.com:
