### ISSUE TITLE
Rediseñar Formulario de Inscripción de MailChimp

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#260]
@FAAREIA necesito que armen un diseño de este formulario en función de la estética del sitio web ParexKlaukol:

http://parexklaukol.us11.list-manage.com/subscribe?u=455b0cd079a287d15e307c9b7&id=eb5b99989b

Averigué y esto se puede hacer totalmente customizado e incluso con CSS a través del API de Mailchimp:

<img width="743" alt="captura de pantalla 2016-02-11 a las 8 34 51 p m" src="https://cloud.githubusercontent.com/assets/6719872/12994004/50f3dfea-d0fc-11e5-8091-58695555029c.png">

http://developer.mailchimp.com/documentation/mailchimp/guides/manage-subscribers-with-the-mailchimp-api/?_ga=1.111396224.542997374.1445447031

http://kb.mailchimp.com/es/lists/signup-forms/css-hooks-for-customizing-forms

@mkreyness cuando puedas lo guiás a Fede con esto?

**Comment by LeandroBraier** [comment]
Esto también debería incluir rediseñar este mailing en caso de ser necesario. Yo lo veo bastnate bien pero quizá se puede perfeccionar:

http://www.parexklaukol.com.ar/_mailing/sumarme/

**Comment by FAAREIA** [comment]
@braulio-evangelisti

**Comment by braulio-evangelisti** [comment]
Este form es un embed form? De ser asi, si me pasan el codigo puedo empezar a trabajar directamente desde la maqueta y ver hasta donde se puede ir modificando.

**Comment by LeandroBraier** [comment]
Chicos hablenlo con MK. El sabe como subir un html a mailchimp.
Brau ahora dale prioridad al mailing de equipo klaukol.
Abrazo

**Comment by mkreyness** [comment]
Ojo que esto no es el HTML de los templates con que yo trabaje.
El API propiamente dicho nunca lo usamos, lo que hicimos fue crear una lista de emails con campos custom.
Estos forms deben ser al reves, para GENERAR listas, pero siempre dentro de mailchimp, eso es lo que necesitan ? Porque un form con otro tipo de usos Mailchimp no lo va a permitir.

El modo "advanced" no es tan advanced como con los templates, no se puede copiar y pegar HTML. Lo que se puede es customizar el CSS de los campos que ellos ya tienen (o agregar campos custom, pero el control general de DONDE va el form lo tienen ellos, por eso no dejan poner un HTML custom.
Yo diria Leandro generar un form standard de los de ellos y sobre eso customizar el CSS, mas no se puede.

**Comment by LeandroBraier** [comment]
Ok, si me parece bien la propuesta MK.

Lo que quiere el cliente es que formulario tenga un diseño más atractivo (más en la línea de los mailings mismos) y que se entienda claro qué hay que hacer. Actualmente mucha gente no entiende qué es y lo cierra.

Para eso, lo que les pido es:

1) Que el título del formulario diga: "¿TODAVIA NO TE SUSCRIBISTE A NUESTRO NEWSLETTER?" y abajo diga: "Es muy simple. Hacelo completando tus datos aquí"

2) El botón de submit que sea rojo más grande y que esté en castellano diciendo: suscribirme

3) El diseño sea más atractivo y en la línea del sitio web.

abrazo

**Comment by mkreyness** [comment]
Pero tienen acceso para verlo en Mailchimp ?

**Comment by LeandroBraier** [comment]
No, por eso decía que coordinen con vos. Igual vayan armando el diseño primero, porque ahora está a full Eze y en Chile como para pedirle el Google Authenticator. Avancemos con el diseño bajo las limitaciones que tenemos. Esto es para el lunes, no es urgente, no se preocupen.

**Comment by braulio-evangelisti** [comment]
Lea hay alguna foto de las que armaron para klaukol que tenga que ver con novedades o algo por el estilo?

**Comment by LeandroBraier** [comment]
Buen xia Brau! Decis para este formulario? Busco y te digo.

Abrazo

**Comment by braulio-evangelisti** [comment]
Si queria probar de usar una imagen de fondo para la parte del encabezado hasta antes que empiezan los campos a completar pero todas la fotos buenas son de colocadores y ese estilo y no tienen nada que ver con novedades, newsletter, etc

**Comment by braulio-evangelisti** [comment]
Lea probé dos alternativas con cambios sutiles ya que no estoy seguro hasta donde te deja modificar el diseño si solo te da algunos id's para pisar la hoja de estilos que ya carga por defecto, uno con foto (tendria que ser una foto mas relacionada al tema puse una de colocadores de ejemplo) y el otro es casi igual pero le saque todas las esquinas redondeadas y lo lleve más para el lado de la página de contacto, dentro del sitio de klaukol.

![test](https://cloud.githubusercontent.com/assets/11272253/13049672/53f9fdea-d3cd-11e5-8321-3ce35839a97d.jpg)

**Comment by LeandroBraier** [comment]
Está mejor Brau, pero te pido lo siguiente:

HEADER

Logo de ParexGroup bien chico arriba al centro.

"¿TODAVÍA NO TE SUSCRIBISTE A NUESTRO NEWSLETTER? " en rojo y bien grande.
Tipografía de "Es muy simple. Hacelo completando tus datos aquí" más grande.
Agregar alguna imagen que refiera a Newsletter mejor. Lo que no se entiende es para que se está suscribiendo la gente. Lo que tiene que entender es que se suscribe a recibir novedades de productos de la marca bien mail.

No se puede embeber el video de la home de la web de ParexKLaukol no?

**Comment by braulio-evangelisti** [comment]
Claro por eso te preguntaba si habia alguna foto de parex referida a novedades o newsletter. No hay no? busco alguna genérica para probar.

Respecto a la ultima pregunta, creo que todo depende de como hayan armado el form este, por lo que vi en mailchimp _(cuenta propia que arme para investigar)_ una de las maneras es "**EMBED FORM**", que segun entendí uno podria copiar el codigo de un formulario base y armar una landing de registro pero hosteada en tu sitio web _(parex en este caso)_ y no dentro de mailchimp. De esa manera entiendo que el diseño no tendria ningun limite y se le podria poner cualquier cosa:

![image](https://cloud.githubusercontent.com/assets/11272253/13056832/b3006ca6-d3f6-11e5-904a-6d9aea82c460.png)

![image](https://cloud.githubusercontent.com/assets/11272253/13056857/dc5d0b04-d3f6-11e5-8dec-470a8306d497.png)

Si estuvieron usando ese form para ir cargando los inscriptos hasta ahora _(creo que es un general form no?)_  nose si se podria cambiar a un embed form y que siga funcionando igual.

**Comment by mkreyness** [comment]
yo entiendo que la gracia es que todo este dentro de mailchimp porque asi se mandan los newsletter desde ahi, y si alguien no quiere seguir estando, se de de baja desde ahi, etc.
No tener que pasar por el server de parexklaukol. Lo correcto inclusive seria que el form actual (que no es un form, solo un campo para ingresar email) para suscribirse se cargara en la base de mailchimp y no tener que hacer nada (actualmente le estamos mandando un mail de confirmacion nosotros, y contra ese mail lo activamos en una base que despues Leandro tiene que exportar de ahi y reimportar en Mailchimp). Hasta donde yo entiendo la intencion es unificar todo... en MailChimp, que se dedican precisamente a este tipo de cosas.

**Comment by LeandroBraier** [comment]
Me parece bien lo de unificar la base de newsletters con esto también.

Brau: No hay problema con el tema de la lista. Podemos crear una lista
nueva y armar un nuevo formulario de registro desde 0 en esa nueva lista si
es necesario, aunque creo que se puede reemplazar un formulario por otro en
la lista ya existente también.

Avancemos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-15 15:29 GMT-03:00 mkreyness notifications@github.com:

**Comment by braulio-evangelisti** [comment]
![test-2](https://cloud.githubusercontent.com/assets/11272253/13059369/67db29fc-d408-11e5-8367-3552b4e3adb5.jpg)

**Comment by LeandroBraier** [comment]
Está bueno el de la derecha. El de la foto no la veo, porque no se ve linda pero tampoco cumple el manual de marca.

Como segunda opción hacé algo con esta estética:

<img width="344" alt="captura de pantalla 2016-02-15 a las 6 27 24 p m" src="https://cloud.githubusercontent.com/assets/6719872/13060297/201c670a-d40f-11e5-9c77-2e790878adf1.png">

Un paralelogramo rojo y el texto blanco adentro + iconito que refiera a newsletter.

abrazo

**Comment by braulio-evangelisti** [comment]
![test-3](https://cloud.githubusercontent.com/assets/11272253/13074810/ab8bbcde-d485-11e5-8e1e-c547b5a1e10d.jpg)

**Comment by LeandroBraier** [comment]
Gracias! Está mejor @braulio-evangelisti 

Solo fijate que la forma que usaste no es exactamente que la misma que en la web. El extremo izquierdo del paralelogramo rojo debe ser recto. Y hagamos dos versiones, una solo con ese cambio y otra en la cual:
1. El botón rojo de abajo tenga la misma forma
2. Aparezcan los 4 logos de las marcas en gris arriba de todo a la derecha del logo de ParexGroup.

abrazo

**Comment by braulio-evangelisti** [comment]
![test-4](https://cloud.githubusercontent.com/assets/11272253/13077327/e7eab02a-d496-11e5-8135-378381fb0df2.jpg)

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! La verdad no me termina de convencer pero no sé cómo decirte de mejorarlo. Siempre en uno de los dos mantené el otro ícono de news que me parece mejor.

Más allá de ese detalle, lo verías con @FAAREIA a ver si se le ocurre alguna otra idea para que quede mejor y en la línea estética de la web principal?

Perdón por las vueltas pero no lo veo bien todavía.

abrazo

**Comment by FAAREIA** [comment]
Algo asi?
Ojo que el form habría que tocarlo y desconozco que tanto se puede. Es probable que el icono del botón azul no se puede incluir.
![news](https://cloud.githubusercontent.com/assets/6184969/13111299/c776e020-d563-11e5-8fef-406347a0047d.png)

**Comment by LeandroBraier** [comment]
Este lo veo mejor. Solo acomodá el logo de ParexGroup y los de las marcas como estaban arriba, el ParexGroup a la izquierda y los demás a la derecha, como en la web.

Si me confirman que se puede hacer así el form lo hago aprobar con el cliente. Si el botón no se puede hacer azul hagamoslo rojo como antes está bien también.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA porfa espero que acomodes eso y me confirme si se puede hacer en MailChimp. COnsultalo con @mkreyness  por las dudas pero yo había entendido por lo que dijeron más arriba que:

"creo que todo depende de como hayan armado el form este, por lo que vi en mailchimp (cuenta propia que arme para investigar) una de las maneras es "EMBED FORM", que segun entendí uno podria copiar el codigo de un formulario base y armar una landing de registro pero hosteada en tu sitio web (parex en este caso) y no dentro de mailchimp. De esa manera entiendo que el diseño no tendria ningun limite y se le podria poner cualquier cosa"

En ese sentido este diseño es posible, solo que la base se guardaría en nuestro server y no en mailchimp verdad? Y luego habría que importarla manualmente. Me confirman porfa? Necesito enviarlo hoy a esto.

**Comment by braulio-evangelisti** [comment]
Armando un embed form, lo unico que estaria en el server de parex es el html con el form, pero ese formulario que te da MailChimp para que lo estilices esta apuntado a mailchimp (el action="") por lo que entiendo cargaría ese usuario en una lista de correo(db de MC, no de Parex), y ya gestionarias todo lo que concierne a newsletter desde mailchimp . No lo probé nunca a esto, es lo que entendí leyendo la documentacion del sitio nomas.

**Comment by LeandroBraier** [comment]
Perfecto @braulio-evangelisti , entiendo. De cualquiera de las dos formas entonces estamos OK para diseñarlo así. Solo faltaría que acomodes el logo de ParexGroup y los de las marcas como estaban arriba, el ParexGroup a la izquierda y los demás a la derecha, como en la web. Pasame lo antes que puedas esa versión así te la mando a aprobar porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
En teoria si. Nose si marcelo tiene algún dato mas de si es asi como funciona.

El diseño no lo tengo yo.

**Comment by FAAREIA** [comment]
Ahi va, ahora voy a darle un vistaso a la doc a ver si no es tan complejo hacer algo asi.

![news](https://cloud.githubusercontent.com/assets/6184969/13147925/c19f6272-d639-11e5-8708-e7479a412606.png)

**Comment by LeandroBraier** [comment]
Perfecto, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
yo lo que digo es que la gran ventaja de que la base resida en mailchimp es que no hay que andar importando manualmente nada (ni dando de baja manualmente nada, es todo autogestion del suscripto).
Ahora, si esa misma base se va a usar para otra cosa, ya no se.

**Comment by FAAREIA** [comment]
Aca hay un artículo interesante sobre personalizar un form. Lo dejo aca asi Brau y yo ya lo tenemos a mano
http://uhurunetwork.com/customizing-mailchimp-form-design/

**Comment by FAAREIA** [comment]
Pregunta:
- ¿Donde puedo encontrar eso de los custom forms?
- ¿hay algun otro usuario con otros permisos en mailchimp?

**Comment by LeandroBraier** [comment]
Veanlo con @braulio-evangelisti porfa. Este es el único usuario que tenemos.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya pude encontrarlo ^^

**Comment by FAAREIA** [comment]
Ya encontré el lugar en donde mailchimp te deja editar todo el código HTML del formulario, eso implica que no habría impedimento en cualquier estilización que se haga.

**Comment by FAAREIA** [comment]
Lea, el mailing ya se puede ir maquetando?

**Comment by LeandroBraier** [comment]
Hola Fede! No me dieron el OK aun pero si querés avanzá. A lo sumo va a haber alguna corrección minima de estética.

Si preferís esperar esperamos.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Me dieron feedback. De maquetación son detalles nomás, fijate qué pueden hacer. 

<img width="658" alt="captura de pantalla 2016-02-24 a las 10 26 41 a m" src="https://cloud.githubusercontent.com/assets/6719872/13286212/7af33890-dade-11e5-9c2b-82e0232a7e35.png">

Son dos puntos: header y footer.

Respecto del footer, yo les dije esto:

> En cuanto al footer, nos habían dicho que quedaba desterrada esa estética del manual de marca viejo. Vos decís de volver a usarla? No creo que quede bien, porque no tiene nada que ver con el estilo actual de la página. Te agregamos algo si querés, sutil, y el copyright y año así queda más completo el footer.

Por algo me refiero a algún detalle de diseño del estilo de la web en el footer, junto con el ©2016 ParexKlaukol S.A. No utilizar esa estética de curvas vieja.

abrazo

**Comment by FAAREIA** [comment]
Voy a maquetar esto Lea, si esta aprobado buenisimo, sino después lo ajustamos sobre la marcha.
![news](https://cloud.githubusercontent.com/assets/6184969/13288105/3cefe092-dae9-11e5-95ec-dd25d888ae42.png)

**Comment by LeandroBraier** [comment]
Perfecto. Adelante!!

Solo poneme © 2016 ParexKlaukol

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi estuve haciendo e investigando un poco.
La realidad es que mailchimp me elimina los campos del formulario en la prueba que estoy haciendo, lo cual me parece raro porque [según lei](https://www.campaignmonitor.com/dev-resources/will-it-work/forms/) si se pueden mandar formularios en mailings aunque algunos clientes de correo no los aceptan o renderizan por completo.

El template de prueba se llama "Prueba Fede".
El form que usé esta en "Lists" y se llama "Prueba de Fede". A ese form le agarré el código html y lo estilicé para meterlo en el template.

Lo que podemos hacer es que el template se mande sin formulario con un link para suscribirte online o sino mandarlo a mano a pesar de que algunos clientes de correo no lo vayan a tomar (ver artículo).

Qué dicen?

**Comment by LeandroBraier** [comment]
Me parece que hubo una confusión. El formulario es online, no es un mailing
en sí. El mailing en sí es otro, es este:

http://www.parexklaukol.com.ar/_mailing/sumarme/

Se los pasé al principio de este ticket.

2016-02-24 15:15 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok perfecto, entonces el form de suscripción queda en mailing como enlace externo nomás.

**Comment by LeandroBraier** [comment]
Exacto Fede! Entonces ya está lista y funcional? Me confirmas porfa?

**Comment by FAAREIA** [comment]
http://parexklaukol.us11.list-manage.com/subscribe?u=455b0cd079a287d15e307c9b7&id=d9d8502655
Ahi ya esta maquetado el formualrio de suscripción online hecho en mailchimp.
Lo que faltaría es que @mkreyness meta mano y haga funcionar las variables. El email, nombre y apellido vinieron de base, pero los checkbox los puse en base a otro formulario por lo que seguro tengas que tocar algo ahi en los name y/o id.

**Comment by FAAREIA** [comment]
Para llegar ahi vayan a:
Lists >  Suscripción ParexGroup >  Suscripción ParexGroup > General forms > Signup form

**Comment by LeandroBraier** [comment]
@FAAREIA pequeño cambio en el footer. El cliente me pide aplicar la estética vieja en el footer, la de las curvas que ves acá. Incluyamoslo.

<img width="749" alt="captura de pantalla 2016-02-26 a las 10 36 39 a m" src="https://cloud.githubusercontent.com/assets/6719872/13353311/321aefd8-dc72-11e5-9495-4b20b2c21518.png">

Yo no estoy de acuerdo, porque no concuerda con la estética actual pero es un pedido enfático de ellas.

abrazo

**Comment by FAAREIA** [comment]
Hecho

http://parexklaukol.us11.list-manage.com/subscribe?u=455b0cd079a287d15e307c9b7&id=d9d8502655

**Comment by LeandroBraier** [comment]
Está perfecto Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
