### ISSUE TITLE
Pequeños Ajustes en Plataformas de Vendedores y Colocadores. 22-02

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#261]
@FAAREIA y @braulio-evangelisti  son pequeños detalles:

*_1) COMUNIDAD DE VENDEDORES
*_
En las bases y condiciones, 

. ~~En la sección ORGANIZADOR cambiar "el promoción" por "la promoción"~~

. ~~En la sección de VIGENCIA cambiar "31 de diciembre de 2015" por "31 de diciembre de 2016"~~

. ~~En la sección EXCLUSIONES se repite el párrafo de la sección LOS PARTICIPANTES. Borrarlo.~~

. Quitar este texto dentro de la sección PREMIO MENSUAL POR SORTEO:

"En el mes de julio entregaremos 1 (una) consola PlayStation® 4 de la empresa Sony® con las especificaciones detalladas en la siguiente dirección web oficial de la marca: https://www.playstation.com/en-us/explore/ps4/techspecs/"

y reemplazar por este:

"Cada mes se anunciará un nuevo premio dentro de la cartelera de la plataforma. El mismo podrá constar de uno o varios ganadores según lo disponga el ORGANIZADOR."

. ~~En la sección RETIRO DE PREMIOS corregir la palabra "Identidad" dentro de "Documento Nacional de Indentidad"~~

*_2) CLUB DE COLOCADORES
*_
En las bases y condiciones:

. ~~En la sección de VIGENCIA cambiar "31 de diciembre de 2015" por "31 de diciembre de 2016"~~

. ~~En la sección de MECÁNICA DE PARTICIPACIÓN reemplazar el párrafo siguiente:~~
~~"Por cada actividad realizada en la plataforma, los PARTICIPANTES sumarán puntos que podrán canjear por herramientas y accesorios de primera calidad del Kit Klaukol y además participarán con 1 ticket cada uno en eventuales sorteos por importantes premios.~~
~~Cada uno de los PRODUCTOS PARTICIPANTES sumará 100 puntos por cada compra del mismo cargada en el sistema.~~
~~Las compras de producto se computarán de la siguiente manera: se considerarán los pedidos cargados desde el 01/08/2015 hasta el 14/12/2015 inclusive, que no estén retenidos por Créditos y no se hayan dejado de entregar por cuestiones de fuerza mayor. Estas compras deberán ser validadas por parte del PARTICIPANTE mediante el envío de los cupones adheridos a cada pack del PRODUCTO PARTICIPANTE a la dirección postal del ORGANIZADOR."~~

por este:

"~~Los PARTICIPANTES participarán con 1 ticket cada uno en eventuales sorteos por importantes premios.~~"

. ~~En la sección PREMIOS quitar la subsección de PREMIOS POR CANJE~~

. ~~En la sección RETIRO DE PREMIOS reemplazar el siguiente párrafo:~~

"~~Cada Participante ganador deberá acreditar su identidad y sus compras mediante la entrega o envío de los cupones de las compras realizadas y completar y suscribir el recibo correspondiente."~~

por este:

"~~Cada Participante ganador deberá acreditar su identidad y su condición de colocador al momento de retirar sus premios.~~"

Solo eso. Gracias!

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ya esta actualizado. La parte que no taché, la de:

"Quitar la sección VENDEDORES entera. Sumar en su lugar este texto como parte de la sección anterior PREMIO MENSUAL POR SORTEO"

No la entendí porque no hay sección VENDEDORES

Abrazoo

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Perdón, mala mia, ahi te lo redacté bien. Es reemplazar un párrafo por otro.

abrazo

**Comment by FAAREIA** [comment]
Job done

**Comment by LeandroBraier** [comment]
Gracias Fede!!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
