### ISSUE TITLE
Bug en Calculador de Adhesivos Actual

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#262]
@mkreyness no me está funcionando NINGUN link en el calculador que está online.

http://www.parexklaukol.com.ar/aplicaciones/calculador.html

Me aparecen los links sin el ".html" final. Me parece que tiene que ver con una intervención que vos hacías sobre el flash no?

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness estoy probando y ahora me andan casi todos. Solo me queda sin andar este link:

http://www.parexklaukol.com.ar/klaukol/klaukol-pla-k-pasta

Parece que no le está apariendo el .html al final. Si se lo agrego anda bien.

**Comment by mkreyness** [comment]
yo lo tenia como /klaukol/klaukol-placa-pasta
Ahi le puse como pla-k

**Comment by LeandroBraier** [comment]
Ahora si! Perfecto.

gracias MK!
