### ISSUE TITLE
Link a Bases y Condiciones Torneo de Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#263]
@FAAREIA el sitio del Torneo sigue subido online no? Si bien no está linkeado en la url de siempre sigue estando no?

Lo que necesito es el link a bases y condiciones del torneo. 

abrazo

**Comment by FAAREIA** [comment]
Esta despublicado según veo:
http://www.parexklaukol.com.ar/torneo-con-slide.pl

Queres que te pase el HTML o el texto de esas bases y condiciones?

**Comment by LeandroBraier** [comment]
Dale, con el texto estamos más que bien. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-22 11:51 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi te subo un zip porque hay 8 variables de bases y condiciones y desconozco cual requeris. Abrite el html en el navegador y no vas a tener problema en ver el texto.

[bases-condiciones.zip](https://github.com/LeandroBraier/Klaukol/files/140785/bases-condiciones.zip)

Cualquier cosa decime
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!! Si, son varias versiones. Ahi lo veo 

Esta es la última versión verdad?

abrazo grande

**Comment by FAAREIA** [comment]
Si, es lo que baje del FTP

**Comment by FAAREIA** [comment]
Vuelvo a enviarlo, bajado del FTP
[bases.zip](https://github.com/LeandroBraier/Klaukol/files/166165/bases.zip)

**Comment by LeandroBraier** [comment]
Gracias fede!
