### ISSUE TITLE
Bug URGENTE en Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#265]
@mkreyness mirá como se ven las imagenes que subo para posteos a compartir:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=36

usuario=LeandroBraier
clave=parexklaukol

Lo corregís porfa? Creo que es parecido a lo que nos pasó hace unos días.

**Comment by mkreyness** [comment]
Esta usando un template de video. Cual asi de compartir FOTO anda bien ? Asi comparo el tipo de juego puesto.

**Comment by LeandroBraier** [comment]
Todos los que antes se veían bien ahora se ven mal.

Por ejemplo:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=18

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=24

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=25

Suena a Duplika o algún cambio en algún template.

**Comment by mkreyness** [comment]
mas bien a un cambio en el programa que no tuvo en cuenta esto.
Hicimos un cambio hace poco (11 feb) para incluir esto de poder compartir un video me parece.
Debe haber sido para algun juego reciente, lo que habria que verificar es que despues de arreglar esto, el otro juego siga bien, te acordas cual era ?

**Comment by mkreyness** [comment]
Listo, ya puse que si lo que cargas en "URL Video" termina en png o jpg  use el template de fotos.
La verdad que en estos casos la imagen no tendria que estar en ese campo, sino en el de imagen.
Pero bueno, ya estaban todos los otros cargados asi, con lo que lo emparche para que ande.

**Comment by LeandroBraier** [comment]
Gracias MK!! Ya revisé los que tenían template de video y se siguen viendo bien.

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=35

abrazo grande y gracias otra vez
