### ISSUE TITLE
Consulta Canje en Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#266]
@FAAREIA nos quedó algún html online donde podamos ver el sistema de canjes que tenía el Club y ocultamos?

**Comment by FAAREIA** [comment]
¿Vos decis esto?

Comprá
Por cada compra de uno de nuestros productos acumulás puntos.

Canjeá
Con los puntos que acumules podés realizar canjes por distintas herramientas y accesorios del Kit Klaukol.

Ganá
Por participar del Club de Colocadores contás con un número en nuestros sorteos.

¿o decis esto?
http://www.parexklaukol.com.ar/colocadores-temp/usuario-compras.html

**Comment by LeandroBraier** [comment]
Esto exactamente. Gracias!!!
