### ISSUE TITLE
Nuevo Newsletter ParexKlaukol (nuevos contenidos y más mobile) 30/3

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#267]
Buen día @FAAREIA !

Te paso pedido de un mock up para un nuevo estilo de newsletter de ParexKlaukol. La idea es que sea más pro y más apuntado a arquitectos, tené en cuenta esto. Tiene que ser más fino el diseño y con mucha imagen.

La primer imagen debe ser un gif animado, aunque sea de 3 frames nomas que hacen loop, como el mailing de Comunidad VIE TUR.

Manteniendo los logos y demás del año pasado, queremos un nuevo diseño. Los contenidos van a ser diferentes:

TENDENCIAS EN ARQUITECTURA
Notas de tendencias (para el mock up podés agarrar notas de tendencias de nuestro facebook http://www.facebook.com/ParexKlaukolArg )

INNOVACIONES EN CONSTRUCCION
Notas sobre productos y máquinas nuevas (para el mock up podés agarrar algo de www.rubi.com)

ENCUESTA DEL MES
Un mini form con tres opciones para que los usuarios voten y accedan a los resultados de la encuesta en la página. (estaría genial que esté en una columna a la derecha de las notas principales y llamativo para convocar a la gente a participar)

Más chico abajo:

PRODUCTO 
Producto de Klaukol que promocionamos ese mes.

OBRA DEL MES
Relevamos un estudio de arquitectura o empresa de construcción en particular a partir de una obra en particular y la linkeamos.

VISIÓN GLOBAL
Novedades de la industria a nivel mundial o local, estadísticas, etc

NOVEDADES PAREXKLAUKOL
Novedades de la empresa.

Cualquier duda consultame.

abrazo

**Comment by FAAREIA** [comment]
Ahi va el adelanto del nuevo diseño.
**Falta terminar la encuesta, el producto del mes, el footer y el encabezado.**

Cualquier cosa que veas anda diciendome.
![nuevo-newsletter](https://cloud.githubusercontent.com/assets/6184969/13432104/f2b88d46-dfaa-11e5-9ecd-915130d9f539.png)

Abrazo

**Comment by LeandroBraier** [comment]
Me gusta mucho Fede!

1) La estética está bien, salvo por el tema de los colores. Yo los veo rosa y azul medio lavado. Necesito que sean el rojo y azul de la marca.

2) El título TENDENCIAS EN ARQUITECTURA cambialo por TENDENCIAS

3) El titulo INNOVACIONES EN CONSTRUCCIONES cambialo por INNOVACIÓN

Y ahí poné una foto de Klaukol Impermeable Potenciado y otra foto de la cortadora de Rubí:
http://www.rubi.com/products/es-ES/cortadores-manuales-para-ceramica/cortadores-profesionales-ts/ts.php

4) En Novedades ParexKlaukol rellená con las últimas 3 novedades que tenemos cargadas en el sitio. 

5) En Visión Global, cargá 3 titulos de esta web:
http://www.arquitecturaviva.com/

abrazo

**Comment by FAAREIA** [comment]
Ahi van los cambios y lo que faltaba:

![nuevo-newsletter](https://cloud.githubusercontent.com/assets/6184969/13461368/aab6f360-e05f-11e5-81de-e1b493db350d.png)

Cualquier cosa decime
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede! El footer iría al revés en realidad. El parexgroup en blanco a la derecha como siempre por manual de marca y el 0800 y url a la izquierda, pero dejame que lo vea el cliente así te paso todo junto después.

**Comment by LeandroBraier** [comment]
@FAAREIA avancemos para la semana que viene con este newsletter. Podrás ser para el 30/3?

Aquí te adjunto los contenidos aprobados por el cliente:

[Contenidos Newsletter ParexKlaukol Abril FInales.docx](https://github.com/LeandroBraier/Klaukol/files/186175/Contenidos.Newsletter.ParexKlaukol.Abril.FInales.docx)

abrazo

**Comment by FAAREIA** [comment]
Ahi me lo pongo a maquetarlo. Va a ir por mailchimp?
Con respecto al footer queda al revés como indicaste?
Abrazo

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! No dijo nada al respecto el cliente, pero lo ideal es que quede al revés como te pedía.

abrazo

**Comment by FAAREIA** [comment]
El mailing maquetado se puede ver en:
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-12/parexklaukol.html
Mañana le pongo el contenido real.
Con respecto a las próximas ediciones, el mailing se va a llenar a mano o va haber algun cms de por medio?

**Comment by LeandroBraier** [comment]
A mano como siempre. Es uno por mes. No se si tiene sentido el cms por
ahora.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-12/parexklaukol-16-12.html
Tiene mucha data faltante:
- Falta definir la imagen inicial.
- La pregunta de la encuesta es muy larga. Si van a ser todas asi le achicamos el tamaño al texto.
- No hay link a la encuesta, la cual también desconozco si va a ser nuestra o ajena.
- #ORGULLO no tiene foto
- Últimas novedades agrupa vision global y novedades parex. Hay que separarlas.
- La noticia de "13/03 a 04/07 Tres..." esta mal. La fecha de la noticia es la fecha de publicación, si hay un evento habría que poner la fecha inicial y final en el título.
- Todos las novedades no tienen link

**Comment by LeandroBraier** [comment]
Está buenisimo Fede!!
- Imagen inicial: por ahora dejemos esa.
- Pregunta encuesta: achicá la letra.
- Link de la encuesta: hay que generarla en la web. Puede ser con la misma estética directamente.
- #Orgullo te paso esta foto:

<img width="769" alt="captura de pantalla 2016-03-30 a las 12 25 02 p m" src="https://cloud.githubusercontent.com/assets/6719872/14146864/99ec43ac-f66f-11e5-825f-d9783f98feac.png">
- Últimas novedades. No, el pedido es que estén juntas, ambas bajo el título de "Últimas novedades" (Visión Global y NOvedades Parex desaparecen para siempre, si bien pueden quedar las novedades en 2 columnas)
- Ponele de fecha 04/04 y decí en el título: "Tres generaciones de arquitectos japoneses exponen en el MOMA de Nueva York hasta el 04/07
- Apenas tenga los links de las novedades te los paso, pero prefiero primero aprobar la maquetación. POrfa pasamela hoy así la hago aprobar.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-12/parexklaukol-16-12.html
La encuesta estoy viendo como hacerla. Te aviso por novedades

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-03/parexklaukol-16-03.html
Actualicé el link que estaba mal, estamos en marzo ^^

**Comment by LeandroBraier** [comment]
Gracias Fede!!!

Excelente! Cuando me den el OK te paso los links también.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
El newsletter ya tiene el link que va a la encuesta.

**Comment by LeandroBraier** [comment]
@FAAREIA recién hoy tuve feedback del cliente. Está todo bien, salvo los siguientes puntos:
1. Me pidieron cambiar la encuesta por esta:

En nuestra página de Facebook los usuarios aman a Rubí, marca que produce herramientas, máquinas y útiles ideal los proyectos de construcción más ambiciosos.
¿Qué opinás de las herramientas Rubí?

a) Son las mejores.
b) Son similares a otras marcas.
c) No las conozco.
1. Agregar la siguiente nota con fecha del 16/03 en Últimas Novedades:

16/03 Comportamiento de los despachos de cemento Portland 
1. Los links son los siguientes:

Nuevo Polo Tecnológico de Palermo
http://www.parexklaukol.com.ar/novedades/nuevo-polo-tecnol%C3%B3gico-de-palermo.html

Cómo se piensa una cocina
http://www.parexklaukol.com.ar/novedades/c%C3%B3mo-se-piensa-hoy-una-cocina.html

16/03 El índice Construya registró en Febrero un descenso de 2,4% respecto a Enero del 2016
http://www.parexklaukol.com.ar/novedades/el-%C3%ADndice-construya-registr%C3%B3-en-febrero-un-descenso-de-2-4-respecto-a-enero-del-2016.html

16/03 Comportamiento de los despachos de cemento Portland 
http://www.parexklaukol.com.ar/novedades/comportamiento-de-los-despachos-de-cemento-portland-.html

31/03 Washington recibe a representantes de todo el mundo para cumbre de arquitectura en seguridad nuclear
http://www.parexklaukol.com.ar/novedades/washington-recibe-a-representantes-de-todo-el-mundo-para-cumbre-de-arquitectura-en-seguridad-nuclear.html

04/04 Tres generaciones de arquitectos japoneses exponen en el MOMA de Nueva York hasta el 04/07
http://www.parexklaukol.com.ar/novedades/tres-generaciones-de-arquitectos-japoneses-exponen-en-el-moma-de-nueva-york-hasta-el-04-07.html

04/04 Estrenamos los últimos dos episodios de la audaz serie #EquipoKlaukol
http://www.parexklaukol.com.ar/equipoklaukol/

Dale prioridad a esto porfa, arrancá la mañana con eso.

Probalos porfa antes de cerrar el news y avisame así chequeo todo antes de pasarlo a Mailchimp.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-03/16-03.html

**Comment by LeandroBraier** [comment]
Está perfecto, Fede. Solo faltaría que el link de la encuesta lleve a la encuesta pedida. Ahora el link lleva a la anterior.

Usá el usuario de Gmail de Parex para eso. El mail es:

parexklaukolarg@gmail.com
Contraseña: parexklaukol2015

Si podés creala ahí porfa. Con eso ya largamos.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!! abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Ya lo envié. abrazo

**Comment by LeandroBraier** [comment]
Mañana fijate porfa @FAAREIA porque en la encuesta no se pueden ver los resultados una vez que votaste.

**Comment by FAAREIA** [comment]
Ahi ya se pueden ver los resultados.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!
