### ISSUE TITLE
Sumar Badges en Comunidad de Vendedores Potenciados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#268]
@mkreyness necesito saber si podemos sumarle un Badge de Honor a los vendedores que superen los 2500 puntos y brindarles todos los meses 10 tickets extra solo por tenerle el Badge.

Lo que necesito saber es si es muy complejo nada más y cuántos días de laburo te llevaría.

@FAAREIA en cuanto a maquetación necesitaría que pienses como te parece de mostrarlo: si agregarle algo especial al avatar del usuario, que la estética de su Comunidad sea toda diferente (no sé, dorada) en función de esto, algo dentro del perfil, lo que se te ocurra. 

abrazo

**Comment by mkreyness** [comment]
la complejidad para mi depende mas que nada de como afecte a la estetica o como/donde se vaya a mostrar.
El dato es muy facil de obener y darle 10 tickets extra a mes vencido tambien es muy simple.

**Comment by LeandroBraier** [comment]
Entiendo MK. Entonces yo lo haría simple. Calcule que fuera agregar una coronita al avatar dentro del Top 5 

<img width="327" alt="captura de pantalla 2016-02-26 a las 5 43 17 p m" src="https://cloud.githubusercontent.com/assets/6719872/13364484/cf87b8d8-dcad-11e5-9766-a0a0ad151b88.png">

y algo similar en la parte de "TU PERFIL" en la home.

<img width="331" alt="captura de pantalla 2016-02-26 a las 5 43 35 p m" src="https://cloud.githubusercontent.com/assets/6719872/13364473/c67b4d5e-dcad-11e5-89c9-73e3c54eead5.png">

**Comment by FAAREIA** [comment]
Si, se puede poner en dorado (amarillo) su nombre y puntos y agregar alguna coronita o estrella

**Comment by LeandroBraier** [comment]
Exacto, estrella me parece mejor. Gracias Fede!!

Vayamos avanzando entonces con la maquetación de esto para mañana o el
miércoles, puede ser? Necesitaría poder comunicar esto el jueves o viernes
y ya poder aplicarlo ese mismo día a todos los que tengan más de esa
cantidad de puntos.

abrazo

**Comment by LeandroBraier** [comment]
Chicos, esto queda frenado por el momento. Cierro el ticket y les aviso el próximo aviso.

abrazo
