### ISSUE TITLE
Bug Mobile en Puntos de Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#269]
@mkreyness el usuario MarielaMazzoni nos dice que intenta compartir distintas dinámicas desde su mobile y no le registra los puntos. Lo hace desde una pc y si lo hace. Se pueden fijar porfa con @valentinsabbath o con quien puedas qué está pasando?

Te digo las dinámicas que nos mencionó:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=35
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=36

Para mi este tipo de cosas ya las puede empezar a agarrar Valen no?

abrazo

**Comment by mkreyness** [comment]
Que mobile/navegador ? Necesitamos minimamente un poco de informacion para poder reproducirlo.
Puede ser que el API de facebook no lo soporte y en tal caso no podemos hacer nada.

**Comment by LeandroBraier** [comment]
Ahi consulté con el usuario.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-02-26 17:28 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness Me responde esto:

Mi tel. Es Samsung s5. Con Android.

**Comment by mkreyness** [comment]
Ah estos juegos ademas son de share, no de like, con lo que ni siquiera se usa el callback de facebook sino el hecho de apretar el boton.
No tengo nada Android para probar.
@valentinsabbath vos tenes ?
Te cuento como funciona: la pagina tiene un boton de share.

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34&usuario=marcelokreyness&clave=papa

vas a ver que al empezar la pagina se instala un eventListener asociado con un evento de edge.create del API de facebook. Cuestion de que cuando el usuario confirma la creacion de su post, ese evento del API llama a una funcion mia que se llama miCallback que se ocupa de hacer un Ajax para cargar los puntos, y finalmente para que eso se vea reflejado en la pagina termina haciendo un reload de la pagina.
Por algun motivo en ese contexto o no esta andando el API de facebook o no permite hacer el llamado AJAX (mas raro).
FIjate si lo podes debuggear un poco.

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath y @mkreyness ! Pudieron avanzar con este tema?

**Comment by mkreyness** [comment]
yo le tire ahi la pelota a Valentin, no tuve feedback.

**Comment by LeandroBraier** [comment]
@valentinsabbath necesito que revises esto porfa. Un usuario comparte posteo de la Comunidad desde su mobile y no le suma los puntos. Te lo paso por wunder también y te copio elpedido textual de MK. Necesito que confirmes si lo recibiste porfa. abrazo

> Te cuento como funciona: la pagina tiene un boton de share.
> 
> http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34&usuario=marcelokreyness&clave=papa
> 
> vas a ver que al empezar la pagina se instala un eventListener asociado con un evento de edge.create del API de facebook. Cuestion de que cuando el usuario confirma la creacion de su post, ese evento del API llama a una funcion mia que se llama miCallback que se ocupa de hacer un Ajax para cargar los puntos, y finalmente para que eso se vea reflejado en la pagina termina haciendo un reload de la pagina.
> Por algun motivo en ese contexto o no esta andando el API de facebook o no permite hacer el llamado AJAX (mas raro).
> FIjate si lo podes debuggear un poco.

**Comment by ghost** [comment]
@mkreyness Como accedo a http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34&usuario=marcelokreyness&clave=papa

**Comment by LeandroBraier** [comment]
Probá con este mejor:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=34&usuario=LeandroBraier&clave=parexklaukol

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by ghost** [comment]
Solo comparte la página 
![screenshot_20160311-114129](https://cloud.githubusercontent.com/assets/16599421/13705290/ed1577ce-e77e-11e5-8515-fa7543b43f5d.png)

**Comment by ghost** [comment]
Si comparto el video, tampoco me suma 120 pts.

**Comment by LeandroBraier** [comment]
Exacto. Ese es el problema que necesito que uds solucionen.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ahi le cambie la clave a "papa" para que ande, tenia otra cosa.
Lo que tenes que debuggear (si tenes como) es ver que pasa con las llamadas que se hacen dentro de fbcallback.js, yo tengo la idea que debe ser que el API de Facebook cuando esta dentro de un navegador de android NO esta llamando al callback como deberia. Esta es la documentacion en que me base para hacer uso de esos callbacks y en PC funciona normalmente:

https://developers.facebook.com/docs/reference/javascript/FB.Event.subscribe/v2.5

**Comment by ghost** [comment]
@mkreyness el que no sume puntos cuando comparto el video por facebook puede tener algo que ver con esto?:
Leverage browser caching (3)
The following cacheable resources have a short freshness lifetime:
M0.jpg
The following resources are explicitly non-cacheable. Consider making them cacheable if possible:
/cgi-bin/sumalike.pl?usuario=LeandroBraier&clave=parexklaukol&juego=76
www.facebook.com/

**Comment by mkreyness** [comment]
No tendria por que cachearse nada, es una llamada a un programa en el servidor.
Obviamente si no lo llama, no se suman los puntos.
Pero ojo que igual podria estarlo llamando y no sumar los puntos porque LeandroBraier es un usuario SUSPENDIDO y no puede pasar de 95 puntos.
Tampoco tengo claro por que dice facebook despues o M0.jpg antes.

**Comment by mkreyness** [comment]
Jamas le sumaria 120 puntos a un usuario suspendido. 
Esa es la razon ademas por la cual podes seguirlo haciendo, si no ya te hubiera dado el juego por "Hecho" y no se puede volver a jugar.
@LeandroBraier te desuspendemos para poder probar ?

**Comment by ghost** [comment]
y vos también estás suspendido? porque tampoco me suma

**Comment by mkreyness** [comment]
Claro, estamos suspendidos justamente para no aparecer como que estamos ganando puntos y quitandoles posibilidades a los verdaderos vendedores en el sorteo.

**Comment by ghost** [comment]
pregunta, cuando ella comparte por face en el movil, se le abre la app de Facebook o el browser?

**Comment by LeandroBraier** [comment]
No tengo ni idea eso jeje. Es un usuario al que ya le preguntamos muchas
cosas y hace más de 1 semana. No sé si puedo seguirle preguntando.

Yo calculo que depende de la configuración de cada usuario.

**Comment by ghost** [comment]
## @mkreyness  Buscando encuentro que varios ponen este código que dicen que es necesario para que funcione. 

protected override void OnActivityResult (int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult (requestCode, resultCode, data);

```
        callbackManager.OnActivityResult (requestCode, (int)resultCode, data);
    }
```

**Comment by mkreyness** [comment]
Pero eso es de algun SDK para otro lenguaje, ademas eso en si no dice nada.
Si no es "web", no importa, son SDK para hacer aplicaciones en C++ o cosas asi que no es lo que usamos.
Fijate si hay problemas para usar el JAVASCRIPT SDK en browsers android.

**Comment by ghost** [comment]
@mkreyness podrías desbloquear tu usuario asi veo si suma los puntos? Prometo no llevarme el premio

**Comment by LeandroBraier** [comment]
Acabo de desbloquearte el usuario MarceloKreyness Valen. Asi no hace falta
que lo haga MK.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by ghost** [comment]
Gracias @LeandroBraier

**Comment by ghost** [comment]
Ahora no me puedo loguear. Se cambió la contraseña?

**Comment by LeandroBraier** [comment]
Revisé el CMS y la pass actual es: 
**mysql99**

**Comment by mkreyness** [comment]
NO, ya le puse "pepe" de nuevo.

**Comment by mkreyness** [comment]
Borra ese post plis, es mi contra maestra.

**Comment by mkreyness** [comment]
No se como volvio a ponerse, yo la habia cambiado por "pepe" hace unos dias justamente para no tener que decir eso aca.

**Comment by ghost** [comment]
En Chome para android (probé en el chrome porque es el navegador que viene con mi celular, en lugar de el navegador nativo de android), compartí dos cosas y sumó puntos perfectamente.

**Comment by LeandroBraier** [comment]
jajaja OK. Borrado MK.

**Comment by LeandroBraier** [comment]
Perfecto. Probá en el de android también por las dudas. No sabemos con cual
acceden los usuarios. Pudiste registrar cual era el inconveniente que no
sumaba los puntos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-14 11:02 GMT-03:00 valentinsabbath notifications@github.com:

**Comment by mkreyness** [comment]
por lo que dice no pudo reproducir el problema, lo mismo que me pasa en la PC.

**Comment by ghost** [comment]
quizás tenga el browser desactualizado, porque probé en el browser nativo y me sigue dando buen resultado

**Comment by mkreyness** [comment]
o alguna opcion de seguridad que no ejecute javascript capaz ?

**Comment by ghost** [comment]
Claro, si tiene deshabilitada la opción de "permitir javascript" no le va a funcionar

**Comment by mkreyness** [comment]
pero me suena que si fuera asi no le andaria practicamente nada de la pagina.
Tiene que haber alguna cuestion de "same-origin-policy", ese tipo de cosas atentan contra el ajax y los callbacks. Capaz un browser desactualizado esta restringiendo de mas. Hasta no poderlo reproducir, no podemos saber que es.

**Comment by LeandroBraier** [comment]
Ok, hagamos así. No sigamos trabajando en esto pero estemos atento por si se nos ocurre qué puede estar pasando o si reproducimos el error. Gracias a los dos!!
