### ISSUE TITLE
Nuevos Juegos VIsuales para Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#270]
@mkreyness estos son juegos para comprar también, son PHP.

http://codecanyon.net/item/50-quiz-pack-for-socioquiz-vol-2/11975240?s_rank=1

Los podemos utilizar o es mucho lio? Seria lo mismo que HTML5 solo que sin Construct no?

**Comment by mkreyness** [comment]
Mmmm, no, nada que ver con HTML5, esto son paginas web comunes que corren en el servidor. 
Son como nuestras trivias pero mostrando imagenes y donde no hay "respuestas correctas" sino un resultado predeterminado en funcion de cuantas veces contestaste la "a.", cuantas veces la "b." etc como en los tests de la revista "Para Ti" (que jamas he leido, pero me los imagino).

El asunto es como esto termina dandote un puntaje (siendo que no hay respuestas correctas) o no tendrian puntaje ?

Ojo que estos al final te obligan a loggearte con facebook, no sea cosa que despues terminen posteando cosas en los muros de la gente y nos maten a puteadas.

**Comment by mkreyness** [comment]
por otra parte, estan en ingles !  Si los datos estan en una base de datos, tenemos que ver como injertar esto y hacer un CMS, y si los datos estan en codigo, hay que editar montones de codigo para traducirlo, y asegurarse de no romper el codigo...

**Comment by LeandroBraier** [comment]
Perfecto, MK. Entonces decime cuanto tiempo nos llevaría adaptar la trivia
a poner imágenes en las opciones y en el resultado una foto y un texto.

Te paso un ejemplo:

_¿A cuál de estos lugares preferirías ir de vacaciones?_

Opciones en imagen:

Playa 1

Montaña 2

Ciudad Europea 3

Turismo Aventura 4

_¿Cuál de estos productos te resultaría más interesante vender?_

Opciones en imagen:

Un celular 1

Un tractor 2

Un cubreojos 3

Un passacassette 4

_¿Con cuál de los siguientes vendedores te identificás?_

Opciones en imagen:

Leonardo Di Caprio en The Wolf of Wall Street 1

Tom Cruise en Jerry Maguire 2

John Hamm en Mad Men 3

Richard Harrison de El Precio de la Historia 4

_Resultados posibles:_

Sos un vendedor valiente y arriesgado, pero te pasás del límite y no tenés
en cuenta a los demás. Deberías pensar más en tus clientes. (Da con 4
puntos)

Sos un representante ejemplar de tu marca, das todo, hasta la salud y la
vida, por conseguir tus objetivos. ¡Muy bien! Pero aflojá un poco en tus
vacaciones. (Da con hasta 8 puntos)

Sos un vendedor distinto. Original, más inventivo que el resto, siempre
salís bien parado de toda situación aunque te gusta el riesgo.
¡Felicitaciones! Sos único. (Da con hasta 12 puntos)

Sos un descubridor de tesoros. Siempre vas más allá de la primera impresión
de las cosas y lográs mucho más de lo que se esperaba sin necesidad de
ideas deslumbrantes. ¡Bien ahí! (Da con hasta 16 puntos)

2016-02-26 19:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ponele una semana con toda la furia, pero en el medio necesito alguna remaquetacion de Fede o Braulio sobre las dos pantallas (la de pregunta+opciones y la de resultados) para que las fotos queden bien acomodadas.

**Comment by LeandroBraier** [comment]
@mkreyness necesitaría que tengamos listo este tipo de trivias en VIE TUR este viernes para una dinámica a publicar el lunes 21 de marzo. Llegamos?

**Comment by mkreyness** [comment]
Supongo que si, pero que hay de la remaquetacion de las pantallas para que puedan tener fotos ?

**Comment by LeandroBraier** [comment]
@FAAREIA repasá este ticket para arriba, que está explicado de lo que estamos hablando.

**Comment by mkreyness** [comment]
@FAAREIA a partir del que dice 
"Perfecto, MK. Entonces decime cuanto tiempo nos llevaría adaptar la trivia
a poner imágenes en las opciones y en el resultado una foto y un texto."

Lo de antes no va.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/vendedores/trivia-imagenes.html
Si esta ok ya lo paso a produccion asi marce hace lo suyo

**Comment by LeandroBraier** [comment]
Excelente Fede!!! Adelante.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Buenísimo.
@mkreyness 
- El template esta en: http://www.parexklaukol.com.ar/vendedores/trivia-imagenes.html
- Fijate que al `form` le agregué la clase `imagenes`
- Los `div` contenedores de los `label`, cierran tag en línea nueva, no hay espaciado
- La imagen esta en el nuevo tag `small` referenciada con un `style` inline.

Creo que nada más, cualquier cosa decime
Abrazo

**Comment by mkreyness** [comment]
Ojo faltaria un template mas, para cuando se muestra el resultado, ahi si iria una sola imagen grande y un texto.

**Comment by LeandroBraier** [comment]
Es cierto MK. Y eso tendríamos que cargarlo también desde el CMS. Cuando esté armado el juego necesito que me confirmen el tamaño que tienen que tener las imágenes.

No se olviden que necesito que esta nueva modalidad esté subida tanto a Parex como a VIE TUR.

**Comment by mkreyness** [comment]
Si, la parte de resultados esta en el CMS y ahora le incorpore imagen, tengo hecha toda la parte de las preguntas pero me falta implementar el resultado, porque llegue ahi y vi que hacia falta un nuevo template.
La idea es que en el CMS se cargue el maximo valor obtenido que merece ese resultado (ej, para el que es de 0 a 4, le pones 4, para el que es de 5 a 8, le pones 8, etc.

Terminemos primero en Parex y despues veo como trasladarlo a VIE TUR, no son los mismos templates.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Avancemos hoy con esto porfa.

2016-03-18 12:13 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Listo, ahi agregué el template: trivia-imagenes-completaT.html
En este caso las respuestas se muestran asi: http://www.parexklaukol.com.ar/vendedores/trivia-imagenes-completa.html
@mkreyness fijate que las respuestas ya no son un `<dl><dt>RTA #1</dt><dd>Texto rta</dd></dl>` ahora estan dentro de un `div.imagenes` y son `divs`

**Comment by mkreyness** [comment]
pero no van 4 imagenes, va UNA imagen, la idea es que diria tipo "Sos un MACHO ALFA, felicitaciones!" y va la imagen de un macho alfa, lo que sea que esto fuere.
Esto es un QUIZ, de esos que te dicen 
"si fueras una flor serias... Una Rosa ? Un Clavel ? Una Cala ? Un Helicántropo ?"
"si fueras un pajaro serias Un Gorrion ? Un Halcon ? Una Paloma ? Un pterodáctilo? "
"si fueras un mamifero serias... "Una vaca ? Un gato ? Un perro ? Un ornitorrinco ?"

Sumas los puntos y te da que si sumaste menos de 7, te dice "Sos un fiaca que no quiere pensar"
si sumaste de 8 a 15 te dice "Sos un mediocre sin ambiciones, bueno para nada"
si sumaste de 16 a 23 te dice "Sos un retorcido diletante, oprobioso y sobreactuado"

y cada posible resultado lleva un dibujo alusivo.

**Comment by LeandroBraier** [comment]
Exacto. Es como dice Marce. Y son 4 soluciones distintas posible, no 3.
Verdad?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-18 17:15 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Tantas como quieras poner. Yo no estoy limitando ni la cantidad de preguntas ni la cantidad de opciones.

**Comment by LeandroBraier** [comment]
Recuerden que este juego tiene que estar activado para cargar el lunes
antes del mediodía porfa. Tanto en VIE TUR como en Vendedores ParexKLaukol

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Yo una vez que este terminado esto del template lo liquido en un ratito. Ahora estoy sin fibertel conectado por el iPhone, asi que no estoy en la mejor de las situaciones, pero de aca a mañana te tengo todo en condiciones como para que lo cargues en el CMS de Parex. Si ves todo bien, despues lo traslado a VIE TUR.
Lo que si para ir ganando tiempo @FAAREIA si poder hacer estos mismos templates compatibles con lo que esta instalado en VIE TUR (seguro hay alguna diferencia, fijate como estan los triviaT.html y triviacompletaT.html de VIE TUR), mejor.

**Comment by FAAREIA** [comment]
#### VENDEDORES

Ahora si, actualicé el template en base a la idea descripta: trivia-imagenes-completaT.html
Maqueta de ejemplo final: http://www.parexklaukol.com.ar/vendedores/trivia-imagenes-completa.html

**Comment by FAAREIA** [comment]
#### VIETUR

http://comunidad.vietur.com.ar/trivia-imagenes-id.html
http://comunidad.vietur.com.ar/trivia-imagenes-completa.html

Es lo mismo que para vendedores

**Comment by mkreyness** [comment]
@LeandroBraier dale el ok a esa maqueta y trabajo sobre eso y lo termino.

**Comment by LeandroBraier** [comment]
Gracias Fede!!

Les confirmo Maqueta por Maqueta:

**http://comunidad.vietur.com.ar/trivia-imagenes-id.html**
Está OK. Adelante. Solo faltaría hacerlo responsivo no?

**http://comunidad.vietur.com.ar/trivia-imagenes-completa.html**

. El "¡Felicitaciones" debería estar adentro de la foto, junto con el otro texto.

. El + 40 puntos no debería aparecer ahi no?

abrazo

**Comment by FAAREIA** [comment]
Los puntos no van ni en vendedores ni en vietur?

**Comment by LeandroBraier** [comment]
No van en el resultado este, me parece que no quedan bien. Si estaban en
los demás juegos no me había dado cuenta, por las dudas saquemoslo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi lo acomodé en vendedores: http://www.parexklaukol.com.ar/vendedores/trivia-imagenes-completa.html
Faltaría hacer el responsivo, que para eso necesitaría saber que tipo de longitud van a tener los párrafos/frases.
Mañana a la mañana lo translado a vietur.

**Comment by LeandroBraier** [comment]
Gracias Fede! Quedó perfecto ahora. Dale, genial.

**Comment by FAAREIA** [comment]
Bueno ya estan los templates listos ya sea en comunidad como también en vietur.
Los templates se llaman:
`trivia-imagenes-completaT.html`
`trivia-imagenesT.html`
Estan responsivos también.

Abrazo

**Comment by LeandroBraier** [comment]
Mil gracias Fede! Genio! Avisame MK lo que necesites. Abrazo

**Comment by mkreyness** [comment]
en realidad no deberian decir "trivia completa", no son trivias.

**Comment by mkreyness** [comment]
@LeandroBraier  si queres ir probando y modificando los contenidos, tene en cuenta lo siquiente (en el CMS): los puntos que suma elegir cada opcion, estan cargados EN LA OPCION, no influye lo que dice puntaje por pregunta (eso es para las trivias normales).
En la solapa de "resultados" que ahora revivio en las trivias (no se usa en las trivias normales) pones las categorias con el puntaje HASTA el cual aplican (el desde esta implicito, es el siguiente al anterior "hasta").
El unico TEMA que cargue por ahora se llama "test QUIZ no publicar" y esta relacionado con un JUEGO que se llama "contestar quiz". El puntaje por contestar (no importa el resultado) es el que dice en el JUEGO, aunque en el TEMA tambien lo dice a efectos de que se muestre en la lista de temas.
Obviamente como no esta publicado no te va a aparecer en la lista, pero lo podes acceder por aca:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=40&...
y ponele usuario y clave que quieras (por ej el mio marcelokreyness pepe)

Acordate que esto funciona como un trivia, y los trivias no se empiezan a contestar DE ENTRADA, hay una primer pantalla de introduccion (donde mostras el video y la documentacion). Esta pantalla no se si tiene que estar, no importa que esté, o molesta que esté. Yo la dejé por si acaso, pero es implica que tenes que ponerle alguna imagen asociada tambien (eso va en el TEMA, como siempre).
El botoncito para arrancar a contestar todavia dice "Trivia", porque es el mismo que las otras.
Dependiendo de lo que decidas hacer con esta pantalla, podemos 
1) eliminarla y que entre a contestar inmediatamente
2) dejarla y entonces hacer un template separado para que en vez de "Trivia" diga "Quiz" ? No se si queremos explicitar ese nombre extranjerizante.

Confirmame todo y despues lo aplico a VIE TUR.

**Comment by mkreyness** [comment]
@LeandroBraier yo mañana a la mañana me voy temprano porque tengo dentista, asi que para ganar tiempo ya pase todo a VIE TUR, pero siguen pendientes cerrar las mismas definiciones.
@FAAREIA las imagenes no me estan andando igual, fijate aca 

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=16&...

usuario=LBraya02
clave=vietur

vas a ver que la primer imagen sale corrida hacia arriba.

Los templates reales en uso se llaman quizT.html y quiz-completaT.html

**Comment by LeandroBraier** [comment]
Gracias MK y Fede! Mañana pruebo cargar y te digo pero en principio estamos
bien asi. No hace falta cambiar Trivia por quiz.

Fede avisame cuando esté corregidi el tema de la imagen.

Abrazo grande

**Comment by FAAREIA** [comment]
Solucionado lo de las imágenes, era algo en el css

**Comment by LeandroBraier** [comment]
Gracias chicos! Acá lo estamos probando y parece funcionar en general pero hay algunos bugs.

Al mismo tiempo probé en Parex y en VIE TUR. En VIE TUR funcionó joya en principio, pero no me dejó cargar los resultados. Los subimos y no quedan registrados. 

En Parex no sé por qué me dejó de tomar los tildes el CMS.

**Comment by mkreyness** [comment]
Pero viste que yo habia dejado cargados unos ejemplos, tenian resultados.

A que te referis con los tildes ?

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Escribo texto con tilde, por ejemplo: "Respondé esta trivia" y me aparece como "Responde? esta trivia"

Yo cargo los resultados y no me aparecen en la lista de resultados. Me sigue apareciendo así la lista:

<img width="1492" alt="captura de pantalla 2016-03-21 a las 6 16 03 p m" src="https://cloud.githubusercontent.com/assets/6719872/13933909/2c08c58c-ef8e-11e5-8092-195c3c35d3df.png">

**Comment by mkreyness** [comment]
ahh letras acentuadas. Pense que hablabas de los tildes de "[x] Respuesta Correcta".
Ok, me pasas el URL donde ves los acentos mal ? Es en el CMS o es en la pagina que ve el usuario ?

**Comment by LeandroBraier** [comment]
Olvidate de eso jeje Lo volví a probar ahora y anda bien. Me parece que era
porque yo hice copy paste en lugar de escribirlo desde cero en el CMS.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ahi arregle lo que no cargaban los resultados, ojo no repitas los "hasta"

**Comment by LeandroBraier** [comment]
Gracias MK!! Te confirmo cuando pude subir todo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness acabo de terminar de subir un quiz entero en VIE TUR y encontré montones de problemas, que no se ven resueltos ni isquiera en el test que hicieron uds. No entiendo por qué no lo solucionaron antes si vieron que pasaba en el test pero entiendo que debe haber algún motivo. Más allá de esto les paso los errores:

1) No se lee Trivia en el nombre de juego:

<img width="705" alt="captura de pantalla 2016-03-22 a las 11 36 25 a m" src="https://cloud.githubusercontent.com/assets/6719872/13954413/695e95ce-f01f-11e5-87fb-ca8225b378dc.png">

2) Las opciones se ven en texto, no en imagen y sin el casillero para seleccionar la opción (lo cual es lógico siendo que deberían mostrar imagen y no texto)

<img width="724" alt="captura de pantalla 2016-03-22 a las 11 35 42 a m" src="https://cloud.githubusercontent.com/assets/6719872/13954452/8fd0d708-f01f-11e5-8c54-94bbf667d9f9.png">

3) Los resultados se ven OK. LO que les pido ya que estamos es que cambien el texto TRIVIA COMPLETA por TU PERFIL DE AGENTE VIE TUR.

Esto es SUPER PRIORIDAD porfa.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, pasanos el ID del juego o el link y dale F5 ahora que antes había subido un css "viejo" y ya lo actualicé

**Comment by LeandroBraier** [comment]
El ID es el 17.

Ahora lo veo bien, solo me falta el punto 1 que te decía. QUe diga "QUIZ" o
TRIVIA en la primer pantalla. Quizá eso es de Marce.

**Comment by FAAREIA** [comment]
Mmmm, ese template de la intro de la trivia no lo toqué. Imagino que debe ser algo de que al juego no le especificaste los puntos que da entonces no renderiza esa parte. Seguro @mkreyness va a saber decirte mejor.

**Comment by FAAREIA** [comment]
Con respecto a las imágenes, tratá de subir imágenes que sea cuadradas asi la animación del mini zoom de la imagen cuando hacer mouse-over funciona.

**Comment by LeandroBraier** [comment]
OK Fede. Igual se ven bien las imágenes.

Respecto de los puntos si está cargado correctamente, debería verse bien.
Intuyo que es algo de MK. No crearon el cartelito que diga Quiz para este
tipo de objeto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness cuando estés de vuelta te fijás porfa este tema?

https://cloud.githubusercontent.com/assets/6719872/13954413/695e95ce-f01f-11e5-87fb-ca8225b378dc.png

abrazo

**Comment by mkreyness** [comment]
estoy de nuevo sin internet, apenas pueda tener una conexion decente me fijo

**Comment by mkreyness** [comment]
Lean, otra vez agregaste un "COMPARTIR" que confunde en el mismo tema, y se escapa por otro template.
El juego SOLO tiene que ser el QUIZ.

Ya se que el template de QUIZ no tiene compartir, pero eso es porque el template que encontre para usar no lo tenia y por si acaso no se lo agregue.
Si queres que el quiz se pueda compartir, lo modifico a nivel template, NUNCA agregues juegos "COMPARTIR" donde ya hay un juego.
Te vuelvo a decir el concepto: el juego "COMPARTIR" es para aquellos casos en que lo UNICO que hay es compartir, asi no pone otras cosas.

**Comment by LeandroBraier** [comment]
Ok MK. Ahora entiendo lo del compartir. No lo hago más. Igual eso no tiene
nada que ver con el problema que te señalé. Sin el compartir sigue igual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-22 18:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
cual es el problema entonces ?

**Comment by mkreyness** [comment]
ninguno de los templates dice ahi cuantos puntos se gana, entiendo que eso fue una politica que se definio de movida de esa manera, porque si no lo decia 3 veces, te acordas ?

**Comment by LeandroBraier** [comment]
Si, en las Trivias dice TRIVIA + 90. Necesito que digo TRIVIA + 100 en este caso.

<img width="275" alt="captura de pantalla 2016-03-22 a las 6 37 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/13968221/555bae6e-f05a-11e5-90b1-3fef1a2cf76e.png">

COmo está ahora queda mal. Se nota el espacio vacío.

**Comment by mkreyness** [comment]
En que trivia te sale asi ?
Yo estoy seguro de haberlo sacado de todos lados porque decia 3 veces lo mismo (una vez en cada icono) y decian que confundia.

**Comment by LeandroBraier** [comment]
En esta por ejemplo:

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=14&usuario=LBraya02&clave=vietur

**Comment by mkreyness** [comment]
ok me fijo que template usa y le copio esa parte, porque realmente en el que estoy usando no estaba.

**Comment by mkreyness** [comment]
ahi lo arregle, era otra cosa. En Klaukol debe pasar lo mismo, ahora lo arreglo.

**Comment by LeandroBraier** [comment]
Perfecto, gracias MK! abrazo
