### ISSUE TITLE
Mailing de Bienvenida Comunidad de Vendedores Abril. 08/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#271]
@braulio-evangelisti necesito una adaptación del mailing agregando el premio arriba en el header como siempre.

![slide-premio-marzo](https://cloud.githubusercontent.com/assets/6719872/13462580/d750e154-e066-11e5-984a-78a7d90568eb.png)

Te mando por wetransfer el psd, confirmame si recibiste.

Puede ser para mañana esto?

abrazo

**Comment by LeandroBraier** [comment]
https://www.wetransfer.com/downloads/418e41353fc6081f90cdee5c3fe0c12f20160302140627/c19ba9

**Comment by braulio-evangelisti** [comment]
http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida-marzo.html ?

**Comment by LeandroBraier** [comment]
Peefecto. Solo sacale el texto en negro que repite "GIFTCARDS HASTA 3.000"

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Listo

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! @mkreyness porfa enviemos esto a listas 1 y 2 mañana a la tarde. abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA necesito mañana que adaptes este mailing con la gráfica del premio de este mes:

![mailing-premio-abril](https://cloud.githubusercontent.com/assets/6719872/14349685/052c2494-fc9b-11e5-9edb-94b79b19fc35.png)

Debería decir EN ABRIL PARTICIPÁ POR y que ahí apareciera esa imagen.

Una vez hecho, dejaselo a @mkreyness y armalo como template en mailchimp como hiciste con el template del concurso de colocadores, así puedo hacer un envío a todos los vendedores desde ahí, como hicimos con el Club de Colocadores.

abrazo

**Comment by mkreyness** [comment]
Y yo a que lo aplicaria ? No tenemos bienvenidas automaticas en vendedores, porque el alta siempre es masiva por un Excel y en tal caso tiene mucho mas sentido que lo mandes por Mailchimp.

**Comment by LeandroBraier** [comment]
Claro, la idea es que lo mande yo directamente por mailchimp. De hecho ayer me pasaron 8 nuevos usuarios y los cargué a mano en el CMS, pero no les envié mailing de bienvenida para que ya esté con el nuevo premio. La idea es que no tengas que enviar más mailings de eso desde Duplika.

**Comment by mkreyness** [comment]
Me parece perfecto, pero no se entonces por que le decis a Fede que cuando termine me lo pase, que tengo que hacer yo con eso ?

**Comment by LeandroBraier** [comment]
Por las dudas nomás. Jeje Mala mia.

**Comment by FAAREIA** [comment]
Cual es la gráfica del premio de este mes?

**Comment by LeandroBraier** [comment]
Perdón, ahi te la subí en mi pedido anterior. Me había olvidado de subirla.

**Comment by FAAREIA** [comment]
Ahi estuve limpiando y haciendo retina el mailing.
Lo pueden ver online y en mailchimp.
El HTML online es solo de muestra, no es para enviar porque los estilos estan puestos de un forma no aceptada por los clientes de mail. El HTML de mailchimp si esta enviable.
http://www.parexklaukol.com.ar/_mailing/comunidad-vendedores/premio-16-04/premio-16-04.html
https://us11.admin.mailchimp.com/templates/design?tid=216149

**Comment by FAAREIA** [comment]
Las fechas las estoy poniendo como año/mes asi ordenan bien los mailings

**Comment by LeandroBraier** [comment]
Está perfecto Fede!! Muchas gracias!
