### ISSUE TITLE
Mailing de Cumpleaños Comunidad de Vendedores. 04/03

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#272]
@braulio-evangelisti necesito también dos propuestas de mailing para enviar a cada vendedor el día de su cumpleaños. Te paso una referencia que al cliente le gustó, pero tiene que estar adaptada a nuestra estética.

http://appnew.embluejet.com/Online/VersionOnline.aspx?eQ2cr45fZt2lsj1RIFsFy-R-51873-R-0

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA  y @braulio-evangelisti como viene esto?

**Comment by LeandroBraier** [comment]
hola?

**Comment by braulio-evangelisti** [comment]
Buen día Lea

Aca te paso 2 bocetos

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/cumple1.jpg

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/cumple2.jpg

El segundo es mas de la estetica de vendedores pero no me convence. Si necesitas armo una tercera opcion a ver como queda.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! Va feedback:

1) Estéticamente veo más rumbeado el segundo pero le falta un poco de trabajo. Tomá de referencia  la línea del nuevo newsletter que armó Fede, que al cliente le encantó: 

https://cloud.githubusercontent.com/assets/6184969/13461368/aab6f360-e05f-11e5-81de-e1b493db350d.png

Sobre todo en aplicación de marca: header, footer, etc.

2) En cuanto al diseño internamente que la torta sea grande, no chica, es importante, aunque está bueno que sea roja y azul. Falta más elemento festivo, es un cumpleaños.

3) No sé si viste bien a fondo la refe que te pasé: tiene un link que lleva a una app web para soplar las velas y al final te da un descuento. Necesito que piensen una dinámica interesante de este tipo. Puede ser la torta y el regalito y que el regalito se abra o algo divertido que se les ocurra, pero que siga esa misma línea de la refe (sin ser un robo, claro).

abrazo

**Comment by braulio-evangelisti** [comment]
Buen día Lea

Fijate ahora
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/cumple3.jpg

Abrazo

**Comment by LeandroBraier** [comment]
Buen día Brau!! 

Gracias! Hay algo que me entendiste mal. La estética del mailing es la de Comunidad de Vendedores, no la del Newsletter. Lo que quería que tomes del Newsletter es la aplicación de marca: Si va ParexGroup a la derecha y con los logos en el fotter va así. Pero recordá que el  mailing es de la Comunidad de Vendedores, por lo cual lo que tiene que estar al frente apenas abrís el mail es la Comunidad de Vendedores. En este sentido, salvo por el footer, está mejor esta versión
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/cumple1.jpg

Sobre esta, te paso feedback:

1) Le falta fiesta. Quizá aparte del regalo, una torta con velitas de fondo en segundo plano o unas guirnaldas o algo que remita a cumpleaños, sino es un regalo porque sí, no porque es el cumpleaños. La frase "feliz cumpleaños" podría estar en rojo o en un color un poco más vivo.
2) El logo de Comunidad está a la derecha, ponelo al centro o a la izquierda.
3) Agregale lo de Abrir el Regalo que implementaste en esta última versión. Para explicar eso necesitaría que maquetes también como sería la landing que se abriría cuando la persona clickee para abrir el regalo.

abrazo

**Comment by braulio-evangelisti** [comment]
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/cumple4.jpg

Ahi va con mas fiesta, la frase feliz cumpleaños en otro color que no sea blanco cuesta leerla sobre la foto, centré el logo de la comunidad, apenas tengamos definido esto armo uno de la landing donde caería el link del regalo.
No le agregué otra torta porque ya tiene una torta en la foto.

**Comment by LeandroBraier** [comment]
Me gusta @braulio-evangelisti Necesito que cambies el moño amarillo por azul (un tema de marca y me mandes como sería el link al que lleva.

**Comment by braulio-evangelisti** [comment]
Ahi va con el lazo azul:

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/cumple5.jpg

Estoy armando una posible landing, con un regalo y una torta, que se abra el regalo y aparezca un ticket con 40 puntos o algo asi, apenas lo tenga lo subo asi lo ves.

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti me gusta como quedó. El texto te lo mando hoy corregido. Espero entonces lo del regalo y el ticket que pueda decir cualquier cosa. Por ejemplo:

40 puntos

Kit de asado

Radio portatil. Que dentro del ticket haya un texto que diga el premio y chau. abrazo

**Comment by braulio-evangelisti** [comment]
Fijate algo asi:

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/abri1.jpg
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/abri2.jpg
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/abri3.jpg

Estan en orden de como seria la dinamica, donde dice 00 iria la edad que cumple la persona si se puede calcular con el dato de la db.

Abrazo

**Comment by LeandroBraier** [comment]
Me gusta. Maquetala como una página de la Comunidad misma, como la página
de Ganadores por ejemplo. Y en lugar de PREMIO PREMIO poné TE REGALAMOS UNA
REMERA KLAUKOL

El lunes te paso los textos finales del mailing así lo presentamos y lo
maquetamos.

abrazo y gracias!

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti ! Te paso los textos que van:

MAILING

**¡¡¡Feliz cumpleaños XXnombreXX!!!**

**La Comunidad de Vendedores Potenciados crece día a día por la potencia de cada uno de sus miembros y por eso nos enorgullece tenerte en el equipo.**

**Hoy es tu cumpleaños y decidimos enviarte este presente. Para abrirlo, simplemente tenés que hacer  clic sobre él.** 

**Te deseamos que disfrutes tu día al máximo y no olvides compartir tu regalo con tus amigos.**

Firma: (LOGO COMUNIDAD DE VENDEDORES)

PÁGINA DEL REGALO

(LOGO COMUNIDAD DE VENDEDORES)

**La Comunidad de Vendedores Potenciados crece día a día por la potencia de gente como vos. Por eso hoy que es tu cumpleaños decidimos enviarte este presente. 
Hacé clic para abrirlo y nos pondremos en contacto para entregártelo.**

TEXTO DEL REGALO: **Te regalamos una Remera Klaukol.**

Avisame porfa cuando lo tengas online para mandarle al cliente.

abrazo

**Comment by braulio-evangelisti** [comment]
Perfecto lea. Calculo que mañana ya subo material de esto maquetado.

Abrazo.

**Comment by braulio-evangelisti** [comment]
Lea fijate ahi:

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/vendedores-cumple.html

Si haces click en el regalo te lleva a la maqueta de prueba para la pantalla de cumpleaños que luego habria que meter en vendedores.

El regalo se abre pasando el cursor por encima y al hacerle un click al ticket se activa.

Abrazo.

**Comment by LeandroBraier** [comment]
Quedó buenisimo Brau!!

El número 75 es la edad real del tipo? Quitemos ese número, que se vean las velitas nomas. Igual lo voy mandando para aprobar. Gracias!

**Comment by braulio-evangelisti** [comment]
Claro seria la edad, puse cualquier numero de ejemplo, se me ocurrio que a lo mejor podria imprimirse la edad calculandola con el dato de la fecha de nacimiento en la db. Habria que consultar con marcelo no?

**Comment by LeandroBraier** [comment]
Pero mejor no lo usemos y listo. Que se vean 2 velitas y nada más.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@braulio-evangelisti el cliente lo vio y el mailing está perfecto. 

Lo que me pidió es en la landing. Son dos cosas:

1) que al hacer clic en el mail del regalo y llegar a la landing, que ya aparezca abierto el regalo con el ticket grande. Que no tenga que volver a hacer clic. 

2) que la estética del regalo de la landing sea la misma estética que usaste en el mailing. Como ahora la landing es estática ahora creo que podrías hacerlo sin problema, no?

abrazo

**Comment by braulio-evangelisti** [comment]
1) Ok ahora lo armo

2) Puedo poner el regalo con los mismos colores del del mailing que son los de klaukol reales, pero armar el regalo como esta en el mailing (en perspectiva) abierto tendria que cambiar toda la dinamica porque va a quedar mal con el resto del sitio que es todo de frente.

**Comment by braulio-evangelisti** [comment]
Actualiza ahora Lea

**Comment by LeandroBraier** [comment]
Gracias Brau!! Lo unico sigo viendo el número en lugar de las velas. Lo demás perfecto.

**Comment by braulio-evangelisti** [comment]
Fiajte ahora

**Comment by LeandroBraier** [comment]
Brau, está bien pero simplifiquemosla. La vi en mobile y es demasiado. 

1) Quitale la parte del logo de arriba:
<img width="1043" alt="captura de pantalla 2016-03-16 a las 3 00 29 p m" src="https://cloud.githubusercontent.com/assets/6719872/13822605/0edd7348-eb85-11e5-99f6-db8f28367f97.png">

Dejando el fondo para que quede detrás del ticket que anuncia el regalo.

2) Abajo que quede el regalo solo abierto. Sin la torta. 

Con eso estamos.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahora?

**Comment by LeandroBraier** [comment]
Ahora está perfecto Brau!!

Confirmo con el cliente.

abrazo

**Comment by LeandroBraier** [comment]
Mientras aprovechá a hacer responsive la landing porfa.

**Comment by LeandroBraier** [comment]
Avisenme cuando esté online.

**Comment by braulio-evangelisti** [comment]
Lea ya Fede esta armando el template para que luego Marcelo lo conecte con el resto del sitio y ahi ya va a haber un link para poder verlo online dentro de Vendedores.

_cuando este el link final va a haber que ponérselo al mailing de cumpleaños, ahora esta apuntando a una carpeta "_prueba-cumple" donde esta la maqueta de vendedores que habría que borrar luego_

Abrazo

**Comment by LeandroBraier** [comment]
Genial Brau! Gracias!

Coordina con Fede para ayudarlo en todo lo que puedas hoy. Incluso
revisando el sitio de revear para ir rescatando los contenidos de la forma
mas prolija posible para poder subirlo a una nueva maquetación.

Abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA como quedó este tema? Cuando tengo todo final para enviar? 

Una vez hecho tengo que pedirle a @mkreyness que ponga el envío automático a cada uno en su cumpleaños.

**Comment by FAAREIA** [comment]
Hola Lea
Link estático: http://www.parexklaukol.com.ar/vendedores/cumple.html
Template: cumpleT.html
Al template habría que hacerlo funcionar y agregarle las variables que hagan falta. @mkreyness

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Antes de que agarre MK me parece que para el tema de las variables tendrías que incluir el nombre del usuario en la frase de "¡FELIZ CUMPLEAÑOS XXXXNOMBREXXX! No?

Con eso estaría porque en principio en abril el regalo va a ser una remera Klaukol para cada cumpleañero pero en Mayo puede cambiar, por lo cual yo haría una variable para el regalo que se pueda editar en el CMS.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo actualicé, también en el template.

**Comment by LeandroBraier** [comment]
Gracias Fede! Ahora si te toca a vos MK.

Puede ser para el lunes.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness necesito programar estos mailings y landings customizados a partir del 1 de abril. Me confirmás si llegamos?

**Comment by mkreyness** [comment]
Si, la cagada es que con todas estas cosas nunca arranco con lo de SiguitDS.

**Comment by LeandroBraier** [comment]
Lo entiendo, sí. No te preocupes, esto tiene prioridad. Lo de Siguit DS es
un emprendimiento a mediano plazo, vamos bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness dejá todo preparado pero tené en cuenta que me acaban de decir que van a pedir un par de cambios al html del mailing. No sé si eso afecta tu proceso o podés seguir y después incorporarlo pero te aviso por las dudas.

abrazo

**Comment by mkreyness** [comment]
no entiendo de donde sale lo del regalo.

**Comment by mkreyness** [comment]
Al HTML del mailing ya le agregue las variables. Por favor cualquier cambio @braulio-evangelisti hacelo sobre lo que ya esta en el server (mismo nombre).

**Comment by mkreyness** [comment]
otra cosa: necesito saber con que "Asunto:" mandar el mail.

**Comment by mkreyness** [comment]
@LeandroBraier ya esta agregado en el CMS una seccion "Regalos" donde definis año y rango de meses (asi no tenes que cargar 12 veces lo mismo si no varia).
Le puse para poner un texto y una foto, pero veo que en la maquetacion no esta previsto poner una foto. Lo dejo por si acaso.

El envio del mailing ya esta listo, pero el link DESDE el mail no me abre, copiando y pegando en el browser si. Capaz hay algo en la maqueta que hace que mi cliente de mail lo considere peligroso o algo asi.

Aca te copio el link de la landing tal como me llego en el mail (cortado para que no lo indexe Google):

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl?

usuario=marcelokreyness&clave=pepe

Igual ahora mando un mail de prueba que trae el mismo link a ver si a vos te abre con el click.

**Comment by LeandroBraier** [comment]
Recibido perfecto MK! Ahi te lo reenvié. Recibí todo perfecto, el link me funcionó bien. 

Solo que si bien vi el mail en mi INBOX, en el subject me apareció la palabra SPAM. Eso lo pusiste vos?

El subject del mail debería ser "¡Feliz Cumpleaños XXNOMBREXXX XXXAPELLIDOXXXX! ¡Abrí tu regalo!"

**Comment by mkreyness** [comment]
No, eso lo debe haber puesto algun antispam que tengas en tu cliente de mail, o que Duplika tenga instalado sobre el servidor de benteveo.tv.

Ahora le ajusto el subject y no te olvides de poner el texto de regalo correcto en el CMS.

**Comment by LeandroBraier** [comment]
Perfecto, MK. Entiendo. Ahi ya cambié eso en el CMS. Está muy bien armado
eso, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-23 11:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness funcionalmente está perfecto, pero le mandé al cliente y pidió cambios para @FAAREIA 
1. El texto hay que agrandarlo, se ve muy chico. 
2. Borrar "NO TE OLVIDES DE COMPARTIR TU REGALO...." 
3. Sacar lo que dice  "STAFF" poner el LOGO DE KLAUKOL (EN VEZ DEL DE LA COMUNIDAD DE VENDEDORES). 
4. Cuando clickeas el regalo que te muestre sólo el ticket y dentro del mismo (en letra chica) poner "te contactaremos para coordinar la entrega". 
5. Incluir en la plataforma un slide de CUMPLEAÑOS como el de GANADORES, donde todos los meses aparezcan los nombres y fechas de los cumpleañeros del mes. No hacen falta fotos porque son más de 40 por mes.

abrazo

**Comment by mkreyness** [comment]
toquen sobre los templates que estan en el server por favor (el de maiiing siempre esta en la carpeta de _mailing y el de la landing en templates/parexklaukol/vendedores/cumpleT.html

**Comment by FAAREIA** [comment]
Pregunta:
En http://www.parexklaukol.com.ar/cgi-bin/cumple.pl ya no va el regalo de abajo o también hay que sacar todo el párrafo de feliz cumpleaños?

**Comment by LeandroBraier** [comment]
Respuesta: No, eso dejalo tal cual, no hay problema.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/vendedores-cumple.html
http://www.parexklaukol.com.ar/cgi-bin/cumple.pl

Fijate si esta OK.
Con respecto al slide, te referías a una imagen para el slide o a una pantalla como la de ganadores? En caso de que sea la imagen podrían prepararla ustedes asi avanzo con todo lo otro?

Abrazo

**Comment by mkreyness** [comment]
No se cual sera el status de esto, pero por si acaso quiero recordar que no esta puesto automatico que se mande nada todavia. Avisame @LeandroBraier cuando ya deba ponerlo.

**Comment by LeandroBraier** [comment]
@FAAREIA estaba repasando esto, que debe ponerse automático a partir de este viernes.

El texto de "Nos contactaremos para coordinar la entrega" debe ir abajo del ticket chiquito, no en reemplazo del texto del regalo. Más como letra chica de legales. El texto de cual es el regalo dentro del ticket lo vamos definiendo nosotros desde el CMS. Lo demás está perfecto.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Esto porfa apenas lo tengas corregido avisame así lo puedo mandar al cliente. Dale prioridad porque es algo chiquito.

**Comment by FAAREIA** [comment]
Ahi lo actualicé:
http://www.parexklaukol.com.ar/cgi-bin/cumple.pl
La variable del texto de regalo la defini como `<!--texto-regalo-->`, si se llamaba de otra forma avisenme.
Abrazo

**Comment by LeandroBraier** [comment]
Excelente Fede! Mil gracias!

Después habria que hacerla con la cuenta de parex no? Para el envio posta.

**Comment by LeandroBraier** [comment]
@FAAREIA faltaría que @mkreyness le agregue el premio que subimos por CMS no?

**Comment by FAAREIA** [comment]
Creo que te confundiste de issue pero el form google tendría que estar en el @gmail que tenga parex argentina

**Comment by LeandroBraier** [comment]
Hablo del premio que va en el ticket.  El que dice "una remera Klaukol"

**Comment by FAAREIA** [comment]
Si sería una variable eso

**Comment by LeandroBraier** [comment]
Por eso. Pero ahora esta cargada la variable y no se muestra. Puede ser?

**Comment by mkreyness** [comment]
La variable se llama asi, texto-regalo, eso esta bien.
Pero tene en cuenta que el contenido depende del mes en que cumple años el usuario, con que usuario entras ? Solo hay premio definido para los que cumplen en abril y mayo (obvio eso se maneja desde el CMS, no es algo fijo, pero eso es lo que esta cargado)

**Comment by LeandroBraier** [comment]
Yo estoy entrando con el link genérico que me pasó Fede:

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl

Creo que no tiene usuario asignado. Tendría que buscar un usuario que cumpla en Abril no?

Por ejemplo este:

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl?

usuario=JorgeProsdocini

&clave=1041966

Asi que ya estamos.

abrazo

**Comment by mkreyness** [comment]
claro, asi son los links que van en el mailing. No te habia mandado un mail de prueba antes ?
Queres que te mande ?
Y avisame cuando ponerlo en produccion.

**Comment by LeandroBraier** [comment]
Dale, mejor. Mandame un mail de pruebas.

2016-03-31 15:38 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ahi te mande uno que cumple hoy. El programa solo manda los cumpleaños reales.

**Comment by mkreyness** [comment]
ojo, extendé en el CMS para que incluya marzo, porque si no va a quedarte sin texto.

**Comment by LeandroBraier** [comment]
@mkreyness el cliente cambió de opinión. Cambié en el CMS el premio a 1000 puntos extra en la Comunidad.

También creé el Tema y el Juego "PUNTOS POR CUMPLEAÑOS" que vale 1000 puntos. Así que lo que necesitaría es que le sumes esos 1000 puntos a todos los que cumplen de mañana en adelante, podrá ser?

Mientras sea dentro de la mañana estamos OK.

abrazo

**Comment by mkreyness** [comment]
O sea que al momento de mandarle el mail le sumo 1000 puntos via ese juego, lo cargaste como tipo "actividad" ?

**Comment by LeandroBraier** [comment]
Exacto! Está bien hecho asi?

**Comment by mkreyness** [comment]
Si, ya lo puse para que le sume 1000 puntos Y se lo canjee por 10 fichas.

**Comment by LeandroBraier** [comment]
Gracias MK!! abrazo grande

**Comment by LeandroBraier** [comment]
@FAAREIA necesitaría que apenas puedas le quites una frase a este mail.

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/vendedores-cumple.html

La frase a quitar es:

**"Nos pondremos en contacto para entregártelo."** 

Me confirmás porfa cuando esté?

**Comment by FAAREIA** [comment]
No esta esa frase en ese mailing, estas seguro?

**Comment by LeandroBraier** [comment]
En la landing a la cual lleva el mailing. No en el mailing.

**Comment by FAAREIA** [comment]
Necesito un usuario y contraseña para ver la landing

**Comment by LeandroBraier** [comment]
LeandroBraier

ParexKlaukol

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! Abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA tengo algo urgente. El cliente me dice que le siguen reclamando por la frase de "entrega".

Me fijo en este usuario y sigo viendo la frase que te pedí quitar:

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl?usuario=FabianRaffo&clave=parexklaukol179

Me cofirmás qué pasó? Necesito mostrarle al cliente un link donde no se vea la frase.

**Comment by mkreyness** [comment]
Es un texto que esta fijo en el template, queres que lo saque ?

**Comment by LeandroBraier** [comment]
Si, por favor Marce. Me había dicho Fede que lo había sacado y yo ya le
había dicho al cliente. Sacalo urgente porfa y confirmame cuando esté hecho
así lo pruebo.

abrazo

**Comment by mkreyness** [comment]
lo que pasa es que hablaban de una landing, y no se si habra ido al template. Ya lo saque, fijate.
Igual se ve raro ese ticket vacio ahi.

**Comment by LeandroBraier** [comment]
SI, no te preocupes. Ahi me di cuenta por qué aparecia vacío, el regalo llegaba hasta el mes pasado. Ya lo puse que aplique hasta diciembre pero todavia no aplicó.

Es por el delay en el refresh de la página?

**Comment by mkreyness** [comment]
no, la pagina no se regenera, es dinamica. Estas seguro que este tipo cumple en julio ?

**Comment by LeandroBraier** [comment]
No, cumple en Junio este tipo en particular. Pero a los de Julio tampoco los veo.

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl?usuario=AbrahamMarioLokman&clave=Construyendo257

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl?usuario=RodolfoSergioBarro&clave=Rody123

Lo que necesitaría es que anden. No sé por qué no me aparece el mensaje. Me pasás un link donde a vos te ande?

**Comment by mkreyness** [comment]
Pero vos tendras una bola de cristal para saber que esos tipos nacieron en julio, porque no tienen ninguna fecha de nacimiento cargada.

**Comment by mkreyness** [comment]
Lokman esta cargado 2 veces. Una vez no tiene fecha (la que tiene el codigo que me pasaste en el URL), y la otra dice que nacio en abril.

**Comment by mkreyness** [comment]
Rodolfo Barro tambien esta cargado dos veces, en una nunca nacio y en otra nacio en abril

**Comment by mkreyness** [comment]
Esta lleno de gente duplicada, porque en una estan con un nombre del medio y en otra no, entonces se le generaron dos codigos diferentes, aunque tienen el mismo mail.

**Comment by mkreyness** [comment]
Aca tenes a alguien que verdaderamente cumple en julio

http://www.parexklaukol.com.ar/cgi-bin/cumple.pl?usuario=LorenaBaritoz&clave=31071979

**Comment by LeandroBraier** [comment]
Genial, me quedo más tranquilo por un lado. Por el lado de que a los tipos les están llegando bien los cumpleaños.

Ahora: esa doble base me preocupa un poco más. Yo cuando descargo del CMS esos usuarios me aparecen 1 sola vez. Recién rechequeé a RodolfoSergioBarrio y FabianRaffo.

De todas formas no es urgente ahora. Con lo que me pasaste me alcanza para responderle al cliente.

Muchas gracias!

**Comment by mkreyness** [comment]
Obvio el codigo esta una sola vez, pero si buscas solo por el apellido Barro (no Barrio) y el otro Lokman, vas a ver que estan dos veces, con distinto codigo.
