### ISSUE TITLE
Tarjetas de Socio en Club de Colocadores. 04/03

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#273]
@FAAREIA y @braulio-evangelisti necesito que sumen a la página de "Mi perfil" la tarjeta de socio con el número de socio que aparece en el Mailing de Bienvenida de Club de Colocadores.

Me confirman si llegan para el viernes porfa?

abrazo

**Comment by FAAREIA** [comment]
Me pasarías el link al último mailing de bienvenida? Asi veo la tarjeta

Abrazo

**Comment by braulio-evangelisti** [comment]
Creo que es este
http://www.parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida.html

**Comment by FAAREIA** [comment]
@mkreyness Marce, ahora lo voy a agregar al template con la variable `<!--socionum-->`, cualquier cosa después lo cambiamos.

**Comment by FAAREIA** [comment]
Hecho, cuando @mkreyness meta las variables de nombre-apellido y numero de socio, meto el código HTML en el template.
El pedazo de código va a ir debajo de la imagen y será asi:
`<div class="socio"><div class="textos"><p>Nombre apellido</p> <small>213123123213</small></div></div>`

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede! Avisen nomas.

**Comment by mkreyness** [comment]
Listo !

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

@FAAREIA el número no dice arriba Número de Socio. Debería decirlo, porque sino no se entiende y necesitamos que ellos sepan donde está su número de socio. Para mi vas a tener que mostrar la tarjeta en un tamaño más grande para lograr eso.

**Comment by FAAREIA** [comment]
Ahi le puse "N° SOCIO:"
Fijate como quedó, entró perfecto en la línea del número.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA !! Gracias!!

**Comment by LeandroBraier** [comment]
@FAAREIA quieren que la tarjeta de socio esté más al frente. La podemos poner en la home arriba de "Tu perfil"?

**Comment by FAAREIA** [comment]
Hecho, ahora la tarjeta de socio esta en en el perfil y en la columna derecha de todo el sitio. Solo es visible para usuarios registrados.
@mkreyness habría que hacer andar las variables esas en la columna derecha. ¿aca hay un template para cambiar el versioning al css en todo el sitio?
Una vez hecho eso, pongo visible la tarjeta.

**Comment by LeandroBraier** [comment]
@FAAREIA necesito que esto quede funcional hoy. Me confirmás porfa?

**Comment by FAAREIA** [comment]
Hola Lea, ahi le aviso por whatsapp a marce

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by mkreyness** [comment]
Ahi lo puse en produccion

**Comment by LeandroBraier** [comment]
Impecable chicos!!! Muchas gracias!!!

abrazo
