### ISSUE TITLE
Vendedores y Colocadores: agregar Género en Formulario de Registración. 07/03

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#274]
@FAAREIA y @braulio-evangelisti necesito que incorporen el campo de género (Hombre, Mujer, Otros) en el formulario de registración y de perfil de Vendedores y de Colocadores. Tal como está en la Comunidad VIE TUR.

abrazo

**Comment by braulio-evangelisti** [comment]
@LeandroBraier el campo genero no esta en el registro de vietur, esta solamente en la pagina de edicion del perfil. Lo agrego en el formulario de registro?

**Comment by LeandroBraier** [comment]
No hace falta Brau. Por ahora no, gracias!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-03 9:03 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya esta el combo select de sexo en el registro y perfil de Colocadores y en el perfil de Vendedores, el cual no tiene registro.
En vendedores no pude entrar con el usuario de siempre de marce por lo que no pude ver como quedó pero no debería haber problemas.
@mkreyness habría que agregar que el registro de Colocadores tome el campo sexo y luego lo correspondiente al perfil. En vendedores lo mismo.

**Comment by mkreyness** [comment]
vendedores: el usuario es el de siempre pero la password es "papa" en vez de "pepe".
Ya tocaste los verdaderos templates de perfil  (en vendedores y colocadores) y el de registro en colocadores ?

**Comment by FAAREIA** [comment]
asi es, esta todo online. En el perfil de colocadores la línea que muestra la tarjeta de socio esta comentada

**Comment by mkreyness** [comment]
ahi lo puse en el de perfil de vendedores, despues a la tarde lo paso al de colocadores

**Comment by LeandroBraier** [comment]
Gracias! Avisame cuando esté nomás.

**Comment by mkreyness** [comment]
si, ya esta hecho desde el viernes a la tarde (la tarde del dia que dije "despues a la tarde").

**Comment by LeandroBraier** [comment]
Promesas cumplidas!! Que buen lunes!! jajaj abrazo grande y gracias!
