### ISSUE TITLE
Versión Offline del Torneo de Potenciados. 03/03

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#275]
@FAAREIA me enviás una versión offline de la maquetación del torneo?

La necesitamos para ofrecerlo como producto a nuevos clientes

abrazo

**Comment by FAAREIA** [comment]
Hubo muchas modificaciones y lo que esta online no lo tengo maquetado sin funcionalidades. Habría que poner el sitio online y bajarse la maqueta para tener la última versión. Luego de bajada, se pone offline.

**Comment by FAAREIA** [comment]
@mkreyness Se podrá poner online marce?
@LeandroBraier qué usuario van a querer mostrar?

**Comment by LeandroBraier** [comment]
Gracias Fede. Intentamos subirlo brevemente solo para poder bajarse la
maqueta. Es para ofrecerlo a nuevos clientes. Igual le consulto a Eze si
vale la pena tanto esfuerzo.

Usuarios: Necesitaría poder mostrar un usuario de distribuidor y uno de
representante comercial.

**Comment by LeandroBraier** [comment]
buen día @FAAREIA ! Avisame cuando lo tengas porfa. abrazo

**Comment by FAAREIA** [comment]
Ok, ahi le pregunto a marce

**Comment by mkreyness** [comment]
Representante:

http://www.parexklaukol.com.ar/cgi-bin/extorneo-con-slide.pl?usuario=JavierVasquez&clave=parexklaukol 

Distribuidor:

http://www.parexklaukol.com.ar/cgi-bin/extorneo-con-slide.pl?usuario=ceramisur&clave=parexklaukol

**Comment by FAAREIA** [comment]
Lea ahi estan las maquetas, sin funcionalidad pero en HTML.
http://www.parexklaukol.com.ar/torneo-de-potenciados/representante.html
http://www.parexklaukol.com.ar/torneo-de-potenciados/distribuidor.html

@mkreyness ya podes poner offline el torno.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias chicos!!

**Comment by mkreyness** [comment]
en realidad ese URL "ex-torneo" nunca fue publico ni accesible, lo deje asi por si acaso.

**Comment by LeandroBraier** [comment]
Gracias a los dos!!! abrazo
