### ISSUE TITLE
Reemplazar Fichas Técnicas en Web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#276]
@braulio-evangelisti de acá al lunes subirías estas dos fichas técnicas a la web?

[Ficha Tecnica_PORCELLANATO FLUIDO.pdf](https://github.com/LeandroBraier/Klaukol/files/159363/Ficha.Tecnica_PORCELLANATO.FLUIDO.pdf)
[Ficha Tecnica_KLAUKOL GRANDES PIEZAS PORCELLANATO.pdf](https://github.com/LeandroBraier/Klaukol/files/159364/Ficha.Tecnica_KLAUKOL.GRANDES.PIEZAS.PORCELLANATO.pdf)

abrazo

**Comment by braulio-evangelisti** [comment]
Hecho!

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti ! abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti me pidieron ahora subir esta:

[FT_Parex_DECOFLEX Imprimacion_051113.pdf](https://github.com/LeandroBraier/Klaukol/files/165897/FT_Parex_DECOFLEX.Imprimacion_051113.pdf)

Corresponde a este producto:

http://www.parexklaukol.com.ar/parex/parex-decoflex-fondo.html

Me confirmás porfa cuando esté subido? Puede ser mañana.

abrazo

**Comment by braulio-evangelisti** [comment]
@FAAREIA

**Comment by FAAREIA** [comment]
Hecho:
http://www.parexklaukol.com.ar/parex/parex-decoflex-fondo.html

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!!

**Comment by LeandroBraier** [comment]
@FAAREIA  tengo una nueva ficha técnica para reemplazar la de Klaukol Porcellanto Fluido. Puede ser mañana tranqui.

[FT_Klaukol_porcellanato fluido.pdf](https://github.com/LeandroBraier/Klaukol/files/207283/FT_Klaukol_porcellanato.fluido.pdf)

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!!
