### ISSUE TITLE
Nuevos Usuarios en Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#278]
Buen día @mkreyness !

Acabo de agregar 2 vendedores a la Comunidad de Vendedores de Parex desde el CMS y les puse de status MANDAR MAIL.

Se mandan automáticos o vos lo gatillás?

COnfirmame porfa.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness ya se enviaron estos mails? Sino envialos urgente porfa.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @mkreyness se sabe algo de esto? Necesito confirmar si se enviaron estos mailings. Abrazo

**Comment by mkreyness** [comment]
se me pierden estas cosas sueltas, @LeandroBraier, ni las veo entre tantos mails.
Si se hubieran mandado solas, habrian cambiado el status de MANDAR MAIL a otra cosa, y por lo que veo siguen ahi. No, no hay nada automatico porque siempre volcamos a mano estas cosas, no hay registracion. Ahora los hago salir.

**Comment by LeandroBraier** [comment]
Veo que no quedó nadie en Mandar Mail así que cierro este ticket. Gracias MK!

**Comment by mkreyness** [comment]
Si, el asunto es que si cargas nuevos me avises que active puntualmente la salida de esos mails, no lo quiero dejar automatico porque si no si cargo un excel se me dispararian solos antes de poder revisar si esta ok, o si hay otro mailing saliendo.

**Comment by LeandroBraier** [comment]
Dale, me parece bien. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-23 11:45 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness tengo un excel con 25 nuevos usuarios para la Comunidad de Vendedores. Podés subirlo automático o los cargo a mano y te aviso?

**Comment by mkreyness** [comment]
nunca es totalmente automatico, siempre tengo que hacer formulas con el excel, modificar cuando en el apellido hay comillias (tipo "D'Agostino"), etc.  Pero pasamelo, no hay problema.

**Comment by LeandroBraier** [comment]
Claro, por eso te preguntaba. Entonces dejá, no te preocupes. Los cargo yo. Prefiero que no tengas que hacer esos trabajos.

Te aviso cuando ya estén subidos.

abrazo

**Comment by mkreyness** [comment]
Ok, tene en cuenta que si queres que les vaya mail de bienvenida tenes que ponerlos en el estado "MANDAR MAIL" y  avisarme cuando hayas terminado asi los disparo.
Si no ponelos directamente en "ACTIVO".

**Comment by LeandroBraier** [comment]
Dale, perfecto. Los pongo en MANDAR MAIL y te aviso.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness ya están listos para hacer MANDAR MAIL. 

Confirmame cuando estén enviados porfa.

abrazo

**Comment by LeandroBraier** [comment]
Pará pará. Todavía no.

**Comment by LeandroBraier** [comment]
Ahora si MK! Mandalos nomas cuando puedas. abrazo

**Comment by mkreyness** [comment]
saliendo

**Comment by LeandroBraier** [comment]
Gracias MArce!!!
