### ISSUE TITLE
Adaptación Mailing de Bienvenida Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#279]
Brau, necesito que mañana como prioridad del día hagas una nueva versión de Mailing de Bienvenida de Club de Colocadores. Que arriba como header tenga esta promoción:

![3 slide - concurso club de colocadores](https://cloud.githubusercontent.com/assets/6719872/13788134/6d1d3290-eabd-11e5-97a7-01fd2c3dd83d.jpg)

Queremos decirles a los Colocadores del Club que participando de este concurso pueden ganar radios, remeras y gorras de Klaukol. 

Arriba, agregale el logo del Club de Colocadores y en lugar de decir "Participá y Ganá" tiene que decir "Respondé correctamente esta pregunta y participá por radios, remeras y gorras Klaukol".

Abajo en lugar de "Suscribite" que diga: "Respondé este mail con tu respuesta para participar del sorteo."

En este wetransfer tenés el editable. 

https://www.wetransfer.com/downloads/3f2ba71bd17155052c27a31bc96f2c2820160315200839/a2b545725e67a2226c38a04b061382f420160315200839/8eb585

Lo podrás tener para mañana tipo 11 am?

Confirmame porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea ya estoy bajando el psd, apenas tenga algo lo subo, calculo que llego para las 11.

**Comment by LeandroBraier** [comment]
Genial Brau!! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Tenes esta fuente para pasarme?

**[FrutigerLTStd BlackCn]**

Gracias

**Comment by LeandroBraier** [comment]
Si! Aqui van todas.

abrazo

[Fuentes Frutiger LT Std.zip](https://github.com/LeandroBraier/Klaukol/files/175787/Fuentes.Frutiger.LT.Std.zip)

**Comment by braulio-evangelisti** [comment]
Fijate algo asi 

http://www.parexklaukol.com.ar/_mailing/colocadores-bienvenida/colocadores-bienvenida-0316.html

**Comment by LeandroBraier** [comment]
Bastante cerca Brau! Buenisimo! 

Te paso feedback:

1) Reemplazar el texto "¡Bienvenido al Club de Colocadores Klaukol!" por "Club de Colocadores te invita a participar de este concurso"

2) El texto: "RESPONDÉ CORRECTAMENTE ESTA PREGUNTA Y PARTICIPÁ POR RADIOS, REMERAS Y GORRAS KLAUKOL" ponele en fuente más grande, como la de la frase anterior.

3) Agrandar un poco los premios, que se vean más.

4) Quitar esta parte: "Ya formás parte del Club donde se reúnen los que más saben. En este espacio te vas a poder capacitar para perfeccionar tu trabajo, intercambiar consejos y divertirte obteniendo grandes beneficios junto a los mejores colocadores del país."

5) Quitar las palabras "A partir de ahora" de la frase: "A partir de ahora ya tenés tu carnet de pertenencia al club y podés ingresar online haciendo clic en el siguiente acceso especial:". 

Quedaría así:

"Ya tenés tu carnet de pertenencia al club y podés ingresar online haciendo clic en el siguiente acceso especial:"

6) Arriba de la frase anterior incluir el Carnet que enviamos siempre en este mailing de bienvenida (no sé por qué lo sacaste en realidad)

7) Una vez hechos estos cambios mandame el link actualizado para que lo haga aprobar con el cliente.

@FAAREIA una vez aprobado voy a necesitar que creen el template para este mailing en Mailchimp. Una vez hecho ese necesito que creen el template para el mailing normal de bienvenida también.

abrazo

**Comment by braulio-evangelisti** [comment]
Actualiza ahora en el mismo link.

**Comment by LeandroBraier** [comment]
Perfecto @braulio-evangelisti !! Muchas gracias!!!

@FAAREIA mejor no lo mando al cliente. Está impecable el mailing. Pasemoslo a Mailchimp directamente. Avisame porfa.

abrazo

**Comment by FAAREIA** [comment]
https://us11.admin.mailchimp.com/templates/design?tid=209845
Variables que usé:
- USUARIO
- CLAVE
- NOMBRE
- APELLIDO
- NUMERO

Fijate que cuando crees las variables, tienen un nombre por defecto pero vos podes definirle un alias. El alias serían los nombres que te pase.

**Comment by LeandroBraier** [comment]
Genial Fede! Impecable!

Ok, lo tengo en cuenta. El número se lo sumo como columna en la lista no?

**Comment by FAAREIA** [comment]
Fijate que hay una columna para definir un alias, sino le cambias ese nombre que te da por defecto

**Comment by LeandroBraier** [comment]
Entiendo, perfecto. Gracias Fede!

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Necesito una modificación sencilla en este mailing.

Lo que necesito es que me cambies la pregunta: 

"¿CUÁL ES EL ADHESIVO CORRECTO PARA COLOCAR PIEZAS DE BAJA ABSORCIÓN SOBRE SOPORTES TRADICIONALES?

por

"¿CUÁL ES EL ADHESIVO DE KLAUKOL IDEAL PARA COLOCAR VENECITAS?

Solo eso. Puede ser para mañana.

abrazo

**Comment by LeandroBraier** [comment]
No te olvides de modificarlo en Mailchimp también.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo cambié en los dos, dale F5

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
