### ISSUE TITLE
ParexKlaukol Versiones 1.0

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#28]
Fede, avancemos con la estética aprobada en todos los sitios que requieren restyling:

. ParexKlaukol Argentina (Klaukol/Parex/Lanko)
. ParexKlaukol Uruguay (Klaukol/Parex/Lanko)
. ParexKlaukol Paraguay (Klaukol/Parex/Lanko)

Lo único que hay que hacer es cambiar el video actual por otro con una mínima corrección. Bajalo de acá:

https://www.wetransfer.com/downloads/19ea7dc06dacf6b1139790ec789e8de920150423202006/8f97e2

Esto lo podremos tener hecho para el domingo? Si fuera así sería genial. Sino para el lunes perfecto también, así ya el lunes pasamos los DNS para hacer la delegación final.

abrazo

**Comment by FAAREIA** [comment]
Yo creo que si puede estar en un estado muy avanzado. Adjunto a Marce asi le mete pata a esto. Igual hoy voy a estar tocando algun template de los que me pidió

**Comment by LeandroBraier** [comment]
Excelente. Así lo veo el domingo ya en estado muy avanzando y le mando todo
a Marce Susevich para que el lunes él gestiona la delegación final a los
sitios 1.0

Los DNS a delegar serían estos, no?
- ns1.duplika.com / 199.102.230.88
- ns2.duplika.com / 50.28.56.141

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-23 17:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Marce, me confirmás esto por favor?

Así le puedo dejar los pasos completos a Eze y Marce.

**Comment by LeandroBraier** [comment]
Lo que me genera dudas es si usamos los mismos DNS como hacemos que de Uruguay vean una cosa y de Paraguay otra?

Te puedo llamar?

**Comment by mkreyness** [comment]
Si son tres dominios, cada dominio apunta a una carpeta diferente.
Yo ya estoy previendo que van a existir esas carpetas porque lo estoy 
teniendo en cuenta para los CMS.
Pero desconozco el enfoque que le este dando Fede al tema con los otros 
sitios.

**Comment by LeandroBraier** [comment]
Buen día Fede! Estoy partiendo de viaje. Les quiero agradecer por todo el esfuerzo y dedicación que le vienen poniendo. Ya me reuní con Eze y está al tanto de todo. Hoy cuando tengan los sitios se los pasan a él y cualquier cosa lo hablan con él.

abrazo grande y hasta la vuelta!
