### ISSUE TITLE
Bug en Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#280]
@mkreyness subí un juego de video en Club de Colocadores y mirá como se ve:

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?usuario=marcelokreyness&clave=pepe&id=16

**Comment by mkreyness** [comment]
Porque todos los elementos que no se ven forman parte de las clases CSS, no es nada especifico de este template, @FAAREIA podes pegarle una mirada ? O se rompio algo o nunca anduvo, es la primera trivia con video @LeandroBraier ?.

**Comment by LeandroBraier** [comment]
No, ya hicimos esto para episodios 1 y 2

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?usuario=marcelokreyness&clave=pepe&id=13

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?usuario=marcelokreyness&clave=pepe&id=14

Y antes se veía bien también. En algún momento esto se rompió.

**Comment by FAAREIA** [comment]
Este tempate nuevo no tiene relación con la lógica de las maquetas armadas en lo nuevo de colocadores. Me fije y en las maquetas no hay template para un juego, me parece raro que esto antes se veia bien.
Ahi lo agrego

**Comment by FAAREIA** [comment]
Solucionado

**Comment by LeandroBraier** [comment]
Gracias Fede! Ahora se ve mejor.

El problema es que el Club de Colocadores no tiene puntos, te acordás? Los usamos para saber qué actividades hicieron nada más, pero no en el front. No se tiene que leer "Compartí y sumá mundo" y demás. 

Como ya hicieron para las trivias:

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?usuario=marcelokreyness&clave=pepe&id=2

**Comment by FAAREIA** [comment]
Se confundieron de template entonces, lo que se tiene que ver es el título y el video entonces? Tiene que haber algun botón que lleve a una trivia o algo asi? Texto del botón?

**Comment by FAAREIA** [comment]
el compartir sigue?

**Comment by LeandroBraier** [comment]
Si se puede si pero sin el texto de puntos.

**Comment by FAAREIA** [comment]
Fijate ahora lea.

**Comment by LeandroBraier** [comment]
Ahora dice "Mirá el video y respondé la siguiente trivia".

Pero no hay trivia.

Revisalo en este link para verlo en front:

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?usuario=marcelokreyness&clave=pepe&id=14

**Comment by FAAREIA** [comment]
Ok, ya estoy medio mareado. Ahi le saqué el botón ese. Esta bien ahi?

**Comment by LeandroBraier** [comment]
Si, ahora está bien eso. jeje

Pero no sé por qué no anda el botón de compartir. Se fijan eso @mkreyness ?

abrazo

**Comment by mkreyness** [comment]
dice "picture is not properly formatted".
La imagen es esta y yo no le veo nada de malo, pero capaz no se banque png ?

http://www.parexklaukol.com.ar/colo/img/temas/2-Thumbnail-EquipoKlaukol.png

**Comment by LeandroBraier** [comment]
Pero el compartir es para compartir el video, o no?

**Comment by mkreyness** [comment]
Todo link de compartir deberiai llevar una foto, si no Facebook busca lo que haya en la pagina general de Klaukol y lo pone. Igual tampoco hay mucha garantia que la use, lo mejor seria que todos estos templates tuvieran los tags de Facebook (og:) que NO tienen.

El video deberia ser el URL de lo que se comparte, pero no esta apareciendo. Ahora arreglo eso.

**Comment by mkreyness** [comment]
Lo que se comparte es lo que en el tema pongas en el campo "URL".
Ahi le copie el URL del video ahi y ya lo pone bien, pero sigue estando el problema de la imagen, no le gusta ese png.
Si queres le saco lo de que use una imagen, y pondra lo que encuentre por default.

**Comment by LeandroBraier** [comment]
Ok, probemos asi MK. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
sale bastante bien, pone la imagen del video en el post, fijate.

**Comment by LeandroBraier** [comment]
Si, ahí está perfecto MK!! Ya lo subí a los 3 episodios.

Gracias a los dos!!

abrazo
