### ISSUE TITLE
Guía Interactiva Revear 29/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#281]
@FAAREIA y @mkreyness además del sitio web de Revear, nos pidieron convertir el actual buscador de distribuidores del sitio en una Guía Interactiva como la Guía de Corralones.

Para esto tendríamos que: 
1. Generar una copia de la Guía de Corralones
2. Reemplazar los datos de corralones por los de distribuidores Revear que tenemos en el CMS
3. Cambiar la estética de la Guía de Corralones por una Nueva estética, bien alineada a la nueva web de Revear. El logo lo voy pidiendo a nuestros diseñadores para ganar tiempo.

Espero cofirmación por si llega a haber algo que no estoy contemplando acá.

La fecha de entrega es conjunta con el restyling de la web de revear pero si consideran que puede estar antes mejor. Si requiere más tiempo aclaren por qué y organicemonos un poco.

abrazo

**Comment by mkreyness** [comment]
en principio no habria mayor inconveniente salvo que me parece que de los distribuidores no hay fotos.
En cuanto a la obtencion de los datos de la base yo para la ACTUAL de revear ya estoy haciendo algo similar a lo que hago para la actual de corralones.

**Comment by LeandroBraier** [comment]
Genial! Si, me acordaba que habías hecho algo así, por lo que de programación no va a llevar mucho, no?

En cuanto a las imágenes no te preocupes. Los corralones Klaukol tampoco tienen y sigo esperando la aprobación de las fotos subidas por vendedores desde hace 1 año por parte del cliente.

abrazo

**Comment by FAAREIA** [comment]
Va a ser una landing aparte o una página interna con un poco más de power?
Para definir su estética vamos a tener que avanzar con el diseño del sitio asi después sale más fácil

**Comment by LeandroBraier** [comment]
Dale, me parece bien Fede. Yo voy avanzando con el logo que parece pavo
pero lleva tiempo.

Hagámoslo como la Guia de Corralones, que funcione de forma independiente
con su propia url, pero conservando la estética de la web de Revear para
que se pueda percibir también como una subpágina de Revear.

abrazo

**Comment by FAAREIA** [comment]
ok, entonces hay que mantener el menú o el encabezado entero asi se puede volver a cualquier sección del sitio.

**Comment by LeandroBraier** [comment]
No hace falta eso. Con un link a la web de Revear visible estamos bien.
Puede ser incluso en el logo de la Guía y abajo al pie.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@mkreyness el lunes voy a tener el Logo. Si se los paso el lunes cuando podemos tener subida la guía?

**Comment by mkreyness** [comment]
ni idea, donde esta la maqueta ?

**Comment by mkreyness** [comment]
Si esta todo maquetado igual que el de corralones y solo hay que cambiarle el URL de donde toma los datos, es muy simple, pero tengo que ver la maqueta.

**Comment by LeandroBraier** [comment]
Copio a @FAAREIA por esto.

**Comment by FAAREIA** [comment]
Cuando este el logo lo empiezo al diseño, luego de aprobado se maqueta. El diseño podría estar en la semana pero su aprobación no sé, con algunas cosas tardan banda en verlas

**Comment by LeandroBraier** [comment]
Asi es Fede. El logo te lo paso hoy mismo, así esta semana seguro ya
mandamos el diseño. Y ahi quedamos a disposición del feedback.

abrazo

2016-04-18 11:48 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Acordate del logo lea
Abrazo

**Comment by LeandroBraier** [comment]
Si, Fede. Gracias por recordar! Calculo que hoy te lo paso, viene medio
atrasado de diseño la versión final.

**Comment by LeandroBraier** [comment]
@FAAREIA disculpame la demora. Todavía no está confirmado el Logo. Espero mañana poder confirmartelo. Te voy pasando un adelanto para que tengas en cuenta que la idea es que todo sea igual a la Guía de corralones salvo el logo de arriba y el fondo, que va a ser de color negro. Este logo no es el final. De hecho va a ser más vertical, como el de la Guía de Corralones.

![logo01-2-01](https://cloud.githubusercontent.com/assets/6719872/14838656/d79c47ca-0bf9-11e6-8b4a-ba933b52a1dc.png)

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA te paso el logo aprobado final.

![logo01-7](https://cloud.githubusercontent.com/assets/6719872/14900086/57662518-0d65-11e6-84fe-5cb7a64b13b2.png)

Nosotros lo vemos mejor con el fondo con esa textura tipo Revear en blanco, pero si querés mantener el negro de fondo porque te parece que queda mejor mantengamoslo.

Confirmame si podemos tener esta adaptación para la semana que viene. Posiblemente el miércoles 4 de mayo.

**Comment by FAAREIA** [comment]
Tendrían el logo vectorizado? o escalable?

**Comment by FAAREIA** [comment]
Lo que noto en el logo y va a pasar en el sitio, es que "Guía de puntos de venta" esta muy chico con respecto a "Revear". Ya el logo es MUY vertical lo cual va a complicar para monitores de poca altura como una laptop comun de 1366x768. Agrandarlo para que se lea "Guía de puntos de venta" no me parece la solución, en el screenshot adjunto el logo ocupa 326px de alto, casi la mitad de la resolución común de una laptop. Habría que "fixear" ese tema.

![sin-titulo-1](https://cloud.githubusercontent.com/assets/6184969/14916626/1ef6c0d4-0df1-11e6-8d34-58098c02444c.png)

**Comment by LeandroBraier** [comment]
Entendido Fede! Te paso en un ratito la versión ajustada. En qué formato lo preferís? PNG transparente?

Qué te pareció la idea del fondo texturado de la izquierda? Se puede o es un lío?

**Comment by FAAREIA** [comment]
El logo no tiene que estar con textura de fondo, pasenmelo en png 24 en alta.
Algunas detalles mejorados:
* El buscador esta horizontal, eso facilita las cosas para mobile. Además queda más prolijo.
* El logo lo corté asi nomás, pero el tamaño sería ese.
* La vista de "Listado" la simplifiqué en una tabla. La info se ve mejor, más organizada y evitamos ese tema de poner la foto del local, que en la guía de corralones no funcionó y no hay 1 foto del frente del corralón.


![guia-de-puntos-de-venta](https://cloud.githubusercontent.com/assets/6184969/14923546/344a2868-0e14-11e6-882c-913b141b3abb.png)
![guia-de-puntos-de-venta-2](https://cloud.githubusercontent.com/assets/6184969/14923547/3468f8d8-0e14-11e6-810d-801904db8471.png)
![guia-de-puntos-de-venta-3](https://cloud.githubusercontent.com/assets/6184969/14923548/349cad54-0e14-11e6-9207-6e0791e9967e.png)

**Comment by LeandroBraier** [comment]
Está buenisimo Fede!!!

Justo para la de Klaukol vamos a empezar a subir fotos pronto pero para este guía no, así que estamos perfectos para Revear. Quedó buenísimo. Gracias!

Acá te paso el logo como me lo pedís y en más alta calidad por las dudas:

![logoguia-revear-final](https://cloud.githubusercontent.com/assets/6719872/14924204/ad1ea248-0e17-11e6-875e-d7677bb17f31.png)
![logoguia-revear-final-alta](https://cloud.githubusercontent.com/assets/6719872/14924203/ad1e712e-0e17-11e6-8c04-093bb8ad71d1.png)

abrazo

**Comment by FAAREIA** [comment]
Ahi actualicé las pantallas con el logo transparente e hice unos pequeños ajustes/cambios.
El post anterior lo borre asi no ocupa tanto espacio el post.

![guia-de-puntos-de-venta](https://cloud.githubusercontent.com/assets/6184969/14954764/5ca7d8ee-104b-11e6-9af6-095717359bd2.png)
![guia-de-puntos-de-venta-2](https://cloud.githubusercontent.com/assets/6184969/14954765/5caaf588-104b-11e6-8e3c-77bc88aa6026.png)
![guia-de-puntos-de-venta-3](https://cloud.githubusercontent.com/assets/6184969/14954766/5cad57ce-104b-11e6-9740-0c3c04da2c19.png)

**Comment by LeandroBraier** [comment]
Quedó buenisimo! Querés que lo mande al cliente para aprobar o ya avanzamos?

**Comment by LeandroBraier** [comment]
Se lo mando y te digo.

Aprovecho a consultar: chequearon la geolocalización de la guía con Mobile? Yo probé en SAMSUNG Android y no me funcionó. Testeen forma que funcione bien.

abrazo

**Comment by LeandroBraier** [comment]
Los diseños están OK Fede! Avancemos!

Solo me pidieron que no olvidemos incluir links a los puntos de venta en la lista de puntos de venta encontrados. Sería una columna más y clickeable.

Consulta:SI hago clic en la ubicacion del punto de venta dentro del mapa, me aparecería una imagen del mismo si la subo en el cms?

**Comment by FAAREIA** [comment]
Qué link es el del punto de venta? el sitio web?
Con respecto a la imagen si marce lo prepara si se podría, y creo que hasta ya esta programado para eso.

**Comment by LeandroBraier** [comment]
Perfecto. Si el link es la pagina web. Hay un campo para eso en el cms.

**Comment by FAAREIA** [comment]
Si, de hecho el nombre del local podría llevar el link al sitio, su dirección a un google maps y el telefono que sea un link que llame, lo cual solo funcionaría en mobile.

**Comment by LeandroBraier** [comment]
Excelente eso! Todavia mejor!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Cómo venís con este @FAAREIA ? Lo podremos mostrar mañana online?

**Comment by FAAREIA** [comment]
Hola Lea, todavía no la empecé y no creo que lo haga hasta el final ya que sería como algo "adicional" del sitio. Si queres la hago después del home, avisame

**Comment by LeandroBraier** [comment]
Buen día Fede! Decime porfa en qué tiempos tenemos cada cosa porfa así te
puedo ordenar las prioridades. Hoy tenemos la Home lista? Podríamos tener
para mañana el resto de la web Revear?

Si estás muy jugado dale prioridad a la web antes que a la Guía, pero
habíamos hablado de tener todo listo hoy te acordás? Esta semana al menos.
Confirmame porfa porque el cliente me está muy encima con esto.

2016-05-11 9:03 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, le doy prioridad a la web. El tema de los tiempos, te había dicho el 5 mayo ([ver post](https://github.com/LeandroBraier/Klaukol/issues/254#issuecomment-217162785)) que me va a llevar unas cuantas horas. Desde el 5 de mayo a hoy inclusive solo pasaron 20hs. Es imposible tenerla para hoy, aun si no tuviese otros clientes que atender.
Estoy avanzando rápido y mañana puede estar el home pero la semana que viene va a estar el sitio y sin responsivo.

**Comment by LeandroBraier** [comment]
@FAAREIA por las dudas ya que hubo varios malentendidos de fechas. Esto va a estar junto con la web, verdad? Yo tengo que entregar todo junto.

**Comment by FAAREIA** [comment]
Claro, el viernes estaría listo o antes. El tema es que esta semana se terminan las maquetas. El tema es preguntarle a marce si llega a hacerlo el mismisimo día =/. @mkreyness

**Comment by mkreyness** [comment]
Yo el viernes recien puedo hacer algo a partir de las 4 de la tarde.

**Comment by LeandroBraier** [comment]
Ok, Fede, si podemos tener el jueves así MK lo agarra antes genial. La idea
era entregarle al cliente el viernes para que apruebe y salir el viernes.

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA usemos este ticket para tema Guía de Puntos de Venta, así no mezclamos.

Yo la veo así ahora, en maquetación faltan ajustes o por qué se tapa el texto y el botón debajo del header?

<img width="1400" alt="captura de pantalla 2016-05-23 a las 1 23 01 p m" src="https://cloud.githubusercontent.com/assets/6719872/15476613/63a88b92-20e6-11e6-9a69-edc94218824c.png">

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness a qué hora podemos tener mostrable esto y en qué link?

Gracias
