### ISSUE TITLE
Distintivos para Usuarios Vendedores Super Potenciados en Tu Perfil. 30/3

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#283]
@FAAREIA para la semana que viene necesitaríamos subir un distintivo a los usuarios que tienen más de 2500 puntos. Automáticamente cuando un usuario supera los 2.500 puntos debería sumársele este distintivo de Vendedor SuperPotenciado arriba de todo, como el Carnet del Club de Colocadores.

![distintivo-vendedor-super-potenciado](https://cloud.githubusercontent.com/assets/6719872/13989126/bbad3104-f0ed-11e5-9bb7-6d1a993a0724.png)

@mkreyness a su vez, todos los que tengan esto deberían todos los meses tener automáticamente un grupo de 10 tickets por el mero hecho de ser Super Potenciados, y arriba de ese ticket grupo de tickets debería decir: "Tenés 10 tickets extra este mes por ser Vendedor Super Potenciado!"

Confirmenme si llegamos para el miércoles que viene.

abrazo

**Comment by mkreyness** [comment]
No creo que podamos intercalar un texto arriba de un grupo de tickets, ya que este podria empezar a mitad de un renglon, y ademas seguramente se decompondria bastante lo responsive al meter un objeto de dimensiones raras para lo que es la grilla de tickets.
Yo haria algo tipo que la primera vez que entra desde que se le acreditaron le aparezca algun mensaje popup que se lo anuncie y despues ya funcionan como tickets normales.
La otra seria que ese tipo de ticket tenga un color diferente o algo asi.

**Comment by LeandroBraier** [comment]
Me parecen bien ambas soluciones que das MK.

1) Cada mes a partir de que el usuario supera los 2500 puntos le aparece un pop up al ingresar que dice:

"¡Felicitaciones XXXXX! Al superar los 2500 puntos te convertiste en un Vendedor Super Potenciado y sumás 10 tickets más por mes."

2) Los 10 tickets extra por mes son azules y dicen arriba "SUPER POTENCIADO"

abrazo

**Comment by FAAREIA** [comment]
@mkreyness 

#### Bloque de "MIS LOGROS"
- http://www.parexklaukol.com.ar/vendedores/home.html
- Cada ticket esta en un `<dd class="ficha">`. Para mostrar el ticket potenciado, tiene que quedar `<dd class="ficha ticket-potenciado">`

#### Perfil del usuario
- http://www.parexklaukol.com.ar/vendedores/usuario-perfil.html
- Cada ticket esta en un `<dd>`. Para mostrar el ticket potenciado, tiene que quedar `<dd class="ticket-potenciado">`

#### Gráfico del ticket potenciado
- El común es `<svg><use xlink:href="img/constante.svg#ticket"/></svg>`, el potenciado es `<svg><use xlink:href="img/constante.svg#ticket-potenciado"/></svg>`. Se le agregó un `-potenciado` solamente.

---

Con respecto al mensaje podes duplicar el actual que te da puntos por el login del día y ponerle el texto que decia Lea.
Queres que te lo prepare o eso lo manejas por programación?

**Comment by mkreyness** [comment]
ya esta implementado el ticket diferenciado, lo pueden ver funcionando con mi cuenta 
user marcelokreyness
clave pepe
En cuanto al popup, podria pasar que la suma de 5 pts por entrar en el dia sea lo que le hace cruzar la frontera de los 2500 puntos, funcionaria bien que esten los DOS divs abiertos ? Cuando cierra uno ve el que esta debajo ?

**Comment by LeandroBraier** [comment]
Si, me parece bien eso MK. Los dos abiertos.

Gracias chicos! La estética quedó muy buena!! Avisenme cuando esté terminado. Entiendo que una vez automatizado esto falta ver el Distintivo de Super Potenciado arriba de "Tu perfil" en la home como en colocadores, no?

<img width="365" alt="captura de pantalla 2016-03-28 a las 4 32 19 p m" src="https://cloud.githubusercontent.com/assets/6719872/14087326/cc092aa6-f4ff-11e5-8589-37940c315c81.png">

abrazo

**Comment by mkreyness** [comment]
@FAAREIA ya maquetaste algo para eso del distintivo ?

**Comment by FAAREIA** [comment]
Si ahi ya lo agregué a la columna derecha y al perfil del usuario.
http://www.parexklaukol.com.ar/vendedores/home.html
http://www.parexklaukol.com.ar/vendedores/usuario-perfil.html

Si Lea da el ok ya se puede implementar. Lo que se agrega es solamente la imagen que tiene una clase.

**Comment by LeandroBraier** [comment]
Gracias Fede! En la home está OK.
En el perfil del usuario tendría que estar al lado del título "Tu perfil"
porque queda muy colgado sino. Se podrá?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Podría quedar asi sino
![sin-titulo-3](https://cloud.githubusercontent.com/assets/6184969/14109045/9a87a6b4-f596-11e5-9fcb-a368ae5f19e0.png)

O sino debajo de "8 fichas" dentro de "Mis logros"

**Comment by LeandroBraier** [comment]
Asi queda perfecto Fede!!! Gracias!!

Solo consulta: más adelante podremos hacer que el css (por ejemplo, color
de fondo, color de tipografías) de la comunidad sea distinto solo para los
usuarios "Super Potenciados"?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si se puede pero va a llevar unas horas y una minima programación por parte de marce.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/vendedores/usuario-perfil.html

@mkreyness fijate que ahora lo hice distinto en la página del perfil del usuario:
- Agregué la clase "super-potenciado" al `<main id="usuario-perfil">`
- Al h2 le agregué la imagen `<img alt="Vendedor super potenciado" src="img/vendedor-super-potenciado.png">`

**Comment by LeandroBraier** [comment]
Quedó genial!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
lo veo a partir de las 4 que llego a mi oficina.

**Comment by mkreyness** [comment]
Pero si el tipo NO es superpotenciado, que pongo ahi ?

**Comment by LeandroBraier** [comment]
Si no es superpotenciado que quede como antes. No se puede?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Entiendo eso, pero @FAAREIA lo armo como algo agregado, no entiendo si tengo que cambiarle algo al agregado o QUITARLO, lo cual es feo.

**Comment by mkreyness** [comment]
otra duda: es superpotenciado si en CUALQUIER MES del pasado sumó 2500 puntos ?
Ponele que alguien llega a serlo en marzo, el 1ero de abril se le va el distintivo hasta que vuelva a sumar o que ?

**Comment by LeandroBraier** [comment]
No, una vez que es superpotenciado ya queda superpotenciado para siempre.

Es 2500 puntos acumulados, no por mes.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ah, bien, esta noche lo liquido entonces.

**Comment by mkreyness** [comment]
Ahi lo puse pero se superpone con la leyenda "MIS DATOS", seguro no tocaste nada mas que esas 2 cosas que dijiste antes, @FAAREIA  ?
Miren:
http://www.parexklaukol.com.ar/cgi-bin/perfilvendedores.pl?

usuario=AndreaFarias73

clave=26898

(esta persona tiene mas de 2500 puntos)

**Comment by mkreyness** [comment]
salvo ese problema del distintivo que se superpone, esta todo implementado.
Por supuesto FALTA lo de sumar los 10 puntos mensuales.
Eso en que momento del mes se haria, al empezar o al terminar el mes? 
Digo para saber si ya lo tengo que sumar ahora en marzo. A mi me seria mas facil hacerlo al principio de mes (cada dia 1).

**Comment by LeandroBraier** [comment]
Al principio de mes entonces. Es lo ideal. AL principio de mes o apenas la
persona supere los 2.500 puntos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-03-29 22:49 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Dije 10 puntos, es 10 tickets, no ?
Igual lo de los tickets solo aplica para el sorteo, conque los agregue el dia 1 antes de que emitas la planilla de sorteo, ya van a entrar.
Hacerlo automatico cada vez que alguien suma un punto es recargar todo el proceso al cuete.

**Comment by LeandroBraier** [comment]
Entiendo pero el problema es que el tipo está perdiendo sumar los 10
tickets el mes mismo en que obtuvo el distintivo. Me parece que no va a
funcionar. Es mucho lio hacerlo automatico?

Estoy pensando que vamos a tener que hacer un mailing especial para
comunicarle a los usuarios del distintivo.

Abrazo

**Comment by mkreyness** [comment]
Con lo que yo digo le ENTRA en el sorteo del mes, porque se lo sumaria a las 0hs del dia 1 con fecha del dia anterior.
Durante el propio dia del sorteo los ve.

**Comment by LeandroBraier** [comment]
Si entiendo. Pero el usuario que supere los 2500 puntos el dia 2 del mes va
a estar hasta el 31 reclamando que no le sumaron los 10 tickets.

Insisto en que se vean esos tickets durante el mes. Porque ademas si los
sumas justo para el sorteo, para el mes siguiente ya desaparecieron no?

**Comment by FAAREIA** [comment]
Ahi lo modifiqué, "Mis Datos" queda separado del borde como "Tu Perfil". El tema es que no veo renderizada la imagen, no aparece el tag @mkreyness

**Comment by mkreyness** [comment]
Ok @LeandroBraier , ponele que en el momento que cruza le sumo los 10 tickets, pero sigue estando el tema de que hay que SEGUIRSELOS sumando todos los meses. Si un tipo cruzo a dia 30, va a tener 20 tikets sumados en 2 dias, me parece tambien muy injusto con el que tardo 1 dia mas en cruzarlo.
@FAAREIA el tag le aparece a quien tenga mas de 2500 puntos, no se con que usuario estas probando, tenes que usar el que yo dije mas arriba: 

http://www.parexklaukol.com.ar/cgi-bin/perfilvendedores.pl?

usuario=AndreaFarias73

clave=26898

obvio pega todas las partes del URL juntas con & , yo estoy tratando de evitar eso aca para que no lo indexen.

**Comment by LeandroBraier** [comment]
Mk: son 10 tickets por mes. Se llegó a 2500 puntos el dia 30 se le suman 10
parael sorteo del mes vigente y luego 10 para el sorteo del mes siguiente.
Siemore son 10. Nunca ve 20 tickets super potenciados juntos.

**Comment by mkreyness** [comment]
Mi miedo es al fraude. Es facil tener mas de una ventana abierta y lograr que en el momento de cruzar de 24xx a 25xx se te asignen los tickets 2 veces. Tenemos vivos de esa clase, ya los hemos sufrido.
En cambio el proceso automatico no hay como engañarlo.
Que te parece si TODOS los dias a las 0:00 o a la hora que te parezca si alguien en el dia anterior cruzo los 2500 le doy los tickets, y despues cada principio de mes ?

**Comment by LeandroBraier** [comment]
Me parece perfecto asi. Esa es una buena forma.

**Comment by FAAREIA** [comment]
Puede haber un usuario super-potenciado con menos de 2500 puntos?
Por ejemplo me logueo con el usuario de marce y las clases correspondientes al super-potenciado aparecen pero no el escudo, puede ser?

**Comment by mkreyness** [comment]
a eso venia mi pregunta de ayer: tengo que SACARLE la clase super-potenciado cuando no lo es ?
El escudo obviamente no lo estoy poniendo, pero en que afecta que deje la clase siempre ?

**Comment by mkreyness** [comment]
o hay otra clase que poner ?

**Comment by FAAREIA** [comment]
La clase super-potenciado solamente va cuando tiene que aparecer el escudo.
Después el ticket especial es otra cosa y tiene su clase propia.

**Comment by mkreyness** [comment]
pero va otra "class=" algo ? O nada ?

**Comment by FAAREIA** [comment]
no nada ^^

**Comment by mkreyness** [comment]
ok en un rato lo ajusto.

**Comment by mkreyness** [comment]
listo

**Comment by mkreyness** [comment]
ya le di las 10 fichas de este mes a todos los que tienen 2500 o mas, y deje automatico que cada dia agregue los nuevos que aparezcan, esto ya incluye darle a todos a principio de mes (con validez en el nuevo mes).
El problema es el que justo suma el ultimo dia del mes, a esos les tengo que hacer una corrida especial a las 23:59 o algo asi. Despues te digo como lo resolvi.

**Comment by mkreyness** [comment]
puse una corrida 23:58, con eso queda todo resuelto.

**Comment by LeandroBraier** [comment]
Marce, no lo anunciamos todavía. Vos hiciste que ya para Marzo les cuenten
estos tickets? Porfa podés quitarselos de vuelta? La idea era lanzar esto
recién en abril, la semana que viene, y comunicarlo especialmente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
