### ISSUE TITLE
Pequeño Bug Sitio Revear Actual. 31/03

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#284]
@FAAREIA encontré en el sitio de Revear algo muy extraño que calculo que es algún problema de programación.

Al final del home http://www.revear.com.ar/, me aparece este texto:
"/\=\s_([^'"]]_)\s*]/g"

Cuando puedas tranqui corregilo abrazo

**Comment by FAAREIA** [comment]
Ahi lo estuve viendo y en el HTML no esta ese texto, debe ser algo que se inserta por código. Tendría que verlo @mkreyness

**Comment by mkreyness** [comment]
Recuerden que todo esto fue copiado de la pagina original, y apenas tocado.
Esta lleno de codigo raro que no tengo la menor idea de lo que hace, seguramente proveniente del magento o algo asi. No encontre un punto para debuggearlo tampoco.

**Comment by LeandroBraier** [comment]
Olvidense entonces. Directamente cuando tengamos el nuevo sitio va a quedar bien.

abrazo
