### ISSUE TITLE
Descarga Números de Socio. 29/3

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#285]
@mkreyness como va? Para mañana a la mañana necesito poder descargar en el excel de usuarios de colocadores los números de socio. Modificarías eso porfa?

También fijate si podés hacer que me exporte nombres y apellidos por separado y que funcionen los tildes y Ñ.

abrazo

**Comment by mkreyness** [comment]
aca te referias al excel de ACTIVIDAD o simplemente al listado de colocadores ?

**Comment by mkreyness** [comment]
Ahi te lo agregue como primer columna de la actualizacion consulta de colocadores y separe nombre de apellido.
Avisame si lo queres tambien asi en la consulta de activadad.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !! Así está perfecto. abrazo
