### ISSUE TITLE
Acortador de ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#286]
@mkreyness tenemos alguno?

Necesito acortar este link para ponerlo en Facebook:

http://parexklaukol.us11.list-manage.com/subscribe?u=455b0cd079a287d15e307c9b7&id=d9d8502655

**Comment by mkreyness** [comment]
Como en Danica decis ?
No, pero se puede usar goo.gl o bit.ly

**Comment by LeandroBraier** [comment]
Ok. Usamos bit.ly entonces.  Abrazo

**Comment by LeandroBraier** [comment]
Podremos hacer una URL que redireccione a este link al menos?

Por ejemplo: parexklaukol.com.ar/suscribite

**Comment by mkreyness** [comment]
a mano ? Si, obvio, lo que no tenemos es un sistema automatico que los genere.
Ahora te lo armo.

**Comment by mkreyness** [comment]
listo.

**Comment by LeandroBraier** [comment]
Mil gracias MK!!! abrazo
