### ISSUE TITLE
Consulta Guía de Corralones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#287]
@FAAREIA consulta: se puede hacer que en el mapa de la Guía de Corralones todos los corralones muestren su nombre ya abierto dentro del mapa, sin que haga falta hacerles clic para que lo muestren.

Se puede?

**Comment by mkreyness** [comment]
Te contesto yo porque eso es tema mio: puedo hacer que los globos aparezcan abiertos apenas se los agrega, pero siempre van a ser globos, queres eso ?

**Comment by LeandroBraier** [comment]
SI! Eso me pidió el cliente. Se puede? Genial.

**Comment by mkreyness** [comment]
Eso piden porque no lo vieron. Si estas en Catamarca capaz sea razonable, pero en capital vas a ver una superposicion ilegible de todo.

**Comment by LeandroBraier** [comment]
Entiendo, si. Hay posibilidad de hacerlo previo y mostrarle antes de
aplicarlo?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
se puede hacer una copia que funcione asi.  Te lo armo a la noche, puede ser ?

**Comment by LeandroBraier** [comment]
Dale, perfecto. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Es inusable !!!
http://www.parexklaukol.com.ar/guia-corralones/index2.html

los carteles se tapan los unos a los otros y a todo el mapa.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

No importa, es lo que pidió el cliente. Muchisimas gracias

abrazo

**Comment by mkreyness** [comment]
pero mira que no esta eso en produccion, solo te lo hice de muestra. Si queres que lo pase a produccion avisame.

**Comment by LeandroBraier** [comment]
No hace falta. El cliente lo quiere para presentaciones internas. Mejor si
no está  en producción.  Es más: le aclaré que no lo subimos a producción
porque se ve feo.
