### ISSUE TITLE
Pequeña modificación en Producto parex

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#288]
@FAAREIA hoy durante el día cuando tengas tiempo hay que corregir la página de Parex térmico.

http://www.parexklaukol.com.ar/parex/parex-atermico.html

Dice 40 kg, pero la PRESENTACIÓN de este producto es por 30 Kg. 

Además hay que cambiar también la imagen del pack. Te la paso por este link de wetransfer:

https://www.wetransfer.com/downloads/0085a0d062d81b3942a8555cd782cc6520160331125345/a388df8029d4ac33bd913158c10af72720160331125345/895c56

La ficha técnica esta OK. 

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
