### ISSUE TITLE
Sección Cumpleaños Vendedores.

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#289]
@FAAREIA Esto es tranqui, cuando se pueda, hacer una versión de la sección de Ganadores pero para los cumpleañeros del mes.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA esto para la semana que viene lo ves posible? COnfirmame hoy porfa.

**Comment by FAAREIA** [comment]
Mañana ya lo liquidamos.

**Comment by LeandroBraier** [comment]
Genial @FAAREIA ! Gracias!

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/vendedores/cumpleanios.html

**Comment by FAAREIA** [comment]
@mkreyness copio a marce que tiene laburo aca.
Abrazo

**Comment by FAAREIA** [comment]
Falta la aprobación de LEa igual marce

**Comment by mkreyness** [comment]
ahi veo algo asi como "mes actual" y "mes que viene", seria asi ?
Y desde donde se accederia a esta pagina ?

**Comment by LeandroBraier** [comment]
Gracias Fede! Yo lo que pedí era solo ver los cumpleañeros de este mes.
Piensen que hay por lo menos 50 por mes. No van a entrar más.

El diseño no lo veo muy bien, Fede. La guirnalda queda rara. Fijate si le
podés encontrar la vuelta. Los papelitos sueltos están bien, pero la
guirnalda queda muy colgada. Fijate si podés tomar algo del mailing de
cumpleaños, que estaba bueno.

Marce: a la sección se debería acceder desde el mailing y desde un slide ad
hoc.

**Comment by mkreyness** [comment]
Ok, cuando este aprobado el template sigo.

**Comment by FAAREIA** [comment]
Fijate ahora Lea, dale F5:
http://www.parexklaukol.com.ar/vendedores/cumpleanios.html

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA!  Gracias!

Lo sigo viendo un poco fuera del target, probá porfa con esta estética: guirnaldas romboides arriba, circulares a los costados y papelitos en el fondo. Nada de globos. A ver si queda mejor, más adulto digamos.

<img width="644" alt="captura de pantalla 2016-04-11 a las 9 42 59 a m" src="https://cloud.githubusercontent.com/assets/6719872/14426672/ebff021e-ffc6-11e5-9c67-fd58b32dcaff.png">

abrazo

**Comment by FAAREIA** [comment]
Ahi va una versión más formal:
http://www.parexklaukol.com.ar/vendedores/cumpleanios.html

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Lo mando al cliente a aprobar antes de que lo toque MK.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA esto es para más adelante pero te voy dando el feedback del cliente acá: vamos a reemplazar la parte dinámica de la sección por una simple imagen grande, similar al slideshow, donde vamos a subir nosotros una foto por CMS con un collage de fotos de todos los cumpleañeros del mes.

Apenas nos saquemos de encima Potenciados y Siguit nos ponemos con esto. abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness esto podremos tenerlo para dentro de una semana más o menos? Me dicen si es muy dificil o una pavada? Cuantas horas llevaría?

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/vendedores/cumpleanios.html
Lo preparé para 1 imágen, no es slideshow ni acepta multiples imágenes

Avisame si esta ok

**Comment by LeandroBraier** [comment]
Está perfecto. Si se puede subir la imagen dsde el CMS y cambiar todos los
meses ya estaríamos. Confirmenme esto.

**Comment by mkreyness** [comment]
hago algo para que solo pongas mes/año y una foto ? Acordate de cargarla antes de que el mes empiece porque si no va a salir vacia

**Comment by LeandroBraier** [comment]
Ok. Entiendo. Perfecto asi.

**Comment by mkreyness** [comment]
Esto ya está, tenés en el menu de adm. de vendedores "Cumpleaños del Mes". Cargue una imagen de prueba con el mes de junio. Ojo no hay una leyenda variable en el template, si queres ponemos la frase "cumpleaños del mes" que sea variable y tome lo que cargues en el CMS.
El link para verlo (que no se donde estaria, lo vas a poner en un slide ?)
es este:

http://www.parexklaukol.com.ar/cgi-bin/cumples.pl 

si lo vas a poner en el link, agregale usuario=&clave= como de costumbre.

**Comment by LeandroBraier** [comment]
Mil gracias @mkreyness !! Queda de mi lado esto entonces. abrazo y gracias a los dos
