### ISSUE TITLE
Falla en Delegación ParexParaguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#29]
Marce, ya pasaron 48 hs y me fui a fijar en la página de ParexParaguay:

http://www.parexparaguay.com.py/cgi-sys/defaultwebpage.cgi

Me da un error rarísimo. Tenés idea de qué puede ser así le consulto al cliente en todo caso (o le aviso que lo estamos corrigiendo?)

abrazo

**Comment by mkreyness** [comment]
Es un tema de soporte con Duplika, creo en realidad que el unico 
habilitado a ese efecto sos precisamente vos, cada vez que pedimos Fede 
o yo algo nos dicen que lo hacen "de favor", pero que lo tiene que hacer 
el titular del server que entiendo sos vos.

**Comment by LeandroBraier** [comment]
No tampoco soy yo el titular del server. Es Marcelo Susevich. Escribime
textualmente qué les tengo que pedir y se lo paso a él.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-22 16:04 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Que el dominio adicional parexparaguay.com.py que esta declarado en la 
cuenta "parexkla" y esta delegado a Duplika desde hace varios dias no 
esta llegando al servidor, y sale ese cartel que me pasaste.
