### ISSUE TITLE
Mailing de Bienvenida a Nuevos Suscriptos al Newsletter. 01/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#290]
Fede, necesitaríamos un mailing de bienvenida muy muy simple, de texto, agradeciéndole a la gente por suscribirse al news de Parex

El texto sería:

"¡Gracias por suscribirte a nuestro newsletter! De ahora en más te mantendremos informado/a de las últimas novedades y tecnologías innovadoras en el mundo de la construcción. "

**Comment by LeandroBraier** [comment]
Hacelo bien bien siempre. Solo logo y texto. Muy simple y automatizable. Necesito la URL para que el cliente apruebe, nada más. No pierdas mucho tiempo con esto que es una pavada.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/bienvenida/bienvenida.html

**Comment by LeandroBraier** [comment]
Está perfecto Fede! Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness porfa ya dejémoslo como envío automático a los usuarios que se suscriban a nuestro newsletter a través de la web o de este link:

http://parexklaukol.com.ar/suscribite

abrazo

**Comment by LeandroBraier** [comment]
Podés pedirle a @valentinsabbath que lo haga quizá.

**Comment by LeandroBraier** [comment]
@FAAREIA me pidieron un cambio muy simple en el texto

El texto final quedaría así:

"¡Gracias por suscribirte a nuestro newsletter! A partir de hoy recibirás las últimas novedades y actualizaciones sobre el mundo de la construcción, arquitectura , tendencias y mucho más."

**Comment by mkreyness** [comment]
Sobre el link no puedo hacer nada, no tengo control del lugar al que esta yendo, ademas no esta entrando en nuestra base de suscriptores.
Los mails automaticos a la base de suscriptores existe hace muchisimo, se mandan cada 5 minutos y son para que CONFIRMEN, porque si no no los marcamos como activos.
Vos lo que queres es que cuando entren al link de CONFIRMACION desde el mail que ya recibieron, se les mande OTRO mail de confirmacion de la confirmacion ? No es mucho ?

**Comment by LeandroBraier** [comment]
Lo pidió el cliente. Incluyámoslo porfa, perdiendo el menor tiempo posible.

Recordá que el lunes sale el primer news y hoy sacamos un posteo en
facebook invitando a la gente a suscribirse.

2016-04-01 13:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
es que no ENTIENDO que hacer.
Sobre lo que se suscriban en OTRO SISTEMA, yo no tengo control.
Yo habia armado todo un sistema de suscripciones con confirmacion, puedo agregar que se mande un mail cuando confirman, pero no puedo hacer nada con datos que no me llegan.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/bienvenida/bienvenida.html

**Comment by mkreyness** [comment]
eso es QUE, pero la pregunta es A QUIEN

**Comment by mkreyness** [comment]
A los que se suscriban por ese otro metodo que desconozco, se le va a mandar un mail de confirmacion previo tambien ? 
Es la duplicidad de metodos lo que me confunde.

**Comment by LeandroBraier** [comment]
No te preocupes MK. Los que de sumen a esta lista les mando manual este
mailing de bienvenida desde mailchimp y listo. Igual tendrias que incluir
para los que de suscriban via web. Te parece bien asi?

**Comment by LeandroBraier** [comment]
Yo ya lo tengo todo listo para mailchimp. Simplemente avisame @mkreyness cuando quede automático para los que se suscriben via web. Con eso estamos. Puede ser para el lunes tranqui.

abrazo

**Comment by mkreyness** [comment]
OK, repaso final:
- el que se suscribe via la HOME de parex se carga en la base de suscriptores como hasta ahora, en un estado PENDIENTE.
  Yo tengo un proceso periodico (cada 5m) que envia un pedido de CONFIRMACION con un link.
  Si el que recibe el mail hace click en el link, pasa a un estado ACTIVO y ahi si deberia mandarle un este SEGUNDO mail, que es totalmente generico (no tiene links ni nada).
  A estos entonces activos los tomas para agregar a MailChimp y que reciban el Newsletter PERO NO LA CARTITA.
  Mientras que a los que entren directamente a MailChimp vos te arreglas para que reciban eso (no se si automatico).

**Comment by LeandroBraier** [comment]
Claro, tal cual. Yo me arreglo para que reciban eso. NO es automático.
Recibo notificaciones de mailchimp cuando se suman.

abrazo y buen finde!

2016-04-01 18:27 GMT-03:00 mkreyness notifications@github.com:
