### ISSUE TITLE
Mailing de Suscripción para Desuscriptos.

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#291]
@mkreyness este es el mailing a enviarle a los desuscriptos.

http://www.parexklaukol.com.ar/_mailing/sumarme/

La base de mails es esta:

[Base de Desuscriptos al 15-02 sin empleados parex.xlsx](https://github.com/LeandroBraier/Klaukol/files/200193/Base.de.Desuscriptos.al.15-02.sin.empleados.parex.xlsx)

Si son muchos para enviar todos juntos ponelos a enviar de a pocos, de la cantidad que sea seguro enviar, a lo largo del fin de semana. No hay apuro. Lo importante es que no caiga como spam.

abrazo

**Comment by mkreyness** [comment]
Pero una vez que reciban el mail y hagan click en "Sumarme", que se supone que va a pasar ?
Si es un formulario de mailchimp, y ya estan desuscriptos, NO SE si los va a aceptar resuscribir, probaste ?

**Comment by LeandroBraier** [comment]
Es que justamente este es el único mecanismo de "resuscripción" que permite
Mailchimp. Enviar a los desuscriptos un mail desde fuera de mailchimp que
los lleve a la lista creada "en" mailchimp. Ya lo hicimos un par de veces a
esto. Le llamamos "reconfirmación" o "resuscripción", algo asi.

2016-04-01 16:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok, pregunto por las dudas. Lo voy mandando en tandas durante el fin de semana, ok ?

**Comment by LeandroBraier** [comment]
Dale, perfecto. Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness la semana que viene (en varias cuotas) podremos hacer un nuevo reenvío de este mail para desuscriptos?

[Base de desuscriptos al 09-09.xlsx](https://github.com/LeandroBraier/Klaukol/files/464837/Base.de.desuscriptos.al.09-09.xlsx)

Como siempre haceme una prueba primero a mi y después largamos. Solo confirmame si para la semana que viene podríamos hacerlo.

abrazo

**Comment by mkreyness** [comment]
si, por que no.

**Comment by LeandroBraier** [comment]
Genial, solo para quedarme tranqui. Avisame cuando arranques nomas. Abrazo
y gracias!

**Comment by mkreyness** [comment]
El texto dice 2015, lo corrijo ?

http://www.parexklaukol.com.ar/_mailing/sumarme/

**Comment by LeandroBraier** [comment]
Si porfa. Quitale directamente "En 2015". Que empiece desde "ParexKlaukol
está consolidando..."

**Comment by mkreyness** [comment]
listo eso.

**Comment by LeandroBraier** [comment]
Gracias! Adelante nomás.

abrazo

**Comment by mkreyness** [comment]
Ahi te mande uno de prueba, creo que esta bien, pero por si acaso dame el OK.

**Comment by LeandroBraier** [comment]
Está perfecto MK! Adelante nomás.

abrazo

**Comment by mkreyness** [comment]
saliendo

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Ya no nos queda nada por hacer no? No podemos recuperar datos de rebotes y demás, verdad?

**Comment by mkreyness** [comment]
Se pueden ver en el CPanel de parexklaukol.com.ar, pero faltan 10 horas para que termine (son unos 1800 y salen exactamente 180 por hora, uno cada 20 segundos).

**Comment by LeandroBraier** [comment]
Buenisimo! Entonces la semana que viene vemos como salió. Muchas gracias de
nuevo y buen finde!!

abrazo

**Comment by LeandroBraier** [comment]
Marce, ya se terminó de enviar esto? Sino frenemoslo ya, apenas se pueda.

abrazo

**Comment by mkreyness** [comment]
se termino de mandar el sabado a la noche, no hay lo que frenar. Habria que ver en CPanel de Klaukol si hubo rebotes.
