### ISSUE TITLE
Falta un "Olvidé mi contraseña" en Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#292]
@FAAREIA tranqui mañana agregalo porfa.

No lo teníamos ya? pensé que lo teníamos en todas las plataformas.

abrazo

**Comment by FAAREIA** [comment]
Estaba hecho pero no implementado, faltaba muy poquito.
@mkreyness 

http://www.parexklaukol.com.ar/colo/recuperar-clave.html
http://www.parexklaukol.com.ar/colo/recuperar-clave.html?contacto=1
http://www.parexklaukol.com.ar/colo/recuperar-clave.html?contacto=2

El template es: `recuperar-claveT.html`
El link para recuperar la clave es: `/cgi-bin/recuperar-clave-colo.pl`

A la página la puse como template asi toma el header actualizado.
Ojo que el bloque del login no lo esta trayendo desde `ingresarT.html` sino que está inline en el html, al menos en el home.

Abrazo

**Comment by mkreyness** [comment]
no, el link es recuperarclavecolo.pl, todo junto, y fue hecho en diciembre.
Hay una mezcolanza de cosas. Voy a copiar el recuperarclavecolo.pl como recuperar-clave-colo.pl y vemos que pasa.

**Comment by LeandroBraier** [comment]
Gracias chicos! Avisenme porfa cuando esté hecho.

2016-04-04 9:55 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
el problema es que el mail que se manda supone la existencia de un template de mail que se llama 
/_mailing/colocadores-recordar/colocadores-recordar.html
pero eso no existe. 
Entonces, lo MANDA, pero vacio.

@FAAREIA cual seria el template del mailing ?

**Comment by FAAREIA** [comment]
Hay que hacerlo, te aviso

**Comment by FAAREIA** [comment]
Un mail simple:
http://www.parexklaukol.com.ar/_mailing/colocadores/recuperar-clave/recuperar-clave.html
Esperemos a que Lea lo apruebe igual.
Abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/club-colocadores/recuperar-clave/recuperar-clave.html
Cambié el link ^^

**Comment by LeandroBraier** [comment]
Está perfecto Fede.

**Comment by mkreyness** [comment]
habria que corregir el texto en 
http://www.parexklaukol.com.ar/colo/recuperar-clave.html?contacto=1

porque dice "te mandamos tu NUEVA ..."
en realidad es la misma, deberia decir "te mandamos la clave a tu mail" o algo asi.

**Comment by FAAREIA** [comment]
Ahi ya lo actualicé en el template

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Gracias! Ya lo probé y joya.

abrazo
