### ISSUE TITLE
Bug en Novedades Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#293]
@mkreyness anteayer subí varias novedades en la web de ParexKlaukol pero no me las actualizó en el Club de Colocadores. Te fijás porfa?

http://www.parexklaukol.com.ar/cgi-bin/maincolo.pl?usuario=marcelokreyness&clave=pepe

abrazo

**Comment by mkreyness** [comment]
Pero les tildaste para que salgan en la web de COLOCADORES ?
Si bien las novedades son las mismas, cuales se muestran dependen de que tengan el tilde prendido.

**Comment by LeandroBraier** [comment]
CIerto! No recordaba eso, perdón. Gracias!
