### ISSUE TITLE
Subida de Distribuidores Revear. 13/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#294]
@mkreyness acá tengo otra tarea que podría hacer @valentinsabbath también.

Necesito subir esta nueva línea de distribuidores de Revear a la base que tenemos en el CMS. 

[Nuevos Distribuidores Revear a Subir.xlsx](https://github.com/LeandroBraier/Klaukol/files/210083/Nuevos.Distribuidores.Revear.a.Subir.xlsx)

Ya ordené las columnas igual que en el mismo por las dudas. Me avisan si se puede? Puede ser para la semana que viene sin problemas.

abrazo

**Comment by mkreyness** [comment]
Se puede.
@valentinsabbath esto va en la tabla "dis" de la base "parexkla_red" del servidor "parexkla" en Duplika.
No se si alguna vez ya accediste ahi para algo, me suena a que no. Cualquier cosa pedime las credenciales.
Si miras el contenido actual de la tabla vas a ver que los campos van mas o menos tal cual excepto algunos que no cargamos (no tenemos los representantes codificados). El dato codigo no es realmente un codigo, porque se repite a lo loco, igual nosotros no lo usamos para nada. 
Y hay un dato de provincia que hay que traducir al id (yo normalmente los reemplazo en el Excel antes de importarlo.
La tabla de provincias es "pvn".

**Comment by ghost** [comment]
@mkreyness Me pasaías el ip y las credenciales? Gracias

El 8 de abril de 2016, 9:24, mkreyness notifications@github.com escribió:

> Se puede.
> @valentinsabbath https://github.com/valentinsabbath esto va en la tabla
> "dis" de la base "parexkla_red" del servidor "parexkla" en Duplika.
> No se si alguna vez ya accediste ahi para algo, me suena a que no.
> Cualquier cosa pedime las credenciales.
> Si miras el contenido actual de la tabla vas a ver que los campos van mas
> o menos tal cual excepto algunos que no cargamos (no tenemos los
> representantes codificados). El dato codigo no es realmente un codigo,
> porque se repite a lo loco, igual nosotros no lo usamos para nada.
> Y hay un dato de provincia que hay que traducir al id (yo normalmente los
> reemplazo en el Excel antes de importarlo.
> La tabla de provincias es "pvn".
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/Klaukol/issues/294#issuecomment-207411011

## 

_Atte. Valentín Gavela._

**Comment by mkreyness** [comment]
te las mando por mail, aca es todo publico y lo indexa google.

**Comment by LeandroBraier** [comment]
Porfa confirmenme cuando está subido esto @valentinsabbath

**Comment by ghost** [comment]
Listo @LeandroBraier , tuve que aprender un par de cositas pero ya está

**Comment by LeandroBraier** [comment]
Excelente Valen! Gracias!
