### ISSUE TITLE
Nueva Dinámica de Subida de Foto. 12/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#295]
@mkreyness necesito que para hoy de ser posible o mañana a la mañana habilites en Estado de ELABORACIÓN una nueva dinámica como esta:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=27

&usuario=LeandroBraier
&clave=parexklaukol

Título:  "Subí tu selfie con Klaukol"

Imagen Inicio:
![posteo-comunidad-de-vendedores-12-4](https://cloud.githubusercontent.com/assets/6719872/14438961/10a6a774-ffff-11e5-9669-bbd2c674dd90.png)

Imagen agradecimiento: 
http://www.myroyalphotobooth.com/wp-content/uploads/2015/07/Photographer.jpg

Texto agradecimiento: Gracias por subir tu foto. ¡Acabás de sumar 300 puntos!

abrazo

**Comment by mkreyness** [comment]
Si no entiendo mal, el problema que no te permite replicarlo directamente vos como tema+juego es que a un jugador que ya subio una foto por el viejo juego (el de subi tu foto con el equipo de trabajo) no le dejaria subir otra.
Lo que tendria que hacer yo es agregar a la tabla de "fotos subidas por vendedores" una identificacion del tema por el cual subieron, y controlar que no se repita en el mismo tema.
Con eso quedaria funcionando cada juego en forma independiente.

**Comment by LeandroBraier** [comment]
Excelente MK! Dale, la idea es que tengas que hacer lo menos posible. Si
puedo subir los contenidos yo mejor.

abrazo

2016-04-11 16:26 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
en principio ya estan hechos todos los cambios necesarios. Armale el tema y el juego (tiene que tener tipo 'UPLOAD') y lo probamos.

**Comment by LeandroBraier** [comment]
Hecho MK!

**Comment by mkreyness** [comment]
Listo, fijate, ojo acordate que vos estas suspendido, asi que no te suma puntos. Yo te diria que te dessuspendas un momento para poder verificarlo.
el id para el URL de jugar.pl es 46

**Comment by LeandroBraier** [comment]
Dale, denme un ratito y lo pruebo.

2016-04-11 18:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Acá me pasa lo mismo que en VIE TUR.

Cambio el usuario de SUSPENDIDO a ACTIVO y me deja de funcionar el usuario. Te fijás MK porfa qué puede ser?

abrazo

**Comment by mkreyness** [comment]
Estas seguro que no le cambiaste la clave tambien ?
Me figura que la clave es "revear", poniendo tu usuario y esa clave me entra perfectamente.
Capaz tu browser esta recordando passwords viejas y al entrar a la pantalla te la forzo.

**Comment by mkreyness** [comment]
y la de VIE TUR es "b3nt3v30"

**Comment by LeandroBraier** [comment]
Fuck, entonces ojo porque me cambió la clave automáticamente. Me venía pasando al cargar distribuidores de Revear. Fijate porfa qué puede estar pasando.

b3nt3v30 es la clave del admin. La clave de ese fake era vietur. Tenés idea qué pasó?

**Comment by LeandroBraier** [comment]
Ahi estoy probandolo y no lo veo actualizado. Te acordás que con el otro juego nos pasaba lo mismo? Queda cacheadísimo y no sé como sacarlo (obvio que borré el caché de mi navegador).

**Comment by mkreyness** [comment]
Password:
Es tu browser, el programa no puede adivinar claves en el aire, tu browser asocio que en la pantalla decia "Password:" y puso automaticamente la que tiene asociado con ese URL.
Siempre hay que tener cuidado con lo que los browsers autocompletan, a mi el Chrome cuando me hace esas cosas me las muestra en amarillo.
Para que no te pase (si vas a estar entrando a la pagina de vendedores, inclusive gente que NO SEAS VOS) tenes que poner en el browser que NO autocomplete (no se si se puede relacionar con la pagina, me parece que no).

Lo otro me perdi: Que es lo que tenes cacheadisimo ?

**Comment by LeandroBraier** [comment]
Perdón, te estoy mezclando.. Este juego me anduvo perfecto pero me sumó 0 puntos. Algo salió mal ahí.

En cuanto a todo lo que sea VIE TUR te lo paso en su ticket correspondiente.

abrazo

**Comment by mkreyness** [comment]
ahora pruebo con tu usuario yo

**Comment by mkreyness** [comment]
me anduvo bien y sumo los 300 puntos.
Puede ser que como yo habia estado haciendo pruebas con tu usuario haya quedado algo de basura que lo complico. Elimine todo eso y probe y anduvo bien. Te lo vuelvo a dejar limpio para que puedas probar vos.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Ahora si!! Ya quedó publicado!

abrazo grande
