### ISSUE TITLE
Bug de los tildes en Vendedores Parex

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#296]
@FAAREIA sigue el Bug de los Tildes en Iniciar Sesión en front end pero también en todos los títulos a los que le ponemos tildes en el CMS @mkreyness 

Porfa esta semana dejenlo resuelto porfa. Evidentemente quedó de la última actualización de duplika.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness en el CMS sigue pasando esto pero en front se ve bien, hay forma de resolver?

**Comment by mkreyness** [comment]
Seguro ? Lo habia arreglado hace unos dias revisando otras cosas, sin haber visto este issue.
Siempre es por los cambios de server que hace duplika, pero sacandole un forzado de utf-8 se arregla.
Si lo ves en alguna pagina puntual avisame, capaz son datos que se cargaron mientras estaba todo feo y ahora al enderezar el resto se torcio eso.

**Comment by LeandroBraier** [comment]
Es en el CMS. Por ejemplo, en los slides de Vendedores:

<img width="1145" alt="captura de pantalla 2016-04-20 a las 4 50 48 p m" src="https://cloud.githubusercontent.com/assets/6719872/14687666/27ac52ee-0715-11e6-9e60-c2005322a1f9.png">

<img width="1148" alt="captura de pantalla 2016-04-20 a las 4 50 54 p m" src="https://cloud.githubusercontent.com/assets/6719872/14687674/31f6dc9c-0715-11e6-848a-b99322d29d1c.png">

<img width="1246" alt="captura de pantalla 2016-04-20 a las 4 50 59 p m" src="https://cloud.githubusercontent.com/assets/6719872/14687677/34aa7188-0715-11e6-931b-b1d3b870cc11.png">

Me pasa en el CMS de Parex pero en el de VIE TUR no, ponele.

**Comment by mkreyness** [comment]
son nuevos ? Me suena a que deben ser cosas que se cargaron DURANTE esta transicion que te digo.
Es cuestion de reescribir el texto nomas.

**Comment by LeandroBraier** [comment]
Ah... a ver... Nop.

Ahi lo chequeé y por más que reescriba siguen apareciendo así.

**Comment by mkreyness** [comment]
es un bolonqui porque entraron cosas con distintos encodings en distintos momentos, al migrar los datos de un equipo a otro quedo todo en una situacion diferente a lo nuevo que se ingresara.
Ahi hice un par de ajustes, en el CMS los veo bien, pero hay que ver si ahora salen bien en la pagina real.

**Comment by LeandroBraier** [comment]
Ahora si, todo perfecto en ambas comunidades. Gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness fijate: en novedades los veo mal a los tildes ahora. FIjate el título de la nota en esta captura.

<img width="184" alt="captura de pantalla 2016-04-26 a las 3 04 27 p m" src="https://cloud.githubusercontent.com/assets/6719872/14838667/0868f470-0bfa-11e6-9ea7-67d385499da9.png">

Otra cosa que noto en novedades es que la URL se arma con tildes, eso no puede provocar problemas después?

![captura de pantalla 2016-04-26 a las 10 27 09 p m](https://cloud.githubusercontent.com/assets/6719872/14838762/f06c5b36-0bfa-11e6-9fc2-f2c3c18d68de.png)

abrazo

**Comment by mkreyness** [comment]
Todo mal. Ahora reviso.

**Comment by mkreyness** [comment]
Listo, con los cambios de server de Duplika directamente los acentos que estaban en el codigo para detectar y reemplazarlos en URLs por las vocales no-acentuadas se habian estropeado.
Y por otra parte nunca funciono con MAYUSCULAS acentuadas, que era lo que tenia esto del "Indice Construya". Ya lo arregle. Lo que si habria que revisar si no se jorobaron URLs en otras news aparte de estas dos, hay que entrar, cambiarle algo y volverle a poner lo que decia para que lo regenere (si no le escribis algo distinto no se detecta cambio y no se reprocesa).

**Comment by LeandroBraier** [comment]
Gracias MK! Mañana reviso por las dudas todo. Abrazo grande

**Comment by LeandroBraier** [comment]
Ahora si, todo perfecto. Gracias! abrazo
