### ISSUE TITLE
Facebook Connect para Registro y Login en Colocadores. FRENADO

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#297]
@FAAREIA se podrá Fede?

**Comment by FAAREIA** [comment]
@mkreyness es un tema de marce, habría que ver si se puede linkear el login del facebook con el del usuario ya registrado en la comunidad. Parece dificil a simple vista.

**Comment by mkreyness** [comment]
El Facebook Login (no es Facebook Connect, Facebook Connect es otra cosa, para postear contenidos) implicaria que al momento de la REGISTRACION (cosa que en Klaukol no existe) capturemos el nombre de facebook como codigo de usuario, y encima puede pasar que ya tengamos a alguien con este usuario y no se pueda duplicar.
Supongamos que en el perfil de los que ya existen les pusieramos un boton de Login (que no tiene mucho sentido porque ya esta loggeado) para capturar su usuario de facebook, lo deberiamos guardar como un dato aparte, y cambiar toda la logica del login para que si esta en facebook lo loggee automaticamente sin pedir contraseña.
Ahora para mi el PEOR de los problemas, es que los vendedores comparten PCs en el trabajo y puede estar loggeado uno en facebook (la gente no se acuerda de desloggearse) y viene otro y en vez de dejarle loggearse con su usuario correcto lo llevamos al sistema EN LA CUENTA DEL OTRO.
Me parece muy confuso.

**Comment by LeandroBraier** [comment]
Mk, me parece que en el título del ticket está la respuesta a tus
preguntas: no es para Vendedores. Es para Colocadores, que sí tienen
registración y acceden desde pc o teléfono propio, no en el trabajo. En tal
caso, se puede hacer registración via Facebook?

2016-04-13 17:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ja ja, no vi la ultima palabra (se me truncan los subject en la columna).
Si, con los nuevos que se registren, pero con los viejos no se bien donde ponerlo.
El boton de "login con facebook" no nos sirve si primero no esta relacionado con un usuario conocido, asi que ponerlo en el propio login no sirve.

**Comment by LeandroBraier** [comment]
Demosle la opción a los viejos de vincular su cuenta de Facebook y listo,
no se puede? Sino dejemosla solo como opción de registración para los
nuevos nada más.

2016-04-13 18:07 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Habria que agregar un boton en el perfil solo para aquellos que no tengan todavia asociado un usuario de facebook, para que lo hagan por ahi. Una vez puesto ya no se podria sacar, y cuando entren a la pagina /colocadores si esta loggeado en facebook lo haria entrar directo.
Ahora todo esto lleva tiempo, y no le estoy dando 5 de bola a Diego...

**Comment by LeandroBraier** [comment]
Si, lo tengo. Esto no es urgente tampoco. Metelo en la cola y decime para
cuando podría estar. Puede ser para fin de mes por ejemplo, todo bien.

2016-04-13 18:19 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ok, tambien le prometi cosas para fin de mes a Diego, voy a ver como meterlo, pero no agreguemos mas plis. El tema del boton en la registracion y en el perfil (aunque no lo pongamos en produccion todavia) lo tendria que maquetar @FAAREIA en algun momento previo.

**Comment by LeandroBraier** [comment]
Ok, puede ser para después de lo de Diego entonces. No es prioridad esto.
Gracias MK!

2016-04-13 18:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Agrego un botón de facebook al perfil del usuario asi lo conecta con su usuario?
Avisenme si esto sigue vigente

**Comment by mkreyness** [comment]
mientras yo no le dedique tiempo a que eso guarde un dato que despues pueda reconocer, me parece que no tiene sentido avanzar en poner el boton.

**Comment by LeandroBraier** [comment]
Tal cual. Esto frenemoslo chicos.
