### ISSUE TITLE
Calculador de Consumo Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#299]
- Link: http://revear.com.ar/calculador-de-consumo.html
- Se agrega calculo de costo y días de obra. Aquí les paso los datos x 100m2, uds lo toman de patrón para el cálculo de las variables no?

Revear:
Costo $21.000 x 100 m2
5 días de obra

Incluye Revestimiento Revear y mano de obra.

Enduido + Pintura:
Costo $29.363 x 100 m2
10 días de obra

Incluye cemento, cal, arena, fijador, enduido, pintura y mano de Obra.

abrazo

**Comment by FAAREIA** [comment]
@mkreyness

**Comment by mkreyness** [comment]
No entiendo como aplicar eso, es un texto fijo ? El calculador de consumo solo dice cuantos kilos de producto cubren una determinada superficie, SEGUN el producto que se elige de un desplegable.
Esto no depende del producto ?

**Comment by LeandroBraier** [comment]
Los datos en realidad son de Revear Marble. Pero apliquemoslo por igual a
todos por ahora.

**Comment by mkreyness** [comment]
Supongamos que agrego dos datos en el CMS: precio por cada producto y en otro lado (fijo porque no depende del producto) tengo "precio de enduido y pintura" independiente de los productos. En los productos que no tengo precio pongo solo la parte de "enduido y pintura", y en los que si ambas cosas ? O pongo igual dependiendo del producto el de "enduido y pintura" ?

**Comment by LeandroBraier** [comment]
Poné el costo por 100 m2 (o por m2, como te sea más conveniente para adaptarte a los datos ingresados por el usuario) de cada producto Revear por un lado (a todos cargales AR$ 21.000 por ahora, cualquier cosa yo lo corrijo más adelante) y de "Enduido + Pintura" por el otro (a este cargale siempre AR$ 29.363). Lo que incluye cada uno sí es un texto fijo que va abajo de todo.

abrazo

**Comment by mkreyness** [comment]
Si, $210/m2 y $293.63/m2 respectivamente serian.
Y lo de 5 y 10 dias de obra tambien deberia ser proporcional a los m2, aunque no dependa del producto.

**Comment by mkreyness** [comment]
Listo, fijate. La tipografia es horrible, no se si preferis que lo mande a la parte que esta en una especie de recuadro violeta con letras blancas.

**Comment by LeandroBraier** [comment]
No, está bien. Lo único si podés que el signo de exclamación quede junto con la frase, ahora queda ene la oración de abajo:

<img width="1680" alt="captura de pantalla 2016-04-18 a las 7 06 56 p m" src="https://cloud.githubusercontent.com/assets/6719872/14620963/1f085e10-0596-11e6-9213-7abc172df1ab.png">

**Comment by LeandroBraier** [comment]
Perdón, mala mia.

**Comment by mkreyness** [comment]
y ademas al copiar y pegar se me coló una comilla.
Listo, fijate.

**Comment by LeandroBraier** [comment]
Quedó perfecto ahora MK! Pero no te olvides que estamos en el tickert
equivocado, así que ahora borro estos comments para no marear al pobre Fede.

abrazo y gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Y lo de Revear lo viste ?

**Comment by LeandroBraier** [comment]
Ahora si. Lo que me parece es que no está bien mostrado. Fede: dale una maquetación más moderna y vistosa, como la del Calculador HTML5 de Klaukol.

Tranqui mañana.

abrazo

**Comment by mkreyness** [comment]
Es que esto es el sitio viejo, con su tipografia diminuta, cuando haga el restyling sera otra cosa.

**Comment by LeandroBraier** [comment]
Ah genial! Los datos son correctos. Están bien.

**Comment by FAAREIA** [comment]
Le doy un restyling a cual pantalla?

**Comment by LeandroBraier** [comment]
Los resultados más que nada.

**Comment by FAAREIA** [comment]
Vale la pena poner un parche visual solo ahi? Preferiría invertir tiempo en lo nuevo que se viene dentro de unas pocas semanas

**Comment by LeandroBraier** [comment]
Si, totalmente de acuerdo Fede. Yo me refiero a que se vea lindo en la
nueva web. Totalmente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-04-19 11:02 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA te cierro este ticket porque ya queda dentro de la nueva web no?

**Comment by FAAREIA** [comment]
Creo que no hace falta que quede abierto, excepto que @mkreyness diga lo contrario

**Comment by mkreyness** [comment]
No hace falta, todo lo que se haga va a ser en la nueva.

**Comment by LeandroBraier** [comment]
Perfecto. Adelante nomas.
