### ISSUE TITLE
Desarrollado por Benteveo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#30]
Fede, te estás olvidando de agregarle el desarrollado por Benteveo a los sitios. Agregaselo a TODOS los de Klaukol. Versión 1.0, Vendedores, Colocadores, TODO.

abrazo

**Comment by FAAREIA** [comment]
Si, eso lo tengo como pendiente. Cuando haya un poco de espacio lo empiezo a meter en todos.
