### ISSUE TITLE
URGENTE Bug en Trivia Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#300]
@mkreyness te paso una trivia nueva:

http://www.parexklaukol.com.ar/cgi-bin/trivia.pl?id=99

usuario=LeandroBraier
clave=parexklaukol

Es una trivia común y corriente, igual a la anterior de "Predecí el superclásico" pero la diferencia es que hay 5 preguntas en vez de 1. Al igual que en aquel caso, todas las respuestas son correctas. Sin embargo, al final, me dice que algunas respuesta fueron correctas y otras no. Te fijás qué puede estar pasando porfa?

Esto si es urgente porque me pidieron que la suba a más tardar mañana a la mañana temprano.

abrazo

**Comment by LeandroBraier** [comment]
Estoy viendo que el ID del juego es raro, porque no tenemos 99 dinámicas creadas.

**Comment by mkreyness** [comment]
el id de una trivia no es el del TEMA, sino el del JUEGO, si hay 99 juegos.
Ahora me fijo.

**Comment by mkreyness** [comment]
estas seguro que esto ya se habia usado asi ? No era mas bien que los puntos lo ganaba el que acertaba y las opciones eran tipo solo BOCA/RIVER y no habia EMPATE, y salio EMPATE, con lo cual no gano nadie ?
Lo que esta pasando aca es que en realidad no funciona ponerle a TODAS que son correctas, porque lo que el programa hace no es ver si la opcion elegida tiene tilde de correcto, sino que busca cual es "la correcta" (trae la primera, no imagina que haya mas) y la compara con tu respuesta. Entonces si en las 5 preguntas elegiste la pimer opcion, barbaro, pero cualquier otra cosa no es "la correcta". Voy a cambiar la forma en que busca/compara y listo.

**Comment by LeandroBraier** [comment]
Eso es rarisimo MK, nunca funcionó así.

En trivias normales, el sistema siempre tomó como correcta la que aparece
como correcta.

Compará esta con la Trivia del Superclásico anterior, ahí vas a ver que
estaba igual. Todos suman los 100 puntos. Después, los que acertaron el
resultado del partido les ibamos a sumar manualmente 200 puntos más por
haber acertado. Como justo hubo empate no acertó nadie y no se los sumamos,
pero el empate estaba como opción correcta también.

No sé si me seguís en esto.

2016-04-20 22:14 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero siempre marcabas solo UNA respuesta correcta, eso es lo normal, nunca deberia haber MAS de una respuesta correcta.
Aca marcaste las TRES como correctas.
Igual ya esta, ya lo arregle, pero en la parte que LISTA las "respuestas correctas", nuevamente, cual pone ? NO tiene sentido, para mi este tipo de cosas tendria que manejarse mas como un "quiz" que como una trivia.

**Comment by mkreyness** [comment]
tampoco encuentro cual es el anterior para comparar. Pasame el link si lo tenes.
Ojo que ESTA trivia nueva ya figura PUBLICADA, hay gente que ya la jugo.

**Comment by LeandroBraier** [comment]
Gracias MK. Ahi lo despubliqué.

Al final en los resultados siempre debe decir que respondió todas correctas y listo. No sé por qué puede ser un problema si todas las respuestas están marcadas como correctas. Insisto que el caso anterior anduvo bien. Te paso link:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=37

**Comment by mkreyness** [comment]
ahora anda igual que el nuevo, porque ya esta tocado el programa. La verdad no se que podria haber estado haciendo antes que saliera bien, pero conceptualmente es lo mismo.
Dice "Gana Boca", porque es la primer opcion correcta de la lista, aunque vote "gana river" o "empate", siempre dice "gana boca".
Tendria que inhibir que no salga una lista de respuetas correctas si no existen las respuestas incorrectas.

**Comment by LeandroBraier** [comment]
Exacto. COn eso lo solucionamos.

**Comment by mkreyness** [comment]
ok, en un rato lo hago

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
GRacias MK!!
