### ISSUE TITLE
Nueva Dinámica de Codigo para el Viernes 22/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#301]
@mkreyness y @FAAREIA necesito para el viernes al mediodía la posibilidad de crear un nuevo tipo de dinámica en la Comunidad de Vendedores de Parex: es simple. EL usuario solo debe ingresar un código que recibe en un flyer y si es correcto gana los puntos.

Mi idea es: subimos una lista de códigos alfanuméricos y los vendedores tienen que ingresar el código en un campo de texto. Si el código coincide con esa base le damos los puntos. Sino no.

Me confirman si se puede?

abrazo

**Comment by mkreyness** [comment]
No entiendo bien la mecanica. A cada vendedor se le va a dar un codigo propio, o cualquiera puede ingresar cualquiera ? El que se ingresa, no se puede volver a ingresar ? (mismo u otro vendedor)

**Comment by LeandroBraier** [comment]
Cada vendedor suma 1 sola vez. Puede ingresar su código o el de otro, no
hay problema, pero cada código ingresado suma puntos 1 sola vez. Si esto
último es un lío hacerlo no es imprescindible. Que el límite sea que el
usuario puede sumar puntos 1 sola vez, no importa el código.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Pero digo, el codigo no deberia ser reutilizado, ni por si mismo ni por ningun otro vendedor.
Como se reparten los codigos entre los vendedores ?

**Comment by FAAREIA** [comment]
Se podría poner un pop-up apenas se loguee. El pop-up dejaría de aparecer cuando ya puso 1 código válido o cuando ya pase esta promo. No debería de reaparecer cuando ya puso un código válido ya que encima no le vuelve a sumar puntos.

**Comment by LeandroBraier** [comment]
Unos cupones impresos. Pero no es tan importante que no se repita el
código, porque lo que quiere el cliente es que conserven el flyer y vayan a
la comunidad. Si varios usan el mismo código no es grave porque significa
que igual tiene el flyer.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ok, vuelvo entonces a donde deberia aparecer esto: como un juego mas en la lista ? Porque si es asi, es un nuevo TIPO de juego, y requiere un poco de testing, si la maqueta está hoy a la tarde puedo hacerlo a la noche, ya mañana viernes no tengo cuando

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Exacto. Dale, no hay problema. COntá conmigo cuando necesites hacer testeo
y demás.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-04-21 9:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
es un juego entonces?

**Comment by LeandroBraier** [comment]
Si, pero muy simple. Solo tiene un campo para escribir un código. Nada mas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/vendedores/juego-formulario.html
Cuando sume los puntos, lo mandaría al home o al listado de juegos y le mostraría el mensaje típico de que ya ganó puntos. Avisame si queres que te lo prepare marce @mkreyness

**Comment by LeandroBraier** [comment]
Está perfecta la maquetación Fede! Avisame @mkreyness cuando esté funcional y le pueda cambiar el nombre a la dinámica así le aviso al cliente. El código necesita ser de determinada longitud o es lo mismo?

Para mi lo ideal sería que fuera la estructura así: 9 caracteres alfanuméricos.

`p4r3x2016` 

Una cosa así. Lo ves OK?

**Comment by mkreyness** [comment]
Cuando entra de nuevo al juego deberia aparecerle "Hecho".
En el listado de juegos (que es generico) yo no meteria cosas especificas de un juego que gano puntos, puede complicar la logica de otras cosas. Yo preferiria si volviera a ESTA MISMA maqueta, con el cambio a "Hecho" y el popup que diga que gano los puntos. Para volver a la lista de juegos que haga click en algo que diga "SEGUI JUGANDO" o algo por el estilo como ya hay en otros juegos, se podra ?
Si no tambien puedo ponerle que al CERRAR el popup lo lleve a la lista de juegos.

**Comment by mkreyness** [comment]
Bueno mas o menos me las arregle con lo que habia, no le aparece "hecho" si entra de nuevo, pero si trata de mandar un codigo le devuelve que ya habia ganado XXX puntos ingresando un codigo antes.
Resumiendo quedo asi:
- en el CMS agregue un nuevo tipo de juego que se llama "Codigo".
- Agregue un TEMA (no publicado obviamente) que se llama "Ingresa tu Codigo"
- Agregue un JUEGO de tipo "Codigo" que se llama "Ingresar Codigo". DENTRO DE ESTE JUEGO (y eso es lo novedoso e importante) agregue una solapa nueva para pegar los codigos. Esto va a permitir tener diferenetes sets de codigos habilitados para diferentes juegos.
- hay 2 codigos cargados por mi, pero se pueden agregar mas por esa via. Son 123456 y 654321.
- Para probar el juego:
  http://www.parexklauko.com.ar/cgi-bin/jugar.pl?id=48
  user y pass habituales.
  Hay 3 situaciones:
- que lo pongas bien, en cuyo caso te muestra ganaste XXX puntos (ojo corregile en el juego la cantidad de puntos que realmente corresponda) y al cerrar el aviso se va a la lista de juegos
- que lo pongas mal, en cuyo caso te dice "CODIGO ERRONEO" y al cerrar el cartel lo podes volver a ingresar.
- que ya lo hayas hecho bien antes, entonces sale ese cartel de "YA GANASTE ANTES xxx PUNTOS INGRESANDO UN CODIGO" que mencione al principio.

Con eso desde lo fucional esta todo, pero hay un detalle que no se que hacer.
Este juego en vez de tener los tipicos botones de Compartir abajo, veo que en la maqueta aparece un like arriba. No se si fue a proposito o no.
Asi como esta ahora, ese like se refiere a una pagina en particular.
Confirmame @LeandroBraier  si queres que saque eso y ponga el mecanismo de compartir de siempre debajo del formulario, y que siempre lo que compartiria seria lo que se cargue como URL en el CMS.

**Comment by mkreyness** [comment]
me comi la "L" de "klaukol" en el URL, es 

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=48

**Comment by LeandroBraier** [comment]
Muchas gracias MK! Mañana lo veo bien en detalle y te confirmo por las
dudas.

Abrazo grande

**Comment by LeandroBraier** [comment]
Saquemos el Like MK. Lo demás está perfecto. Cuando tenga la lista de códigos te aviso. Gracias!

abrazo
