### ISSUE TITLE
Sumar puntos a los que acertaron esta dinámica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#302]
@mkreyness hoy terminan los clásicos y tenemos que sumar los puntos que correspondan a los que acertaremos al menos 1 de las 5 preguntas de esta trivia:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?&id=47

Creo un juego oculto que sume los puntos y te paso la lista de los que acertaron así vos les sumás los puntos de ese juego. Está OK el procedimiento?

**Comment by mkreyness** [comment]
1) hay que deshabilitar el juego asi no pueden votar con los resultados sabidos, ya lo deshabilitaste ?
2) carga un juego de tipo "actividad" para este caso que sea "acertar con un superclasico" o algo por el estilo. Al no tener un TEMA, queda automaticamente "oculto", como vos decis.
3)  marcame en la trivia como correcta solo la opcion que corresponda en cada caso y yo a quienes hayan acertado le sumo puntos en ese otro juego nuevo.

**Comment by LeandroBraier** [comment]
1) Hecho.
2) Hecho.
3) Hoy es el último partido. Mañana te modifico eso en la trivia, te parece?

Gracias!

**Comment by mkreyness** [comment]
3) mira que 9:30 am yo me voy y no hay garantias de que me pueda reconectar antes de las 4. Si podes hacerlo temprano mejor asi nos lo sacamos de encima.

**Comment by LeandroBraier** [comment]
Dale, lo hago hoy de ultima y ya te queda.

2016-04-25 17:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@mkreyness ya los subí. Este cambio no le quita los puntos a los que ya sumaron 100 no? POrque todos los que participaron tienen que sumar 100. A los que acertaron al menos 1 partido se les suman 200 puntos más del nuevo juego que te creé, que se llama "Acertar el clásico."

abrazo

**Comment by mkreyness** [comment]
Los puntos otorgados no hay nada que los quite, no se reevaluan las respuestas.
Ok, en un rato les agrego 100 puntos del juego nuevo a quienes corresponda.

**Comment by LeandroBraier** [comment]
Dale joya.

Ojo que son 200 puntos los del juego nuevo.

Abrazo

**Comment by mkreyness** [comment]
200.

**Comment by LeandroBraier** [comment]
Esto ya está MK? Confirmame nomás.

abrazo

**Comment by mkreyness** [comment]
Si, lo hice anoche, parece que no te confirme entonces.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Joya entonces. abrazo
