### ISSUE TITLE
Newsletter Mayo ParexKlaukol. 28/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#304]
@FAAREIA necesitaría que, sobre la misma base del newsletter pasado, armes el newsletter de mayo. Llegás para mañana aunque sea a la tarde?

[Contenidos Newsletter ParexKlaukol MAYO Corregidos el 27-04.docx](https://github.com/LeandroBraier/Klaukol/files/239313/Contenidos.Newsletter.ParexKlaukol.MAYO.Corregidos.el.27-04.docx)

abrazo

**Comment by LeandroBraier** [comment]
Ahi te reemplacé el archivo porque agregué una pequeña novedad. Son las 17.30 hs. Bajalo de vuelta para estar seguros. abrazo

**Comment by FAAREIA** [comment]
Vamos a tratar de llegar, mañana justo me tengo que ir casi todo el día. Lo vi por arriba pero noté que agregaron un texto de bajada a las últimas noticias, lo cual no estaba contemplado en la base del template. ¿tiene que ir?
Con respecto al diseño de revear no vamos a llegar para el viernes, igual falta poco y el viernes seguro hay 1 o 2 pantallas de las 3 que faltan.

**Comment by LeandroBraier** [comment]
No te preocupes. Tengamos la web de Revear para el lunes.

La línea de más que decís de las últimas noticias no la pongas, solo el
título como hicimos el news pasado.

abrazo y gracias!

2016-04-27 18:18 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-04/16-04.html

**Comment by LeandroBraier** [comment]
Perfecto Fede!! Mil gracias!! Lo veo hoy con el cliente.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA te paso los links de las notas y unos ajustecitos para el lunes.

**TENDENCIAS**
http://www.parexklaukol.com.ar/novedades/todo-lo-que-querias-saber-sobre-el-boom-del-porcellanato.html

http://www.parexklaukol.com.ar/novedades/la-sustentabilidad-en-el-foco-del-debate-.html

http://www.parexklaukol.com.ar/novedades/haciendo-historia--alberto-prebisc--un-precursor-del-modernismo-en-argentino.html

**ÚLTIMAS NOVEDADES**
http://www.parexklaukol.com.ar/novedades/comienza-la-expo-estilo-pilar.html

http://www.parexklaukol.com.ar/novedades/los-condominios--un-modelo-de-negocio-que-gana-terreno.html

http://www.parexklaukol.com.ar/novedades/como-arranco-2016-en-el-sector.html

http://www.parexklaukol.com.ar/novedades/anuncian-el-nuevo-edificio-mas-alto-del-planeta.html

http://www.parexklaukol.com.ar/novedades/expo-arquitectura-berazategui.html

http://www.parexklaukol.com.ar/novedades/batimat--fematec--expo-construir.html

**Acordate también de corregir lo siguiente:**
1) Dice Newsletter de Abril y en realidad debería decir de Mayo.

2) La fecha de la nota de Estilo Pilar cambiala 15/04

3) Cambia la frase "Expo Arquitectura Berazategui" por "Comienza la Expo Arquitectura Berazategui"

4) Cambiar la frase "Batimat + FEMATEC + Expo Construir" por "Arranca Batimat + FEMATEC + Expo Construir"

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo estás?POrfa dale prioridad a este newsletter hoy. abrazo grande

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-05/16-05.html

**Comment by FAAREIA** [comment]
Cuando este OK al 100% avisame que hay que meter los estilos de una form especial antes de enviarlo

**Comment by LeandroBraier** [comment]
Está perfecto. Muy bueno lo del texto que de achica cuando ya leiste.

Solo fijatw que el Comenzó la Expo Estilo Pilar es 22/4

Lo demas perfecto. Si podes subimelo como template a mailchimp genial. Sino
pasame el codigo html con el estilo incluido y yo lo armo.

**Comment by FAAREIA** [comment]
Esta es la última versión:
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-05/16-05-mailchimp.html
No puedo entrar a mailchimp, ya se venció mi código. Cualquier cosa decime y me meto.

**Comment by LeandroBraier** [comment]
Dale, no te preocupes. Si puedo hacer copy-paste con el codigo fuente de esta URL estamos joya.

Gracias!
