### ISSUE TITLE
URGENTE CMS Parex caido

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#305]
@mkreyness me aparece error 505 al entrar al cms de Parex. El de VIE TUR funciona OK. Porfa apenas puedas fijate porque justo hoy tengo que hacer el sorteo. Ayer andaba bien.

**Comment by LeandroBraier** [comment]
<img width="1214" alt="captura de pantalla 2016-05-02 a las 8 44 25 a m" src="https://cloud.githubusercontent.com/assets/6719872/14953596/773947b0-1041-11e6-826f-97012efe885a.png">

**Comment by mkreyness** [comment]
Como siempre, aplicaron algun cambio de no se que que hizo que no encuentre el path. Lo mismo que paso unos dias antes en el servidor de Benteveo. Ya hice el ajuste para que sea inmune a eso.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! abrazo grande
