### ISSUE TITLE
Liberen a Pase de Gol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#306]
@mkreyness necesito que para el próximo lunes, 9 de mayo, el juego Pase de Gol que está actualmente en la Comunidad de Vendedores (y sigue funcionando) permita sumar puntos de forma ilimitada hasta el día 31 de mayo. 

Me confirmás si se puede y cuando lo hayas aplicado? 

Puede quedar desde este viernes sin problema.

abrazo

**Comment by mkreyness** [comment]
Si, no hay problema.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by mkreyness** [comment]
Ya quedo implementado. El 1ero de junio habria que verificar que vuelva a la situacion normal.

**Comment by LeandroBraier** [comment]
Me lo agendo, MK. Muchas gracias!!!!
