### ISSUE TITLE
Ver si se puede acceder con COnstruct 2

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#308]
@valentinsabbath , me decís si este juego una vez comprado se puede editr con Construct 2? 

http://codecanyon.net/item/flags/15674299

**Comment by ghost** [comment]
@LeandroBraier, está hecho con otro entorno de desarrollo que se llama "Game Maker". Según este post de Construct2 es posible la importación de elementos de Game Maker.
Pero, la importación puede no ser 100% completa, depende del juego.

https://www.scirra.com/tutorials/63/importing-gamemaker-rooms-and-objects-to-construct-2-free-edition

**Comment by LeandroBraier** [comment]
Ah ok. Entiendo. Es un pequeño riesgo. Podremos bajar algun juego
cualquiera cualquiera gratis para probar la importación?

**Comment by ghost** [comment]
https://www.scirra.com/forum/was-wondering-if-its-possible-to-import-gamemaker_t78030
The whole game won't convert over, only certain things like objects and rooms. You'll have to do all the code from scratch, unfortunately.

O sea que es imposible importar, solo importa algunas cosas.
Lo que veo que es el "memory game", no será mejor buscar un juego memoria hecho para construct y cambiar las imágenes que traiga por banderas?

**Comment by LeandroBraier** [comment]
Tal cual. Voy a pedir que hagan eso entonces. Gracias Valen!
