### ISSUE TITLE
Detalles Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#31]
Fede, te paso acá los pendientes de Comunidad de Vendedores.
1. Cambiar el video instructivo en la web por este que es el definitivo:

https://www.youtube.com/watch?v=st4CpBFJ-pI
1. Testear en IE9.

abrazo

**Comment by FAAREIA** [comment]
Hecho lo del video.
Lo de IE9 se lo delegué a Marce porque hay algo que rompe todo el sitio.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
```
Listo, prueben ahora.
El secreto es que IE9 no acepta paths relativos al sitio, hay que
poner el URL completo, si no lo IGNORA.

El 28/05/2015 a las 13:32,
  LeandroBraier escribió:

Gracias Fede!

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  On Thu, May 28, 2015 at 1:27 PM, Federico Arena
  <notifications@github.com>
  wrote:

  > Hecho lo del video.
  > Lo de IE9 se lo delegué a Marce porque hay algo que rompe
  todo el sitio.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/31#issuecomment-106465311
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by FAAREIA** [comment]
ajajaja, es una chatarra ese navegador. Ahora lo veo OK

**Comment by LeandroBraier** [comment]
Genial, Fede. Gracias!

En carpeta de Dropbox/BENTEVEO MAQUETADOR/KLAUKOL/Testeos Generales Web te
estoy subiendo capturas de error en distintos navegadores y dispositivos
reales, no simulados.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
ÚLTIMO UPDATE DE PEDIDOS:

Genial, además de los detalles uqe se ven en la carpeta de Testeos Generales, les paso dos detalles mínimos de texto de la home:

En Cómo participo

Donde dice "productos Klaukol" debe decir "productos ParexKlaukol"

Arriba del botón de "Empezá a jugar acá"

Donde dice "Sumate al Facebook de Klaukol" debe decir "Sumate a nuestro espacio en Facebook"

En la parte de "Cómo utilizo mis puntos…

Donde dice: "1 ticket equivale a 1 número dentro del enorme Tablero de la comunidad" debería decir "1 ticket equivale a 1 número en el sorteo del mes"

Donde dice "Y si este mes no ganaste, siempre tendrás una nueva oportunidad en el mes próximo." debería decir "Y si este mes no ganaste, siempre tendrás una nueva oportunidad en el mes próximo de jugar nuevos desafíos y volver a acumular puntos para el sorteo."

Reemplazar el texto del premio por el siguiente:

PARTICIPÁ POR UN FIN DE SEMANA IDEAL

1 fin de semana para vos y un acompañante

Alojamiento

Excursión

Traslado

Comidas
Te subo también un PPT con distintos detalles de corrección marcados específicamente en cada sección de la web. Lo subí al Dropbox en

BENTEVEO MAQUETADOR/KLAUKOL/COMUNIDAD DE VENDEDORES

abrazo

**Comment by LeandroBraier** [comment]
Fede, no te olvides de ir avanzando con todas estas modificaciones esta semana, como para tenerlas al menos para fines de la semana. Dánica sigue siendo prioridad pero no lo colguemos. Revisá el último ticket entero porque sumé cosas, lo edité.

abrazo

**Comment by LeandroBraier** [comment]
Fede, actualicé el ppt que está en BENTEVEO MAQUETADOR/KLAUKOL/COMUNIDAD DE VENDEDORES

Tiene correcciones detalladas que tendríamos que tener para lunes que viene a la tarde de ser posible.

Leelas y decime qué te parecen. Están muy gráficamente detalladas. Si querés hacemos un skype hoy a las 16 hs y lo charlamos punto por punto.

abrazo

**Comment by FAAREIA** [comment]
Ya esta todo Lea. Lo podes ver en:
http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl

Dale F5.

**Comment by LeandroBraier** [comment]
Buenísimo Fede!

Faltan cosas y veo errores. Por favor revisá todo el pedido y testeá la página, fijate que esté todo corregido y funcionando bien.

Por ejemplo: 

. sigue diciendo "enorme tablero de la comunidad"

. los links de la barra azul del menú de arriba no funcionan si entro a Mis logros.

. si voy a bases y condiciones la estética de los tickets no se ve bien.

Porfa revisen todo, esto es lo que vi a simple vista.

abrazo

**Comment by FAAREIA** [comment]
Ok ahora chequeo eso. Lo del texto ese de "enorme..." lo cambio por algo especifico o lo decido yo?

**Comment by LeandroBraier** [comment]
Estoy viendo que nunca te pasé las bases y condiciones definitivas. Todavía figuran las de Poett. Te las paso por mail en un doc y acá en texto.

abrazo

ORGANIZADOR
PAREXKLAUKOL S.A. (en adelante, el “ORGANIZADOR”), con domicilio en Av. Dr. Ignacio Arieta 3817, San Justo, Pcia de Buenos Aires, organiza el promoción denominada “COMUNIDAD DE VENDEDORES POTENCIADOS PAREXKLAUKOL” (en adelante, la “PROMOCION”).
VIGENCIA
La presente PROMOCION tendrá vigencia en el territorio de la República Argentina desde el día 1° de junio de 2015 al 31 de diciembre de 2015 inclusive (en adelante, “PLAZO DE VIGENCIA”).
ACEPTACIÓN DE LAS BASES
La mera participación en la PROMOCION implica la total e irrestricta aceptación y conocimiento de las presentes bases y condiciones (en adelante, las “BASES”), así como de las decisiones que posteriormente pueda adoptar el ORGANIZADOR en relación con cualquier punto o cuestión no previsto en el mismo, previa conformidad expresa de Lotería Nacional S.E.
LOS PARTICIPANTES
Podrán participar en la PROMOCION todas las personas físicas mayores de edad que comercialicen en cualquier punto de venta los PRODUCTOS PARTICIPANTES en alguna de sus presentaciones y sigan la mecánica descripta en el apartado MECÁNICA DE PARTICIPACIÓN de estas BASES (en adelante, el/los “PARTICIPANTE/S”).
EXCLUSIONES
Podrán participar en la PROMOCION todas las personas físicas mayores de edad que comercialicen en cualquier punto de venta los PRODUCTOS PARTICIPANTES en alguna de sus presentaciones y sigan la mecánica descripta en el apartado MECÁNICA DE PARTICIPACIÓN de estas BASES (en adelante, el/los “PARTICIPANTE/S”).
La mera participación en la Promoción implica el compromiso de los Participantes que sus acciones dentro de la plataforma no lesionen derechos de terceros ni vayan en contra de la moral y las buenas costumbres.
Para preservar el buen uso de la PROMOCIÓN, la PLATAFORMA y los perfiles y páginas de ParexKlaukol S.A.  en redes sociales, el Organizador se reserva el derecho de eliminar cualquier Pieza y/o comentario con contenido:
A) Discriminatario, abusivo, difamatorio o grosero;
B) Fraudulento o falso;
C) Que haga apología del delito o el odio de cualquier tipo;
D) Que viole cualquier normal o ley vigente en la República Argentina; 
E) Agresivo u ofensivos en general;
F) Que posea todos o la mayoría de sus caracteres en letra mayúscula, dado que es considerado una agresión en redes sociales e Internet en general;
G) Que mencionen productos sustitutos o de la competencia de la marca “Dánica”.
H) Pornográfico, desnudez y/o cualquier imagen o referencia no apta para todo público.

MECÁNICA DE PARTICIPACIÓN
Para participar de esta PROMOCIÓN, los PARTICIPANTES deberán subscribirse a la plataforma Comunidad de Vendedores Potenciados Parex Klaukol (en adelante, la PLATAFORMA) mediante cupones diseñados para tal fin. Luego de subscriptos recibirán un correo electrónico con su DNI y una clave, datos necesarios para ingresar a la PLATAFORMA ubicada en la dirección web www.parexklaukol.com.ar/vendedores/.
Dentro de la plataforma, podrán acceder a distintos tipos de contenidos sobre los productos de ParexKlaukol S.A. y jugar a distintos tipos de juegos que les permitirán sumar puntos. Por cada 100 puntos que sumen, obtendrán un ticket con un número de 5 cifras, con el cual participarán del sorteo realizado a fin de mes. Cuántos más tickets obtengan en el período del mes previo a cada sorteo mayores posibilidades tendrán de obtener el premio mensual.
A fin de mes, se realizará un sorteo ante escribano público en el cual se designará un ticket ganador. A partir del día del sorteo, todos los puntos y tickets obtenidos por los usuarios vuelven a cero y comienzan a sumar nuevos puntos y tickets para el siguiente premio mensual.

PREMIOS
El programa de premios de la presente PROMOCION está compuesto por:
PREMIO MENSUAL POR SORTEO:
Al final de cada mes calendario se realizará un sorteo entre todos los participantes. Cada uno participará mediante los números de tickets que haya obtenido durante dicho mes jugando y obteniendo puntos a través de la plataforma COMUNIDAD DE VENDEDORES. 
El premio mensual será variable y consistirá en 1 (un) viaje para 2 (dos) personas dentro del territorio nacional o 1 (un) articulo del hogar por un valor total de hasta $10000 c/u.

CONDICIONES DE PREMIOS:
En ningún caso los Premios podrán ser modificados o canjeado por otros, ni por su valor en dinero en efectivo, ni por un bien o servicio distinto de los indicados en el apartado PREMIO MENSUAL POR SORTEO.
Todos los costos derivados de la obtención de los Premios Semanales y del Premio Principal, así como los gastos en que incurran los Participantes que resulten ganadores como consecuencia de la obtención y entrega de los mismos incluyendo, pero no limitando, a impuestos, gastos de traslado y estadía, se encontrarán a exclusivo cargo, costo y responsabilidad de cada Participante ganador.
Se deja constancia que los Premios no son negociable, y que todos ellos son personales e intransferibles.
En caso que los premios establecidos en las presentes Bases no puedan ser entregados por causas no imputables al Organizador, los mismos podrán ser reemplazados por otros de igual o semejante valor, a elección exclusiva del Organizador.

RETIRO DE PREMIOS:
El plazo para retirar los Premios adjudicados es de treinta (30) días corridos a partir del anuncio de los ganadores por parte del Organizador y deberán ser retirados por las oficinas del Organizador, en Av. Dr. Ignacio Arieta 3817, San Justo, Pcia de Buenos Aires, de lunes a viernes en el horario de 10:00 a 17:00 horas. En caso de no poder asistir en el plazo determinado podrá coordinar entrega en persona por parte del Organizador, también dentro de los treinta (30) días corridos a partir del anuncio de los ganadores. 
Cada Participante ganador deberá acreditar su identidad y su pertenencia al Corralón correspondiente con su Documento Nacional de Indentidad y completar y suscribir el recibo correspondiente.
Los Participantes que resulten ganadores de los Premios serán notificados por el Organizador mediante correo electrónico a la dirección de correo electrónico proporcionada por el Participante ganador (conforme las presentes Bases) en el cupón de inscripción a la promoción. En caso de que el Organizador no pueda contactar a los Participantes potenciales ganadores de los Premios en el plazo de 10 días, se volverá  a sortear el mismo. 
En el caso de no poder presentarse en forma personal, el Participante que resulte ganador podrá designar una persona autorizada para el retiro del Premio, comunicando en forma previa al Organizador mediante Carta Documento.
Si el Participante ganador del Premio, o la persona que éste designe, no retirara su premio dentro del plazo indicado precedentemente, el premio en cuestión quedará en poder del Organizador, perdiendo el ganador todo derecho sobre el mismo.

Todos ellos y en su conjunto denominados los PREMIOS o individualmente como el PREMIO.
Los PREMIOS se asignarán conforme el procedimiento establecido en el punto 8.
El ORGANIZADOR no se hará cargo de ningún gasto extra y/o adicional en que incurra el ganador.
Los PREMIOS no serán transferibles a terceros ni canjeables por otro premio distinto del asignado -con excepción del PREMIO consistente en el automotor.
El PREMIO no incluye cualquier otro gasto, ni ningún otro servicio o bien distinto del expresamente mencionado en las presentes BASES, como así tampoco ningún impuesto en que el ganador deban incurrir para la utilización de los PREMIOS. El PREMIO no podrá ser reclamado por otras personas que no sean los ganadores. Si el ORGANIZADOR tomara conocimiento que el PREMIO ha sido comercializado por el PARTICIPANTE ganador, podrá dejarlo sin efecto en forma automática, sin derecho a compensación alguna.
Estarán a cargo del ganador los gastos de patentamiento, alistamiento, seguro, flete y cualquier otro relacionado con la transferencia del dominio y entrega del PREMIO indicado en el punto 7. También será a cargo del ganador el pago de los impuestos, aranceles, sellados, formularios, honorarios de profesionales y todo otro costo o gasto necesario para transferir e inscribir en el Registro de la Propiedad el dominio del automotor. El ORGANIZADOR no se hará responsable en caso de que el ganador no pueda efectuar dicha gestión.

**Comment by LeandroBraier** [comment]
Estaba en los pedidos que te pasé más arriba. Te los copio de nuevo aquí:

Donde dice: "1 ticket equivale a 1 número dentro del enorme Tablero de la comunidad" debería decir "1 ticket equivale a 1 número en el sorteo del mes"

Donde dice "Y si este mes no ganaste, siempre tendrás una nueva oportunidad en el mes próximo." debería decir "Y si este mes no ganaste, siempre tendrás una nueva oportunidad en el mes próximo de jugar nuevos desafíos y volver a acumular puntos para el sorteo."

Otro error que veo: revisá TODOS los links internos. Algunos llevan a versiones viejas o no listas de las páginas. Ejemplo:

http://www.parexklaukol.com.ar/vendedores/home.html

abrazo

**Comment by FAAREIA** [comment]
Ahi ya lo cambié todo.
Ahi encontré un bug y se lo pasé a marce.
Lo que también necesitaría probar es la trivia, pero necesito un usuario. Ya se lo pedí a marce también.

**Comment by mkreyness** [comment]
```
No pude reproducir el bug, a mi los links me abren bien.
Pasame desde que URL es que no te abren.

Usuario virgen de puntos:

Usuario: test
pass: pepe


El 08/06/2015 a las 13:05, Federico
  Arena escribió:


  Ahi ya lo cambié todo.
    Ahi encontré un bug y se lo pasé a marce.
    Lo que también necesitaría probar es la trivia, pero necesito un
    usuario. Ya se lo pedí a marce también.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Abrir me abren pero hay errores en las URLS. Yo estoy entrando desde:

http://www.parexklaukol.com.ar/_vendedores3/login.html

Desde donde debería entrar ahora?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-08 13:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Ese URL es viejo. Se entra oficialmente desde

http://www.parexklaukol.com.ar/vendedores

y si queres entrar como un usuario, haces click en "iniciar sesion"
y pone user/pass.

El 08/06/2015 a las 13:50,
  LeandroBraier escribió:

Abrir me abren pero hay errores en las URLS. Yo estoy
  entrando desde:

  http://www.parexklaukol.com.ar/_vendedores3/login.html

  Desde donde debería entrar ahora?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-08 13:42 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > No pude reproducir el bug, a mi los links me abren bien.
  > Pasame desde que URL es que no te abren.
  >
  > Usuario virgen de puntos:
  >
  > Usuario: test
  > pass: pepe
  >
  >
  > El 08/06/2015 a las 13:05, Federico
  > Arena escribió:
  >
  >
  >
  > Ahi ya lo cambié todo.
  > Ahi encontré un bug y se lo pasé a marce.
  > Lo que también necesitaría probar es la trivia, pero necesito
  un
  > usuario. Ya se lo pedí a marce también.
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/31#issuecomment-110069251
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Fede, está OK la comunidad. Necesito que cuanto hagas lo siguiente en el siguiente orden:

1) Quitar el slide "Hay 2 juegos nuevos"

2) Habilitar el link a la Comunidad de Vendedores en la home de ParexKlaukol y en donde más corresponda.

3) Que en la página de los juegos, por ejemplo donde está ahora el video de Klaukol Impermeable Potenciado, donde dice "Jugá y Sumá Puntos", que además de VIDEO, PDF y TRIVIA, aparezca COMPARTIR EN FACEBOOK y que eso sume 30 puntos también.

4) En las bases y condiciones, en donde dice "El premio mensual será variable..." reemplazar por el siguiente texto:

El premio consistirá en 1 (un) viaje para 2 (dos) personas dentro del territorio nacional saliendo desde la Ciudad Autónoma de Buenos Aires.  Si la persona ganadora no es habitante de la Ciudad de Buenos Aires se entregará un viaje de igual valor que salga de un punto cercano a la zona donde se encuentra.  

En el mes de junio entregaremos 1 (un) viaje a la ciudad de Mendoza para 2 (dos) personas. 
El paquete incluye 
·        Pasaje aéreo Bue Mendoza Buevolando por Aerolineas Argentinas en clase R. 
·        Traslados Aeropuerto-Hotel-Aeropuerto 
·        3 noches de alojamiento con desayuno en el hotel NH Cordillera en base doble.

Si la persona que resulte ganadora no es habitante de la Ciudad de Buenos Aires podrá pedir al Organizador el canje por un viaje de igual valor de hasta $8.000 + IVA. 

Avisame cuando estén hechos estos 4 puntos.

abrazo

**Comment by LeandroBraier** [comment]
Fede, ahí te actualicé este ticket.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta todo menos el punto 3. ¿Lo de compartir lo saco del título entonces?

**Comment by LeandroBraier** [comment]
Si, mejor. Que quede abajo para que quede claro que suma puntos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Te está faltando el Desarrollado por Benteveo abajo de todo. No te olvides.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 17:39 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Ok, voy a tratar de hacerlo hoy eso. Marce tiene que programar lo suyo ahi, ahora hay una instancia de "hecho" o "compartido" como las trivias

**Comment by LeandroBraier** [comment]
Perfecto Fede. MK, avisame cuando lo hayas podido implementar porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 18:37 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Oops, no se de que me hablan.
Que miro donde, Fede ?

**Comment by mkreyness** [comment]
Otra cosa: los puntajes que yo puse a cada juego eran cualquier cosa 
inventada, nunca me enteré qué poner, cuales son los puntajes CORRECTOS 
para cada cosa ?
Esta todo parametrizado en el CMS, pero hay que poner la verdad.

Tengo la siguiente lista de actividades cada una que tiene un puntaje 
independiente:

```
     Ingresar (diariamente) a la comunidad
     Completar el perfil (esto es basicamente subir la foto)
     Completar los datos del corralon (esto ojo que ya estan 
```

cargados los datos)
         Sumarse a nuestro Facebook
         Ver el video y completar la Trivia del tema "Klaukol 
Impermeable Potenciado"
         Bajar documentos y Completar la Trivia del tema "Klaukol 
Impermeable Potenciado"
Completar la Trivia del tema "Klaukol Impermeable Potenciado"

Cada juego tiene un puntaje propio excepto las trivias, donde hay un 
puntaje independiente por cada pregunta.
De todos modos el maximo teorico del juego (si contesta todas las 
preguntas de la trivia) lo tengo que cargar en el juego para que lo 
muestre, y NO se suma.

Va a haber realmente puntajes adicionales diferentes si completa la 
trivia bien habiendo bajado el documento que si no lo hizo ?
Porque "mirar el video" o "contestar la trivia sin mirar el video" en 
realidad es lo mismo, no lo podemos diferenciar.
Y habria que dar un puntaje extra si habiendo contestado la trivia sin 
bajar los doc igual despues entra a alguno de los links ?

y por lo que dicen aca habria que agregar otra actividad que seria 
compartir algo ?

**Comment by FAAREIA** [comment]
Ahi ya metí / reubiqupé lo del facebook en el juego. Necesitaría un usuario activo para poder verlo.

Marce, lo de facebook en el juego, es el "me gusta" y "compartir" que estaba puesto al lado del título. Antes no sumaba puntos, pero ahora parece que si. +30

**Comment by mkreyness** [comment]
user: marcelokreyness
pass: pepe

**Comment by FAAREIA** [comment]
Gracias. Ahi se puede ver la modificación.
http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?usuario=marcelokreyness&clave=pepe&id=1

**Comment by LeandroBraier** [comment]
Solo dice Facebook, Fede. Debería decir "Compartir en Facebook" + 20 puntos

abrazo

**Comment by FAAREIA** [comment]
Ok, igual no es un botón eso. Los botones van a ser si o si los del costado.

**Comment by LeandroBraier** [comment]
Entiendo. Quiero decir que Facebook +20 puntos no se entiende qué es. En
todo caso ponelo así y debajo poné el texto:

"Compartí este contenido y sumá puntos"

Sino el usuario no lo entiende.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Marce, acá te respondo en detalle lo que preguntás. Algunos puntajes del front los cambio en función de tus comentarios pero en general los veo correctos. De última el cliente va a pedir cambiarlos y listo.

Ingresar a la comunidad por primera vez: 30 puntos  
Ingresar (diariamente) a la comunidad: 5 puntos
         Completar el perfil (esto es basicamente subir la foto): 60 puntos
         Completar los datos del corralon (esto ojo que ya estan cargados los datos): 60 puntos
         Sumarse a nuestro Facebook: 60 puntos
         Ver el video y completar la Trivia del tema "Klaukol Impermeable Potenciado" 60 puntos
         Bajar documentos y Completar la Trivia del tema "Klaukol Impermeable Potenciado" 60 puntos
         Completar la Trivia del tema "Klaukol Impermeable Potenciado" (sin ver video ni doc) 60 puntos
         Compartir en Facebook: 20 puntos

Si te falta algo decime. Sino decime donde los cargo y los cargo yo.

Consultas:

El Compartir en Facebook ya está funcionando?

Estoy viendo que no está el Facebook Connect. El Facebook Connect debería estar en Tu Perfil y debería sumar 60 puntos también.

El máximo teórico del juego qué es? El máximo de puntos total que puede sumar un usuario? No termino de entender eso. Decime y te hago las cuentas y te lo paso ahora si es necesario.

abrazo

**Comment by mkreyness** [comment]
```
Contesto inline

El 10/06/2015 a las 0:10, LeandroBraier
  escribió:


  Marce, acá te respondo en detalle lo que preguntás. Algunos
    puntajes del front los cambio en función de tus comentarios pero
    en general los veo correctos. De última el cliente va a pedir
    cambiarlos y listo.
  Ingresar a la comunidad por primera vez: 30 puntos



Ves, eso NI lo tenia. Lo tengo que programar.



    Ingresar (diariamente) a la comunidad: 5 puntos



Ok, cambiado.


  Completar el perfil (esto es basicamente subir la foto): 60
    puntos



Cambiado


   Completar los datos del corralon (esto ojo que ya estan
    cargados los datos): 60 puntos



Cambiado


   Sumarse a nuestro Facebook: 60 puntos



Cambiado


   Ver el video y completar la Trivia del tema "Klaukol
    Impermeable Potenciado" 60 puntos



Entonces cada pregunta es 30 y no 15, cambiado.


   Bajar documentos y Completar la Trivia del tema "Klaukol
    Impermeable Potenciado" 60 puntos



misma trivia entonces.


   Completar la Trivia del tema "Klaukol Impermeable Potenciado"
    (sin ver video ni doc) 60 puntos



misma trivia entonces.


  Compartir en Facebook: 20 puntos


Agregado, ojo, todavia sin implementar.


  Si te falta algo decime. Sino decime donde los cargo y los
    cargo yo.
  Consultas:
  El Compartir en Facebook ya está funcionando?


No.


  Estoy viendo que no está el Facebook Connect. El Facebook
    Connect debería estar en Tu Perfil y debería sumar 60 puntos
    también.


No lo vi ni maquetado.
Cual seria la idea ? Un boton de "login  por facebook" en vez de
user/pass ? Pero eso tendria que estar en el propio login, no en el
perfil.


  El máximo teórico del juego qué es? El máximo de puntos total
    que puede sumar un usuario? No termino de entender eso. Decime y
    te hago las cuentas y te lo paso ahora si es necesario.


30+30 = 60, eso nomas. Pero el usuario PODRIA ganar solo 30.


  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto todo.

El Facebook Conect no puede estar en el login porque tenemos que validar sí o si que es un vendedor. Por eso digo de ponerlo en el Perfil. En realidad más que un Login es una conexión entre ambas cuentas. Esto lo vamos a necesitar más adelante para armar grupos en facebook etc. No se puede hacer eso?

Respecto del total teórico sigo sin entender pero si ya está respondido en lo anterior genial. Cuando puedas explicamelo.

abrazo

**Comment by mkreyness** [comment]
```
No entiendo como podriamos "unirlas", porque no podemos pedirle la
contraseña de facebook.
A lo sumo guardar su nombre, pero con eso solo no hacemos nada,
siempre necesitamos que este loggeado para actuar en su nombre.
Lo unico que existe es que estando loggeado podemos mostrar en
nuestro sitio las caras de sus amigos o cosas asi, eso es el
facebook connect.

Total teorico: olvidate, es una pavada.
Digo "teorico" porque no podemos asegurar que gane esos puntos, eso
es lo que GANARIA si contestara todo bien. Para no tener que
sumarlos, ya tengo el total guardado en un solo lado.


El 10/06/2015 a las 0:36, LeandroBraier
  escribió:


  Perfecto todo.
  El Facebook Conect no puede estar en el login porque tenemos
    que validar sí o si que es un vendedor. Por eso digo de ponerlo
    en el Perfil. En realidad más que un Login es una conexión entre
    ambas cuentas. Esto lo vamos a necesitar más adelante para armar
    grupos en facebook etc. No se puede hacer eso?
  Respecto del total teórico sigo sin entender pero si ya está
    respondido en lo anterior genial. Cuando puedas explicamelo.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
Ahi implemente lo de diferenciar primer ingreso a la comunidad de primer ingreso DEL DIA.
Tambien detecte otra cosa: habia puntajes fijos en el template del perfil, dicen 60 por perfil y 120 por corralon. Ahi lo parametrice en el template y ahora lo toma del CMS. Lo mismo el nuevo de compartir en facebook.
Otra cosa, Fede: el share que pusiste queda vacio en FB, seguramente hay que agregar algo mas, como la foto del producto, parece que con la pagina sola no muestra nada.

De todos modos, esto va para ambos: llevo horas investigando y no hay manera de saber si el usuario realmente lo shareó, porque NO hay callback de los eventos de share.
Solo puedo trackear el LIKE. Una de dos: o sacamos el boton de Compartir, o me tengo que colgar del evento de que lo clickee, pero no podemos saber si no lo cancelo despues.

**Comment by mkreyness** [comment]
y aun para hacer esto de trackear el click sobre el boton de share tal como esta hecho (como un atributo opcional del boton de like) tampoco puedo, habria que implementar cada boton por separado.
Me parece al cuete el share, el like a una pagina (como estamos haciendo, que lo haga del micrositio del producto) siempre permite agregar un texto, asi que no difiere mucho del share.
El like ya esta generando puntos (una sola vez por tema).

**Comment by LeandroBraier** [comment]
Ok. Buenisimo lo del like. Y lo del share hagamoslo por separado entonces Fede. Gracias MK!

Por ahora entonces el Facebook Conect dejemoslo en suspenso. Lo vamos a agregar para los que se quieran sumar a alguna parte en especial de la comunidad. Eso se puede hacer? Como un segundo login dentro del login?

**Comment by mkreyness** [comment]
```
Si, de hecho cualquiera de los botones de like/share si no esta
previamente loggeado en facebook lo hace loggearse. Yo entiendo que
cualquier accion especifica de facebook que pongamos en cualquier
lado (que son comentar, likear, sharear, no se me ocurre ninguna
otra) implicitamente siempre va a tener un login, y no nos
corresponde estar guardandonos nada, eso lo maneja facebook.

El 10/06/2015 a las 8:21, LeandroBraier
  escribió:

Ok. Buenisimo lo del like. Y lo del share hagamoslo
  por separado entonces Fede. Gracias MK!

  Por ahora entonces el Facebook Conect dejemoslo en suspenso. Lo
  vamos a agregar para los que se quieran sumar a alguna parte en
  especial de la comunidad. Eso se puede hacer? Como un segundo
  login dentro del login?

  mkreyness <notifications@github.com> escribió:
```

**Comment by FAAREIA** [comment]
Entonces chau share. Y lo del facebook connect no va tampoco no?

**Comment by mkreyness** [comment]
```
Ojo que el template juegoT.html lo tuve que tocar bastante por los
cambios, sacale el share pero a lo que esta en el server, no me lo
pises.

El 10/06/2015 a las 8:37, Federico
  Arena escribió:


  Entonces chau share. Y lo del facebook connect no va tampoco
    no?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias a los dos!

Cierro el ticket y después si hay cosas son con issue puntual.

abrazo
