### ISSUE TITLE
Ajuste de foto en Club de Colocadores. 27/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#310]
Fede, nos falta cambiar una foto del Club de Colcoadores, la que está abajo de TU TRABAJO VALE.

<img width="1583" alt="captura de pantalla 2016-05-20 a las 1 02 17 p m" src="https://cloud.githubusercontent.com/assets/6719872/15433245/e6e19960-1e87-11e6-9482-7abe80e3e7e0.png">

Cambiala por esta:

![foto-tu-trabajo-vale-colocadores-new](https://cloud.githubusercontent.com/assets/6719872/15433324/45ee13c0-1e88-11e6-86f8-5164d585279d.png)

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA hoy podés resolver esto porfa antes de la call?

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!
