### ISSUE TITLE
Asignar puntos Vendedores por acertar

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#311]
@mkreyness cómo va?

Necesito que le asignes a los siguientes usuarios el juego "Acertar Trivia Final del Torneo" a todos los usuarios que respondieron "San Lorenzo" en la 3er pregunta de la "Trivia Final del Torneo".

Me confirmás porfa?

abrazo

**Comment by mkreyness** [comment]
Lei bien ? 540 puntos son a c/u ?

**Comment by LeandroBraier** [comment]
En realidsd serían 360, ahi lo corregí. Lo que les decimos es que si
aciertan, triplican los puntos. Como la trivia sumaba 180, triplicado daba
540. Ahora lo pasé a 360 para que en total sume 540.

Gracias por alertar!

abrazo

**Comment by mkreyness** [comment]
Ahi les cargue, ojo DESHABILITASTE el juego, si no alguno va a hacerse el vivo y despues decir que por que no le dieron los puntos.
Ahora les agrego 3 fichas a todos y veo a cuales el saldo les daba como para una ficha mas con los "60".

**Comment by LeandroBraier** [comment]
jajaja Dale, perfecto. Si, ya suspendí el tema y el slide correspondientes.
Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-05-23 11:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
listas las fichas.

**Comment by LeandroBraier** [comment]
Gracias MK!!!!
