### ISSUE TITLE
Arreglar Geolocalización Guia de Corralones. 25/05

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#312]
@mkreyness Para arreglarlo cuando se pueda.

http://www.parexklaukol.com.ar/guia-corralones/

**Comment by LeandroBraier** [comment]
@mkreyness hoy podés resolver esto porfa antes de la call?

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Porfa apenas puedas resolvé esto que es importante para la landing que está haciendo Fede también.

abrazo

**Comment by mkreyness** [comment]
Ahora me fijo

**Comment by mkreyness** [comment]
listo
