### ISSUE TITLE
Newsletter Junio ParexKlaukol. 30/05

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#313]
@FAAREIA te paso el contenido para el newsletter. Lo necesitaría para el lunes de ser posible. Confirmame si llegás porfa.

[Contenido Newsletter ParexKlaukol JUNIO v26-05.docx](https://github.com/LeandroBraier/Klaukol/files/284787/Contenido.Newsletter.ParexKlaukol.JUNIO.v26-05.docx)

abrazo

**Comment by FAAREIA** [comment]
Lea, me lo puse a hacer pero lo corté porque falta demasiada información.
- La imagen de portada tiene que ser de 640x360
- La imagen de portada sirve como intro a una nota que el template del mailing NO tiene. Hay que agregarlo.
- Las notas de tendencias, etc estan con links que no son los finales
- La nota de Innovaciones no tiene texto y la foto no sirve, vean el template antes de preparar fotos.
- Si va haber 1 "Producto del mes", pasarme una imagen de al menos 640px de ancho.
- Las "Últimas novedades" tienen mal la fecha, un texto que no tiene lugar en el template y link externos.

**Comment by LeandroBraier** [comment]
Ok. Hoy te paso todo esto asi el lunes podes armar el news de una. No te
preocupes.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Te paso acá el word corregido con los links y las imagenes en un zip. Confirmame si podemos tenerlo armado para hoy a la tarde estamos OK. abrazo

[Contenido Newsletter ParexKlaukol JUNIO v31-05.docx](https://github.com/LeandroBraier/Klaukol/files/291034/Contenido.Newsletter.ParexKlaukol.JUNIO.v31-05.docx)

[Imagenes Newsletter Junio.zip](https://github.com/LeandroBraier/Klaukol/files/291035/Imagenes.Newsletter.Junio.zip)

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-06/16-06.html
No manden ese porque hay que hacer algo con los estilos, simplemente es para verlo y probar los links.
Fijate el tema de las fechas de ultimas novedades, seguro haya que acomodar alguna

**Comment by LeandroBraier** [comment]
Está perfecto salvo el link de la nota del Lanzamiento, te la pasé mal.

El link sería este: http://www.parexklaukol.com.ar/busca-gran-colocador/

Cuando lo tengas avisame porfa.

abrazo

**Comment by LeandroBraier** [comment]
Perdón, la última fecha tenés razón que está mal. La nota de "23 al 27-05: I Encuentro Nacional sobre Ciudad, Arquitectura y Construcción Sustentable" debería ir debajo de la de TENDIEZ con la fecha 23/05

Con eso estamos. abrazo

**Comment by FAAREIA** [comment]
Fijate ahora

**Comment by LeandroBraier** [comment]
Está perfecto el link. Lo de Novedades que te pedí aparte todavía no lo veo.

**Comment by FAAREIA** [comment]
Dale f5, lo corrí ya

**Comment by LeandroBraier** [comment]
Está perfecto @FAAREIA !! Gracias!!! abrazo grande

**Comment by FAAREIA** [comment]
Ojo de NO mandarlo por mail aún, cuando este OK avisame y le meto los "estilos inline".

Abrazo

**Comment by LeandroBraier** [comment]
Dale, entiendo. Reabro el ticket por las dudas.

Te aviso.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA está aprobado el pedido!

Solo pidieron agregar el siguiente texto debajo del título CASA INTERACTIVA:

"Conocé la Casa Interactiva de ParexKlaukol! Esta herramienta te ayudará a elegir el productor que mejor le queda a tu obra"

![ajuste en innovaciones](https://cloud.githubusercontent.com/assets/6719872/15764495/93a29d06-2901-11e6-8edd-5ce749e80241.jpg)

Si mañana a primera hora podés ajustar esto y ya dejarle los estilos inline cierro el ticket nomás.

abrazo

**Comment by FAAREIA** [comment]
Lo estaba tratando de subir pero se cayó el server de Duplika

**Comment by LeandroBraier** [comment]
Está caido. Gracias por avisar! abrazo

**Comment by LeandroBraier** [comment]
Te aviso cuando Duplika lo sube de nuevo

**Comment by LeandroBraier** [comment]
Se olvidaron de renovar el dominio. Ya están tramitando eso. Te confirmo.

**Comment by LeandroBraier** [comment]
Ya está arriba el sitio de vuelta @FAAREIA !!! Podés subir el news ya. Confirmame porfa.

abrazo y gracias

**Comment by FAAREIA** [comment]
Ahi va!
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-06/16-06-inline.html

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Muchas gracias!!

Lamentablemente me piden una versión paralela de este news sin la primera nota, es decir, sin la imagen y texto que hace referencia a la Campaña "Klaukol en Busca del Gran Colocador". Es mucho lio hacerla?

Hacela en un link aparte por las dudas si se puede, así nos quedan las 2 versiones.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-06/16-06_2.html
Fijate ahi lea

**Comment by LeandroBraier** [comment]
Gracias Fede! Está OK pero quitá la foto de Potenciados del header.
Reemplazala por esta:

http://homejoss.com/wp-content/uploads/2016/05/surprising-beautiful-stone-fireplaces-then-model-gallery-design-ideas.jpg

**Comment by FAAREIA** [comment]
dALE f5

**Comment by LeandroBraier** [comment]
Casi perfecto @FAAREIA !!! Gracias!!! Solo tendrías que cambiar el link de "Ver en el navegador" por el link actual y cierro el ticket.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!! abrazo grande
