### ISSUE TITLE
Feedback Web Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#314]
@FAAREIA va el feedback del cliente y la última revisión mia. Confirmame si podemos aplicarlo mañana a esto así ya publicamos mañana mismo.

1) La última modificación en productos que hiciste el martes no se ve bien en Chrome:

<img width="851" alt="captura de pantalla 2016-05-26 a las 4 40 15 p m" src="https://cloud.githubusercontent.com/assets/6719872/15587107/1ab2dabc-235e-11e6-9e65-72d7c28a620a.png">

2) Cambiar la foto del fondo de la página de Selección de Usuario por esta foto (aunque agregándole el filtro de oscuridad que vos le ponés para que quede bien).

![slide2-textura-que-decora-y-protege-hd-revear-usuario-final](https://cloud.githubusercontent.com/assets/6719872/15587934/ed79eb4a-2361-11e6-824c-fe21ed00e083.jpg)

3) Calculador de Consumo: chequeá que se vea bien en la mayor parte de los navegadores. No sé en qué navegador lo ve el cliente pero dice que se le superponen los campos a completar con el título "SUPERFICIE A REVESTIR"

4) Cambiar el Link a YOuTube a un nuevo canal del que tenemos pleno control: https://www.youtube.com/channel/UC-iXrheUeGNyEzGA32hRusQ

5) Esto último es sin apuro, pero si lo podés hacer hoy también general. Ya lo hicimos para el canal de YouTube de Parex. Es un proceso para vincular la página web con el canal de YouTube y poder obtener la URL personalizada.

> ## 
> 
> Vinculación del webmaster
> Verifica tu sitio web con las Herramientas para webmasters de Google. El webmaster verificado puede aprobar una solicitud para conectar tu sitio web con la página de Google+ de tu empresa.
> Selecciona Mi Negocio >  Página de Google+ en el menú de navegación que se encuentra a la izquierda.
> En la pestaña "Acerca de", haz clic en el botón Vincular sitio web que se encuentra junto a la URL del sitio web.
> ¿No ves el vínculo? Esto se debe a que las páginas de Google+ locales no son aptas para vincularse a un sitio web. Puedes agregar tu sitio web a la información de tu empresa siguiendo estos pasos.
> Si sabemos quién es el webmaster de este sitio web, te ofreceremos la opción de enviarle una solicitud para que apruebe el vínculo. Si le envías dicha solicitud, el webmaster conocerá tu dirección de correo electrónico.
> El webmaster verificado puede confirmar el vínculo en Herramientas para webmasters de Google.
> Una vez que se apruebe el vínculo, recibirás un correo electrónico. También verás una marca de verificación verified checkmark junto al sitio web en la pestaña "Acerca de" del perfil de tu página.
> 
> Después de que vincules tu página de Google+ con tu sitio web, también podrás vincular tu sitio web con tu página para dirigir a los clientes a la presencia de tu empresa en redes sociales. Más información sobre cómo agregar la Insignia de Google+ a tu sitio web

Solo eso. Gracias @FAAREIA ! Vamos todavia!

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Porfa podrás resolver esto hoy? La landing empezala pero puede estar para el lunes. Seguro hoy te paso los cambios estéticos que haya.

**Comment by FAAREIA** [comment]
No hay drama, te aviso cuando este. Al mediodía recien puedo ponerme con todo

**Comment by FAAREIA** [comment]
- Todo listo
- Le sume un favicon
- Le puse el código de Google Analytics
- Registré revear.com.ar en Herramientas Google

La explicación de los de YouTube es de Google +, pero imagino que ahora que el sitio esta conectado a las Herramientas de Google, van a poder crear el canal de Revear en Youtube. Decime cualquier cosa

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA !!! Excelente lo del Favicon?

No entiendo lo del canal de Revear en YouTube. Ya está creado, te referís a la URL customizada?

**Comment by FAAREIA** [comment]
Yo me metí con la cuenta de parexklaukol y no tenia ningun canal según vi =/. Estan usando otra cuenta para revear?

**Comment by LeandroBraier** [comment]
Sip. El link que te pase en el primer comment de este thread. Fijate. Lo
tenes ahi.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! 

**1.** Revisé y era en el ticket anterior. Te paso de nuevo el link así es más fácil: https://www.youtube.com/channel/UC-iXrheUeGNyEzGA32hRusQ

Ese es el canal que tenés que usar y seguir las instrucciones que te pasé de Vinculación del Webmaster. El acceso a la cuenta de Gmail correspondiente es el siguiente:

revearparex@gmail.com
sentirparedes

No nos sirve cualquier vinculación a Google Plus, nos sirve esta porque ya tenemos el canal creado. Deicme si necesitás algo más asi ya cerramos esta web de revear. 

**2.** El cliente me debe respuesta sobre la foto de fondo de la home de selección de usuario. Si no le gusta esa vamos a probar con esta otra. Te la dejo subida en opción brillante y opaca por las dudas porque hoy tengo reuniones todo el día. Escribime por whatsapp cualquier cosa.

![fondo-marble-rulato-revear](https://cloud.githubusercontent.com/assets/6719872/15649135/95bb0772-2645-11e6-9231-13db7a6c81ed.jpg)

![fondo-marble-rulato-revear-opaco](https://cloud.githubusercontent.com/assets/6719872/15649137/98540a9c-2645-11e6-9532-ac880e87033a.jpg)

abrazo

**Comment by LeandroBraier** [comment]
Fede me contestó el cliente sobre la foto de la home. Me pasas el original
de la que estaba antes? Le agrego textura revear a esa foto y te la paso
para dejar esa, que les gustó  (como refe, es la misma que esta en empresa )

Abrazo

**Comment by FAAREIA** [comment]
Cuando la guardes, guardala para web desde photostop o illustrator que si la guardas como un jpg común pesa muchisimo más el archivo.

![reve-intro](https://cloud.githubusercontent.com/assets/6184969/15650462/1c0bc826-264f-11e6-9da2-675a6074cb1f.png)

**Comment by LeandroBraier** [comment]
Dale entiendo. Abrazo y gracias!

**Comment by LeandroBraier** [comment]
Fede aca esta la foto:

https://mega.nz/#F!MAQhCI5a!Mdqu6rEM-4SivFWI0wvtRg

Confirmame recepción.

**Comment by LeandroBraier** [comment]
![casa-con-textura-marble-y-marble-almendra](https://cloud.githubusercontent.com/assets/6719872/15657206/3d6af2cc-2685-11e6-9e51-34002ec863ad.jpg)

Te la subo lo más comprimida posible.

abrazo

**Comment by FAAREIA** [comment]
Ahi la subí, denle F5
Fijate que seguro no estes usando el "guardar para web", aca en PC el atajo es ctrl+alt+shift+s

**Comment by LeandroBraier** [comment]
Lo veo joya! Gracias Fede!! Les doy el OK en breve para que ya publiquemos la web nueva en la URL principal.

**Comment by LeandroBraier** [comment]
Chicos, tenemos el OK para subir la web. @mkreyness avisame porfa cuando lo tengas online. Me dijo Fede que recién a las 20 hs volvías, no hay problema. Avisame nomas cuando lo subas aunque sea tarde.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA mientras MK publica y una vez cerrada la landing y los mailings de la competencia de Colocadores, empezá a trabajar ya la versión responsive de Revear porfa.

**Comment by mkreyness** [comment]
Ojo no lo trabajes sobre _beta Fede porque si bien yo voy a intentar que no quede ningun link referenciado a ahi, capaz se me escape alguno.

**Comment by mkreyness** [comment]
Publicado !
Yo veo todo bien, pero peguenle una revisada a ver si detectan algo que falle.
@LeandroBraier una cosa que habria que cambiar es en los productos del slide que apunten a los URLs estatico de cada producto y no al cgi-bin

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !

En general no veo fallas graves. Estoy viendo cosas que se ve que nunca ajustamos. Hagamoslo mañana antes de lo responsive @FAAREIA porfa.

**1) PRODUCTO**

Nombres de colores se tapan:

<img width="178" alt="captura de pantalla 2016-05-30 a las 11 14 01 p m" src="https://cloud.githubusercontent.com/assets/6719872/15660925/f4c00ace-26b8-11e6-8d9a-d0c1cf49c4bb.png">

**2) TEXTURAS**

La versión particulares se ve igual que la de profesionales, pero era distinta. Aplicá la versión de particulares por favor @FAAREIA Para particulares no debe hablar de programas 3D ni nada de eso. Solo ve las texturas y, si hace clic, se descarga la textura, nada más. Es decir, las funciones son iguales, cambian los textos.

Te pasé esto el 30 de marzo :

VERSIÓN USUARIOS FINALES
La variedad de texturas de Revear te permite dar un toque de vida a tu fachada y paredes. Conoce en nuestra página de TEXTURAS, toda la variedad de productos Revear y proyectá como pueden quedar en tu próxima casa o en la remodelación de tu hogar.

TEXTURAS
(Mosaico de JPGs que muestran la textura del producto. Mouse over dice el nombre del producto y al hacer clic descarga el JPG correspondiente a su PC)

**3) CALCULADOR DE CONSUMO**

¿Esto no llevaba imagen? El cliente no dijo nada aún pero me parece que había algo no?

**4) LINK A SPOTIFY**

Porfa sumá una red social más a la web, que es la de spotify. Va el link:

https://open.spotify.com/user/reveararg/playlist/77TILlZ800DMOQxZgOAI4g

abrazo

**Comment by mkreyness** [comment]
@FAAREIA yo ya deje en /templates/revear un template (copiado del que estaba ahora) con nombre texturas-profesionalT.html, para que lo tome en las profesionales.
Modifica vos el /templates/revear/texturaT.html (que seria el de particulares) y ya con eso quedaria.

**Comment by FAAREIA** [comment]
Algunos detalles que vi, Lea decidirá si se hacen o no.

@LeandroBraier 
- Las imagenes de la sección Texturas pesan mucho. Abro una foto y veo que pesan 320KB, la bajo al photoshop y si la guardo para web a 60 de calidad, pesa 100KB. Osea, si las imágenes de la sección se guardan para web, la página carga 3 veces más rápido que antes. **60 de calidad es mucho para una textura en donde el ruido o la compresión no se nota, se podría hasta darle 50. El tema es bajar en 1/3 el peso de la página.**
- [En este producto](http://www.revear.com.ar/productos-para-particulares/revegrain.html) la parte de rendimiento quedó mal, imagino que es porque se cargó asi en el CMS. **Pasame el ícono de soplete y a mano cuado puedas. Esto quedó colgado.**
- Faltan todas las meta descriptions y los title. **Los title en realidad ya estan, faltan las descripciones para páginas como Texturas, Ventajas, etc. Para los productos o novedades no hace falta creo**
- Faltan todos los OpenGraph, principalmente la imagen de cada sección. Secciones como Contacto o Empresa, tendrían la misma imagen que el home, sería el mismo OpenGraph. Pero sería distinto en secciones compartibles como novedades, productos, calculador, guia, novedad y producto y capas otras que me olvidé.**El formato es el mismo, 1200x630 y pone el logo más grande porque se achica a menos de la mitad en el facebook**

## 

@mkreyness 
- Falta hacer el botón de FB y Pinterest en Tendencia y Producto **CUANDO PUEDAS HAGANLO**
- Si no hay video en el Producto, el bloqué sigue apareciendo. **SI SE PUDIERA SACAR SOLO EN ESOS CASOS GENIAL**
- Las texturas de los productos no tienen thumb. Hay que generarlas porque a un usuario de celular la página le va a tardar muchisimo en cargar. El thumb tiene que ser de 72x72 y lo haría cropeando un pedazo de la imagen, achicando la imagen a 72x72 NO porque perdes el detalle de la textura. **ENTIENDO. LAS PUEDO SUBIR YO (LEAN)?**

## 

@FAAREIA  (no puedo autotaguearme)
- ~~En texturas ver la línea del hover cuando un título tiene 2 renglones.~~
- ~~Poner código en Imprimir del Producto~~
- ~~CSS para imprimir página del Producto~~

**Comment by LeandroBraier** [comment]
@FAAREIA respondí en negrita sobre cada punto dentro de tu mismo comment. Este comment nuevo lo borramos después.

Los puntos que te había pedido ya están resueltos? Te agregué un punto 4 con link a spotify.

**Comment by FAAREIA** [comment]
Te contesté encima de lo anterior ^^

**Comment by FAAREIA** [comment]
@mkreyness cuando puedas limpiate todo lo que ya esté en desuso en la carpeta de Revear, incluyendo todo "_beta" si ya no se usa. Se hace muy dificil saber en donde tocar o donde poner los archivos ahora. Si @LeandroBraier confirma que tiene el backup en su poder, por favor limpiate todo

**Comment by mkreyness** [comment]
mas que limpiarlo lo mandaria a una carpeta "old" por si acaso salta algo y haya que reponerlo.
Ese backup lo hiciste vos ?
En la carpeta revear solo deberian quedar los php  y los subdirectorios cig-bin, img, inc, css y js
Los templates estan todos en /templates/revear y todos los assets estan en alguno de estos subdirectorios que te digo.

**Comment by FAAREIA** [comment]
Ok perfecto, mañana preparo backup entonces. El backup se que alguien lo tiene, yo lo tuve en un momento y después lo subí creo y se lo bajó lea. Algo asi había sido.
"_beta" lo borro entonces?

**Comment by mkreyness** [comment]
no borres nada, movelo a una carpeta "old". Que creamos que voluntariamente no se usa no implica que no haya algun lugar escondido donde por error se este accediendo. Al moverlo si hay un error va a saltar pero vamos a poder corregirlo, si lo borras, estamos en problemas.

**Comment by FAAREIA** [comment]
@LeandroBraier cuando vuelvan a generar las imágenes de las texturas, de paso saquenle los espacios de los nombres de los archivos. Un navegador nuevo en un entorno común parece no presentar problemas, pero puede traer problemas y no encontrar el archivo.
Osea que `nombre de textura.jpg` tiene que ser `nombre-de-textura.jpg`

**Comment by LeandroBraier** [comment]
Dale, @FAAREIA lo tengo en cuenta. Hoy a la tarde te paso todo esto que me pedís así ya cerramos.

**Comment by LeandroBraier** [comment]
@FAAREIA hoy estoy trabajando en los agregados que pedís, pero te repaso lo que sigue pendiente de tu parte:

1) LINK A SPOTIFY

Porfa sumá una red social más a la web, que es la de spotify. Va el link:

https://open.spotify.com/user/reveararg/playlist/77TILlZ800DMOQxZgOAI4g

2) Si no hay video en el Producto, el bloqué sigue apareciendo. SACAR SOLO EN ESOS CASOS  (quizá esto corresponde a @mkreyness ?)

3) Thumbs de Texturas: No tengo donde cargarlas por ahora. Si lo pueden agregar así cargo todo junto con las versiones más chicas de las imágenes genial. Si consideran que con las versiones más comprimidas de las imágenes de texturas alcanza confirmenme también por favor.

abrazo

**Comment by mkreyness** [comment]
2), si es mio. Tengo que modificar un poco el template de producto y tocar el programa.
Por si acaso: no toques el template productoT.html @FAAREIA que lo voy a estar modificando yo.

**Comment by FAAREIA** [comment]
Para el punto 3 puede agregarse un campo más al CMS o sino debería autogenerarse la imagen asi no es tanto quilombo. Un crop de 72x72 sin achicar la textura, asi se nota

**Comment by LeandroBraier** [comment]
Uh, si se pudiera autogenerar genial! Para evitar el excesivo Data Entry, pero si es mucho lio el autogenerar lo hago @mkreyness Decime vos.

**Comment by mkreyness** [comment]
donde van esos thumbs ?

**Comment by LeandroBraier** [comment]
Entiendo que son las imágenes de cada textura que vemos en la página de
Texturas una al lado de la otra antes de clickear en alguna para agrandarla.

**Comment by mkreyness** [comment]
y eso no esta controlado con el tamaño que tiene cada celda ahi ? Fede no se puede modificar algo en el template para que haga crop de la imagen y listo ?

**Comment by FAAREIA** [comment]
No, en la sección texturas la imagen es muchisimo más grande que 72x72, ahi no hay nada que tocar.
El tema es que en cada producto en la parte de Colores, ahi irian los thumbs de 72x72.

**Comment by FAAREIA** [comment]
El tema con el "autocrop" es que la imagen te la carga igual, osea que un tipo que visita la página del producto con un celular o una conección mala, carga imagenes que después capas ni ve. Un thumb de 72x72 debería ocupa 8KB o 10KB y la imagen normal 120KB capas. Son 12 veces menos y el tipo carga la imagen a pedido.

**Comment by mkreyness** [comment]
ya esta lo de que no aparezca el espacio de video cuando no hay video.

**Comment by mkreyness** [comment]
no tengo una herramienta para hacer esos crops en duplika, y sabes el kilombo que es pedirles cada cosa. Si podes hacerlos y despues me pasas un .zip con todo, yo los bajo y engancho en la base.
Pero por favor usa los mismos nombres safe que tienen ahora con -72x72 agregado, asi lo puedo automatizar.

**Comment by LeandroBraier** [comment]
Dale, yo te lo paso.

**Comment by LeandroBraier** [comment]
@FAAREIA estoy en proceso de mis pendientes (crops, imagenes mas livianas, etc).

Me dice Mariano de redes sociales que no está hecha la vinculación con YouTube que te pedí. Te paso aquí el paso a paso de nuevo:

> "1. Descarga el archivo HTML de verificación [google1e5175b864ac3c90.html] .
> 2. Sube el archivo a http://www.revear.com.ar/.
> 3. Confirma que la subida se ha realizado correctamente a través de la página http://www.revear.com.ar/google1e5175b864ac3c90.html .
> 4. Haz clic en el botón de verificación que aparece a continuación.
> Para mantener la verificación, no elimine el archivo HTML aunque la verificación se haya realizado correctamente."

El HTML del Paso 1 es el que obtenés al verificar en Google. Yo te había pasado el instructivo y después me dijiste que estaba hecho pero a nosotros no nos figura como hecho ni nos llegó el mail correspondiente. Te paso de nuevo el instructivo:

> Vinculación del webmaster
> Verifica tu sitio web con las Herramientas para webmasters de Google. El webmaster verificado puede aprobar una solicitud para conectar tu sitio web con la página de Google+ de tu empresa.
> Selecciona Mi Negocio > Página de Google+ en el menú de navegación que se encuentra a la izquierda.
> En la pestaña "Acerca de", haz clic en el botón Vincular sitio web que se encuentra junto a la URL del sitio web.
> ¿No ves el vínculo? Esto se debe a que las páginas de Google+ locales no son aptas para vincularse a un sitio web. Puedes agregar tu sitio web a la información de tu empresa siguiendo estos pasos.
> Si sabemos quién es el webmaster de este sitio web, te ofreceremos la opción de enviarle una solicitud para que apruebe el vínculo. Si le envías dicha solicitud, el webmaster conocerá tu dirección de correo electrónico.
> El webmaster verificado puede confirmar el vínculo en Herramientas para webmasters de Google.
> Una vez que se apruebe el vínculo, recibirás un correo electrónico. También verás una marca de verificación verified checkmark junto al sitio web en la pestaña "Acerca de" del perfil de tu página.
> 
> Después de que vincules tu página de Google+ con tu sitio web, también podrás vincular tu sitio web con tu página para dirigir a los clientes a la presencia de tu empresa en redes sociales. Más información sobre cómo agregar la Insignia de Google+ a tu sitio web

Esta vez seguí los 2 instructivos tal cual por favor y confirmame cuando esté hecho.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA está faltando el link a spotify también. https://open.spotify.com/user/reveararg

En resumen:

1) LINK SPOTIFY

2) VERIFICACIÓN GOOGLE.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo estás? Pudiste ver estos 2 temas? En un toque los resolvés.

**Comment by FAAREIA** [comment]
La verificación ya la hice pero el instructivo no es claro, osea no dice desde que url tengo que hacer las cosas.
Me meto en youtube y no veo nada para hacer y me meto a Google + y me da para llenar datos. Fijense si con la verificación web ya esta lo que necesitan.

Por otra parte el link a spotify me pide que me loguee, puede ser?

**Comment by LeandroBraier** [comment]
Spotify si. Es asi.

En cuanto a verificación si es lo que hiciste la otra vez y no hiciste nada
nuevo ahora no nos sirve. Subiste el html a la web nueva?

**Comment by FAAREIA** [comment]
No ahora la verificación la hice con la cuenta de revear y no la de parex. Fijense y diganme, si falta algo pasenme primero link y luego pasos para seguir en ese respectivo link.
Lo de spotify ya lo puse, dale F5 por si no lo ves

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Spotify @FAAREIA !

En cuanto a verificación no nos aparece como verificado en Google Plus. Revisalo vos y vas a ver:

Al parecer todavía no impactó, no nos llegó el email avisando ni la marca de verificación junto al sitio web en la pestaña "Información" de la página de marca en Google+. Con el login revearparex@gmail.com pass: sentir paredes en https://plus.google.com/b/113014718831911666678/113014718831911666678/about se puede ver en la parte de enlaces que sigue ofreciendo la posibilidad de enlazar el sitio web con el Google+.

Los pasos son los que ya te pasé varias veces. No hay más que eso.

Si ya tenés el HTML (entiendo que ya lo subiste a la web de Revear) asegurate de haber seguido estos dos:

> 1. Confirma que la subida se ha realizado correctamente a través de la página http://www.revear.com.ar/google1e5175b864ac3c90.html .
> 2. Haz clic en el botón de verificación que aparece a continuación.
>    Para mantener la verificación, no elimine el archivo HTML aunque la verificación se haya realizado correctamente."

Si eso lo hiciste correctamente, confirmame y probamos una segunda via de verificación de los datos de Google Business que es esta:

https://support.google.com/business/answer/3039617

**Comment by FAAREIA** [comment]
Ya esta hecho, confirmenmelo igual
Abrazo

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Lo confirmo entonces con el equipo de SM y te aviso.

abrazo

**Comment by LeandroBraier** [comment]
Listo @FAAREIA ! Ya llegó mail y pudimos verificar. Gracias @FAAREIA ! POrfa guardate paso a paso lo que hiciste para verificar así la próxima ya es más fácil.

me quedo el ticket para las mejoras que quedan de mi lado.

abrazo

**Comment by LeandroBraier** [comment]
**IMAGENES COMPRIMIDAS**

@FAAREIA y @mkreyness les paso todas las imágenes comprimidas a 50 de calidad y sus versiones con el -72x72 que me pidieron y tal como me las pidieron (fue un momento zen hacerlas).

[50 de calidad y version 72.zip](https://github.com/LeandroBraier/Klaukol/files/328758/50.de.calidad.y.version.72.zip)

Atención: La imagen llamada **REVERECO-Planchado-Blanco** es nueva, no es la misma que estaba antes. Si es un lio vincular esa avisenme y esa sola la subo manualmente via CMS sin problema.

**ICONOS DE RODILLO, PINCEL Y SOPLETE**

@FAAREIA te paso los íconos que me pedías

![iconos-de-pincel](https://cloud.githubusercontent.com/assets/6719872/16284038/b1234fa2-38a5-11e6-873e-dd1d9525aece.png)
![icono-soplete](https://cloud.githubusercontent.com/assets/6719872/16284040/b127f7e6-38a5-11e6-90fb-394292ad041d.png)
![icono-rodillo](https://cloud.githubusercontent.com/assets/6719872/16284039/b126a878-38a5-11e6-81c5-f918572fddb5.png)

**QUEDAN DE MI LADO**

Descripciones de las páginas 

Cargar fotos para Home de los demás productos

Mañana espero resolverlas.

abrazo

**Comment by mkreyness** [comment]
No recuerdo haberte pedido nada de esto, supongo que fue @FAAREIA , expliquenme que tengo que hacer.

**Comment by mkreyness** [comment]
ahi lo vi mas arriba. Los bajo y despues veo como los engancho, pero los originales (sin el 72x72) cambiaron ?

**Comment by mkreyness** [comment]
siempre aprieto el boton equivocado...

**Comment by LeandroBraier** [comment]
jajaj Si @mkreyness los originales sin el 72x72 cambiaron. Ahora pesan menos de 100 k. Antes pesaban entre 300 y 400.

**Comment by mkreyness** [comment]
ojo yo veo que mandaste 65 "72x72" pero yo tengo 90 "colores". Si hago ciegamente que a todo se le agregue el 72x72 van a haber 25 que van a salir rotas.

**Comment by LeandroBraier** [comment]
Hay colores que no tienen textura. 

Entendí que ibas a reemplazar las texturas por archivos del mismo nombre y después les ibas a vincular a cada una su "72x72". No se puede hacer eso?

**Comment by mkreyness** [comment]
Ah, ok, las que estan marcadas como texturas son 64, y el 1 de diferencia es el nuevo que dijiste, ok, no dije nada.

**Comment by mkreyness** [comment]
otro problema es que los nombres no coinciden con lo que decian antes, antes tenian blancos, ahora tienen guiones, voy a tratar de reemplazar todo automaticamente en la base, pero la verdad que es un peligro.

**Comment by mkreyness** [comment]
listo, pareceria estar todo ok, peguenle una mirada.
Ahora los thumbs de las texturas en la pagina de cada PRODUCTO son los nuevos 72x72, mientras que la imagen basica (la que se muestra al ampliar) "sigue siendo" la que era (salvo este ajuste de blancos por guiones en los nombres).
En el CMS ahora en la solapa "Colores" de los productos podes cargar/modificar por separado Imagen y Thumb. Asi cargue los "revereco" estos que cambiaron.

**Comment by LeandroBraier** [comment]
Excelente Marce! Muchisimos gracias! Voy a revisar por las dudas asi nos
quedamos tranquilos. Abrazo grande y hasta mañana!

**Comment by LeandroBraier** [comment]
Chequeados y todos bien. Gracias Marce.

**Comment by LeandroBraier** [comment]
@mkreyness estoy intentando poner un nuevo slide en la web de Revear y no me lo toma, puede ser?

<img width="1382" alt="captura de pantalla 2016-07-25 a las 7 10 48 p m" src="https://cloud.githubusercontent.com/assets/6719872/17118656/f3daee98-5297-11e6-9ef5-c6cf55cfec5c.png">

**Comment by mkreyness** [comment]
El de texturas ?
Por que no pones mejor esto que es fijo ?
http://www.revear.com.ar/texturas-profesional.html

**Comment by LeandroBraier** [comment]
jaja no, estoy hablando del Slides Home. Subí un nuevo slide y no aparece en la página.

**Comment by mkreyness** [comment]
y otra vez se arruinaron todos los acentos, yo no se que tocan en Duplika que va para un lado, va para otro, lo que ahora sirve, mañana no sirve.
Ahora veo

**Comment by mkreyness** [comment]
nos mudaron por enesima vez de server sin avisar parece.

**Comment by LeandroBraier** [comment]
Perdón, yo soy el que estoy demorando la mudanza de server. Esta semana avanzo con el tema, disculpá.

**Comment by mkreyness** [comment]
Lo que digo es que los tipos estos nos llevan de aca para alla sin avisar.
Igual no entiendo bien cual es el que decis que no te aparece. En la foto me mostras 3 pero 2 estan tildados profesional y uno que no.
Ese solo sale en el particular.

**Comment by LeandroBraier** [comment]
Tenés razón MK! Perdón! No me había dado cuenta. Pero bueno, al menos encontraste ese error ; ) jeje

Igual prometo esta semana avanzo con la mudanza.

abrazo

**Comment by mkreyness** [comment]
si ojo todavia no toque nada, sigue asi. En la parte web se ve todo normal ? No hay bichos raros en los acentos ?

**Comment by LeandroBraier** [comment]
La verdad estoy viendo y no noto nada.

**Comment by mkreyness** [comment]
ojo porque los slides que escribiste ultimos (ahora que normalice el resto) quedaron mal. Ahi los retipeé para que se vean bien en el CMS. Rechequea por favor que todo siga saliendo bien.

**Comment by LeandroBraier** [comment]
Tal como decis, el slide nuevo no se ve bien en la web (en el CMS si)

<img width="1073" alt="captura de pantalla 2016-07-25 a las 8 38 39 p m" src="https://cloud.githubusercontent.com/assets/6719872/17120667/42d75552-52a4-11e6-981e-2af0c0613c83.png">

**Comment by mkreyness** [comment]
yo lo veo bien ahora. Capaz cuando miraste todavia no se habia regenerado la pagina

**Comment by LeandroBraier** [comment]
Yo también. Gracias @mkreyness !

**Comment by LeandroBraier** [comment]
@FAAREIA hay un problema en la maquetación del formulario. Te fijás porfa?

www.revear.com.ar/cgi-bin/contacto.pl

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias!!!
