### ISSUE TITLE
Consultas Extra Web Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#315]
@mkreyness una consulta: estoy repasando este pedido de Fede:

> Acortar algo como
> Av. SAN MARTIN 420 CAPITAL FEDERAL Ciudad Autonoma de Bs. As.
> Av. SAN MARTIN 420, C.A.B.A. .
> De esa forma hay menos choclo de datos y capas que se puede incluir la dirección en un link hacia google maps. -> https://www.google.com.ar/maps/place/DIR+ALTURA+CABA

Entiendo que se solucionaría simplemente cambiando a los que tiene dentro del campo PROVINCIA "Ciudad Autónoma de Buenos Aires" y reemplazarlo "C.A.B.A" y borrarles el contenido del campo de LOCALIDAD. Qué opinás?

**Comment by mkreyness** [comment]
No entiendo lo de poner un link a googlemaps, si lo que mostramos ya es googlemaps.
Yo pondria 'CABA', ya con eso GoogleMaps lo reconoce.
De acuerdo en sacarle "CAPITAL FEDERAL" en la localidad. Si queres lo hago yo de un plumazo.

**Comment by LeandroBraier** [comment]
Dale perfecto. Adelante MK!

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias!
