### ISSUE TITLE
Nuevo Bug en Novedades ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#316]
@mkreyness subimos una nota a la web de Parex y no funciona. Te fijás que pasa? La nota debería aparecer en esta url:

http://www.parexklaukol.com.ar/novedades/parexgroup-presente-en-tendiez-tendencias-de-diseno.html

Intuyo que tiene que ver con lo que hicimos para Revear.

abrazo

**Comment by mkreyness** [comment]
No. En realidad el problema viene de mucho antes, cuando Duplika hizo algun cambio, no se estaban publicando ni novedades ni cambios en los productos desde entonces, necesariamente.
Te acordas que hice un parche desde el telefono (estaba en el dentista), y quedaron estas dos cosas sin actualizar.
Ya esta andando:

http://www.parexklaukol.com.ar/novedades/parexgroup-presente-en-tendiez-tendencias-de-diseno.html

**Comment by LeandroBraier** [comment]
Gracias Mk!

**Comment by LeandroBraier** [comment]
Puede ser que en la lista de novedades de la web no se vea la nota?

**Comment by mkreyness** [comment]
otro programa sin tocar... Ahora lo arreglo.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness cuando puedas fijate, me parece que nunca lo resolviste a esto no? Porque seguimos con los mismos problemas que el viernes.

**Comment by mkreyness** [comment]
No, el programa esta arreglado. Que es lo que no te aparece publicado ?

**Comment by LeandroBraier** [comment]
No es eso. Me decía la persona que carga las notas que no se le cargaban
las imágenes, pero estoy probando yo y me anda. Vamos a probar de vuelta y
te aviso. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
