### ISSUE TITLE
Landing Klaukol En Busca del Gran Colocador

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#317]
@FAAREIA está aprobadísima la landing. Solo pidieron cambios muy chiquitos:

. Agregar link a pdf de FAQ. Estaría arriba de “Leé las bases y condiciones” y diría “Preguntas frecuentes”. 

. Agregar la dire del evento debajo 30/06 a las 18 hs. La dirección es Tucumán 2159.

. Cambiar la frase “Demostralo" por “Vení a demostrarlo.”

Solo eso abrazo!

**Comment by LeandroBraier** [comment]
@FAAREIA hoy dale prioridad a esta landing por favor. Prioridad número 1.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/busca-gran-colocador/

Falta el tema de bases y condiciones, preguntas frecuentes y que muestra el botón de "recibir info de competencia".
Si falta algun link avisame.
Todavía no esta responsiva

**Comment by FAAREIA** [comment]
Cuando puedan pasenme la foto para facebook de 1200x630

Abrazo

**Comment by FAAREIA** [comment]
Pasame también el link del video en youtube

**Comment by LeandroBraier** [comment]
**FEEDBACK RESTANTE** PARA @FAAREIA . 

Los links de FAQ y Bases te lo paso mañana temprano junto con el link del video también. 

La foto de Facebook la paso acá: 

![potenciados gana un viaje 1200 x 630](https://cloud.githubusercontent.com/assets/6719872/15657476/921ddff8-2687-11e6-9d85-56d44c105bf5.png)

. Que lo negro empiece donde empezaba en el PSD que te pasé. Es decir, la parte de abajo de la foto de Korol e Ivana que pise sobre negro.

**Comment by FAAREIA** [comment]
Fijate ahora Lea, le oscurecí los bordes asi no hace falta que este al 100%.

**Comment by LeandroBraier** [comment]
@FAAREIA lo veo mejor. Ahora solo necesitaría que lo negro empiece donde empezaba en el PSD que te pasé. Es decir, la parte de abajo de la foto de Korol e Ivana que pise sobre negro. 

Con eso entregamos.

abrazo

**Comment by LeandroBraier** [comment]
**FEEDBACK PARA @mkreyness** 

Empecemos a armar el formulario de registración. Los campos:

Nombre
Apellido
Mail
Teléfono

Si querés podemos usar un formulario de suscripción de Mailchimp si te parece OK. Como te parezca mejor.

**Comment by LeandroBraier** [comment]
@FAAREIA y @mkreyness borré comments y actualicé el thread para que sea más corto. Borré lo que no es necesario conservar.

**Comment by FAAREIA** [comment]
Dale F5 Lea

**Comment by mkreyness** [comment]
Si lo hago yo entonces tenes que exportar los datos a mailchimp, si usas directo el de mailchimp es todo automatico, me parece mas simple para todos.

**Comment by LeandroBraier** [comment]
Dale, vamos con el de mailchimp. Mañana lo genero con Eze, que me pasa el Authenticator. 

Gracias @FAAREIA ! Ya vi que corregiste lo que te pedí. Mañana te paso los contenidos que faltan, pero fijate que la frase final de la columna derecha dice "Dejanos tus datos y recibí las" y debería decir "Dejanos tus datos y recibí las últimas novedades sobre las competencias."

Puede ser para mañana. abrazo grande

**Comment by LeandroBraier** [comment]
@FAAREIA te paso los materiales que te faltaban para terminar la landing. Dale prioridad mañana a la mañana por favor.

**1. Bases y condiciones:** bajá el pdf de este link:

https://mega.nz/#!z9tXiC5D!Oqr-vuqEPngO8BX7mFR5_sxmdaCEgPGE6s_lx4oIaEQ

**2. Preguntas frecuentes:** bajá el pdf de este link:

https://mega.nz/#!vscEQBzQ!hjKJWe5NitvUp8KeNRxSBhZwD6_F52LAGKYygvA5KWo

**3. El teaser ya está subido a YouTube.** Te paso el link al embed:

https://www.youtube.com/embed/p9VGYPX0lpw

**4. Te paso el link al formulario de suscripción** en Mailchimp:

http://eepurl.com/b3Xzs5

Una vez que esté la landing hecha, te voy a pedir que rediseñes el formulario más lindo como hiciste para la base de ParexKlaukol. 

**5.** Ya pedimos la delegación de la url definitiva: www.klaukoltebusca.com.ar

Yo les di los DNS de Duplika. Porfa vayan redireccionado desde adentro lo que sea necesario.

**6. Hay que sumar una sección de texto** entre el header y la parte de “PRÓXIMOS ENCUENTROS”. 

Te paso la imagen y el PSD en este ZIP:

[como-participar-landing-competencia.zip](https://github.com/LeandroBraier/Klaukol/files/292457/como-participar-landing-competencia.zip)

Usá lo que te sirva más y de la forma que quede mejor estéticamente. Para mi el fondo de la imagen conviene que sea negro, pero fíjate como te parezca mejor.

**Comment by FAAREIA** [comment]
Ahi lo estoy terminando, fijate que cuando me suscribo me manda a una url que esta en ingles y dice algo como:

## 

Almost finished...

We need to confirm your email address.

To complete the subscription process, please click the link in the email we just sent you.
ParexKlaukol S.A.
Dr. Ignacio Arieta 3817
Buenos Aires, CABA B1754AQQ
Argentina

Add us to your address book

##

**Comment by LeandroBraier** [comment]
Si, hay que hacer el mailing de confirmación como hicimos para Parex y
reemplazar ese mensaje. Te fijas si se puede cambiar?

**Comment by FAAREIA** [comment]
Ya subí la nueva versión y totalmente responsiva.
Lo del mensaje creo que ya esta, voy a hacer otra prueba.

**Comment by FAAREIA** [comment]
Me olvidaba, con respecto al dominio nuevo. Ya esta seteado en el panel de control por lo que cuando se deleguen los DNS, la url va a mostrar la landing

Ojo que hay que cambiarlo en el newsletter al link que te lleva a la landing

**Comment by LeandroBraier** [comment]
Tal cual, tenés razón. Aún no recibí el OK para ese newsletter, pero te lo
cargo en ese ticket.

abrazo y muchas gracias! quedó excelente el formulario. Me pongo a probarlo
y te digo.

**Comment by LeandroBraier** [comment]
Quedó excelente Fede!! Muy bueno!!! Funciona muy bien todo el proceso. Solo quedaría poner el Favicon con el Iso de Klaukol (no el de ParexGroup) cuando vos puedas, sin apuro.

abrazo

**Comment by FAAREIA** [comment]
Hecho, ya lo subi a http://www.klaukoltebusca.com.ar/ el cual ya esta delegado y funcionando

**Comment by LeandroBraier** [comment]
Genial Fede! Yo aún no lo veo delegado, debe ir por zonas como siempre no?

**Comment by FAAREIA** [comment]
Más que por Zonas por proveedores de internet imagino. Telecentro debería tenerla ya delegada en todos lados

**Comment by LeandroBraier** [comment]
Ya llegó y está excelente!!! Gracias @FAAREIA !!

**Comment by LeandroBraier** [comment]
@FAAREIA esta campaña se reavivó con todo. Necesito para el viernes que le hagas algunos ajustes varios para dejarla lista para presentar al cliente. Cambió levemente el nombre de la campaña y algunos otros detalles.

1) Necesito que lo pases al estilo YPF como hicimos para Paty Chile. Header arriba con la estética de la campaña (Korol y demás) y debajo fondo pleno, puede ser blanco o gris, como en la web de Parex. Lo importante es que se vea bien limpio y más pro.

2) No cambió demasiado, pero la estética definitiva de la campaña podés obtenerla de acá, del archivo de Afiche:
https://mega.nz/#F!61VkHAQQ!JBuUJBd5Dma7PMmM8zzv-A

3) Cambiar logo por el nuevo logo que subí acá en el archivo del Afiche:
https://mega.nz/#F!61VkHAQQ!JBuUJBd5Dma7PMmM8zzv-A

4) Cambiar frase “PRIMERA COMPETENCIA NACIONAL DE COLOCADORES” por UN GRAN DESAFÍO PARA COLOCADORES

5) Cambiar el texto: 
¿SOS EL MEJOR COLOCADOR? VENÍ A DEMOSTRARLO Y GANÁ UN VIAJE A BARCELONA PARA VER JUGAR AL NRO.1 DEL MUNDO 

por el siguiente: 
¿SOS EL MEJOR COLOCADOR? VENÍ A CAPACITARTE Y DEMOSTRALO. GANÁ UN VIAJE A BARCELONA PARA VER JUGAR AL NRO.1 DEL MUNDO

6) Cambiar el texto de "cómo participar" por este y el dorso actual del flyer de colocadores, que te lo subí en:

https://mega.nz/#F!61VkHAQQ!JBuUJBd5Dma7PMmM8zzv-A

7) Cambiar el botón de QUIERO RECIBIR a que diga: QUIERO INSCRIBIRME EN LA COMPETENCIA

8) En el formulario hay que cambiar en la imagen de arriba el logo nuevo.

9) Incluir el espacio para poner a los corralones destacados, con logo del corralon + foto del colocador ganador. Podés ver un mock up que te va a resultar más explicativo en este diseño que cerré yo de la landing anterior:

![mock-up-landing-potenciados](https://cloud.githubusercontent.com/assets/6719872/16824866/a0395e10-4945-11e6-8c1c-63e31a764c4c.jpg)

El cliente no quiere que quede tan negro ni tan desprovisto, por eso te digo de tomar de referencia acá también la de YPF que tomamos para Paty Chile. Te paso este mock up SOLO para que veas a que me refiero con el espacio para corralones. 

Necesitaría poder entregar esto el viernes. Me confirmás si llegamos?

abrazo

**Comment by FAAREIA** [comment]
Para mañana no se llega. Yo diría que la semana que viene se presenta el nuevo diseño y luego se maqueta.

**Comment by LeandroBraier** [comment]
Mmm, para mañana no llegás con el nuevo diseño al menos? Sin maquetación?

Así como el JPG que te subí acá arriba.

**Comment by FAAREIA** [comment]
Se puede llegar pero no es garantía. El diseño a veces sale al toque y a veces cuesta. Además es como te dije en Paty, tengo que diseñar un sitio en base a un afiche. Paty tenía más recursos pero aca solo hay una textura o la imagen de la cancha y corol que va a ir en el encabezado.
También tené en cuenta que estamos en medio de lo de Paty y se coló lo de Vietur que espero no haya más cambios, si mañana algo me roba tiempo ya no es posible que salga el nuevo diseño.

**Comment by LeandroBraier** [comment]
@FAAREIA solo para dejarlo asentado lo que hablamos por tel, acordate de pasarme mañana al mediodía hasta donde llegaste así vemos si necesitamos pedirle una mano al equipo de diseño.

abrazo grande y gracias!

**Comment by FAAREIA** [comment]
Ahi le estuve dando al diseño, me faltó el header y el footer, pero eso con lo que hay se resuelve más fácil que todo el contenido.
El zip con el archivo photoshop bajenlo de http://benteveo.tv/busca-colocador.zip

![busca-colocador](https://cloud.githubusercontent.com/assets/6184969/16880336/1f4051a0-4a8b-11e6-9fe4-642da3e5b7a7.png)

**Comment by LeandroBraier** [comment]
Quedó muy bueno Fede!!!! Solo que el rojo lo veo desteñido, no es el rojo
Klaukol no?

**Comment by LeandroBraier** [comment]
Confirmame entonces si llegas con el header para la tarde incluido y la corrección de color para la tarde.

También fijate que estén todos los puntos pedidos. Por ejemplo, el 7 no está:

7) Cambiar el botón de QUIERO RECIBIR a que diga: QUIERO INSCRIBIRME EN LA COMPETENCIA

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, para hoy ya no llego. Lo sigo el lunes en base a lo que les pasé o en base a lo que le retoquen.

**Comment by LeandroBraier** [comment]
OK, retocamos nosotros entonces. Gracias!

**Comment by FAAREIA** [comment]
Lea avisame o mandame si hay algo nuevo.
Abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Mandamos el diseño el viernes y estamos esperando feedback. Apenas tengo respuesta te aviso, por ahora esperemos. 

Seguí avanzando con FUCA nomás.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA te paso la landing final en PSD para que la maquetes. La necesitaríamos subida mañana aunque sea a última hora, llegás? (obvio no hace falta que esté responsive mañana)

https://www.wetransfer.com/downloads/661602727d522aafd41e8174fcae76aa20160718233408/99f86ba634154c76144fa3c94ba40bea20160718233408/c6cc63

Todo lo tenés en el PSD. Lo único que tenés que cambiar del psd es lo siguiente:

1) El fondo no debe ser blanco. Usá el fondo gris de este micrositio que hicimos pero sin los chirimbolos de Potenciado. Solo el fondo gris concreto.
http://www.parexklaukol.com.ar/klaukol-impermeable-potenciado/home.html

2) Donde hay fotos de finalistas y logos de corralones poné iconos de relleno mientras tanto.

3) Agregar un footer negro con link a web, página de Facebook, mail de la empresa (klaukol.marketing@klaukol.parex.com) y el 0800-222-5528 de Klaukol, acompañado a la izquierda de logo "Klaukol Potencia que Une" y a la derecha de logo "ParexGroup". Similar a como está en el micrositio que te pasé pero con todos los datos que te pido.

**POP UP**
Aparte aprovecho a pedirte que prepares este POP UP para subir a la página oficial de ParexKlaukol con el link a esta web (www.klaukoltebusca.com.ar) el lunes que viene.

![pop-up-en-busca-del-colocador-klaukol](https://cloud.githubusercontent.com/assets/6719872/16934811/82d0be74-4d30-11e6-8908-c9711eb22c7e.jpg)

Confirmame mañana porfa, una vez que cierres el mailing interno de Paty Chile, si llegás con esto.

abrazo

**Comment by FAAREIA** [comment]
No se si llego para hoy, el encabezado hay que rehacerlo. Es una imagen fija de 1680px de ancho y me pusieron palabras en el extremo derecho. El encabezado tendría que ser de un ancho de 1104px y tener en cuenta que si el fondo es del ancho máximo del monitor, pensar qué imagen iria a lo ancho o si tenes una imagen de 1104px después le haces un fade a los costados para lograr ese ancho variable.

Además pusieron una tipografía que no es web, la cual voy a cambiar por la que había.

**Comment by LeandroBraier** [comment]
Ok, si nosotros te resolvemos el header y te pasamos la imagen llegás?

**Comment by LeandroBraier** [comment]
El texto iría dentro de la imagen, no hace falta que esté como texto.

**Comment by FAAREIA** [comment]
El tema es que hay que meterlo como texto porque sino el encabezado se va a ver bien en 1104px de ancho y después en 768px 640px 480px y 320px se va a ver mal. Todo tiene que ser flexible, o poder reacomodarse.

**Comment by FAAREIA** [comment]
Yo creo que si llego, si me pasan el footer también, mejor aún ^^

**Comment by LeandroBraier** [comment]
Entendí lo del texto. Ok, entonces para mañana a la mañana podés tenerla entera?

**Comment by FAAREIA** [comment]
Si, sin responsivo seguro

**Comment by LeandroBraier** [comment]
Genial.

**Comment by LeandroBraier** [comment]
Gracias Fede!

**Comment by LeandroBraier** [comment]
![landing-header](https://cloud.githubusercontent.com/assets/6719872/16953361/194a3a20-4da3-11e6-81c7-176b0acd99e7.png)

@FAAREIA el diseñador me pasó el header sin texto en el tamaño que pediste por si te suma.

**Comment by FAAREIA** [comment]
Esta mejor, pero en 1104px de ancho, corol no se ve. Que ponga unas guías asi sabe como diagrama la imagen. Acuerdense de pasarme el psd porque yo eso lo desarmo en capas.

**Comment by LeandroBraier** [comment]
Ok, entiendo.Le pido el psd y vos lo terminás de ajustar?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
si pedile, seguro achico el logo o pongo a corol de un lazo y a la chica del otro

**Comment by LeandroBraier** [comment]
Aca va el PSD fede!

https://mega.nz/#!ZcBWDShB!zk48t3ut5huhmUcumDVQl5NI4kDGxRSSfeykUI9ljG8

**Comment by LeandroBraier** [comment]
@FAAREIA frená un toque con esto que te vamos a mandar un PSD final corregido. Te aviso apenas lo tengo. Esto va a demorar la entrega no t e proecupes.

**Comment by LeandroBraier** [comment]
@FAAREIA ahora si, ya lo resolvimos. Acá te paso el PSD integrando pedidos del usuario pero al mismo tiempo (quiero creer) resolviendo los problemas que teníamos con el header. 

Fijate ahora: https://mega.nz/#F!3tlFBYzS!XGLaWXGpNe9I5byCZq5_aw

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, el header sigue estando gigante voy a tener que achicarlo. Con respecto al contenido, no veo cambios.

**Comment by LeandroBraier** [comment]
La mayor parte del texto quedó fuera del header eso es un cambio no? No lo
ves a ese? En el header está solo la foto y el logo. Llegás a subirlo
maquetado no responsive para hoy a ultima hora?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Recordá no pisar los formularios y demás que ya están funcionando en esa
URL ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-07-20 9:41 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Fijate ahi lea:
www.parexklaukol.com.ar/busca-gran-colocador2/

Faltaría que me pases la meta-description y la foto de 1200x630 para facebook.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

1) Falta el texto de abajo del header y antes del "Como participar":

<img width="692" alt="captura de pantalla 2016-07-20 a las 12 35 25 p m" src="https://cloud.githubusercontent.com/assets/6719872/16991717/eb4c117c-4e72-11e6-8a33-e71af564b352.png">

2) El logo debería estar más centrado en el header, no abajo de todo sino como en el psd y la captura que te pasé arriba.

3) Los finalistas no están como te pedí. No se entienden nada eso. Tenemos que ya publicarla asi que debería haber un thumbnail gris en la imagen, en lugar de "Nombre-Apellido" decir "Finalista 1", Finalista 2, y así. Y abajo en vez de un logo falso decir "Corralón 1, Corralón 2, " etc

4) El footer no queda bien así. Mejor en lugar de negro hacelo en gris oscuro como el de la web de ParexKlaukol. Arriba de los botones poné "Información de contacto". Recordá que los colocadores son gente sencilla, tenemos que ponerles todo in your face para asegurarnos que lo vean. De hecho, el cliente pedía poner el texto del 0800 en realidad, no un botón para llamar directamente, pero como vos lo proponés está muy bien. Simplemente agregale arriba "Información de contacto"

abrazo

**Comment by FAAREIA** [comment]
PAsame el psd otra vez que creo que tengo otro, eso del logo nunca lo vi asi

**Comment by LeandroBraier** [comment]
El link es este mismo:

https://mega.nz/#F!3tlFBYzS!XGLaWXGpNe9I5byCZq5_aw

Puede ser que no te lo había actualizado. Probalo ahora y dale F5. Debería estar actualizado y deberías ver esto:

<img width="1639" alt="captura de pantalla 2016-07-20 a las 12 59 09 p m" src="https://cloud.githubusercontent.com/assets/6719872/16992585/3b0d6a00-4e76-11e6-9421-2e5dbc123019.png">

**Comment by FAAREIA** [comment]
El PSD no esta asi. Acordate que yo necesito separar 3 capas, Logo, actores y cancha.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/busca-gran-colocador2/
Pregunta:
Lo de los finalistas, no sería ejor sacarlo si no va haber ningun por ahora? O es para que lo vea el cliente nomás?

**Comment by LeandroBraier** [comment]
Era para que lo viera el cliente nomás lo de los finalistas. Por ahora
dejalo así que está bien. Lo demás lo veo bien, ahora le pido a diseño que
te pase bien el PSD. En un toque lo tenés.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Acá está el nuevo PSD @FAAREIA ! Te paso solo lo que te faltaba. FIjate si lo podés agregar.

https://mega.nz/#F!bhlDgIjY!17tXRAu5-FSOcYBVElcuKw

No te olvides de poner el logo del Header más centrado, no donde está ahora, sobre el borde inferior de la imagen.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA llegamos a tenerla para hoy a la landing?

**Comment by FAAREIA** [comment]
Hola Lea, tené en cuenta que yo le doy hasta el mediodía o hasta cumplir 4hs, después tengo otros compromisos y entregas.
Hoy lo tenemos, igualmente el .psd no está como en el png, el psd es el mismo que antes. Voy a ver las diferencias y lo voy a replicar

**Comment by FAAREIA** [comment]
Lo que me faltaría es la textura esa en donde se apoya el texto, con esa imagen en grande, lo replico por completo

**Comment by LeandroBraier** [comment]
@FAAREIA porfa esto terminalo hoy. No les voy a seguir pidiendo materiales a los chicos, buscale la vuelta para que quede bien igual sin la textura. Se las pedí mil veces, me pasan cosas intermedias y seguimos dando vueltas.

Porfa cerralo lo mejor posible con la diagramación esta aunque sea sin la textura. Hoy dale prioridad a eso y al Mailing Interno de PAty Chile (que le falta cambiar solo 2 pavadas)

**Comment by FAAREIA** [comment]
Job done. Dale F5

**Comment by LeandroBraier** [comment]
Hermoso @FAAREIA !! Se lo muestro al equipo y te confirmo.

**Comment by LeandroBraier** [comment]
@FAAREIA te pido los últimos ajustes y estamos:

1) Te paso el fondo de concreto posta para reemplazar ese. Te pido que lo hagas continuar hasta donde empiezan los finalistas. 

https://www.wetransfer.com/downloads/f06e694cbfabde730439c6a2483c7a6c20160721140308/457de16e79f9370ffc63b15a1de9de0920160721140308/7a6af0

Además, dos pedidos que ya te había hecho y quedaron pendientes:

2) Cambiar el botón de QUIERO RECIBIR a que diga: QUIERO INSCRIBIRME EN LA COMPETENCIA

3) En el formulario hay que cambiar en la imagen de arriba el logo nuevo. Reemplazando esa imagen por esta que te paso acá ya lo resolvés:

![pop up](https://cloud.githubusercontent.com/assets/6719872/17031139/0b8eefd2-4f49-11e6-9030-3652cc8dc15b.png)

Esto seguro lo podés resolver antes del mediodia no?

abrazo

**Comment by LeandroBraier** [comment]
Por si te sirve acá pudimos armar el PSD completo con todo.

https://www.wetransfer.com/downloads/e51b8115d9fc59f92dbe52d466bd173e20160721142750/842b3db58152176febafe78470093df220160721142750/541d1e

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Te voy a estar pasando unos ajustes más que pidió el cliente pero cosas muy sencillas. Quedó muy bien. Si para mañana tenés estos ajustes finales estamos bien.

abrazo

**Comment by FAAREIA** [comment]
http://www.klaukoltebusca.com.ar/
Subida

**Comment by LeandroBraier** [comment]
Muchísimas gracias @FAAREIA ! Lo veo arriba. Sos un grosso.

Te paso acá los últimos cambios para mañana nomás:

1) Cambiar: ANOTATE EN TU CORRALÓN 

x ANOTATE EN NUESTROS PUNTOS DE VENTA 

2) Cambiar: Inscribite en tu corralón amigo.  

x  Inscribite en tu comercio amigo.

3) Cambiar la fecha del próximo evento por 17/08. Quedaría así:

Rosario, provincia de Santa Fe 30/06 a las 18hs. en el Club Sportivo América, Tucumán 2159

4) En el footer de abajo dejar solamente:

 Logo de Klaukol (sin Potencia que une) que linkee a la web de Parex principal

Reemplazar el logo de ParexGroup por la frase "con el apoyo de Rubí" como estaba antes en la landing vieja (utlizando el logo de Rubí). 

Potencia que Une y ParexGroup se eliminan.

5) Agregar el mismo favicon de Club de Colocadores.

6) La sección de Finalistas reemplazá las imágenes grises por siluetas como las de este PSD: 

https://mega.nz/#!gNxlgS6L!_gVCTLKvjSiQI6JGlyUXGwv6MJhJ4tSLKHvWQk7k-H0

Solo eso.

abrazo y gracias otra vez!

**Comment by FAAREIA** [comment]
Todo actualizado Lea, fijate ahora y dale F5.
http://www.klaukoltebusca.com.ar/

**Comment by LeandroBraier** [comment]
Muchísimas gracias @FAAREIA ! Quedó muy muy bueno!! 

Te voy a molestar más tarde una vez más solo para cambiar el embed del video. Gracias!

abrazo

**Comment by FAAREIA** [comment]
Ahi le puse el OpenGraph al sitio + Google Analytics.
La foto que puse es la del pop-up que se va a mostrar en el home de parexklaukol.com.ar

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!!! Me había olvidado de pedirtelo.

**Comment by LeandroBraier** [comment]
@FAAREIA consulta: falta hacer responsive esta landing no? Eso cuando lo tendrías?

**Comment by FAAREIA** [comment]
Máximo 8hs más de trabajo

**Comment by LeandroBraier** [comment]
Ok, entiendo. Con que esté para el miércoles o jueves a más tardar
responsive estamos bien?

**Comment by FAAREIA** [comment]
si perfecto

**Comment by LeandroBraier** [comment]
@FAAREIA ya podés cambiar el video de la landing por el definitivo!!

`<iframe width="560" height="315" src="https://www.youtube.com/embed/1dj_4YI4MN4" frameborder="0" allowfullscreen></iframe>`

Con que esté el lunes estamos OK.

Además el cliente pidió linkear a la Guía de Corralones en la primera línea del "Cómo participar". Lo que necesito es que: donde dice: 

**La inscripción es gratuita. Inscribite en tu comercio amigo. Y este será tu sponsor durante la competencia.** 

Siguiendo esa misma frase diga:

**Encontrá el más cercano en esta guía.**
(con el link a la guía de corralones)

abrazo y gracias!

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo estás?

Porfa avisame cuando hayas cambiado el embed y agregado esta frase con el link.

abrazo

**Comment by FAAREIA** [comment]
Ahi puse todo, en breve le cambio el color al link mientras voy avanzando con lo responsivo

**Comment by LeandroBraier** [comment]
Excelente @FAAREIA ! Gracias!!

**Comment by FAAREIA** [comment]
Ahi le terminé lo responsivo. Mañana le voy a pegar una mirada más pero estaría listo

**Comment by LeandroBraier** [comment]
Excelente Fede!! Quedó muy bueno! muchas gracias!!

Seguís con FUCA no? Mañana te paso unas páginas de login y demás para el evento de En busca del Colocador Klaukol pero eso ya es con más tiempo.

abrazo y gracias!

**Comment by FAAREIA** [comment]
Si con FUCA
