### ISSUE TITLE
Nuevos Distribuidores Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#318]
@mkreyness te paso nuevos distribuidores a subir en el CMS. Vos los podés subir todo de una?

[Nuevos Distribuidores Revear 31-05.xlsx](https://github.com/LeandroBraier/Klaukol/files/291746/Nuevos.Distribuidores.Revear.31-05.xlsx)

**Comment by mkreyness** [comment]
Si pero ojo tema coordenadas, alguien tiene que entrar y dejar que se recalculen c/u.
Cuando llego a mi oficina intento.

**Comment by LeandroBraier** [comment]
Dale, entiendo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
Aca no se si hay nuevos, pero seguro que hay muchisimos que ya estan cargados.
No me puedo basar en el dato "codigo" porque se repite dentro del excel tambien y dentro de la base que ya tengo. Y hay muchisimos SIN CODIGO. Seran esos los nuevos ? Pero en tal caso, que codigos le pongo ?
El excel tiene 552 registros, yo tengo en la base 770, asi que tampoco es que esten "todos los que tenia" + nuevos.

**Comment by LeandroBraier** [comment]
Ok consulto si se pueden reemplazar los repetidos o cuales son los nuevos.

**Comment by mkreyness** [comment]
Y si son los que no tienen codigo, que los SEPAREN y les asignen codigo.
Si le ponen codigo y no me separan cuales son los nuevos, voy a terminar duplicando cientos.

**Comment by LeandroBraier** [comment]
Entiendo, gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2016-05-31 16:41 GMT-03:00 mkreyness <notifications@github.com>:

**Comment by LeandroBraier** [comment]
@mkreyness aca te vuelvo a enviar la lista pero solo con los nuevos que no tienen código de cliente. Confirmame si podés subirlos sin código o con código repetido. Por lo que entiendo si porque ya hay en la base subida unos cuantos sin código. Lo que no se pueden repetir son las razones sociales no?

[Nuevos Distribuidores Revear 03-06.xlsx](https://github.com/LeandroBraier/Klaukol/files/297776/Nuevos.Distribuidores.Revear.03-06.xlsx)

**Comment by mkreyness** [comment]
las razones sociales se repiten mucho mas todavia, porque esto en realidad son LOCALES de distribuidores, no empresas. Pinturerias Prestigio esta como 80 veces (una por cada local), y la razon social siempre es la misma.
Si, los puedo cargar sin codigo, lo que no podia es saber cuales de los que habia eran nuevos porque no hay nada 100% distintivo (salvo tal vez el domicilio, pero tambien eso podia estar escrito diferente y ser el mismo lugar.
Ahora las subo. Acordate que habria que revisar si todas las direcciones aparecen bien en el mapa, y si no forzarle coordenadas.

**Comment by mkreyness** [comment]
la verdad que es un infierno para cualquier geolocalizador como ponen las direcciones, hay un numero metido delante del nombre de la ciudad, que no significa nada, lo tengo que sacar si no va a fallar todo. Y por otra parte ponen en Capital como si fueran ciudades los nombres de las sucursales (porque ni siquiera son barrios, "T.Garcia" no es un barrio).
Lo estoy limpiando todo antes de subir.

**Comment by LeandroBraier** [comment]
Entiendo. Avisame si necesitás que te ayude con algo de eso y después
pasame como te quedó asi la proxima te lo limpio yo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-06-03 18:05 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ya esta todo subido.
Lo que hay que revisar con cuidado siempre es la columna de localidad, porque en el caso de las cadenas grandes lo que ponen ahi es un numero de sucursal y despues algo que a veces es una localidad, muchas veces abreviada (por ejemplo, "VARELA" en vez de "FLORENCIO VARELA") o directamente el nombre de la calle. Especialmente en Mendoza estaban todas mal las localidades, tuve que buscar por numero de telefono para saber realmente donde estaba c/u.

**Comment by LeandroBraier** [comment]
Ufff que laburo. Gracias MK!! La próxima lo reviso yo directamente. abrazo
