### ISSUE TITLE
Pop up + Header Web ParexKlaukol. 22-07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#319]
@FAAREIA necesito que vayas preparando los siguientes materiales para que, cuando yo te avise que lanzamos la campaña de "Klaukol En Busca del Gran Colocador" vos los puedas subir a la web principal de ParexKlaukol en ese mismo momento.

Los elementos son:

1) Un pop up (clásico, con link a www.klaukoltebusca.com.ar)

![pop up gana un viaje a barcelona 1](https://cloud.githubusercontent.com/assets/6719872/15765626/3f93e1b4-290d-11e6-8068-64fd2b71eb71.png)

2) Un pequeño diseño para el header de la web, que reemplazaría el espacio central que actualmente tiene el pack de Klaukol Impermeable Potenciado. Se vería así:

![header-web](https://cloud.githubusercontent.com/assets/6719872/15765621/380a027a-290d-11e6-80c7-e8c0ad8367ef.jpg)

También con link a www.klaukoltebusca.com.ar

Este diseño lo podés descargar de este mismo link:

https://mega.nz/#F!H9lhVR5T!w0Pro0NWiUB00WxCSDQuSA

abrazo

**Comment by FAAREIA** [comment]
Ahi lo dejé todo preparado para cuando se lance ;)
abrazooo

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA !! Cierro el ticket y te aviso cuando hay que subirlo a producción.

Probablemente te pasemos cambios para el pop up antes, el cliente está pidiendo cambios aparte. 

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA el lunes necesito que subas el POP UP y el header. Te los paso acá ajustados con la nueva info de la campaña.

![pop up](https://cloud.githubusercontent.com/assets/6719872/17041594/67a2d048-4f7d-11e6-9a9f-f9b90b2319b3.png)

HEADER:

https://mega.nz/#F!5MID2QII!mn_eQnMUJC1v4lVSEWQRjQ

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA si podés confirmame si podés dejar listo esto para subirlo el lunes estamos joya.

**Comment by FAAREIA** [comment]
Todo preparado

**Comment by LeandroBraier** [comment]
Genial @FAAREIA ! Gracias!

El lunes publicado directamente. Si llega a cambiar algo yo te aviso, sino ya publicalo nomás.

abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo estás? Porfa avisame cuando subas el pop up y el header nuevos.

abrazo

**Comment by FAAREIA** [comment]
Job done

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Genial!
