### ISSUE TITLE
Analytics para Argentina, Paraguay y Uruguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#32]
Fede, te paso los ID y Scripts para que subas Analytics a los distintos sitios. Si necesitás algo más decime. El miércoles voy a investigar algunas cosas más de analytics nuevas a ver qué nos suman.+

Argentina

ID de seguimiento 
UA-63615243-1

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63615243-1', 'auto');
  ga('send', 'pageview');

</script>

Paraguay

ID de seguimiento
UA-63615243-3

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63615243-3', 'auto');
  ga('send', 'pageview');

</script>

Uruguay

ID de seguimiento
UA-63615243-2

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63615243-2', 'auto');
  ga('send', 'pageview');

</script>

**Comment by braulio-evangelisti** [comment]
Listo ya está implementado para los 3 sitios.

Abrazo

**Comment by LeandroBraier** [comment]
Genial! Gracias.
