### ISSUE TITLE
Juego Constructores Furiosos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#320]
Buen día @valentinsabbath !! Cómo andás? Te paso un nuevo juego a tunear para Parex y para VIE TUR.

Necesito que lo abras con el programa de HTML5 y me pases las piezas que se pueden reemplazar (necesitamos meter la marca Klaukol /VIE TUR en los banners de atrás y reemplazar al referí que se cae de las maderas por otras figura, por ejemplo).

[codecanyon-7920976-angry-soccer-cup-2014-html5-game.zip](https://github.com/LeandroBraier/Klaukol/files/300361/codecanyon-7920976-angry-soccer-cup-2014-html5-game.zip)

El link con la info es esta:

http://codecanyon.net/item/angry-soccer-cup-2014-html5-game/7920976?s_rank=9

Confirmame recepción porfa.

abrazo

**Comment by ghost** [comment]
Otro juego hecho con » Made with GameMaker Studio 
No puedo abrirlo con Construct2

**Comment by LeandroBraier** [comment]
Fuck. Habíamos chequeado en teoría que el juego fuera para Construct 2.

GameMaker Studio tiene versión gratis igual. Te fijás si podés intervenirlo igual en este caso?

http://www.yoyogames.com/gamemaker

Aparentemente no tiene una curva de aprendizaje demasiado elevada. Chequealo Valen porfa.

**Comment by ghost** [comment]
Es muy simple, no se necesita abrirlo con ningun programa. Son estas imàgenes las que te permite cambiar.
Importante: NO se puede modificar el juego, ni siquiera se lo puede importar al Game Maker porque está en la versión "compilada" o "final" y no en la versión de código (para programar).

![angrysoccer_smile_texture_0](https://cloud.githubusercontent.com/assets/16599421/15877599/3d5532ae-2ceb-11e6-9595-3af93014b955.png)
![angrysoccer_smile_texture_1](https://cloud.githubusercontent.com/assets/16599421/15877600/3d568aa0-2ceb-11e6-9536-cae3748df2d4.png)
![angrysoccer_smile_texture_2](https://cloud.githubusercontent.com/assets/16599421/15877601/3d58704a-2ceb-11e6-9315-53cd46a409b9.png)
![angrysoccer_smile_texture_3](https://cloud.githubusercontent.com/assets/16599421/15877602/3d5ad312-2ceb-11e6-81cd-fda4a516fd6b.png)
![angrysoccer_smile_texture_4](https://cloud.githubusercontent.com/assets/16599421/15877603/3d5cd5a4-2ceb-11e6-9750-4d7636ba5c9c.png)

**Comment by ghost** [comment]
![splash](https://cloud.githubusercontent.com/assets/16599421/15877717/f52b2c08-2ceb-11e6-8c33-58f5eb533d82.png)

**Comment by LeandroBraier** [comment]
Ah genial Valen! Mejor todavia entonces no? Perfecto.

**Comment by ghost** [comment]
El juego anterior hubo que programarlo para que cuando el jugador finalice
el juego, lo redireccionaba a otra web. En este juego esto no se va a poder
hacer

2016-06-07 20:52 GMT-03:00 LeandroBraier notifications@github.com:

> Ah genial Valen! Mejor todavia entonces no? Perfecto.
> El jun. 7, 2016 8:11 PM, "valentinsabbath" notifications@github.com
> escribió:
> 
> > [image: splash]
> > <
> > https://cloud.githubusercontent.com/assets/16599421/15877717/f52b2c08-2ceb-11e6-8c33-58f5eb533d82.png
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> > https://github.com/LeandroBraier/Klaukol/issues/320#issuecomment-224441815
> > ,
> > or mute the thread
> > <
> > https://github.com/notifications/unsubscribe/AGaJgE6jU1DRXBoTQ78nR1n4Q202W4ikks5qJfqNgaJpZM4Iu2dZ
> > 
> > .
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/LeandroBraier/Klaukol/issues/320#issuecomment-224448560,
> or mute the thread
> https://github.com/notifications/unsubscribe/AP1JffFvdrQYXz39tJxJftaWiAd-Ulzjks5qJgQ3gaJpZM4Iu2dZ
> .

## 

_Atte. Valentín Gavela._

**Comment by LeandroBraier** [comment]
Consultalo con MK porfa a ver como podemos resolverlo. Quiza como hacíamos
con los juegos flash.

**Comment by ghost** [comment]
@mkreyness , qué se puede hacer en este caso?

**Comment by mkreyness** [comment]
Si no podes intervenir en el fuente del juego, no se puede hacer nada. 
Lo del flash tambien era modificando el fuente, era codigo que abria un URL, conceptualmente lo mismo que en Construct2.

**Comment by LeandroBraier** [comment]
@mkreyness podemos saber si entraron a jugar al menos? Si hicieron clic en el juego para jugar?

**Comment by LeandroBraier** [comment]
El archivo principal no es un javascript? No se puede meter código ahí?

**Comment by mkreyness** [comment]
No tengo idea QUE COSA es el juego. Si es un javascript puede estar "obscured" por lo tanto ser incomprensible. No seria imposible, pero habria que dedicarle un tiempo a encontrar el lugar donde sucede el "final" del juego.

**Comment by LeandroBraier** [comment]
Si podés bajatelo y fijate:

[codecanyon-7920976-angry-soccer-cup-2014-html5-game.zip](https://github.com/LeandroBraier/Klaukol/files/300361/codecanyon-7920976-angry-soccer-cup-2014-html5-game.zip)

@valentinsabbath si es un javascript vos podés revisar y ver donde meter lo de los puntos, no?

**Comment by mkreyness** [comment]
ya me fije con debugger de chrome sobre el preview. Lo que quise decir es "obfuscated, maldito corrector". Tal cual, esta totalmente obfuscado, las rutinas y las variables tienen todos nombres cripticos, no se puede practicamente saber nada. Trate de debuggearlo un poco para ver si podia atraparlo cuando dice "You Win"  pero no lo logre. Seguro que se puede, pero hay que dedicarle horas a encontrarlo.

**Comment by LeandroBraier** [comment]
@valentinsabbath vos podés intentar debuggear eso? Tenemos un poco de tiempo, no tiene que ser esta semana, pero resolverlo en este caso lo vamos a tener que resolver igual.

**Comment by ghost** [comment]
@LeandroBraier lo voy a intentar

**Comment by LeandroBraier** [comment]
Muchas gracias Valen! Avisame cualquier cosa.

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath ! Como va?

Te paso acá las imagenes para reemplazar. Vos poneles los nombres correctos a cada una nomás.

https://www.dropbox.com/s/pg0liiq7kkxuzvw/Imagenes%20a%20reemplazar%20en%20Juego%20ParexKlaukol%20y%20VIE%20TUR.zip?dl=0

Pudieron resolver lo del debugger?

**Comment by ghost** [comment]
Hola @LeandroBraier  todo bien vos!?
Está MUY dificil este código. Tiene 60.000 líneas todas en clave que es imposible de entender.
La verdad que no se si voy a poder encontrar la parte en donde termina

**Comment by LeandroBraier** [comment]
Ok. Sigamos intentando porque ya no nos queda otra.

**Comment by LeandroBraier** [comment]
@mkreyness acá hablamos con Eze y Valentín el tema. Sumemosle los puntos al usuario cuando empieza a jugar. Con eso estamos.

**Comment by mkreyness** [comment]
El problema es que la llamada al URL que suma los puntos termina en volver al juego, eso tiene sentido al final, pero dificilmente al principio.
Hay que hacer un template con un enfoque diferente.
@valentinsabbath que es lo que iria en sí como juego en la página, un iframe con un URL ?

**Comment by LeandroBraier** [comment]
Entiendo. Valentín tenía una propuesta un poco más avanzada para esto que
quizá te sirva. Busquenle la vuelta por ese lado pero no tiene sentido
meterse en el código "ofuscado".

2016-06-14 16:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by ghost** [comment]
Si, es un iframe. Yo decia que quizas se podia dar el premio a los segundos
de que el jugador haya entrado

**Comment by mkreyness** [comment]
Que entro a donde, a la pagina o al juego ? El click que haga dentro del iframe yo no lo recibo, asi que nunca sumaria los puntos.
Lo mas facil seria que la pagina NO muestre el iframe, sino que tenga un boton de "Empezar a jugar" y que cuando se clickee ahi llame al programa que suma puntos y este cuando vuelva pase en el URL algun codigo que haga que SI aparezca el iframe pero con el juego YA INICIADO. 
Pero no se si eso es posible (que el juego arranque apenas se cargue la pagina.

**Comment by mkreyness** [comment]
Aca hay algo que podria funcionar para detectar un click en un iframe, aunque no se si en todos los browsers, especialmente mobile:

var monitor = setInterval(function(){
    var elem = document.activeElement;
    if(elem && elem.tagName == 'IFRAME'){
       ACA IRIA LA LLAMADA AJAX PARA SUMAR PUNTOS
        clearInterval(monitor);
    }
}, 100);

**Comment by mkreyness** [comment]
pasame lo que haya que instalar del juego y como deberia invocarse desde el IFRAME y lo pruebo.

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath y @mkreyness !

Avisenme cuando pueda probar el juego y el tema de los puntos. abrazo grande

**Comment by mkreyness** [comment]
@valentinsabbath pasame las cosas asi las instalo y puedo avanzar por favor.
Ya esta customizada la interface del juego (imagenes, etc) ?

**Comment by ghost** [comment]
Perdón por el retraso.
@LeandroBraier: Tienen errores las imagenes que me pasaste:
El PNG está mal hecho

![1](https://cloud.githubusercontent.com/assets/16599421/16083473/6fbd0072-32eb-11e6-940d-94dfccb6d59b.png)
![2](https://cloud.githubusercontent.com/assets/16599421/16083476/71d790b6-32eb-11e6-867b-e1755b8bdfea.png)

**Comment by valentinsabbath** [comment]
@mkreyness  Esto es para colocarlo en la pagina:

**Comment by valentinsabbath** [comment]
@mkreyness Esto es para colocar el juego en la pagina:
    <body>
        <div class="gm4html5_div_class" id="gm4html5_div_id">
        <img src="SAM/splash.png" id="GM4HTML5_loadingscreen" alt="smilegames:HTML5 loading screen" style="display:none;"/>
            
            <canvas id="canvas" width="1024" height="768">
               <p>Your browser doesn't support HTML5 canvas.</p>
            </canvas>
        </div>

        
        <script type="text/javascript" src="SAM/AngrySoccer_Smile.js?ETSYB=1627382381"></script>
		
		<script>
			document.body.setAttribute("style","-ms-touch-action: none;");
		</script>

**Comment by LeandroBraier** [comment]
Entiendo Fede. Consulto y te digo.

**Comment by ghost** [comment]
@mkreyness  este es el codigo para colocarlo en la pagina
[code.txt](https://github.com/LeandroBraier/Klaukol/files/316310/code.txt)

**Comment by mkreyness** [comment]
@LeandroBraier: es "Valentin", no "Fede" 
Esto me exculpa cuando dije "Fran" en vez de "Fede" :)

**Comment by mkreyness** [comment]
@valentinsabbath , ese codigo llama a un js, que capaz me lo pasaste, pero seguro hay un monton de cosas mas que instalar (iconos, css, etc), me pasas todo junto en un .tar.gz o algo asi ?

**Comment by LeandroBraier** [comment]
jajja Mil disculpas Valen!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by ghost** [comment]
Está todo en el comprimido que te pasó Lean mas arriba, pensé que lo habías ejecutado.
Pero acá te mando el tarball:
[angry.tar.gz](https://github.com/LeandroBraier/Klaukol/files/316350/angry.tar.gz)

**Comment by mkreyness** [comment]
algun motivo para que se llame "AngryVietur" la carpeta ? Esto es para Klaukol, o estoy yo confundido ?

**Comment by ghost** [comment]
También va a ser para a vietur, pero se puede cambiar el nombre porque no
está modificado todavia

**Comment by mkreyness** [comment]
Ah, porque lo estoy probando en Parex y como a su vez el thread este dice "Klaukol", no entendia nada. Ok. Ya en un ratito lo tengo andando todo.

**Comment by mkreyness** [comment]
Listo, el truco ese para detectar el click no funcionó, pero encontre otro. pero queda mal (corrido y demasiado ancho) en la maqueta, tal vez tenga que intervenir @FAAREIA un momento para ajustarlo.

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?usuario=LeandroBraier&clave=parexklaukol&id=54

Acordate @LeandroBraier para ver si te suma los puntos (le puse 100) que tenes que dessuspenderte.

Fede: el template es www/templates/vendedores/juego-jsT.html

@LeandroBraier : no te olvides subir alguna imagen de instructivo, como en el resto de los juegos.
Para que se use este template y no otros al juego hay que ponerle como tipo (y ya le puse) "Juego JS Ofuscado".

**Comment by ghost** [comment]
el problema es el scrolling. Con la rueda del mouse para atrás hacés reducís el zoom del juego. Pero al mismo tiempo la página se va para abajo. Se pude bloquear el scrolling cuando estás en la zona del juego?

**Comment by mkreyness** [comment]
yo no hago ningun scrolling y lo veo horriblemente corrido.
El problema es que el iframe tiene un tamaño fijo, que no tiene las mismas proporciones que el juego.
Seguramente se pueda bloquear el scrolling, pero no cambia esto.

**Comment by ghost** [comment]
Lo que digo es que el juego utiliza el scroll como zoom in zoom out

**Comment by LeandroBraier** [comment]
Buen día @mkreyness y @valentinsabbath , ya empezamos mal: el juego que subieron no tiene las imágenes cambiadas, es el origen bajado de ENVATO y además se mal subido en la caja del juego:

<img width="1091" alt="captura de pantalla 2016-06-16 a las 10 01 15 a m" src="https://cloud.githubusercontent.com/assets/6719872/16116955/f9201b28-33a5-11e6-9352-046a8a3dffef.png">

Coordinen entre uds por favor. Hablen por teléfono, por whatsapp. NO perdamos tiempo por no levantar el tubo.

**Comment by FAAREIA** [comment]
Ya esta solucionado el tema del iframe y quedó responsivo.
Lo de evitar el scroll lo veo rebuscado ya que la página es larga y necesita scroll. Lo que yo haría para evitar códigos rebuscados es agregarle un botón de `lupa +` y `lupa -` que hagan zoom in y out.

**Comment by ghost** [comment]
@LeandroBraier mas arriba aclaré que las imágenes que me pasaste están mal hechas y puse las imagenes. @FAAREIA fijate mas arriba que te muestra cómo quedan las imágenes en el juego. Hay un problema con los bordes de los objetos.

**Comment by FAAREIA** [comment]
Qué problema? En firefox no veo nada, posteate un screenshot. Si es lo de los bordes negros, ya se solucionó.

**Comment by ghost** [comment]
@FAAREIA, mas arriba, con el logo, los árbitros, las pelotas, la gomera

![1](https://cloud.githubusercontent.com/assets/16599421/16121578/2f6249f4-33ba-11e6-98ca-568f75125405.png)

![2](https://cloud.githubusercontent.com/assets/16599421/16121552/192bbee0-33ba-11e6-819a-ef1997bfc33d.png)

**Comment by FAAREIA** [comment]
En Firefox, Chrome e IE11 de Windows 8 se ve bien el juego. Imagino que vos tenes mac y es un bug de rederización de iOS o del navegador webkit (safari / chrome). Además los objetos que se te ven mal no aparecen como tags en el HTML por lo que no pueden ser impactados por CSS.

En IE11 el único bug que encontré es que la pantalla inicial no se adapta al ancho y alto, pero si se adapta cuando empieza el juego.

**Comment by FAAREIA** [comment]
El testing no fue en localhost, aviso por las dudas. Probalo online

**Comment by ghost** [comment]
@FAAREIA es raro, porque en Linux con Chrome, se ve bien el juego original. Igual lo paso para que lo probemos.
@mkreyness te subo el juego que le puse las imagenes personalizadas que hizo Fede.  
[angry.tar.gz](https://github.com/LeandroBraier/Klaukol/files/318750/angry.tar.gz)

**Comment by LeandroBraier** [comment]
Tenés razón Valen. las imagenes están de mi lado, no me acordaba de eso. El
martes la vamos a tener.

**Comment by mkreyness** [comment]
Con esta version lo veo todo bien, recuerden cuando hagan las imagenes definitivas que sean compatibles con estas.

**Comment by LeandroBraier** [comment]
@valentinsabbath te paso las piezas de la versión de Klaukol. Probalas. Si están OK te mando las de VIE TUR.

![slide 5 constructores furiosos](https://cloud.githubusercontent.com/assets/6719872/16135331/4b4c119c-33f9-11e6-87d6-10ac1496a7f3.png)
![slide 2 klaukol](https://cloud.githubusercontent.com/assets/6719872/16135332/4b4c03be-33f9-11e6-86c4-dc984ad62930.png)
![slide 1 klaukol](https://cloud.githubusercontent.com/assets/6719872/16135334/4b514c5c-33f9-11e6-93f8-1d2892a7485a.png)
![slide 4 klaukol](https://cloud.githubusercontent.com/assets/6719872/16135333/4b51207e-33f9-11e6-9784-b194ba2b6865.png)

Confirmenme si pueden hoy si está todo OK.

**Comment by mkreyness** [comment]
yo no puedo confirmarte nada porque no se ni donde van. Cuando Valentin las integre y me reenvie el paquete, probamos online.
En VIE TUR todavia no arme la logica del template ni nada, pero lo puedo ir preparando.

**Comment by ghost** [comment]
@LeandroBraier lo que hay que corregir en la última imágen que me pasaste es que a lo que está sin transparencia hay que hacerlo TODO TRANSPARENTE. Por eso me parace funciona mal. Fijate que en las imagenes originales que te paso aca el fondo es transparente (cuando te las descargas te das cuenta mejor)
![angrysoccer_smile_texture_](https://cloud.githubusercontent.com/assets/16599421/16171811/a2cef8e2-354f-11e6-8a99-6d83f1dc4f8c.png)

![angrysoccer_smile_texture_22](https://cloud.githubusercontent.com/assets/16599421/16171816/c9e508d6-354f-11e6-82c7-2fc1ec69680f.png)
![angrysoccer_smile_texture_00](https://cloud.githubusercontent.com/assets/16599421/16171819/ea5633b0-354f-11e6-95d0-b90e7123db25.png)

**Comment by LeandroBraier** [comment]
Perfecto. Ahi esta la cuestion. Te la corrijo y tr la mando. Gracias valen!

**Comment by LeandroBraier** [comment]
Aquí van con las correcciones @valentinsabbath !! 

Por favor necesitaría tener el juego subido mañana a la mañana lo más temprano posible para probarlo y ver si podemos publicarlo ya a la tarde. abrazo

![slide-4-klaukol-transparente](https://cloud.githubusercontent.com/assets/6719872/16215490/1b13f3b2-3739-11e6-8832-4f61aae71f2a.png)

![slide-3-para-ambos-transparente](https://cloud.githubusercontent.com/assets/6719872/16215492/1cd945bc-3739-11e6-9427-bf140a332dd3.png)

![slide-2-klaukol-transparente](https://cloud.githubusercontent.com/assets/6719872/16215551/8da7f5ea-3739-11e6-8d2e-c464e4b54b78.png)

![slide-1-klaukol-transparente](https://cloud.githubusercontent.com/assets/6719872/16215554/8f7c116c-3739-11e6-879b-71511d2492e5.png)

**Comment by mkreyness** [comment]
yo hasta las 9:30 estoy conectado, despues ya mucho mas complicado.
@valentinsabbath Si me rearmas el tar antes de esa hora, lo subo y dejo andando.

**Comment by LeandroBraier** [comment]
Gracias MK! Yo toy desde temprano también.

**Comment by ghost** [comment]
Imágenes cambiadas. Fijense si funciona!
[Angry Soccer - Cup 2014.tar.gz](https://github.com/LeandroBraier/Klaukol/files/324682/Angry.Soccer.-.Cup.2014.tar.gz)

**Comment by mkreyness** [comment]
ahi lo puse pero anda mal, a veces da un error y en general las imagenes de los arbitros son tan transparentes que no se ven.

**Comment by mkreyness** [comment]
El error que tira es 
Uncaught InvalidStateError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

asi que alguna imagen tiene problemas o falta.

**Comment by LeandroBraier** [comment]
Buen dia equipo!

Fijate Valen que problema puede haber. Lo de la imagen de los arbitros
decime cual es el problema y te mando la imagen corregida.

**Comment by ghost** [comment]
Creo que este ya funciona bien 
[Angry Soccer - Cup 2014.tar.gz](https://github.com/LeandroBraier/Klaukol/files/325554/Angry.Soccer.-.Cup.2014.tar.gz)

**Comment by LeandroBraier** [comment]
Gracias Valen! Avisenme porfa cuando pueda probarlo en la comunidad de
Parex.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo ya esta subido y parece andar todo bien. NO TE OLVIDES @LeandroBraier de poner un instructivo, si no se queda ahi una imagen negra colgada.

**Comment by LeandroBraier** [comment]
@mkreyness y @valentinsabbath anda perfecto el juego, pero no carga los puntos.

Me detecta que lo jugué, pero no me lo suma los puntos (y eso que me cambié de SUSPENDIDO a ACTIVO) Se fijan eso porfa?

En una hora les paso las imagenes para subir el de VIE TUR también y sumo los instructivos.

**Comment by mkreyness** [comment]
solo suma una vez el juego, ya lo jugue yo en tu nombre antes, por lo tanto no te vuelve a sumar.
O queres que CADA vez que entran vuelva a sumar ?

**Comment by LeandroBraier** [comment]
En Parex esta bien que sumen una sola vez. Más adelante sacamos un mes de ilimitado.

Para ese te pido @valentinsabbath si podés reemplazar esta imagen:

![slide 3 para klaukol-transparente](https://cloud.githubusercontent.com/assets/6719872/16245879/35897b9a-37d9-11e6-924e-d04f7d36892a.png)

En VIE TUR todos los juegos pueden sumar 10 veces el puntaje del juego, no te olvides @mkreyness .

@valentinsabbath te paso en este zip las 5 imagenes para VIE TUR. Confirmame si está todo OK y pasale a MK porfa para que lo suba también asi lo probamos.

[Imagenes Juego Agentes Furiosos VIE TUR.zip](https://github.com/LeandroBraier/Klaukol/files/326570/Imagenes.Juego.Agentes.Furiosos.VIE.TUR.zip)

abrazo

**Comment by mkreyness** [comment]
Despues de probar esto (cuando @valentinsabbath me lo pase integrado) te borro todas las jugadas asi probas que te sume (una vez).
Cuando ande todo ahi lo paso a VIE TUR. En realidad ahi esta todo "hasta 1000 puntos", no "10 veces el juego". Es fijo.

**Comment by LeandroBraier** [comment]
@mkreyness ya cargué el instructivo pero me da error al cargar la imagen. Te fijás qué puede ser?

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=54

usuario=LeandroBraier&clave=parexklaukol

abrazo

**Comment by mkreyness** [comment]
El link que pusiste es a algo efimero o privado, no funciona. Probe de abrirlo a mano y da error.
Esto es lo que pusiste:

https://www.facebook.com/parexklaukolarg/photos/p.932318930223785/932318930223785/?type=3&theater

Tenes que poner un link a algo permanente/no privado/y supongo que nunca https.

**Comment by LeandroBraier** [comment]
@mkreyness el link te da error porque no está publicado el posteo aún. Lleva al posteo que queremos que ser comparta con el botón de "Share". Vos nos habías dicho que ese campo era para eso. 

Lo que me entiendo que me decís es que para que funcione el instructivo tengo que poner ahi el link tengo que subir la ruta del Instructivo. Si se puede, podés hacer que no sea así? Es decir, que usemos el Upload de Imagen para subir el instructivo y ya el template tome el mismo de allí? Asi podemos usar el campo de URL para lo que queremos que el botón de "Share" comparta.

**Comment by LeandroBraier** [comment]
@valentinsabbath y @mkreyness ya publiqué el Juego de Klaukol. Cuando cambien el juego con la nueva imagen eso no va a alterar nada no?

Quedo a la espera de que resuban el juego con esa nueva imagen y me avisen cuando esté subido el de VIE TUR también.

abrazo

**Comment by mkreyness** [comment]
Claro, ahi puse que en vez del campo "url" tome el de imagen (solo para este juego, ojo, no se si en los demas realmente esta puesto asi).
Pero si bien eso te libera el URL para poner el share, notaras que este template de juegos NO TIENE un boton de compartir, habria que agregarlo.
Yo estoy esperando a que @valentinsabbath lo rearme y me lo mande, y en cuanto lo tenga lo subo.
En teoria no tendria por que romperse nada.
Todavia no pase nada de esto a VIE TUR, definamos primero entonces si tiene que ir boton de share (ningun juego lo tuvo hasta ahora)

**Comment by LeandroBraier** [comment]
Perdón, pensé que lo teníamos. Olvidemonos del botón de share entonces, no
perdamos tiempo con eso. Avancemos con la versión de VIE TUR cuando Valen
te lo pase.

abrazo

2016-06-21 21:29 GMT-03:00 mkreyness notifications@github.com:

**Comment by ghost** [comment]
Angry-Parex con la imagen que me pediste @LeandroBraier 
[Angry Soccer.tar.gz](https://github.com/LeandroBraier/Klaukol/files/326915/Angry.Soccer.tar.gz)

**Comment by valentinsabbath** [comment]
@LeandroBraier fijate q

**Comment by ghost** [comment]
@LeandroBraier fijate que las imagenes de vie-tur tiene los mismos errores que tenian las de Parex

**Comment by mkreyness** [comment]
ya puse la ultima version de Angry en produccion.
Te borre todas las veces jugadas, fijate cuando lo pruebes si te suma los puntos, y si no avisame.

**Comment by mkreyness** [comment]
ya tengo todo implementado en VIE TUR tambien, lo que faltaria es el juego propiamente dicho (por ahora esta puesto el de Klaukol para probar) y obviamente ponerle una imagen de instructivo adecuada (tambien la toma de la IMAGEN, no del URL).
Acordate que el limite es 1000 fijo, yo al juego que cargue de prueba le puse 100, si va a ser otra cosa voy a tener que cambiar a que en vez de 1000 sea (puntosjuego \* 10)

**Comment by LeandroBraier** [comment]
@valentinsabbath necesito que me digas qué necesitás que le cambie a las imágenes de VIE TUR porque estamos chequeando y las vemos iguales a las de Klaukol. Porfa dale prioridad a esto que ya tendría que haber salido ayer.

abrazo

**Comment by ghost** [comment]
El slide 4 no tiene el fondo transparente
![slide 4 vie turl agentes furiosos](https://cloud.githubusercontent.com/assets/16599421/16267086/6535dec6-385e-11e6-9d31-97f96d4ec157.png)

**Comment by LeandroBraier** [comment]
Gracias! Solo eso?

**Comment by ghost** [comment]
Solo eso!

**Comment by LeandroBraier** [comment]
Genial! La próxima decinos directamente lo que falta porfa, asi lo resolvemos más rápido.

Aquí va corregido:

![slide-4-vie-tur-agentes-furiosos-transparente](https://cloud.githubusercontent.com/assets/6719872/16267326/9aae8a8e-385f-11e6-9ff0-f5be9bb6231e.png)

Confirmame cuando esté todo subido porfa.

abrazo

**Comment by ghost** [comment]
Listo
[Angryvietur.tar.gz](https://github.com/LeandroBraier/Klaukol/files/327886/Angryvietur.tar.gz)

**Comment by LeandroBraier** [comment]
Gracias @valentinsabbath ! @mkreyness llegás a reemplazarlo ahora?

**Comment by mkreyness** [comment]
si, ya te aviso

**Comment by mkreyness** [comment]
listo, no te olvides las instrucciones, y el jopo de los agentes queda cortado, recien se ve cuando se los golpea y caen.

**Comment by LeandroBraier** [comment]
jaja es cierto! Pero es mínimo. Gracias @mkreyness ! Ya subí el instructivo y probé y quedó funcionando. Gracias chicos por todo!!!

abrazo grande y les aviso cualquier cosa.
