### ISSUE TITLE
Subir PDFs en CMS

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#321]
@FAAREIA necesito subir este PDF al producto PAREX DECOFLEX RULATO TRAVERTINO

[Ficha Tecnica PAREX DECOFLEX RT.pdf](https://github.com/LeandroBraier/Klaukol/files/309724/Ficha.Tecnica.PAREX.DECOFLEX.RT.pdf)

@mkreyness se lo pido a Fede porque hay que subirlo para el lunes pero no quería dejar de consultarte a vos si no podemos hacer que en el futuro los suba yo directamente a los PDF, me parece muy pavo tener que pedirle a Fede que haga algo tan sencillo.

abrazo

**Comment by mkreyness** [comment]
El tema es que esta puesto para que puedas linkear a PDFs (u otros documentos) que esten FUERA del sitio, o a esas porquerias de backup de donde arrancamos. 
Si TODOS los documentos estan dentro del sitio, tenemos que moverlos a un lugar unico y ahi te convierto a un upload.
En realidad el mayor problema es que no tengo en el CMS un upload de archivos genericos, solo de imagenes y video (imaginate lo peligroso que seria tener un link que permita hacer upload de CUALQUIER cosa, un robot podria facilmente detectarlo y usarlo para inyectar viruses).
Pero podria hacer uno para uploadear PDFs, si es que siempre son PDFs.
Lo que pasa tambien es que este no es el mejor momento para distraerme con eso, capaz despues de terminar PatyChile.

**Comment by LeandroBraier** [comment]
Ok no problem. Le pido a Fede entonces que los siga subiendo por ahora. No
hay problema. Gracias MK!

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!! En el link de Ficha técnica está perfecto. En la presentación interactiva intenté cambiar el link pero aún no lo veo actualizado.

Igual como la presentación anterior estaba en Scribd para que se vea ahí deberíamos subirla a Scribd no? O se puede poner un display del mismo PDF de la ficha técnica que ya subiste? Eso sería ideal.

**Comment by FAAREIA** [comment]
El link de scribd si no me equivoco es un iframe por lo que si queres que se visualice un PDF en ese lugar, hay que armarlo. Igual me parece que nunca tuvo sentido lo de Scribd, ahi tan chico.... un PDF sería lo mismo, va a quedar diminuto todo. Además si es una ficha técnica lo que queres subir ahi, no sería una "Presentación interactiva" y el link hacia la ficha técnica estaría duplicado sin sentido.

**Comment by LeandroBraier** [comment]
Ok, entiendo lo que decís Fede!!

Lo quito y listo.

abrazo
