### ISSUE TITLE
Calculador de Consumo Revear: Faltan productos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#322]
@mkreyness estoy viendo que faltan productos en el calculador. Por ejemplo, Marble. Puede ser?

Me confirmás apenás podés tener todos ahí?

**Comment by mkreyness** [comment]
Para que un producto aparezca en el calculador tiene que tener cargados los datos que permiten el calculo (basicamente las presentaciones) Habiamos quedado que los que faltaban los datos no los mostrara, porque si no daba error el calculo.
Con que le cargues los datos que le faltan, va a aparecer automaticamente.

**Comment by LeandroBraier** [comment]
Perfecto MK. No lo recordaba. Gracias!

**Comment by LeandroBraier** [comment]
@mkreyness ya agregué los datos que faltaban en Marble y Revividor pero siguen sin aparecer. Te fijás porfa?

**Comment by mkreyness** [comment]
Los agregaste en el "NUEVO Revear" ? Para mi que los agregaste en el viejo, porque el nuevo sigue sin tener ninguna presentacion cargada.

**Comment by mkreyness** [comment]
por si acaso: no es el campo de texto que dice "presentaciones" (eso es solo para lo que se muestra en la ficha del producto).
Es la SOLAPA "Presentaciones", donde se cargan renglone con unidad de medida y cantidad.
Cualquier duda fijate como esta cargado por ejemplo en el reveplaster

**Comment by LeandroBraier** [comment]
No entendí que tenía que cargarlo ahi. Estoy intentando y no me lo guarda. Te fijás si vos podés cargar las presentaciones en el CMS porfa? 

Lo estoy intentando en Nuevo Revear, por supuesto.

**Comment by mkreyness** [comment]
El CMS no esta poniendole bien el producto en el primer campo, entonces se guarda pero no queda vinculado con el producto.
Arreglo eso y te aviso.

**Comment by mkreyness** [comment]
listo, ya esta arreglado y cargue las tres presentaciones del marble, aunque no se bien si tienen que decir bolsa o balde o que. El de 300 le puse tambor, pero no se la diferencia entre el de 6 y el de 30 Kg.

**Comment by LeandroBraier** [comment]
Gracias MK. Ahora completo el resto. Abrazo
