### ISSUE TITLE
Subir Ficha Técnica Pastina Fluida

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#323]
@FAAREIA cuando puedas lo subís porfa?

[Ficha Técnica KLAUKOL PASTINA FLUIDA IMPERMEABLE ANTIHONGOS.pdf](https://github.com/LeandroBraier/Klaukol/files/315083/Ficha.Tecnica.KLAUKOL.PASTINA.FLUIDA.IMPERMEABLE.ANTIHONGOS.pdf)

Es para PASTINA FLUIDA IMPERMEABLE, la Pastina Roja.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! En qué producto la subiste?

Porque estoy viendo que es un producto que se llamaba diferente y me genera duda. Lo voy a consultar.

**Comment by FAAREIA** [comment]
El rojo: http://www.parexklaukol.com.ar/klaukol/pastina-klaukol-piezas-normales-fluidas.html

**Comment by LeandroBraier** [comment]
Perfecto Fede. Gracias!
