### ISSUE TITLE
Nueva URL para Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#324]
@FAAREIA el cliente está delegando una nueva URL al Club de Colocadores.

Es **www.clubklaukol.com.ar**

Está delegando a los mismos dns de siempre. Te aviso por si tenés que hacer algo más o solo chequear que se haga correctamente.

abrazo

**Comment by FAAREIA** [comment]
@mkreyness Copio a marce que seguro tiene que hacer algun truquito.
Por ahora lo que esta hecho es el agregado del dominio `clubklaukol.​com.​ar`, lo cual creó `public_html/clubklaukol`

**Comment by LeandroBraier** [comment]
Gracias Fede!! Espero el truquito de Marce entonces.

**Comment by mkreyness** [comment]
no, eso de ponerlo como si fuera un subdominio no sirve, y de hecho daba error hiciera lo que hiciese en esa carpeta.
Lo que habia que hacer era un alias con redireccion, como estaba "clubdecolocadores.com.ar".
Ahi hice lo mismo con clubklaukol.com.ar, hay que esperar un poco a que actualicen ellos sus archivos, porque por ahora sigue dando el mismo error que cuando estaba como subdominio (lo manda a una pagina http://www.clubklaukol.com.ar/cgi-sys/defaultwebpage.cgi)

**Comment by LeandroBraier** [comment]
Genial MK! Muchas gracias! Lo pruebo hasta que funque.
Clubdecolocadores.com.ar va a seguir funcionando también?

**Comment by mkreyness** [comment]
clubdecolocadores.com.ar sigue y va a seguir andando.
Pero el otro no termina de arrancar. A nivel cpanel estan identicos, y ambos apuntan al mismo IP.
Si mañana sigue igual yo sugiero mandar un mail a duplika.

**Comment by LeandroBraier** [comment]
Ok. Yo me ocupo no te preocupes. Si no sale les escribo. Quiza no hicieron
bien la delegación las chicas de parex.

**Comment by mkreyness** [comment]
no, la delegacion esta bien porque apunta al mismo IP, es algo dentro de Duplika.

**Comment by LeandroBraier** [comment]
Ya funciona Marce! Gracias!

**Comment by mkreyness** [comment]
A mi todavia no, que raro.

**Comment by LeandroBraier** [comment]
Son los servicios de internet por zona.  Con fede siempre nos pasa.

**Comment by LeandroBraier** [comment]
Gracias a los dos!
