### ISSUE TITLE
Bug en Consejos en Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#325]
@mkreyness cargué 3 nuevas fotos en la sección de consejos del Club de Colocadores y me dan error. Te fijás porfa qué pasa?

http://www.parexklaukol.com.ar/cgi-bin/consejoscolo.pl?

usuario=marcelokreyness&clave=pepe

Así no queda todo el fin de semana así.

**Comment by mkreyness** [comment]
fueron a guardarse a una carpeta equivocada (la de corralones).
Capaz todas las que tenian foto fueron cargadas cuando todavia estabamos con la primer version y al pasar a la segunda version se estropeo pero recien ahora se nota. 
Ahora lo arreglo y te aviso.

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Muchas gracias MK!! Buen finde largo!!
