### ISSUE TITLE
Consulta para añadir a Guía de Corralones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#326]
@FAAREIA consulta: si quisieramos destacar 2 o 3 corralones por mes (seteable desde el cms) en la Home de la Guía de Corralones. Como diciendo "Corralones destacados del mes" (por distintas razones), cómo te parece que podríamos hacerlo modificando lo menos posible el diseño de la Guía hoy? En base a esa propuesta que pienses, cuántos días estimás que te llevaría aplicarla?

**Comment by FAAREIA** [comment]
Es todo laburo de marce eso. Habría que hacer una imagen o una nota con link a los destacados y cuando se abre el link aparece la guía con esos corralones determinados.

**Comment by FAAREIA** [comment]
@mkreyness

**Comment by mkreyness** [comment]
pero no hay una "home" de la guia de corralones, es la guia y listo. 
No entiendo cuando deberia aparecer y a donde deberia llevar, si es una misma cosa.
Me parece mas bien que @LeandroBraier se refiere a que dentro de la tira que aparece al costado del mapa haya una seccion (como tenemos en los aside de vendedores, etc.) de los "Top 5 Corralones" o algo por el estilo, con un thumb de c/u (que nunca fueron cargados, para este caso deberian cargarse) y que al hacer click en alguno de ellos directamente lo centre y muestre en el mapa.

**Comment by LeandroBraier** [comment]
Exacto.

Fede: antes del trabajo de MK viene pensar el diseño de eso. El "como"
vamos a destacar uno o varios corralones. Por eso te pregunto a vos, para
que me hagas una propuesta de como lo diseñarias. Tal como esta ahora la
guia es difícil sumar ahi el destacado.  Entiendo que habria que reformarla
y por eso te consulto a vos.

**Comment by FAAREIA** [comment]
Había entendido otra cosa, ahora con lo que dice marce me quedó claro.
Lo que haría es meter un simple bloque sobre el mapa que se titule "Destacados del mes" y ahi metes una lista de top 5 o 10. El bloqué podría contraerse asi el usuario ve mejor el mapa.
El mobiles chicos estaría oculto obviamente, no hay espacio

**Comment by LeandroBraier** [comment]
Mmm entiendo pero :

1) necesito que funcione tanto si destacamos 1 como 5 corralones.

2) necesito que en mobile si se vea. En mobile si fuera 1 solo corralon
destacado podríamos usar ese bloque?

**Comment by FAAREIA** [comment]
Me lo imagino igual que los destacados Top5 de la comunidad de vendedores por ejemplo, por lo que si hay uno no hay drama, va a quedar algo vacio nomás excepto que le hagamos un diseño exclusivo para ese caso.

En mobile si se va a ver pero en resoluciones de 320 o 480 me parece muy invasivo, ya hasta el mapa es chico en esos casos. Si es necesario que aparezcan igualmente, pensaría otra forma de ponerlos que no sea un bloque o directamente que aparezcan siempre en el mapa visibles y con un puntero dorado o algo asi destacado.

**Comment by LeandroBraier** [comment]
Ok. Entonces en la versión más chica de Mobile no aparecen, pero en las
demás sí.

Por el momento entonces no lo pensemos como el Top 5. Pensemos en 1 solo
corralón destacado por mes que vaya en ese bloque, así se ve su nombre, su
thumbnail (yo los cargaría, obviamente) y un texto de por qué se destaca
ese mes.

Cuánto nos llevaría ese desarrollo? (calculen por favor horas de trabajo
enfocado en esto incluyendo diseño, maquetación y programación, yo después
le adiciono las horas necesarias teniendo en cuenta las demás tareas
paralelas).

2016-06-22 10:01 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si no hay rebusques en el diseño por parte del cliente, lo mio puede llevar 6hs máximo con responsivo incluido.

**Comment by LeandroBraier** [comment]
Gracias Fede! Calculo 10 hs tuyas entonces y estimo lo de MK en ponele
otras 6 hs. Cuando me confirma MK aviso al cliente.

abrazo

**Comment by mkreyness** [comment]
si.

**Comment by LeandroBraier** [comment]
Perfecto chicos! Gracias!
