### ISSUE TITLE
Pequeño Ajuste en Calculador de Consumo Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#327]
@mkreyness cuando puedas, sin apuro, necesito que en el Calculador de Consumo se pueda calcular sin necesidad de poner ancho y alto en metros. Me confirmás si se puede porfa?

Con que esté para mañana o el viernes estamos OK.

abrazo

**Comment by mkreyness** [comment]
El error es que los campos estan puestos como obligatorios, pero el calculo tiene previsto que solo ponga los m2 directo. Ya le saque la obligatoriedad.

**Comment by LeandroBraier** [comment]
Muchas gracias MK!! Perfecto ahora!
