### ISSUE TITLE
Bug Fichas Técnicas Web Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#328]
@mkreyness  te fijás qué pasa? Ahora no anda ninguna ficha técnica y en el CMS no aparecen cargadas.

En algunos productos se bajan con error. La verdad no recuerdo cómo fue esta subida, puede ser que nunca las hayamos subido? No puedo creer que eso se nos haya pasado. Además estaban todas en el sitio anterior. Cómo podemos recuperar eso?

En caso de que tenga que subirlas de vuelta por lo menos pasenme un acceso a ellas lo antes posible por favor.

**Comment by FAAREIA** [comment]
Creo que lo que falta es la variable de la url de la ficha técnica. Actualmente lo que hay es lo que dejé yo en la maqueta, un documento de prueba en pdf.
En este link pueden ver lo que digo http://www.revear.com.ar/productos-para-profesionales/revividor-colores-revear.html
@mkreyness

**Comment by LeandroBraier** [comment]
Sisi lo vi. No entiendo lo que decís de la variable. Lo uqe necesitamos son
las fichas técnicas. Pasame las URL donde están esas fichas técnicas y yo
las pongo producto por producto si es necesario. Lo que no tengo es esas
fichas técnicas y tenía entendido que ya estaban subidas, porque ya estaban
en el sitio anterior y esas URL las manejan uds en el hosting.

Se ve que también se me pasó a mi chequear.

**Comment by mkreyness** [comment]
Estaba previsto en los templates y en el CMS estan cargados los URLs, pero capaz con la "limpieza" del sitio viejo quedaron inaccesibles. Seguramente ANTES de eso andaban.
Ahora veo donde quedaron los documentos y los hago accesibles.

**Comment by mkreyness** [comment]
Listo. Ya quedo independizado del backup viejo, recree la misma estructura en el sitio vigente.
El del link que pasaste arriba @LeandroBraier ya funciona bien.

**Comment by LeandroBraier** [comment]
Ok, los otros los arreglás vos también?

Sino pasame las URLS y yo los arreglo a todos, como prefieras.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-06-22 14:15 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero estan TODAS las urls cargadas en el CMS, no hay nada que "arreglar".

**Comment by mkreyness** [comment]
lo que paso es que todo el contenido del "sitio viejo" se renombro, y estas cosas no se habian copiado al nuevo.
Ahora si.

**Comment by LeandroBraier** [comment]
Perfecto MK!!! Muchas gracias!!! abrazo

**Comment by FAAREIA** [comment]
En este producto sigue mal la url: http://www.revear.com.ar/productos-para-profesionales/revividor-colores-revear.html
En el cms debe estar cargada mal

**Comment by LeandroBraier** [comment]
Tenés razón, quedó tu PDF de prueba ahí. Gracias por avisar Fede!!

Repasé y nunca hubo un PDF de Ficha técnica que de ese producto @mkreyness Solo era un JPG. Usemos el que te paso aquí:

![2015_revividor_revear_fichatecnica_](https://cloud.githubusercontent.com/assets/6719872/16279016/846fdd10-388f-11e6-9ea8-441b3d177b46.jpg)

abrazo

**Comment by mkreyness** [comment]
Listo pero ojo que el icono (unico) que hay siempre dice PDF, no seria mejor guardar este JPG como PDF ? Asi como esta es raro lo que hace (lo guarda en vez de abrir).

**Comment by LeandroBraier** [comment]
Gracias MK!!

Si se pudiera hacer que se hiciera preview en lugar de descargar todos los PDF genial. Sino dejemoslo así por ahora.

abrazo

**Comment by mkreyness** [comment]
claro, es que tenia puesto a proposito el tag de "download", ahi se lo saque y le puse que lo abra en solapa nueva, fijate.

**Comment by LeandroBraier** [comment]
Perfecto MK!! Gracias!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
