### ISSUE TITLE
Párrafo a agregar en Bases y Condiciones de Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#329]
Puede ser mañana, todo bien. @FAAREIA

> TODOS LOS PARTICIPANTES AL ACCEDER A PARTICIPAR ACEPTAN LOS TERMINOS Y CONDICIONES QUE LA EMPRESA DECIDE. ASIMISMO LOS PARTICIPANTES CEDEN SUS DERECHOS DE IMAGEN PARA TODO TIPO DE PIEZAS GRAFICAS, FOTOS, VIDEOS Y/O CUALQUIER OTRO TIPO DE REGISTRO QUE LA MARCA REALICE PARA PROMOCIONAR LA CAMPAÑA POTENCIADOS, EN BUSCA DEL GRAN COLOCADOR

**Comment by FAAREIA** [comment]
en que parte lo agrego?

**Comment by LeandroBraier** [comment]
Abajo de todo en letra chiquita está perfecto.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!
