### ISSUE TITLE
Ajuste Home Web Parex Paraguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#330]
@FAAREIA tengo un pedido muy específico y simple para la Home de Paraguay. Necesito que subas el mismo destacado central de Klaukol Impermeable Potenciado que tenemos en la web de Argentina en la Web de Paraguay.

http://www.parexparaguay.com.py/

Puede ser para mañana tranquilo.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !
