### ISSUE TITLE
Backup Sitio Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#331]
@FAAREIA necesitaría un nuevo backup de la web de Revear. Puede ser para la semana que viene tranquilo. 

¿Me dirías un aproximado del peso del sitio? Es para ver cómo podemos alcanzarselo al cliente.

**Comment by FAAREIA** [comment]
El tema con esto es que hay que incluir archivos que estan linkeados desde el sitio anterior. Lo ideal para todos sería desvincularse completamente del sitio anterior, más limpio, más prolijo, menos problemas a futuro o ante un cambio, etc. Teniendo en cuenta que ya pasamos todos los colores, que queda para desvincular del sitio anterior?

Por otra parte me meti a ver un poco los archivos y habría algo que hay que fixear porque hay mucho contenido duplicado. @mkreyness 
Todos los productos y tendencias estan duplicados porque estan separadas por usuario-profesional y usuario-comun. Esto seguro traiga problemas con google, excepto que me digan que las tendencias con mismo título llevan imágenes o textos diferentes o que el mismo producto tenga imágenes o textos diferentes dependiendo del usuario.

**Comment by LeandroBraier** [comment]
Mmm, interesante ver estos temas. Hablemoslo antes de hacer el backup. Me parece bien y el backup no es urgente.

Si se pudiera no duplicar contenidos sería lo ideal por google. También me parece bien relevar qué contenidos quedan linkeados del sitio anterior y pasarlos al nuevo antes de hacer el backup.

**Comment by mkreyness** [comment]
El problema es que las paginas de productos (aunque parezcan iguales) si VIENE por la rama particular tiene los menues y links para seguir con cosas particulares, y si viene por la rama profesional, lo que corresponde a la profesional.
Entonces fisicamente no son iguales las paginas. El contenido interno de cada pagina NO esta duplicado (las fotos estan una sola vez, los colores/texturas una sola vez, etc.) Solo el HTML esta dos veces, dependiendo de distintas carpetas (/productos-particular, /productos-profesional o algo asi)

**Comment by LeandroBraier** [comment]
Entiendo. Entonces no veo problema. Solo nos queda emanciparnos del sitio viejo. Qué nos queda de ahí @mkreyness ?

**Comment by mkreyness** [comment]
Todo lo que era del sitio viejo de Revear esta aislado en una carpeta que se puede no-backupear y listo. No la borré por si acaso (ya vimos que fue necesario rescatar los PDF de ahi). En teoria no ya deberia necesitarse nada de ahi .
Pero Revear no es un sitio TOTALMENTE separado del de Parex. La base de datos es una sola, los programas usan recursos en comun, los procesos automaticos corren todos desde el mismo lugar.
No se bien exactamente que es lo que quieren tener como backup de Revear, pero no es algo que se pueda "copiar a otro server" y sacarlo andando, sin tener todo lo que es comun con Parex.

**Comment by LeandroBraier** [comment]
Mejor todavía MK. Hagamoslo como la otra vez. Los contenidos del sitio pero
que no puedan hacerlo andar solo con eso.

2016-06-24 14:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
El punto de quiebre son las busquedas, porque llaman a programas, si no tienen la base de datos ni los programas, no pueden funcionar. Todo lo demas es suficientemente estatico como para andar. 
Lo otro que no andaria es las llamadas ajax desde el calculador y la guia. La guia es totalmente dinamica, asi que no andaria nada en realidad.
@FAAREIA si lo vas a levantar entonces yo diria hacerlo con todo lo que depende de public_html/revear EXCEPTUANDO las carpetas  /cgi-bin y /viejos

**Comment by FAAREIA** [comment]
Ok, lo que migraría entonces es:
- ~~_beta~~
- ~~cgi-bin~~
- css
- ~~ex-js~~
- img
- inc
- js
- Mail
- media (Son los PDFs, lo que falta migrar y renombrar correctamente)
- novedades
- productos-para-particulares
- productos-para-profesionales
- tendencias
- ~~viejos~~

---

Cambiando de tema, tener el HTML duplicado es tener contenido duplicado. Hay dos opciones para mi:
1. Cuando entras a productos, ve que usuario sos y te muestra solo los que son para vos
2. Se mantiene el HTML duplicado y se pone un tag en una de las versiones diciendo que la otra version en la original. Desconozco como va a impactar en el posicionamiento tenerlo asi, tenes las visitas divididas al dope porque el contenido es el mismo.

**Comment by LeandroBraier** [comment]
En posicionamiento puede ser, pero en información nos sirve saber si los
que vieron son profesionales o usuarios finales. Si se puede mantener la
duplicación y agregar el tag que decís mejor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-06-24 17:17 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
los templates NO estan duplicados, por lo tanto el tag tendria que ser una variable y setearse por programa.  Es dedicarle un cierto tiempo.

**Comment by FAAREIA** [comment]
Ok, tengan en cuenta que esto hay que aplicarlo y luego ver como reacciona google con urls duplicadas para el posicionamiento. Tengo entendido que todo el tráfico de una va directo a la otra, que sería la original.

**Comment by mkreyness** [comment]
pero los urls son diferentes y el contenido es parcialmente diferente.

**Comment by FAAREIA** [comment]
Recién entre a 1 producto y su contenido es igual para uno u otro usuario. Ahora si van descripciones diferentes, pdfs diferentes, imágenes del slideshow distintas, podría safar pero no veo eso.

Contenido duplicado: https://support.google.com/webmasters/answer/66359?hl=en
Canonical urls: https://support.google.com/webmasters/answer/139066?hl=en

Con la solución de la canonical url, todo el posicionamiento de
http://www.revear.com.ar/productos-para-particulares/revividor-colores-revear.html
iria a
http://www.revear.com.ar/productos-para-profesionales/revividor-colores-revear.html
o viceversa

Lo raro, como todo lo que pide el cliente, es que al entrar a una de las 2, ya estaría siendo particular o profesional

**Comment by mkreyness** [comment]
LOS MENUES son todos diferentes, porque llevan a links diferentes. Hasta el link del menu principal lleva a OTRO menu principal.

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA más allá de la discusión SEO, que me llevo lo que pasaron y lo pienso y lo paso a otro ticket nuevo, cuando podemos tener listo el backup completo del sitio para enviar al cliente?

**Comment by mkreyness** [comment]
@FAAREIA lo levantas vos ?

**Comment by FAAREIA** [comment]
Si dale, reviso el ticket y lo hago. Va a ir sin base de datos obviamente

**Comment by FAAREIA** [comment]
http://revear.com.ar/revear.zip

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !!! abrazo grande
