### ISSUE TITLE
Trivia con Predicción de la Final del Domingo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#332]
@mkreyness tengo una nueva trivia para predecir la final del domingo, con el juego creado para que si aciertan les sumemos 200 puntos. Como era el proceso? Te aviso el lunes así les sumás esos puntos a los que acertaron?

Aparte te consulto: no sé por qué en este template desapareció el botón de compartir:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=56

**Comment by mkreyness** [comment]
Si dale, avisame el lunes quien gano el partido... Como vivo adentro de un tupper :)
El template que usa este juego (una trivia comun) no tiene previsto un boton de compartir, ademas que estaria compartiendo, si el juego es solo para usuarios ?
Los que tienen boton compartir son los videos o contenido embedded, que podrian funcionar fuera del sitio.

**Comment by LeandroBraier** [comment]
Antes lo tenía creo. No te preocupes, dejalo así nomás.

El lunes te digo quien ganó, esperoq ue con alegría.

abrazo

**Comment by LeandroBraier** [comment]
Lamentablemente perdimos, MK. Ya despubliqué el tema, pero deberías sumarle los 200 puntos a los que respondieron Chile en la pregunta 3.

abrazo

**Comment by mkreyness** [comment]
Lamentablemente para los vendedores, ninguno respondio Chile. De todos modos no hay pregunta 3, solo veo 1 y 2.

**Comment by LeandroBraier** [comment]
Si, tal cual. Mala mia. Se ve que estas trivias son yeta. Vamos a dejar de hacer trivias y ganamos. Solo nos falta eso ; )

abrazo
