### ISSUE TITLE
Pequeño cambio de imagen en producto Sitio Paraguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#334]
@FAAREIA necesito cambiar el thumb y la imagen de este producto del sitio de Paraguay.

Es Klaukol Impermeable Potenciado, que antes se llamaba Impermeable Fluido y lo cambié. El ID de producto es 85.

La imagen a colocar es esta:

![3d kl_impermeable_potenciado_25kg](https://cloud.githubusercontent.com/assets/6719872/16381262/0e866e86-3c52-11e6-96a7-b904d0def34d.jpg)

Me confirmás porfa cuando lo hayas podido hacer?

abrazo

**Comment by FAAREIA** [comment]
Esta corrompida la foto, ni la veo.
En el CMS se puede cargar la foto? Si es asi, pasame los accesos pls

**Comment by LeandroBraier** [comment]
Ese es el problema. Sino ni te molestaba. No lo puedo subir desde el CMS.

A ver ahora si la sube bien a la imagen:

![klaukol-impermeable-potenciado-25-kg](https://cloud.githubusercontent.com/assets/6719872/16383221/9b99d1c0-3c5a-11e6-8c0e-33ec29b008da.jpg)

![klaukol-impermeable-potenciado-25-kg](https://cloud.githubusercontent.com/assets/6719872/16383222/9e432502-3c5a-11e6-828e-d0768bb93681.png)

**Comment by LeandroBraier** [comment]
Algo estaba fallado en el archivo. Ya lo rexporté y lo resubí acá. Fijate porfa.

**Comment by FAAREIA** [comment]
Hecho.
Copio a @mkreyness que me di cuenta que el páginado/filtros de los productos no funciona. Otra vez duplika imagino y el problema de un server compartido

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!! Perfecto eso. Avisenme si les puedo ayudar en algo con eso, escribiendo a Duplika o algo.

(Ya les aviso que estoy organizando la migración paulatina de los sitios a un hosting propio)
