### ISSUE TITLE
Paginado de Productos en Sitio Parex

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#335]
Cito al gran @FAAREIA cuando dijo:

> Copio a @mkreyness que me di cuenta que el páginado/filtros de los productos no funciona. Otra vez duplika imagino y el problema de un server compartido

**Comment by mkreyness** [comment]
desde cuando pasa esto ?

**Comment by mkreyness** [comment]
A mi me anda, probe con Parex y Klaukol. Probe de filtrar, probe de paginar, me anduvo todo.
Lo que si veo que el producto Parex Atermico sale sin thumbnail y con los textos con los acentos mal, pero los otros parecen estar bien.
Me pueden dar un ejemplo de lo que anda mal para probar ?

**Comment by FAAREIA** [comment]
No fuí específico porque pensé que pasaba en los 3 dominios.
En AR funciona bien, PY y UY no.
Ej: http://www.parexparaguay.com.py/cgi-bin/listaproductosbase.pl?site=2&marca=1&pagina=2

**Comment by mkreyness** [comment]
estoy comparando todo entre AR y PY, ajuste algunas diferencias, pero igual da error. Voy a ver si se puede encontrar algo en un log en el CPanel y si no va a haber que consultar con Duplika

**Comment by mkreyness** [comment]
listo, ya encontre la madre del borrego, deberia haber quedado andando todo, peguenle una mirada

**Comment by FAAREIA** [comment]
Lo veo joya, revisé UY y PY

**Comment by LeandroBraier** [comment]
Muchas gracias muchachos! Me olvidé de agradecerles ayer. Abrazo
