### ISSUE TITLE
Quitar cartel de Bienvenida Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#336]
@mkreyness necesito quitar el pop up con el texto del cartel de bienvenida que aparece cada vez que entrás al Club de Colocadores.

Me avisás porfa?

abrazo

**Comment by mkreyness** [comment]
La bienvenida por suma de puntos del dia decis ? Pero el primer ingreso si lo dejo ?

**Comment by LeandroBraier** [comment]
El tema es que menciona los puntos y en el club no hay puntos.

Si dice puntos hay que sacarle esa parte o directamente el cartel.

**Comment by mkreyness** [comment]
Ok, saco el cartel del todo entonces. En un rato.

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias MK!!!
