### ISSUE TITLE
Newsletter Julio ParexKlaukol. 01/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#337]
Buen día @FAAREIA !

Te paso los contenidos para el news de Julio. Si llegás a maquetarlo hoy genial, dandole prioridad frente a FUCA y todo lo demás.

[NEWSLETTER JULIO 2016 FINAL.docx](https://github.com/LeandroBraier/Klaukol/files/343528/NEWSLETTER.JULIO.2016.FINAL.docx)

Sino, sería para el lunes a primera hora. Ya incluye imágenes, links y todo lo que necesitás.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-07/16-07.html
No lo pude probar pero la base está

**Comment by LeandroBraier** [comment]
Está perfecto Fede!

Solo me faltó pasarte los copetes de las 2 primeras notas. Aquí van:

**Hogares a leña para ambientes modernos**

Conocé en esta nota una serie de hogares a leña modernos, que brindarán calor a tu hogar sin descuidar diseño y en línea con las nuevas tendencias.

**Cómo hacer una chimenea paso a paso**

Nada más alegre en un hogar o casa de fin de semana, como una chimenea bien construida. Todo lo que necesitás aprender para construirla en esta nota.

Confirmame cuando estén arriba y estamos.

abrazo

**Comment by FAAREIA** [comment]
Hecho, fjate ahora

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Fede!! Muchísimas gracias!

abrazo

**Comment by FAAREIA** [comment]
Acordate que no esta listo para mandar, hay que pasar los estilos dentro de cada tag. Eso es un preview del mailing a enviar nomás, falta ese paso que te digo

**Comment by LeandroBraier** [comment]
Ah, ok. Porfa dejalo listo para que meta en Mailchimp porfa. Ya está aprobado.

**Comment by FAAREIA** [comment]
Hecho, ahi le puse todos los estilos inline.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede! Abrazo y buen finde
