### ISSUE TITLE
Consulta: backupear y dar de baja viejo sitio Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#338]
Buen lunes @mkreyness !

Qué posibilidad tenemos de backupear y dar de baja el viejo sitio Revear.

Para que no sigan posicionados en Google algunos links de la web vieja que ya no se ven, como este: 
http://www.revear.com.ar/novedades/revividor-colores-revear/

**Comment by mkreyness** [comment]
en realidad eso es un engendro, porque usamos el mismo nombre (novedades) para guardar las nuevas y ahi estaban las viejas, que no se quitaron. 
Por lo tanto esto YA ESTA en el backup que levanto Fede. 
Esas cosas (que son pocas, solo dentro de "novedades"), si te parece bien, las borro a mano ya.

**Comment by LeandroBraier** [comment]
Perfecto. Ahí chequeé y están en el backup de Fede tal cual.

Borralas a mano nomás. Gracias!

**Comment by mkreyness** [comment]
y en realidad toda esa carpeta "novedades" esta mal, porque la correcta es "tendencias", que esta abierta por tipo de usuario.
La elimino y listo.

**Comment by LeandroBraier** [comment]
Genial! Avisame cuando esté eliminada porfa. abrazo

**Comment by mkreyness** [comment]
ya la eliminé cuando dije "la elimino y listo".

**Comment by LeandroBraier** [comment]
jaja perfecto gracias!
