### ISSUE TITLE
Pequeño ajuste de texto en Página LEED / ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#339]
@FAAREIA en esta página:

http://www.parexklaukol.com.ar/certificacion-leed.html

necesito que cambies dentro del cuadro de productos, donde dice "Klaukol Pastina Renovación" por "Klaukol Pastina Piezas Normales Fluida"

<img width="757" alt="captura de pantalla 2016-07-04 a las 12 14 13 p m" src="https://cloud.githubusercontent.com/assets/6719872/16564358/6f0b6d7a-41dd-11e6-8a68-ebd66327e701.png">

Solo eso. Puede ser para mañana.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/certificacion-leed.html

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! abrazo
