### ISSUE TITLE
Bug Productos Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#340]
@mkreyness fijate lo que pasa cuando hacés clic en "Línea Premium" o "Revestimientos texturados" de esta parte de la página de producto:

<img width="384" alt="captura de pantalla 2016-07-12 a las 9 40 52 a m" src="https://cloud.githubusercontent.com/assets/6719872/16766582/5c6cc94a-4811-11e6-86cf-5395bae0d7f3.png">

Te lleva a una lista .pl donde los productos dan error. Por favor resolvamos esto cuanto antes.

abrazo

**Comment by mkreyness** [comment]
a mi no me da ningun error, habra sido alguna de las gracias de Duplika, que se habra arreglado sola.

**Comment by mkreyness** [comment]
AHHH cuando haces click en los productos que vienen en la lista, ok, ya entendi. Ahora veo.

**Comment by mkreyness** [comment]
listo.

**Comment by LeandroBraier** [comment]
Gracias Mk!
