### ISSUE TITLE
Metadata Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#341]
@FAAREIA los datos que están saliendo en google para la nueva web son cualquiera. 

Me pasás que necesitás así te lo paso redactado?

<img width="675" alt="captura de pantalla 2016-07-12 a las 12 43 10 p m" src="https://cloud.githubusercontent.com/assets/6719872/16772505/ee7d71c2-482a-11e6-9e92-c46c69f7ef67.png">

Es metadescripcion y qué más?

**Comment by FAAREIA** [comment]
Estuve buscando y no pude encontrarlo pero falta TODO el SEO del sitio.
Sería:
- Todos los meta description
- Todos las imagenes de 1200x630 para facebook. De cada productos y secciones en todas sus variables.

**Comment by FAAREIA** [comment]
Hay que definir también que URL va a ser el oficial en google, si el producto profesional o el particular, asi se define el canonical.

**Comment by LeandroBraier** [comment]
Que la oficial de GOogle sea la particular, eso ya te lo defino. En cuanto a metadescription cuánto caracteres máximo?

Las fotos te las armo.

abrazo

**Comment by FAAREIA** [comment]
La metra descripción es el texto detalle que te muetra google debajo del link a la página. Se dice que con 160 caracteres te entra bien sin que te lo corte el buscador con un "..."
También he leido que aunque te lo corte, igual sirve para la indexación lo que no llega a leerse.

**Comment by LeandroBraier** [comment]
Perfecto, gracias Fede!! Intento pasartelo en breve.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-07-14 12:22 GMT-03:00 Federico Arena notifications@github.com:
