### ISSUE TITLE
Nueva dinámica de Subir Foto en Vendedores Parex

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#342]
@mkreyness necesito que crees una nueva dinámica de estas (ya hiciste un par, por ejemplo para fin de año: 

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=27

usuario=LeandroBraier
clave=parex

Necesito una nueva para mañana que sirva para el Día del Amigo. Me confirmás si llegás porfa?

abrazo

**Comment by mkreyness** [comment]
No hace falta desarrollar nada, ponele al juego tipo "UPLOAD", con eso ya funciona.
