### ISSUE TITLE
Newsletter Agosto ParexKlaukol. 05/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#343]
Buen día @FAAREIA !

Te paso los contenidos para el news de Agosto. Confirmame si llegás para mañana al mediodía o a la tarde ponele.

[Contenido Newsletter ParexKlaukol AGOSTO Corregida 25-7 con links.docx](https://github.com/LeandroBraier/Klaukol/files/387396/Contenido.Newsletter.ParexKlaukol.AGOSTO.Corregida.25-7.con.links.docx)

[Imagenes Newsletter AGOSTO.zip](https://github.com/LeandroBraier/Klaukol/files/387398/Imagenes.Newsletter.AGOSTO.zip)

Ya incluyo imágenes, links y todo lo que necesitás.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-08/16-08.html
Estaba muy organizado, me llevó menos tiempo.
Chequealo todo, los links no anda ninguno y faltan fechas de últimas novedades. El texto de rubi lo achiqué porque no entraba.
Acordate que esta versión no es enviable.

**Comment by LeandroBraier** [comment]
Muy bueno Fede!!

1) A las fechas que no tenés ponele 01/08

2) En la encuesta, la palabra "razón" le falta el tilde.

Los links no están publicados pero andan no te preocupes. Corregime esto porfa y lo mando a a aprobar. Gracias!

**Comment by FAAREIA** [comment]
Ahi esta listo.
En la encuesta se pueden elegir varias opciones, no solo 1. Le puse asi porque imagino que puede haber varias causas por las que elegirian un porcellanato

**Comment by LeandroBraier** [comment]
Genial Fede!

**Comment by LeandroBraier** [comment]
@FAAREIA como va? Me pidieron los siguientes cambios en el news y ya salimos. El doc corregido es este:

[Contenido Newsletter ParexKlaukol AGOSTO Corregida 4-08 con links A MAQUETAR.docx](https://github.com/LeandroBraier/Klaukol/files/402135/Contenido.Newsletter.ParexKlaukol.AGOSTO.Corregida.4-08.con.links.A.MAQUETAR.docx)

Te detallo los ajustes para mayor claridad:

**1-** Hay que agregar lo de la competencia de Colocadores. Ya lo tenías armado en la versión de Junio, solo cambian los textos.

http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-06/16-06.html   

**2-** En producto del mes, agregamos un segundo producto al lado del Grandes Piezas que es de Rubi. el TILE LEVEL. 
Debajo tenemos que poner que lanzamos un 20% de descuento solo en Tile Level de Rubí presentando el número de socio del Club de Colocadores Klaukol.

**3-** Los logos de los clubes y la guia de corralones irían al pie, no como segmentos debajo. Quitemos esos dos.

**Comment by LeandroBraier** [comment]
@FAAREIA podrás mandarme esto hoy? Es lo único prioridad para hoy. Lo demás queda ya para la semana que viene, no hay problema.

**Comment by LeandroBraier** [comment]
@FAAREIA te paso la imagen lista para el news. Decime si queda bien o si te parece necesario hacerle algo más. Tengo al equipo de diseño a full y lo resolví yo, pero quizá se puede mejorar.

![2016-08-final](https://cloud.githubusercontent.com/assets/6719872/17516105/d40a0226-5e12-11e6-8d80-fbe6444dfa7b.png)

**Comment by FAAREIA** [comment]
Fijate ahi Lea:
www.parexklaukol.com.ar/_mailing/parexklaukol/16-08/16-08.html

**Comment by LeandroBraier** [comment]
Muchas gracias Fede! Te pido 2 ajustecitos nomás:

1) Cambiar textos de parte de Potenciados:

Arranca “Klaukol en busca del Colocador Klaukol”
Klaukol comienza en Agosto el primer desafío nacional de colocadores en la que todos ganan: colocadores, vendedores y puntos de venta. ¿El premio? Un viaje a Barcelona para ver jugar al nº1 del mundo. Enterate más en www.klaukoltebusca.com.ar

2) Falte el tilde a la palabra "razón" en la pregunta de la encuesta

3) Quitar este recuadro rojo porfa:

<img width="614" alt="captura de pantalla 2016-08-09 a las 3 38 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/17527953/c174f9aa-5e43-11e6-8693-453e8f01153c.png">

Lo demás perfecto. Porfa confirmame cuando esté, le doy F5 y lo mando nomás.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo. Probalo todo igual por las dudas

**Comment by LeandroBraier** [comment]
@FAAREIA ahi repasé los links. Algunos no funcionaban por temas del cms que ya solucioné. 

Pero hay dos que tienen el link mal puesto, o por error del word o temas tecnicos de la url que me hicieron que tenga que cambiarla:

¿Qué se espera para el segundo semestre y qué planifican las empresas?

http://www.parexklaukol.com.ar/novedades/¿que-se-espera-para-el-segundo-semestre-y-que-planifican-las-empresas-.html

4° Encuentro Tendiez 2016 en la ciudad de Córdoba: "Experiencias de desarrolladores, arquitectos e interioristas"

http://www.parexklaukol.com.ar/novedades/4to-encuentro-tendiez-2016-cordoba.html

Solo eso.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi lea
Abrazo

**Comment by LeandroBraier** [comment]
Fede querido, me quiero matar. El primer link sigue sin funcionar y ahora tampoco en la página. Es algo del CMS que no entiendo.

Acá lo corregí y me aseguré de que ahora funcione bien. 

http://www.parexklaukol.com.ar/novedades/que-se-espera-para-el-segundo-semestre.html

Porfa actualizalo y con eso ya estamos. Ya lo mandé igualmente.

abrazo y muchísimas gracias por la paciencia!

**Comment by FAAREIA** [comment]
Fijate ahora, seguro era el caracter "¿" el que jodia

**Comment by LeandroBraier** [comment]
Impecable Fede!!! Muchísimas muchísimas gracias!!! Ya quedó joya.

abrazo grande

**Comment by LeandroBraier** [comment]
@FAAREIA consulto por las dudas. Ya está listo para copiar el código fuente y usar en Mailchimp no?

**Comment by FAAREIA** [comment]
Si todo listo

**Comment by LeandroBraier** [comment]
@FAAREIA pequeños ajustes y ya queda:

1) Cambiar texto de "Arranca “Klaukol en busca del Colocador Klaukol”
por el siguiente:
**Klaukol comienza en Agosto el primer desafío nacional de colocadores. ¿El premio? Un viaje a Barcelona para ver jugar al nº1 del mundo. Enterate más en www.klaukoltebusca.com.ar**

2) Cambiar la Cortadora XN y reemplazar por el Tile Level. A la imagen del Tile Level quitarle la caja. Que queden solo los 3 elementos con los signos +:

<img width="132" alt="captura de pantalla 2016-08-12 a las 12 31 22 p m" src="https://cloud.githubusercontent.com/assets/6719872/17626778/139c5c94-6085-11e6-900d-8bd2fe6d4ee6.png">

3) Agregar una nota más debajo de Porcellato, bajo el rótulo de "Eventos" (igual estética queel "Tendencias" de arriba pero en azul). 
La nota dice: 
Título: Se viene el Forum Construya Mar del Plata!
El 8/09 sumate a un escenario de actualización y networking para todos los protagonistas de la cadena de valor de la construcción.
Link: http://www.parexklaukol.com.ar/novedades/forum-construya-mar-de-plata-2016.html
Imagen dentro del círculo, una de estas dos (la que quede mejor):

<img width="361" alt="captura de pantalla 2016-08-12 a las 12 28 41 p m" src="https://cloud.githubusercontent.com/assets/6719872/17626887/9828c72c-6085-11e6-945b-06dd1587d427.png">
<img width="200" alt="captura de pantalla 2016-08-12 a las 12 28 30 p m" src="https://cloud.githubusercontent.com/assets/6719872/17626888/982a8440-6085-11e6-9894-a28c36b37bd8.png">

4) Dentro de últimas novedades, cambiar la fecha de Forum Construya Mar del Plata a 08-09

5) Cambiar la encuesta a:

“Se viene el Forum Construya en Mar del Plata. ¿Vos ya participaste de alguno?

Si

No, pero me gustaría.

Me gustaría saber qué es.

Esto puede ser para hoy a última hora, total lo mando el martes a primera hora.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahora lea:

http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-08/16-08.html
Probalo todo
Abrazo

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Revisé todos los links:

Las últimas novedades tienen 3 ajustes:

1- El link está mal. Debe ser este: http://www.parexklaukol.com.ar/novedades/que-se-espera-para-el-segundo-semestre.html

2- Cambiar Fecha de Casa FOA a 09-09

3- El link de Tendiez no anda. Lo ajusté, usá este:

http://www.parexklaukol.com.ar/novedades/4to-encuentro-tendiez-2016-cordoba.html

Con eso envío. Gracias!

abrazo

**Comment by FAAREIA** [comment]
Fijate ahora lea.
Abrazo
