### ISSUE TITLE
Pequeños ajustes en Web ParexKlaukol 03/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#345]
@FAAREIA te paso para mediados de la semana que viene una serie de cambios sencillos en la página web de ParexKlaukol, una vez que termines las maquetaciones del sistema. 

De esto como siempre mandame propuesta de diseño primero y una vez aprobado lo maquetamos.

1) Quieren que los telefonos de contacto figuren en la home. 
Seria bueno alguna leyenda que diga "LLAMANOS PARA ASISTENCIA EN OBRA" y poner alli el 08002225528 y también con la frase Orientacion Klaukol relacionada. Quieren que diga las dos frases arriba del teléfono, fijate cómo podés hacer que quede bien.

Quieren que esto esté dentro de este área:

![pedido laura 1](https://cloud.githubusercontent.com/assets/6719872/17265953/ac7946d2-55c9-11e6-908a-8a8c7072fa50.JPG)

2) Piden sumar como en la web de Revear un "ENCONTRANOS EN" resumido al pie de la home 

![pedido laura 2](https://cloud.githubusercontent.com/assets/6719872/17265961/b7cba61a-55c9-11e6-8c58-6c50a6d42355.JPG)

3) Hay que cambiar el teléfono que figura acá en contacto por el 5167-9999

![pedido laura 3](https://cloud.githubusercontent.com/assets/6719872/17265966/bd6c029a-55c9-11e6-8e91-468460c3fc2d.JPG)

4) Muy pequeño detalle: fijate que el thumbnail de la lista de productos de Parex Atérmico no se ve. Revisás qué pasó porfa?

<img width="841" alt="captura de pantalla 2016-08-01 a las 12 56 39 p m" src="https://cloud.githubusercontent.com/assets/6719872/17299242/eba5b73e-57e3-11e6-94c5-08a18cddf258.png">

Cualquier duda avisame.

abrazo

**Comment by FAAREIA** [comment]
2 - Hecho
3 - Hecho
4 - No hay foto asignada ahi, falta que le asignen la que estaba antes desde el CMS

1 - Ahi va el diseño, entiendo que quieren las frases arriba del número pero el diseño llevo para otro lado, sino iba a ocupar más alto. Siempre es mejor que el cliente no prediseñe en su cabeza las cosas ^^
![demo](https://cloud.githubusercontent.com/assets/6184969/17815546/234ae562-660b-11e6-8124-76dc1e374bb0.jpg)

**Comment by LeandroBraier** [comment]
Gracias Fede!!!

1) Arriba debería decir ORIENTACIÓN KLAUKOL solo, sin la palabra "relacionada", que era de mi explicaición nomás.

2) Falta el "Encontranos en:"

3) Perfecto.

4) Quién hace eso? No entiendo. Si es desde el CMS, como es la ruta?

**Comment by FAAREIA** [comment]
2 - Si le pongo un título, tengo que ponerle título a los links de las otras 3 columna. Decime bien como serían los títulos en tal caso.

4 - Copia a marce @mkreyness que creo que el lo tiene linkeado de alguna forma en la base de datos.

1 - Ahi va sin esa palabra:
![demo](https://cloud.githubusercontent.com/assets/6184969/17818296/4be5882a-6619-11e6-9f55-6bdbfd6f6816.jpg)

**Comment by LeandroBraier** [comment]
Gracias!

2- Dejalo así nomás. Subilo a producción tranquilo.

4- Espero a MK

1- Está perfecto así. Solo cambialo a que diga ORIENTACIÓN PAREXKLAUKOL (me
acabo de dar cuenta de este detalle perdón) y subilo a producción nomás.

2016-08-19 14:29 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo va? Avisame cuando 1, 2 y 3 estén arriba. 

4) @mkreyness cómo va? Avisame si tenés la ruta de dicho archivo yo lo subo al CMS, porque el CMS no me permite subirlo yo como archivo. Si querés te paso el archivo yo y lo volvés a subir, para no tener que buscarlo. Avisame nomás.

abrazo

**Comment by FAAREIA** [comment]
Hecho, ya esta todo subido.

**Comment by mkreyness** [comment]
En la parte de productos donde decia "Thumb" de ese producto "parex atermico" estaba en blanco. Le copie lo que decia el campo de al lado (el de la imagen full, que igual era un thumb parece), y listo. Espera unos minutos a que las paginas se regeneren o miralo con el buscador de producto (hay que ponerlo sin acento) que es dinamico y ya te lo muestra.

**Comment by LeandroBraier** [comment]
Excelente quedó MK!!! Muchas gracias!!!

**Comment by LeandroBraier** [comment]
Muchas gracias a los dos!!! Los quiero jejej abrazo
