### ISSUE TITLE
Programación Sistema En busca del colocador Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#346]
@mkreyness y @valentinsabbath ya tenemos la primer maquetación para empezar a armar el sistema:

**1-** Login de registración

http://benteveo.tv/klaukol-colocador-busca-evento/registrarse.html

**2-** Login con número y testeo de DNI

**3-** 3 tipos de trivias maquetadas, agregando el timer

**4-** Ranking de Top 30 de usuarios, con scroll automático o manual, a elección

http://benteveo.tv/klaukol-colocador-busca-evento/jugadores.html

**5-** Muestrario de distintos videos de KLaukol con timer gigante en la pantalla grande

http://benteveo.tv/klaukol-colocador-busca-evento/contador.html

**6-** Pantalla fija que dice “3, 2, 1 manos a la llana!” que aparece en toda la pantalla cuando el timer llegue a CERO.

http://benteveo.tv/klaukol-colocador-busca-evento/empieza.html

**7-** Muestrario de videos a pantalla completa con el logo de En busca del Colocador Klaukol, sin timer

**8-** Pantalla fija donde solo se ve el logo de En busca del Colocador Klaukol

Confirmenme si recibieron por favor. 

Más allá de esto, necesito que me confirmen si pueden hacer reunión para el lunes a las 10 am para testear el sistema en la agencia. En caso de que alguno no pueda, la alternativa son las 4 pm.

Espero confirmación entonces.

abrazo

**Comment by mkreyness** [comment]
Recibido. Esto es 99.99% tema mio, lo que tiene que hacer Valentin es armar todo el hardware e instalarle a cada raspi lo que necesita para funcionar. 
Para llegar a tener todo para el lunes a las 10, necesito que todos los materiales esten listos mañana mismo.
A que te referis con "en la agencia" ? A "en la productora" ?

**Comment by LeandroBraier** [comment]
jaja Perfecto! Perdón, ahora le decimos la agencia jeje. Fede me dijo que mañana tiene el resto de la maquetación, no te preocupes. abrazo

**Comment by mkreyness** [comment]
@valentinsabbath necesito el server prendido y conectado todo el tiempo, mira que yo trabajo en horarios raros.

**Comment by mkreyness** [comment]
@LeandroBraier veo dos cosas en la maqueta esta: 
- el texto "con el apoyo de Rubi" se pisa con el boton "Registrar Usuario", no se si ustedes lo ven tambien.
- pregunta: ciudades veo que es un desplegable, le cargo la base de datos de ciudades por provincia que tenemos ya en algun lado ? (creo que VIETUR)

**Comment by ghost** [comment]
Dale Marcelo lo hago a la noche que ahora no estoy en casa

**Comment by mkreyness** [comment]
Y despues no me lo apagues !

**Comment by LeandroBraier** [comment]
@mkreyness está ya maquetado para 1080 Full HD. Si lo ponés en pantalla completa lo vas a ver joya.

**Comment by mkreyness** [comment]
pero la registracion se va a hacer en full HD ? Los monitores dan esa resolucion ?

**Comment by LeandroBraier** [comment]
Es una notebook que usa la persona de que los registra. La ponemos a pantalla completa y listo.

**Comment by mkreyness** [comment]
Y lo de las ciudades ? Uso lo de VIETUR ? O tendria mas sentido tener mas ciudades cercanas a la zona en que se va a hacer cada evento ? Siempre la idea es minimizar el tiempo de registracion.

**Comment by LeandroBraier** [comment]
Usemos lo de VIE TUR mejor. Incluye todas las ciudades más importantes del
país. Si es alguna que no está se puede hacer que esa ciudad la completen a
mano?

**Comment by mkreyness** [comment]
Si obvio no es obligatorio elegir.

**Comment by mkreyness** [comment]
la registracion ya quedo andando, con lo de las ciudades y todo.
Lastima que no puedas hacer andar el NeoRouter, @LeandroBraier 
Aca estaria la pagina:
http://10.0.0.23/klaukol-colocador-busca-evento/registrarse.html

**Comment by LeandroBraier** [comment]
@mkreyness Fede me paso unas maquetaciones más, que te las sumé arriba en el listado, pero no tiene todavía las maquetaciones 2 y 3 que son entiendo las que más necesitás. 

Ahi le insistí si puede redoblar esfuerzos para tenerlas para hoy, pero si las tenemos mañana nos complica mucho?

**Comment by mkreyness** [comment]
Hago lo que se pueda ir haciendo, lo importante es que no se corte...

**Comment by LeandroBraier** [comment]
jajajja Así es, no se cortará jamás jeje Gracias MK!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@valentinsabbath vos también me confirmás reunión para el lunes a las 10 am? Así ya agendo.

**Comment by ghost** [comment]
Confirmado!

**Comment by LeandroBraier** [comment]
Gracias Valen! Ya mandé el evento por google!

**Comment by FAAREIA** [comment]
Recuerden que el diseño esta basado para una resolución full screen de 1920x1080. Cuando no se respete la resolución, lo que va a joder no es el ancho sino el alto ya que la idea es que no haya scroll.
Más allá de eso, en un caso de urgencia puede achicarse todo con el zoom del navegador o sino achicando el valor por defecto de la fuente del navegador, la cual es 16px de base.

**Comment by mkreyness** [comment]
@LeandroBraier la numeracion de los items donde esta la lista de maquetas quedo rara, hay como 5 cosas llamadas "1", por favor cuando puedas corregilo como deba ser porque quedo confuso.

**Comment by mkreyness** [comment]
Dudas: lo de "top 30", en cada pagina entran 8, se supone que tendriamos que ciclar automaticamente de una pagina a otra de las 4 para que todos se vean ? Porque no se si no quien va a "tocar los botones" si esto es algo en exhibicion autonoma. 
Ademas como no se esta mostrando el numero de PUESTO EN EL RANKING, puede ser muy confuso (alguien puede aparecer al tope de la 4ta pagina y creer que esta primero).

**Comment by mkreyness** [comment]
Respecto de la pagina con contador que tiene que mostrar un conjunto de videos, esos videos supongo que los tendriamos que tener en forma local, puesto que no va a haber conexion a internet. Los tenes para pasarmelos ? O alguno de ejemplo aunque sea ? La idea es que corran en continuado uno tras otro siempre en el mismo orden ? En ese caso podria ser un unico video ? O @FAAREIA  vos tenes algo para poner tipo carrousel pero que avance recien cuando el video termina ?

**Comment by LeandroBraier** [comment]
Corregido lo de la puntuación MK!

TOP 30: Gracias por existir MK. No me había dado cuenta. Es crucial @FAAREIA que el top 30 tenga el número de puesto de cada uno además del puntaje. Yo pensé que eso iba en los espacio vacíos que quedaban en el medio, pero si no está hay que agregarlo porfa.

VIDEO EN PÁGINA CON CONTADOR: Tal cual, vamos a subir el video de forma local y va a ser uno largo con todos los videos pegados dentro. Despues tendría que estar loopeado para empezar de vuelta.

**Comment by mkreyness** [comment]
El puntaje tampoco esta, definamos bien entonces que columnas van y en que orden, yo propongo:
- PUESTO
- PUNTAJE
- NOMBRE Y APELLIDO
- CORRALON

y no pondria el numero de participante, total con ver su nombre y el corralon en que trabaja es suficiente.

**Comment by mkreyness** [comment]
Salvo esos detalles, yo estoy al dia con todo lo que podia hacer, necesito con urgencia la maquetacion de cuestionarios para trabajar en eso en el fin de semana.

**Comment by LeandroBraier** [comment]
Gracias MK! Ahi le pasé en limpio los pedidos a Fede y le pregunté como venimos con el resto.

**Comment by LeandroBraier** [comment]
@mkreyness para video de muestra (basta un botón) para la pantalla del countdown te paso este video:

ssyoutube.com/watch?v=1dj_4YI4MN4

La semana que viene recién vamos a tener el reel completo con todos los videos, por eso prefiero mandarte un videito solo corto para no demorar tiempos en el servidor y demás.

Si se te llega a caer el Neorouter el fin de semana y Valen no lo puede arreglar avisame y vemos qué podemos hacer. Como vos bien decís: lo importante es que no se corte.

abrazo

**Comment by mkreyness** [comment]
pero no tenes el .mp4 ? Youtube no me sirve.

**Comment by LeandroBraier** [comment]
Mirá el link. Te permite descargar el MP4 de ahi directamente. EN la resolucion que quieras (magia!)

**Comment by mkreyness** [comment]
ahhh, y yo que creia que el "ss" era un error de tipeo. Ok.

**Comment by LeandroBraier** [comment]
jajaja magia de viernes

**Comment by ghost** [comment]
Buenas! 
En registración ahora me doy cuenta, es pantalla táctil, sin teclado.
Estaría bueno que el maqueteado tenga un pad numérico.
No conviene poner el teclado en pantalla porque es horrible, tapa parte de la pantalla  y solo se va a usar en la registracion

**Comment by mkreyness** [comment]
A mi me dijeron que era una notebook para registracion.

**Comment by ghost** [comment]
Perdón, aca:
http://10.0.0.23/klk2/login-01.html

**Comment by mkreyness** [comment]
Tenes razon, pero no uses esos links "klk". Son backups parciales que hago cada vez que Fede me manda una nueva version.

El oficial es siempre este path:
http://10.0.0.23/klaukol-colocador-busca-evento/login-01.html

**Comment by ghost** [comment]
quise registar un usuario y me dio "internal server error"

**Comment by ghost** [comment]
desde aca 
http://10.0.0.23/klaukol-colocador-busca-evento/registrarse.html

**Comment by LeandroBraier** [comment]
Tenes razón Valen habria que agregar el pad. Yo estaba pensando que habia
teclado en pantalla pero no es una tablet, es una pantalla tactil como vos
decis.

**Comment by mkreyness** [comment]
ya solucione lo que daba el internal. El campo nuevo de numero de participante no tenia nombre en la maqueta nueva. Gracias.

**Comment by mkreyness** [comment]
Anoto aca cosas que tengo que solucionar yo, antes de que me las olvide. Por favor agregar @LeandroBraier si tenes algo mas:
- en el tema que habia dos preguntas siempre volvia a preguntar la misma en vez de pasar a la segunda
- en el tema corregir para que al terminar vuelva al login
- guardar en la base de datos info general del evento (provincia - localidad para poner de default) SI, OK.
- incluir base de corralones para autocomplete (que correspondan a la provincia default ?) SI, OK.
- implementar manejo de pad numerico (0-9 + borrar)
- implementar un timer por cada pregunta (40 segundos dijimos ?) SI, TAL CUAL.
- implementar logica de timeout que marque la pregunta con 0 puntos pero ya respondida y pase a la siguiente.
- implementar logica de botones para saltear pregunta y cambiar de participante
- separar logica de cuestionarios en dos tipos de temas: los especificos y el general (que seria uno solo):
  - el especifico va a venir indicado por URL segun el totem que sea y sigue el orden secuencial de las preguntas del tema
  - el general tambien va a venir por URL pero elige preguntas random y no permite contestar mas de 10 de ellas.
- agregar seteo de hora de corte del sistema: no solo para el 3, 2 y 1 sino para que corte en todas las terminales.
- el router se conecta por ethrrnet con una notebook que controla el display de los videos
- las url tienen que ser únicas para cada tema y cada raspi muestra un solo tema salvo las 2 generales.
- pensar sistema de las raspis generales para que el usuario pueda entrar varias veces: una pregunta por turno cada 5 minutos por usuario y hasta un total de 10 preguntas.

**Comment by LeandroBraier** [comment]
Excelente MK! Al final ayer a la tarde no te vi en Skype y no pudimos repasar. Con fede ya repasamos. Acá te sumé en tu lista lo que me pareció que te faltaba y te confirmé lo que me consultabas. Avisame si está todo ahora sí.

abrazo

**Comment by mkreyness** [comment]
Que raro, estuve conectado al skype del iPhone de 4:30 a 5:30 aprox y pense que capaz te engancharon en otra reunion y vos no pudiste.
Bueno yo ya estuve trabajando anoche con el cambio de logica, y para el resto de cosas dependo mucho de las maquetas modificadas. Ya vi lo que agregaste en la lista, perfecto.

**Comment by LeandroBraier** [comment]
A esa hora nos conectamos, qué lástima. Yo te veía como desconectado. Salvo que tenga otro usuario. Pasame tu usuario por las dudas. 

Perfecto entonces, avanzá todo lo que puedas. Me dijo Fede que hoy si o si te entrega las cosas rápidas, es decir, casi todo, salvo el panel de control o el ranking. Todo lo que es para las raspis lo entrega seguro.

abrazo

**Comment by mkreyness** [comment]
Mi usuario de skype es mkreyness. A mi me figura que estoy online, fijate si me ves (igual ahora estoy por salir en 5 min asi que se me va a desconectar del wifi)

**Comment by LeandroBraier** [comment]
Perdón MK. No te pude responder antes. Como viene todo? Como viste la maquetación de Fede?

**Comment by mkreyness** [comment]
ya aplique todo lo que me pasó Fede, lo unico que me queda pendiente es tomar el "area code" y pegarselo al celular por delante, salvo que sea necesario guardarlo por separado ?

Esta noche (que supongo que no va a haber nuevas maquetas todavia) voy a trabajar con:
- datos generales del evento (provincia y localidad default)
- autocomplete de corralones de la provincia vigente
- aplicar hora de corte para que ya no se puedan loggear

para lo del timer por pregunta voy a esperar a que este la maqueta de las preguntas, porque va a variar bastante con lo del boton.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!! @FAAREIA está a pleno solo con esto y dando prioridad a lo que es para las raspis así que lo vas a tener en breve.

abrazo y gracias!

**Comment by mkreyness** [comment]
que opinas de lo del area code, la guardo por separado o lo pego todo junto ?

**Comment by LeandroBraier** [comment]
Pegalo todo junto nomas. Es mas facil guardarlo después.

**Comment by mkreyness** [comment]
Ya esta andando todo eso que dije, pero tengo un pedido para @FAAREIA : como ahora despues de contestar la pregunta general te saca automaticamente al login, no hay oportunidad de mostrarle los puntos (en realidad siempre paso eso al responder la ultima pregunta). Habria que agregar el cartel redondo de los puntos en la pantalla de login como un div oculto para poder mostrarle eventualmente ahi al tipo los puntos acumulados cuando lo echo.

**Comment by LeandroBraier** [comment]
Perfecto MK! Consulta: ese cartel de puntos sumados le dice también si
respondió correctamente o no, verdad?

2016-08-10 10:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
claro, muestra el acumulado, no depende de la ultima respuesta

**Comment by LeandroBraier** [comment]
A lo que voy es, en terminos de usabilidad, no conviene decir si fue
correcta o incorrecta? Es mucho lio agregad ponele solo es palabra?

**Comment by mkreyness** [comment]
Que pondriamos en caso de que este mal ? "INCORRECTO, seguis teniendo xxx puntos" ?
Y si esta bien "CORRECTO, ahora tenes xxx puntos" ?

**Comment by LeandroBraier** [comment]
Si, me parece bien así Marce. Es bien claro para los participantes.

¿Se puede hacer sobre el pop up actual o le pido a Fede la remaquetación de
eso?

**Comment by mkreyness** [comment]
Lo puedo manejar yo, dejalo que termine el resto de cosas.

**Comment by mkreyness** [comment]
Pero lo que si necesito es asegurarme que ese popup funcione bien en la pagina de login, porque se va a terminar siempre mostrando ahi despues de CADA pregunta general, y de terminar la tira de preguntas de un tema especifico.

**Comment by LeandroBraier** [comment]
Dale, genial. Genio MK!!!!

**Comment by LeandroBraier** [comment]
Ok, esperamos respuesta de @FAAREIA respecto del pop up en la página de login.

**Comment by LeandroBraier** [comment]
@mkreyness salió todo muy bien en el evento!! La verdad que el sistema funcionó excelente. Solo surgen algunos ajustecitos a optimizar para el próximo evento será en 3 semanas pero estos cambios pueden estar para el jueves que viene, todo bien.

1) Que en el DNI se puedan ingresar 7 cifras, no solo 8 (tuvimos un problema con 1 participante quizá un poco viejo)

2) La registración al presionar el botón demoraba 10 segundos (20 segundos en nuestros testings en la agencia). Esto no variaba con ethernet o por rooter, así que habría que optimizar el procesamiento de esa info porque fue algo medio crítico que nos hizo poner 4 máquinas a inscribir (incluido Marcelo S, fue muy gracioso) más yo con el celu y aún así no dabamos a vasto (hubo 215 inscriptos!!!)

3) Se le puede agregar sonido a los countdowns? Si yo te doy un track que dure 15 minutos por ejemplo para el countdown del juego 1 y 2 se le puede poner? (no te digo para el countdown de varias horas porque sería imposible)

4) Notamos que el sistema se podía utilizar solo con Chrome. Con Safari no, por ejemplo. Se puede optimizar esto también? 

5) Necesitaría Linkear en la página "logo" el ranking de listado también, como "Ranking 2" aunque quede en 2 líneas.

6) Al exportar las bases no me guarda el dato de localidad en absoluto (recuerdo que cargamos el dato de muchas ciudades y no se exportaron. Solo las provincias.

Por ahora solo eso y con tiempo, para la semana que viene tranqui.

Cuando enchufemos el servidor mañana te confirmo.

abrazo

**Comment by mkreyness** [comment]
1) yo no estoy haciendo ninguna validacion de la cantidad de digitos, capaz hay alguna mascara por CSS que obligue a ingresar 8 ? Pero eso con agregar un 0 delante al tipear se salva. Es mejor eso que capaz comerse un digito por error
2) Pero mira que no hace NADA, un misero insert en la base de participantes, mucho mas simple por ejemplo que contestar una pregunta de cuestionario, que graba una tabla de horario, otra tabla de puntaje, otra tabla de respuesta... Ahi hay algo raro, cuando la tengan conectada y accesible lo voy a investigar.
3) Supongo que si, pero va a tardar mas en cargar la pagina (15 minutos de audio no es poca cosa, y no se si puede hacer streaming)
4) Yo no hice nada crhrome-especifico. Decime que no te anda con Safari y veo, pero no tengo una Mac para probarlo, solo podria con el Safari de iPhone
5) Ok
6) No guarda o no exporta ? Guardar yo recuerdo que se guardaba. Si entras en un participante no te muestra el dato ?

**Comment by LeandroBraier** [comment]
1) Basado en la experiencia, prefiero que falte un dígito jeje

2) Lo sé, por eso me resulta tan extraño que tarde tanto y a Valen también. Investiguemos para optimizar.

3) Probemos porfa. No habría streaming. Es música de fono como un track en mp3 que dura igual que el countdown.

4) No me accede a las páginas directamente. No las carga nunca. Probamos con el registrarse y con el CMS.

6) No podría confirmarte ahora, cuando conecte el servidor te digo, pero en el export no me aparecieron.

abrazo

**Comment by mkreyness** [comment]
1) ok cuando pueda acceder investigo que hace que no te deje ingresar menos, seguro que es una mascara del CSS de lo cual no tengo idea, pero le preguntare a Fede.
2) Y con los cuestionarios entonces NO tardaba ? Para mi es un problema de conexion de esa notebook, probaron desde otro lado, por ejemplo, desde el propio server ? Porque si el server es el mismo y la red es la misma y lo que cambia es de Notebook a Raspi, el problema estaba en la Notebook
4) el CMS es el mismo de siempre, que lo accediste miles de veces desde Safari. No puede ser un problema de browser.

**Comment by LeandroBraier** [comment]
1) Ok

2) Como te decía: usamos 4 máquinas distintas, mi celu y otra notebook
conectada por ethernet al lado del servidor. En todas demoraba lo mismo.
Por eso suponemos que es algo del sistema.

4) Yo nunca usé el CMS con el safari pero investiguenlo. En la práctica no
pudimos acceder desde celus ni desde compus que no sea desde el chrome.

2016-08-18 12:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by ghost** [comment]
Por momentos la red andaba lenta también desde el punto de vista
raspi-server. Tardaban en validar los dni inclusive tuve que reiniciar 2 de
ellas porque la página se colgó al validar el dni.
Marce habia un ping con una latencia de 400 ms entre mi notebook con
debian, el router y el server. Inclusive se llego a latencias mayores. Será
el router el lento?
No hice tests de la red sin router pero no estaría mal probar el desempeño.

**Comment by mkreyness** [comment]
Es un desastre ese router o el cableado entonces, si yo pingueo mi routercito D-LINK 600 desde mi PC que tiene ya unos años, me da siempre < 1ms, o sea algo tan chico que es inmedible. Lo que vos decis es  400 o mas veces ese tiempo.
El server no es, porque mientras estabamos por Neorouter andaba todo perfecto.

**Comment by ghost** [comment]
El router estaba como server dhcp para las máquinas que se conectaban por wifi. Para la próxima lo dejo directamente como access point y que esas máquinas se conecten con ip fija.
Por otro lado en la red está el switch de 16 bocas. Que no creo que sea un problema.
Hablando del cableado, conecté al server, al router y a mi pc con los cables clase 6 que usamos para paty chile en verano y en invierno y aún asi había lentitud en la red. Tardaba un monton en acceder a todas las webs tanto al cms como al logo.html

**Comment by mkreyness** [comment]
Aparentemente no seria el switch, porque tambien les pasaba por wifi, no ?
Yo de lo que mas desconfio es del router.

**Comment by ghost** [comment]
Para descartar el factor router voy a ir a la oficina y probar con el nisuta y listo

**Comment by LeandroBraier** [comment]
Mañana estamos en la produ Valen si querés venirte y lo probamos. De
cualquier forma igual dejamos ya conectado el servidor para que MK siga
investigando. Gracias a los dos!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-08-18 16:34 GMT-03:00 valentinsabbath notifications@github.com:

**Comment by ghost** [comment]
Oka mañana me paso!

**Comment by LeandroBraier** [comment]
@mkreyness me dice Valen que ya está conectado el servidor. Corrijamos y revisemos todo lo hablado porfa. Lo de la lentitud dice Valen que debe ser alguna raspi porque con el router solo anda barbaro jeje

1) Que en el DNI se puedan ingresar 7 cifras, no solo 8 (tuvimos un problema con 1 participante quizá un poco viejo)

2) La registración al presionar el botón demoraba 10 segundos (20 segundos en nuestros testings en la agencia). Esto no variaba con ethernet o por rooter, así que habría que optimizar el procesamiento de esa info porque fue algo medio crítico que nos hizo poner 4 máquinas a inscribir (incluido Marcelo S, fue muy gracioso) más yo con el celu y aún así no dabamos a vasto (hubo 215 inscriptos!!!)

3) Se le puede agregar sonido a los countdowns? Si yo te doy un track que dure 15 minutos por ejemplo para el countdown del juego 1 y 2 se le puede poner? (no te digo para el countdown de varias horas porque sería imposible)

4) Notamos que el sistema se podía utilizar solo con Chrome. Con Safari no, por ejemplo. Se puede optimizar esto también?

5) Necesitaría Linkear en la página "logo" el ranking de listado también, como "Ranking 2" aunque quede en 2 líneas.

6) Al exportar las bases no me guarda el dato de localidad en absoluto (recuerdo que cargamos el dato de muchas ciudades y no se exportaron. Solo las provincias.

abrazo

**Comment by mkreyness** [comment]
1) siempre me sono raro esto, y acabo de verificar que no hay ningun problema en ingresar 7 cifras. No se de donde sacaron eso.
El punto 2) no se puede verificar.
3) Pasame el track
4) no hay nada que haga que sea especifico para Chrome. Acabo de probar con Firefox y funciona sin problema. No puedo probar en Safari porque no tengo Mac y si bien tengo iPhone no tengo como entrar desde el iPhone a esa red (el Neorouter no anda en el iPhone)
5) ningun problema
6) ya verifique, no es un problema de exportacion, el dato no se guardo. Ninguno dice nada.

**Comment by LeandroBraier** [comment]
1) Es una conclusión de @valentinsabbath de que ese era el problema de ese usuario. Se nos cae una teoría entonces.
2) OK.Lo chequearemos en el evento finalmente, reponiendo la raspi que lo haga lento.
3) Descartado por Eze este pedido. Gracias!
4) ok. Probaré con Safari alla.
5) Hecho?
6) No te puedo creer. Por qué no se guardó? Ni siquiera el dato default?

**Comment by mkreyness** [comment]
1) tal vez se referian a algun problema al querer identificar las 3 cifras faltantes en el login ?
5) No, pero en el curso de la noche lo hare en algun momento y te aviso
6) Seguramente esta diferente el nombre del campo entre el formulario y lo que espera el programa, al cambiar el desplegable que habia puesto Fede por el campo de texto tipeable con el autocomplete. Es bug mio y lo tengo que arreglar.

**Comment by mkreyness** [comment]
5) Listo
6) si, lamentablemente fue eso. Ya esta arreglado.

**Comment by LeandroBraier** [comment]
Gracias MK!!
