### ISSUE TITLE
Pequeño ajuste a Mailing de Cumpleaños Vendedores. 05/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#347]
@FAAREIA necesito un pequeño ajuste en este mailing.

http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/vendedores-cumple.html

Es reemplazar el paquete de regalo por el ticket de 1000 puntos directamente, como dice en la imagen:

![modificacion-mailing-cumpleanos-vendedores](https://cloud.githubusercontent.com/assets/6719872/17347064/4e0d6056-58e4-11e6-99b4-37bf6e0e7828.JPG)

Esto puede ser para el viernes tranca. 

abrazo

**Comment by FAAREIA** [comment]
Si les das F5 ya se puede ver:
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/vendedores-cumple.html

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

Me parece que no se entiende manteniendo ambas cosas. Quitá el paquete de regalo cerrado de la imagen y dentro del rótulo azul poné "TE REGALAMOS PARA ESTE MES:", de forma que ese mensaje quede arriba del ticket de 1000 PUNTOS EXTRA.

Abajo del ticket podés poner el paquete abierto si queda bien, sino con eso estamos.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo ajusté:
http://www.parexklaukol.com.ar/_mailing/vendedores-cumple/vendedores-cumple.html

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Gracias!

A producción directo nomás.

abrazo
