### ISSUE TITLE
Pequeño ajuste de texto en Web Revear. 08/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#348]
@FAAREIA esto es para el lunes tranqui.

En la página de Preguntas Frecuentes, cambiar la pregunta de QUÉ COLORES OFRECEN por esto:

¿QUÉ COLORES OFRECEN? 
Poseemos una cartilla de colores stándar de REVEAR, la cual es aplicable a la mayoría de los productos que fabricamos. Por otra parte, podemos fabricar a pedido cualquier otro color, de una cartilla de más de 2700 colores. Este servicio también es prestado por la mayoría de nuestros Distribuidores en todo el país. (Consultar colores estándares disponibles) 

Tranqui y sin apuro.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !
