### ISSUE TITLE
Ajustes en Calculador Revear. 08/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#349]
@mkreyness me pasan 2 errores del calculador de la web de Revear. Te fijás qué puede ser?
1.  Para 350Mts determina 1 tambor, 9 latas grades y 5 chicas... En realidad debería decir 2 tambores. Me dice el cliente que la cantidad es la misma y es más práctico decir 2 tambores que mostrar todos los tipos de unidades que trae el producto.

<img width="1158" alt="captura de pantalla 2016-08-04 a las 4 56 18 p m" src="https://cloud.githubusercontent.com/assets/6719872/17415564/d6bfa33c-5a60-11e6-98f7-c98fe552d5c0.png">
1. También me dice que no aparecen los productos Revefloor ni Revecret, pero tienen cargado el rendimiento por m2 en el CMS. Te fijás qué pasa?

abrazo

pd: Esto no es urgente. Tiene prioridad el sistema del evento.

**Comment by mkreyness** [comment]
O sea quieren que redondee a 2 tambores si anda por encima de 1.5 tambor por ejemplo ? Esta barbaro lo que dicen pero tienen que definir un criterio.
Donde pusiste "me dice que aparecen" queres decir "me dicen que NO aparecen" ?

**Comment by LeandroBraier** [comment]
Tal cual las 2. Ahi agregué el NO.

Es que 1 tambor de 300 kg + 9 baldes de 30 kg + 5 envases de 6 kg equivale exacto a 2 tambores de 300. No es redondeo. Es exacto. No sé por qué no muestra 2 tambores directamente.

**Comment by mkreyness** [comment]
Ese que la cuenta no da 600 y el 5to envase no se usa completo, pero lo trata de aproximar lo mejor que pueda.
Ponele que necesita 599 Kg, y eso lo forma con 300 + 9 x 30 + 4 x 6 + 5kg. Como no hay envase de 1kg, le suma 1 a la ultima unidad. Lo que no "sabe" es que entonces puede reconvertirse a 1 balde mas, y ahi 10 baldes a  un tambor.

**Comment by mkreyness** [comment]
Si todos los envases son multiplos del envase mas chico, con redondear todo primero al entorno del mas chico se arregla (en este caso primero convierto 599 a 600 y listo), pero no se si en todos los casos todas las unidades posibles son multiplos entre si, ponele (exagerando) que viniera en baldes de 19 o bolsas de 13, y hacen falta 25. El sistema te ofreceria 19+13, cuando obviamente seria mucho mejor 13+13

**Comment by LeandroBraier** [comment]
Claro, lo que te quiero decir es que 2 tambores o la suma de esos distintos envases dan 600 kg igual. Entonces es lo mismo que le sobre un toque de un tambor o de un balde. Prefieren que sea más simple. Es solo eso. 

No te preocupes por las matemáticas. Si igual va a sobrar, que sobre.

En cuanto a Revefloor y Revecret pudiste ver algo?

**Comment by mkreyness** [comment]
Es lo de siempre, no tienen cargadas presentaciones. No es el TEXTO que figura en la solapa principal para mostrar en el catalogo de productos, es la SOLAPA Presentaciones donde hay que detallar los envases y contenidos.

**Comment by LeandroBraier** [comment]
Perfecto. Ya te lo subo yo eso entonces.

Gracias MK!

**Comment by LeandroBraier** [comment]
MK, ya agregué las presentaciones. De ambos son: 1 balde de 30 kg y 1 envase de 6 kg, pero lo importante es que si o si siempre hay que comprar los dos. Son componente A y componente B. No sirve uno sin el otro. Podrás incluir eso en la ecuación del calculador?

**Comment by mkreyness** [comment]
entonces son sub-productos combinados ? No tenemos eso previsto.

**Comment by mkreyness** [comment]
Ya esta arreglado lo del fraccionamiento, fijate que ahora 350m2 de Marble da 2 tambores de 300.

**Comment by LeandroBraier** [comment]
Excelente MK. Con lo de Revefloor y Revecret no sé cómo solucionarlo. No podremos hacer que yo te digo cuánto de cada presentación tenés que usar por m2 y el calculador los cuente en paralelo?

**Comment by mkreyness** [comment]
pero hay que modificar todo, el CMS y el programa calculador, cuando termine lo del evento Klaukol si queres me pongo con eso, pero ahora seria un suicidio.

**Comment by LeandroBraier** [comment]
Ok. Si obvio.  Prioridad el evento.

**Comment by LeandroBraier** [comment]
@mkreyness hablé con el cliente. Para resolver esto me dijeron que simplemente pongamos al Revefloor el rendimiento de 3 kg / m2, y revecret de 4 kg m2. Ya lo puse y aparecen en el calculador así que todo en orden. CIerro el ticket. abrazo
