### ISSUE TITLE
CMS Novedades Klaukol. DEADLINE: 09/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#35]
MK, cómo va? Ya tenemos un acceso para pasarles a las chicas y que puedan cargar novedades en las webs de ParexKlaukol?

abrazo

**Comment by LeandroBraier** [comment]
Marce, viste esta consulta? Necesito saber si llegamos a tenerlo listo para el lunes o martes.

abrazo

**Comment by mkreyness** [comment]
Si, esta el CMS hecho desde el primer dia, pero por el bolonki que es el 
tema de los paths para las imagenes (que dependen del sitio) no tengo 
como hacer que se carguen con el CMS.
Tendrian que cargar la novedad sin fotos y pasarmelas para que yo las 
enganche a mano donde corresponda segun cual sea el sitio.
Con tiempo eso lo puedo solucionar, pero no para hoy.

Si queres les habilito la opcion en el acceso de mantenimiento que ya 
tienen y usan para el corralon.

**Comment by LeandroBraier** [comment]
Dale, habilitales la opción pero cuando tengamos solucionado lo de las imágenes. Eso no puede estar para el martes?

**Comment by mkreyness** [comment]
Si, pero depende de que otras sorpresas me encuentre !
Recien me entero de eso del uso anonimo del sitio de vendedores...

**Comment by LeandroBraier** [comment]
Ok. Entonces si lo prometo para el miércoles es a prueba de sorpresas?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-05 18:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si pero tratemos de manejar un orden de prioridades y entender que los 
tiempos se suman.
Con esto + lo de vendedores de klaukol a modificar tengo carton lleno.

**Comment by LeandroBraier** [comment]
Entendido. Solo necesito saber tiempos.

**Comment by mkreyness** [comment]
Ya esta implementado en el CMS, la idea seria que entren por aca:

http:/www.parexklaukol.com.ar/cgi-bin/red.pl

con el user/pass que ya tienen (mantenimiento, parkla)

Les separe un entry por cada pais para facilitar la cosa. Ahora hay un problema: las fotos todo bien pero el CUERPO de la noticia es un HTML embedded (asi fue lo que rescato Fede de los sitios anteriores y asi lo guardamos en el CMS) porque no tienen un formato fijo. Esos cuerpos en general TAMBIEN contienen fotos y videos, los videos no es gran problema porque seran links a youtube, pero las fotos, si no las tienen hosteadas en algun lado, no van a tener como cargarlas aca via CMS. Tendriamos que darles o algun acceso FTP o que nos las pasen y nosotros las instalamos donde corresponda.

**Comment by LeandroBraier** [comment]
Gracias Marce! 

Lo que no entiendo es por qué no podemos implementar un sistema como el de Dánica, en el cual sí podemos cargar directamente las imágenes. Sobre todo teniendo en cuenta que en el CMS que me pasás está la opción de SUBIR ARCHIVO, no la de INGRESÁ LA URL DE LA IMAGEN.

Yo propongo que si lo podemos solucionar lo hagamos, creo que tenemos espacio de sobra en el servidor para subir 5 imagenes por mes, no? De última le ponemos un límite de tamaño si es necesario.

abrazo

**Comment by mkreyness** [comment]
```
LA imagen del listado de novedades SI la podes subir, y asi estan
todas visibles. Esa es la de "subir archivo".
El problema es que el CONTENIDO de una novedad no tiene un formato
fijo, ni secciones fijas, ni nada, es un cacho de HTML que me
pasaron, y DENTRO de ese HTML hay referencias a imagenes que, como
estaban en el backup, funcionan, pero si quieren agregar nuevas no
tienen como.
Por ejemplo, hay noticias que tienen una lista de 4 o 5 imagenes
dentro, cada una con un texto, otras no, son puro texto.

Danica tiene una estructura:
    - receta
        - foto chica
        - foto grande
        - video
        - pasos
            - ingredientes

aca es 

    - novedad
        - foto
        - html

no tiene un formato fijo el html que yo pueda representar, y no son
"ingredientes" las fotos.


El 08/06/2015 a las 9:36, LeandroBraier
  escribió:


  Gracias Marce! 
  Lo que no entiendo es por qué no podemos implementar un sistema
    como el de Dánica, en el cual sí podemos cargar directamente las
    imágenes. Sobre todo teniendo en cuenta que en el CMS que me
    pasás está la opción de SUBIR ARCHIVO, no la de INGRESÁ LA URL
    DE LA IMAGEN.
  Yo propongo que si lo podemos solucionar lo hagamos, creo que
    tenemos espacio de sobra en el servidor para subir 5 imagenes
    por mes, no? De última le ponemos un límite de tamaño si es
    necesario.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ok. Quise probar como se veía cargando la imagen y no anda bien el sistema.

Probé con una publicación llamada "Feria Construya Chaco". En Novedades no aparece y cuando la busco por URL se ve horrible:

http://www.parexklaukol.com.ar/novedades/feria-construya-chaco.html

Revisá esto porfa. Necesito que funcione OK o decime qué estoy haciendo mal.

abrazo

**Comment by mkreyness** [comment]
```
1) no es INMEDIATO, se publican cada 1 min. Igual capaz no la veias
porque se habia ido al fondo por no tener fecha. Ahi le puse fecha a
mano, en realidad esta faltando el campo de fecha real en el CMS (el
que hay es una fecha "mostrable" que ya no tiene sentido porque el
sistema la calcula sola). Ahora ajusto eso.
2) el html lo pusiste como un texto plano, fijate como estan hechos
(no por mi) los otros html
Minimo hay que ponerle <p> y </p> para que lo arme como
un parrafo.

Fijate ahora como quedo. Ojo la fotito SOLO se usa en la lista de
noticias (o de categorias o de etiquetas), no dentro de la noticia,
eso lamentablemente tiene que estar embedded en el HTML. Si queres
usar la misma foto, podes referenciar a esto:

<img
```

src="/media/wysiwyg/Noticias-AR/Lupa-3-Arquitectos-Corregido-Compress-BN.gif">

```
que es el tag para ver ESA imagen.

El 08/06/2015 a las 10:36,
  LeandroBraier escribió:


  Ok. Quise probar como se veía cargando la imagen y no anda bien
    el sistema.
  Probé con una publicación llamada "Feria Construya Chaco". En
    Novedades no aparece y cuando la busco por URL se ve horrible:
  http://www.parexklaukol.com.ar/novedades/feria-construya-chaco.html
  Revisá esto porfa. Necesito que funcione OK o decime qué estoy
    haciendo mal.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Bueno, Marce. Esas son todas cosas que necesito que corrijas. El cliente no sabe html y no va a ingresar un html. Necesito que el HTML se arme solo. Si querés que la foto aparezca siempre en el mismo lugar, en un html automático, o como te parezca mejor, pero necesito que sea bien sencillo cargar las novedades. Recordá que este CMS es para el cliente.

Ahora te llamo igual por otro tema.

abrazo

**Comment by LeandroBraier** [comment]
Fede, hablé recién con MK por teléfono. Para mañana necesito que armes un template html para novedades, de forma que el cliente simplemente cargue un texto, foto y a lo sumo un link a un video de youtube y con eso se arme el artículo.

Como referencia del template tomá este artículo de novedades:
http://www.parexklaukol.com.ar/novedades/klaukol-lanza-el-nuevo-adhesivo--klaukol-grandes-piezas-porcellanato-.html

Tendría:

1) 1 foto debajo del título y arriba del texto.

2) Un texto.

3) 1 video de YouTube embebido debajo del texto y arriba de los tags.

Cuando tengas esto armado pasaselo a MK porfa para implementación.

**Comment by LeandroBraier** [comment]
Este pedido puede ser para mañana.

abrazo

**Comment by FAAREIA** [comment]
Ya cree el template. El identico al actual pero agregué la variable de imagen y video. La del cuerpo ya estaba. Ya le avisé a marce también.

**Comment by LeandroBraier** [comment]
MK: Fede ya creó el template. Avancemos con esto entonces para que lo pueda testear en el cms.

Gracias Fede!! 

abrazo

**Comment by mkreyness** [comment]
```
Lo veo esta tarde.

El 08/06/2015 a las 13:47,
  LeandroBraier escribió:


  MK: Fede ya creó el template. Avancemos con esto entonces para
    que lo pueda testear en el cms.
  Gracias Fede!! 
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto, no hay apuro con esto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-08 13:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Fede, asi (aun recortado) no sirve, porque vuelve a incluir 
 adentro, y la gracia precisamente es que eso sea algo tipo 
, ya que  es lo que voy a reemplazar con esto 
en el template general. Es como si fuera un include. Acordate que en 
ninguna de las variables va a haber HTML porque no queremos que escriban 
html los usuarios.

Ademas la idea es que en  solo vaya el URL de la imagen, el 
resto ("<img src=" y cualquier class alrededor) ya esten en el template.

Voy a cambiarlo por mi cuenta por algo tipo asi para poder ir 
programandolo, despues fijate de estilizarlo como corresponda.

<p>

<img src=""/>

</p>

<p>

</p>



<p><iframe width="640" height="480" src="" frameborder="0" 
allowfullscreen></iframe></p>

**Comment by mkreyness** [comment]
```
Listo, quedo asi:

- en el CMS ahora por cada novedad hay una SEGUNDA SOLAPA con el
HTML. En el caso de las viejas, es el viejo HTML.
- pero tambien hay ahora en la PRIMER solapa nuevos campos de:
    - Imagen GRANDE
    - Texto
    - Video
    - un boton de "Generar HTML y Guardar"
Entonces:
    - al crear una novedad, se le puede subir (ademas de la imagen
chica para la lista) una imagen grande, poner un texto (puro) y el
URL de un video.  Solo el texto seria obligatorio, las otras dos son
opcionales.
    - al apretar "Generar HTML y Guardar", se arma (fuera de la
vista habitual del usuario) el HTML correspondiente, y se guarda.
    - en caso de querer modificar algo de ese HTML manualmente, solo
hay que tener la precaucion de darle siempre el "Guardar" comun (sin
generar HTML).
    NO puse que se genere siempre el HTML ante cualquier cambio de
imagen/texto/video, precisamente para evitar que eso pise
involuntariamente un eventual HTML toqueteado.


El 08/06/2015 a las 13:53,
  LeandroBraier escribió:

Perfecto, no hay apuro con esto.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-08 13:51 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Lo veo esta tarde.
  >
  > El 08/06/2015 a las 13:47,
  > LeandroBraier escribió:
  >
  >
  > MK: Fede ya creó el template. Avancemos con esto entonces
  para
  > que lo pueda testear en el cms.
  > Gracias Fede!!
  > abrazo
  >
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/35#issuecomment-110071599
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Genial MK. Entonces el botón "Generar HTML y Guardar aparece solo la
primera vez y después queda deshabilitado no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 2:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No, no.
Cualquier ajuste que hagas en el texto tenes que volverlo a apretar
para que cambie el HTML, por lo tanto el boton sigue habilitado.
Lo que digo es que si se hizo un toque DIRECTO EN EL HTML (como es
el caso de los viejos, en que TODO esta en el HTML y no existe info
en los otros campos) no hay que usar el boton.
Pero no puedo yo detectar las intenciones.
A lo sumo puedo rechazar el uso del boton si el texto esta vacio,
pero imagen y video vacios son opciones validas.

El 09/06/2015 a las 9:04, LeandroBraier
  escribió:

Genial MK. Entonces el botón "Generar HTML y Guardar
  aparece solo la
  primera vez y después queda deshabilitado no?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-09 2:03 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Listo, quedo asi:
  >
  > - en el CMS ahora por cada novedad hay una SEGUNDA SOLAPA con
  el
  > HTML. En el caso de las viejas, es el viejo HTML.
  > - pero tambien hay ahora en la PRIMER solapa nuevos campos
  de:
  > - Imagen GRANDE
  > - Texto
  > - Video
  > - un boton de "Generar HTML y Guardar"
  > Entonces:
  > - al crear una novedad, se le puede subir (ademas de la
  imagen
  > chica para la lista) una imagen grande, poner un texto (puro)
  y el
  > URL de un video. Solo el texto seria obligatorio, las otras
  dos son
  > opcionales.
  > - al apretar "Generar HTML y Guardar", se arma (fuera de la
  > vista habitual del usuario) el HTML correspondiente, y se
  guarda.
  > - en caso de querer modificar algo de ese HTML manualmente,
  solo
  > hay que tener la precaucion de darle siempre el "Guardar"
  comun (sin
  > generar HTML).
  > NO puse que se genere siempre el HTML ante cualquier cambio
  de
  > imagen/texto/video, precisamente para evitar que eso pise
  > involuntariamente un eventual HTML toqueteado.
  >
  >
  > El 08/06/2015 a las 13:53,
  > LeandroBraier escribió:
  >
  > Perfecto, no hay apuro con esto.
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-06-08 13:51 GMT-03:00 mkreyness
  > <notifications@github.com>:
  >
  > >
  > >
  > >
  > >
  > >
  > > Lo veo esta tarde.
  > >
  > > El 08/06/2015 a las 13:47,
  > > LeandroBraier escribió:
  > >
  > >
  > > MK: Fede ya creó el template. Avancemos con esto
  entonces
  > para
  > > que lo pueda testear en el cms.
  > > Gracias Fede!!
  > > abrazo
  > >
  > > —
  > > Reply to this email directly or view
  > > it on GitHub.
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > >
  >
```

<https://github.com/LeandroBraier/Klaukol/issues/35#issuecomment-110071599
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/35#issuecomment-110226812
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Entiendo. igual no me preocupa porque es algo que podría pasar con
novedades viejas, no las nuevas a crear. Gracias Marce!

Lo pruebo y te digo si me falla algo.

abrazo

**Comment by LeandroBraier** [comment]
Marce: lo probé y funcionó todo bien. Consulta: los videos se suben directamente al hosting entonces?

Pensé que ibamos a poner una url de youtube y se iba a generar el embed solo.

**Comment by mkreyness** [comment]
Mmm, no, la idea era que te apareciera un campo de texto para pegar una 
URL. No me fije que se puso automatico el boton.
Espera que lo arreglo y te aviso.

**Comment by LeandroBraier** [comment]
Dale, no problem. Otra sugerencia: debería tomar los puntos apartes o espacio entre líneas como un </p><p>

Se puede eso? Para que no quede el texto todo pegado.

**Comment by mkreyness** [comment]
Si, por eso hubiera estado bueno poner el editor HTML como en lo de 
'cadena de mails' (que no tienen que ESCRIBIR html, eso lo convierte 
internamente).

**Comment by LeandroBraier** [comment]
Bueno, sumemoslo entonces. Está bueno. Que sea lo más similar a un mail de
Outlook o ese estilo de clientes posible.

Dentro de las prioridades no sería lo primero igual.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-10 17:33 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ahi puse que minimamente reemplace los enters por <br> con lo cual se 
separa bien, fijate

http://www.parexklaukol.com.ar/novedades/forum-construya-mendoza-2015.html

(por si ya tenias cacheado dale F5).

**Comment by LeandroBraier** [comment]
Gracias!
