### ISSUE TITLE
PArex Uruguay Caido

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#350]
@mkreyness te fijás qué pasó?

Probablemente tema de IP de Duplika de nuevo. Decime nomás el nuevo ip si es así y les pido que redireccione.

**Comment by mkreyness** [comment]
En este momento y si no sopla mucho el viento, el IP de parexklaukol.com.ar (y por lo tanto el que tienen que ponerle a UY y PY) es  67.227.178.197

**Comment by mkreyness** [comment]
Paraguay lo tiene bien, o ya les pasamos este dato, o que se avivaron por su cuenta.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Ahi les escribí. abrazo

**Comment by LeandroBraier** [comment]
@mkreyness Marcos de Parex Uruguay me responde esto a mi pedido de que usen los DNS:

Esimtado, no hay problema, si necesito me matengas estos registros para seguir funcionando con el correo, avisame cuando lo tenas armado y te delgo a estos dns.
Un abrazo, 

mail.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

autoconfig.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

autodiscover.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

_autodiscover._tcp.parexuruguay.com.uy.    14400    IN    SRV    Priority: 0
Weight: 0
Port: 443
Target: cpanelemaildiscovery.cpanel.net    

webdisk.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

whm.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

webmail.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

cpanel.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

cpcalendars.parexuruguay.com.uy.    14400    IN    A    67.23.226.189    

_caldav._tcp.parexuruguay.com.uy.    14400    IN    SRV    Priority: 0
Weight: 0
Port: 2079
Target: power.nsjet.com    

_caldavs._tcp.parexuruguay.com.uy.    14400    IN    SRV    Priority: 0
Weight: 0
Port: 2080
Target: power.nsjet.com    

_carddav._tcp.parexuruguay.com.uy.    14400    IN    SRV    Priority: 0
Weight: 0
Port: 2079
Target: power.nsjet.com    

_carddavs._tcp.parexuruguay.com.uy.    14400    IN    SRV    Priority: 0
Weight: 0
Port: 2080 
Target: power.nsjet.com    

_caldav._tcp.parexuruguay.com.uy.    14400    IN    TXT    path=/    

_caldavs._tcp.parexuruguay.com.uy.    14400    IN    TXT    path=/    

_carddav._tcp.parexuruguay.com.uy.    14400    IN    TXT    path=/    

_carddavs._tcp.parexuruguay.com.uy.    14400    IN    TXT    path=/    

cpcontacts.parexuruguay.com.uy.    14400    IN    A    67.23.226.189

mail.parexuruguay.com.uy.       MX  0

Lo podemos hacer a eso?

**Comment by mkreyness** [comment]
Nada de eso depende de nosotros. Nosotros malamente nos enteramos de que Duplika cambio un IP y se lo avisamos porque ELLOS manejan todo eso. No tenemos ninguna forma de poner ni sacar nada de lo que dice.

**Comment by mkreyness** [comment]
Para decirtelo de otra manera, el dominio parexuruguay.com.uy NO ESTA DELEGADO a Duplika.
Solo esta APUNTADO por quien lo tenga delegado.
Fijate que si no fuera asi, no se caeria cada vez que cambia de IP, porque Duplika lo podria ajustar por su cuenta como hace con parexklaukol.com.ar (que SI esta delegado a Duplika).

**Comment by LeandroBraier** [comment]
Sisi, entiendo eso. Entiendo entonces que no podemos hacer lo que pide porque no tenemos control sobre el dominio y que eso lo tiene que resolver la gente de Parex.

Ahora: si tuvieramos delegado por dns el dominio a Duplika, ¿SI tendríamos control sobre estos temas o tampoco?

**Comment by mkreyness** [comment]
No se si la gente de Parex, probablemente el proveedor uruguayo donde esta delegado el dominio.
Si estuviera el dominio delegado a Duplika podemos hacer las cosas que permite hacer el CPanel de Duplika, siempre es mejor pasarle a ellos porque el CPanel es limitado.

**Comment by mkreyness** [comment]
"ellos" me refiero a los tecnicos de Duplika.

**Comment by LeandroBraier** [comment]
pero entonces, en caso de hacer esto, tendríamos que alojar todas sus casillas de mail ponele? LEs regalaríamos nuestro hosting? O es solo delegar a hostings que ellos tienen para esas cosas?

**Comment by mkreyness** [comment]
No, el tema siempre es asi: vos registras un dominio en la autoridad competente, ponele en este caso nic.uy. Ahi estas obligado a ponerle los DNS a tu dominio, y ellos (el NIC) lo almacena en lo que se llama los ROOT servers. Esos DNS son la direccion de un servidor (llamemoslo ZONE server) donde corre un programa que CONTESTA PREGUNTAS, segun un protocolo. Las respuestas a las preguntas surgen de una especie de "Guia IP" que guarda el zone server, que se llaman "ZONE FILES". Es uno por cada dominio.
Distintos programas preguntan distintas cosas, por ejemplo, un browser le pregunta al ZONE server a que IP se tiene que conectar para acceder a una pagina web de un dominio.
Otro programa, un cliente de mail, le pregunta a que IP se tiene que conectar para entregar un correo.
DONDE esta el ZONE server es totalmente INDEPENDIENTE de las respuestas que da.
De hecho los ZONE servers viven prestandose esa "guia de dominios" los unos a los otros, para que se cacheee y la proxima vez no le pregunten a el. 
Pero siempre para cada ZONE FILE hay un unico server AUTORITATIVO, o sea, el que los demas le preguntan cuando no saben. Ahi en el server autoritativo es donde se hacen los cambios. 
Entonces: el dominio esta DELEGADO a un server autoritativo donde se maneja el "zone file maestro" digamos, del dominio.
DONDE este fisicamente esto, es totalmente independiente de su contenido.
O sea, yo puedo en Buenos aires tener una guia de telefonos de Rosario, y consultarla.
Yo puedo tambien tener una pagina con todos los telefonos de las sucursales de Garbarino del pais, aunque yo no este simultaneamente parado "en todo el pais".
No es lo mismo vender una heladera, que saber el telefono de donde venden la heladera.
Entonces: el servidor de mail, el servidor web, el servidor de cualquier cosa, puede estar en cualquier lugar del mundo, con cualquier IP, lo importante es que el que tiene el server autoritativo (el que SABE donde estan alojados esos servicios) es el que puede hacer los cambios.
Si Garbarino de Ushuaia cambia su numero de telefono, mientras no le avise al que publica la guia de telefonos en casa central, no va a recibir un misero llamado.
Obviamente eso implica que es CONVENIENTE, pero no OBLIGATORIO, que el server autoritativo lo maneje el mismo personal que maneja el hosting, porque asi cuando hacen el cambio de IP tambien pueden actualizar el zone file, y es probable que cuando no hay contacto entre el personal que modifica los IP de los servicios con el personal que administra el zone file, pase lo que esta pasando.

Lo que a vos te estan diciendo, erroneamente, es que nosotros que tenemos apenas un poco de contacto con el que administra el servicio de hosting web, garanticemos que el que maneja el zone file no lo rompa, pero no tenemos ningun acceso al zone file.

**Comment by mkreyness** [comment]
web, mail, y cualquier otro servicio puede estar en servidores separados, con IP separados, en hosting separados, siempre y cuando TODOS los cambios se le comuniquen al que maneja el zone file.

**Comment by LeandroBraier** [comment]
Muchas gracias por la explicación MK!

Entonces le digo a esta persona que no podemos hacer eso porque no tenemos control del zone file. Que tendrían que pedirle eso al que maneje el zone file del dominio.

Confirmame si es correcto nomas y lo mando.

abrazo

**Comment by mkreyness** [comment]
Si pero lo de "zone file" es algo muy interno de como se llama, es mejor que le digas que eso lo tiene que hacer quien tenga control del "DNS autoritativo".

**Comment by LeandroBraier** [comment]
Perfecto. Con eso les respondo. Gracias!!
