### ISSUE TITLE
Ingresar no suma Puntos en Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#351]
@mkreyness cuando puedas te fijás esto? Un usuario escribió quejándose de que no suma puntos por ingresar. Entonces la persona que administra hoy comunidades entró a Juegos y vio que no estaba, entonces lo creó. Eso me resulta raro porque siempre existió ese juego. Te fijás qué puede estar pasando que no funciona hoy?

<img width="1403" alt="captura de pantalla 2016-08-12 a las 12 12 28 p m" src="https://cloud.githubusercontent.com/assets/6719872/17626157/7643308c-6082-11e6-9de3-593e0e47b25c.png">

**Comment by mkreyness** [comment]
No entiendo, como va a crear el juego "puntos por ingresar", eso es de uso interno del sistema, tiene un id FIJO. Si lo borraron, hicieron flor de desastre el ID del nuevo que haya puesto no sirve para nada porque los programas no lo conocen.

**Comment by mkreyness** [comment]
Si tal cual borraron el juego de ID =3,  y crearon uno de ID=131 que no sirve para nada, que esperaban que el sistema interpretara la descripcion y supiera que hacer ?
Ahi le cambie el ID  a 3 y le puse como tipo "Actividad" (al que crearon no le pusieron nada).
Pero hay que cortarle los dedos a quien hizo esto, fue un acto criminal !
Le puse los 5 puntos a c/u de los 4 que entraron hoy.... Pero esto no fue HOY. Esta pasando asi desde el 17 de julio. Quiere decir que en el sorteo de Julio no se tomaron en cuenta estos puntos (ya que el inexistente juego no tenia puntaje).
Ahora voy a forzarle los 5 puntos a cada entrada de agosto, pero igual esto va a generar bolonki con las fichas, porque capaz algunos ya deberian haber sumado fichas y hasta que hagan algo mas no se les va a ajustar.

**Comment by LeandroBraier** [comment]
Muchísimas gracias MK!! Lo debe haber borrado esta persona sin querer. Para evitar que vuelva a ocurrir si podés pasame un usuario de admin que no pueda borrar cosas y se lo paso.

Está perfecto todo esto que me decís que hacés. Simplemente si llega a llegar queja de algún usuario le explicamos y se los sumo yo a mano, no te preocupes. 

Cuando puedas tranqui pasame ese usuario nomás.

abrazo y gracias otra vez!

**Comment by mkreyness** [comment]
no hace falta un usuario, deshabilito el boton eliminar de esa pantalla de juegos y listo. De ultima si algo no se usa se puede dejar no publicado. En un rato lo deshabilito.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias! Mejor aun.

**Comment by mkreyness** [comment]
Listo. Que lindo que es mi CMS :)

**Comment by LeandroBraier** [comment]
jajajjaja Cada dia canta mejor
