### ISSUE TITLE
Usuarios de Rosario a sumar a Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#352]
@mkreyness te paso la base completa de pre + inscriptos en el evento mismo, revisada y limpia. Aun así puede ser que haya usuarios ya registrados con el mismo mail o sin mail. Lo que necesito es que los inscribas a todos por sistema (para evitar hacerlo 1 x 1) y me avises, así le mando mailing de bienvenida a los que tengo el mail.

[Base de Participantes Inscriptos en el Evento en Rosario a sumar en Club de Colocadores.xlsx](https://github.com/LeandroBraier/Klaukol/files/425218/Base.de.Participantes.Inscriptos.en.el.Evento.en.Rosario.a.sumar.en.Club.de.Colocadores.xlsx)

En cuanto a los datos de puntos en la competnecia y numero de participante te los paso por las dudas, por si se pueden sumar, pero sé que el campo no está. Si te complica borrá esas últimas 2 columnas del excel y listo.

abrazo

**Comment by mkreyness** [comment]
y que hago con los que haya "registrados con el mismo mail o sin mail", los cargo igual ?

**Comment by LeandroBraier** [comment]
Si podés hacerlo automáticamente, no los cargues y pasame cuales son. Si es algo manual avisame, te los filtro yo y te mando el excel de vuelta.

**Comment by mkreyness** [comment]
igual por lo que veo son solo 13 tipos los que dieron un email.
Mucho mailing de bienvenida no vas a poder mandar.

**Comment by LeandroBraier** [comment]
Tal cual. Pero si no los mando me retan jeje

**Comment by mkreyness** [comment]
Apenas yo los cargue esos 13 se van a mandar solos. El problema es que todo el resto va a quedar en un estado desactivado, no importa ?

**Comment by LeandroBraier** [comment]
Mejor aun! Genial!

El resto que queden como no confirmados o un estado que, sin mail, les
permite si tienen el usuario entrar. Puede ser?

**Comment by mkreyness** [comment]
puedo cargar los que no tienen mail directamente en ese estado.
Ahora subo todo.

**Comment by mkreyness** [comment]
listo, hubo 4 o 5 que dieron que el DNI ya estaba cargado, y un par de esos eran de los pocos que tenian email.

**Comment by LeandroBraier** [comment]
Gracias MK! No problem. Esos con DNI repetido no se generaron entonces?

**Comment by mkreyness** [comment]
No, no puedo dar de alta DNIs repetidos, me lo rechaza la base.

**Comment by LeandroBraier** [comment]
Ah ok. Porfa decime cuales son estos si se puede.

**Comment by mkreyness** [comment]
Eran 4:
93102274 Sebastian Britos
21690867 Ruben Caiguara 
30686481 Juan Martiniche
32444692 Gustavo Velasco

**Comment by LeandroBraier** [comment]
Gracias Marce!!!

abrazo
