### ISSUE TITLE
Juego Adiviná Banderas para Parex

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#354]
Buen día @valentinsabbath ! Cómo va?

Tenemos que adaptar el Juego Adiviná Banderas que hicimos para VIE TUR para la Comunidad de Vendedores de ParexKlaukol. Acá te paso las 2 imágenes que teníamos que adaptar. Una va en el juego, la del Instructivo la cargo yo en el CMS cuando subas el juego. Confirmame si lo que dice el Instructivo es correcto o tenés que adaptar algo.

![title-sheet0](https://cloud.githubusercontent.com/assets/6719872/17853959/05a13a88-6846-11e6-8484-95625a3ab21a.png)

![instructivo-para-juego---adivina-banderas-parexklaukol](https://cloud.githubusercontent.com/assets/6719872/17853966/0aaec54a-6846-11e6-91b8-fd14e3bb15d0.png)

abrazo

**Comment by ghost** [comment]
@LeandroBraier eran 7 banderas

**Comment by ghost** [comment]
Habría que poner "cada vez que superes las 6 banderas" ...

**Comment by ghost** [comment]
@mkreyness  cómo subo el juego?

**Comment by LeandroBraier** [comment]
Dale, lo modifico al instructivo y lo subo por CMS. @mkreyness le indicás
como subir el juego?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
En Klaukol no hay nada armado como para manejar ESTE tipo de juegos (Javascript), solo lo tuvimos en VIE TUR hasta ahora. 
Seguramente tengo que preparar unas cuantas cosas primero, por ejemplo el template y el tipo de juego.
Despues es cuestion de alojar toda la carpeta del juego en el servidor en una carpeta nueva (/vendedores/juegos/banderas)  y referenciar eso asi como si fuera el URL del video (fijate en VIE TUR esta asi en el Tema).
Pero tengo que implementar primero varias cosas, asi que aguantenme unas horas.

**Comment by LeandroBraier** [comment]
Dale @mkreyness avisame nomás. Puede ser para mañana, estamos bien.

**Comment by mkreyness** [comment]
Bueh, por fin cai en el thread correcto. ACA es donde hay que usar las credenciales de Klaukol para que Valentin cargue el juego de BANDERAS. Repito lo que dije en el lugar equivocado:

@LeandroBraier lo tenes que poner como juego tipo HTML5, igual que el "Coloca con Klaukol".
y al tema ponele como URL DE VIDEO esto: img/vendedores/banderas

**Comment by ghost** [comment]
El juego ya está editado pero no me puedo conectar al server
Acá está 
https://drive.google.com/drive/folders/0B0BybArEfuZoQTJIQklPUTJ6LUE?usp=sharing

**Comment by LeandroBraier** [comment]
Gracias Valen! Ya lo puedo ver en la Comunidad?

**Comment by mkreyness** [comment]
Dado que no lo pudo subir, no lo vas a poder ver.
Ahora yo trato de subirlo y te aviso.

**Comment by mkreyness** [comment]
valen ahi subi lo que me pasaste de Banderas, pero parece ser el proyecto, no el HTML.
Por ejemplo, incluiste un autosave que pesa como 8Mb y un backup que pesa otros 8Mb.
Lo que hay que subir es lo que te genera cuando EXPORTAS el projecto a HTML5, esto no es.
Mira lo que sale: 

http://www.parexklaukol.com.ar/vendedores/img/banderas/

ahi yo tendria que ver un index.html (como ya te dije antes) que se ocupe de mostrarme el juego, no un proyecto para compilar el juego...

**Comment by mkreyness** [comment]
ya esta subido el juego

**Comment by LeandroBraier** [comment]
No lo encuentro @mkreyness Como es el ID?

**Comment by mkreyness** [comment]
Me refiero a que subi la carpeta de Valentin a 

http://www.parexklaukol.com.ar/vendedores/img/banderas/

 la carga de tema/juego pense que lo hacias vos.

**Comment by LeandroBraier** [comment]
Si, claro. Ahí lo probé pero no me lo carga:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=65&usuario=LeandroBraier&clave=parex

Lo puso en el campo de video al URL, está bien?

**Comment by mkreyness** [comment]
En realidad el /vendedores en este caso no iba, porque ya es el club de vendedores, ahi lo cambie a img/banderas/
pero de todos modos ese es el TEMA, yo no encuentro que hayas cargado el JUEGO con tipo HTML5, puede ser ? No lo veo.

**Comment by LeandroBraier** [comment]
Tenés razón. Me faltó el juego. Gracias!

Ahora lo veo funcionando y le cargué el Instructivo.
1. El juego se ve como descentrado y chico puede ser? En VIE TUR logramos ponerlo en mayor tamaño y centrado @valentinsabbath 
2. Consulta: el juego funciona exactamente igual que en VIE TUR, verdad? Si adivinás X banderas en X tiempo te suma puntos todas las veces hasta un tope de 10 veces? Solo para confirmar.
3. El instructivo está subido? Confirmenme la ruta así la subo porfa.

abrazo

**Comment by ghost** [comment]
1-@LeandroBraier todo eso lo manejó Fede, es un tema de maquetación.
2-El juego funciona exactamente igual que en VIE TUR.
3-No se quien tenía que subir el instructivo, por lo pronto habia que cambiar una partecita te acordas?

**Comment by LeandroBraier** [comment]
1- OK. @FAAREIA nos das una mano? Necesito que este juego:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=65

(usuario=LeandroBraier&clave=parex )

se vea como este (maquetativamente hablando):

http://comunidad.vietur.com.ar/cgi-bin/jugar.pl?id=20

(usuario=LBraya02&clave=vietur)

3- Es que va en la carpeta IMG y yo no tengo el acceso. No lo podés subir vos y pasarme la ruta? Te paso acá el instructivo corregido a 6 banderas como habías pedido:

![instructivo-para-juego-adivina-banderas-parexklaukol](https://cloud.githubusercontent.com/assets/6719872/17913115/57734490-696e-11e6-8270-fff452591807.png)

abrazo

**Comment by ghost** [comment]
No pude entrar al server. MK quizás pueda

**Comment by mkreyness** [comment]
2- el juego puede funcionar igual que en VIE TUR, pero lo que pasa con los puntos depende de reglas que hay en Klaukol, que no son las mismas. Eso del tope de 10 veces era porque habia un limite de 10x puntaje, pero aca en Klaukol no hay tal cosa, y si lo hubiera, aplicaria a otros juegos tambien y no creo que quieran eso. Actualmente lo que hay en Klaukol es que nadie gane mas de 100 puntos por el mismo juego.
Definime bien como tiene que ser el caso de este juego y le hago un toqueteo, o si se pudiera definir una politica general mucho mejor.

@valentinsabbath tenemos que solucionar eso de que no podes entrar al server, usaste port 4444 ? Te dio error al desencriptar la private key ?

**Comment by mkreyness** [comment]
ya subi esa imagen. Ahora habria que ponerla como instructivo, no se si el nombre con que quedo es el mejor, pero es lo que salio de bajarla de aca.

http://www.parexklaukol.com.ar/vendedores/img/57734490-696e-11e6-8270-fff452591807.png

**Comment by LeandroBraier** [comment]
Gracias MK! No es lo ideal lo del nombre de la imagen pero ya fue. Lo pruebo.

En cuanto a los juegos, todos tienen un tope de 100 puntos decís? Entonces en este caso particular subamos el tope a 2000 puntos y listo. Así puede sumar 200 puntos 10 veces. Está bien así?

**Comment by LeandroBraier** [comment]
Faltaría que @FAAREIA ajuste lo de la maquetación para que se vea más grande, como en la Comunidad VIE TUR.

**Comment by mkreyness** [comment]
Tengo tambien que tocar el programa para que maneje un template SEPARADO en este juego, ya que el template que usamos para juegos "tipo HTML5" se usa en otros y se verian feo.
Ya lo hablamos con @FAAREIA

**Comment by FAAREIA** [comment]
Ahi cree el template `juego-html5-verticalT.html`, ss una copia del `juego-html5T.html` y al juego le deje esos margenes en negro porque sino es muy vertical y puede que no entre en pantalla.
Abrazo

**Comment by mkreyness** [comment]
ahi toque el programa para que en este caso use ese template.

**Comment by mkreyness** [comment]
pero algo se rompio en el template, miren:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=65
usuario=LeandroBraier&clave=parex

**Comment by LeandroBraier** [comment]
juju es cierto. Se hizo pelota.

**Comment by FAAREIA** [comment]
Ahi esta listo, era un div mal cerrado ^^
Abrazo

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !! Quedó todo entonces! Gracias a los 3!! abrazo

**Comment by mkreyness** [comment]
el juego no esta llamando a sumapuntos.pl sino a "sumapuntosbanderas.pl" @valentinsabbath 
Yo ahora lo voy a copiar, pero siempre fijate que es lo que esta llamando, porque cada cosa custom es siempre un posible error.

**Comment by mkreyness** [comment]
y cuando lo jugabas una vez ya lo daba por jugado y no volvia a sumar puntos, ya arregle eso (que es un tema separado que despues de los 2000 no siga sumando). Habria que probarlo bien, yo jugue ya 4 veces con usuario LeandroBraier (ganando siempre) y me tiene harto. Por favor sigan ustedes porque yo me tengo que ir. La meta es que despues de los 2000 no siga sumando.
