### ISSUE TITLE
Donde se guardan los datos de contacto de Revear?

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#355]
@mkreyness una consulta: podemos guardanos los datos que pasan por este formulario de la nueva web de Revear?

http://www.revear.com.ar/contacto.php

Solo esa consulta. Me servirían poder ver los datos en el CMS si se pudiera, porque no recuerdo a donde llevaba el formulario. Si envia un mail al mail de Parex, se podrá hacer que nos llegue una copia a nosotros al menos?

**Comment by mkreyness** [comment]
Ese formulario seguramente solo manda un mail, pero puedo agregarle (con un poco de trabajo) que grabe en la base de datos y despues accederlo por CMS, pero si queres como cosa rapida le agrego que haga Bcc: a la direccion que vos me digas.

**Comment by LeandroBraier** [comment]
Dale perfecto. Que mande un bcc a revearparex@gmail.com y listo. Con eso me
arreglo por ahora. Si en el futuro se puede exportar por CMS mejor.

2016-08-22 11:43 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
listo. El receptor original es un tal claudio.guisasola@klaukol.parex.com
Teoricamente si ingresas una prueba le va a llegar a el y tambien a esta direccion que me pasaste, probalo.

**Comment by LeandroBraier** [comment]
@mkreyness estoy probando cargar pero en la lista desplegable de "Provincia" no aparece CABA y en la lista de Localidad para la Provincia de Buenos Aires no aparece nada. Te fijás qué pasa?

**Comment by LeandroBraier** [comment]
Buen día @mkreyness cuando puedas te fijás qué pasa acá?

**Comment by mkreyness** [comment]
Sorry no habia visto este ticket ayer.
Lo que "pasa aca" es que ese formulario no es mio, es un php que armó Fede en base a algun mockup y quedó asi, acordate justamente que no se guardan los datos, etc. etc.
no tiene ningun "autocompletar" de localidades, y la lista de provincias no es la de mi base de datos, esta hardcoded ahi.
Habria que reemplazarlo por un template de los de siempre + programa de verdad que guarde los datos + agregarle autocompletar.
Ahi de parche le agregue CABA, pero igual hay que rehacer todo.

**Comment by LeandroBraier** [comment]
mmm ok. Importante esto. Entonces le pido a Fede que rehaga el formulario?

**Comment by mkreyness** [comment]
No, yo me puedo arreglar con esto, pero no hasta la tarde cuando vuelvo.

**Comment by LeandroBraier** [comment]
ah, todo bien. Tranqui a la tarde, no hay tanto apuro.

**Comment by mkreyness** [comment]
Aca ya tenes (no esta puesto todavia desde la home) el link para el formulario que SI graba datos en una base, y NO manda ese mail (despues voy a poner un robot que cada tanto mire las altas y mande los mails) pero se pueden consultar desde el CMS.

http://www.revear.com.ar/cgi-bin/contacto.pl

Lo que todavia no tiene es el autocompletar de localidades (en realidad en ningun lugar de ParexKlaukol tenemos eso de las localidades, lo tendria que copiar de VIE TUR) pero por lo menos se puede tipear algo, antes no se podia ni eso. Vale la pena ponerle el autocompletar ?

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Ahi lo probé. No hace falta el autocompletar. Ya me hice una prueba para ver si funciona y no me llegó aún a RevearParex. Puede tener una demora? Entre ayer y hoy me llegaron 10 mensajes del form a esa casilla.

**Comment by mkreyness** [comment]
Lee lo que yo escribi, puse "NO", en mayusculas, NO manda el mail todavia.
Tengo que armar un proceso en batch que "cada tanto mire las altas y mande los mails) pero se pueden consultar desde el CMS."
O sea, por ahora solo podes consultarlos desde el CMS.
Yo ahora me estoy yendo y a la noche completo lo del envio de mails.

**Comment by mkreyness** [comment]
Y acordate que esto no esta operativo para la gente, si te llegan mails es porque estan escribiendo en el form viejo, que apenas estemos seguros de que este anda bien, lo reemplazo.

**Comment by LeandroBraier** [comment]
Ah, perfecto. Entiendo, perdón! La cabeza no lee todo ultimamente.

Ahi lo vi en CMS perfecto!!! Apenas ande el envío de mails al señor original y a revearparex lo pasamos a producción entonces.

abrazo y gracias!

**Comment by mkreyness** [comment]
Si, primero para probar por supuesto NO voy a poner al señor original.

**Comment by LeandroBraier** [comment]
jajaj por supuesto. Gracias!

**Comment by mkreyness** [comment]
ya quedo andando el robot que manda los mails, solo a revearparex@gmail.com por ahora.
Ahora van a llegar nuestras dos pruebas.
Si queres cargar con el URL que te pase mas, en el orden de los 7 minutos te llega el mail a revearparex@gmail.com.

**Comment by mkreyness** [comment]
si te parece todo OK, paso a produccion el formulario y le agrego ese address al envio de mail

**Comment by LeandroBraier** [comment]
Buen dia MK: Pasalo a producción y agrega el address nomas. Gracias!

**Comment by mkreyness** [comment]
listo ya esta todo pasado a produccion, la direccion de envio es la de guisasola y la de gmail esta como bcc, si queres hacete alguna prueba, sabiendo que le va a llegar a guisasola.

**Comment by LeandroBraier** [comment]
Gracias MK!!! Ahi probé y en 7 min debería llegar. CUalquier cosa te aviso.
abrazo

2016-08-24 9:59 GMT-03:00 mkreyness notifications@github.com:
