### ISSUE TITLE
Reemplazar Fichas técnicas Revear 06-09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#356]
@FAAREIA algunos productos tienen actualizaciones de sus fichas técnicas. Te paso aquí las nuevas para reemplazarlas en la web. Avisame cuando esté hecho porfa.

[FICHAS TECNICAS REVEAR A ACTUALIZAR.zip](https://github.com/LeandroBraier/Klaukol/files/452854/FICHAS.TECNICAS.REVEAR.A.ACTUALIZAR.zip)

abrazo

**Comment by FAAREIA** [comment]
Pregunta
Eso no se sube por CMS?
Si es por CMS pasame usuario y clave

**Comment by mkreyness** [comment]
No hay UPLOAD de eso via CMS, porque son links a URLs que pueden ser cualquier cosa, no tienen upload porque no tienen una carpeta fija definida.
Si los archivos se llaman igual, hay que reemplazarlos en las carpetas que ahora estan, y no hay que tocar nada en el CMS. Si los archivos se llaman distinto, hay que actualizar el URL en el CMS.

**Comment by LeandroBraier** [comment]
Buen día chicos!

No se llaman igual los PDF. 

@FAAREIA , pasame las URL de estos nuevos y yo la subo por CMS al producto correspondiente a cada una.

abrazo

**Comment by FAAREIA** [comment]
http://revear.com.ar/docs/classic-stone-ficha-tecnica.pdf
http://revear.com.ar/docs/marble-ficha-tecnica.pdf
http://revear.com.ar/docs/natural-stone-ficha-tecnica.pdf
http://revear.com.ar/docs/revex-ficha-tecnica.pdf
http://revear.com.ar/docs/revoque-plastico-fino-flexible-ficha-tecnica.pdf
http://revear.com.ar/docs/stone-rodillo-ficha-tecnica.pdf

**Comment by LeandroBraier** [comment]
Gracias!
