### ISSUE TITLE
Newsletter Septiembre ParexKlaukol. 06/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#357]
Buen día @FAAREIA !

Te paso los contenidos para el news de Septiembre. Confirmame si llegás para mañana a armarlo.

[Contenido Newsletter ParexKlaukol SEPTIEMBRE a maquetar 04-09.docx](https://github.com/LeandroBraier/Klaukol/files/454976/Contenido.Newsletter.ParexKlaukol.SEPTIEMBRE.a.maquetar.04-09.docx)

[Imagenes Newsletter SEPTIEMBRE.zip](https://github.com/LeandroBraier/Klaukol/files/454977/Imagenes.Newsletter.SEPTIEMBRE.zip)

Ya incluyo imágenes, links y todo lo que necesitás. Hay imágenes demás por las dudas. Cualquier duda avisame.

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-09/16-09-P.html

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Solo dos ajustes:

1) En la encuesta, falta el tilde en "época" y en "elegís"

2) El link de Tendiez no anda. Cambialo por este: http://www.parexklaukol.com.ar/novedades/4to-encuentro-tendiez-2016-cordoba.html

3) La foto de "portada" y los logos de arriba de ella no linkean a ningún lado. Poneles un link invisible por las dudas si alguien clickea que vaya a: http://www.parexklaukol.com.ar/novedades.html

Solo eso. Gracias!

**Comment by FAAREIA** [comment]
Hecho dale F5, a las marcas les puse sus respectivos links.

**Comment by LeandroBraier** [comment]
Impecable Fede!! Muchas gracias!

Te aviso cuando tengo feedback.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA el cliente pidió un par de ajustes muy mínimos.

1) Cambiar el título "Últimas tendencias y novedosos diseños de exteriores" por "Últimas tendencias y novedosos diseños de exteriores"

El link corregido sería: http://www.parexklaukol.com.ar/novedades/ultimas-tendencias-y-novedosos-disenos-de-exteriores.html

2) Cambiar el producto Parex Decoflex Terminación Final por Parex Decoflex Rulato Travertino

El link sería este: http://www.parexklaukol.com.ar/parex/parex-decoflex-rulato-travertino.html

**Comment by FAAREIA** [comment]
Hace un rato se cayó el servidor parece, cuando vuelva hago los cambios Lea

**Comment by LeandroBraier** [comment]
Ahi lo vi. Te aviso cuando esté.

**Comment by LeandroBraier** [comment]
@FAAREIA ya está solucionado lo del hosting!

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Puede ser que otra vez esté caído el hosting? No puedo entrar a ninguna de las páginas.

**Comment by LeandroBraier** [comment]
Ahí ya está entrando, disculpá.

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Enviado! abrazo

**Comment by FAAREIA** [comment]
Lea, ese no lo envies, espera que te lo paso bien con los estilos inline

**Comment by FAAREIA** [comment]
Este es el link final:
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-09/16-09.html

**Comment by LeandroBraier** [comment]
Enviado @FAAREIA ! Para el mes que viene podrás investigar un poco si se puede mejorar un poco el diseño para adaptarlo más a mobile vertical? Por ejemplo, podríamos buscar fotos verticales nosotros, no hay problema por eso, pero en celus verticales cuesta leerlo, medio que te obliga a abrirlo horizontal y el mobile está creciendo muchísimo, ya casi que supera a las aperturas de compu.

abrazo

**Comment by FAAREIA** [comment]
Se puede sacar el ancho fijo y que quede a la "deriva" el tema es que va a comprimirse el contenido, nada va a pasar de tener 2 columnas a 1 columna debajo de otra como suele hacerce en lo responsivo.
Sin embargo, hace unos meses, buscando y buscando, encontré 2 artículos que daban estadísticas de como aplicar lo responsivo a los mailing. El tema es que casi todos ignoran la directiva, excepto iphone y en algunos modelos. Tampoco pude aplicalo ni probarlo por la falta de tiempo.

**Comment by LeandroBraier** [comment]
Dale, está bueno eso. Para el próximo news, el de Octubre, apliquémoslo.

Los que armo yo con mailchimp se adaptan perfecto. Le meto una imagen de
1000x de ancho ponele y se adapta bien para mobile. No queda scroll a los
costados. TIene que haber alguna forma no tan compleja.

Ahora te reenvio uno de esos por si te sirve de inspiración.

abrazo

2016-09-09 17:04 GMT-03:00 Federico Arena notifications@github.com:
