### ISSUE TITLE
Actualizar Ficha Técnicas Grandes Piezas Porcellanato. 06/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#358]
@FAAREIA cuando puedas reemplazá esta ficha técnica por la que tiene ahora el producto:

[FT_Klaukol_Grandes_Piezas_Porcellanato.pdf](https://github.com/LeandroBraier/Klaukol/files/455452/FT_Klaukol_Grandes_Piezas_Porcellanato.pdf)

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
