### ISSUE TITLE
Bug en Carga de Imágenes en Novedades

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#359]
@mkreyness estamos teniendo problemas al cargar imágenes en novedades tanto en Parex como Revear (mismo CMS)

Revisás porfa qué pasa? 

Caso de ejemplo: En la nota "Ahorrá en la factura: reducí el gasto energético con un diseño adecuado" en Revear cargué varias veces los campos de "Imagen" e "Imagen Grande" y nada. Da error. 

Te fijás porfa? Porque nos está pasando en novedades parexklaukol también.

**Comment by mkreyness** [comment]
acabo de subir yo dos fotos cualquiera en esos campos sin ningun problema (en la noticia de "ahorra en la factura".

**Comment by LeandroBraier** [comment]
Puede ser que tenga tildes la imagen? me acabo de dar cuenta de eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ni idea porque ya los pise, pero seguro que se rompe tratar de uploadear un archivo con un nombre non-safe.

**Comment by LeandroBraier** [comment]
Perdón Marce. Ya lo pude resolver a eso. Ahora me encuentro con otro bug, este parece ser real.

Publico y la nota y aparece en el listado de Tendencias, pero el link falla:

http://www.revear.com.ar/tendencias/particular/ahorra-en-la-factura--reduci-el-gasto-energetico-con-un-diseno-adecuado.html

Te fijás qué puede ser?

Aprovecho a consultar. La tendencia que aparece en la Home se actualiza sola o hay que pedirle a Fede especialmente?

**Comment by mkreyness** [comment]
A que te referis con que el link falla ? Hice click ahi y me lo mostro perfecto.
Nada es inmediato, el proceso que regenera todo corre cada 5 minutos.
Dentro del momento que se regenera puede que este primero la lista de Tendencias y despues la nota en si, pero se ajusta en segundos.

**Comment by mkreyness** [comment]
lo que veo que queda horrible es que ya hay demasiadas "etiquetas", y sale todo superpuesto en esa parte.

**Comment by mkreyness** [comment]
justamente donde no aparece es al hacer click en la etiqueta, debe tener que ver con los acentos. Me fijo.

**Comment by mkreyness** [comment]
Lean, las etiquetas van separadas por PUNTOYCOMA, no por COMA. Por eso andan mal.

**Comment by mkreyness** [comment]
Fijate las primeras novedades cargadas, las tienen (correctamente) cargadas con la separacion con puntoycoma.

**Comment by LeandroBraier** [comment]
Me refiero a que, si tarda en generar el link, debería tardar lo mismo en mostrar como publicada la nota. Si entra un usuario justo en el mientras tanto queda en la nada. No se puede resolver eso? 

Lo de las etiquetas ya lo corregí, es un chino acordarse de eso. Si se pudiera mejorar para que lo tome de ambas formas mejor. Sino hacer un campo por etiqueta?

**Comment by mkreyness** [comment]
Deberia ser todo suficientemente instantaneo, eso depende de la performance del server y la cantidad de cosas a procesar. Puedo ver si cambiando el orden en que se procesa esto se evita, pero hay cosas que se apuntan mutuamente, asi que no se si es realmente factible.

Se usó puntoycoma porque asi me lo habia pasado Fede cuando armaron los datos en base al sitio viejo de Klaukol, yo respete esa convención, creo.
La ventaja del puntoycoma es que podes armar etiquetas que incluyan comas, por ejemplo:
"Hugo, Paco y Luis; El Pato Donald; Mickey y Pluto"
Si usaras coma, "Hugo" se separaira de "Paco y Luis'.

**Comment by LeandroBraier** [comment]
Ok, entiendo Mk. Dejemoslo así por ahora entonces. abrazo
