### ISSUE TITLE
Cambios en Productos ParexParaguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#36]
Fede, te subí a BENTEVEO MAQUETADOR/ KLAUKOL/ WEB PARAGUAY un ppt con cambios y agregados en la parte de productos de la Web de PAraguay. Es muy puntual y simple. Cualquier duda me consultás. Esto tendría que estar para lunes o martes que viene.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Excelente Fede y MK! Gracias!
