### ISSUE TITLE
Bug en Productos Parex Paraguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#360]
@mkreyness te fijás por qué en Parex Paraguay cargué un producto del sitio de Argentina y no me levanta ninguna imagen?

El producto es:
**Adhesivo Klaukol Grandes Piezas Porcellanato para la colocación de porcellanatos** 

Supongo que tiene que ver con tema rutas, pero decime así sé como agregar futuros productos.

**Comment by mkreyness** [comment]
PATY Paraguay ??? 
Lo que pasa es que lo que copiaste es un URL que es relativo al sitio, si dentro del sitio de Paraguay (que esta separado del sitio de Argentina, aunque este todo en el mismo server) hay que copiar el producto fisicamente dentro del server a la carpeta de Paraguay, que capaz nisiquiera tiene la misma estructura.

**Comment by LeandroBraier** [comment]
Bueno, a eso me refiero. Cómo hago para agregar ese producto? O no se puede por CMS?

Se lo pido a @FAAREIA ?

**Comment by mkreyness** [comment]
El CMS de Klaukol no hace upload de imagenes, porque se hizo basado en el backup, nadie los cargo a mano. Al tener que agregar a mano, hay que meterlos dentro de esa estructura de backup.

**Comment by mkreyness** [comment]
O sea, si, es del tipo de cosas que soles pedirle a @FAAREIA

**Comment by LeandroBraier** [comment]
OK, pero ves posible que hagamos el cambio para que hagamos que pueda subir productos a través de CMS?

**Comment by mkreyness** [comment]
Para eso primero hay que relocalizar manualmente todos los que ahora estan desperdigados, en una UNICA carpeta por marca/pais. Una vez que haya un sitio unico, puedo cambiarlo de URL a boton de upload y mostrarlo como en cualquier otro CMS.
Pero eso hay que hacerlo sin que se rompa el sitio, o sea, copiar, no mover.
Es un laburo chino.

**Comment by LeandroBraier** [comment]
Ok, dejemoslo por ahora entonces. Ya cuando migremos el sitio lo vamos a tener que hacer de alguna forma.
