### ISSUE TITLE
Sumar Producto Klaukol Grandes Piezas Porcellanato en Parex Paraguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#361]
@FAAREIA necesito subir este producto a Paraguay tal como está en Argentina. Yo creé el producto en el CMS con todo igual que en Argentina pero no funcionó por tema de rutas. Quizá te sirve eso, sino borralo.

Lo que necesito es que esté subido igual que en Argentina.

**Comment by mkreyness** [comment]
Es al reves, @FAAREIA lo tiene que poner en el mismo lado que estan las otras cosas de Paraguay y pasarte la ruta definitiva donde quedo, para que lo pongas en el CMS.
Yo sugiero como hicimos con los Guazukol que van a la carpeta "/home/parexkla/www/_parex/img/productos-py"  y por lo tanto en el URL solo le tenes que poner img/<nombre del archivo> ya que internamente 
parexparaguay.com.py/img apunta a esa carpeta "/home/parexkla/www/_parex/img/productos-py"

**Comment by LeandroBraier** [comment]
Ok, hagan lo que tengan que hacer y pasenme el instructivo claro de qué subo, no hay problema.

**Comment by mkreyness** [comment]
si me decis el nombre del archivo (de imagen) te lo hago yo en un segundo.

**Comment by LeandroBraier** [comment]
Dale, gracias! Te paso las rutas que copié y pegué de Argentina. Acá tenés los nombres de imagenes también no?

/media/catalog/product/cache/1/small_image/75x/9df78eab33525d08d6e5fb8d27136e95/3/d/3d_grandes_piezas_porcellanato_izq.png

/media/catalog/product/cache/1/thumbnail/150x150/9df78eab33525d08d6e5fb8d27136e95/3/d/3d_grandes_piezas_porcellanato_izq.png

Las rutas de la ficha técnica y hoja de seguridad te las paso también porque no andan:

/pdf/productos/klaukol-grandes-piezas-porcellanato-ficha-tecnica.pdf

hojas-de-seguridad/HS-Klaukol-Grandes-Piezas.pdf

abrazo

**Comment by mkreyness** [comment]
claro el problema es que ambas imagenes se llaman igual, porque en el viejo sistema tenaian carpetas separadas por tamaño.
Necesariamente le voy a tener que cambiar el nombre a una de ellas

**Comment by LeandroBraier** [comment]
No problem. Pasame las rutas finales y yo me arreglo, todo bien.

**Comment by mkreyness** [comment]
tenes que poner: 
img/grandes_piezas_porcellanato_izq-150x.png
en la imagen grande y
img/grandes_piezas_porcellanato_izq-75x.png
en la chica.
Fijate si eso te anda bien y veo lo de los adjuntos.

**Comment by LeandroBraier** [comment]
Parece que funcionaron! Probé ahora en Galería, que se muestra donde dice "imágenes" y no aparece. Me confirmás si ahí va la misma o no?

http://www.parexparaguay.com.py/klaukol/adhesivo-klaukol-grandes-piezas-porcellanato-para-la-colocacion-de-porcellanatos.html

**Comment by FAAREIA** [comment]
Avisen si necesitan de mi

**Comment by mkreyness** [comment]
Seria lo que en la pagina se muestra como "multimedia" ? Si, teoricamente si pones el mismo URL tambien aparecerian, yo de hecho estoy viendo el thumbnail como parte de la galeria, se ve chiquito.

**Comment by LeandroBraier** [comment]
Está bien, pero es eso lo que aparece. Cuando puedas pasame ruta de la FT y la Hoja de seguridad y estamos.

Gracias!

**Comment by mkreyness** [comment]
Ahi copie eso en los mismos lugares (pero paraguayos) que los de Klaukol. Si copias los mismos paths en los URLs deberian andar.

**Comment by LeandroBraier** [comment]
ANdóoo!! Andóoo!! Gracias Marce!!! jeje

abrazo grande
