### ISSUE TITLE
Club de Colocadores: Sumar Actividad de Colocadores con Datos de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#362]
@mkreyness necesitaría poder exportar en el Club de Colocadores un excel como el de la Comunidad de Vendedores que diga el listado de actividades pero con todos los datos del vendedores que las hizo. 

Lo podrás sumar para mañana porfa?

**Comment by mkreyness** [comment]
ok

**Comment by mkreyness** [comment]
esto listo

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by LeandroBraier** [comment]
@mkreyness no se podrá incluir que exporte el número de socio también? Me lo había pedido el cliente y pensé que lo incluías.

Puede ser para mañana tranqui.

**Comment by mkreyness** [comment]
Es la segunda columna, la que dice "Legajo".

**Comment by mkreyness** [comment]
pero sale mal, ahora la arreglo.

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias MK!!!

Ahora si!!

abrazo
