### ISSUE TITLE
Envio de Mailing de Bienvenida Vendedores a Ana

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#363]
@mkreyness tengo una nueva usuaria en la Comunidad de Vendedores. Necesito que le gatilles el mail de bienvenida solo a ella. Podrá ser?

Mailing: http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Código: apcheuquel
Password: klaukol
mail: apcheuquel@yahoo.com.ar

Confirmame si podés enviarlo o programarlo para mañana a la mañana.

abrazo

**Comment by LeandroBraier** [comment]
Es importantísimo el tema porque es el mail del cliente directamente.

**Comment by mkreyness** [comment]
los mails de bienvenida salen automaticos, para todo nuevo usuario registrado, como se registró ?

**Comment by mkreyness** [comment]
ah, no, no es automatico porque no hay como registrarse, se supone que cuando me mandan una lista de nuevos para cargar, yo corro el proceso que les manda.
Estan cargando usuarios a mano por el CMS ?
Igual el usuario de ella figura en estado ACTIVO, por lo tanto no le saldria el mail.
Si queres que a ella (y al resto de los que esten en estado "MANDAR MAIL") les mande, la paso a ese estado y le mando a todos (son unos 15).

**Comment by LeandroBraier** [comment]
Si la cargue en el cms yo.

Cambiale el estado y mandale solo a ella porfa.

**Comment by mkreyness** [comment]
pero el resto como se dio de alta ? Es raro.
Pongo a los otros como activos para que no salgan.

**Comment by mkreyness** [comment]
Son estos los otros, todos cargados seguidos
petisa68@hotmail.com  
corralonelaleman@hotmail.com
veronicals@hotmail.com  
delcysandoval@hotmail.com  
victoriariverola@hotmail.es 
carinapottier@hotmail.com  
ceciliapottier@hotmail.com  
hujito77@hotmail.com  
eduardobetancort@hotmail.com
maty_haro@hotmail.com  
betancortd@gmail.com  
s_bilat@hotmail.com  
m.betancort@hotmail.es  
antoneeligus@hotmail.com

**Comment by mkreyness** [comment]
listo, todos esos estan ahora activos, y salio el mail para apcheuquel  (y volvio a estar activa)

**Comment by LeandroBraier** [comment]
Excelente MK. Gracias!

Los subi yo a esos y me debo haber olvidado de pedirte que les mandes el
mailing de bienvenida supongo. Aunque creo que lo mandé desde mailchimp. Lo
reviso después y te digo. Gracias MK!
