### ISSUE TITLE
Poder ordenar y ocultar los temas de Comunidad de Vendedores. 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#364]
@mkreyness cuando puedas, sin apuro, necesito poder definir el orden de los "temas" de la Comunidad de Vendedores a través del CMS. Lo que ya hacemos en la Comunidad VIE TUR.

Cuando puedas, sin apuro.

abrazo

**Comment by mkreyness** [comment]
No recordaba haber agregado un campo de numero de orden en VIE TUR, pero eso es lo que habria que hacer, no ?

**Comment by LeandroBraier** [comment]
Exacto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
MK, avisame porfa cuando esté.

**Comment by LeandroBraier** [comment]
@mkreyness cuando puedas tocar esto porfa avanzá. Aprovecho y te pido una cosita más: se puede hacer que los juegos que ya están hechos queden siempre abajo de la lista y los que están por hacer queden arriba? (esto sería diferente para cada usuario, por eso te lo consulto aparte).

**Comment by mkreyness** [comment]
Estoy a full con las cosas de SiguitDS, si esto se volvio urgente lo puedo tratar de hacer en algun hueco.
Si, se podria hacer que la pagina de juegos reordene siempre los juegos SIN JUGAR arriba, y los jugados abajo, y a su vez dentro de los SIN JUGAR poner mas arriba los mas nuevos, con eso ni seria necesario eso de que haya un campo de ordenamiento general, o si ?

**Comment by LeandroBraier** [comment]
Claro, eso sería una solución mejor aún. No es tan urgente, pero tampoco lo dejemos para cuando Siguit esté terminado. Si puede estar en algún momento de la semana que viene genial. Es algo que me pidió el cliente y tengo reunión con ellos el jueves. Para que no me lo reclamen.

**Comment by mkreyness** [comment]
fijate asi (poniendo un "2" despues de "vendedores"
http://www.parexklaukol.com.ar/cgi-bin/juegosvendedores2.pl

(usuario=marcelokreyness&clave=pepe)

si te parece bien, lo paso a producccion (le saco el "2").

**Comment by LeandroBraier** [comment]
Perfecto así! Pasalo a producción nomás.

abrazo

**Comment by mkreyness** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Muchísimas gracias @mkreyness !
