### ISSUE TITLE
Bug en Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#365]
@mkreyness dos problemas con la carga de trivias:

1) Estaba cargando una trivia en Club de Colocadores y me pasó esto:

http://www.parexklaukol.com.ar/cgi-bin/jugarcolo.pl?id=28&usuario=marcelokreyness&clave=pepe

Ya había probado con distintas imagenes y funcionaba bien, pero ahora me aparece el 404.

2) Al intentar subir un link como "documentación" me aparece este bug:

`select id,des from`jue_clc`order by des:Unknown column 'des' in 'field list'
`

<img width="1640" alt="captura de pantalla 2016-09-16 a las 2 55 25 p m" src="https://cloud.githubusercontent.com/assets/6719872/18595143/d1fae50c-7c19-11e6-8152-aa442753ff8e.png">

Podrás solucionar estos 2 temas hoy? Lo necesito cuanto antes.

**Comment by mkreyness** [comment]
lo primero es que hay un "!" al final del nombre del Jpg, eso seguro que no puede funcionar, volvelo a subir sin eso.
Lo otro apenas llego lo reviso, seguramente nunca se usó y quedó algo mal copiado de los archivos de vendedores.

**Comment by LeandroBraier** [comment]
Donde ves el "!" ?

El nombre es este:

cuanto-sabes-de-parex-decoflex-colocadoresx650.jpg

**Comment by mkreyness** [comment]
en esta frase de error que sale:

The requested URL /colocadores/img/temas/cuanto-sabes-de-parex-decoflex-colocadoresx650.jpg! was not found on this server.

**Comment by LeandroBraier** [comment]
Hay ok pero yo no puedo cambiar eso. Lo suma el mensaje de error.

**Comment by mkreyness** [comment]
No, el mensaje de error no puede estar agregando eso. Habia un "!" de mas en el template, ya lo arregle, pero estas usando un lugar que es un player de video para poner una imagen, no parece estar muy bien eso.

**Comment by mkreyness** [comment]
ya esta arreglado el segundo tema.

**Comment by LeandroBraier** [comment]
Ahora si, perfecto MK. Gracias!!
