### ISSUE TITLE
2 nuevos productos a Parex Paraguay

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#366]
@FAAREIA ya creé en el CMS las entradas para estos dos nuevos productos. Necesito que vos subas las imágenes y fichas técnicas y me los cargues o me pases las URL y yo las cargo.

**Guazurevok Exterior**

Imagen:

![muestra guazu exterior alpha0005](https://cloud.githubusercontent.com/assets/6719872/18638148/7001b580-7e65-11e6-86d8-c5ed9cfe99d2.png)

Ficha técnica:

[Orig_fichatecnica-guazurevok-parexparaguay.pdf](https://github.com/LeandroBraier/Klaukol/files/480464/Orig_fichatecnica-guazurevok-parexparaguay.pdf)

**Guazurevok Interior**

![muestra guazu exterior alpha0005](https://cloud.githubusercontent.com/assets/6719872/18638152/77a73cc4-7e65-11e6-8b06-27281bbb25ce.png)

Ficha técnica: Es la misma que el producto anterior, están juntas.

abrazo

**Comment by FAAREIA** [comment]
Link único para la ficha porque es la misma:
http://www.parexparaguay.com.py/bkps/parexparaguay.com.py/media/custom/upload/guazurevok.pdf

Link a las fotos pero fijate que son las mismas, las dos dicen EXTERIOR:
http://www.parexparaguay.com.py/bkps/parexparaguay.com.py/img/guazurevok-exterior.jpg
http://www.parexparaguay.com.py/bkps/parexparaguay.com.py/img/guazurevok-interior.jpg

**Comment by LeandroBraier** [comment]
Perdón @FAAREIA ! Gracis por avisar. Te paso acá la de interior entonces así me la subís también porfa.

![muestra guazu interior alpha0005](https://cloud.githubusercontent.com/assets/6719872/18648193/ee9b58f4-7e8f-11e6-9fd5-655540afdf33.png)

abrazo

**Comment by FAAREIA** [comment]
Ahi la actualicé

**Comment by LeandroBraier** [comment]
Gracias Fede!!!

**Comment by LeandroBraier** [comment]
@FAAREIA no funcionan los links en la web, te fijás pr qué? Me parece que el cms le agrega rutas que enquilomban.

Te fijás porfa? 

http://www.parexparaguay.com.py/parex/guazurevok-exterior.html

**Comment by LeandroBraier** [comment]
@FAAREIA pudiste ver esto?

**Comment by LeandroBraier** [comment]
@mkreyness me ayudás con esto porfa? @FAAREIA no responde y es una pavada. Se ve que subió las imágenes al lugar incorrecto en el hosting.

**Comment by mkreyness** [comment]
es que no tenes que incluir "bkps/parexparaguay.com.py/", eso ya es "paraguay".  Ahi se lo saque a todo lo de "exterior"
El problema es que mientras siga "suspendido", la pagina no se va a regenerar. Lo tuve que poner "a publicar" para poder verlo.
De todos modos hay cosas mal, el color gris no existe (hay algo que se llama "gray" pero no se si es lo mismo, yo ni siquiera lo veo gris) y la imagen se pisa feo con los textos (creo que es demasiado grande)

**Comment by mkreyness** [comment]
Fede los subio bien, pero estaban mal referenciados desde el CMS.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! 

Creo que no me habían explicado que se cargaban así en Paraguay. Fijate que la ficha técnica sigue sin verse. Le cambié la URL a una y tampoco.

1) Acá te paso Fede las imágenes adaptadas al tamaño correcto:

Thumbnails
![guazurevok-interior-thumbnail](https://cloud.githubusercontent.com/assets/6719872/18693870/afe514aa-7f7b-11e6-92ab-224e25c14a3d.png)
![guazurevok-exterior-thumbnail](https://cloud.githubusercontent.com/assets/6719872/18693872/b428b40e-7f7b-11e6-834c-2e94718dc3ae.png)

Imagenes
![guazurevok-interior](https://cloud.githubusercontent.com/assets/6719872/18693875/b913159a-7f7b-11e6-9acb-2e4bd3421e6e.png)
![guazurevok-exterior](https://cloud.githubusercontent.com/assets/6719872/18693877/bc5e9346-7f7b-11e6-9321-0834f5216f23.png)

Conserven los nombres de las imagenes y avisenme cuando estén reemplazas en la carpeta IMG avisenme porfa.

2) @mkreyness No hay una forma de hacer más intuitivo esto? Sé que ya lo pregunté, pero hacerlo de una vez seguro lleva menos tiempo a todos y menor riesgo que demorar una semana en subir un nuevo producto a la web.

abrazo

**Comment by mkreyness** [comment]
Ya te explique otras veces, el problema es que todo el contenido esta desperdigado por mil carpetas y encima los archivos tienen nombres repetidos, porque el tamaño esta representado por el nombre DE LA CARPETA en que esta, y no por el nombre del archivo.
Para poder unificar todo como corresponde alguien se tiene que poner a rearmar todo poniendole nombres diferentes para que puedan convivir en una misma carpeta. Podemos abrirlo por pais y marca, pero no por tamaño, ya que todo lo que esta en una misma pantalla del CMS tiene que ir a una misma carpeta.
Una vez hecho ese laburito, hay que actualizar todos los nombres en el CMS (SIN el nombre de la carpeta), hacer unos ajustes de programacion para que sepa a que carpeta corresponde cada pantalla, y finalmente tocar todos los programas que en base a templates arman las paginas finales para que se regeneren las paginas bien. 
Es casi como una migracion, yo lo haria, pero cuando migremos a otro server.

**Comment by LeandroBraier** [comment]
Ok @mkreyness Entiendo. LO incluyo en el proceso de migración del sitio.

En cuanto a estos productos puntualmente, cuando van a estar subidos?

**Comment by mkreyness** [comment]
No hice nada con esas nuevas inagenes porque le hablabas a Fede, si no lo hago a la tarde

**Comment by LeandroBraier** [comment]
jeje le sigo hablando a @FAAREIA en realidad, pero no me responde jeje

**Comment by FAAREIA** [comment]
Ahi me meto con eso, ayer me saqué una muela y cuando volví no tenia internet =/

**Comment by LeandroBraier** [comment]
jejeje son cosas que pasan cuando te sacás una muela jejje Gracias! Y tomá mucho helado!

**Comment by FAAREIA** [comment]
La verdad estoy medio perdido con esto de los paths, me confunde bastante.
@LeandroBraier los nombres de las imágenes no puedo mantenerlos porque cuando subis a algo github el nombre te lo cambia por algo como `bc5e9346-7f7b-11e6-9321-0834f5216f23.png`

Links como me parece que deberían ir en el CMS para que en la web los tome:
img/productos-py/guazurevok-exterior.jpg
img/productos-py/guazurevok-exterior-150x150.jpg
img/productos-py/guazurevok-interior.jpg
img/productos-py/guazurevok-interior-150x150.jpg

PDF
/bkps/parexparaguay.com.py/media/custom/upload/guazurevok.pdf

Si los probas y no andan habría que hacer que los chequee marce, pero los probé y anduvieron recién.

**Comment by LeandroBraier** [comment]
@mkreyness siguen sin funcionar. 

Me parece que @FAAREIA y vos no se están entendiendo, porque él me sigue pasando las urls que vos decís que no ponga.

Porfa revisen y pasenme las URL correctas lo antes posible.

**Comment by mkreyness** [comment]
Porque @FAAREIA lo esta mirando desde el punto de vista general, y no del sitio paraguayo.
Nosotros tenemos 4 sitios ahi: argentina, revear, uruguay, paraguay.
El dato de SITIO que esta en el CMS ya hace que TODO lo que referencies pertenezca al sitio que corresponda.
Internamente las cosas estan desperdigadas, pero yo hice los links necesarios en su momento para que lo que @FAAREIA ve como /home/parexkla/www/_parex/img/productos-py
vos simplemente lo veas como img, siempre que el producto diga que pertenece al sitio de Paraguay.
Entonces, lo unico que tenes que poner en el CMS es esto:

img/guazurevok-exterior.jpg
img/guazurevok-exterior-150x150.jpg
img/guazurevok-interior.jpg
img/guazurevok-interior-150x150.jpg

Fijate, vas a ver que te anda.

**Comment by LeandroBraier** [comment]
Gracias, ahí funcionan las imágenes. Ahora cuando hago click en la imagen en multimedia se cuelga, puede ser?

Además me sigue sin funcionar la ficha técnica. Me pasás como sería la url de esa?

**Comment by LeandroBraier** [comment]
@FAAREIA estoy viendo que el tamaño que tomé de las imágenes de otros productos no me sirvió acá tampoco. Se siguen encimando con los textos:

http://www.parexparaguay.com.py/parex/guazurevok-exterior.html

Cual es el tamaño correcto de Thumb?

**Comment by mkreyness** [comment]
Dejaste un enter despue del .jpg del la primer imagen (lo que se abre al hacer click). 
Aparentemente eso vuelve loco al popup. Sacalo, espera un ratito a que todo se actualice y vas a ver que anda bien (no lo hago yo para que lo puedas ver).
Fichas tecnicas: simplemente pone 
/media/custom/upload/guazurevok.pdf
porque bkps/parexparaguay.com.py como ya te dije, esta implicito por el dato "sitio" del producto.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! Que increible que sea eso.

Ahora nos queda solo solucionar el tamaño de los thumbnails @FAAREIA Cuando puedas decime, pero ya le avisé al cliente que está online.

**Comment by FAAREIA** [comment]
Ahi le ajuste algo en el CSS y achiqué las imágenes, ahora va bien dale F5

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Ahora sí. Cierro el ticket y me lo guardo para acordarme con qué ruta subir estas imágenes. LO del CSS queda para próximos productos también? 

abrazo

**Comment by FAAREIA** [comment]
Si lo del CSS ya esta aplicado, sería un fix que aplica a los 3 paises.

**Comment by LeandroBraier** [comment]
genial. Gracias @FAAREIA !
