### ISSUE TITLE
Detalle importante: Imagen de preview de Facebook Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#367]
@FAAREIA en la preview de Facebook del Club quedó una imagen que es politicamente incorrecta para nosotros: la del modelo de colocador anterior.

<img width="522" alt="captura de pantalla 2016-10-03 a las 1 05 40 p m" src="https://cloud.githubusercontent.com/assets/6719872/19043362/30fcd692-8966-11e6-9bbe-0c375213c7b7.png">

La podrás cambiar por la nueva que te pasé?

Lease:

<img width="1675" alt="captura de pantalla 2016-10-03 a las 1 06 13 p m" src="https://cloud.githubusercontent.com/assets/6719872/19043395/547dbe24-8966-11e6-88be-c9b172851701.png">

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, me recordas en donde usamos la nueva foto? Si la tenes por ahi mejor, y si hay alternativas de la misma mejor aún.
Abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA te paso el ticket donde la usamos. Ahí la tenés subida:

[https://github.com/LeandroBraier/Klaukol/issues/310](https://github.com/LeandroBraier/Klaukol/issues/310)

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! Cuanto demoraba más o menos en actualizarse en FB, te acordás eso?
