### ISSUE TITLE
Juego de Subí tu foto

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#368]
@mkreyness necesito un nuevo juego de "Subí tu foto" para la Comunidad de Vendedores. Ves posible pedirle a Valen que tome lo que ya hiciste en otras ocasiones y lo repita?

**Comment by mkreyness** [comment]
Si la foto va al mismo repositorio de "Fotos de vendedores" que antes, no hay que programar nada, simplemente agrega un tema y un juego de tipo "upload". Fijate como estaba hecho el anterior.

**Comment by LeandroBraier** [comment]
Genial MK! Lo puedo hacer yo entonces.  Gracias.
