### ISSUE TITLE
Redireccionamiento "Acceso Distribuidores"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#369]
@FAAREIA te paso un pedido bastante claro del cliente. Decime si es posible hacerlo.

El cliente dice:

Hoy en día nuestros proveedores deben acceder al siguiente link para ingresar a bajarse las facturas y consultas su estado de cuenta:

![acceso distribuidores](https://cloud.githubusercontent.com/assets/6719872/19091678/f789fbd4-8a59-11e6-9d4f-f42e663084bf.jpg)

Como veras los lleva a una dirección extraña : http://200.41.126.125/publiweb/principal.php, que es la q se maneja aquí internamente 

Lo que necesitamos es crear una dirección q sea mas simple: como idea podría ser www.parexklaukol.com,ar/misfacturas o www.parexklaukol.com,ar/facturas y que ese link de acceso los dirija a la página web que hoy en día ingresan los clientes desde acceso distribuidores (http://200.41.126.125/publiweb/principal.php). 

Porque la idea es poder comunicarles a ellos que ingresando simplemente a esta dirección:  www.parexklaukol.com,ar/misfacturas, pueden acceder a lo q necesiten (sin tener q seguir toda la ruta de ingresar  a la home, buscar el acceso a distibudirores, etc) 

Se puede hacer?

**Comment by FAAREIA** [comment]
Hola Lea, todo se puede pero me parece que este issue puede volverse grande ya que imagino que ese IP es una intranet de ellos y va haber que averiguar quién lo administra.
@mkreyness Copio a marce que es tema de el

**Comment by FAAREIA** [comment]
Perdón, había entendido mal. Pensé que querían crear un alias permanente en la intranet
Ahora lo hago y probamos

**Comment by FAAREIA** [comment]
Hecho.
http://www.parexklaukol.com.ar/misfacturas
http://www.parexklaukol.com.ar/facturas
Las 2 urls llevan a la intranet esa.

**Comment by LeandroBraier** [comment]
Muchisimas gracias @FAAREIA !! QUé velocidad!

abrazo grande

**Comment by LeandroBraier** [comment]
El favicon y el título de página no lo podemos modificar nosotros no? Para eso si tenemos que acceder a su server, verdad?

**Comment by FAAREIA** [comment]
Claro, para eso si.

**Comment by LeandroBraier** [comment]
Perfecto, gracias Fede!
