### ISSUE TITLE
Newsletter Novedades Klaukol Junio. DEADLINE: 09/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#37]
Fede, te paso la info para el news corporativo de Junio en un ppt. Está subido en BENTEVEO MAQUETADOR/ KLAUKOL/ NEWSLETTER NOVEDADES JUNIO

La idea es priorizar imagen (ejemplo q está en el primer slide de Visa y algunos otros q adjunto aqui) 

O sea en el news que te llega al mail debe ser mas foto que texto. Debe ser BIEN GRAFICO. 
Por eso hay un ppt aparte con diseños de referencia. Son fotos con titulo con texto corto (aqui con prioridad en imagen)  y dps el link con el desarrollo de nota mas larga donde se prioriza texto. La nota más larga sería una novedad de la sección novedades de la web. (Eso lo carga el cliente via CMS).

Las notas van con distinto destaque, en orden de importancia son: 

NOVEDADES (como primera) 
PRODUCTO - CAPACITACIONES (en segundo orden de destaque) 
EVENTOS-SUSTENTABILIDAD (en tercer orden de destaque) 

Te lo paso a vos directamente porque ya tenemos un newsletter de base standard armado. Habría que adaptar eso a estos pedidos.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi va el diseño del news. Algunos detalles:
- Un newsletter asi nunca puede ser template. Hay tipografías no-básicas e imágenes y fondos que a veces se cruzan.
- Ello dicen "bien gráfico" pero dan ejemplos que no son válidos. Es como pretender poner una gigantografía horizontal en una revista, son 2 estructuras distintas. Lo aclaro porque ellos pasan ejemplos de navegador (1280px de ancho o más) en donde el título y la bajada es realmente corto y la foto la rompe. Aca hay 640px de ancho y los títulos y bajas que nos pasarón son largos.
- El concepto de "bien gráfico" también queda confuso con el ejemplo de la 3 página del powerpoint. La página 4 y 5 también quedan descolgadas ya que son meramente imágenes, no hay casi texto.

![news](https://cloud.githubusercontent.com/assets/6184969/8062337/84009974-0ea5-11e5-8607-37c23e47dbdc.png)

**Comment by LeandroBraier** [comment]
Entendido Fede! Gracias!! Quedó muy bueno.

Ya lo estaba teniendo en cuenta a esto pero quise que igual vieras el feedback entero del cliente para tener en cuenta lo que busca.

abrazo

**Comment by LeandroBraier** [comment]
Una corrección pequeña. En el primer apartado que lleva a Facebook no hace falta el leer más.

Corregime eso y lo mando a aprobar.

abrazo

**Comment by LeandroBraier** [comment]
Perdón, algo más: que ese link que dice "facebook.com/parexklaukolarg" lleve a esa url pero el texto del botón diga: "IR A FACEBOOK"

abrazo

**Comment by LeandroBraier** [comment]
Va corrección de texto para algunas partes y resumo los cambios anteriores:

APARTADO FACEBOOK

. No hace falta el leer más.

. que ese link que dice "facebook.com/parexklaukolarg" lleve a esa url pero el texto del botón diga: "IR A FACEBOOK"

. Cambiar el texto por el siguiente:

Seguinos en Facebook y enterate de todas nuestras novedades

Consejos prácticos, capacitaciones, tutoriales, tendencias y mucho más.

APARTADO GUÍA DE CORRALONES

Nueva Guía de Corralones. Encontrá tu corralón más cercano.

Nuestra guía online de corralones te permite desde cualquier dispositivo ubicar los corralones cercanos a la zona donde realizás tu obra. Ingresá y encontrá tu corralón más cercano (toda esta frase va con link a la guía) 

El LEER MÁS está ok.

**Comment by FAAREIA** [comment]
Te lo mandé por mail Lea. Vuelvo a eso de las 18hs hoy.
Abrazo

**Comment by LeandroBraier** [comment]
Fede, necesito modficiaciones en este newsletter.

Serían dos versiones:

1) una parecido a como esta, conservando el orden de las noticias, y agregando alguna imagen al costado en la nota de Idea, del Forum y sobre todo de Lanko (sacar ese pack, debe ir con imagen si o si). Quedaría casi igual, pero con las siguientes fotos que te paso aquí:

Foto para la nota de Idea

![escuela de negocios idea](https://cloud.githubusercontent.com/assets/6719872/8236132/98c088d8-15bc-11e5-81c6-03e836555f30.png)

Foto de Forum Construya 

http://www.grupoconstruya.com.ar/actividades/images/Tucuman2014/ForumTucuman2014_08g.jpg

Foto de Lanko

![slide-8--lanko](https://cloud.githubusercontent.com/assets/6719872/8236032/02b4eca8-15bc-11e5-9493-e5429ffa12d7.png)

2) Una segunda propuesta con la nota destacada arriba de Lanko con la imagen que te pasé más en grande y luego el resto más como está ahora. La nota de arriba sería la de Lanko, con la foto que te paso por WeTransfer bien grande y el siguiente texto:

SUSTENTABILIDAD
Lanko 901 es la solución fácil y sustentable para resolver la aislación térmica

Después de esta nota iría de la Forum Construya y recién abajo de eso el resto de las notas.

COnfirmame si recibiste todo porfa.

abrazo

**Comment by FAAREIA** [comment]
![sin-titulo-2](https://cloud.githubusercontent.com/assets/6184969/8237021/c33c434e-15c2-11e5-8ac0-016dae80994f.png)
![sin-titulo-3](https://cloud.githubusercontent.com/assets/6184969/8237022/c36daac4-15c2-11e5-8f9a-b6cbeeb26ab9.png)

**Comment by LeandroBraier** [comment]
Excelente Fede!!

Gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA , te envío por WeTransfer el psd con el diseño final del Newsletter Klaukol Junio a maquetar para mañana a la mañana.

Confirmame si llegamos.

abrazo

**Comment by LeandroBraier** [comment]
Te van a faltar los links a las notas, te los paso a la tarde.

abrazo

**Comment by LeandroBraier** [comment]
Aca va el link:

https://www.wetransfer.com/downloads/48684e9b3da8c426612c118d8a51d8bf20150625154013/c3207b

**Comment by FAAREIA** [comment]
Se lo asigno a Braulio para que lo haga. Teniendo en cuenta que son todas tipografías especiales, todo va a ser imagen.

**Comment by FAAREIA** [comment]
@braulio-evangelisti

**Comment by LeandroBraier** [comment]
Si, hagamoslo así es más rápido. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Braulio: te paso los links para este newsletter. Aprovecho y te pido que quites la referencia al Club de Colocadores o que lo pongas en gris por lo menos, ya que aún no está habilitado.

Por favor agregale a los links un tag que nos indique luego en el Analytics que los clics vienen del newsletter.

LOGO PAREX GROUP
http://www.parexklaukol.com.ar/

LOGO KLAUKOL
http://www.parexklaukol.com.ar/productos-klaukol.html

LOGO PAREX
http://www.parexklaukol.com.ar/productos-parex.html

LOGO LANKO
http://www.parexklaukol.com.ar/productos-lanko.html

LOGO FACEBOOK
http://www.facebook.com/parexklaukolarg

LOGO YOUTUBE
http://www.youtube.com/cftonline

NOTAS EN ORDEN DE ARRIBA A ABAJO Y DE IZQUIERDA A DERECHA
http://www.parexklaukol.com.ar/novedades/ahora-estamos-en-facebook.html
http://www.parexklaukol.com.ar/novedades/encontra-tu-corralon-mas-cercano.html
http://www.parexklaukol.com.ar/klaukol-impermeable-potenciado/
http://www.parexklaukol.com.ar/novedades/parexgroup-continua-sus-programas-de-desarrollo-en-la-escuela-de-negocios-idea.html
http://www.parexklaukol.com.ar/novedades/expoconstruir-2015-principal-encuentro-de-negocios-de-la-construccion.html
http://www.parexklaukol.com.ar/novedades/aislacion-termica--ahorra-el-40%-de-la-energia-de-tu-hogar-facil.html
http://www.parexklaukol.com.ar/guia-corralones/
http://www.parexklaukol.com.ar/vendedores/

LINK PAREXKLAUKOL.COM.AR
http://www.parexklaukol.com.ar/

LOGO PAREXGROUP DEL FOOTER
http://www.parexgroup.com.ar/

Por favor avisame para qué hora lo podríamos tener maquetado.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti en qué estamos con esto?

Era un toque maquetarlo, es todo imagen. Para cuando lo tenés? Lo tengo que enviar mañana sin falta.

**Comment by braulio-evangelisti** [comment]
Lo termino y te lo mando. 18hs esta bien?

**Comment by LeandroBraier** [comment]
Dale, 18 hs estamos bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Listo Lea, fijate ahi.

http://parexklaukol.com.ar/_mailing/novedades/

Cualquier corrección, hasta las 19:30 esto.
Abrazo

**Comment by LeandroBraier** [comment]
OK. Te paso feedback:
1. Los links de arriba están mal, no son los que yo te pasé. Repasá y
   corregilos.
2. La fecha está mal. Quitala directamente.
3. El link de la guía de corralones te lo pasé mal yo: es así:

http://www.parexklaukol.com.ar/novedades/encontra-tu-corralon-mas-cercano--nueva-guia-de-corralones-klaukol.html
1. Los links del footer de Klaukol, Parex, Lanko y ParexGroup están mal. No
   los pongas de memoria, mirá la lista que te pasé y pegalos de ahí.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 18:34 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Ahi lo arregle, como los links /lanko /parex etc redireccionan a su pagina respectiva pense que no habia problemas.

**Comment by LeandroBraier** [comment]
Gracias! Ahora si!

En el logo de abajo de todo no pusiste el link que te pasé pero ya fue, yo lo sé corregir.

abrazo
