### ISSUE TITLE
Nuevos Productos Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#370]
Buen día @FAAREIA ! Para subir un producto en revear también te tengo que pedir a vos no?

Confirmame porque necesito subir uno hoy para que esté online el martes.

abrazo

**Comment by mkreyness** [comment]
No, el "Nuevo Revear" esta bien hecho, lo cargas todo por CMS, salvo fichas tecnicas.

**Comment by LeandroBraier** [comment]
Genial MK. Y las fichas técnicas se las paso a Fede entonces no?

**Comment by mkreyness** [comment]
Si, despues tenes que poner el URL completo, segun donde lo haya subido.
Por ejemplo si te fijas en el primer producto que aparece, dice asi:

http://www.revear.com.ar/media/custom/upload/revividor.jpg

o sea que el lo subiria en el home/parexkla/public_html/revear/media/custom/upload/XXXXX
y vos lo referencias como

http://www.revear.com.ar/media/custom/upload/XXXXX

**Comment by LeandroBraier** [comment]
Perfecto @mkreyness ! Gracias!

@FAAREIA te pido entonces que subas la ficha técnica porfa:

[FICHA TECNICA_MEDIANERAS_PDF BAJA.pdf](https://github.com/LeandroBraier/Klaukol/files/516484/FICHA.TECNICA_MEDIANERAS_PDF.BAJA.pdf)

Me pasarías el link hoy porfa?

**Comment by FAAREIA** [comment]
El nombre que le puse al archivo es: `ficha-tecnica-medianeras.pdf`
El url final sería `http://www.revear.com.ar/media/custom/upload/ficha-tecnica-medianeras.pdf` si no me equivoco

**Comment by mkreyness** [comment]
Es correcto

**Comment by LeandroBraier** [comment]
Perfecto chicos! Muchísimas gracias!!!

**Comment by LeandroBraier** [comment]
@FAAREIA estoy subiendo dos productos nuevos. Te paso las fichas técnicas:

FICHA TÉCNICA REVEAR FRENTES
[FRENTES.pdf](https://github.com/LeandroBraier/Klaukol/files/539957/FRENTES.pdf)

FICHA TÉCNICA REVEAR MUROS
[MUROS.pdf](https://github.com/LeandroBraier/Klaukol/files/539958/MUROS.pdf)

Cuando puedas me pasás el link para que suba?

**Comment by FAAREIA** [comment]
`http://www.revear.com.ar/media/custom/upload/ficha-tecnica-frentes.pdf`
`http://www.revear.com.ar/media/custom/upload/ficha-tecnica-muros.pdf`

Cualquier cosa decime lea
abrazo

**Comment by LeandroBraier** [comment]
Perfecto Fede!! Muchas gracias!!!
