### ISSUE TITLE
Newsletter Octubre ParexKlaukol. 13/10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#371]
Buen día @FAAREIA !

Te paso los contenidos para el news de Octubre. Confirmame si llegás para mañana a armarlo.

[Contenido Newsletter ParexKlaukol OCTUBRE Corregida.docx](https://github.com/LeandroBraier/Klaukol/files/524712/Contenido.Newsletter.ParexKlaukol.OCTUBRE.Corregida.docx)

[Imagenes Newsletter Octubre.zip](https://github.com/LeandroBraier/Klaukol/files/524713/Imagenes.Newsletter.Octubre.zip)

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, todavía no lo vi pero para mañana no llego. Ahora voy a darle lo que me queda de horas y mañana a la mañana esta listo.

**Comment by LeandroBraier** [comment]
Perfecto, con eso estamos OK Fede. Hacelo ya directamente para enviar
porfa. No hagas esa etapa intermedia que hacés siempre.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-10/16-10.html

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !! Está excelente! Listo para mandar?

**Comment by FAAREIA** [comment]
Hola Lea si esta listo, igual siempre hace una prueba previa

**Comment by LeandroBraier** [comment]
Perfecto gracias!

**Comment by LeandroBraier** [comment]
@FAAREIA me piden un ajustecito mínimo. La primer foto la primer foto por como la recortaste no se aprecia q hay una pileta, trata de reencuadrarla desde mas abajo, aunque corte la ventana.

Porfa necesitaría esto hoy, porque el news sale el lunes temprano.

**Comment by FAAREIA** [comment]
Job done

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Excelente! abrazo
