### ISSUE TITLE
Bugs en Novedades Parex

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#372]
@mkreyness estamos teniendo los siguientes problemas:

**1 . Error en tema paginación de imágenes.** 

En la solapa de imágenes, cuando son más de 11 imágenes requiere paginar y falla el sistema. Cargás una foto más y al volver a la solapa se borraron las demás. Probalo en la nota "_ceramicos-y-porcellatos-para-banos-modernos_" que ya tiene 11 imagenes

**2. No se puede alterar el html después de cargar imágenes.** 
Probá cargar una imagen y volver a la solapa HTML para insertarla, vas a ver que te aparece como una maquetación de todo el CMS adentro del HTML. La unica forma es guardar cambios y volver a entrar.

**3. Cargamos imágenes en el html, guardamos, las vemos y después se borran.**
Además de los puntos 1 y 2, nos pasó de guardar un HTML que ya tenía insertadas una serie de imágenes y se veían, pero al volver a entrar más tarde habían desaparecido.

Todo esto nos pasó en estas 2 notas:

ceramicos-y-porcellatos-para-banos-modernos.html
cocinas-pequenas-con-inspiracion.html

Ambas del 01-11-2016

Me confirmás qué puede estar pasando y para cuando podríamos corregirlo? Obviamente puede ser para mañana la respuesta.

abrazo

**Comment by mkreyness** [comment]
La verdad que salvo lo primero, todo lo demas parecen cosas del plugin de editor HTML que desconozco si tienen arreglo, capaz haya una nueva version para reemplazar. En cuanto pueda lo miro bien.

**Comment by LeandroBraier** [comment]
Ok. Al punto 2 ya nos acostumbramos, pero 1 y 3 son fundamentales. Dales prioridad a esos 2.

**Comment by mkreyness** [comment]
1) Agregue tres imagenes y no me paso eso. Claro que tarda un poco en refrescar toda la lista porque son muchas imagenes, pero finalmente aparecen las 12, 13, 15. NO HAY paginacion antes de las 20 creo, no hay ningun limite en 11, simplemente es scroll. Es largo, si, porque las imagenes hacen que cada renglon sea alto.

Lo que si veo de raro es que me aparecio el cartel de si quiero "abandonar la pagina", porque ese refresco parece no gustarle al Chrome. Siempre le contesto que NO quiero abandonar la pagina.

**Comment by LeandroBraier** [comment]
1) Ok. Vos decís que la persona que estaba cargando puso abandonar la página y por eso las perdió?

**Comment by mkreyness** [comment]
No, no creo que eso haga que se pierda nada tampoco, solo que asusta.
Recien agregue una mas, le di a proposito que si quiero abandonar, y no solo no se fue, sino que la foto esta ahi. OJO lo que no me esta respetando bien es el orden, porque la ultima que agregue (la de la Mona Jimenez, JURO que en Clarin salio eso y por eso lo capturé) y veo otras 2 o 3 que agregue antes, listadas despues. Eso capaz tambien marea.

**Comment by mkreyness** [comment]
Pregunta, porque ya lo tengo muy olvidado esto, como hacen para insertar una imagen, la abren para tener el URL completo y lo pegan en la tool de imagenes del HTML ?

**Comment by LeandroBraier** [comment]
Exacto. Hacemos eso.

**Comment by mkreyness** [comment]
A mi me anda bien, no sera que a veces en vez de darle "Guardar Cambios" aprietan "Generar HTML y Guardar" ? Eso solo hay que hacerlo al principio cuando todavia no lo editaste, si no obvio que vas a perder todos los cambios.

**Comment by LeandroBraier** [comment]
Aaahhh ok. Consulto y te digo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-10-26 19:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
El punto 3 IS HAPPENING NOW! Intento cargar nuevas fotos en una nota y no me deja.

Me pasó en varias pero como ejemplo te doy la nota de Cerro Negro. Se llama "Cerro Negro - Programas"

**Comment by mkreyness** [comment]
yo veo todo normal, hay varias fotos en la lista de imagenes, y las mismas estan dentro del HTML, no ?
No se como reproducir el problema, tampoco quiero andar tocando cosas que ya estan publicadas.

**Comment by LeandroBraier** [comment]
Ok. Lo que hice fue entrar desde Firefox para que se sumen. Pero las mismas
que subí desde Firefox desde Chrome no podía.

Dejalo por ahora y te aviso cuando se vuelva a repetir, pero no se te
ocurre qué puede ser?

**Comment by mkreyness** [comment]
Algun bloqueo de popups que tuvieras en el Chrome ? No se, yo siempre que probe lo hice desde Chrome y me anduvo perfecto.

**Comment by LeandroBraier** [comment]
Es que el pop up se abrió y cargué la foto, pero no aparecía luego en la
página principal, en la lista de imágenes.

**Comment by mkreyness** [comment]
Pero no termino de entender a que llamas "la lista de imagenes". Es la solapa "Imagenes" (algo que manejo yo) o las que te muestra para elegir el plugin HTML (algo que no manejo yo).

**Comment by LeandroBraier** [comment]
Yo cargo la foto via pop up, el pop up se cierra y en la solapa imágenes no
aparece la imagen que cargué. Esa sería la descripción más acertada de lo
que me pasó. Si te sirve a la tarde te paso una captura de video.

2016-11-07 19:17 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero a ver: vos entras en "Novedades Argentina", das Buscar, entras en una novedad, haces click en la solapa "Imagenes". Ahi (como hay muchas imagenes) escrolas hasta abajo donde dice "Agregar Imagenes".
Te abre una pantalla donde ya figura fijo el nombre de la novedad, tendrias que agregar una descripcion, y apretar el boton que dice "Seleccionar Archivo". Seleccionas un archivo local tuyo, ESPERAS UN POCO, porque siempre el upload tarda, el boton "Guardar Nuevo" NO responde inmediatamente.
Cuando el boton reacciona a tu click, ves que avanza un % de subida, y cuando llega al 100% se cierra esa ventana, y SIN EMBARGO no aparece automaticamente en la lista. Eso si, me acaba de pasar.
Pero le doy reload a la pagina y APARECE, o sea, no es que se haya perdido, solo que no se refresco bien la pagina (probablemente porque tiene muchas imagenes o algo asi). Ese es el tema ? Y con firefox anda siempre bien ?

**Comment by LeandroBraier** [comment]
Exacto. Ese es el problema en Chrome. En Firefox eso mismo no me pasó.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-11-08 9:27 GMT-03:00 mkreyness notifications@github.com:
