### ISSUE TITLE
Newsletter Noviembre ParexKlaukol. 31-10

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#373]
Buen día @FAAREIA !

Te paso los contenidos para el news de Noviembre. Sería para el lunes.

[Contenido Newsletter ParexKlaukol NOVIEMBRE a maquetar.docx](https://github.com/LeandroBraier/Klaukol/files/556463/Contenido.Newsletter.ParexKlaukol.NOVIEMBRE.a.maquetar.docx)

[Imagenes Noviembre.zip](https://github.com/LeandroBraier/Klaukol/files/557284/Imagenes.Noviembre.zip)

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi Lea:
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-11/16-11.html

**Comment by LeandroBraier** [comment]
Excelente Fede!!! Solo te pido ajustecitos:

1) Agregale el tilde a "PLANIFICÁS" en la parte de la encuesta.

2) En las novedades de abajo, cambiale la fecha a las Últimas novedades.

Ponele 01/11 a Informe Construya
A los de #EnBuscaDelColocador poneles a cada uno su fecha: 05/11, 16/11 y 30/11
A Tendiez ponele 10/11
A Cerro Negro ponele 25/11

Y ordenalos por fecha porfa.

Con eso lo mando.

abrazo

**Comment by FAAREIA** [comment]
Job done!

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Ya listo para subir a mailchimp o falta?

El cliente no me respondió aún pero es posible que me pida pasar la nota de Cerro Negro como nota principal arriba. Te aviso.

abrazo

**Comment by FAAREIA** [comment]
Si ya esta listo

**Comment by LeandroBraier** [comment]
Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA tenemos unos ajustes que hacerle al news. Llegás a hacerlo para hoy?

Cambian algunas notas y algunas fotos. Pensé que te lo había pasado antes de ayer pero estoy viendo que en este ticket no está. No sé en donde te lo habré pasado:

[Contenido Newsletter ParexKlaukol NOVIEMBRE a maquetar 2-11.docx](https://github.com/LeandroBraier/Klaukol/files/572382/Contenido.Newsletter.ParexKlaukol.NOVIEMBRE.a.maquetar.2-11.docx)

[Imagenes Noviembre.zip](https://github.com/LeandroBraier/Klaukol/files/572383/Imagenes.Noviembre.zip)

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi Lea, mirá que hay un par de links rotos aún
Abrazo

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! Faltaban publicar algunas notas. Ya las publiqué todas y solo falla el link de la nota de ¿Te animás a una cocina negra?

A esa cambiale el link por el siguiente:

http://www.parexklaukol.com.ar/novedades/tendencias-deco-2017--te-animas-a-una-cocina-negra-.html

Solo eso y ya estamos!

abrazo

**Comment by FAAREIA** [comment]
Hecho
Fijate ahora
Abrazo

**Comment by LeandroBraier** [comment]
Impecable Fede!! Muchas gracias!!

**Comment by LeandroBraier** [comment]
@FAAREIA te paso un cambio solo más y estamos: quitar la novedad del 05/11 sobre #EnBuscaDelColocadorKlaukol.

Solo eso. avisame cuando está porfa.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-11/16-11.html
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
