### ISSUE TITLE
Mailing para Colocadores URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#374]
@FAAREIA necesito que armes este mailing en Mailchimp mediante imagen para hoy lo antes posible. Podés hacerlo con el PNG?

**Comment by LeandroBraier** [comment]
@FAAREIA va la imagen final para que la maquetes:

![mailing-club-de-colocadores-final](https://cloud.githubusercontent.com/assets/6719872/19945024/f761b212-a11c-11e6-834a-eb865d75cc43.png)

Ya tiene el OK final final del cliente. Porfa apenas lo tengas en Mailchimp avisame. 

abrazo

**Comment by FAAREIA** [comment]
Esta en mailchimp lea

**Comment by LeandroBraier** [comment]
Muchisimas gracia Fede!!!
