### ISSUE TITLE
Sumar Nuevos Colocadores al Club de Colocadores 07/11

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#375]
@mkreyness necesito que sumes hoy estos usuarios nuevos al Club. A los que tienen mail mandales el mailing de bienvenida porfa.

[Participantes Evento Tecnopolis a sumar a Club de Colocadores Klaukol.xlsx](https://github.com/LeandroBraier/Klaukol/files/575837/Participantes.Evento.Tecnopolis.a.sumar.a.Club.de.Colocadores.Klaukol.xlsx)

Avisame cualquier faltante.

abrazo

**Comment by mkreyness** [comment]
a la tarde lo cargo y mando, pero no son un poco aparatosos los nombres de usuario ? Digo, si uno tiene que tipear eso para loggearse no da muchas ganas.
Ademas siendo que todos tienen la misma clave, cualquier error de tipeo (que te falte un numero o que los escribas al reves) estas entrando a la cuenta de otro y sin siquiera darte cuenta.

**Comment by LeandroBraier** [comment]
Es cierto eso pero lo venimos haciendo hace rato. La mayoría entra a través
de los mails, no te preocupes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

2016-11-07 13:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ya estan cargados y los mails estan saliendo.

**Comment by LeandroBraier** [comment]
Genial MK. Gracias!
