### ISSUE TITLE
Bug en Registración Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#376]
@mkreyness cuando alguien deja sin completar el DNI o cualquier otro campo en el formulario, el sistema da el siguiente mensaje:

**Ya hay otro usuario registrado con ese DNI**

El mensaje correcto debería ser "Por favor completá tu DNI." o los campos que estén faltando completar, no?

**Comment by mkreyness** [comment]
El campo deberia ser obligatorio en el formulario, a mi ni me deberia llegar. 
Sera que en algun momento pidieron que no fuera obligatorio ? 
Esta dando ese error recien ahora porque entre la gente que me pasaste habia un par sin DNI, si no nunca hubiera pasado.

**Comment by mkreyness** [comment]
Ahi me fije, el campo ESTA puesto como obligatorio. No se por que no le da bola, ni a ninguno de los otros, eso lo tendria que revisar Fede, capaz falte algo en el CSS.
Puse los que estaban con DNI vacio en nulo y ahora no da ese error, en realidad da otro pero tampoco esta previsto en la interface mostrar un cartel con ese error, ahora reviso eso.

**Comment by mkreyness** [comment]
y es grave porque el CODIGO es el DNI.  Voy a poner mientras un doble control de que no falte el DNI, si.

**Comment by mkreyness** [comment]
Listo lo del DNI, pero el problema de hacerlo asi es que se pierde todo lo demas que el tipo haya escrito, lo mejor es que @FAAREIA vea por que no andan los atributos "required".

**Comment by LeandroBraier** [comment]
Gracias @mkreyness !!

Te fijás @FAAREIA porfa??

**Comment by FAAREIA** [comment]
El tema aca es que el boton no manda el formulario normalmente, sino que ejecuta la funcion: `validarform();` es por eso que la validación no la hace el browser. Habría que resolver eso

**Comment by mkreyness** [comment]
Porque tiene que comparar si lo que repite el email coincide, pero despues llama al submit, no ejecuta ahi el control de required ?

**Comment by FAAREIA** [comment]
El tema es que no existe botón que envie el formulario, eso lo hace la función por lo que no interviene el navegador parece.
Habría que hacer que el form se envié normalmente y que luego chequee eso del mail

**Comment by mkreyness** [comment]
Pero la gracia esta en que no tenga que retipear todo de nuevo por haber puesto mal el mail, si se hace el submit, todo lo que ya cargo se pierde. Entonces lo que voy a hacer es que el control de que los campos no esten vacios lo haga la misma "ValidarForm" y listo.

**Comment by mkreyness** [comment]
Ya esta, igual no es perfecto proque tampoco hace las validaciones de formato de los email. No sabes si no se puede invocar ese control de alguna manera ? Como busco documentacion de esto ?

**Comment by FAAREIA** [comment]
El tema de emular la validación del navegador imagino que es complicado porque cada uno tiene su "engine".
Lo que se podría hacer es guardar los valores y ponerlos como value="X" cuando se recargue la página con el error

**Comment by mkreyness** [comment]
Ya encontre, se llama "checkValidity();" lo que hay que hacer.
Le agrego "email.checkValidity();" dentro de mi validarForm.

**Comment by LeandroBraier** [comment]
@mkreyness me avisás cuando esté listo esto?

**Comment by mkreyness** [comment]
ya esta listo esto desde que dije eso.

**Comment by LeandroBraier** [comment]
Gracias chicos!
