### ISSUE TITLE
Inscripción Klaukol te Busca

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#378]
@FAAREIA te paso lo que hablamos hoy.

1) Intentar acortar el proceso.

2) Cambiar este texto:

<img width="696" alt="captura de pantalla 2016-11-09 a las 8 45 50 p m" src="https://cloud.githubusercontent.com/assets/6719872/20158508/68f5eeba-a6b9-11e6-964d-1b059edfa204.png">

Por el siguiente texto (todo lo demás quitarlo): 

FELICITACIONES YA ESTAS INSCRIPTO EN LA COMPETENCIA! 

Solo falta un paso. Acabamos de enviarte un mail para que confirmes tu dirección de correo electrónico. 

"volver al sitio web" (que lleve a www.klaukoltebusca.com.ar)

3) Cambiar este texto del mailing:

![captura de pantalla 2016-11-09 a la s 17 28 46](https://cloud.githubusercontent.com/assets/6719872/20158566/c443eede-a6b9-11e6-966a-02326a4d70b8.png)

Por el siguiente texto (quitar todo lo demás):

SUBJECT: Ya estás inscripto en la competencia En Busca del Colocador Klaukol

Por favor confirmá tu correo electrónico haciendo clic en este botón:

CONFIRMAR

Ante cualquier duda contactarse con klaukol.marketing@klaukol.parex.com

4) Cambiar este texto de la pantalla:

![captura de pantalla 2016-11-09 a la s 17 29 08](https://cloud.githubusercontent.com/assets/6719872/20158600/082bb000-a6ba-11e6-8e94-bff98bd4c847.png)

Por el siguiente texto (quitar el captcha y el botón):

¡MUCHAS GRACIAS POR CONFIRMAR TU DIRECCIÓN DE CORREO ELECTRÓNICO!

Te mantendremos al tanto periódicamente de las novedades de la competencia.

5) Quitar esta pantalla:

![captura de pantalla 2016-11-09 a la s 17 30 45](https://cloud.githubusercontent.com/assets/6719872/20158637/492ff85e-a6ba-11e6-8c5f-10d7f57f9a0e.png)

abrazo

**Comment by FAAREIA** [comment]
La última pantalla no la muestra y va directo al sitio, pero a la anteúltima no le puedo sacar el captcha ni evitarla. Estuve leyendo un poco pero no encontré forma.
Salvo eso, esta todo listo

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!! Ahora lo chequeo.

**Comment by LeandroBraier** [comment]
Está perfecto Fede. Solo 1 cambio. 

En el mail, donde dice "Confirmar suscripción" no se puede poner "Confirmar email"?

<img width="1176" alt="captura de pantalla 2016-11-10 a las 7 30 59 p m" src="https://cloud.githubusercontent.com/assets/6719872/20196177/4971b0fa-a778-11e6-8caf-e2fc41f9f2de.png">

La palabra suscripción confunde.

**Comment by FAAREIA** [comment]
hECHO

**Comment by LeandroBraier** [comment]
Fede: me sigue diciendo CONFIRMAR SUSCRIPCIÓN arriba, que es donde te pedía. Vos lo cambiaste abajo, que estaba bien diciendo solo CONFIRMAR.

<img width="761" alt="captura de pantalla 2016-11-11 a las 12 19 33 p m" src="https://cloud.githubusercontent.com/assets/6719872/20219541/b47fa916-a808-11e6-9b9e-0cfa768f2309.png">

Porfa me lo ajustás?

**Comment by FAAREIA** [comment]
Ahora si ;)

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! abrazo
