### ISSUE TITLE
Nuevos Usuarios Colocadores Cordoba y Mendoza

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#379]
@mkreyness cuando puedas hoy a la tarde creale usuario de Club de Colocadores a estas 2 bases de usuarios y, a lo que tienen mail, programales el mailing de bienvenida para mañana si se puede.

[Pre Inscriptos al 10-11.xlsx](https://github.com/LeandroBraier/Klaukol/files/589863/Pre.Inscriptos.al.10-11.xlsx)

[Preinscriptos Cordoba.xlsx](https://github.com/LeandroBraier/Klaukol/files/589864/Preinscriptos.Cordoba.xlsx)

abrazo

**Comment by mkreyness** [comment]
lo que pasa es que apenas los cargue el proceso automatico lo va a tratar de mandar.
Si lo inhibo para que no corra, tampoco va a mandar mails a los que se anoten individualmente online, no se que es peor.

**Comment by mkreyness** [comment]
Tampoco son tantos los que tienen mail, 23, hay problema en que se manden hoy ?

**Comment by LeandroBraier** [comment]
Dale, no hay problema.

**Comment by mkreyness** [comment]
listo, ya esta todo cargado y los mails estan saliendo.

**Comment by LeandroBraier** [comment]
Muchas gracias MK!
