### ISSUE TITLE
Cambio en Login de Comunidad de Vendedores. DEADLINE: hoy 08/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#38]
Fede, necesito que cambies en el login el campo de DNI por USUARIO

Resulta que no pudimos conseguir los DNI de los vendedores por una cuestión que no viene al caso, así que lo que vamos a hacer es cargar los usuarios con un nombre de usuario y clave que serían así:

EJEMPLO:

Usuario: jhernandez01

password: 05061956

La password correspondería a la fecha de nacimiento del tipo.

Esto tendría que estar hoy junto con todos los cambios pedidos para la Comunidad de Vendedores.

abrazo

**Comment by LeandroBraier** [comment]
Tener en cuenta que la URL de la comunidad debe ser la siguiente:

www.parexklaukol.com.ar/vendedores/

Si no es así por favor modifiquenla porque está así en todas las gráficas impresas y demás.

A las 16 hs deberíamos estar subiendola a producción. Llegamos bien?

abrazo

**Comment by mkreyness** [comment]
```
Ya esta cambiado.
Lo que si deberiamos eliminar toda actividad de los usuarios
truchos, no ? O la dejamos para que haya algo ?

El 08/06/2015 a las 11:32,
  LeandroBraier escribió:


  Tener en cuenta que la URL de la comunidad debe ser la
    siguiente:
  www.parexklaukol.com.ar/vendedores/
  Si no es así por favor modifiquenla porque está así en todas
    las gráficas impresas y demás.
  A las 16 hs deberíamos estar subiendola a producción. Llegamos
    bien?
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Cuando tengamos todo aprobado por el cliente la borramos, sí. Por ahora no
porque creo que ellos siguen haciendo pruebas con unos usuarios truchos que
yo les creé.

Lo que antes era DNI ahora es un nombre de usuario, no?

Otra consulta: el nombre de usuario es sencible a mayúsculas?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-08 12:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Si Lea, ya esta todo. Lo podes ver en:
http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl

Dale F5.

**Comment by mkreyness** [comment]
```
Si, lo que era DNI es "usuario", yo no usaria la palabra "nombre",
porque el nombre es un dato aparte.
No, no creo que sea sensible a mayusculas (en realidad depende de lo
que se le cante a la implementacion de la base de datos), pero
siempre es mejor que los generemos todo minuscula.

El 08/06/2015 a las 12:08,
  LeandroBraier escribió:

Cuando tengamos todo aprobado por el cliente la
  borramos, sí. Por ahora no
  porque creo que ellos siguen haciendo pruebas con unos usuarios
  truchos que
  yo les creé.

  Lo que antes era DNI ahora es un nombre de usuario, no?

  Otra consulta: el nombre de usuario es sencible a mayúsculas?

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-08 12:03 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Ya esta cambiado.
  > Lo que si deberiamos eliminar toda actividad de los usuarios
  > truchos, no ? O la dejamos para que haya algo ?
  >
  > El 08/06/2015 a las 11:32,
  > LeandroBraier escribió:
  >
  >
  > Tener en cuenta que la URL de la comunidad debe ser la
  > siguiente:
  > www.parexklaukol.com.ar/vendedores/
  > Si no es así por favor modifiquenla porque está así en todas
  > las gráficas impresas y demás.
  > A las 16 hs deberíamos estar subiendola a producción.
  Llegamos
  > bien?
  > abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/38#issuecomment-110027958
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Perfecto, MK. Gracias! Cierro este ticket.

Fede, lo seguimos en el ticket correspondiente a lo otro.

abrazo
