### ISSUE TITLE
Subir nuevos colocadores Evento Córdoba

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#380]
@mkreyness cuando puedas subí estos al Club de Colocadores y mandales mailing de bienvenida a los que tienen mail.

[Participantes Evento Cordoba a subir.xlsx](https://github.com/LeandroBraier/Klaukol/files/598596/Participantes.Evento.Cordoba.a.subir.xlsx)

abrazo

**Comment by mkreyness** [comment]
pero todos los codigos son casi identicos a los que ya estan, salvo el "-", no importa ?

**Comment by LeandroBraier** [comment]
No hay problema. Es solo para diferenciar de alguna forma a los que fueron
al evento de los que se suscribieron aparte.

**Comment by mkreyness** [comment]
Ok, lo mando a la noche porque ahora me estoy yendo a una cena de fin de año... Ya empezo esa epoca.

**Comment by LeandroBraier** [comment]
jajajj que lindo! Dale no hay problema. Puede ser mañana tambien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
listo ya cargue todo y estan saliendo los mails (que no son muchos).

**Comment by LeandroBraier** [comment]
Muchas gracias MK! Excelente este horario para mandar los mailings.
