### ISSUE TITLE
Sumar Nuevos Colocadores Mendoza al Club

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#381]
@mkreyness cuando puedas hoy subís estos nuevos usuarios al Club de Colocadores? Incluyendo el teléfono, puede ser?

[Nuevos Usuarios Club de Colocadores Mendoza.xlsx](https://github.com/LeandroBraier/Klaukol/files/621778/Nuevos.Usuarios.Club.de.Colocadores.Mendoza.xlsx)

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness no te olvides porfa de subir estos usuarios.

abrazo

**Comment by mkreyness** [comment]
no lo habia visto. Esta noche lo subo, ahora me estoy yendo.

**Comment by LeandroBraier** [comment]
Todo bien, esta noche joya.

abrazo

**Comment by mkreyness** [comment]
listo, ya estan cargados, y en un minuto salen los mails a los que tienen.

**Comment by LeandroBraier** [comment]
Muchas gracias @mkreyness !
