### ISSUE TITLE
Newsletter Diciembre ParexKlaukol 01-12

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#382]
@FAAREIA te paso todo listo para maquetar el newsletter de Diciembre de ParexKlaukol

Podrás tenerlo para mañana a la tarde?

[Contenido Newsletter ParexKlaukol DICIEMBRE v30-11 con LINKs.docx](https://github.com/LeandroBraier/Klaukol/files/622846/Contenido.Newsletter.ParexKlaukol.DICIEMBRE.v30-11.con.LINKs.docx)

[Imagenes DICIEMBRE.zip](https://github.com/LeandroBraier/Klaukol/files/622847/Imagenes.DICIEMBRE.zip)

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/parexklaukol/16-12/16-12.html
No esta listo para mandar, imagino que faltan novedades o confirmar links

**Comment by LeandroBraier** [comment]
Excelente Fede! Muchas gracias! Avanzá nomás con la versión
"mailchimpeable" Yo avanzo con las notas.

abrazo

[image: Benteveo TV] <http://benteveo.tv>
LEANDRO BRAIER
BENTEVEO
Guatemala 5582 - Piso 2 (CABA) Argentina
*T.* +54 9.11.58.71.73.99
*E.* leandro@benteveo.tv
*W.* www.benteveo.tv

**Comment by FAAREIA** [comment]
Ahi esta listo para copiar y pegar a mailchimp.
Cualquier cosa decime
Abrazo

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!
