### ISSUE TITLE
Ajustes de maquetación en Guía de Corralones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#385]
@FAAREIA cuando tengas un hueco después de la landing de FUCA, revisá la guía de corralones en resoluciones bajas. Por ejemplo:

1366x768
1200x800

Mirá como se enciman los textos:

<img width="1079" alt="captura de pantalla 2016-12-28 a las 3 38 06 p m" src="https://cloud.githubusercontent.com/assets/6719872/21528187/6fbd121a-cd0f-11e6-89a1-959eba33fd94.png">

Se podrá pulir?

**Comment by FAAREIA** [comment]
Si se puede, eso pasa cuando en resoluciones grandes el usuario achica verticalmente la ventana. Ahi le ajuste para que no siga pasando.

Cuañquier cosa decime
Abrazo

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Muchas gracias!!!
