### ISSUE TITLE
Pequeño Bug en Compartir Foto Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#386]
@mkreyness te fijás qué pasa en esta dinámica que en vez de compartir la imagen linkea a la imagen en facebook?

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=81&usuario=RaulRuiz&clave=estudianteslp

Es raro, porque la veo igual a esta, que funciona bien:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=77&usuario=RaulRuiz&clave=estudianteslp

**Comment by mkreyness** [comment]
a mi ambas me funcionan igual, y bien.
Ojo que si primero habias hecho armado algo mal y despues lo corregiste, puede haberte quedado cacheado lo viejo, probá desde otra maquina.

**Comment by LeandroBraier** [comment]
Nono tiene unos dias eso. Yo no lo habia probado en mi máquina. Que raro!
En fin si te anda pido una tercera opinión  por las dudas pero debe andar.

**Comment by mkreyness** [comment]
Si, lo publique y mire en mi muro, y estaba la foto perfecta. Ojo, yo soy el owner del facebook app, tampoco mi funcionamiento es necesariamente el de "cualquier usuario".

**Comment by LeandroBraier** [comment]
Gracias MK! Ya probe con otra compu y todo bien. Perdon por joder! Abrazo
