### ISSUE TITLE
Web ParexKlaukol Ajustes 2017

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#387]
@FAAREIA cuando vuelvas necesito que revises lo que hicimos con MK quitando a Lanko de la web.

También te pido que quites el logo en los footer de la Comunidad de Vendedores, Club de Colocadores y Guía de Corralones.

A su vez, subí una nueva versión del video, pero en 4MB. Quizá vos lo podés comprimir mejor y resubir. aquí va:

[video-parexgroup-2.mp4.zip](https://github.com/LeandroBraier/Klaukol/files/697692/video-parexgroup-2.mp4.zip)

Necesitaría que le quites también el pop up de Klaukol te busca.

abrazo

**Comment by mkreyness** [comment]
ojo que el video hay que subirlo en formato webm tambien, el viejo esta en ambos formatos. Si pongo el que me mandaste, dependiendo del navegador que este usando el que lo mira, va a ver el nuevo o el viejo.

**Comment by LeandroBraier** [comment]
Tenés razón MK. Acá creo que lo pude convertir. Decime si sirve:

[video-parexgroup-2.webm.zip](https://github.com/LeandroBraier/Klaukol/files/697763/video-parexgroup-2.webm.zip)

abrazo

**Comment by mkreyness** [comment]
Si, sirve, ahora subo este y pongo ambos en produccion.
Van tambien para Paraguay y Uruguay ?

**Comment by LeandroBraier** [comment]
si, de una. Gracias!

**Comment by mkreyness** [comment]
listo los 3.

**Comment by LeandroBraier** [comment]
Muchisimas gracias MK!! abrazo grande

**Comment by FAAREIA** [comment]
Hola Lea, cómo andan?

- Entiendo que lo del video ya esta hecho.
- Lo de LANKO solo falta sacarlo de la [Casa Interactiva](http://www.parexklaukol.com.ar/aplicaciones/casa-interactiva.html) @mkreyness 
- Lo de los logos a los micrositios los saqué del home y quedó centrado lo del Equipo Klaukol
- Saqué el modal que aparecia en el home

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Bienvenido de vuelta!!! Una alegría tenerte de vuelta. Espero la hayas pasado muy bien en las vacas.

Respecto de esto entendiste mal. Había que sacar el Logo de Lanko de las Plataformas y Micrositios, no los Logos de los Micrositios de la web. Los podrás poner de vuelta porfa?

Lo único que necesitamos como concepto general es quitar toda presencia de la marca Lanko de todos los sitios web. Según pude ver hay que sacar EL LOGO DE LANKO del footer de:

Comunidad de Vendedores

Club de Colocadores

Guía de Corralones.

abrazo

**Comment by FAAREIA** [comment]
Ok, ahi ya saqué el logo de Lanko de los Micrositios, quedaría solo lo de la Casa Interactiva

**Comment by mkreyness** [comment]
yo no lo veo, donde lo ves vos ?

**Comment by LeandroBraier** [comment]
Yo lo veo Fede. Está cargado para los techos, pero no me pidieron sacarlo
de ahí. Dejemoslo por ahora y consulto con el cliente. Queda de mi lado
esto. Muchas gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399
