### ISSUE TITLE
Constructores Furiosos con Puntos Ilimitados

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#388]
@valentinsabbath Necesito que para este viernes me liberes los puntos de Constructores Furiosos, que se pueda sumar puntos sin limites, como hicimos con Pase de Gol. Me confirmás si podés hacerlo?

abrazo

**Comment by mkreyness** [comment]
El limite no esta en el juego, esta en el sistema. Lo que se hizo para "Pase de Gol" esta hardcoded en el programa que agrega los puntos a la base de datos.
Lo tengo que tocar yo. Es un segundo. Tambien le puedo explicar a @valentinsabbath para que lo haga el, no hay problema.
Cuando decis "para el viernes" quiere decir "recien el viernes" o se puede hacer ya ?

**Comment by LeandroBraier** [comment]
Vamos a avisar que esto arranca el viernes, así lo correcto sería hacerlo el viernes. Si es un segundo te hago acordar el viernes y listo. Despreocupate.

Gracias MK! Igual explicale a Valen así no te jodo con estas cosas.

abrazo

**Comment by mkreyness** [comment]
y tiene una fecha limite de validez ? Porque lo de Pase de Gol fue hasta el 31-5-2016

**Comment by LeandroBraier** [comment]
Hasta el 21 de marzo porfa. 21-3-17

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Cómo estás?

No te olvides hoy de "ilimitar" esto hasta el 21-3

abrazo

**Comment by mkreyness** [comment]
Listo, si podes y tenes tiempo  de jugarlo, proba de sumar muchos puntos con tu usuario, y despues avisame y lo borro.
Valen: el programa es el www/parexklaukol/cgi-bin/sumapuntos.pl de siempre que llamas vos desde el juego, al cual le toque una query donde busca a ver si el usuario ya lo jugo. En el query lo que hago es ponerle "and (jue_id<>112 or current_date >'2017-03-21')" o sea que recien van a serle visibles los puntos previos ganados por el juego 112 (este de "Constructores Furiosos") cuando haya pasado el 21-03-2017

**Comment by LeandroBraier** [comment]
Muchas gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2017-01-20 8:51 GMT-03:00 mkreyness <notifications@github.com>:
