### ISSUE TITLE
Modificaciones en Info Pastinas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#389]
@mkreyness tenemos que cambiar info de las pastinas en función del Manual de Colocacion Klaukol. Esto es para @FAAREIA no?

Confirmame porfa

1) En Piezas normales Fluidas:

Sumamos Color Caoba.

<img width="769" alt="captura de pantalla 2017-01-20 a las 12 56 57 p m" src="https://cloud.githubusercontent.com/assets/6719872/22154731/7248ccbe-df0b-11e6-8eec-a77430d6e6d3.png">

Sacamos Color Coral .

Revisamos que los demás colores coincidan con el manual.

2) En Alta Performance:

Sacamos Rosa Mar y Opalo, 

Cambiamos Terra por Terracota, 

Sumamos Arena.

<img width="1216" alt="captura de pantalla 2017-01-20 a las 12 56 31 p m" src="https://cloud.githubusercontent.com/assets/6719872/22154722/65b688e2-df0b-11e6-9520-66c43f2171a4.png">

3) Quitamos el producto Pastina Klaukol Epoxi porque está cancelado.

Si es tuyo @mkreyness podrás tenerlo para la semana que viene?

abrazo

**Comment by mkreyness** [comment]
No es ni para mi ni para Fede, se hace via el CMS, fijate que en el producto "Piezas Normales Fluidas" aparece esta lista en el campo "Colores:" 
Coral; Talco; Silex; Teja; Bruma; Opalo; Boreal; Hulla; Olivina; Mercurio; Blenda; Cobre; Estano

Si el color que tenes que agregar ya existe en algun producto quiere decir que ya esta previsto en el CSS con ese nombre y simplemente tenes que agregarlo a la lista (siempre separado por puntoycoma, como el resto.
Si tenes que sacar un producto, simplemente quita el nombre.

**Comment by mkreyness** [comment]
Ahora, si aparece un color completamente nuevo, lo va a tener que agregar Fede al CSS sin duda.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/klaukol/pastina-klaukol-piezas-normales-fluidas.html
http://www.parexklaukol.com.ar/klaukol/pastina-klaukol-alta-performance-fluida.html

Revise todos los colores y estan bien excepto por el color Arena del de Alta Performance que en la foto que pones arriba tiene otro color distinto al original. Osea el color Arena original es el que se ve en el link y no el de la foto de arriba. Si el color que va es el de arriba, significa que tiene mal puesto el nombre o hay que renombrarlo

**Comment by LeandroBraier** [comment]
Gracias Fede!

Si, tendrías que cambiar al ARENA que figura en la imagen que te pasé y ver por qué no se está viendo el color Terracota. Lo demás perfecto.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, por eso te digo el color Arena es el que es porque ya esta siendo usado en otros productos. Ahora si vos queres que el color sea el que mandaste, hay que ponerle otro nombre o sino lo cambiamos pero va a cambiar en el resto de los productos que lo tengan también.
Con respecto al terracota yo lo veo bien, dale F5 o limpiate el caché

**Comment by LeandroBraier** [comment]
Hola Fede! Terracota ya lo veo bien.

En cuanto a Arena, te referís a los colores de Klaukol? Si es así modificá el color Arena porque el único producto de Klaukol que lo usa es esa Pastina.

Ahora, si te referís a productos de Parex o Revear, es otro tema. No deberían cruzarse los colores entre las marcas. Me confirmás esto cuanto antes porfa?

abrazo

**Comment by FAAREIA** [comment]
Los colores se comparten entre las marcas, el color terracota o cualquier otro es el mismo para los productos del sitio parexklaukol. Revear no tiene nada que ver con esto.
Por eso te decia que el color Arena es el actual y capas que ese color que te mandaron a vos con el nombre Arena en realidad se llama de otra forma como por ejemplo "Arena naranja"

**Comment by LeandroBraier** [comment]
Ok, te confirmo: dentro de las pastinas, el color Arena modificalo al que te pasé porfa y ya cerramos este tema.

Yo revisé y te confirmo: no hay en otros productos de Parex o Klaukol el color Arena. 

abrazo

**Comment by FAAREIA** [comment]
Job done.

**Comment by LeandroBraier** [comment]
Perfecto Fede! Gracias!!!
