### ISSUE TITLE
Mailing HTML de Login para Comunidad de Vendedores Klaukol. DEADLINE: 08/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#39]
Fede, después de que tengamos subida la comunidad de vendedores necesito tener el mailing html que le enviaremos a cada usuario de la comunidad con su link directo al login con sus datos ya escritos y en los campos. Te acordás cual te digo? Ya lo tenías armado. Solo necesitaría que me pases el HTML para hacerlo aprobar y programar con MK el envío.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no me acuerdo cual me decis. Yo en un rato me tengo que ir además. Se necesita para hoy?

**Comment by LeandroBraier** [comment]
Te puedo llamar? Porque si lo necesitaríamos hoy así lo podemos mandar mañana a la mañana.

**Comment by FAAREIA** [comment]
Si llamame dale

**Comment by LeandroBraier** [comment]
Perfecto, entonces apenas tengo el diseño te lo paso.

**Comment by LeandroBraier** [comment]
Fede, te paso el PSD para maquetar. En el HTML tendría que estar la opción para customizar el nombre del usuario y para que cada link tenga el usuario y clave ya escrito no?

https://www.wetransfer.com/downloads/e3afe624ffb132e5d4e4f6ca265fcf2220150608210440/63d9f20d5e2d56b58d75c130d9947b0e20150608210440/bea7b8

**Comment by mkreyness** [comment]
```
el link realmente deberia llevar al login con datos precargados pero
que apriete el boton "Login", o directamente al home del vendedor ya
loggeado ?

El 08/06/2015 a las 19:20,
  LeandroBraier escribió:


  Fede, te paso el PSD para maquetar. En el HTML tendría que
    estar la opción para customizar el nombre del usuario y para que
    cada link tenga el usuario y clave ya escrito no?
  https://www.wetransfer.com/downloads/e3afe624ffb132e5d4e4f6ca265fcf2220150608210440/63d9f20d5e2d56b58d75c130d9947b0e20150608210440/bea7b8
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ahi ya esta el newsletter:
http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html
Lo vinculé al login asi se autocompletan los datos. Habría que meter las variables

**Comment by LeandroBraier** [comment]
Perfecto Fede!

Me pasás como se completarían esas variables para armar la URL? Así no le
tengo que pedir a uds, ya lo resuelvo yo y no los jodo.

O cómo proponés hacerlo? Marce ya tiene cargados todos los usuarios en el
CMS; quizá se puede hacer automáticamente.

abrazo

**Comment by FAAREIA** [comment]
Si le erras 1 caracter ya falla. Yo diría que lo prepare marce.

**Comment by LeandroBraier** [comment]
Ok, entiendo. Lo hablo con Marce. Abrazo

**Comment by mkreyness** [comment]
```
Pero lo mandamos nosotros o por mailchimp ?
Yo creo que siendo 50 lo podemos mandar nosotros sin problema.
Cuando tiene que salir ?

El 09/06/2015 a las 9:09, LeandroBraier
  escribió:

Ok, entiendo. Lo hablo con Marce. Abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Yo creo que lo podemos mandar nosotros, porque lo único que necesitamos
saber es cuantos siguieron el link y listo y eso lo podemos saber por
Analytics no? No hace falta MailChimp.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
```
Y vuelvo a preguntar: esta bien que lo lleve al LOGIN (como esta
puesto ahi) ? Para mi tiene que llevarlo a la home de vendedores YA
LOGGEADO, dado que no le estamos mostrando ahi su usuario y
contraseña.

Por otra parte yo creo que HABRIA que mostrarla en el texto
justamente para que se la anote y la PROXIMA vez que quiera ingresar
sepa que poner, si no estas obligandolo a buscar el mail donde
estaba el acceso.

El 09/06/2015 a las 10:00, Marcelo
  Kreyness escribió:



  Pero lo mandamos nosotros o por mailchimp ?
  Yo creo que siendo 50 lo podemos mandar nosotros sin problema.
  Cuando tiene que salir ?

  El 09/06/2015 a las 9:09,
    LeandroBraier escribió:

  Ok, entiendo. Lo hablo con Marce. Abrazo
    —
      Reply to this email directly or view

        it on GitHub.
```

**Comment by mkreyness** [comment]
```
Supongo que si, esa parte de analytics la desconozco.

El 09/06/2015 a las 10:08,
  LeandroBraier escribió:

Yo creo que lo podemos mandar nosotros, porque lo
  único que necesitamos
  saber es cuantos siguieron el link y listo y eso lo podemos saber
  por
  Analytics no? No hace falta MailChimp.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  On Tue, Jun 9, 2015 at 10:00 AM, mkreyness
  <notifications@github.com> wrote:

  >
  >
  >
  >
  >
  > Pero lo mandamos nosotros o por mailchimp ?
  > Yo creo que siendo 50 lo podemos mandar nosotros sin
  problema.
  > Cuando tiene que salir ?
  >
  > El 09/06/2015 a las 9:09, LeandroBraier
  > escribió:
  >
  > Ok, entiendo. Lo hablo con Marce. Abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/39#issuecomment-110350071
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Datos en el Mail de origen: Tenés razón. Se lo tengo que pedir a Fede

ANALYTICS: Ok. Total cada URL va a ser diferente no? Porque incluye el
usuario y login de cada usuario, por lo cual analytics lo toma como una
página distinta.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 10:09 GMT-03:00 mkreyness notifications@github.com:

> Supongo que si, esa parte de analytics la desconozco.
> 
> El 09/06/2015 a las 10:08,
> LeandroBraier escribió:
> 
> Yo creo que lo podemos mandar nosotros, porque lo
> único que necesitamos
> saber es cuantos siguieron el link y listo y eso lo podemos saber
> por
> Analytics no? No hace falta MailChimp.
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> On Tue, Jun 9, 2015 at 10:00 AM, mkreyness

**Comment by LeandroBraier** [comment]
Fede: necesitaría sumar Usuario y Login en el newsletter. Entre la frase: "...hemos podido crearte un acceso especial" y  "Logeate automáticamente ahora" debería haber un espacio que diga:

Usuario: (XXXXXNOMBRE DE USUARIO REALXXXXX)

Password: (XXXXCLAVE REALXXXX)

Es necesario que tanto usuario como contraseña sean seleccionables como texto. Todo lo demás no hace falta, pero eso sí.

abrazo

**Comment by LeandroBraier** [comment]
Un detalle más: En la frase "tendrás fichas o números que te permitirán..." debería decir "tendrás números que te permitirán..."

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no tengo la tipografía, necesitaría que me la envies.

**Comment by LeandroBraier** [comment]
dale. ya te la paso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Olvidate de lo que te dije, ahi lo pude arreglar sin tipografía

**Comment by LeandroBraier** [comment]
Ok. Igual te las mando por mail porque el cliente me va a pasar más cambios en los textos. Aguantá un toque si querés para hacer esto.

abrazo

**Comment by mkreyness** [comment]
avisenme cuando este terminado asi hago un template en base a eso con las variables puestas donde corresponda, o mejor si ya las dejas puestas vos, Fede. El link tiene que llevar a http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?cod=&pwd= asi ya se puede trackear por Analytics, no llevar al login.html pelado.
Y en los campos que tengas que mostrar usuario y clave tambien ponele  y

**Comment by FAAREIA** [comment]
Oka, se puede ver aca igual:
http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Denle F5

**Comment by FAAREIA** [comment]
Analytics no esta puesto en la comunidad de vendedores aún. Tendrían que pasarme el código de seguimiento

**Comment by LeandroBraier** [comment]
Pero no está dentro del ParexKlaukol.com.ar? No es el mismo código o es otro?

**Comment by FAAREIA** [comment]
si, es cierto, sería el mismo
ahora cuando se defina esto lo agrego

**Comment by mkreyness** [comment]
```
pero me dejas ya puestas las variables, Fede ? No pongas esos XXXXX,
pone <!--usuario--> y <!--clave-->
Asi no laburo al pedo 20 veces cambiandolo mientras siguen ajustando
textos.
Y el link es
```

http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl?cod=&pwd=

```
no "login.html".


El 09/06/2015 a las 10:43, Federico
  Arena escribió:


  si, es cierto, sería el mismo
    ahora cuando se defina esto lo agrego
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
cambiado

**Comment by mkreyness** [comment]
```
No se toca mas entonces ?
Lean cuando habria que mandar estos mails ?
Yo no lo tengo armado todavia, pero esta tarde lo tengo listo.

El 09/06/2015 a las 11:06, Federico
  Arena escribió:


  cambiado
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
OK, esperá porque lleva cambios que estoy esperando me los valide el cliente para pedirselos a Fede. Este mail de bienvenida a la comunidad sale hoy a la tarde apenas vos puedas. 

abrazo

**Comment by mkreyness** [comment]
```
ok, vos decime cuando se puede, yo lo armo enseguida, te mando uno
de prueba, y si esta ok lo largamos.

El 09/06/2015 a las 13:15,
  LeandroBraier escribió:


  OK, esperá porque lleva cambios que estoy esperando me los
    valide el cliente para pedirselos a Fede. Este mail de
    bienvenida a la comunidad sale hoy a la tarde apenas vos puedas.

  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Fede, va texto y cambios definitivos para este mail. Cuando tengamos listo este te paso otras adaptaciones que son para mañana.

TEXTO MAIL DE BIENVENIDA  A LA COMUNIDAD:

BIENVENIDO A LA COMUNIDAD DE VENDEDORES POTENCIADOS PAREXKLAUKOL 

Un espacio de encuentro donde podés sumarte y competir con otros vendedores en divertidos juegos, trivias y todo tipo de desafíos. 

Hemos recibido tus datos personales y con ellos pudimos crearte un aceso especial.

Usuario: (XXXXXNOMBRE DE USUARIO REALXXXXX)

Password: (XXXXCLAVE REALXXXX)

Hacé clic acá para logearte automáticamente. 

Premio del mes: Sacar las fotos de todos los premios y poner una foto de paisaje de Mendoza. 

¿Cómo participo? 

JUGÁ 

Divertite demostrando de lo que sos capaz en juegos que ponen a prueba tus conocimientos y aptitudes. Competí con otros vendedores. 

SUMÁ 

Todos los puntos que puedas subiendo tu foto, la de tu corralón, conectando tu Facebook, compartiendo contenidos y jugando a los diferentes desafíos. 

GANÁ 

Cuantos más puntos sumes en el mes, más chances tendrás de ganar los premios que tenemos todos los meses. 

Agregamos Links a Facebook y Guía de Corralones con el mismo texto que en el Newsletter de Junio: 

Seguinos en Facebook y enterate de todas nuestras novedades 

Consejos prácticos, capacitaciones, tutoriales, tendencias y mucho más. 

LINK A FACEBOOK 

Nueva Guía de Corralones. Encontrá tu corralón más cercano. 

Nuestra guía online de corralones te permite desde cualquier dispositivo ubicar los corralones cercanos a la zona donde realizás tu obra. Ingresá y encontrá tu corralón más cercano. 

LINK A LA GUÍA  

FOOTER: 

parexklaukol.com.ar/vendedores/ 

Sumamos Logo de ParexGroup y los datos de contacto: 

0800-222-5528 
klaukol.marketing@klaukol.parex.com

**Comment by LeandroBraier** [comment]
Recién le pasé el texto nuevo a Fede. Cuando él lo tenga nos avisa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 13:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya lo estoy pasando. Para la prox. necesitaría un PSD más limpio u ordenado. Es un lio hacer cambios asi.

**Comment by LeandroBraier** [comment]
Ok, le pido al diseñador eso o te lo ordeno.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ya estoy con eso, digo para la prox. asi hacer los cambios de texto o mover elementos no me lleva 20 o 30m

**Comment by FAAREIA** [comment]
Ahi estan los cambios y agregados. No lo paso a imágenes porque dijiste que iba a haber más cambios. Lo que si me parece es que quedó larguisimo.
En el espacio que hay entre el texto y el botón "Hace clic aca para..." va a ir la data del usuario.

![newsletter-club-de-vendedores-x](https://cloud.githubusercontent.com/assets/6184969/8068408/1f8364c0-0eca-11e5-987a-79c148348633.png)

**Comment by mkreyness** [comment]
Este link sigue siendo valido ?

http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

**Comment by FAAREIA** [comment]
Es válido pero esta desactualizado

**Comment by mkreyness** [comment]
ok, pero lo vas a actualizar en ese mismo ?
Yo digo para poder irlo programando, aunque despues cambie la estetica, 
porque la tarde es como que se esta terminando y lo querian mandar hoy.

Acordate cambiar los links que llevan a login.html por lo que te pase.

**Comment by FAAREIA** [comment]
Según entendí, faltan cambios. Pero si Lea dice que ya lo hagamos lo paso a imágenes.
Ok los links

**Comment by LeandroBraier** [comment]
Pará. Te paso dos cambios simples:

1) Poner el botón de "HACÉ CLIC ACÁ PARA LOGEARTE AUTOMÁTICAMENTE" arriba
de los datos de Usuario y Clave.

2) Hacer el footer del logo de ParexGroup como en el Newsletter Novedades
Junio: con logo de ParexGroup a la izquierda y el 0800 y el mail en el
margen derecho.

Lo demás perfecto. Por ahora no va a haber más modificaciones.

abrazo

**Comment by FAAREIA** [comment]
Actualizado:
http://www.parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

**Comment by mkreyness** [comment]
Ok, Lean necesito:
- asunto del mail
- quien lo manda (nombre y direccion)

Obviamente si todavia hay cambios pendientes en los juegos no lo puedo 
mandar, pero por lo menos quiero tenerlo listo.

**Comment by LeandroBraier** [comment]
Ok. Aqui va:

From: Novedades ParexKlaukol klaukol.marketing@klaukol.parex.com
Asunto: XXXUSUARIOXXX, bienvenido/a a la Comunidad de Vendedores
Potenciados ParexKlaukol

Tenelo listo para enviar nomás. Yo te aviso.

abrazo

**Comment by mkreyness** [comment]
Mas tarde ajusto esto, pero andar ya anda.

Fede hice un par de toques, decia "aceso" en vez de "acceso" le puse la 
eñe como &ntilde; porque en el mail me llegaba mal, y al final te habia 
pasado mal los nombres de los parametros en el URL, ya esta todo 
ajustado (te digo por si tenes que tocar algo mas, lo hagas sobre lo que 
esta en el server.

**Comment by LeandroBraier** [comment]
Gracias a los dos! Son unos genios.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 20:03 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Marce, cuando tengamos listo el sitio de vendedores cerramos y mañana
temprano te confirmo para mandar los mails.

Gracias por toda la polenta que le están poniendo.

abrazo grande

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-09 20:12 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by mkreyness** [comment]
```
Pero viste mis dudas sobre los puntajes ?

El 09/06/2015 a las 23:14,
  LeandroBraier escribió:

Marce, cuando tengamos listo el sitio de vendedores
  cerramos y mañana
  temprano te confirmo para mandar los mails.

  Gracias por toda la polenta que le están poniendo.

  abrazo grande

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-09 20:12 GMT-03:00 Leandro Braier
  <leandrobraier@gmail.com>:

  > Gracias a los dos! Son unos genios.
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  > Móvil 1158717399
  >
  > 2015-06-09 20:03 GMT-03:00 mkreyness
  <notifications@github.com>:
  >
  >> Mas tarde ajusto esto, pero andar ya anda.
  >>
  >> Fede hice un par de toques, decia "aceso" en vez de
  "acceso" le puse la
  >> eñe como &ntilde; porque en el mail me llegaba mal, y
  al final te habia
  >> pasado mal los nombres de los parametros en el URL, ya
  esta todo
  >> ajustado (te digo por si tenes que tocar algo mas, lo
  hagas sobre lo que
  >> esta en el server.
  >>
  >>
  >> On 09/06/2015 08:00 p.m., LeandroBraier wrote:
  >> > Ok. Aqui va:
  >> >
  >> > From: Novedades ParexKlaukol
  <klaukol.marketing@klaukol.parex.com>
  >> > Asunto: XXXUSUARIOXXX, bienvenido/a a la Comunidad
  de Vendedores
  >> > Potenciados ParexKlaukol
  >> >
  >> > Tenelo listo para enviar nomás. Yo te aviso.
  >> >
  >> > abrazo
  >> >
  >> > —
  >> > Reply to this email directly or view it on GitHub
  >> > <
  >>
```

https://github.com/LeandroBraier/Klaukol/issues/39#issuecomment-110527696
      >> >.
      >>
      >> >
      >>
      >> —
      >> Reply to this email directly or view it on GitHub
      >>
https://github.com/LeandroBraier/Klaukol/issues/39#issuecomment-110528081
      >> .
      >>
      >
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Si. Te respondí. Los puntajes de cada acción están todos detallados en el
Front. Me parecen bien por ahora y es lo que vio el cliente.

Te los paso por el otro ticket por las dudas:

abrazo

**Comment by mkreyness** [comment]
```
No veo la respuesta en ningun lado. Yo toque todo poniendoles 30 a
cada posiibilidad de juego, pero estaban en 40, 120, cualquier cosa
antes.

El 10/06/2015 a las 0:02, LeandroBraier
  escribió:

Si. Te respondí. Los puntajes de cada acción están
  todos detallados en el
  Front. Me parecen bien por ahora y es lo que vio el cliente.

  Te los paso por el otro ticket por las dudas:

  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ahi la estoy terminando de subir en el otro ticket para no mezclar tickets. Te paso mi opinión, no está confirmada por el cliente aún, pero hacelo en base a eso por favor.

abrazo

**Comment by mkreyness** [comment]
```
Queres que te mande el mail de bienvenida al usuario LeandroBraier
asi ves como quedó ?

El 10/06/2015 a las 0:10, LeandroBraier
  escribió:


  Ahi la estoy terminando de subir en el otro ticket para no
    mezclar tickets. Te paso mi opinión, no está confirmada por el
    cliente aún, pero hacelo en base a eso por favor.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Exacto!

Justo eso te iba a pedir.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-10 11:25 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
ahi salio para gmail.

El 10/06/2015 a las 11:35,
  LeandroBraier escribió:

Exacto!

  Justo eso te iba a pedir.

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-10 11:25 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Queres que te mande el mail de bienvenida al usuario
  LeandroBraier
  > asi ves como quedó ?
  >
  > El 10/06/2015 a las 0:10, LeandroBraier
  > escribió:
  >
  >
  > Ahi la estoy terminando de subir en el otro ticket para no
  > mezclar tickets. Te paso mi opinión, no está confirmada por
  el
  > cliente aún, pero hacelo en base a eso por favor.
  >
  > abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/39#issuecomment-110772984
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Genial MK. Lo veo perfecto. Confirmo con el cliente.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-10 11:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, me pidieron un cambio sencillo en el mail. Cuando vuelvas hagamoslo así ya mandamos los mails. Te copio una imagen acá que explica el cambio. El texto debería ser este (el de la imagen tiene faltas de ortografía y gramática):

"Demostrá de lo que sos capaz en juegos que ponen a prueba tus conocimientos y aptitudes, compitiendo con otros vendedores. Jugá, Sumá y Ganá!"

![unico cambio en mail de envio a vendedores](https://cloud.githubusercontent.com/assets/6719872/8090658/cff07f30-0f85-11e5-8feb-f9f71ef5b430.gif)

**Comment by FAAREIA** [comment]
Actualizado. Denle F5.

**Comment by LeandroBraier** [comment]
Perfecto Fede!

MK: Mañana a la mañana largá nomás los mails a la base que ya tenés cargada y a la que te mandé hoy nueva en Excel, ya con nombres de usuario, nombre y apellido separado y claves puestas. La recibiste a esa?

**Comment by mkreyness** [comment]
```
No, no recibi ningun excel tuyo desde el dia 8.

El 10/06/2015 a las 20:06,
  LeandroBraier escribió:


  Perfecto Fede!
  MK: Mañana a la mañana largá nomás los mails a la base que ya
    tenés cargada y a la que te mandé hoy nueva en Excel, ya con
    nombres de usuario, nombre y apellido separado y claves puestas.
    La recibiste a esa? 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
Lean te lo mando de vuelta asi chequeas.
Una cosa que me parece que nos comimos es que esto no tiene un link
"ver este mail online".

El 10/06/2015 a las 20:02, Federico
  Arena escribió:


  Actualizado. Denle F5.
  —
    Reply to this email directly or view
      it on GitHub.
```
