### ISSUE TITLE
Modificación de Textos en Sección Ventajas de Web Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#390]
@FAAREIA necesito que modifiques el texto en VENTAJAS DE REVESTIMIENTO. 

Sería reemplazar este texto:
![core](https://cloud.githubusercontent.com/assets/6719872/22481118/c6599304-e7d2-11e6-9a6d-6db4347e8bf0.jpg)

Por este:
**Los arquitectos aseguran que la aplicación de Revear reduce un 30% los costos frente al uso de revoque fino + enduido + pintura acrílica tradicional.**

Puede ser para mañana. Confirmame nomás. abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !
