### ISSUE TITLE
Mailing HTML para Lanzamiento Comunidad de Vendedores No Customizado. DEADLINE: 11/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#41]
Fede, necesito una adaptación del mailing de bienvenida con el siguiente texto.

¿TODAVÍA NO TE SUMASTE A LA COMUNIDAD DE VENDEDORES POTENCIADOS PAREXKLAUKOL?

Un espacio de encuentro donde podés sumarte y competir con otros vendedores en divertidos juegos, trivias y todo tipo de desafíos. 

Hacé clic acá para ir a la comunidad. 

Reemplazamos "Premio del mes" por "Miles de pesos en premios todos los meses" 

Acá sí van las fotos de los distintos premios que había en el PSD original

A partir de "¿Cómo participo?" es todo igual al otro mailing.

A modo de referencia te paso el PSD original por si necesitás algo, pero basate en el que ya corregiste y ya tenés.

https://www.wetransfer.com/downloads/6e02114b234557a8635ed52ac238289120150608135351/13db153cbba9400497f7369f52bb249120150608135351/2fc7b4

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-ir/vendedores-ir.html

**Comment by LeandroBraier** [comment]
Este está perfecto, Fede. Cuando tengo el OK del cliente lo enviamos nomás.

abrazo

**Comment by LeandroBraier** [comment]
Me piden un cambio más. Viste el Jugá, Sumá y Ganá del párrafo largo? El que empieza "Demostrá de lo que sos capaz..."?

Necesito que esté destacado en tipografía más grande, como la del ¿Cómo Participo?

Eso solo en ambos mailings y ya estamos.

**Comment by FAAREIA** [comment]
Ahi esta actualizado Lea. Dale F5.

**Comment by LeandroBraier** [comment]
No lo entendiste bien, Fede.

No quiero que agrandes TODO EL TEXTO. Solo la frase "Jugá, Sumá y Ganá". Lo demás que quede como estaba.

Este cambio aplicalo al Mailing de Bienvenida también porfa.

**Comment by FAAREIA** [comment]
Ahi va. F5

**Comment by FAAREIA** [comment]
Ahi esta también en el de bienvenida.
