### ISSUE TITLE
Mailing HTML para Lanzamiento Comunidad de Vendedores ADAPTADO A CONSTRUYENDO RELACIONES. DEADLINE: 11/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#42]
Fede, esta adaptación es casi igual a la anterior. Solo cambia que, debajo del titular que dice:

¿TODAVÍA NO TE SUMASTE A LA COMUNIDAD DE VENDEDORES POTENCIADOS PAREXKLAUKOL?

el texto sería el siguiente:

Te invitamos a participar de  la Comunidad de Vendedores, el nuevo programa de premios de Parexklaukol. Un espacio de encuentro donde podés sumarte y competir con otros vendedores en divertidos juegos, trivias, cursos y todo tipo de desafíos. Por haber participado del Programa Construyendo Relaciones ya te encontrás inscripto.  

BOTÓN: Hacé clic acá para ingresar a la comunidad (este botón funciona igual que el "logeate automáticamente" del mailing de bienvenida)

Todo lo demás es igual. Cualquier cosa me avisás.

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-existente/vendedores-existente.html

**Comment by LeandroBraier** [comment]
Está casi perfecto, Fede. Solo quitá la palabra cursos de la parte en que dice: "divertidos juegos, trivias, cursos y todo tipo de desafíos".

abrazo

**Comment by FAAREIA** [comment]
Ahi lo arreglé. Dale F5.

**Comment by LeandroBraier** [comment]
Me piden un cambio más. Viste el Jugá, Sumá y Ganá del párrafo largo? El que empieza "Demostrá de lo que sos capaz..."?

Necesito que esté destacado en tipografía más grande, como la del ¿Cómo Participo?

Eso solo en ambos mailings y ya estamos.

**Comment by FAAREIA** [comment]
Ahi esta actualizado Lea. Dale F5.

**Comment by LeandroBraier** [comment]
No lo entendiste bien, Fede.

No quiero que agrandes TODO EL TEXTO. Solo la frase "Jugá, Sumá y Ganá". Lo demás que quede como estaba.

Este cambio aplicalo al Mailing de Bienvenida también porfa.

**Comment by LeandroBraier** [comment]
Además destacalo con algo más, no solo con la tipografía.

**Comment by FAAREIA** [comment]
Ahi va. F5

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo

**Comment by LeandroBraier** [comment]
Fede, me pidieron un cambio MUY mínimo en el newsletter antes de enviarlo. Donde dice "Inscripto" que diga "preinscripto". Lo llegás a modificar hoy así hacemos el envío a la tarde? Confirmame porfa.

**Comment by FAAREIA** [comment]
Hecho, dale F5
