### ISSUE TITLE
Pequeña corrección: cambiar link de destino CFT en la web ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#43]
Buen día Braulio! Te pido un detalle muy simple que pidió el cliente que cambiemos en la web. En el link que lleva al CFT Online, que en lugar de llevar al sitio web lleve al canal de YouTube del CFT.

https://www.youtube.com/CFTonline

Confirmame porfa cuando esté hecho.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
