### ISSUE TITLE
Vendedores #2: Compartir contenido y Página

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#45]
Buen día Fede, necesito dos cosas simples en la Comunidad lo antes posible.

1) EN la Home, debajo del botón Compartí y Ganá, que se pueda dar Me gusta y Compartir la página de la comunidad de Vendedores en Facebook y que eso sume 40 puntos.

2) En la parte de Facebook del Contenido, que al lado del Me gusta esté el Compartir y que los dos sumen 40 puntos cada acción.

Avisame cuando esté porfa.

abrazo

**Comment by mkreyness** [comment]
```
Perdon que me meta, pero el tema de sumar puntos lo tengo que hacer
yo, y vuelvo a decirles que el "Compartir" no tiene feedback, solo
puedo saber si usaron el "Like".
Por este motivo habiamos SACADO el boton "Compartir" del juego y
dejado solo el "Like".

El 15/06/2015 a las 8:02, LeandroBraier
  escribió:


  Buen día Fede, necesito dos cosas simples en la COmunidad lo
    antes posible.
  1) EN la Home, debajo del botón Compartí y Ganá, que se pueda
    compartir la página de la comunidad de Vendedores en Facebook y
    que eso sume 40 puntos.
  2) En la parte de Facebook del Contenido, que al lado del Me
    gusta esté el Compartir y que los dos sumen 40 puntos cada
    acción.
  Avisame cuando esté porfa.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ponganlo igual por favor. Y pensemos la forma de que sume puntos igual,
tiene que haber una forma, aunque sea por atrás. De última si alguien
responde todo y solo nos queda saber si compartió sumemosle los 40 puntos
igual. serian 40 por like y 40 por compartir. No se si soy claro.

1) el cliente tiene que percibir que damos puntos por compartir.

2) si le damos los 40 a todos los que hicieron todo menls compartir no se
va a dar cuenta y estamos bien.

Abrazo

**Comment by mkreyness** [comment]
```
Para hacerlo de otra manera NO hay que usar el widget automatico que
esta poniendo Fede, el cual no tiene feedback, llama directamente a
algo en Facebook fuera de nuestro control.
Fijate si podes ponerle algo mas custom Fede en el cual podamos
tener control sobre lo que haga el boton.

El 15/06/2015 a las 10:47,
  LeandroBraier escribió:

Ponganlo igual por favor. Y pensemos la forma de que
  sume puntos igual,
  tiene que haber una forma, aunque sea por atrás. De última si
  alguien
  responde todo y solo nos queda saber si compartió sumemosle los 40
  puntos
  igual. serian 40 por like y 40 por compartir. No se si soy claro.

  1) el cliente tiene que percibir que damos puntos por compartir.

  2) si le damos los 40 a todos los que hicieron todo menls
  compartir no se
  va a dar cuenta y estamos bien.

  Abrazo
  El jun 15, 2015 10:43 a.m., "mkreyness"
  <notifications@github.com> escribió:

  >
  >
  >
  >
  >
  > Perdon que me meta, pero el tema de sumar puntos lo tengo que
  hacer
  > yo, y vuelvo a decirles que el "Compartir" no tiene feedback,
  solo
  > puedo saber si usaron el "Like".
  > Por este motivo habiamos SACADO el boton "Compartir" del
  juego y
  > dejado solo el "Like".
  >
  > El 15/06/2015 a las 8:02, LeandroBraier
  > escribió:
  >
  >
  > Buen día Fede, necesito dos cosas simples en la COmunidad lo
  > antes posible.
  > 1) EN la Home, debajo del botón Compartí y Ganá, que se pueda
  > compartir la página de la comunidad de Vendedores en Facebook
  y
  > que eso sume 40 puntos.
  > 2) En la parte de Facebook del Contenido, que al lado del Me
  > gusta esté el Compartir y que los dos sumen 40 puntos cada
  > acción.
  > Avisame cuando esté porfa.
  > abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/45#issuecomment-112075257
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by FAAREIA** [comment]
Realmente desconozco si se puede enviar el like o compartir sin el widget de facebook. Nunca lo hice asi. Si me confirmas que se puede hacer igual sin el widget, te genero un botón igual al que renderiza FB y listo

**Comment by mkreyness** [comment]
```
Seguro que se puede, pero dejamelo armado en otro lugar en paralelo
asi voy viendo que agregarle.

El 15/06/2015 a las 11:54, Federico
  Arena escribió:


  Realmente desconozco si se puede enviar el like o compartir sin
    el widget de facebook. Nunca lo hice asi. Si me confirmas que se
    puede hacer igual sin el widget, te genero un botón igual al que
    renderiza FB y listo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Create o agrega a cualquier html que quieras un `<button type="button">Like / Share</button>` y probate con eso. En realidad el tag mucho no importa, pero ese sería el correcto. Si te anda, voy y lo estilizo.

**Comment by mkreyness** [comment]
Listo, fijate aca:

http://www.parexklaukol.com.ar/vendedores/ejemplo-share.html

Y tiene un callback !! Fijate lo que pasa cuando shareas, y cuando no 
shareas.

**Comment by LeandroBraier** [comment]
Fede, no te olvides de que en la Home también tiene que haber un Me gusta y un Compartir de la Página en General.

abrazo

**Comment by FAAREIA** [comment]
Pregunto, el like lo dejo igual que antes?
El código que empieza con "window.fbAsyncInit..." lo copio tal cual y lo agrego o lo reemplazo por el que creo que ya estaba?

**Comment by mkreyness** [comment]
```
Si, el like dejalo como estaba que ya tenemos otra forma de
atraparlo.
Lo del fbAsyncInit hay que mergearlo. No me acuerdo lo que tenia, de
que template estamos hablando ?

El 16/06/2015 a las 13:00, Federico
  Arena escribió:


  Pregunto, el like lo dejo igual que antes?
    El código que empieza con "window.fbAsyncInit..." lo copio tal
    cual y lo agrego o lo reemplazo por el que creo que ya estaba?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
Fede como viene esto ? Avisame cuando ya este el boton en el/los templates que corresponda (una copia que no sea la que esta en produccion) asi le agrego el codigo del callback que haga que sume puntos, lo pruebo y pongo todo junto en produccion.

**Comment by LeandroBraier** [comment]
Buen día chicos!

Ahora lo hablamos en la reunión pero este tema es prioridad nº 1 hoy.
Necesitaría tenerlo en producción cuanto antes.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-16 23:47 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede: hoy necesitaba tenerlo subido y funcionando en producción. ¿Qué pasó?

**Comment by FAAREIA** [comment]
Hecho, ya esta puesto en la columna derecha y en el juego mismo. Falta insertarle el código nomás.

**Comment by mkreyness** [comment]
```
Ahora me pongo con eso

El 18/06/2015 a las 9:01, Federico
  Arena escribió:


  Hecho, ya esta puesto en la columna derecha y en el juego
    mismo. Falta insertarle el código nomás.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
Ya esta puesto el codigo, entonces ahora hay 4 actividades de facebook distintas:
Estas dos que son fijas y se pueden usar desde cualquier pagina:
- "unirse" a la comunidad que es el Like de ARRIBA (lo que teniamos de antes)
- "compartir" la comunidad que es el Share de ABAJO

Estas que son "tematicas" y tienen (o van a tener) diferentes instancias a medida que aparezcan mas temas X :
- "dar me gusta" al tema X (lo que teniamos de antes)
- "compartir" el tema X

Cada cosa suma puntos por separado y puede hacerse una sola vez.
Habria que revisar CUANTOS puntos tiene que dar c/u Lean, igual esta todo por el CMS y se puede cambiar.

**Comment by LeandroBraier** [comment]
Gracias @mkreyness ! 

Yo le había dicho a @FAAREIA  en este ticket lo de los puntos pero lo refresco y actualizo punto por punto de los que vos marcás:

. "unirse" a la comunidad que es el Like de ARRIBA (lo que teniamos de antes) 40 puntos
. "compartir" la comunidad que es el Share de ABAJO 40 puntos

. "dar me gusta" al tema X (lo que teniamos de antes) 20 puntos
. "compartir" el tema X 40 puntos

Lo actualizo acá, así que guiate por esta puntuación nomás.

Ya está funcionando entonces?

abrazo
