### ISSUE TITLE
Detalle #1 Web ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#48]
Braulio, cómo andás? Un pedido bastante simple que necesitamos lo antes posible.

Quitar el link de Construyendo Relaciones de la web de ParexKlaukol Argentina.

![links construyendo](https://cloud.githubusercontent.com/assets/6719872/8169746/fbeaeb34-1381-11e5-86ac-5420d2b3b639.jpg)

avisame si lo podemos sacar hoy porfa.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
