### ISSUE TITLE
Detalle #2 WebParexKlaukol. DEADLINE: 16/06

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#49]
Brau, te paso otro pedido simple. Hay que cambiar el producto Klaukol Impermeable Fluido en la web por el producto Klaukol Impermeable Potenciado (el mismo sobre el cual hicimos el micrositio en parexklaukol.com.ar/klaukol-impermeable-potenciado/)

Fijate en el ppt que te pasé por wetransfer aquí que está detallado qué hay que cambiar en cada caso.

https://www.wetransfer.com/downloads/5454d57435aa7a4875f0280100a4f30920150615204255/31c15d

Cualquier duda me avisás.

abrazo

**Comment by LeandroBraier** [comment]
Se lo reasigné a Fede.

**Comment by LeandroBraier** [comment]
No te olvides de este @FAAREIA es una pavada y me lo están pidiendo medio urgente.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya hice mi parte en este tema. Hay que pedirle a @mkreyness que haga el resto.
La landing page es:
http://parexklaukol.com.ar/klaukol-impermeable-potenciado/

@LeandroBraier Habría que bajarse el video y subirlo a youtube. Marce sino no puede subirlo.

**Comment by LeandroBraier** [comment]
El video ya está subido en YouTube. Paso el link:

https://www.youtube.com/watch?v=Az9zTS-5LE4

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 14:19 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Esta bien ese URL ? No tendria que ser el que dice "embed" ?

**Comment by FAAREIA** [comment]
Si, el watch no es. Es la url que tiene el embed

**Comment by mkreyness** [comment]
pero es el video de siempre, tiene fecha de mayo. No entiendo que es lo que estan cambiando/tengo que hacer.

**Comment by mkreyness** [comment]
Ah, que el que vino del XML original era otro viejo, ok, ahi le puse este.

**Comment by LeandroBraier** [comment]
Gracias MK!

Fede: la imagen del producto, la ficha técnica, la hoja técnica y la
presentación multimedia siguen con el producto viejo. Hay que actualizar
eso también por favor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Reitero, eso no se hace desde el CMS. No se puede.

**Comment by LeandroBraier** [comment]
Ok, Marce. Entonces necesito que cambies eso. La ficha técnica la tenés en
el micrositio. La presentación multimedia es la ficha técnica subida a no
se donde. El pack del producto también.

Fijate si necesitás algo más pero metamosle para que esté hoy.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
OK, del micrositio pude tomar la ficha tecnica.
En el CMS (proveniente del XML) tengo OTRA cosa llamada "Hoja Tecnica" que no se que es, la saco ?
La presentacion multimedia no puede ser la ficha tecnica. Yo veo un slideshow en el micrositio pero es un conjunto de fotos, no es algo real.
No se a que llamas "el pack del producto", es la foto ? Usamos la que se muestra en el juego ?

**Comment by mkreyness** [comment]
Lean fijate mis preguntas, hoy a la noche no voy a estar trabajando, asi que si "tiene que estar para hoy" mas vale que sea ya.

**Comment by LeandroBraier** [comment]
Perdón, te iba a responder.

HOJA TÉCNICA: Volala nomás, no hace falta.

PRESENTACIÓN MULTIMEDIA: Es la Ficha Técnica en PDF subida a Scribd. Dejame que la subo y te la paso mañana. Dejala como está a esa por ahora.

PACK DEL PRODUCTO: Si, usemos la que se muestra en el juego o esta imagen que te paso aquí:

![producto klaukol potenciado definitivo](https://cloud.githubusercontent.com/assets/6719872/8243736/0ae15a5e-15f0-11e5-9d00-be035fd18efd.png)

abrazo

**Comment by mkreyness** [comment]
Listo sacada la "hoja tecnica" y reemplazado el pack con este que pusiste.
Ojo que tambien se usa una imagen para thumbnail que esta vieja (dice 
fluido, chiquito).

Probe de poner esta misma y obviamente quedaba gigante y mal.
Ya repuse la que estaba (tarda 1 min en updatear).
Habria que tener una de thumbnail.

Todo esto tendria que poder manejarse mejor desde el CMS pero como tiene 
fijas rutas que se agregan DELANTE de lo que se pone en el CMS (a la 
carpeta de backup) por ahora no se puede.
En algun momento de tranquilidad (que no es este) va a haber que 
emprolijarlo y no usar nada de los backups, sino pasar lo util a 
carpetas manejadas por el CMS.

**Comment by LeandroBraier** [comment]
Ok, MK. Gracias por todo el esfuerzo de hoy!

Te paso imagen de thumbnail para cuando tengas tiempo de cambiarla.

![thumbnail-kip](https://cloud.githubusercontent.com/assets/6719872/8244396/9c886c08-15f6-11e5-90d9-57f2e0635d13.png)

abrazo

**Comment by mkreyness** [comment]
Ok, vuelvo tarde pero tratare de dejarla puesta

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
No hay apuro Marce.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 20:49 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
listo

**Comment by LeandroBraier** [comment]
Gracias MK!

Apenas tengo subido a Scribd el pdf te lo paso.

**Comment by LeandroBraier** [comment]
Me dijeron que no subamos nada a Scribd, que eso se cancela. Así que quitemos la parte de Presentación Multimedia de la página del Producto y estamos. Gracias!

**Comment by mkreyness** [comment]
OK, se los saco. Por si acaso hubiera que reponer algo, este es el link que habia:

http://www.scribd.com/embeds/59511034/content?start_page=1&view_mode=list&access_key=key-56o8q1q9wkn0z2xyhou

y este otro al hacer click ahi

http://es.scribd.com/doc/59511034/Ficha-Tecnica-Klaukol-Impermeable-Fluido
