### ISSUE TITLE
Maquetación ParexKlaukol Web 2.0

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#50]
Fede, con MK estuvimos viendo los motores y aplicaciones que nos quedaron pendientes en la web para la versión 2.0. Hoy están razonablemente andando.

SITIO KLAUKOL

1) Calculador de Materiales: Casi listo.
http://www.parexklaukol.com.ar/aplicaciones/calculador.html
 Detalles a solucionar:
- El encoding raro de las superficies/texturas etc. (*)
- que los links a productos que hay en c/u redirijan a los productos actuales (corre por cuenta de Lean, que tiene que pasar a MK una tabla de equivalencias.)

2) Casa Interactiva: Casi listo.
http://www.parexklaukol.com.ar/aplicaciones/casa-interactiva.html

Detalles a solucionar:
- que los links a productos que hay en c/u redirijan a los productos  actuales (MK esperando tabla de equivalencias de Lean)

SITIO PAREX

3) Simulador de Fachadas: Listo.
http://www.parexklaukol.com.ar/aplicaciones/simulador-de-fachadas.html

4) Cotiza tu obra: Listo.
http://www.parexklaukol.com.ar/aplicaciones/cotiza-tu-obra.html

(*) esto se comprometió a limpiarlo MK a mano en la base, siendo que no tenemos un CMS para que pueda accederlo Lea.

Lo que necesitamos que hagas, Fede, en los 4 casos, es maquetar el header y el footer que enmarcan este contenido, los cuales deberían estar minimamente adaptados a la estética actual del sitio mejorada. 

Tené en cuenta que estas son las aplicaciones que tenemos más urgencia de resolver, correspondientes a Klaukol y Parex. Las del sitio de Revear son segunda prioridad después de estas y te las voy a pasar en un ticket aparte.

Confirmame si podríamos tener estas maquetaciones para el viernes.

abrazo

**Comment by mkreyness** [comment]
```
La base ya la limpie, deberian salir bien los textos de los
desplegables, si ven algo feo me avisan.

El 15/06/2015 a las 22:00,
  LeandroBraier escribió:


  Fede, con MK estuvimos viendo los motores y aplicaciones que
    nos quedaron pendientes en la web para la versión 2.0. Hoy están
    razonablemente andando.
  SITIO KLAUKOL
  1) Calculador de Materiales: Casi listo.
    http://www.parexklaukol.com.ar/aplicaciones/calculador.html
    Detalles a solucionar:

    El encoding raro de las superficies/texturas etc. (*)
    que los links a productos que hay en c/u redirijan a los
      productos actuales (corre por cuenta de Lean, que tiene que
      pasar a MK una tabla de equivalencias.)

  2) Casa Interactiva: Casi listo.
    http://www.parexklaukol.com.ar/aplicaciones/casa-interactiva.html
  Detalles a solucionar:

    que los links a productos que hay en c/u redirijan a los
      productos actuales (MK esperando tabla de equivalencias de
      Lean)

  SITIO PAREX
  3) Simulador de Fachadas: Listo.
    http://www.parexklaukol.com.ar/aplicaciones/simulador-de-fachadas.html
  4) Cotiza tu obra: Listo.
    http://www.parexklaukol.com.ar/aplicaciones/cotiza-tu-obra.html
  (*) esto se comprometió a limpiarlo MK a mano en la base,
    siendo que no tenemos un CMS para que pueda accederlo Lea.
  Lo que necesitamos que hagas, Fede, en los 4 casos, es maquetar
    el header y el footer que enmarcan este contenido, los cuales
    deberían estar minimamente adaptados a la estética actual del
    sitio mejorada. 
  Tené en cuenta que estas son las aplicaciones que tenemos más
    urgencia de resolver, correspondientes a Klaukol y Parex. Las
    del sitio de Revear son segunda prioridad después de estas y te
    las voy a pasar en un ticket aparte.
  Confirmame si podríamos tener estas maquetaciones para el
    viernes.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/calculador.html
http://parexklaukol.com.ar/casa-interactiva.html
http://parexklaukol.com.ar/cotiza-tu-obra.html
http://parexklaukol.com.ar/simulador-de-fachadas.html

Necesitaría que cargue el iframe o el .swf @mkreyness ¿podrías poner las rutas?

**Comment by mkreyness** [comment]
No va a andar nada si no los pones en la carpeta /aplicaciones, esa carpeta es un link interno a la posicion del backup donde estan todos los recursos que usan, si no esta ahi seguro que no va a andar nada (no todo es .swf, hay accesos a la base de datos que dependen de cosas de php que se ejecutan desde ahi). Fijate todo esto mismo pero con /aplicaciones/ puesto, y ahi vas a ver en cada IFRAME la ruta del .swf correspondiente.

**Comment by mkreyness** [comment]
Aparte ya los habia puesto antes en algun lado. Este es el iframe del calculador, ves que esto no es es SWF, necesita estar ahi.
<iframe src="http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar/simulador/calculador.php" width="100%" height="560" frameborder="0" allowtransparency="true">

**Comment by mkreyness** [comment]
mmmm, me parece que no se puede pegar HTML aca, solo se ve un tag de p.

**Comment by mkreyness** [comment]
Calculador:
Este es el unico que tiene un path absoluto
http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar/simulador/calculador.php

El resto son relativos a lo que yo llame "aplicaciones" (que en realidad es "www/_backup/parexklaukol/"

Casa Interactiva:
media/wysiwyg/casa-interactiva.swf
Simulador:
simulador/simulador-paso1.html
Cotiza tu obra:
media/wysiwyg/calculador.swf

**Comment by FAAREIA** [comment]
Entonces como hago para no duplicar toda la carpeta include, css y js? Tener cosas asi duplicadas nunca es práctico.
Para poner código fijate en https://guides.github.com/features/mastering-markdown/

**Comment by mkreyness** [comment]
Ponele en el head de estas paginas los paths absolutos a los /js, /includes y /css que necesites en vez de relativos (js, include y css) y todo te lo tendria que tomar de la correcta, no hay por que duplicar nada.
Acordate que todo esto es un pasticho provisorio para sacarnos el problema de encima hasta que nos contraten para rehacer las aplicaciones, sobre las cuales actualmente no tenemos real control.

**Comment by FAAREIA** [comment]
Pero eso no rompería la ruta del src del iframe o el object?

**Comment by mkreyness** [comment]
```
No, por que ? Cada src es independiente.
No digo que pongas un "base href", digo que donde dice

script src="js/pepito.js"

diga

script src="/js/pepito.js"

etc.
Con eso usas siempre los mismos (los que dependen de
parexklaukol.com.ar, o sea /www/parexklaukol)

El 19/06/2015 a las 9:06, Federico
  Arena escribió:


  Pero eso no rompería la ruta del src del iframe o el object?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ahora pruebo ;)

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/aplicaciones/calculador.html
http://www.parexklaukol.com.ar/aplicaciones/casa-interactiva.html
http://www.parexklaukol.com.ar/aplicaciones/simulador-de-fachadas.html
http://www.parexklaukol.com.ar/aplicaciones/cotiza-tu-obra.html

Si los ven OK, ya los linkeo desde la web

**Comment by LeandroBraier** [comment]
Fede, yo los veo OK. Solo te pido lo siguiente: quitale el título en rojo
que le agregaste a los tres primeros (Calculador, Casa Interactiva y
Simulador de Fachadas). En esos 3 está de más. En Cotizá tu Obra dejalo
porque está bien.

Cuando tengas eso listo dejalo todo listo para subir pero no lo subas a
producción todavía. Agendate para subirlo el miércoles 24/06, que es el
miércoles que viene. Es para que el cliente no reciba esto y empiece a
pedir más cosas siendo que estamos a full con el resto de las tareas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

**Comment by LeandroBraier** [comment]
Fede, subilo hoy a producción si podés así le aviso al cliente que ya está.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya lo puse en Argentina. Para Uruguay y Paraguay son los mismos?

**Comment by mkreyness** [comment]
Mmmm, yo no toque nada de esto para Uruguay y Paraguay, ojo.

**Comment by LeandroBraier** [comment]
Son los mismos, sí, salvo los dominios a los que llevan los links. @mkreyness si necesitás que te adapte los excel para uruguay y paraguay avisame y pasame el excel modelo si cambiaste algo del que te mandé antes.

abrazo

**Comment by FAAREIA** [comment]
Osea que Argentina, Uruguay y Paraguay apuntan a los mismos links. Nada varia entre dominio y dominio en el calculador o la casa interactiva por ejemplo?

**Comment by LeandroBraier** [comment]
NO, no son los mismos. Habría que cambiar los dominios ahí. Lo veo con MK.

Fede, respecto del Cotizador de Parex, desde donde accedo a él en la web online ahora?

**Comment by FAAREIA** [comment]
Creo que en su momento lo habíamos sacado porque no iba a estar más.

**Comment by LeandroBraier** [comment]
Jaja Quién lo había dicho? Yo no recuerdo que el cliente lo haya pedido.
Incluyamos el link así lo podemos presentar porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 15:10 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, tengo que ver como era que iba. No linkearía a nada por ahora. Recien podría hacerlo mañana a la mañana.

**Comment by LeandroBraier** [comment]
Ok. Anotatelo para mañana a la mañana y avisame cuando esté porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 15:33 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Volviendo al tema uruguay/paraguay en las 4 aplicaciones, yo no se si los PRODUCTOS son los mismos para los tres paises, me suena que no, pero nosotros nunca recibimos una base de datos de uruguay o de paraguay, solo de Argentina, o sea que todas las bases de calculo que aplican y los resultados que muestran son validos para los 3 paises.

**Comment by LeandroBraier** [comment]
Si, Marce. Las bases de cálculo y los productos son los mismos en general.
Solo que hay diferencias en los listados de los productos en cada país. Eso
lo sabe FEde, son pequeñas diferencias que no creo que afecten.

LO que sí creo que puede afectar son los links, Marce. Confirmame vos esto.
No están puestos con el dominio los links? Quiero decir: "
www.parexklaukol.com.ar/blabla..."

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 15:55 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
El problema es que las cosas que hacen INTERNAMENTE las aplicaciones, 
cuyo control no tenemos, leen de la base de datos que hay, que es la de 
Argentina.
No hay forma de que muestre productos que no esten cargados en esa base, 
no van a aparecer por milagro, porque la unica base de datos que nos 
llego fue la de parexklaukol.com.ar, ni la de Revear, ni las de Paraguay 
y Uruguay.

Los trucos que hice via un .htaccess para que los links la Casa 
Interactiva y el Simulador de Fachadas acceda a los productos de 
Argentina se puede hacer perfectamente con dominios de uruguay/paraguay, 
pero NO son los productos correctos.

**Comment by LeandroBraier** [comment]
Por qué NO son los productos correctos?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 16:36 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Porque tengo en el CMS una base de productos de cada pais (armadas en 
XML por Fede/Braulio) y son levemente distintas entre si.
Obviamente mucho coincide, pero solo en Paraguay esta el Guazukol, y hay 
productos en Argentina que no se venden en Paraguay ni Uruguay, como 
Parex Estilo 4D, Meztik, Stuko Norteño y el Stuko Patagonico.

**Comment by mkreyness** [comment]
Hice para probar unos enganches como para ver con dominio de paraguay las aplicaciones.
Por supuesto el encabezado y pie sigue siendo el de argentina con lo que los links no sirven, hay que hacer los correspondientes.

He aqui el resumen:

1) Casa Interactiva: 
http://www.parexparaguay.com.py/aplicaciones/casa-interactiva.html
bastante bien, los productos van a sus equivalentes paraguayos, pero hay que encontrar si o si a donde mandar los productos que no existen en paraguay (por ej, me genera este link: 
http://www.parexparaguay.com.py/parex/parex-estilo-4d.html
que NO existe, es un producto "argentino".

2) Calculador:
http://www.parexparaguay.com.py/aplicaciones/calculador.html

Aca es donde mas se complica porque los links tienen el dominio parexklaukol.com.ar explicito.

3) Simulador de Fachadas
http://www.parexparaguay.com.py/aplicaciones/simulador-de-fachadas.html

parece estar bien.

4) Cotiza tu Obra
http://www.parexparaguay.com.py/aplicaciones/cotiza-tu-obra.html

parece estar bien.

Si les parece avanzar en este sentido lo que tenemos que ver con Fede es como hacer que los headers/footers dependan del dominio, y el contenido interno vaya como esta via soft link enganchando con el real de parexklaukol.com.ar (el unico contenido que existe realmente).

**Comment by FAAREIA** [comment]
Lo de Cotiza tu obra, ya esta. El link esta donde originalmente estaba: en la categoría de productos parex.

**Comment by LeandroBraier** [comment]
Excelente. Gracias Fede! Queda cerrado entonces esto.

abrazo

**Comment by FAAREIA** [comment]
Lo de Paraguay y Uruguay queda para cuando se rehagan los motores?

**Comment by LeandroBraier** [comment]
No, subilo nomás. 

1) Las diferencias son mínimas. Solo aparece 1 producto que no está en esos países, que es Parex Estilo4D. Ahí dejemoslo yo le aviso al cliente.

2) Subamoslo pero cambiando el dominio de los links.

3 y 4) Subamoslos como están.

De última si el cliente pide cambios van cuando se rehagan esos motores.

abrazo

**Comment by FAAREIA** [comment]
Ok, te aviso si llego a subirlo hoy. Creo que igualmente va haber más de 1 producto que lleve a un 404 (pagina no encontrada).

**Comment by LeandroBraier** [comment]
Ok, cuando lo tengas lo probamos y lo hablo con el cliente.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-23 11:31 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Ojo Fede que todo lo que puse para Paraguay en realidad esta apuntando a lo mismo que Argentina, al hacer los nuevos headers/footers no pises las versiones argentinas al hacer las paraguayas/uruguayas. O sea, en este momento hay estos soft links:

public_html/parexklaukolpy/simulador -> public_html/bkps/parexklaukol.com.ar/simulador/
y
public_html/parexklaukolpy/aplicaciones -> public_html/_backup/parexklaukol/

y creo que ambas cosas son necesarias para que funcionen.

**Comment by LeandroBraier** [comment]
Buen dia Fede! Avisame cuando estén los de Uruguay y PAraguay así los testeo.

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Fede, no los veo online todavía.

![captura de pantalla 2015-06-24 a la s 09 49 35](https://cloud.githubusercontent.com/assets/6719872/8330045/e740c120-1a54-11e5-8f4b-033e5117a418.png)

**Comment by FAAREIA** [comment]
Ok, los pongo online. Pensé que los querías probar antes.

**Comment by FAAREIA** [comment]
Ahi ya estan online en UY y PY.
@mkreyness Hacete eso de los soft links en uruguay. Paraguay ya andan.

**Comment by LeandroBraier** [comment]
Excelente Fede! Gracias!

MK, avisame cuando esté lo de los soft links nomás.

**Comment by mkreyness** [comment]
Listo, fijense si todo anda como deberia.

**Comment by LeandroBraier** [comment]
Yo lo veo OK y ya le avisé al cliente, así que cualquier cosa nos avisan ellos.

abrazo
