### ISSUE TITLE
Micrositio Klaukol Impermeable Potenciado/ Links del Footer

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#51]
Buen día Braulio, necesito que habilites los links a la Comunidad de Vendedores y a la Guía de COrralones en el Micrositio, que aún están en gris deshabilitado. Cambialos por los logos actuales también.

http://www.parexklaukol.com.ar/klaukol-impermeable-potenciado/home.html

abrazo

pd: Confirmame recepción por favor

**Comment by braulio-evangelisti** [comment]
Listo Lea. Ya esta implementado online.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Braulio!
