### ISSUE TITLE
Vendedores #4: Mínimo cambio de texto en Bases y condiciones Vendedores Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#52]
Fede, esto lo necesito para hoy si puede ser. En la parte de las bases titulada "Premio Mensuales por sorteo" hay que cambiar a partir del párrafo que dice "En el mes de junio..." por el siguiente texto.

En el mes de junio entregaremos 1 (un) viaje a la ciudad de Mendoza para 2 (dos) personas saliendo desde la Ciudad Autónoma de Buenos Aires. 
El paquete incluye 
� Pasaje aéreo Bue Mendoza Bue volando por Aerolineas Argentinas en clase R. 
� Traslados Aeropuerto-Hotel-Aeropuerto. 
� 3 noches de alojamiento con desayuno en el hotel NH Cordillera en base doble. 
Si por alguna cuestion la persona que resulte ganadora no puede tomar el viaje a Mendoza podrá canjearlo por un viaje de igual valor de hasta $8.000 + IVA. en la agencia Neptuno Viajes - Tel. 5254-8951 - vanesa@neptuno.com.ar. 

Todo lo demás sigue igual.
abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo

**Comment by LeandroBraier** [comment]
Fede, habría que sacar una parte más del texto. La que figura acá:

![sacar esto tambien](https://cloud.githubusercontent.com/assets/6719872/8190370/7f292ac2-1438-11e5-965d-c88ec65cbb39.gif)

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
