### ISSUE TITLE
Mailings Comunidad de Vendedores Versión 2.0. DEADLINE: 18/6

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#53]
Fede, te mando por WeTransfer la estética nueva de los mailings en PSD. 

https://www.wetransfer.com/downloads/250d1b599c4a5552190d9f6975089b9020150617233848/7b2de6

Necesito que adaptes los 3 mailings que tenemos a esta estética:
1. Lanzamiento general
2. Bienvenida con Usuario y Clave
3. Preexistentes con Usuario y Clave
4. Una nueva versión para preexistentes que en lugar de usuario y clave diga: "Contactá a tu representante Klaukol para obtener tu nuevo usuario y clave." Y en lugar del botón "Hacé clic para logearte automáticamente" que diga "Hacé clic acá para conocer la Comunidad"

abrazo

**Comment by FAAREIA** [comment]
Lea, me falta la tipografía fingerbanger para editar el boton del psd. Cuando puedas pasamela

**Comment by LeandroBraier** [comment]
Descargala de acá Fede:

http://www.dafont.com/fingbanger.font

**Comment by FAAREIA** [comment]
Fijate si ahi esta bien Lea:
http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html
http://parexklaukol.com.ar/_mailing/vendedores-ir/vendedores-ir.html
http://parexklaukol.com.ar/_mailing/vendedores-existente/vendedores-existente.html
http://parexklaukol.com.ar/_mailing/vendedores-preexistente/vendedores-preexistente.html

**Comment by LeandroBraier** [comment]
Está excelente Fede!

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
