### ISSUE TITLE
Error en Compartir Facebook

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#54]
Va captura del error @mkreyness 

![captura de pantalla 2015-06-18 a la s 13 16 24](https://cloud.githubusercontent.com/assets/6719872/8235864/e97c6a78-15ba-11e5-985b-3e0fa0268aa6.png)

Lo antes posible tendríamos que resolverlo porque el cliente ya lo vio.

abrazo

**Comment by LeandroBraier** [comment]
https://www.facebook.com/v2.3/dialog/feed?app_id=376720105866121&description=&display=popup&e2e=%7B%7D&link=http%3A%2F%2Fparexklaukol.com.ar%2Fklaukol-impermeable-potenciado%2F&locale=es_LA&name=NUEVO%20KLAUKOL%20IMPERMEABLE%20POTENCIADO&next=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2F1ldYU13brY_.js%3Fversion%3D41%23cb%3Dfa68494d3edd0c%26domain%3Dwww.parexklaukol.com.ar%26origin%3Dhttp%253A%252F%252Fwww.parexklaukol.com.ar%252Ff55e13addd26b8%26relation%3Dopener%26frame%3Df3eef4969808ba4%26result%3D%2522xxRESULTTOKENxx%2522&picture=http%3A%2F%2Fwww.parexklaukol.com.ar%2Ftemplates%2Fparexklaukol%2Fvendedores%2Fimg%2Flogo.png&sdk=joey&version=v2.3

**Comment by mkreyness** [comment]
Sabes que a mi este mismo link me abre perfecto.
Agregalo a @FAAREIA (a mi no me deja) a ver que le trae a el.

**Comment by LeandroBraier** [comment]
La verdad no sé qué hacer, MK. Lo tenemos que resolver a esto.

La versión de Chrome que tengo es esta: Versión 43.0.2357.124 (64-bit)

Decime si sirve. No sé qué puede ser la verdad. Puede ser algo de privacidad?

A mi el compartir de Dánica me funciona OK. Por ahi es algo del Token.

![captura de pantalla 2015-06-18 a la s 15 15 08](https://cloud.githubusercontent.com/assets/6719872/8238343/69cd9f98-15cb-11e5-9bd6-20283f55b850.png)

Si es eso hagamos que TODO usuario que toque el botón de compartir sume los puntos y listo. No hace falta el token de Facebook si ese es el problema.

**Comment by mkreyness** [comment]
```
El de danica es el sharer tradicional que no tiene feedback.
Probaste ahora que puse el URL shortener ?

El 18/06/2015 a las 15:05,
  LeandroBraier escribió:


  La verdad no sé qué hacer, MK. Lo tenemos que resolver a esto.
  La versión de Chrome que tengo es esta: Versión 43.0.2357.124
    (64-bit)
  Decime si sirve. No sé qué puede ser la verdad. Puede ser algo
    de privacidad?
  A mi el compartir de Dánica me funciona OK. Por ahi es algo del
    Token.

  Si es eso hagamos que TODO usuario que toque el botón de
    compartir sume los puntos y listo. No hace falta el token de
    Facebook si ese es el problema.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
Fijate si este que es el ejemplo que yo arme antes de ponerlo en 
produccion te funciona:

http://www.parexklaukol.com.ar/vendedores/ejemplo-share.html

Yo ya probe en tres maquinas distintas, 6 browsers distintos, con 2 
cuentas distintas de facebook, y en todos el primer link que vos mismo 
me pasaste me anda PERFECTO.
Yo no digo que este bien y no haya que hacer nada, pero si no puedo 
reproducir el error no lo puedo arreglar !

**Comment by LeandroBraier** [comment]
Mirá Marce. Lo que yo veo es esto:

![captura de pantalla 2015-06-18 a la s 15 54 29](https://cloud.githubusercontent.com/assets/6719872/8239237/e6a92a46-15d0-11e5-8c23-d0737ef0ee63.png)

Es decir, no veo lo correcto me parece.

**Comment by FAAREIA** [comment]
Marce, a mi también me tira el error. Dudo que sea algo del navegador o el OS. Debe ser algun parámetro que le falta pasar a FB, o algo asi.

**Comment by FAAREIA** [comment]
O capas alguna configuración propia de cada uno de FB??? ?_?

**Comment by mkreyness** [comment]
Yo no logro que me de error jamas bajo ninguna circunstancia !
Ademas ya hay usuarios reales que compartieron los dos tipos de share.
Fijense si en sus configuraciones de seguridad de facebook tiene puesto 
que esta prohibido publicar en su nombre, en definitiva eso es lo que el 
share hace.

**Comment by mkreyness** [comment]
Tenes que hacer click en esa letra "f", es un BOTON.

**Comment by LeandroBraier** [comment]
Lo probé y me dio error, pero no solo eso. ME APARECIÓ EL MENSAJE DE "NO ME
QUIERAS ENGRUPIR!!!!"

Si eso está en la Comunidad nos matan. Sacalo urgente por favor MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
claro que no esta eso en el sitio real !

**Comment by mkreyness** [comment]
A ver fijate si te da error ahora, encontre por ahi que hay un parametro que podria estar faltando, no se por que a mi me anda sin eso, pero fijate si ahora te anda (en el sitio real, olvidate del de prueba)

**Comment by LeandroBraier** [comment]
Todavia no. Puede ser que tarde en impactar el cambio?

Querés pasarme la URL así la pruebo?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 16:53 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Es raro, a mi Facebook me dice que NO tengo que agregar ese parametro. Creo que por mas que se lo paso lo quita.

El url es este, y a mi me anda perfecto, pero seguro a vos no:

https://www.facebook.com/v2.3/dialog/feed?app_id=376720105866121&description=Jug%C3%A1%2C%20sum%C3%A1%20y%20gan%C3%A1!&display=popup&e2e=%7B%7D&link=http%3A%2F%2Fwww.parexklaukol.com.ar%2Fvendedores%2F&locale=es_LA&name=Comunidad%20de%20Vendedores%20Potenciados&next=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2F1ldYU13brY_.js%3Fversion%3D41%23cb%3Df28af934d4%26domain%3Dwww.parexklaukol.com.ar%26origin%3Dhttp%253A%252F%252Fwww.parexklaukol.com.ar%252Ff5dfabe1c%26relation%3Dopener%26frame%3Dff80d7f1c%26result%3D%2522xxRESULTTOKENxx%2522&picture=http%3A%2F%2Fgoo.gl%2FnsZh05&sdk=joey&version=v2.3

**Comment by LeandroBraier** [comment]
Exacto. Me da el mismo error de antes.

PERO

en la nueva versión que subiste, ahora me da un error distinto:

![captura de pantalla 2015-06-18 a la s 17 20 27](https://cloud.githubusercontent.com/assets/6719872/8241014/0ab5930a-15dd-11e5-8985-65dfe951516f.png)

**Comment by mkreyness** [comment]
AHAHHHHAHHAHHAHAHAHAHHHHHHHHH Yo soy el developer ! Tengo que publicarla entonces, ajhor aveo.

**Comment by mkreyness** [comment]
el app no estaba publicado porque faltaba mi email como developer. Ya lo complete.
Igual PODRIA ser que la tenga que someter a aprobacion de Facebook, confirmame si te anda o no asi se si tengo que hacer ese submission.

**Comment by LeandroBraier** [comment]
AAAAAAHORA SIIII

Vamos todavía!

Ya me funciona!

Ahora hay que corregir otras cosas, porque a mi no me comparte como a los otros usuarios. Mirá:

![captura de pantalla 2015-06-18 a la s 15 49 33](https://cloud.githubusercontent.com/assets/6719872/8241318/0849d20a-15df-11e5-84cd-cb0eab5e58bf.png)

![captura de pantalla 2015-06-18 a la s 17 33 25](https://cloud.githubusercontent.com/assets/6719872/8241310/f4827132-15de-11e5-8643-21bfa95453ad.png)
![captura de pantalla 2015-06-18 a la s 17 34 47](https://cloud.githubusercontent.com/assets/6719872/8241311/f625a7e8-15de-11e5-9e93-73bb62af4a47.png)

**Comment by mkreyness** [comment]
No tengo mucho para cambiar, ya que el dialogo lo pone Facebook.
Los parametros que puedo pasarle son solamente el URL de la foto y el URL del link. Lo que pasa es que es un dialogo de FEED, no realmente de SHARE. El share lo que hace es tomar datos de la pagina para lo cual la pagina tiene que ser estatica (no nos sirve para el juego) y ademas no tiene realmente feedback, por eso volvi a la version esta de feed.

**Comment by LeandroBraier** [comment]
Claro, pero por qué al otro usuario le comparte el video perfecto y a mi me
aparece así?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 17:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero el otro fue posteado desde youtube.com, no tiene nada que ver con nuestro sitio, usaran otra interface.

**Comment by mkreyness** [comment]
El link que tiene puesto el boton Compartir del JUEGO (no el general) es el del micrositio. Si queres lo cambio a que ponga el link a Youtube

**Comment by LeandroBraier** [comment]
No, el link está bien. Pero la imagen no tiene nada que ver con el
Micrositio. Por lo menos que aparezca el producto, Nuevo Klaukol
Impermeable Potenciado.

Y respecto de la imagen de preview de la Comunidad, no se puede achicar un
poco para que se vea mejor en Facebook?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 17:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
La imagen esta fija, es la que puso Fede en el template, pero la puedo 
cambiar por el poster del video, ok ?

**Comment by LeandroBraier** [comment]
Dale, perfecto. 

@FAAREIA mañana fijate si podés achicar la imagen del logo de la Comunidad para que entre bien en el posteo de Facebook. El tamaño sería 485 x 255.

abrazo

**Comment by mkreyness** [comment]
Listo, fijate si te sale bien el poster

**Comment by LeandroBraier** [comment]
Perfecto.

Y además me deja seguir compartiendo aunque no pueda sumar más puntos. Eso
es genial. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si obvio, no se deshabilita nunca, pero solo suma puntos una vez.

**Comment by LeandroBraier** [comment]
Excelente resolución.

Gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Lea, lamentablemente se puede poner solo 1 imagen para que facebook la tome. Veo que hay dos tipos de posts, uno con foto horizontal y otro con foto cuadrada. La cuadrada queda bien pero la horizontal no y no hay forma de decirle que en modo horizontal tome otra foto =/
Avisame si queres que pase la versión cuadrada normal a una horizontal, pero es una u otra.

**Comment by LeandroBraier** [comment]
No termino de entender bien lo que decís Fede. Te referís a la imagen de
preview del link de Comunidad de Vendedores?

Si es eso entonces achiquemos la imagen lo suficiente para que quede "más o
menos" bien en ambos formatos. Se entiende lo que digo?

Fijate la que puso MK para el link de Klaukol Impermeable Potenciado que me
parece que funciona bien.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 8:52 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
```
Es porque es el poster de youtube que tenemos asociado en el CMS
como imagen del "tema" KIP, obviamente al ser tomado de un video
tiene formato ancho.

El 19/06/2015 a las 9:07, LeandroBraier
  escribió:

No termino de entender bien lo que decís Fede. Te
  referís a la imagen de
  preview del link de Comunidad de Vendedores?

  Si es eso entonces achiquemos la imagen lo suficiente para que
  quede "más o
  menos" bien en ambos formatos. Se entiende lo que digo?

  Fijate la que puso MK para el link de Klaukol Impermeable
  Potenciado que me
  parece que funciona bien.

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-19 8:52 GMT-03:00 Federico Arena
  <notifications@github.com>:

  > Lea, lamentablemente se puede poner solo 1 imagen para que
  facebook la
  > tome. Veo que hay dos tipos de posts, uno con foto horizontal
  y otro con
  > foto cuadrada. La cuadrada queda bien pero la horizontal no y
  no hay forma
  > de decirle que en modo horizontal tome otra foto =/
  > Avisame si queres que pase la versión cuadrada normal a una
  horizontal,
  > pero es una u otra.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/54#issuecomment-113487963
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
CLaro, pero en formato vertical queda bastante bien. Vamos por ahí.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 9:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi ya modifiqué la imagen en el compartir general del sitio, ese que aparece en la columna derecha abajo de todo.

**Comment by LeandroBraier** [comment]
El formato quedó perfecto. Voy a empezar a pensar imágenes especialmente
para esos links, así se las paso directamente cuando les paso el contenido.

La de Comunidad de Vendedores creo que la vamos a mejorar un poquito pero
así está bien. Gracias Fede!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 10:46 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Pero es facebook el que tira error, seria que no estabas loggeado ? Capaz este plugin no fuerza login

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Marce, me parece que te llegó un mensaje viejo. Este ticket ya está
cerrado, todo en orden.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 15:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
No, a VOS te llego esto que es viejo :)
Habia quedado en el outbox de mi celular, y recien ahora salio.

**Comment by LeandroBraier** [comment]
Ah, genial. Todo en orden entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 16:14 GMT-03:00 mkreyness notifications@github.com:
