### ISSUE TITLE
Posible Juego a proponer a Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#55]
@FAAREIA y @mkreyness les consulto:

Si proponemos un juego así, lo ven muy dificil?

http://www.miniclip.com/games/bad-apple/en/#t-c-f-C

Ya consulté con nuestro diseñador flash y me dijo que tiene experiencia y juegos y sabe como resolverlos.

Me confirman si lo puedo proponer?

**Comment by mkreyness** [comment]
Es el viejo y querido minesweeper.
Lo que tenes que preguntarle al diseñador si puede devolverme un 
resultado de si el jugador completo bien el juego o fallo.
Tambien me parece que puede haber puntos parciales, porque suele ser 
imposible terminar 100% el juego sin que te explote.

**Comment by LeandroBraier** [comment]
Claro, te averiguo eso.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 17:48 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Me dice el diseñador que sí. Que va a chequear con un programador pero cree que sí se puede. En paralelo, no podemos averiguar si se puede hacer con JavaScript? Al menos comprando o bajando un motor de por ahi?

**Comment by mkreyness** [comment]
```
La logica del juego si, no hay drama, pero las animaciones/parte
grafica obviamente no las hago yo asi que no puedo opinar sobre su
dificultad.

El 19/06/2015 a las 8:32, LeandroBraier
  escribió:


  Me dice el diseñador que sí. Que va a chequear con un
    programador pero cree que sí se puede. En paralelo, no podemos
    averiguar si se puede hacer con JavaScript? Al menos comprando o
    bajando un motor de por ahi?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ok, le consulto a @FAAREIA qué opina al respecto entonces.

**Comment by FAAREIA** [comment]
Si se hace por javascript la animación podría hacerse con un gif y ejecutarlo/poner-play al hacerle click. Claro esta que para hacer eso se necesita alguien que dibuje la forma, la pinte y haga los fotogramas correspondientes.

**Comment by LeandroBraier** [comment]
Eso lo puede hacer el diseñador Flash, que claramente además de flash es diseñador. Entonces confirmado que se puede. Les aviso qué respuesta tengo del cliente.

Gracias!

**Comment by mkreyness** [comment]
Si pero no puedo meter un Flash en cada celda, o sea, si la logica la 
manejo yo, chau Flash, tiene que ser un gif que no repita, o algo asi.

**Comment by LeandroBraier** [comment]
Puede ser un GIF que no loopee. Eso está en las propiedades del GIF.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 14:26 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Si el asunto ademas es poder controlar CUANDO hace el movimiento.
Supongo que hay que tener en realidad dos versiones de cada cosa,
una estatica y otra de la animacion, y reemplazar la estatica por la
animada en el momento en que la tocan o le corresponda.

El 19/06/2015 a las 14:35,
  LeandroBraier escribió:

Puede ser un GIF que no loopee. Eso está en las
  propiedades del GIF.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-19 14:26 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Si pero no puedo meter un Flash en cada celda, o sea, si la
  logica la
  > manejo yo, chau Flash, tiene que ser un gif que no repita, o
  algo asi.
  >
  > On 19/06/2015 11:44 a.m., LeandroBraier wrote:
  > >
  > > Eso lo puede hacer el diseñador Flash, que claramente
  además de flash
  > > es diseñador. Entonces confirmado que se puede. Les
  aviso qué
  > > respuesta tengo del cliente.
  > >
  > > Gracias!
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > > <
  >
```

https://github.com/LeandroBraier/Klaukol/issues/55#issuecomment-113535417
      > >.
      >
      > >
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/55#issuecomment-113581539
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
MK, me podrías calcular las horas que te llevaría haciéndolo en JS si te paso todos los elementos gráficos?

**Comment by LeandroBraier** [comment]
Las horas que te llevaría digamos, para presupuestar.

**Comment by mkreyness** [comment]
Estamos hablando SOLO del juego del buscaminas ?

**Comment by LeandroBraier** [comment]
Sip.

**Comment by mkreyness** [comment]
Ponele 15 horas con toda la furia.

**Comment by LeandroBraier** [comment]
Genial. Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
