### ISSUE TITLE
Preview Sitio Klaukol Impermeable Potenciado

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#56]
Fede, por lo que venimos publicando hasta ahora, la única URL que no genera preview es la de  Klaukol Impermeable Potenciado.

Se puede ver en la publicación https://www.facebook.com/parexklaukolarg/posts/735532416569105 que la imagen de preview está en blanco, pero cuando publicamos/programamos no aparece una imagen (y por lo tanto la posibilidad de subir otra, como ya hicimos con algunos links).

Necesitaría que subas una imagen del pack o el preview del video como estás haciendo en la Comunidad de Vendedores.

abrazo

**Comment by FAAREIA** [comment]
Hecho, fijate ahora.

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo
