### ISSUE TITLE
Vendedores #5 Mensaje de Fin de Trivia. DEADLINE: 22/6

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#57]
MK, necesito un cambio dentro de la trivia.

Cuando el usuario responde ambas preguntas mal la plataforma lo invita a ver de nuevo los contenidos y seguir jugando. Eso está OK. 

Pero si el usuario se equivoca en 1 sola pregunta, al final debería ver la trivia entera y cuál era la respuesta correcta en cada caso.

Me refiero a esta pantalla:

http://www.parexklaukol.com.ar/cgi-bin/fintrivia.pl

Esto puede ser para la semana que viene.

abrazo

**Comment by mkreyness** [comment]
Pero no tenemos algo armado para mostrar "la trivia entera", ni algo 
pensado para mostrar "la respuesta correcta". Le pasaste a Fede para 
maquetarlo ?
Y una vez que se le muestra eso, como "se va" de ahi ?

**Comment by LeandroBraier** [comment]
@FAAREIA como andás?=

Necesitaría que hagas esta pequeña modificación en fintrivia.pl para poder mostrar las respuestas correctas a cada pregunta.

abrazo

**Comment by mkreyness** [comment]
no es en fintrivia.pl (ese es mi programa) sino en el template trivia-completaT.html, ojo que todo esta en produccion, no cambies directamente, hacelo en trivia-completaT2.html y contame los cambios asi yo despues hago los ajustes en [ahora si] fintrivia.pl que es lo mio.

**Comment by FAAREIA** [comment]
Pongo lo que puse en otro issue:

Listo lo de respuestas correctas:
http://parexklaukol.com.ar/vendedores/trivia-completa.html

Marce, fijate que al `<dl>` le agregué al final:

```
<dt>Respuesta #1:</dt
><dd class="respuesta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</dd
><dt>Respuesta #2:</dt
><dd class="respuesta">Dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</dd>
```

Guarda que el tag cierra en línea nueva ^_^

**Comment by mkreyness** [comment]
Pongo aca lo que dijo Lean:

Está bueno. Se tendría que sumar Pregunta #1 y Pregunta #2 antes de cada
Respuesta pero estéticamente está perfecto.

Digo yo:
Entiendo que cuando Fede puso "Respuesta #1" se refiere a la respuesta 
correcta de la pregunta #1, ya que no ponemos las respuestas incorrectas.
Entonces el formato seria algo tipo

Pregunta 1: respuesta correcta a la pregunta 1
Pregunta 2: respuesta correcta a la pregunta 2

**Comment by LeandroBraier** [comment]
Me parece perfecto lo que dice MK.

**Comment by mkreyness** [comment]
Estoy terminandolo, en seguida te mando link de prueba.

**Comment by mkreyness** [comment]
El problema es que la pregunta es larga y wrappea mucho, y se pierde visualmente la respuesta.
Proba con este link

http://www.parexklaukol.com.ar/cgi-bin/triviamk.pl?id=15&usuario=marcelokreyness&clave=pepe

y dale a la respuesta correcta (la 3).

**Comment by FAAREIA** [comment]
Claro, estaba preparado para textos cortos. Ahora lo adapto.

**Comment by mkreyness** [comment]
```
Fede, usa directamente el template de desarrollo:
www/templates/vendedores/trivia-completaT2.html 
No esta en produccion todavia

El 24/06/2015 a las 8:47, Federico
  Arena escribió:

Claro, estaba preparado para textos cortos. Ahora lo
  adapto.

  El 23 de junio de 2015, 8:01 p. m.,
  mkreyness<notifications@github.com>
  escribió:

  > El problema es que la pregunta es larga y wrappea mucho, y se
  pierde
  > visualmente la respuesta.
  > Proba con este link
  >
  >
  >
```

http://www.parexklaukol.com.ar/cgi-bin/triviamk.pl?id=15&usuario=marcelokreyness&clave=pepe
      >
      > y dale a la respuesta correcta (la 3).
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/57#issuecomment-114667544
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by FAAREIA** [comment]
Cambié algo en el CSS nomás. Ahora no hace falta que el DD tenga la clase "respuesta".

**Comment by mkreyness** [comment]
```
Ahi le saque la clase "respuesta" pero no veo mayor diferencia.
El CSS es el que es accesible desde

http://www.parexklaukol.com.ar/templates/parexklaukol/vendedores/

Vuelvo a pasar el link para que mires como sale:
```

http://www.parexklaukol.com.ar/cgi-bin/triviamk.pl?id=15&usuario=marcelokreyness&clave=pepe

```
y selecciona la respuesta 3 y dale finalizar.


El 24/06/2015 a las 9:03, Federico
  Arena escribió:


  Cambié algo en el CSS nomás. Ahora no hace falta que el DD
    tenga la clase "respuesta".
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Dale F5.

**Comment by mkreyness** [comment]
```
Ah, ahora si, genial.
Leandro: esperamos entonces a tener las imagenes definitivas para
las trivias nuevas y subimos a produccion todo junto ?

El 24/06/2015 a las 9:28, Federico
  Arena escribió:

Dale F5.

  El 24 de junio de 2015, 9:13 a. m.,
  mkreyness<notifications@github.com>
  escribió:

  >
  >
  >
  >
  >
  > Ahi le saque la clase "respuesta" pero no veo mayor
  diferencia.
  > El CSS es el que es accesible desde
  >
  >
  http://www.parexklaukol.com.ar/templates/parexklaukol/vendedores/
  >
  > Vuelvo a pasar el link para que mires como sale:
  >
  >
  >
```

http://www.parexklaukol.com.ar/cgi-bin/triviamk.pl?id=15&usuario=marcelokreyness&clave=pepe
      >
      > y selecciona la respuesta 3 y dale finalizar.
      >
      >
      > El 24/06/2015 a las 9:03, Federico
      > Arena escribió:
      >
      >
      > Cambié algo en el CSS nomás. Ahora no hace falta que el DD
      > tenga la clase "respuesta".
      >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/57#issuecomment-114846343
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.
