### ISSUE TITLE
Vendedores #6: Dos nuevas trivias para Klaukol Impermeable Potenciado

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#58]
Fede, necesitamos subir dos nuevas trivias. 

Trivia de Seguridad
¿Por qué Klaukol Impermeable Potenciado es la mejor opción para trabajar en pisos y revestimiento de media y alta absorción sobre soportes tradicionales?
1. Porque su fórmula permite trabajar en superficies no porosas.
2. Este producto posee aditivos hidrófugos que otorgan más seguridad porque reducen al mínimo el pasaje de agua. (Correcta)
3. Porque resiste las altas temperaturas.

Trivia de Trabajabilidad
¿Qué significa que Klaukol Impermeable Potenciado tiene mayor tiempo abierto?
Respuestas:
- que la mezcla seca más rápido
- que la mezcla es más fluida
- que la mezcla se mantiene húmeda durante el tiempo de trabajo (correcta)

Lo podremos tener subido para mañana?

abrazo

**Comment by mkreyness** [comment]
```
Las trivias son parte del CMS, no las maneja Fede, te lo tengo que
cargar yo, y en un futuro lo podras manejar directo, o mejor aun, el
propio cliente. No me animaria en este caso en particular dejarselo
a ellos.

El problema radica en que como esta armado, cada "tema" tiene una
sola trivia, que se accede de 3 maneras diferentes
(video/adjuntos/propia trivia).

Si en este caso el tema es KIP, no hay forma de agregarlas EN la
actual pagina del tema KIP.
Lo que habiamos hablado es crear un tema "KIP 2" (o KIP Seguridad,
dale un nombre adecuado) y ahi si en ese tema, completando todos los
dato (probablemente la mayoria sean los mismos que en el tema KIP
preexistente), asociarle la nueva trivia.

Si me confirmas esto, te lo armo en un rato.


El 22/06/2015 a las 12:09,
  LeandroBraier escribió:


  Fede, necesitamos subir dos nuevas trivias. 
  Trivia de Seguridad
    ¿Por qué Klaukol Impermeable Potenciado es la mejor opción
    para trabajar en pisos y revestimiento de media y alta
    absorción sobre soportes tradicionales?
    1. Porque su fórmula permite trabajar en superficies no
    porosas.
    2. Este producto posee aditivos hidrófugos que otorgan más
    seguridad porque reducen al mínimo el pasaje de agua.
    (Correcta)
    3. Porque resiste las altas temperaturas.
  Trivia de Trabajabilidad
    ¿Que significa que Klaukol Impermeable Potenciado tiene mayor
    tiempo abierto?
    Respuestas:

    que la mezcla seca más rápido
    que la mezcla es más fluida
    que la mezcla se mantiene húmeda durante el tiempo de
      trabajo (correcta)

  Lo podremos tener subido para mañana?
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Es que no lo veo. Es todo el mismo contenido pero con la trivia diferente.
Estéticamente se va a ver exactamente igual. Y no tenemos otro video del
mismo producto como para que algo cambie. No hay forma de sumarlo al mismo
contenido? Lleva mucho más tiempo eso?

Sino otra alternativa sería crea el objetivo trivia por fuera del contenido
y que, si alguien necesita más información, tenga el link de esa página a
mano dentro de la trivia. Cual de las dos ves posible?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 12:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Es un kilombo, si.
Tendria que rearmar todo de cero para que haya n trivias diferentes
por cada tema.
Ahora hay 3 "actividades" diferentes (una de cada tipo) pero todos
comparten la misma trivia, es la forma de no permitirle responder
las mismas preguntas de vuelta si ya contestó.
En la base de datos podemos cargar eso que decis, pero no hay como
renderearlo en lo maquetado. 
La maqueta es generica, con un formato fijo: una imagen, un video,
una lista de adjuntos descargables, y 3 actividades, que
corresponden a la misma trivia.
No tenemos maquetas variables que se adapten a cualquier combinacion
de cosas.

Las dos cosas son inviables de hoy para mañana, mas cuando tenemos
que meterle pata a lo de Torneos.

Lo mas sencillo seria tratar de forzar un 2do tema ("KIP y la
Seguridad") con un contenido mas simple (por ej, no poner video ni
documentos) y con solo la trivia.
Eso (reducir) creo que el template se lo banca, o al menos lo puedo
ajustar facil.


El 22/06/2015 a las 12:33,
  LeandroBraier escribió:

Es que no lo veo. Es todo el mismo contenido pero con
  la trivia diferente.
  Estéticamente se va a ver exactamente igual. Y no tenemos otro
  video del
  mismo producto como para que algo cambie. No hay forma de sumarlo
  al mismo
  contenido? Lleva mucho más tiempo eso?

  Sino otra alternativa sería crea el objetivo trivia por fuera del
  contenido
  y que, si alguien necesita más información, tenga el link de esa
  página a
  mano dentro de la trivia. Cual de las dos ves posible?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-22 12:16 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Las trivias son parte del CMS, no las maneja Fede, te lo
  tengo que
  > cargar yo, y en un futuro lo podras manejar directo, o mejor
  aun, el
  > propio cliente. No me animaria en este caso en particular
  dejarselo
  > a ellos.
  >
  > El problema radica en que como esta armado, cada "tema" tiene
  una
  > sola trivia, que se accede de 3 maneras diferentes
  > (video/adjuntos/propia trivia).
  >
  > Si en este caso el tema es KIP, no hay forma de agregarlas EN
  la
  > actual pagina del tema KIP.
  > Lo que habiamos hablado es crear un tema "KIP 2" (o KIP
  Seguridad,
  > dale un nombre adecuado) y ahi si en ese tema, completando
  todos los
  > dato (probablemente la mayoria sean los mismos que en el tema
  KIP
  > preexistente), asociarle la nueva trivia.
  >
  > Si me confirmas esto, te lo armo en un rato.
  >
  >
  > El 22/06/2015 a las 12:09,
  > LeandroBraier escribió:
  >
  >
  > Fede, necesitamos subir dos nuevas trivias.
  > Trivia de Seguridad
  > ¿Por qué Klaukol Impermeable Potenciado es la mejor opción
  > para trabajar en pisos y revestimiento de media y alta
  > absorción sobre soportes tradicionales?
  > 1. Porque su fórmula permite trabajar en superficies no
  > porosas.
  > 2. Este producto posee aditivos hidrófugos que otorgan más
  > seguridad porque reducen al mínimo el pasaje de agua.
  > (Correcta)
  > 3. Porque resiste las altas temperaturas.
  > Trivia de Trabajabilidad
  > ¿Que significa que Klaukol Impermeable Potenciado tiene mayor
  > tiempo abierto?
  > Respuestas:
  >
  > que la mezcla seca más rápido
  > que la mezcla es más fluida
  > que la mezcla se mantiene húmeda durante el tiempo de
  > trabajo (correcta)
  >
  > Lo podremos tener subido para mañana?
  > abrazo
  > —
  > Reply to this email directly or view
  > it on GitHub.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/58#issuecomment-114149193
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Ok, vamos con esa opción. En lugar del video poné la imagen del producto
que tenemos en su página correspondiente y que el título sea: Impermeable
Potenciado: Trivia de Seguridad.

Que el Compartir de Facebook comparta esa página de Trivia, no el VIdeo de
KIP digamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 12:47 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Ok, durante la tarde lo dejo resuelto.

El 22/06/2015 a las 12:50,
  LeandroBraier escribió:

Ok, vamos con esa opción. En lugar del video poné la
  imagen del producto
  que tenemos en su página correspondiente y que el título sea:
  Impermeable
  Potenciado: Trivia de Seguridad.

  Que el Compartir de Facebook comparta esa página de Trivia, no el
  VIdeo de
  KIP digamos.

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-22 12:47 GMT-03:00 mkreyness
  <notifications@github.com>:

  >
  >
  >
  >
  >
  > Es un kilombo, si.
  > Tendria que rearmar todo de cero para que haya n trivias
  diferentes
  > por cada tema.
  > Ahora hay 3 "actividades" diferentes (una de cada tipo) pero
  todos
  > comparten la misma trivia, es la forma de no permitirle
  responder
  > las mismas preguntas de vuelta si ya contestó.
  > En la base de datos podemos cargar eso que decis, pero no hay
  como
  > renderearlo en lo maquetado.
  > La maqueta es generica, con un formato fijo: una imagen, un
  video,
  > una lista de adjuntos descargables, y 3 actividades, que
  > corresponden a la misma trivia.
  > No tenemos maquetas variables que se adapten a cualquier
  combinacion
  > de cosas.
  >
  > Las dos cosas son inviables de hoy para mañana, mas cuando
  tenemos
  > que meterle pata a lo de Torneos.
  >
  > Lo mas sencillo seria tratar de forzar un 2do tema ("KIP y la
  > Seguridad") con un contenido mas simple (por ej, no poner
  video ni
  > documentos) y con solo la trivia.
  > Eso (reducir) creo que el template se lo banca, o al menos lo
  puedo
  > ajustar facil.
  >
  >
  > El 22/06/2015 a las 12:33,
  > LeandroBraier escribió:
  >
  > Es que no lo veo. Es todo el mismo contenido pero con
  > la trivia diferente.
  > Estéticamente se va a ver exactamente igual. Y no tenemos
  otro
  > video del
  > mismo producto como para que algo cambie. No hay forma de
  sumarlo
  > al mismo
  > contenido? Lleva mucho más tiempo eso?
  >
  > Sino otra alternativa sería crea el objetivo trivia por fuera
  del
  > contenido
  > y que, si alguien necesita más información, tenga el link de
  esa
  > página a
  > mano dentro de la trivia. Cual de las dos ves posible?
  >
  > Leandro Braier
  > Producción Audiovisual & Social Media
  > Benteveo Producciones <http://benteveo.tv>
  >
  > Móvil 1158717399
  >
  > 2015-06-22 12:16 GMT-03:00 mkreyness
  > <notifications@github.com>:
  >
  > >
  > >
  > >
  > >
  > >
  > > Las trivias son parte del CMS, no las maneja Fede, te lo
  > tengo que
  > > cargar yo, y en un futuro lo podras manejar directo, o
  mejor
  > aun, el
  > > propio cliente. No me animaria en este caso en
  particular
  > dejarselo
  > > a ellos.
  > >
  > > El problema radica en que como esta armado, cada "tema"
  tiene
  > una
  > > sola trivia, que se accede de 3 maneras diferentes
  > > (video/adjuntos/propia trivia).
  > >
  > > Si en este caso el tema es KIP, no hay forma de
  agregarlas EN
  > la
  > > actual pagina del tema KIP.
  > > Lo que habiamos hablado es crear un tema "KIP 2" (o KIP
  > Seguridad,
  > > dale un nombre adecuado) y ahi si en ese tema,
  completando
  > todos los
  > > dato (probablemente la mayoria sean los mismos que en el
  tema
  > KIP
  > > preexistente), asociarle la nueva trivia.
  > >
  > > Si me confirmas esto, te lo armo en un rato.
  > >
  > >
  > > El 22/06/2015 a las 12:09,
  > > LeandroBraier escribió:
  > >
  > >
  > > Fede, necesitamos subir dos nuevas trivias.
  > > Trivia de Seguridad
  > > ¿Por qué Klaukol Impermeable Potenciado es la mejor
  opción
  > > para trabajar en pisos y revestimiento de media y alta
  > > absorción sobre soportes tradicionales?
  > > 1. Porque su fórmula permite trabajar en superficies no
  > > porosas.
  > > 2. Este producto posee aditivos hidrófugos que otorgan
  más
  > > seguridad porque reducen al mínimo el pasaje de agua.
  > > (Correcta)
  > > 3. Porque resiste las altas temperaturas.
  > > Trivia de Trabajabilidad
  > > ¿Que significa que Klaukol Impermeable Potenciado tiene
  mayor
  > > tiempo abierto?
  > > Respuestas:
  > >
  > > que la mezcla seca más rápido
  > > que la mezcla es más fluida
  > > que la mezcla se mantiene húmeda durante el tiempo de
  > > trabajo (correcta)
  > >
  > > Lo podremos tener subido para mañana?
  > > abrazo
  > > —
  > > Reply to this email directly or view
  > > it on GitHub.
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > >
  >
```

<https://github.com/LeandroBraier/Klaukol/issues/58#issuecomment-114149193
      > >
      >
      > > .
      > >
      > —
      > Reply to this email directly or view
      > it on GitHub.
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/Klaukol/issues/58#issuecomment-114159371
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
Lean, dudas:
aca en realidad son DOS trivias separadas o una sola con dos preguntas ?
Si son dos tengo que agregar DOS temas, uno "Seguridad" y otro "Trabajabilidad"
Cuales serian los puntajes por responder c/u ?

Comentarios:
Me parece que esta BIEN como lo estamos haciendo, porque si todo esto fuera un UNICO tema KIP, seria inentendible que trivias hizo y que trivias no (todos los iconos se verian iguales, los textos son fijos), enterarse de que aparecio una nueva, etc.
En todo caso a futuro tenemos que dar un poco mas de flexibilidad al formato, o que si el juego es solo una trivia sin tener que mostrar nada, entre directo de la lista de juegos (la que por ahora es invisible).

**Comment by LeandroBraier** [comment]
Entiendo lo que decís MK y comparto.

Hagamos dos trivias separadas, con la misma foto de producto. Yo después te
paso una estética propia para la imagen de cada trivia. En la parte de
VIDEO de cada "tema" que lleve al mismo de antes, por si necesita
informarse más.

Como vamos con el tema de que las respuestas correctas aparezcan al final?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 13:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Para eso de que las respuestas correctas habia que maquetar algo
nuevo, con el formato que quieran que aparezcan.

El 22/06/2015 a las 14:11,
  LeandroBraier escribió:

Entiendo lo que decís MK y comparto.

  Hagamos dos trivias separadas, con la misma foto de producto. Yo
  después te
  paso una estética propia para la imagen de cada trivia. En la
  parte de
  VIDEO de cada "tema" que lleve al mismo de antes, por si necesita
  informarse más.

  Como vamos con el tema de que las respuestas correctas aparezcan
  al final?

  abrazo

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-22 13:59 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Lean, dudas:
  > aca en realidad son DOS trivias separadas o una sola con dos
  preguntas ?
  > Si son dos tengo que agregar DOS temas, uno "Seguridad" y
  otro
  > "Trabajabilidad"
  > Cuales serian los puntajes por responder c/u ?
  >
  > Comentarios:
  > Me parece que esta BIEN como lo estamos haciendo, porque si
  todo esto
  > fuera un UNICO tema KIP, seria inentendible que trivias hizo
  y que trivias
  > no (todos los iconos se verian iguales, los textos son
  fijos), enterarse de
  > que aparecio una nueva, etc.
  > En todo caso a futuro tenemos que dar un poco mas de
  flexibilidad al
  > formato, o que si el juego es solo una trivia sin tener que
  mostrar nada,
  > entre directo de la lista de juegos (la que por ahora es
  invisible).
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/58#issuecomment-114178817
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mkreyness** [comment]
Falto que me definas los puntos para cada trivia.

**Comment by LeandroBraier** [comment]
Valen lo mismo que la trivia anterior. Exactamente igual. Serían 60 puntos en total.

Ok con lo de maquetación. Le pido a Fede. abrazo

**Comment by mkreyness** [comment]
Pero la trivia anterior tenia 2 preguntas, entonces tenias la posibilidad de ganar 30 o 60.
Te referis a 60 en total ? Porque aca como son dos trivias separadas, no existe eso de "contestarla a medias", son 30 en una y 30 en la otra, o 60 en una y 60 en la otra.

**Comment by mkreyness** [comment]
Y otro tema: el template de juego actual NO tiene previsto que pueda faltar alguna de las secciones, esta todo con una estructura fija, me parece que habria que pasarle urgente a Fede que haga una version nueva que tenga partes variables (o sea, que cualquiera de las 3 posibildades pueda ser sacada. Para no atrasarnos voy a intentar hacerlo por mi cuenta y en todo caso si queda medio cachuzo se lo paso para que lo emprolije.

**Comment by LeandroBraier** [comment]
Gracias MK. Respecto de la Trivia de 1 pregunta, sí. Que toda la Trivia de
Seguridad valga 60 puntos y toda la Trivia de Trabajabilidad valga 60
puntos, aunque cada una tenga una pregunta.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 17:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ya casi esta. Una ultima cosita: esta bien ponerle "Trabajabilidad" de nombre ? Estas induciendo la respuesta correcta (la unica que habla de "trabajo").
Podes ver las 3 aca (es un acceso que todavia la gente no ve porque solo hay 1 oficialmente publicada)

http://www.parexklaukol.com.ar/cgi-bin/juegosvendedoresmk.pl?usuario=marcelokreyness&clave=pepe

Lo que no termino de figurarme tampoco es como hacer para "compartir la trivia", ya que no es una pagina accesible sin estar loggeado, y si lo mando con las credenciales para que aparezca loggeado, estoy revelando en Facebook su acceso.
Para mi todo lo que se comparta tendria que ser siempre algo publico.

**Comment by LeandroBraier** [comment]
Buenisimo. No te preocupes por eso. Le falta una Q a la tercera opción. El
resto OK.

Mañana te paso las imagenes que van en lugar del video y del thumbnail de
esa lista de contenidos.

Tenés razón con respecto a compartir. Tendría que compartir sus resultados.
Algo así como "Contesté correctamente la Trivia de Trabajabilidad de
Klaukol Impermeable Potenciado.". Se puede hacer eso?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 17:46 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Agregada la Q (en realidad estaban las 3 en minuscula, asi que puse 'q').
Si va a haber un video diferente, podriamos compartir el thumb de ese 
video diferente.

El texto ese se lo puedo forzar, creo.
En realidad con tiempo lo ideal para compartir un 'triunfo' es que 
generemos un diplomita, publico, a nombre del tipo, y que sea eso lo que 
comparta.
De paso el diplomita podria estar "esponsoreado" por las marcas, 
clickeables, etc. etc.

**Comment by LeandroBraier** [comment]
Está buena la idea, Marce, pero no quiere que parezca certificación de
Klaukol. SImplemente quieren que sea como un juego, así que debería ser
similar a "Gané tantos puntos en Candy Crush"

No va a haber un video diferente, va a haber una imagen fija. Es mucho lio
eso?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 18:09 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Por eso, no algo con aspecto oficial sino un tarjeton que diga "Gané 60 puntos contestando la Trivia de Trabajabilidad", hasta le podemos poner su propia cara (a todo esto sigue pendiente poder moderar las fotos feas).
Ojo que deberian ser 2 imagenes: una chica para el thumb en la lista de temas, y otra para la pagina del juego en si. Hay que ver que tal se ve una imagen puesta ahi porque es un iframe. Cuando me la pases probamos y si no toco el template.

**Comment by LeandroBraier** [comment]
Dale. No te preocupes, mañana te la paso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-22 18:26 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Listo lo de respuestas correctas:
http://parexklaukol.com.ar/vendedores/trivia-completa.html

Marce, fijate que al `<dl>` le agregué al final:

```
<dt>Respuesta #1:</dt
><dd class="respuesta">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</dd
><dt>Respuesta #2:</dt
><dd class="respuesta">Dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</dd>
```

Guarda que el tag cierra en línea nueva ^_^

**Comment by LeandroBraier** [comment]
Está bueno. Se tendría que sumar Pregunta #1 y Pregunta #2 antes de cada
Respuesta pero estéticamente está perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-23 9:44 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Este en realidad no es el thread correcto, este es el de las trivias nuevas.
Lo paso al otro y te repregunto algo.

**Comment by LeandroBraier** [comment]
Chicos, lo correspondiente a este ticket de nuevas trivias ya está resuelto? Puedo verlo final en algun link?

**Comment by mkreyness** [comment]
Te mande el link para verlo el mismo lunes:
http://www.parexklaukol.com.ar/cgi-bin/juegosvendedoresmk.pl?usuario=marcelokreyness&clave=pepe

Ahi aparecen todas las trivias,  pero ya las respondi asi que te aparecen como "hecho". Si en este URL le cambias el usuario y clave a los tuyos las ves.
De hecho no lo puse en produccion porque estaba esperando que me pasaras las imagenes correctas, te acordas ?

**Comment by LeandroBraier** [comment]
Genial MK. Acá te paso los thumbnails que te faltaban entonces. Decime si los ves todo bien y subilos nomás.

![kip-trivia-de-trabajabilidad](https://cloud.githubusercontent.com/assets/6719872/8329984/8ef0c100-1a54-11e5-973e-ced23d363d1e.jpg)
![kip-trivia-de-seguridad](https://cloud.githubusercontent.com/assets/6719872/8329985/8ef475fc-1a54-11e5-81c5-0884efbc1cd7.jpg)

![kip-trivia-de-trabajabilidad-1280x720](https://cloud.githubusercontent.com/assets/6719872/8329987/935cbb04-1a54-11e5-94dd-0ee6f371aca2.jpg)
![kip-trivia-de-seguridad-1280x720](https://cloud.githubusercontent.com/assets/6719872/8329988/935f121e-1a54-11e5-810a-5ff7ec5decfd.jpg)

Cuando esté listo lo de mostrar las respuestas correctas subamos todo junto a producción nomás.

abrazo

**Comment by mkreyness** [comment]
```
Me temo que voy a necesitar ayuda de nuestro amigo @FAAREIA porque
hay que remaquetar el lugar donde va la imagen.
Fede, el tema es asi: para estos temas que tienen una sola forma de
contestar la trivia hice un template separado, que se llama

juego-simpleT.html

El asunto es que en el lugar que en las otras va el video, en esta
va una imagen, que la guardo en el mismo campo de la base que en la
completa va el url del video, porque es verdad que lo reemplaza.
Por supuesto queda todo horrible porque la imagen se pasa del ugar.
Pegale una mirada por favor, es donde puse comentarios "aca esta la
chanchada".
Para verlo en accion:
```

http://www.parexklaukol.com.ar/cgi-bin/jugarmk.pl?id=2&usuario=marcelokreyness&clave=pepe

```
El 24/06/2015 a las 9:38, LeandroBraier
  escribió:


  Genial MK. Acá te paso los thumbnails que te faltaban entonces.
    Decime si los ves todo bien y subilos nomás.




  Cuando esté listo lo de mostrar las respuestas correctas
    subamos todo junto a producción nomás.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Dale F5.

**Comment by mkreyness** [comment]
```
Perfecto.
Me queda Lean entonces ver por qué sigue habilitado el juego una vez
ya hecha la trivia (el "Hecho" de afuera no lo inhabilita, pero
adentro deberia estar grisado el icono de "juga a esta trivia").
A la tarde arreglo eso y paso todo con cuidado a produccion. 

El 24/06/2015 a las 10:42, Federico
  Arena escribió:


  Dale F5.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Dale. Ya que estás agregale el tilde al primer "Qué" de "Qué significa que Klaukol..."

abrazo

**Comment by mkreyness** [comment]
Listo, lo del icono que no se me grisaba es porque yo soy un participante trucho que me pasaba de los 99 puntos entonces nunca sumaba. Borre mi historia previa y ahi lo grisó perfecto.
Ya está todo en producción y agregué el tilde al primer "Qué".

**Comment by LeandroBraier** [comment]
Perfecto. Gracias MK!
