### ISSUE TITLE
Nuevo Mailing Simple Klaukol. DEADLINE: 24/6

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#59]
Fede, necesito armar un mail de resubscripción para algunas listas.

Tiene que ser muy simple, solo tiene un botón que lleva a un formulario de MailChimp donde la gente se resubscribe.

Estética: Tipo ParexGroup: fondo gris concreto (sin los simbolitos de Klaukol Impermeable Potenciado, solo el fondo concreto, si lo necesitás te lo paso) y rojo y azul en partes igual. 

Subject: XXXNOMBREXXXXX, ParexKlaukol te invita a sumarte y ganar

Texto: En 2015, ParexKlaukol está consolidando una verdadera comunidad en el mundo de la construcción y la decoración de interiores. La integran arquitectos, empresarios, constructores, colocadores y vendedores de toda Latinoamérica que se encuentran en la búsqueda permanente de colaborar en la creación de lo nuevo y reciben por ello increíbles premios todos los meses.

Por eso, desde ParexKlaukol consideramos de vital importancia que vos también te sumes. Simplemente dando clic a este botón recibirás en esta dirección de email todas las novedades y oportunidades para corralones, arquitectos, vendedores, colocadores.

En el medio un botón de "Subscribirme" en rojo y azul.

**Comment by FAAREIA** [comment]
Se lo asigno a @braulio-evangelisti

**Comment by LeandroBraier** [comment]
@FAAREIA Fede, estamos atrasados con esto. Braulio no me respondo. Ya estaba prácticamente listo ayer, necesito el HTML para hacer el envio urgente por favor.

**Comment by LeandroBraier** [comment]
Gracias a los dos!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti necesitaría que quites lo de XXXXXNOMBREXXXXX en el título del mail, que quede simplemente "ParexKlaukol te invita a sumarte y ganar increíbles premios"

**Comment by braulio-evangelisti** [comment]
Listo fijate ahi
