### ISSUE TITLE
#7 Modificación de formato en Slideshow

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#60]
@FAAREIA , necesito hacer una modificación en el formato del slideshow

El texto del titular va a estar dentro de la imagen, en un estilo más similar a la foto del televisor con el futbolista que teníamos en la etapa previa al lanzamiento. A la derecha habría texto pero no con un titular tan grande como ahora, sería un titulo menor y después tres lineas de texto como está ahora.

Para cuando lo podríamos tener?

abrazo

**Comment by FAAREIA** [comment]
Eso sería un slide especial, porque los otros se mantendrían no?

**Comment by LeandroBraier** [comment]
No, cambiarían todos. De hecho tendríamos que subir dos juntos como ese,
además de adaptar el actual del viaje, claro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi ya hice un leve cambio. Lo podes ver sin programación y algo roto aca:
http://www.parexklaukol.com.ar/vendedores/home2.html
Tendrían que pasarme las imágenes ya con los títulos incrustados y los textos que irian al costado.

**Comment by LeandroBraier** [comment]
Ahi va! Genial!

Hoy te paso esas imagenes y titulos y lo subimos hoy.

De todas formas se podrá avanzar con el CMS para que las pueda subir
directamente yo?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-24 9:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
```
No esta CMSeado todavia, esta fijo en la maqueta.
Fede le podes poner variables y se lo agrego via CMS ?

El 24/06/2015 a las 13:17,
  LeandroBraier escribió:

Ahi va! Genial!

  Hoy te paso esas imagenes y titulos y lo subimos hoy.

  De todas formas se podrá avanzar con el CMS para que las pueda
  subir
  directamente yo?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-24 9:50 GMT-03:00 Federico Arena
  <notifications@github.com>:

  > Ahi ya hice un leve cambio. Lo podes ver sin programación y
  algo roto aca:
  > http://www.parexklaukol.com.ar/vendedores/home2.html
  > Tendrían que pasarme las imágenes ya con los títulos
  incrustados y los
  > textos que irian al costado.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/60#issuecomment-114858685
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Eso sería genial, asi no les gasto tiempo a uds con estas cosas.

Tengan en cuenta que el slideshow del torneo de corralones debería tener
este mismo cambio.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-24 15:02 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Habría que agregarlo al CMS primero, subir las imágenes, título secundario y textos. Y luego implemento las variables asi ya se ve online de una.

**Comment by LeandroBraier** [comment]
Hablalo con @mkreyness Según entendí yo él necesitaba que arrancaras vos.

**Comment by mkreyness** [comment]
puedo ir avanzando una parte, pero para verlo andando necesito que este maquetado en el template

**Comment by FAAREIA** [comment]
Hay que replicar el template entonces.

**Comment by mkreyness** [comment]
Creo que estamos hablando de cosas diferentes, yo me referia a lo de TORNEO. Aca estas hablando de Vendedores ?

**Comment by FAAREIA** [comment]
Creo que si ^^

**Comment by mkreyness** [comment]
Para vendedores es otra cosa porque esta en produccion, si, replicalo con otro nombre y agregale las variables que necesites y yo en base a eso lo armo en el CMS.

**Comment by mkreyness** [comment]
Igual hasta las 4 de la tarde no voy a poder avanzar con nada de esto. Si tienen que hacer algun cambio urgente yo diria Fede que lo hagas directamente sobre lo que esta en produccion, y despues le damos la generalidad del CMS.

**Comment by FAAREIA** [comment]
Marce, ahi subi un mainT-2.html con las variables.
Abrazo
