### ISSUE TITLE
Mailing a reenviar a usuarios ya inscriptos

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#62]
MK, hay un usuario que dice que no recibió el mailing de bienvenida. Habría que volverselo a enviar.

Su nombre de usuario es MLauraBonaventura.

No hay apuro tampoco. Cuando puedas nomás, antes del sábado.

abrazo

**Comment by LeandroBraier** [comment]
Ante la duda enviaselo también a esta dirección de email, aunque no quede acentada como mail oficial del usuario:

calerasanjusto@yahoo.com.ar

**Comment by mkreyness** [comment]
Tenes forma de chequear cual es su mail ?
Porque salir, salio, a esta direccion:
laurabonaven@yahoo.com.ar

**Comment by LeandroBraier** [comment]
Yo también tengo el mismo. Debe haber algun error, o quizá le cayó en spam. No pierdas mucho tiempo, reenviaselo a ese mail y a CaleraSanJusto@yahoo.com.ar y ya fue.

abrazo
