### ISSUE TITLE
Listado de actividad vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#63]
MK, cuando puedas pasame como descargarme un excelc on la actividad de cada vendedor y poder hacer un analisis.

abrazo

**Comment by mkreyness** [comment]
Ya esta puesto en el menu de "Club de Vendedores", bajo el nombre de 
"Consulta de Actividad".
Te sale:
- vendedor
- corralon
- juego/actividad
- puntos
- fecha

y podes filtrar si queres por persona o actividad, y por supuesto rango 
de fechas.
Si te sirve algun otro dato del vendedor para poner (por ej, provincia) 
avisame.

**Comment by LeandroBraier** [comment]
Si, me sirve. Si podés sumarlo genial, no es urgente, pero en algun momento
me lo van a pedir.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-24 19:27 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Gracias MK!
