### ISSUE TITLE
Mailing de subscripción a Lista Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#64]
@mkreyness 

Apenas puedas necesito que envies este mailing a la lista que te paso via mail.

http://parexklaukol.com.ar/_mailing/sumarme/

Puede ser entre hoy a la tarde y mañana a la mañana todo bien.

abrazo

**Comment by mkreyness** [comment]
Ok, en un rato lo mando.

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Modificado Marce!

Avanzá.

**Comment by mkreyness** [comment]
Veo mucha basura en los nombres que me pasaste en el excel (todo lo que deberia ser acentos), a vos te aparecen bien ? Ademas estan dados vuelta y tienen el titulo al final.
Por ejemplo:
"Cerini MarÃ­a Cristina Arq."
queda feo que diga "Arg." despues del nombre, o 
"CÃ©spedes JosÃ© MarÃ­a M.M.O."
(M.M.O es Maestro Mayor de Obras)
Si mejor los mando sin mostrar el nombre en el subject ? Preferible nada antes que algo feo.
Hasta hay casos sin nombre (son internos de parex).

**Comment by LeandroBraier** [comment]
Exacto. Que no se vea el nombre en el subject mejor. Incluso tampoco en el
nombre que aparece en el "To:" del mail.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-25 16:42 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
OK, te voy a mandar uno de prueba y si lo recibis OK, largo todo.

**Comment by mkreyness** [comment]
confirmame

**Comment by mkreyness** [comment]
Te llego ?

**Comment by LeandroBraier** [comment]
No me llegó che. Me preocupa.

A Gmail lo mandaste?

**Comment by mkreyness** [comment]
No, a leandro@benteveo.tv
Ahora te mando a gmail.
Los que me mande a marcelo@kreyness.com me llegaron bien.

**Comment by LeandroBraier** [comment]
Me llegó al spam che, ahi lo vi. Tiene algun problema, mirá como lo veo.

![captura de pantalla 2015-06-25 a la s 18 36 52](https://cloud.githubusercontent.com/assets/6719872/8366023/b5d99076-1b67-11e5-8867-2c0320e8432b.png)

**Comment by mkreyness** [comment]
Ah, mira que raro, a mi me lo muestra bien. Menos mal que probamos.
Es el enter del final de "/html" que nunca me lo graban. Ahi se lo 
agrego a mano y te mando de nuevo.

**Comment by LeandroBraier** [comment]
dale genial

**Comment by mkreyness** [comment]
te mande a benteveo y a gmail, confirmame si ambos se ven bien y largo todo.

**Comment by LeandroBraier** [comment]
No me llegó ninguno. NO sé por qué.

**Comment by mkreyness** [comment]
Me mande a mi mismo a gmail y tampoco me llego. Rebotes de hoy en la cuenta de admin del sitio no hay. No se si puede estar llegando rebote a "marketing parexklaukol".
Pero lo que me mando a kreyness.com llega perfecto. Podras fijarte si lo que te mando a benteveo pueda estar entrando en el servidor viejo (el de Guilleron)?

**Comment by LeandroBraier** [comment]
No, porque ya no existe en el de guilleron. Lo borro Marce el lunes creo.

Estará entrando como spam?

**Comment by mkreyness** [comment]
Al menos a mi Gmail no, ni spam ni nada.

**Comment by mkreyness** [comment]
fijate de nuevo por favor si te llego, me mande a fibertel, el sntispam me puteo por algo, le hice unos toques y ya no putea. A GMail sigue sin entrarme pero fijate en benteveo.

**Comment by LeandroBraier** [comment]
Ahi me llegaron dos juntos y no al spam. Llegaron bien pero sigue el mismo
problema. Recien te lo reenvie.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-25 19:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Y no me llego lo que reenviaste, esto esta medio maldito.
Ojo que capaz esos que te llegaron con el defecto eran viejos ?

El 25/06/2015 a las 20:07,
  LeandroBraier escribió:

Ahi me llegaron dos juntos y no al spam. Llegaron bien
  pero sigue el mismo
  problema. Recien te lo reenvie.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-06-25 19:59 GMT-03:00 mkreyness
  <notifications@github.com>:

  > fijate de nuevo por favor si te llego, me mande a fibertel,
  el sntispam me
  > puteo por algo, le hice unos toques y ya no putea. A GMail
  sigue sin
  > entrarme pero fijate en benteveo.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/64#issuecomment-115424158
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.
