### ISSUE TITLE
Error en Fechas de Novedades ParexKlaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#65]
Marce, fijate que yo cargo una fecha en el cms y en el sitio se despliega con otra fecha más adelantada. Habría que revisar eso porfa. Sin apuro.

abrazo

**Comment by LeandroBraier** [comment]
A esto se suman otra inconsistencia en ese CMS: Lo que actualizaste en el CMS del cliente no se actualizó en http://72.52.188.248/cgi-bin/red.pl 

Por ejemplo, el editor de html, el orden de las búsquedas, etc.

**Comment by mkreyness** [comment]
no hay que usar mas por IP, tenes que usar por 
www.parexklaukol.com.ar/cgi-bin/red.pl, aunque se refiera a cosas de 
paraguay y uruguay

**Comment by LeandroBraier** [comment]
Ah, ok. No hay que usarlo más para Novedades o para lo demás?

Porque por IP es el único CMS donde tengo todo lo demás.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 13:34 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Hay una sola base de datos, todos los accesos al CMS te tienen que 
mostrar lo mismo, lo que pasa es que esa version por IP te va a fallar 
por 20 lados.
Tiene que aparecerte todo.

**Comment by LeandroBraier** [comment]
Tenés razón, era una confusión mia. Ya encontré todo.

abrazo y gracias!
