### ISSUE TITLE
Simulador de Fachadas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#66]
@mkreyness cuando tengas tiempo la semana que viene revisá el funcionamiento.

Cuando pongo las opciones revoque grueso o fino, por ejemplo, se me queda cargando. Estoy en chrome de mac.

http://www.parexklaukol.com.ar/aplicaciones/simulador-de-fachadas.html

**Comment by mkreyness** [comment]
Te pasa SIEMPRE ?
A mi me anda bien, no creo que eso pueda depender del browser, es una 
busqueda en la base de datos en el server.

**Comment by LeandroBraier** [comment]
Hoy me pasó todas las veces pero ayer probé una vez y me anduvo mal, la
segunda me anduvo bien. Por eso no te avisé ayer.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 13:31 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Acordate que todo esto es lo de gleepa, no tengo mucho control.
Puede que la base de datos le timeoutee, pero me parece raro porque es 
todo local.

**Comment by LeandroBraier** [comment]
OK, dejemoslo así, si ve que sigue pasando te aviso. Gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 14:07 GMT-03:00 mkreyness notifications@github.com:
