### ISSUE TITLE
Cambiar Legajo Impositivo en Web ParexKlaukol. 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#67]
@braulio-evangelisti te paso para cambiar el legajo impositivo de la web de ParexKlaukol cuanto antes.

https://drive.google.com/file/d/0B_6ywYX9PGKLTUdxYTlJVzFrRVA5SGJ3alFLVmdpZUxMNC1r/view?usp=sharing

Confirmame por favor si puede estar cambiado para hoy a la noche.

abrazo

**Comment by braulio-evangelisti** [comment]
Dale, termino la newsletter y cambio esto.
Abrazo

**Comment by LeandroBraier** [comment]
Genial, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Lea no tengo acceso por FTP a la carpeta donde esta subido el legajo actual para reemplazarlo.

Puede que el administrador haya restringido permisos para esa carpeta al usuario FTP que tengo.

Otra puede ser que ese archivo se suba por algun gestor/administrador que tenga el sitio. De ser asi no tengo acceso al mismo.

**Comment by LeandroBraier** [comment]
Consultalo con Fede, él lo subió al último si no me equivoco.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 18:51 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA necesitaría cambiar el legalo impositivo. Vos sabés donde hacerlo?

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias Fede!! 

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti necesitamos actualizar el legajo impositivo en la web de Parex Klaukol

Descargalo de acá:

https://www.wetransfer.com/downloads/bee6b8f621bb6329c45b7e654b00a4d820150924152209/cab9cf66efd5673e3c00f3e003e6815b20150924152209/852d16

**Comment by braulio-evangelisti** [comment]
La ultima vez que probe hacer este cambio no tenia acceso a la carpeta del servidor para subir el archivo. Pruebo y cualquier cosa te aviso.

Abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA me dijo Brau que no va a estar disponible hasta el miércoles por tema familiar. Porfa mañana sin falta dejemos actualizado este Legajo.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

**Comment by LeandroBraier** [comment]
Buen día @braulio-evangelisti o @FAAREIA necesitaría que actualizaran una vez más este legajo impositivo.

[Legajo Impositivo 2016.pdf](https://github.com/LeandroBraier/Klaukol/files/88962/Legajo.Impositivo.2016.pdf)

Porfa avisenme cuando esté online.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

**Comment by LeandroBraier** [comment]
@FAAREIA para el lunes podrás actualizar una vez más el legajo impositivo de abajo en la web de Parex?

[Legajo Impositivo 2016.pdf](https://github.com/LeandroBraier/Klaukol/files/529981/Legajo.Impositivo.2016.pdf)

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA !!

**Comment by LeandroBraier** [comment]
@FAAREIA  ya tenemos el legajo 2017. Lo podrías actualizar porfa para mañana y confirmarme?

[Legajo Impositivo 2017.pdf](https://github.com/LeandroBraier/Klaukol/files/742939/Legajo.Impositivo.2017.pdf)

abrazo

abrazo

**Comment by LeandroBraier** [comment]
buen día @FAAREIA ! Subiste esto? Por favor necesito que lo subas URGENTE porque me lo pide el cliente.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA ! Pasate a wunder porfa y seguimos pr ahi!

abrazo
