### ISSUE TITLE
Maquetación Newsletter ParexKlaukol. DEADLINE: 06/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#68]
Fede, necesitamos maquetar el newsletter mensual de Klaukol en formato responsive. No es prioridad ahora pero tratemos de respetar esta fecha que te pongo, que es posterior a la entrega de torneos y demás.

http://parexklaukol.com.ar/_mailing/novedades/

Este de junio ya lo mandé, así que la maquetación nos debería servir para ir cambiándole el contenido de textos y fotos y que el resto se mantenga.

abrazo

**Comment by FAAREIA** [comment]
Se podrían hacer algunos mínimos ajustes para lograr algunos detalles, pero la realidad es que no existe un newsletter responsive. No hay forma de poner reglas para que se vaya ajustando.
Capas que lo mejor sería ver en donde lo ven "pésimo" y tratar de mejorarlo.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/torneo-corralones/login-c.html
http://www.parexklaukol.com.ar/torneo-corralones/login-c2.html
http://www.parexklaukol.com.ar/torneo-corralones/login-r.html

http://parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=coronel&clave=coronel&torneo=1&tipo=R
http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=test&clave=test&tipo=C&torneo=1

http://www.parexklaukol.com.ar/torneo-corralones/bases-condiciones.html

Marce, ojo que en el template de slideT-C, al final incluí un script para llenar los "data-puesto". No te olvides se sacarlo cuando este hecho lo del orden.
Por otra parte, habría que poner en template a las bases y condiciones para que se vea el nombre de usuario.

**Comment by LeandroBraier** [comment]
Muchísimas gracias Fede!

Ahora lo veo y te doy feedback.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-29 16:54 GMT-03:00 Federico Arena notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Buen dia Lea
Cuando lo hayas visto avisa que se necesita acomodar de esto asi lo vamos viendo.
Abrazo

**Comment by LeandroBraier** [comment]
Buen día Braulio! 

Te cuento: más que nada me parece que para Mobile está muy ancho. No lo leo bien en formato vertical, eso suele ocurrir, pero al menos al ponerlo en formato horizontal debería poder verlo bien. El resto está OK.

Igual este pedido incluye que lo maqueten como newsletter, no como un html armado solo con imágenes. Eso es lo principal porque sino estos mails llenos de imágenes van directo al spam. 

También revisá el html una vez que lo hayas terminado. Mirá que en los últimos dos html que maquetaste había espacios de más, etiquetas que cerraban y nunca abrían, cosas así. Revisalo porfa.

abrazo

**Comment by FAAREIA** [comment]
Hay un tema igual, ese newsletter no se va a ver bien en mobile nunca. Se podría hacer que el ancho máximo sea 640px y que si el dispositivo tenga 480px, el newsletter mida 480px pero las imágenes van a quedar mal, los textos también y todo va a quedar mal superpuesto. Reitero: No existe el newsletter responsivo. Se puede hacer que se ajuste al ancho mediante el uso de %, pero no se puede hacer que quede bien, eso no va a pasar.
Se puede pasar a HTML y que se ajuste el ancho pero el contenido seguro quede comprimido, mal y desarticulado en mobile.
Adicionalmente el mobile es medio impredecible, el iphone de Marce S. agrandaba los textos a su antojo y rompia algunas cosas.

**Comment by LeandroBraier** [comment]
Ok, no hay problema entonces. Hagamoslo de ancho máximo 640px y nada más.
me parece que quedé el acento en responsive cuando debió haber quedado el
acento en maquetación. Lo importante es que el newsletter esté maquetado,
no con imagenes cortadas nada más. Lo de responsive ya fue, solo lo del
ancho está bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-30 15:38 GMT-03:00 Federico Arena notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Acomodo algunos detalles y la subo

**Comment by braulio-evangelisti** [comment]
Listo Lea, la subi aca:

http://parexklaukol.com.ar/_mailing/novedades2/

Abrazo

**Comment by LeandroBraier** [comment]
Excelente laburo Braulio!!

Gracias!

Cierro el ticket. Tené en cuenta que cuando te pase los contenidos y fotos del Newsletter de Novedades de Julio es este el template que tendrías que tomar de base para armarlo.

abrazo
