### ISSUE TITLE
Nuevo Mailing Vendedores (adaptación de mailing de bienvenida)

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#69]
@FAAREIA necesito que hagas una adaptación del mail de bienvenida pero con esta estética y texto.

https://www.wetransfer.com/downloads/75854215089b13bdaf51150044dc456a20150629205302/746e61078914624d9727418680b000c220150629205302/36a278

Llegás a tenerlo para hoy? Hoy no le pasé nada a Braulio yo.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/_mailing/vendedores-sorteo/vendedores-sorteo.html

**Comment by LeandroBraier** [comment]
Mil graciass Fede!! Sos un grande.

abrazo
