### ISSUE TITLE
Nuevas Bases de Usuarios Comunidad de Vendedores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#70]
@mkreyness te pasé por mail dos bases corregidas sin repetidos.

Necesitaría si las podés cargar y enviar los mails de bienvenida hoy mismo, a más tardar mañana a la mañana , porque el cliente se atrasó corrigiendolos y parece que se le puede armar conflicto con esos vendedores.

Me confirmás si llegás?

abrazo

**Comment by mkreyness** [comment]
ya terminaron de salir

**Comment by LeandroBraier** [comment]
Gracias MK!
