### ISSUE TITLE
Actualizar Fichas Técnicas Productos ParexKlaukol. DEADLINE: 01/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#71]
Fede, esto es una pavada y es para mañana a la tarde tranqui.

necesito reemplazar las fichas técnicas de la mayoría de los productos de Klaukol (salvo Impermeable Potenciado).

Están todos aquí:

https://drive.google.com/open?id=0B_6ywYX9PGKLNGw5SDhnUFJTcVk

abrazo

**Comment by FAAREIA** [comment]
Puede ser fácil pero lleva tiempo. Más allá de eso en el CMS no hay lugar para reemplazar el archivo.
Cómo queres hacer @mkreyness ?

**Comment by LeandroBraier** [comment]
SI hubiera lugar en el CMS lo hago yo chicos. Avisenme nomás.

No es urgente. Puede ser incluso para el jueves también.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-30 15:17 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Si las fichas tecnicas son los documentos adjuntos, de alguna manera ESTA todo en el CMS.
El asunto es que lo que no se puede es UPLOADEARLOS via el CMS, porque lo que nos vino en los backups estaba todo desperdigado.

Hay que subirlos a una carpeta accesible desde donde el sistema espera que esten, que por como vino todo mal parido es:

public_html/bkps/parexklaukol.com.ar/media/custom/upload/XXXX (o parexparaguay.com.py, etc.)

y en la parte de archivos adjuntos del CMS poner solo la parte XXXX

Por ejemplo ahora el del Porcellanato Fluido esta en

http://www.parexklaukol.com.ar/bkps/parexklaukol.com.ar/media/custom/upload/File-1402063506.pdf

y en el CMS (solapa Adjuntos) dice:

Nombre: Ficha Tecnica
URL: /pdf/productos/File-1402063506.pdf

porque asi vino en algun momento, pero el programa (asco total) reemplaza /pdf/productos por /media/custom/upload

O sea, no se si los archivos que tenes que cambiar conservan los nombres o tienen otros, pero si se bajan en

public_html/bkps/parexklaukol.com.ar/media/custom/upload/

y se cambian los nombres en el CMS, todo deberia salir andando.
Probemos con uno si quieren.

**Comment by FAAREIA** [comment]
Lea, dame acceso al google drive asi me lo bajo y veo todo.

**Comment by LeandroBraier** [comment]
Ahi te pasé el acceso. Avisame si pudiste.

abrazo

**Comment by FAAREIA** [comment]
No tengo acceso pero ahi te pedi con la cuenta de gmail el acceso

**Comment by LeandroBraier** [comment]
Ahi te lo pasé. Confirmame si ahora si

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahora si

**Comment by FAAREIA** [comment]
Hecho, ya estan todas actualizadas. Les cambié el nombre a uno más SEO.
Eran solamente fichas técnicas de algunos productos.
El PDF "klaukol-hiperflex-fluido-ficha-tecnica.pdf" no lo pude ubicar porque no existe el producto HiperFlex Fluido, sino el Flex Fluido. El pack es diferente al igual que el nombre.

La actualización la hice en Argentina.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Ahora consulto si va en Paraguay y Uruguay también y qué hacemos con
hiperflex fluido.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-01 10:56 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Gracias chicos!

Hipeflex no va por ahora y en paraguay y uruguay no se actualiza.

Chas gracias por la velocidad.

abrazo
