### ISSUE TITLE
Subir usuarios Vendedores sin mail

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#72]
Marce, hay posibilidad de que te pase una base de usuarios sin mail y crearles usuario y clave a todos juntos?

La gente de Klaukol se encarga de informa a esa gente.

**Comment by mkreyness** [comment]
Si, mientras tengan codigo y password.
Igual te cuento que el server físico en el q esta klaukol es el mismo q benteveo, esta inaccesible parece

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Ahora te paso la lista entonces.

abrazo

**Comment by LeandroBraier** [comment]
Te llegó?

**Comment by mkreyness** [comment]
Si, ya los cargue.

**Comment by LeandroBraier** [comment]
Gracias!
