### ISSUE TITLE
Torneo de Potenciados #2 Perfil de Distribuidor. DEADLINE: 03/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#73]
Fede, como le comentaba a MK el otro día, necesitamos sumar un perfil de cada usuario corralón. 

Tendría el mismo formato que el perfil de usuario de la comunidad de vendedores.

DATOS DEL USUARIO

DATOS DEL CORRALÓN

TUS LOGOS

En esta parte, en lugar de de puntos habría lo siguiente:

PERFIL DEL CLIENTE

Cantidad de bolsas equivalentes compradas hasta el momento (y dividido por mes).

packs comprados de cada uno de los Productos

Objetivo Semestral y promedio mensual.

Barrita general (la misma que se ve en el dashboard)

Velocimetro mensual igual que en el dashboard.

Llegamos a tenerlo para el viernes tipo mediodía?

abrazo

**Comment by FAAREIA** [comment]
Si no aparece nada urgente, yo creo que si

**Comment by LeandroBraier** [comment]
Con esto no llegamos para hoy al mediodía obviamente, pero para la noche llegamos?

**Comment by FAAREIA** [comment]
El tema es que tengo que hacer otras cosas también, lo ideal sería dejarlo para el lúnes a primera hora. Pensá que falta el diseño aún.

**Comment by LeandroBraier** [comment]
Ok. Todo bien, el lunes a primera hora.

abrazo

**Comment by LeandroBraier** [comment]
Buen día Fede!

Cómo venís con esto?

**Comment by FAAREIA** [comment]
Ahi va un adelanto, me falta estilizarlo un toque.
http://www.parexklaukol.com.ar/torneo-corralones/usuario-perfil.html

Lo que necesitaría definir bien es la tabla y para eso necesito la ayuda de @mkreyness , principalmente para ver como poner lo siguiente:
"Cantidad de bolsas equivalentes compradas hasta el momento (y dividido por mes). packs comprados de cada uno de los Productos" (tabla aparte?)
"Objetivo Semestral y promedio mensual."

**Comment by LeandroBraier** [comment]
Buenisimo, coordinen con Marce entonces. 

La diagramación la veo bien. Sería ideal que la foto de perfil, al sumarse, se viera ahí, como para que tenga alguna imagen el perfil.

No te olvides que además de la barrita general estaría faltando el velocímetro mensual.

abrazo

**Comment by mkreyness** [comment]
La info que yo supongo que va a venir (porque todavia nunca me mandaron datos reales) va a estar abierta en 3 columnas de producto, en c/u hay que poner una cantidad, y entiendo que los renglones deberian corresponder a los 6 meses del torneo y un total abajo.
Como cada columna de producto tiene una ponderacion diferente, deberia haber una columna despues de las 3 columnas de producto una con el total de "puntos" (o como lo quieran llamar) acreditados.
Los datos de objetivo semetral y promedio mensual son unicos, pero para visualizar mejor lo del velocimetro, deberiamos repetirlo como una columna mas, o sea que el semestral es el total de la columna.

Algo asi:

Mes   Prd1 Prd2 Prd3 Puntos Obj.Mens  "barrita" Velocimetro
Julio   10   10      10     60        50                         [(60*100/50)-100]
Agosto
...

## Diciembre

Total   10  10      10      60    300

**Comment by FAAREIA** [comment]
Ahora si, va todo completo:
http://www.parexklaukol.com.ar/torneo-corralones/usuario-perfil.html

**Comment by LeandroBraier** [comment]
Está muy bueno, Fede. Solo te pido cambios de texto:

Donde dice Diciembre poné Julio y otro mes.

En el menú:

Donde dice Producto #1 poné Impermeable Potenciado

Donde dice Producto #2 poné Porcellanato

Donde dice Producto #3 poné Flex Fluido

Donde dice Velocidad poné Ventas/Mes

Con eso estamos para la entrega. Gracias!

abrazo

**Comment by mkreyness** [comment]
Los productos esta bien que sean fijos, pero el mes (al menos en la 
version template) tiene que quedar como una variable, que ire 
completando con los datos.

**Comment by LeandroBraier** [comment]
Perfecto, perdón!

Igual el primer mes que aparezca debería ser Julio, que ya está sumando
ahora no?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 15:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Va a estar sumando el dia que manden algun dato real, por ahora son 
todos inventados y les puedo poner la fecha que sea necesaria.

**Comment by LeandroBraier** [comment]
Perfecto entonces. Cuando el resto de esos cambios del menú avisen porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 15:32 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Fede cuando hagas esos cambios por favor dejamelo templatizado en

www/templates/parexklaukol/torneos/perfilT.html

**Comment by FAAREIA** [comment]
Ahi ya deje todo listo.

**Comment by mkreyness** [comment]
Esta bien que el que accede a esto (supongo que el dueño del corralon) pueda estar cambiando el nombre y domicilio ? Esto afectaria directamente a la guia de corralones y lo que sea que escriba va a salir publicado.

**Comment by LeandroBraier** [comment]
Estoy de acuerdo. Que eso solo lo podamos modificar nosotros, Marce!!

Gracias Fede!!

Quedó buenisimo!

FEDE: Un detalle que veo acá y me hace acordar que todavía no está en el
dashboard principal del Torneo: falta el indicador del 100%, que no va
arriba de todo de la barra, sino a la mitad de la misma. Arriba de todo no
debe decir nada, pero el máximo es el 200%. Lo habíamos hablado pero
hablalo con MK que te lo explico. Es porque se supone que todos tienen que
superar su objetivo. Así como el velocimetro tiene el 100% al centro del
semicírculo, no a la derecha de todo, la barra debe tenerlo en el medio y
no arriba de todo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 16:00 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
ya pueden verlo medianamente en accion aca:

http://www.parexklaukol.com.ar/cgi-bin/perfilcorralon.pl?usuario=test&clave=test&torneo=1

todavia el programa que "Guarda" lo que pongan ahi no existe, pero queria que fueran viendo lo de las ventas abajo.
Puse los meses que hay datos (inventado) y un renglon de "TOTAL SEMESTRE".
Yo sacaria la palabra "Mensuales" de "Objetivo", esta claro que es de cada mes y abajo el total semestre.
Lo que no logro hacer andar es el velocimetro, que valores tiene que recibir en el data-velocidad, Fede ? Le estoy poniendo proporcional como si fuera de -5 a +5, pero no me lo toma.

**Comment by LeandroBraier** [comment]
Gracias MK!

Lo veo genial.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 18:16 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
provincia y ciudad estan al reves.
Los voy a dar vuelta y le cambio "Obj.mensuales" por "Objetivo", ok ?

**Comment by LeandroBraier** [comment]
Un detalle más: Si se llama "Tu perfil" no debería decir debajo "Tus datos"
y "Tu distribuidor"?

Donde dice Corralón debería decir Distribuidor, jeje

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 18:48 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 18:47 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
"Tu distribuidor" a mi me suena raro, pareceria de que le estas hablando acerca de quien le vende al corralon, no del corralon en si. Yo pondria "Tu negocio" ?

**Comment by mkreyness** [comment]
O "Tu empresa" ?
Y tampoco me parece coherente que abajo diga "Perfil del cliente", eso en todo caso seria si lo estuviera mirando el corredor, pero no el corralon.

**Comment by LeandroBraier** [comment]
Saquemos el TU a todo entonces.

"Perfil del Distribuidor"

"Usuario"

"Empresa"

(Cuando vuelva Duplika digamos)

**Comment by mkreyness** [comment]
Listos esos cambios.
Para @FAAREIA : puse un link para que desde la pagina del torneo se acceda al perfil haciendo click en el nombre/foto del usuario, pero no se ve bien (se puso oscura la parte del nombre).
Fijate en el template como se puede arreglar.
Otra cosa es que ya puse que muestre la foto de usuario que se cargue en el perfil (tanto en con-slideT-C.html como en perfilT.html), pero la foto que subi es grande y no la escala como deberia.
Fijate que si le haces abrir en nueva pestaña la muestra completa.
Estoy hablando de esto:
http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=test&clave=test&torneo=1
y esto:
http://www.parexklaukol.com.ar/cgi-bin/perfilcorralon.pl?usuario=test&clave=test&torneo=1

**Comment by FAAREIA** [comment]
@mkreyness puse 5 instancias del velocimetro a través del atributo "data-velocidad".
Instancias:
data-velocidad="-2"
data-velocidad="-1"
data-velocidad="0"
data-velocidad="1"
data-velocidad="2"
Fijate si te sirve, mi idea era que agarres el porcentaje y en base a eso definias en que velocidad anda.

Vos pusiste 11 instancias contando el 0, lo cual me parece demasiado para un gráfico chiquito, fijate si lo podes acotar a 5 ^^

**Comment by FAAREIA** [comment]
Ahi esta listo lo del 100% en la barra y lo de la foto de perfil en la barra superior.

**Comment by mkreyness** [comment]
Ok, este era el dato que no tenia.
Igual me parece un poco grueso tener solo 2 valores positivos y 2 negativos.
"0" seria entonces por ejemplo entre -33% y 33%, -1 seria entre -66% y 
-34%, 1 seria entre 34% y 66% y los extremos -67% en adelante -2 y 67% 
en adelante +2 ?

**Comment by FAAREIA** [comment]
Yo pondría 0 de 0 a 25%
1 . 25% a 100%
2 . 100%+
-1 . -25 a -100%
-2 . -100%

Pensá que el gráfico es meramente ilustrativo, lo importante es el número

**Comment by mkreyness** [comment]
pero 100% es un valor extremo que en el caso negativo nunca se va a dar, 
no tiene sentido reservar una rayita para un valor unico.
Por eso yo decia 67%

**Comment by FAAREIA** [comment]
Ok dale asi entonces
