### ISSUE TITLE
Carga de Nuevos Slides Comunidad de Vendedores en el Slideshow

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#74]
Fede, en un ratito te paso un slide para reemplazar el actual del slideshow de vendedores. Cómo hacemos?

1) ¿Te lo paso o lo puedo cargar en el CMS?

2) ¿Ya tendría el nuevo formato más ancho y con menos texto que habíamos hablado? Podremos sino cambiarlo a un formato como el del Torneo de Potenciados que ocupe todo el ancho?

Pensá que necesito subirlo lo antes posible, con lo cual decime cual es la via más rápido nomás y después vemos el tema que lleve más tiempo (CMS, cambiar formato, etc)

**Comment by FAAREIA** [comment]
Ya le había dejado un template preparado para el cambio que habias pedido pero desconozco si marce lo vió y aplicó.
@mkreyness 
Creo que en vendedores era un slide unico para todos, asi que pasame y lo subo sino

**Comment by LeandroBraier** [comment]
Genial! Estoy esperando aprobación del cliente.

Gracias!

**Comment by mkreyness** [comment]
Estoy en el dentista asi que no me esperen.
Lo que haya que cambiar en el template en curso cambialo.
Yo nunca llegue a CMSear esta parte.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Van los nuevos slides Fede!

![slide-primer-ganador-version-1-v2](https://cloud.githubusercontent.com/assets/6719872/8484268/0b7fe7c2-20cd-11e5-991f-c2e79f78c1af.png)

El texto es:

Titulo: Estamos contactando al Ganador del Premio de Junio.

Descripción: Mientras tanto, ya podés sumar puntos para el espectacular premio de Julio. 
Seguí atento nuestra página de Facebook.

Este slide desplaza el otro que está ahora. Afuera la valija, no va más.

Me avisás cuando esté arriba porfa?

abrazo

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl

Ahi ya lo subí
En 20m ya me tengo que ir, cualquier cosa avisame lo antes posible

**Comment by LeandroBraier** [comment]
Se ve muy feo en el No registrado. Mirá:

![captura de pantalla 2015-07-02 a la s 16 40 42](https://cloud.githubusercontent.com/assets/6719872/8485946/a17735d2-20d7-11e5-87cb-1d292a33c9ea.png)

En el registrado no está tan feo, pero el texto no luce bien, mirá:

![captura de pantalla 2015-07-02 a la s 16 41 52](https://cloud.githubusercontent.com/assets/6719872/8485966/c4816b6a-20d7-11e5-8e0f-06690a58e769.png)

Dale un espaciado entre titulo y cada renglón de la descripción, así quizá mejora.

Te paso una versión más chica por si queda mejor. Fijate si queda mejor a tu criterio:

![slide-primer-ganador-version-1-v3](https://cloud.githubusercontent.com/assets/6719872/8486020/33474e0c-20d8-11e5-939f-2644c5db657c.png)

abrazo

**Comment by LeandroBraier** [comment]
Fede, lo pudiste solucionar? Lo veo muy feo y esto está en producción. Necesito que lo resuelvas URGENTE.

**Comment by LeandroBraier** [comment]
Fede, cuando vuelvas probamos cómo hacer para que el texto del slideshow quede abajo y la columna derecha ocupe el espacio que queda a la derecha del Slideshow. Se puede eso?

abrazo

**Comment by mkreyness** [comment]
Lean, ahi hice unos ajustes que me pidio Fede para que se vea mejor la 
foto, fijate si te parece OK y yo creo que deberiamos liberar el 
countdown de agosto, asi como esta queda incoherente.

**Comment by LeandroBraier** [comment]
Buenisimo MK!

Por lo menos quedó prolijo.

Respecto del texto de la derecha,no le podrás poner un par de <p></p> o de
</br> para que no estén tan amuchadas las líneas ahí arriba y queden con un
poco más de espacio?

Por lo menos hasta que resolvamos más definitivamente el diseño de eso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-02 18:58 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
a ver ahi como lo ves.
Y confirmame si cambio la fecha de sorteo a 1-agosto asi empieza el 
countdown.

**Comment by LeandroBraier** [comment]
Quedó bien el espacio MK. Si le podés dar un espacio más entre los dos textos de la descripción mejor, sino ya fue. Mañana lo terminamos de ajustar. 

El countdown arrancalo nomás cuanto antes.

abrazo

**Comment by mkreyness** [comment]
```
listo ambas cosas.

El 02/07/2015 a las 21:10,
  LeandroBraier escribió:


  Quedó bien el espacio MK. Si le podés dar un espacio más entre
    los dos textos de la descripción mejor, sino ya fue. Mañana lo
    terminamos de ajustar. 
  El countdown arrancalo nomás cuanto antes.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Gracias MK!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-02 21:37 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi lo pasé a CSS los cambios para que quedén.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede. Qué opinás de lo que te decía, que la columna derecha suba
por sobre el texto, para que rellenar ese espacio en blanco?

En caso de que no se pueda, decime cuál sería el tamaño ideal para que la
imagen del slideshow quede bien y te adapto la gráfica. Me preocupa que
queda medio desbalanceado visualmente no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Uno siempre tiene que pensar que el contenido a veces te define el diseño. Poco contenido con una imagen asi de grande no queda, es preferible hacer 1 sola imagen con el texto incrustado, pero tené en cuenta que si lo haces con una, lo haces con todas.
El tamaño es el mismo que el torneo, 984px de ancho máximo.

**Comment by LeandroBraier** [comment]
Ok, perfecto. Ahora te paso rediseño.

Te aviso que hoy vamos a tener nuevos slides para subir. Cómo hacemos? te
los paso a vos no?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-03 11:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si por ahora

**Comment by LeandroBraier** [comment]
Ok, Fede. Te paso un slide para centrarlo, de 900px de ancho. Va sin texto.

Este reemplaza el actual que dice "Tenemos un ganador".

![slide-primer-ganador-hernan-nunez](https://cloud.githubusercontent.com/assets/6719872/8503188/88963b2a-2191-11e5-9202-39b1d39a7bb2.png)

Después te voy a pasar uno más para subir a la tardecita.

Avismae cuando esté subido porfa.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! 

Quedó gigante, te paso versión de 600 px de ancho, a ver si queda mejor.

![slide-hernan-nunez-2](https://cloud.githubusercontent.com/assets/6719872/8504840/c205744e-21ae-11e5-98d6-a9cd8a44fb63.png)

En un ratito te estoy pasando el segundo slide, que lleva al posteo embebido.

Acá va la url del posteo a embeber:

https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/750202071768806/?type=1&theater

Este es el link para armar el código:

https://developers.facebook.com/docs/plugins/embedded-posts

Fijate que pide algo de una App. MK sabe como resolver eso

abrazo

**Comment by mkreyness** [comment]
El codigo de APP de Klaukol es el que ya esta puesto en todos los 
templates de Vendedores, Fede lo puede copiar de ahi.
Lo importante es que me avisen que estan agregando para que yo de de 
alta la actividad en la base de datos y le agregue el codigo que lo 
detecte, asi empiezan a sumar.

**Comment by LeandroBraier** [comment]
Fede, ya tengo el segundo slide, el que lleva al posteo embebido.

![slide-copa-america](https://cloud.githubusercontent.com/assets/6719872/8505341/84711006-21b9-11e5-835e-551eb6f0dd14.png)

Confirmame por favor cuando esté subido.

abrazo

**Comment by LeandroBraier** [comment]
Fede, apenas puedas sacalo al slide "Compartí este posteo".

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Hoy te voy a pasar unos slides nuevos para sumar. Me parece que si fueran un poco más anchos mejor no? Acá quedan distintos que en Torneo de Potenciados, porque el logo está a la izquierda.

**Comment by FAAREIA** [comment]
Ok dale. Probemos más ancho a ver si queda. Lo mejor para probar cosas asi es sacar un screenshot e incrustarle el png e ir probando como queda.

**Comment by LeandroBraier** [comment]
Hice eso y me parece que queda bien. Te paso el nuevo slide a agregar y el del Ganador Anterior modificado a tal fin.

![slide-premio-de-julio-vendedores](https://cloud.githubusercontent.com/assets/6719872/8547217/ba01b2ac-2493-11e5-81fc-ba90e3c40e68.png)

![slide-ganador-de-junio](https://cloud.githubusercontent.com/assets/6719872/8547213/b3686558-2493-11e5-893d-784c546d0c27.png)

Subilos nomás a producción y cualquiera cosa los corregimos. El slide del Premio de Julio que lleve a las bases y condiciones.

abrazo

**Comment by LeandroBraier** [comment]
Fede, van dos slides más para sumar a continuación de estos dos:

Este iría tercero con link al perfil del usuario:

![slide-3-vendedores-subi-la-foto-de-tu-corralon](https://cloud.githubusercontent.com/assets/6719872/8550324/4f8d937e-24a6-11e5-8eed-5d8b5db9a977.png)

Este iría cuarto con link al listado de contenidos de la Comunidad de Vendedores, donde se ven los videos de KIP, las Trivias, etc:

![slide-4-vendedores-tu-muro-tambien-suma-puntos](https://cloud.githubusercontent.com/assets/6719872/8550310/32f1922e-24a6-11e5-8ec2-85dbe9c54260.png)

Confirmame cuando esté subido porfa.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!!

abrazo

**Comment by LeandroBraier** [comment]
Gracias!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
