### ISSUE TITLE
Vendedores #8: Vinculación con Facebook

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#75]
@FAAREIA y @mkreyness necesito saber si mañana podemos hacer lo siguiente en la comunidad de Vendedores.

1) Embeber un posteo de Facebook para que la gente lo comparta (si no se puede embeber el posteo recurrimos a meter la image nomás y agregar botones de compartir abajo, que habría que medir en puntaje como todos los botones de compartir)

2) Poner un embed de la página de facebook de ParexKLaukol dentro de la Comunidad, como el de la home de Dánica?

3) Sumar puntos manualmente a los usuarios individual o de a varios juntos. Las chcias de Klaukol se van a fijar quien participó en el posteo y me van a decir a quién sumarle puntos por eso específicamente, de forma manual.

Espero respuesta de uds por estos 3 temas.

abrazo

**Comment by LeandroBraier** [comment]
Puntos 2 y 3 pueden no ser para mañana si no se puede.

**Comment by mkreyness** [comment]
1) si definen esos detalles antes de las 4, yo llego a esa hora a mi 
oficina y agrego lo de que sume puntos, etc. Creo que se puede.
2) me parece que es tema neto de Fede, porque es solo un embed.
3) entiendo que es mas que nada inyectar datos a la base, no es algo 
para programar, si tenes forma de pasarmelo en un excel (hasta ahora 
todo este tema de recibir exceles de ellos viene flojo), siempre despues 
de las 4, lo hago sin problema.

**Comment by LeandroBraier** [comment]
Gracias MK! Espero respuesta de @FAAREIA entonces. Tema 1 y tema 2 podríamos resolverlos hoy entonces. Tema 3 yo te puedo pasar un excel el lunes. Sería Nombre y Apellido del usuario y puntos que se le suman no? Algun dato más? Código de Usuario lo vamos a tener que machear con nombre y apellido me parece.

abrazo

**Comment by FAAREIA** [comment]
Buscando el activity feed de FB resulta que dejó de funcionar hace unos días:
https://developers.facebook.com/docs/plugins/activity
Habría que encontrar un reemplazo al menos para el sitio de dánica y parece que no hay nada ni similar para poner. =/

Para embeber un posteo necesito saber cual va a ser el que metamos en el sitio

**Comment by LeandroBraier** [comment]
1) Todavía no está publicado el posteo. Si me dejan poner el código a mi via CMS yo lo puedo subir cuando lo publiquemos, que va a ser después de las 16 hs seguramente, cuando Marce vuelva. Llegamos a eso? Si no llegamos cuando tengo el posteo les paso el código. Está explicado acá:

https://developers.facebook.com/docs/plugins/embedded-posts

2) Tema Activity Feed es cierto, Facebook lo bajó. URGENTE reemplacemos esto en los sitios de Dánica y Paty por este plugin.

https://developers.facebook.com/docs/plugins/page-plugin

Confirmame si lo ves posible.

En Vendedores propongo que siempre haya 1 posteo embebido para compartir, que sea distinto. Nosotros publicamos cada dos o tres días, si puedo ingresar el código por CMS lo voy actualizando yo. Cómo lo ven?

abrazo

**Comment by FAAREIA** [comment]
El pt2 ya esta resuelto.

**Comment by LeandroBraier** [comment]
Gracias Fede!

2) El punto 2 quedó hermoso ese en Dánica y Paty! Es mejor que el de antes. Creo que entonces sí lo podemos sumar a la Comunidad de Vendedores. Se puede sumar en columna derecha abajo de Actividad reciente?

1) El punto 1 lo sumaríamos como un contenido más de la Comunidad, como la foto de la trivia no? Claro que no como la foto sino como un embed del posteo.

Y abajo diría que suma 80 puntos por compartirlo, 100 puntos más por subir una foto del usuario viendo el partido y, si Argentina gana, multiplica los puntos por la cantidad de goles que haga.

**Comment by mkreyness** [comment]
Es que Nombre y apellido se REPITE !
Pueden exportar a excel la base de vendedores del sistema y agregar las columnas que quieran, sin perder la identidad (codigo de usuario)

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
perfecto entonces. Hacemos así.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-03 12:55 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA 

1) EMBED DEL POST 

Va embebido como un contenido más, como la Trivia de Seguridad, por ejemplo, que es un contenido pero tiene una foto fija.

URL del posteo a embeber:

https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/750202071768806/?type=1&theater

Este es el link para armar el código:

https://developers.facebook.com/docs/plugins/embedded-posts

Fijate que pide algo de una App. MK sabe como resolver eso

 mkreyness commented 3 hours ago
El codigo de APP de Klaukol es el que ya esta puesto en todos los
templates de Vendedores, Fede lo puede copiar de ahi.
Lo importante es que me avisen que estan agregando para que yo de de
alta la actividad en la base de datos y le agregue el codigo que lo
detecte, asi empiezan a sumar.

2) SLIDE A SUBIR:

Es este:

![slide-copa-america](https://cloud.githubusercontent.com/assets/6719872/8505855/5859182a-21cc-11e5-9f0b-e9ae49e1c2b7.png)

Que la imagen lleve a la url donde está embebido el post.

abrazo

**Comment by mkreyness** [comment]
```
Mirando en detalle veo que esto igual es mucho mas para mi que para
Fede !

1) Embedded post: 
esto implica agregar un nuevo tipo de tema en el CMS, para que lo
maneje correctamente, porque hasta ahora teniamos temas con 3
posibles actividades sobre la misma trivia (el original) y tema
"simple" que solo tiene una foto (lo de seguridad).
Esto seria un nuevo tipo "embedded post", tengo que ver que agregar
en el CMS, y como implementarlo.
No es trivial.
Tendria que tener entonces un share (como el de seguridad) y por ahi
es que gana los puntos, no ?

2) Slide:
Entiendo que eso es en la home de vendedores, tene en cuenta que eso
lo ve gente SIN ESTAR LOGGEADO, con lo cual no puedo llevarlo a una
"actividad" porque para eso tendria primero que loggearse.

Confirmame todo y arranco en un entorno de prueba.

El 03/07/2015 a las 21:42,
  LeandroBraier escribió:


  1) EMBED DEL POST 
  Va embebido como un contenido más, como la Trivia de Seguridad,
    por ejemplo, que es un contenido pero tiene una foto fija.
  URL del posteo a embeber:
  https://www.facebook.com/parexklaukolarg/photos/a.722794467842900.1073741830.692680497520964/750202071768806/?type=1&theater
  Este es el link para armar el código:
  https://developers.facebook.com/docs/plugins/embedded-posts
  Fijate que pide algo de una App. MK sabe como resolver eso
  mkreyness commented 3 hours ago
    El codigo de APP de Klaukol es el que ya esta puesto en todos
    los
    templates de Vendedores, Fede lo puede copiar de ahi.
    Lo importante es que me avisen que estan agregando para que yo
    de de
    alta la actividad en la base de datos y le agregue el codigo que
    lo
    detecte, asi empiezan a sumar.
  2) SLIDE A SUBIR:
  Es este:

  Que la imagen lleve a la url donde está embebido el post.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
MK: va la foto sola por si la necesitás:

![klaukol-copa-america-v1-b](https://cloud.githubusercontent.com/assets/6719872/8505936/f2e65f34-21d0-11e5-9567-2518f8bc7eb3.png)

**Comment by mkreyness** [comment]
```
Cuando quiero hacer share con esta imagen me dice que esta "mal
formateada".
Capaz no le gusta que sea png, voy a probar guardarla como jpg.

El 03/07/2015 a las 22:16,
  LeandroBraier escribió:


  MK: va la foto sola por si la necesitás:

  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
Sin incluir la imagen al sharear anda bien, creo que el problema es
que es demasiado grande.
Yo si la trato de achicar con el Paint de Windows se me pixeliza
feo, no podras generar vos con la Mac alguna version mas chica ?
El share funciona bien (paga los puntos), pero esta sin imagen.
Lo de que el slide lleve al juego loggeado anda bien tambien.

El 03/07/2015 a las 22:48, Marcelo
  Kreyness escribió:



  Cuando quiero hacer share con esta imagen me dice que esta "mal
  formateada".
  Capaz no le gusta que sea png, voy a probar guardarla como jpg.

  El 03/07/2015 a las 22:16,
    LeandroBraier escribió:


    MK: va la foto sola por si la necesitás:

    —
      Reply to this email directly or view

        it on GitHub.
```

**Comment by LeandroBraier** [comment]
@FAAREIA de acá nos quedó pendiente subir el embed de Facebook a la comunidad. A qué hora lo podrás subir Fede?

**Comment by FAAREIA** [comment]
Me dice que la URL no es válida -_-
Ni http://www.parexklaukol.com.ar/vendedores/
Ni http://www.parexklaukol.com.ar/cgi-bin/mainvendedores.pl

Qué podrá ser @mkreyness ?

**Comment by mkreyness** [comment]
Ataque D.O.S. a duplika. A ratos anda.
Lo estamos sufriendo hace 1 semana

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Hoy le avisé a la mañana a Duplika de esto. Dicen que están migrando cosas
a un no se qué más seguro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ni se como hizo para salir desde esa cuenta @teraxis de mi telefono, ni 
la tengo instalada. Cosa'e mandinga.

**Comment by LeandroBraier** [comment]
@FAAREIA necesitamos tener el embed subido a la Comundidad. A qué hora lo podés tener en producción? Avisame porfa.

@mkreyness consulta técnica: podemos detectar si hacen "me gusta" a la página desde ese embed y sumarles puntos por eso?

En caso contrario: podemos saber de alguna manera si son fans de la página o no y sumarlos puntos por eso?

abrazo

**Comment by mkreyness** [comment]
No creo que pueda tener feedback de algo embedded.
En todo caso cuando este puesto, pruebo y te digo.

Cualquier accion inversa (ver desde la pagina la lista de fans) NO 
SABRIAMOS como relacionarlos con nuestros users, ya que no le pedimos a 
la gente que nos diga su usuario de facebook.

Inclusive si son todos compañeros de trabajo y comparten la misma 
maquina, menos que menos podemos saber si el usuario loggeado en 
facebook y el usuario loggeado en el sistema coinciden, alguien puede 
estar dando un like en nombre de otro.

Lo unico que se puede saber es cuando hacen like desde un BOTON NUESTRO, 
y ahi sumarle puntos, cosa que ya estamos haciendo.

**Comment by FAAREIA** [comment]
Aún me tira:
"Error: No es una URL válida de Facebook."

**Comment by LeandroBraier** [comment]
En donde te tira eso? En el embed?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
https://developers.facebook.com/docs/plugins/page-plugin

**Comment by LeandroBraier** [comment]
No entiendo en qué te puedo ayudar Fede. Decime y te doy una mano. O es
para MK esto?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho, le estaba metiendo una URL equivocada.

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo

**Comment by LeandroBraier** [comment]
Quedó muy bien la verdad.
