### ISSUE TITLE
Acción Lanzamiento Club de Colocadores

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#76]
MK, te cuento una acción que vamos a hacer para el lanzamiento del Club de Colocadores. Decime si lo ves difícil y un aprox de horas que te llevaría.

El día 20 de julio de 2015 realizaremos una campaña especial en la cual los vendedores podrán interactuar con los colocadores.

Los colocadores obtendrán 100 puntos por cada pack de producto Klaukol que adquieran, pero con esta acción, además, podrán decir en su plataforma qué vendedor les vendió los packs y duplicar los puntos.

Los vendedores, a su vez, recibirán puntos en su propia plataforma cada vez que un colocador los nombre como su vendedor.

Lo ves posible? Caro?

Entiendo que el Colocador tendría que tener en su plataforma un espacio para decir cuántas bolsas compró y en qué corralón. Una vez seleccionado el corralón, le aparecería la lista de vendedores de ese corralón y tendría que elegir.

Espero tu feedback mañana tranqui.

abrazo

**Comment by mkreyness** [comment]
pero la plataforma para colocadores (real) todavia ni existe, no 
deberiamos primero hablar de eso ?
Y tene en cuenta que no tenemos REALMENTE interrelacionados los 
vendedores con la guia de corralones, por lo tanto el popup de 
corralones si lo saco de la guia, no concuerda con lo que hay en la base 
de vendedores, y si tomo lo de la base de vendedores no solamente no 
coincide, sino que puede estar mal cargado, mal escrito, etc.
O sea, nada de esto es TECNICAMENTE dificil, pero me parece que ha que 
empezar por emprolijar la base de datos.

**Comment by LeandroBraier** [comment]
Si es ese el tema lo gestionamos (o a lo sumo la culpa la tiene otro, no
hay problema).

Gracias MK!

Era solo porque es algo que se había hablado con el cliente y el cliente se
olvidó y queríamos saber la complejidad para decidir si recordarselo o
dejarlo pasar.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-03 0:51 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Perfecto MK. El cliente dio el OK para avanzar. Braulio está diseñando el Club de COlocadores. La semana que viene lo encaramos a esto. La idea sería tener una primera versión del Club de Colocadores con esta funcionalidad que lo vincula a la Comunidad de Vendedores para el viernes 10. 

Lo ves posible?

A Fede le pregunto aparte cuando cerremos tema de Comunidad de hoy.

**Comment by mkreyness** [comment]
O sea que la lista de corralones que tendria que elegir el colocador saldria de lo que esta en la de vendedores, y no en la guia ? Podemos filtrar aunque sea por provincia/localidad ? Porque si no el desplegable de corralones es gigante.
Los colocadores tambien provendrian de una base de datos a cargar, con un user/pass para login, etc ? O se pueden dar de alta ellos mismos ?

**Comment by LeandroBraier** [comment]
MK: no hay problema con filtrar también por localidad. Me parece bien.

Respecto de la inscripción, se podrían anotar ellos mismos. La existencia del club se las comunicarían los mismos vendedores al venderles los productos, por lo cual es un buen momento para hacer una de dos:

1) hacerles llenar un cupon de preinscripcion como en la Comunidad de Vendedores.

2) invitarlos a inscribirse por si mismo

Yo me inclinaría mas por la 1), ya que los colocadores van a ser todavia mas básicos digitalmente que los vendedores.

Abrazo

**Comment by mkreyness** [comment]
Mejor si es la 1), pero hay que asignarles codigo de usuario (y password) a c/u, sin que se repitan.
Otra duda: lo de la cantidad de bolsas que compran del producto, tienen que poder elegir producto de un desplegable ? En tal caso, van todos los productos o un subconjunto ? Hay un factor de ponderacion variable por producto (como en el caso de los torneos) de cuantos puntos le suma al vendedor ?

**Comment by mkreyness** [comment]
Igual si tenes algun diseño que le pasaste a Braulio para maquetar, mandame aunque sea un JPG asi me voy haciendo una idea de lo que voy a recibir. Ya estuve creando estructuras en la base de datos y el CMS, para el 10 seguramente llegamos bien (si no aparece nada raro en el medio) pero todo lo que vaya conociendo de antemano, mejor.

**Comment by LeandroBraier** [comment]
Tengo algo, pero Braulio lo está trabajando aun. Hoy le pido nueva versión y te la paso.

Gracias MK.

**Comment by LeandroBraier** [comment]
Marce, te paso cómo sería el perfil que necesito que tenga el Club de Colocadores.

![mock-up-club-de-colocadores-julio-2015--carga-tus-compra](https://cloud.githubusercontent.com/assets/6719872/8535139/514e52ee-2419-11e5-9830-19e5ba6399ae.jpg)

Cualquier duda avisame. Es solo una maquetación. En cuanto a diseño seguro que lo ponés bien. El casco, la llana, la bota, etc son representaciones de los posibles objetos por los cuales los colocadores van a poder cambiar los puntos. 

El Club de Colocadores va a funcionar normalmente como un programa de puntos por canje. Además del canje, cada tanto va a haber un sorteo en el cual todos los usuarios participan con 1 solo número en igualdad de condiciones.

Acá te paso también cómo debería quedar la home:

![mock-up-club-de-colocadores-julio-2015-home](https://cloud.githubusercontent.com/assets/6719872/8535164/944cc238-2419-11e5-8017-8e8d4834453a.jpg)

**Comment by mkreyness** [comment]
```
Si quiere cargar 2 compras tiene que entrar 2 veces al perfil ? No
va FECHA ? No tiene como consultar lo que ya cargó ?
Me parece confuso mezclar el "perfil" (algo fijo) con las compras
(algo repetitivo a lo largo del tiempo) todo en un mismo plano.

Y yo cambiaria el orden: en este caso si primero provincia, despues
desplegable de localidades de la provincia, despues desplegable de
corralones de esa localidad, y despues desplegable de vendedores de
ese corralon, para que vaya filtrando.
Obviamente si deja localidad en blanco igual le traigo todos los
corralones de la provincia, pero le va a costar mas encontrarlo.
Sigo sin entender bien que pasa con el PRODUCTO, si es cualquier
producto ParexKlaukol de los que aparecen en el sitio, o son solo
esos 3 promocionados ?



El 06/07/2015 a las 20:01,
  LeandroBraier escribió:


  Marce, te paso cómo sería el perfil que necesito que tenga el
    Club de Colocadores.

  Cualquier duda avisame. Es solo una maquetación. En cuanto a
    diseño seguro que lo ponés bien. El casco, la llana, la bota,
    etc son representaciones de los posibles objetos por los cuales
    los colocadores van a poder cambiar los puntos. 
  El Club de Colocadores va a funcionar normalmente como un
    programa de puntos por canje. Además del canje, cada tanto va a
    haber un sorteo en el cual todos los usuarios participan con 1
    solo número en igualdad de condiciones.
  Acá te paso también cómo debería quedar la home:

  Fijate que el logo es distinto. No tiene el círculo azul ni las
    manos agarradas. Es más simple.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
1) Ok, hagamos separado el perfil y el espacio de carga de compras

2) No hay problema con el cambio de orden. Me parece bien.

3) Me parece que después de cargar, la página se refresca y puede cargar
otro producto. No veo problema ahí. La lista desplegable de productos
tendría todos los productos de Argentina, sí.

4) Creo que además de los puntos deberíamos hacerle un chart como el del
Torneo de Potenciados diciendo cuánto compró de cada cosa y con fecha, no?

Hagamos eso entonces.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-06 21:15 GMT-03:00 mkreyness notifications@github.com:
