### ISSUE TITLE
Menú y Resultados Landings Offline Klaukol

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#8]
Fede, necesito dos páginas más para los juegos de Klaukol. 

Una llamada Menú (puede ir en el Index) que diga como título "Presentación Klaukol Impermeable Potenciado" y abajo dos botones: Desafío 1 y Desafío 2, que lleven a las otras dos páginas.

La segunda es llamada "Resultados" y simplemente es así. Título: Resultados. Y al lado de un círculo de cada uno de los 5 colores aparece la suma de los tiempos de los dos desafíos anteriores para cada equipo. Ya le pedí a Marce que arme la parte funcional y te voy a pasar a vos después para que lo maquetes, pero te voy avisando para que avancemos porque para el lunes al mediodía deberíamos resolverlo.

abrazo

**Comment by FAAREIA** [comment]
Ok con las páginas, el tema es que el sitio de parex estan bastante mal armado y fijate que no hay un menú como siempre, sino que son botones distribuidos a lo largo de las páginas. Lo máximo que se puede hacer es poner un botón en el index de alguna forma que quede bien. Igualmente para eso también necesitamos el FTP asi subimos el index con ese agregado.

**Comment by mkreyness** [comment]
```
Me parece que estas mezclando temas, esto es para el juego.

El 09/03/2015 a las 8:44, Federico
  Arena escribió:


  Ok con las páginas, el tema es que el sitio de parex estan
    bastante mal armado y fijate que no hay un menú como siempre,
    sino que son botones distribuidos a lo largo de las páginas. Lo
    máximo que se puede hacer es poner un botón en el index de
    alguna forma que quede bien. Igualmente para eso también
    necesitamos el FTP asi subimos el index con ese agregado.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
Es esto, Fede:

Menu:
Tiene que estar todo como ya lo hice en menu.html, en una unica
pagina de menu, porque es la unica forma en que puedo sumar los
resultados. Un link es para desafio 1, otros 5 links son para
desafio 2 por cada equipo, y uno final que va a resultados.
Resultados:
Fijate resultados.html, faltaria ponerle los div con circulos de
colores, el contenido ya se genera bien.

El 07/03/2015 a las 13:52,
  LeandroBraier escribió:


  Fede, necesito dos páginas más para los juegos de Klaukol. 
  Una llamada Menú (puede ir en el Index) que diga como título
    "Presentación Klaukol Impermeable Potenciado" y abajo dos
    botones: Desafío 1 y Desafío 2, que lleven a las otras dos
    páginas.
  La segunda es llamada "Resultados" y simplemente es así.
    Título: Resultados. Y al lado de un círculo de cada uno de los 5
    colores aparece la suma de los tiempos de los dos desafíos
    anteriores para cada equipo. Ya le pedí a Marce que arme la
    parte funcional y te voy a pasar a vos después para que lo
    maquetes, pero te voy avisando para que avancemos porque para el
    lunes al mediodía deberíamos resolverlo.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ok perfecto, estilizo eso que esta ahora entonces.

**Comment by LeandroBraier** [comment]
Dale. Porfa inclui los cambios que yo te habia pedido antes: las bandas y logos de Klaukol y cambiar el botón fuxia por uno blanco con lineas negras.

Abrazo

**Comment by FAAREIA** [comment]
Denle F5 que subi la actualización.

Cualquier cosa diganme

**Comment by LeandroBraier** [comment]
Fede o Marce: necesitaría que me mandaran el zip con el contenido de todo el sitio como hiciste el otro día pero con la versión actual, la actualizada.

Gracias!

**Comment by mkreyness** [comment]
Va. Chequea que todo te funcione plis.

**Comment by LeandroBraier** [comment]
Dale. No me llegó por acá, enviamelo aparte a mi mail porfa.

abrazo

**Comment by mkreyness** [comment]
uh, que porqueria esto de github.

**Comment by LeandroBraier** [comment]
Gracias Marce!
