### ISSUE TITLE
Vendedores #9: Tabla de posiciones atrasada

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#81]
@FAAREIA y @mkreyness : Hay usuarios con 500 puntos pero en el ranking sigue figurando los que tiene 330 como máximo. Por favor corrijamos esto hoy porque los usuarios se están quejando. Por ejemplo, FabianLopez, que tiene más de 500.

<img width="343" alt="captura de pantalla 2015-07-04 a la s 10 17 15" src="https://cloud.githubusercontent.com/assets/6719872/8508035/f2daa922-2235-11e5-91b7-c4ed1eb49ccf.png">

**Comment by mkreyness** [comment]
Pero los puntos se resetearon el 1/7, habiamos quedado q funcionaba asi. 

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Tal cual. Los 500 puntos los tiene de Julio este Fabian Lopez.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-04 10:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Vos donde ves eso ?
Yo solo le veo 100 puntos en julio.

**Comment by LeandroBraier** [comment]
Tenés razón. Tiene 1 solo. El resto son de Junio.

abrazo
