### ISSUE TITLE
Como sumar puntos manualmente a los usuarios paso a paso

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#82]
Me explicás Marce cómo hacer? Porque estoy seguro que los usuarios se van a quejar y voy a tener que hacerlo ahora el finde.

**Comment by mkreyness** [comment]
El problema es que esos puntos hay que atribuirselos a ALGUNA actividad, 
en este momento no hay prevista una interface para hacerlo, pero te 
habilito un abm donde puedas elegir vendedor, ingresar fecha, elegir 
actividad y los puntos que quieras y darselos.

**Comment by mkreyness** [comment]
Ahi te agregue una solapa de actividades por vendedor, donde podes editarle, agregarle, o borrarle actividades. Cada actividad tiene un puntaje que, si no esta canjeado, permite que cuando junte 100 se le asigne un nuevo ticket. Ojo que esto NO va a disparar automaticamente esos nuevos tickets (por ej, le agregas 1000 puntos a un tipo, que deberian darle 10 tickets), le aparecerian recien cuando haga la proxima actividad "real".
Si queres te agrego un editor de tickets.

**Comment by LeandroBraier** [comment]
Gracias Marce!

Entro a editar las actividades pero falta un botón de guardar, no?

**Comment by mkreyness** [comment]
Como esta dentro de un frame capaz tenes que escrolarlo un poco o 
agrandar el frame (es estirable) para ver los botones.

Si agregas actividad, salen los botones "Cancelar" y "Guardar Nuevo".
Si editas una preexistente, tiene botones "Cancelar/Eliminar/Guardar 
Cambios".

**Comment by LeandroBraier** [comment]
Yo encuentro donde "agregar" actividad. SOlo tengo "Consulta de Actividades"

Cuando consulto una intento cambiarle el puntaje al menos pero no te botón de guardar. Van capturas:

![captura de pantalla 2015-07-04 a la s 14 16 58](https://cloud.githubusercontent.com/assets/6719872/8508802/f5a5db2a-2255-11e5-93c3-487a88201302.png)

![captura de pantalla 2015-07-04 a la s 14 18 01](https://cloud.githubusercontent.com/assets/6719872/8508803/f88b494c-2255-11e5-9587-08467ab13380.png)

**Comment by mkreyness** [comment]
Es que no es ahi, esa es la consulta de siempre.
La lista de actividades EDITABLE cuelga de cada vendedor.
Vas al vendedor que queres y tenes una SOLAPA nueva con su actividad, 
donde podes editarla.

**Comment by LeandroBraier** [comment]
Perfecto!! Ahora si!

No lo encontraba. Gracias!
