### ISSUE TITLE
Vendedores #10: Pequeña modificación en Bases y Condiciones

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#83]
Fede, en la sección "Premio Mensual por sorteo" donde dice:

En el mes de junio entregaremos 1 (un) viaje a la ciudad de Mendoza para 2 (dos) personas saliendo desde la Ciudad Autónoma de Buenos Aires.
El paquete incluye
A) Pasaje aéreo Bue Mendoza Bue volando por Aerolineas Argentinas en clase R.
B) Traslados Aeropuerto-Hotel-Aeropuerto.
C) 3 noches de alojamiento con desayuno en el hotel NH Cordillera en base doble.
Si por alguna cuestion la persona que resulte ganadora no puede tomar el viaje a Mendoza podrá canjearlo por un viaje de igual valor de hasta $8.000 + IVA. en la agencia Neptuno Viajes - Tel. 5254-8951 - vanesa@neptuno.com.ar.

Debería decir:

En el mes de julio entregaremos 1 (una) consola PlayStation®4 de la empresa Sony® con las especificaciones detalladas en la siguiente dirección web oficial de la marca: https://www.playstation.com/en-us/explore/ps4/techspecs/

Confirmame cuando lo podrías tener corregido.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

Puede ser que no vea el ícono de Marca Registrada ®? Me aparece como letra desconocido en la web. El resto perfecto.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo solucioné ;)

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
