### ISSUE TITLE
Vendedores #11: Bug en Carga de Actividades

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#84]
@mkreyness me mandé una.

En el usuario de código "MaximilianoBustos" cargué una actividad de 80 puntos sin fecha y ahora no la puedo borrar. Necesitaría que:
1. Que la borres lo antes posible.
2. Que hagas que se asigne una fecha automáticamente a la actividad, para evitar que vuelve a ocurrir esto. Tengamoslo en cuenta en otras partes del CMS porque esta cuestión de usabilidad ya me pasó alguna vez en alguna otra parte del cms.

abrazo

**Comment by mkreyness** [comment]
Listo, la borre y le puse que por default tenga la fecha del dia.
En realidad la mala suerte es que esa sea la primer columna del listado, 
por eso no podes volverlo a acceder.

**Comment by LeandroBraier** [comment]
Gracias MK!

abrazo
