### ISSUE TITLE
Torneo de Potenciados #4: Modificación en Bases y Condiciones. DEADLINE: 07/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#86]
@FAAREIA te paso por mail las bases y condiciones del Torneo corregidas. Si lo tenés corregido para mañana estamos OK. Son terminologías que cambiaron y algunas frases incluso, por eso te las paso todas completas de nuevo.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

Solo queda un detalle. Donde dice: CATEGORÍAS DE CORRALONES debería decir CATEGORÍAS DE DISTRIBUIDORES.

El resto joya. Gracias!

**Comment by FAAREIA** [comment]
Hecho
