### ISSUE TITLE
Vendedores #13: El bug de los puntos continua

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#87]
Marce, por favor revisá una vez más que los puntos se hayan reseteado bien en julio. Mirá esta captura:

<img width="390" alt="captura de pantalla 2015-07-06 a la s 19 05 29" src="https://cloud.githubusercontent.com/assets/6719872/8534204/8c6a0e76-2410-11e5-88f4-32bc829c1e1a.png">

Hay 200 puntos y 1 solo ticket. Esto nos puede generar un lio tremendo y puede explicar el reclamo de Fabian Lopez del viernes. Por favor chequeá que esté todo bien reseteado en cuanto a puntos y tickets y todo lo que haya sea solo de Julio.

abrazo

**Comment by mkreyness** [comment]
Debe estar funcionando distinto en distintos lugares, por eso yo te preguntaba donde lo veias.
Los 205 puntos estos si son sumando junio. Ahora veo donde es eso de "mis logros" y lo ajusto.

**Comment by mkreyness** [comment]
Ahi lo arregle. El problema es que el reset es a efectos de que no arrastre saldo para fichas, pero no los puedo ELIMINAR, porque es lo que me marca que el juego ya esta jugado.
Ahi hice unos cambios a mano y en el proximo fin de mes va a ser automatico. Lo que si entonces DURANTE el dia del sorteo, como ya te dije antes (y no sucedio justamente porque todo seguia visible) ahora si que NO se van a ver los tickets, el "reseteo" VALE desde las 0hs del dia de sorteo.

**Comment by LeandroBraier** [comment]
Perfecto, no hay problema por eso. Gracias!

abrazo
