### ISSUE TITLE
"Olvidé mi contraseña" en Comunidad de Vendedores y Torneo de Potenciados. DEADLINE: 10/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#88]
@mkreyness necesito que, sin apuro, sumemos el sistema de "olvidé mi contraseña" en Comunidad de Vendedores y Torneo de Potenciados.

Mi idea es que resetee la contraseña a la clave original que nosotros le dimos al usuario y automáticamente le envíe un mail igual al mailing de bienvenida con título diferente: "Hemos reestablecido tu contraseña original en la Comunidad de Vendedores ParexKlaukol" (o Torneo de Potenciados Klaukol, lo que corresponda).

abrazo

**Comment by mkreyness** [comment]
No tengo guardada la contraseña original, si la cambió, la cambió.
Lo que puedo hacer es generarle una nueva al azar y que la vuelva a 
cambiar por lo que quiera.

**Comment by LeandroBraier** [comment]
Entonces se le podría mandar un mail directamente con la contraseña actual.
Eso sí, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-07 13:02 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Mas vale, pero tienen que poner la direccion de mail con que esten 
registrados, y muchos NO tienen mail porque son direcciones compartidas.
Inclusive debe haber duplicados.
Habria que pedirles usuario + email, y en el caso de que tengamos al 
usuario pero el email en la base este en blanco, mandarsela a la que 
este poniendo y confiar ?

**Comment by LeandroBraier** [comment]
Exacto. Me parece bien eso. Igual si no tienen mail se joden, llaman al
0800 y ahí les dicen su contraseña por telefono. La proxima se van a
acordar.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-07 13:09 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok, le pasas a Fede/Braulio para maquetar como seria el input de esos 
datos ?
Usuario ya ingresó, pero en el mismo login si le ponen un link de 
"olvide mi contraseña" deberia desplegarse un cuadrito mas para ingresar 
el email.

**Comment by LeandroBraier** [comment]
Ok, MK.

@FAAREIA necesito sumar al Login de Comunidad de Vendedores y Torneo de Potenciados un link de "Olvidé mi contraseña" que despliegue un cuadrito que diga: "Escribí tu dirección de email" y debajo un botón de "Enviar contraseña"

Gracias!

**Comment by mkreyness** [comment]
Y tambien tendriamos que tener alguna forma de mostrarle en la misma ventana de login que la contraseña fue enviada.  Deberia ser un div (normalmente oculto) en el mismo template con una "x" para cerrarlo, y yo lo activo como siempre con un result=algo

**Comment by FAAREIA** [comment]
Ahi esta subido en vendedores. @mkreyness habría que el action al form nomás.

**Comment by mkreyness** [comment]
ok a la tarde lo chequeo/termino.

**Comment by FAAREIA** [comment]
En torneos ya esta también.
Para mostrar el mensaje hay que agregar un ?contacto=1 solamente.

**Comment by mkreyness** [comment]
cual es el login de torneos ?

**Comment by FAAREIA** [comment]
www.parexklaukol.com.ar/torneo-corralones/login-c.html
www.parexklaukol.com.ar/torneo-corralones/login-r.html

**Comment by mkreyness** [comment]
1) Van realmente dos login separados ? No habiamos dicho que era un unico login y que yo detectaba si era corralon o corredor segun el propio codigo de usuario ?
2) Tendria que haber un contacto=2 para mostrar un cartel de error diciendo que ese email no corresponde al usuario.
3) Si tocas lo de 2) de paso cambiale el texto al contacto=1 que diga que se le mandó la contraseña, quedamos que NO se le genere una nueva.

**Comment by FAAREIA** [comment]
No recuerdo realmente, el HTML no se cual es entonces....
El contacto=2 no debería de existir ya que son sitios para IE9+, los campos ya son obligatorios.
Avisame cuando esté y le cambio el texto.

**Comment by mkreyness** [comment]
no es un problema de obligatoriedad, el tema es que si el tipo me pone una direccion de mail que NO concuerda con su usuario (o con ningun usuario) no puedo mandarle nada.

**Comment by FAAREIA** [comment]
Claro tenes razon, ahi lo agrego y cambio del texto

**Comment by FAAREIA** [comment]
Hecho, fijate ahora.

**Comment by mkreyness** [comment]
Ok, igual lo voy a tocar un poco porque venimos tuteando al tipo y ante el error lo tratas "de usted". Parece que con el error se enfrio la relacion ;)
No toques nada que voy a intervenirlos yo con cosas.

**Comment by mkreyness** [comment]
Lean ahi lo hice andar para el login de vendedores, todavia no esta en produccion, podes verlo con este nombre:

http://www.parexklaukol.com.ar/vendedores/login2.html

El problema es que el mailing de bienvenida habla del viaje a Mendoza, no podemos mandar eso, habria que actualizar primero el contenido de ese mailing, no ?

Y en el caso de los torneos, ni siquiera se que mailing mandarle.

**Comment by LeandroBraier** [comment]
Quedó muy bien chicos! Ahora le pido a Fede eso aparte, MK, y te aviso.

Respecto de Torneos subamos la opción ya en producción y cuando tengamos el
mailing armado lo vinculamos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-08 17:09 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero resolvamos este tema pendiente de torneos: es UN login unico o va a haber dos tipos como armo Fede ? Ni se desde donde se va a acceder ese login.

**Comment by LeandroBraier** [comment]
Yo les había dicho que ibamos con un solo login, que es el que se ve el
corralón de fondo blureado. Ese solo es el que necesitamos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-08 17:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok entonces seria el que puso como login-c.html
Lo renombro a login.html a secas y le voy metiendo la logica esta del "olvidé", pero falta el contenido del mail en si.

**Comment by LeandroBraier** [comment]
@mkreyness ya está listo el mail para el "olvidé la contraseña"

Activalo ya para Comunidad de Vendedores. La versión para Torneo de Potenciados la hacemos más adelante.

http://parexklaukol.com.ar/_mailing/vendedores-recordar/vendedores-recordar.html

Avisame cuando esté cargado porfa.

abrazo

**Comment by mkreyness** [comment]
Ahi lo puse en produccion para no demorarlo, pero:
- El alternate text de la imagen seguia hablando del viaje a mendoza, se 
  lo saque.
- esta mal el texto de una de las imagenes, "Capáz" no lleva acento.
  Ojo que el archivo 
  "http://parexklaukol.com.ar/_mailing/vendedores-recordar/vendedores-recordar.html" 
  ya esta modificado, supongo que corregir solo la imagen NO implicaria 
  pisar el html.

**Comment by LeandroBraier** [comment]
Ya lo pedí Marce! Avisando que no pisen el html. Asi que esto ya queda en producción.

Gracias!

abrazo
