### ISSUE TITLE
Cambio de tamaño Slides a 700px

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#89]
Fede, no me termina de cerrar como queda ese tamaño en el slideshow. Las proporciones si pero el tamaño no. Te paso los 4 en 700 px de ancho a ver si queda mejor. Vos decime cuando estén arriba.

![slide-1-premio-de-julio-vendedores-700](https://cloud.githubusercontent.com/assets/6719872/8571128/3abb591c-255b-11e5-8bc5-2e64ccf2bcff.png)
![slide-2-ganador-de-junio-700](https://cloud.githubusercontent.com/assets/6719872/8571130/3c62b486-255b-11e5-9bd6-5e2c89123494.png)
![slide-3-vendedores-subi-la-foto-de-tu-corralon](https://cloud.githubusercontent.com/assets/6719872/8571133/3efb8c22-255b-11e5-8133-d8032c2b0382.png)
![slide-4-vendedores-tu-muro-tambien-suma-puntos-700](https://cloud.githubusercontent.com/assets/6719872/8571136/41b6490c-255b-11e5-9429-6dd57dd2c6e7.png)

abrazo

**Comment by FAAREIA** [comment]
Hecho, dale F5

**Comment by LeandroBraier** [comment]
Gracias Fede! Lo veo mucho mejor. Cualquier cambio lo iremos viendo.

abrazo
