### ISSUE TITLE
Estructura sitio Revear

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#9]
Fede, probablemente tengamos que también retomar y hacer responsive este sitio:

http://www.revear.com.ar/

Te lo paso para que lo vayas chequeando. Por lo visto no es muy diferente de los otros, aunque los contenidos son distintos.

abrazo

**Comment by LeandroBraier** [comment]
Fede, necesito que vayas bajandote toda la info de este sitio por lo pronto, antes que ellos lo migren todo a nuestro servidor, por las dudas. Confirmame porfa apenas lo tengas backupeado.

abrazo

**Comment by FAAREIA** [comment]
Es lo mismo que te respondi en el otro post. Este sitio también nos los mandaron ya backupeado, aunque la base de datos no la tenemos en ninguno de los casos

**Comment by LeandroBraier** [comment]
Qué base de datos sería?

Así la pido urgente.

**Comment by FAAREIA** [comment]
Todos los sitios que tienen ellos funcionan con programación, no hay ningun HTML estático, por lo que toda la data viene de las bases de datos y un CMS

**Comment by LeandroBraier** [comment]
Entocnes cuando lo suban todo a nuestro hosting lo vamos a tener, verdad?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Claro, asi es. De hecho si lo suben mal se va a romper el sitio por lo que si o si van a tener que dejar la posta subida

**Comment by LeandroBraier** [comment]
Fede, necesito que avancemos a armar este sitio. Cuando lo remaquetes, necesito que con los mismos elementos modifiques de una manera la hoja de estilos para que a simple vista la página se vea distinta, renovada. Es una cuestión de maquillaje nomás, pero si cambias las tipografías, algo en la distribución, menúes, etc.

Vayamos avanzando con eso

**Comment by FAAREIA** [comment]
Si es una optimización visual, no hace falta remaquetarlo sino reestilizarlo. Lo ideal sería poder montarme el sitio localmente para hacer los cambios y listo. Habría que preguntar si se puede montar localmente, capas que la configuración del server es complicada.

**Comment by FAAREIA** [comment]
O sino que nos den acceso FTP asi vamos probando y viendo. Son sitios de muchos archivos.

**Comment by LeandroBraier** [comment]
Entiendo, sí, es reestilizarlo, pero que se vea claramente diferente. 

Entiendo también que para todo esto tenemos que esperar que nos den acceso FTP. Yo ya avisé a la marca que después del acceso FTP necesitamos 10 días más para terminar de armar los sitios, ellos lo saben. Pero te aviso esto para que vayas avanzando en lo que puedas ir avanzando.
