### ISSUE TITLE
Limitar a 99 puntos usuario HiltonLobruno

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#90]
MK, necesito que hoy aunque sea a última hora limites a 99 puntos a este usuario. Solo eso.

abrazo

**Comment by mkreyness** [comment]
Lo podes hacer directamente desde el CMS, simplemente hay que cambiarle 
el estado al vendedor de ACTIVO pasarlo a SUSPENDIDO.
Sigue funcionando, pero no pasa de los 99.

**Comment by LeandroBraier** [comment]
Gracias MK!

Me lo imaginaba jeje

abrazo
