### ISSUE TITLE
Torneo de Potenciados #4: Bug de barras y velocimetros 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#91]
@FAAREIA y @mkreyness algo no anda bien. MK ya cargó todos los datos y me parece que las barras lo tomaron bien, pero los velocímetros no.

1) El velocímetro aparece solo en la barra del participante, cuando debería aparecer en todas las barras.

2) La barra del participante, que se pone amarilla, aparece fuera de lugar, más arriba que las demás. Debería estar igual solo que amarilla.

3) La agujita no representa el porcentaje del promedio mensual y el dato que aparece ahí tampoco es correcto.

Mañana necesitaríamos tenerlo corregido para el mediodía porfa.

abrazo

**Comment by mkreyness** [comment]
Los numeros en general son MUY chicos comparados con los objetivos, aun 
estando estos divididos por 6.
Vos con cual participante estas mirando asi veo lo mismo ?

**Comment by mkreyness** [comment]
Otra cosa: hay 577 corralones (sobre 1858) tienen puesto usuario y password.
El que mas compras tiene, casualmente no.
De hecho hay 354 corralones que tienen objetivo y compras, pero no 
tienen usuario y password.
Es decir, solo 211 de los 565 corralones con objetivo y compras tienen 
usuario y password.

Algo esta mal en esto de los datos que mandaron.

**Comment by mkreyness** [comment]
La flecha de la velocidad habia quedado fija, ya que recien ayer con el perfil entendi como se usaba.
Ahora ajusto eso y agrego velocidades en los demas (realmente en el template solo esta en el propio).
Una vez ajustado eso vemos como queda lo de la altura rara de la amarilla.
Estoy viendo con el que esta numero 1 de los que tienen codigo y password:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=distabile&clave=127844&torneo=1&tipo=C

**Comment by mkreyness** [comment]
Listo, por lo menos con este caso se ven las cosas bien (la razon por la que quedaba mas alto era que no salia la palabra "puesto", el problema en la barra blanca con fondo amarillo es que el texto "100%" no se ve, porque es blanco sobre blanco.
Igual el caso del 1er puesto es diferente a los demas posibles puestos porque no dice que le falta x% para subir uno, con lo cual ahora voy a buscar quien es el segundo que tenga user/pass y veo que tal sale.

**Comment by mkreyness** [comment]
Je, habia varias cosas mal, el % estaba fijo en 20% en vez de tomarlo del programa (esto debe haber sido consecuencia del cambio de modelo por puntos a por porcentaje).

Vean que pasa ahora con este, que es el 3ro:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1&tipo=C

El texto de lo que le falta para pasar de puesto es mas alto que el del solo texto "PUESTO", ni que hablar si le dejara el texto "PUESTO", seria mucho peor.

Esto te lo tengo que dejar a vos Fede. Siempre hablando del template con-slideT-C.html, al que ya le hice varios cambios.

Otra cosa que no estoy seguro de que este bien: el porcentaje se muestra respecto de TODO el torneo (y es por lo que se ordena la tabla) mientras que el velocimetro es por lo del mes en curso (o sea, de 1/6 del objetivo) por eso el mejor esta en velocidad -76% y tiene 3.90% del objetivo total (no se pueden sumar esos dos numeros pretendiendo que den 100).
Esto es porque compro 1216 bolsas sobre un objetivo total de 31218: cumplio un 3.90% del semestre y 23.4% del mes, o sea que esta en un -76.6% (=> trunca a 76%) abajo de lo que deberia.
Siendo que no paso ni 1/3 del mes, es bastante injusto decirle que esta TAN abajo, pero bueno, ellos sabran.

**Comment by LeandroBraier** [comment]
Buen día Marce!

Tema 1) Quitale la frase "un puesto" que diga simplemente" +x% para subir" y listo.

Tema 2) Dejemoslo así, que está bien.

Aparte, decías algo de corralones sin usuario y clave. Si me das el OK me bajo el excel de corralones y te paso usuario y clave para los que no lo tienen aún.

abrazo

**Comment by mkreyness** [comment]
1) listo, ver aca: 
http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1&tipo=C
2)  no se cual es el 2).
Yo lo que sigo viendo es que si el tipo esta en el ranking no puede ver su propio porcentaje.

Si, pasame usuario/clave para todos los que no tengan. Ojo el corralon numero 1 (que le puse test/test porque fue el que use para probar) "tiene", pero hay que cambiarselo.

**Comment by LeandroBraier** [comment]
2) Es lo que decías de que el ranking sea por el porcentaje semestral y no por el mensual. Dejemoslo como está.

Respecto de que el usuario no vea su propio porcentaje es algo que tenemos que corregir, tal cual. Por favor avisenme para qué hora estaría eso.

**Comment by mkreyness** [comment]
Es un tema de colores, lo tiene que resolver Fede, seguramente es algo simple.

**Comment by LeandroBraier** [comment]
Marce, te pasé por mail los códigos y claves de los corralones que faltaban.

abrazo

**Comment by mkreyness** [comment]
ok, te aviso cuando lo tenga todo cargado.

**Comment by LeandroBraier** [comment]
Dale. Lo antes posible por favor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
fijate lo que te respondi sobre el mail con el excel.

**Comment by LeandroBraier** [comment]
Dale, espero tu respuesta entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ya cargue los representantes, lo que si hay casos de mas de 20 corralones con el mismo nombre.
Queres (para automatizarlo un poco) que les ponga como usuario el codigo que pusiste + el numero de corralon ? Asi nunca va a haber repeticiones, y el que igual era uno solo no creo que le joda mucho que le agreguemos un numero de 3 o 4 cifras al final.

**Comment by LeandroBraier** [comment]
Exacto. Avancemos así.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-10 14:10 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, ya todos los corralones tienen usuario.
Bajalo de nuevo para tener realmente lo que se asigno a c/u.

**Comment by LeandroBraier** [comment]
Genial. Qué necesitás de mi parte?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Nada, ya esta todo hecho.

**Comment by LeandroBraier** [comment]
Genial. Ahi me lo bajé. Dos preguntas:

1) Los corralones que participan son los que tienen Estado = 1 no?

2) De donde me puedo bajar un excel que además tenga usuario y pass de cada uno?

Entonces en este ticket solo quedaría que @FAAREIA corrija el porcentaje de la barra amarilla que no se ve. Digamos: en la que no se ve el porcentaje.

**Comment by mkreyness** [comment]
Mmm, No.
Los corralones son los mismos de la GUIA DE CORRALONES, el estado tiene que ver con otras cosas, no podemos asociarlo a un torneo en particular.

Los que participan son todos los que tienen objetivo, y ese dato no esta en el corralon (es un objetivo para cada torneo o semestre).
Creo que la forma mas simple de filtrarlos seria por representante, los que no tienen, no van.

El dato de usuario y password ahora se lo agrego a la consulta y lo vas a poder exportar a Excel.

**Comment by mkreyness** [comment]
En realidad el de usuario estaba. Ahi agregue el de password.  Si bien en pantalla no se muestra, al exportar al excel, sí.

**Comment by LeandroBraier** [comment]
Genial. Eso necesitaba. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi esta todo listo.
Abrazo

**Comment by LeandroBraier** [comment]
Ok, gracias Fede!

Cierro este ticket y en un rato te paso unas modificaciones que me está pidiendo el cliente (para variar).

Pueden ser para el lunes esas modificaciones.

abrazo
