### ISSUE TITLE
Newsletter ParexKlaukol Newsletter Julio para hoy. DEADLINE: Hoy 10/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#92]
Fede, te paso un pedido de maquinación de newsletter para hoy en base a este template:

http://parexklaukol.com.ar/_mailing/novedades2/

El template ya está armado, solo hay que reemplazar fotos y textos. Por favor confirmame si lo podemos tener hoy.

Van los textos de las notas en orden de arriba a abajo incluyendo las fotos. Cuando tenga los links te los paso, pero no están subidos aún a Noveades.

TÍTULO DEL NEWSLETTER: Novedades de Julio en ParexKlaukol

NOTA 1 Y PRINCIPAL (adaptar al tamaño)

FOTO 1
http://lunar.thegamez.net/greentechnology/green-building-materials/green-building-materials-resolute-in-tough-economic-conditions-the-1024x768.jpg

Título: Todo sobre Edificios verdes en Argentina. 

Texto: Conocé mas sobre la certificación LEED para construcción sustentable y el nuevo sistema de evaluación de edificios verdes.

FOTO 2

![preview-club-colocadores](https://cloud.githubusercontent.com/assets/6719872/8618642/6cdad288-26e6-11e5-8fee-f57b8a01fc58.png)

parexklaukol.com.ar/_colocadores/

Título: Si sos colocador, sumate a nuestro Club!

Texto: En el Club de Colocadores Klaukol podés sumar puntos y canjearlos por fabulosos premios todos los meses. Sumate!

Las siguientes 3 notas van chiquitas como las 4 de abajo sobre fondo gris:

FOTO 3

PRODUCTO

Título: Mortero monocapa color: fachadas en un solo paso

IMAGEN: ![parex estilo 4d](https://cloud.githubusercontent.com/assets/6719872/8618748/6564fb4a-26e7-11e5-8e7e-d0679971694a.png)

Texto: Con Parex Estilo 4D, nuestro mortero monocapa color de última generación, podés sustituir el proceso tradicional por una única aplicación. Descubrí más!

FOTO 4

TENDENCIAS

IMAGEN: ![3-estilos-porcelanatto](https://cloud.githubusercontent.com/assets/6719872/8618738/3de85c4c-26e7-11e5-9f29-ad592d22bb50.png)

Título: Tres estilos en Porcellanatos para ambientes originales

Texto: El uso de porcellanatos para revestir pisos o muros es hoy muy valorado por arquitectos y decoradores. Te compartimos 3 propuestas. Conocelas!

FOTO 5

Título: Capacitaciones: este mes en Entre Ríos y Santiago del Estero 

![foto-capacitaciones-julio](https://cloud.githubusercontent.com/assets/6719872/8618831/3d1de614-26e8-11e5-9633-418fbcf818b9.png)

Texto: Durante Julio estaremos recorriendo las Gualeguay, Monte Caseros, Frías y Termas de Rio Hondo.  Acercate, conoce sobre nuestros productos y su forma de aplicación.  Enterate más!

Abajo van de las notas va todo igual que la otra vez, solo que con el logo de Club de Colocadores habilitado.

Confirmame por favor @FAAREIA si llegamos a tenerlo para la tarde.

abrazo

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/novedades-julio/novedades-julio.html
Faltarían los vínculos lea.

**Comment by LeandroBraier** [comment]
Genial, Fede. Tres cambios nomás:

1) Falta el tilde en el "Conocé más" de la foto 1.

2) Va una nueva versión de la foto de Club de Colocadores.

![foto-club-colocadores](https://cloud.githubusercontent.com/assets/6719872/8628274/f7115b0c-2727-11e5-9a0e-7603a9bd58ba.png)

3) Va una foto para cambiar la de Capacitaciones, por formato y estética.

![foto-capacitaciones](https://cloud.githubusercontent.com/assets/6719872/8628337/760c18de-2728-11e5-99c8-72f7f5fb5d6b.png)

4) Cambiá el logo del Club de Colocadores por el que quedó en el Club de Colocadores posta:

![logo-ok-club-colocadores-final-def](https://cloud.githubusercontent.com/assets/6719872/8628283/fef70d26-2727-11e5-98f8-8281d51f6954.png)

abrazo

**Comment by LeandroBraier** [comment]
Fijate que te actualicé la foto de capacitaciones.

abrazo

**Comment by LeandroBraier** [comment]
Fede, cuando puedas necesitaría esto corregido porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahora ya cambie las fotos lea, pero siguen faltando los links.

**Comment by LeandroBraier** [comment]
Excelente, Fede. Gracias!

Queda de mi lado. Cuando tenga links y modificaciones nuevas te lo paso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-13 9:10 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Braulio: te paso las modificaciones finales para el news. Gustó mucho también! Solo son cuestiones de contenido en general. Cuando lo tengas listo, ponele links falsos a las notas y pasamelo. Cuando tengo los links finales te los paso.

<img width="1012" alt="captura de pantalla 2015-07-14 a la s 09 51 03" src="https://cloud.githubusercontent.com/assets/6719872/8673367/5741a18a-2a0c-11e5-8f4e-7fdfd8ba8798.png">

ACÁ VAN LOS TEXTOS DE LAS DOS NOTAS QUE CAMBIAN:

Titular: Techos Verdes: cómo mejorar tu calidad de vida pensando por encima de tu cabeza

Descripción: Esta nueva tecnología ambiental ofrece muchos beneficios relacionados con el cuidado del medio ambiente y la calidad de vida. Conoce más haciendo clic aquí.

![techos-verdes01](https://cloud.githubusercontent.com/assets/6719872/8673488/494cb5fa-2a0d-11e5-8169-8b241185d9eb.jpg)

Titular: Porcellanatos. Diversas propuestas para ambientes originales

Descripción: El uso de porcellanatos para revestir pisos o muros es hoy muy valorado por arquitectos y decoradores, pero hay muchas tendencias. Conocelas!

![shutterstock_44492791](https://cloud.githubusercontent.com/assets/6719872/8673534/b57c3fe8-2a0d-11e5-9314-8daa9c123441.jpg)

A esta última foto la vas a tener que recortar un poco me parece para que tenga el formato correcto.

Cualquier duda avisame.

abrazo

**Comment by braulio-evangelisti** [comment]
Ahi apliqué los cambios, fijate como quedo:

http://parexklaukol.com.ar/_mailing/novedades-julio/novedades-julio.html

Deje una copia de la misma con las correcciones pero con la primer nota de edificios verdes por si sirve para Agosto por lo que entendi:

http://parexklaukol.com.ar/_mailing/novedades-julio/novedades-agosto.html

Abrazo

**Comment by LeandroBraier** [comment]
Excelente Braulio!!

Muy bien pensado!

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-14 12:00 GMT-03:00 Braulio Evangelisti notifications@github.com:
