### ISSUE TITLE
Nuevo tema subido falla.  URGENTE

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#93]
Fede, tengo nuevo video con Trivia, lo subí todo al CMS y no funciona. Mirá:

http://www.parexklaukol.com.ar/cgi-bin/jugar.pl?id=5&usuario=LeanBraier&clave=parexklaukol

Necesito que lo soluciones urgente porfa porque hoy tiene que quedar subido. Te voy a pasar el Slide en un ratito, por favor subilo apenas te lo pase también.

abrzo

**Comment by mkreyness** [comment]
Fede puede tocar el slide, pero todo lo que pase por el CMS es cosa mia.
Dejame que lo miro, no es solo cargar el juego, tambien hay que cargar 
el tema.

**Comment by mkreyness** [comment]
Ah, al reves, cargaste un TEMA y su trivia, pero no tiene la actividad asociada.
Eso se carga en juegos, asociando al tema. (y hay actividades que no llevan tema porque son generales, como "entrar" o "dar me gusta").
Puede haber 1, 2 o 3 juegos asociados al mismo tema. En este caso seria solo la trivia por video, no ?
La parte que vi que cargaste en la solapa de resultados nunca se llego a usar. Eso lo habia parametrizado en base a algo que hablamos muy al principio pero despues se hizo lo de progress (0/2, 1/2, 2/2) que reemplazo a todo eso, asi que no te molestes en cargarlo en los proximos.
No lo elimine porque capaz el requerimiento vuelva a aparecer.
Le voy a cargar el juego de trivia video.

**Comment by mkreyness** [comment]
Ahi esta, igual tuve que hacer mas cambios, porque hasta ahora los modelos que teniamos de template eran:
- completo (video + documentacion + trivia suelta)
- simple ( imagen + trivia suelta)
- "embedded" share (imagen + share)

y en este caso se dio diferente porque es simple pero con video en vez de imagen.
Ya esta andando, fijate.

**Comment by LeandroBraier** [comment]
Si, pero lo quise acomodar y me parece que me mandé macana. Fijate. Quiero
que tenga al menos el video y la trivia funcionando. El PDF lo puse sin
nombre y ahora no lo puedo editar, como me pasó el otro viernes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
El video esta funcionando. La trivia tambien, pero el cuestionario esta mal, las dos preguntas estan en pagina 1 y figuran como pregunta 1.
Te lo cambio a paginas separadas y con numeros 1 y 2, ok ?
Entonces lleva PDF ?

**Comment by LeandroBraier** [comment]
Gracias MK!

Sí, lleva PDF. Este debería ser igual al primero de Klaukol Impermeable
Potenciado:
- completo (video + documentacion + trivia suelta)

El PDF lo tengo. Cómo lo subo?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-10 19:36 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
En la parte de juegos, donde ahora te agregue la descripcion del de PDF, vas a ver que hay una solapa DOCUMENTOS. Ahi agregas un renglon con el nombre y el URL al PDF.
No haces upload por aca, se supone que el PDF ya esta en algun lado.

**Comment by mkreyness** [comment]
Igual veo que no anda si estas DENTRO del "juego" (no aparecen los botones para agregar).
Pero igual en la lista de juegos podes tildar donde dice  [ ] Documentos y te aparece la listita debajo y ahi si podes agregar.

**Comment by LeandroBraier** [comment]
Perfecto, ahí pude. Ya funciona todo joya. Gracias MK!

Vos podés subir el slideshow con el link también?

**Comment by mkreyness** [comment]
Si, pero siempre es a manopla por ahora, todavia no esta implementado via CMS.
Es para agregar o para reemplazar alguno de los actuales ?

**Comment by LeandroBraier** [comment]
Para agregar nomás. Te lo puedo pedir a vos entonces?

Genial. Estoy esperando feedback del cliente. Te aviso cuando tengo noticias.

abrazo

**Comment by LeandroBraier** [comment]
Marce, está aprobada la imagen. 

![slide-trivia-10-julio-par](https://cloud.githubusercontent.com/assets/6719872/8630936/1d298146-2743-11e5-93ce-c5db1c29056b.png)

Subila y que linkee al nuevo tema que creamos hoy.

abrazo y gracias!

**Comment by LeandroBraier** [comment]
Marce, te llegó?

**Comment by mkreyness** [comment]
Si, pero no estoy online en este momento, en un rato me siento y lo implemento.

Enviado desde mi iPhone

**Comment by mkreyness** [comment]
la foto dice suma 80 puntos y el juego tiene 60... Cambio los puntajes al juego antes de ponerlo ?
O esta mal la imagen ?

**Comment by LeandroBraier** [comment]
Tenés razón. Va corregida la foto.

![slide-trivia-10-julio-par](https://cloud.githubusercontent.com/assets/6719872/8631546/52ef4f02-274f-11e5-99a1-980bc5c7ff91.png)

Gracias!

abrazo
