### ISSUE TITLE
Torneo de Potenciados #4: Modificaciones de diseño. DEADLINE: 14/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#94]
@FAAREIA, van una serie de cambios en el Torneo pedidos por el cliente. 

A criterio general, quieren que todo sea más simple para el dueño del corralón, casi que en modo de pregunta y respuesta. Ejemplo ¿como vengo este mes? cuanto mas tengo que comprar? Una cosa así.

Te paso los cambios:

1) Login

Cambiar el texto de "Ingresá…" por "Ingresá para participar de la competencia de ventas."

2) Home Corralones

Que el ritmo del Slideshow sea un poco más lento para que se lean enteros los slides.

Cambiar la diagramación y los colores que te paso aquí en este mock up.

![mock-up-con-correcciones-torneo-potenciados](https://cloud.githubusercontent.com/assets/6719872/8630635/a6698fdc-273e-11e5-8f52-2626020ce74d.png)

Las fuentes adaptalas al css y demás estilos, pero te paso esto para que veas la diagramación exacta que quieren y que a simple viste quieren algo menos formal, más llamativo y no con charts.

Lo que sigue debajo de la Tabla de Posiciones queda igual.

3) Perfil del Distribuidor

Quitar la foto y quitar toda la parte de "PERFIL DEL CLIENTE". Que todo eso quede en la home, como en el mock up de arriba.

abrazo

**Comment by LeandroBraier** [comment]
Fede, estos cambios pueden estar para mañana sin problema. Antes de arrancar decime porfa aprox cuántas horas te llevarían estos cambios y te confirmo con Eze.

Si son muchas horas por ahi lo frenamos. Avisame porfa.

abrazo

**Comment by FAAREIA** [comment]
Creo que hoy lo puedo terminar, el tema es que si le sacamos el fondo blanco a los bloques, va a quedar todo medio flotando y menos llamativo y organizado.

**Comment by LeandroBraier** [comment]
Claro. Entiendo. Fijate cómo le podés encontrar una vuelta a eso pero sin recurrir al chart, que no les gusta. Dale un formato más explicativo, como si fuera un folleto, entendés? Pregunta, respuesta.

O sea que te llevará aproximadamente 3 hs máximo? Si es así avanzá nomás.

**Comment by FAAREIA** [comment]
máximo no sé porque no hay un diseño definido y aprobado, pero hoy si se puede presentar algo

**Comment by LeandroBraier** [comment]
Buenisimo. Avancemos con esa primera entrega entonces.

Abrazo

**Comment by FAAREIA** [comment]
Ahi ya modifique la frase del login y dupliqué el tiempo de transición entre slides.
Lo de cambiar la diagramación y colores no entiendo que es.

Aca va el agregado de la data:
http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1&tipo=C

Lo del velocimetro lo saqué de los 4 bloques porque me parece que no simplifica, sino que es un gráfico que hay que verlo bien y entenderlo.
¿Lo del chart se saca de la tabla de posiciones?

**Comment by LeandroBraier** [comment]
Fede, me parece que no viste el mock up que te pasé. Fijate en la web, no
solo en el mail:

https://github.com/LeandroBraier/Klaukol/issues/94#issuecomment-120934831

Si bien me gusta lo de los rectángulos de colores, me parece que no viste
todo el pedido completo, en cuanto a los textos que irían y a los cambios
en el diseño, que está todo en un mock up que te armé especialmente y quizá
en el mail no te lo muestra. Lo tenés que ver en la web.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-13 10:52 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hola Lea, la foto es esta si no me equivoco:
https://cloud.githubusercontent.com/assets/6719872/8630635/a6698fdc-273e-11e5-8f52-2626020ce74d.png

Me faltó poner el mes, la pregunta pero lo otro lo dejé igual como pediste.
De hecho los charts los saqué porque me dijiste que no iban más.

Lo del fondo blanco y los títulos también lo modifico como en el ejemplo?

**Comment by LeandroBraier** [comment]
Si, no tal cual, pero en esa línea: color más llamativo, fuente más grande.

Lo del chart se va de la tabla de posiciones también.

Lo de la prgunta del mes es importante porque sino se ven dos rectángulos de colores con dos objetivos diferentes y no se entiende por qué.

**Comment by FAAREIA** [comment]
asi?
http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1&tipo=C
Medio gigante me parece igual.
La palabra "puesto" del 3 de la tabla no estaba porque se la habíamos sacado, queda asi?

**Comment by LeandroBraier** [comment]
Me gusta.

Y las barras de porcentaje por qué las sacaste?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-13 11:54 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Me dijiste que no iban, es un chart en barra. Excepto que con chart te refieras a los velocimetros.

**Comment by FAAREIA** [comment]
Avisame y lo repongo

**Comment by FAAREIA** [comment]
Ahi agregué las barras verticales pero no el velocimetro

**Comment by LeandroBraier** [comment]
Fede, gustó mucho al cliente esta versión. 

1) Te paso algunos cambios muy mínimos que piden:

![nuevos cambios torneo de potenciados](https://cloud.githubusercontent.com/assets/6719872/8677455/7fd47528-2a25-11e5-8f3d-012711e10bd3.gif)

2) A estos cambios deberías sumarle emprolijar todo lo que resta emprolijar. Por ejemplo: hay mucha diferencia entre las fuentes más grandes y las más chicas. Las grandes están bien, aumentá las más chicas porque es gente mayor la que lee y le va a resultar demasiado chico ese cuerpo 9 o 10 que estamos usando.

3) Además, me recordaron que quitemos la foto del perfil del corralón y el chart que dice "Perfil del Cliente" de ahí en la versión de los corralones. Por ahora hagamos eso.

![viejos cambios torneo de potenciados](https://cloud.githubusercontent.com/assets/6719872/8677499/c36ccdb2-2a25-11e5-8827-8b90b3cf0ff7.gif)

Puede ser para mañana al mediodía esto?

abrazo

**Comment by FAAREIA** [comment]
Yo creo que llegamos.

**Comment by LeandroBraier** [comment]
Genial. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, tu prioridad mañana es esto, el Torneo de Potenciados. Todo lo demás va en segundo lugar.

abrazo

**Comment by FAAREIA** [comment]
www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=aldocampanella&clave=127847&torneo=1&tipo=C

Fijate si falta algo, lo de la barra verde no se va a ver pero ya lo implementé en el CSS.
@mkreyness habría que agregar la clase "supero" al div .porcentaje para cuando el % supera el 100%.

**Comment by FAAREIA** [comment]
@mkreyness también hay que cambiar lo del % en vez de PTS, que diga "93939 PTS para subir"

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

@mkreyness avisame cuando esté eso porfa.

abrazo

**Comment by mkreyness** [comment]
```
listo, ojo tuve que tocar el template.

El 15/07/2015 a las 10:50, Federico
  Arena escribió:


  @mkreyness también hay que cambiar lo
    del % en vez de PTS, que diga "93939 PTS para subir"
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
Por lo que veo tambien hay que ponerle variables a todo lo de arriba y llenarlo con contenido real, si no vas a tocar mas nada en el template lo hago yo, y de paso pongo eso del "supera". Espero tu ok @FAAREIA

**Comment by FAAREIA** [comment]
Tenés mi OK ^^

**Comment by mkreyness** [comment]
Todo listo, aunque con los datos que hay (reales) no hay forma de probar lo del "supera".

**Comment by LeandroBraier** [comment]
Genial, no problem.

Lo único que necesitaría ahora es lo siguiente:

Que me pasen un link a dashboard de distribuidor cada una de las 6 categorías y de 1 corredor por cada 1 de las 6 categorías.

Serían 12 links en total.

abrazo

**Comment by mkreyness** [comment]
Pero el distribuidor tiene que aparecer entre los 10 primeros puestos ? No es tan facil (con datos tan chicos) encontrarlo.

**Comment by LeandroBraier** [comment]
No podemos ordenar en el cms por puesto? Deberíamos. Sino va a ser un lío
controlarlo, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-15 11:59 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Me contestas mis preguntas con más preguntas... Asi no voy a avanzar
:)

Se puede, pero no en la consulta comun desde donde accedes a
modificar los datos del corralon, ya que surge de comparar datos de
3 tablas separadas y no todos tienen objetivo ni compras.
Habria que hacer una consulta especial que haga lo mismo que el
ranking pero general.

Hago esto primero y despues seleccionas a gusto a cuales mostrar ?
Pero va a llevar un buen rato, no creo que lo pueda tener antes de
las 6 (sobre todo porque estoy saliendo y vuelvo a mi ofic a las 4).

El 15/07/2015 a las 12:08,
  LeandroBraier escribió:

No podemos ordenar en el cms por puesto? Deberíamos.
  Sino va a ser un lío
  controlarlo, no?

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-07-15 11:59 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Pero el distribuidor tiene que aparecer entre los 10 primeros
  puestos ? No
  > es tan facil (con datos tan chicos) encontrarlo.
  >
  > —
  > Reply to this email directly or view it on GitHub
  >
```

https://github.com/LeandroBraier/Klaukol/issues/94#issuecomment-121643806
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Ok, a las 18 hs está bien MK. Decime si necesitás alguna respuesta más de
mi parte para llegar con eso. Yo le voy pasando al cliente lo que tenemos
hasta ahora igual.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-15 12:13 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Tengo todo lo necesario, uso el mismo criterio que en las paginas para distribuidores y corredores.
Te pongo un filtro por categoria y por representante, y el dato del % de cumplimiento semestral para ordenar por ahi. En cuanto lo tenga te aviso.

**Comment by LeandroBraier** [comment]
Genial, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-15 13:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Listo, lo tenes en el menu de Torneos, bajo el nombre "Ranking de Distribuidores".
El primer dato por el cual podes (y debes) filtrar es el Torneo, obviamente ahora hay uno solo, pero cuando haya mas de uno, es lo primero a seleccionar. Despues puse que puedas separar por provincia por si eso pudiera interesar en algun momento (pero no es obligatorio), la categoria, y si queres tambien el representante.
Ya sale ordenado por porcentaje de cumplimiento del TORNEO decreciente, o sea tal cual como en la pagina (vas a ver que nuestro amigo Aldo Campanella es el 3ero de su categoria).
Podes exportarlo a excel si queres para ver las passwords y armar los links.
Esto es para DISTRIBUIDORES, para ver el dashboard del REPRESENTANTE podes elegir cualquiera que veas que tiene buenos puntajes, y el user/pass lo sacas de la lista de "representantes".

**Comment by LeandroBraier** [comment]
Impecable MK. Gracias!

**Comment by LeandroBraier** [comment]
MK, estoy viendo que al exportar excel de representantes no me da codigo ni pass. Podrás agregar eso porfa?

abrazo

**Comment by LeandroBraier** [comment]
Otro tema: esta URL me da error, puede ser porque es muy largo el código?

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=corralonsanmartinshmogliac-tavanni&clave=127976&torneo=1&tipo=C

**Comment by LeandroBraier** [comment]
Otro caso: en el excel que bajé me apareció la clave pegada al código del usuario, como si todo fuera parte del codigo y no hubiera clave. Lo probé correcto y no anda:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=joseypedrocelottic&clave=128026&torneo=1&tipo=C

Lo probé pegado también y sin clave e igual no funcionó:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=joseypedrocelottic128026&clave=&torneo=1&tipo=C

Los reviso todos y te paso feedback de todos los casos como estos si hay más.

abrazo

**Comment by mkreyness** [comment]
```
Este primer link de joseypedrocelottic me anda bien.
Obviamente NO va pegado. Vos decis que si entras al corralon en el
CMS el dato esta asi ?

El 16/07/2015 a las 9:59, LeandroBraier
  escribió:


  Otro caso: en el excel que bajé me apareció la clave pegada al
    código del usuario, como si todo fuera parte del codigo y no
    hubiera clave. Lo probé correcto y no anda:
  http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=joseypedrocelottic&clave=128026&torneo=1&tipo=C
  Lo probé pegado también y sin clave e igual no funcionó:
  http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=joseypedrocelottic128026&clave=&torneo=1&tipo=C
  Los reviso todos y te paso feedback de todos los casos como
    estos si hay más.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
no lo que esta pasando en este caso es que si el tipo no esta en el
ranking no esta calculando los datos de arriba y da una division por
cero al calcular el porcentaje.
Ya lo arreglo.

El 16/07/2015 a las 9:43, LeandroBraier
  escribió:


  Otro tema: esta URL me da error, puede ser porque es muy largo
    el código?
  http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=corralonsanmartinshmogliac-tavanni&clave=127976&torneo=1&tipo=C
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
Listo lo del usuario y clave. a Guillermo Caravelli (el "representante" de Juan Perugia) y a Juan Corredor habria que eliminarlos.

**Comment by mkreyness** [comment]
Lo de que daba error con los que no entraban en el ranking tambien ya esta arreglado.

**Comment by LeandroBraier** [comment]
Perfecto, gracias!

Ya me puedo bajar los password de los representantes comerciales?

**Comment by mkreyness** [comment]
Si, a eso me referia cuando dije "listo lo del usuario y clave".

**Comment by LeandroBraier** [comment]
AH, perfecto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-16 13:40 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
@FAAREIA , dos modificaciones mínimas y estamos:
1. sumar barrita de porcentaje mensual mes por mes que sacamos.  No el velocímetro, la barrita igual que la de abajo pero que en lugar del porcentaje semestral diga el mensual. Ponela a un costado, donde te parezca que queda mejor
2. Agrandemos el % dentro de todas las barras que esta demasiado pequeño y cuesta leerlo.

Lo demás joya.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA a qué hora podrías tener estos dos cambios sencillos?

**Comment by FAAREIA** [comment]
Pregunta
La barra mensual es asi vertical igual que la otra? Tiene que ser una barra? va a prestar a confusión
Los % si los agrando los tengo que sacar de la barra, no entran sino. El límite de 100% se lo dejaría dentro, el otro por fuera creo.

**Comment by FAAREIA** [comment]
Ahi cambié lo de los porcentajes. Me pareció que sacar el porcentaje iba a quedar mal por lo que @mkreyness te voy a pedir si el decimal del % puede ser 1 y no 2. Osea 83.4% en vez de 83.41%.

**Comment by LeandroBraier** [comment]
Si, barra vertical igual que la otra.

Todo OK con lo que decís de hacer con los porcentajes. Adelante.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 15:13 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
La barra no se puede poner al costado de la otra, va a ser muy confunso.
La barra es 1 sola o detalla todos los meses? Sería mejor ponerla como un bloque aparte sino

**Comment by FAAREIA** [comment]
No dije nada, ya se a que barra te referías. La que sacamos "te faltan"

**Comment by FAAREIA** [comment]
Ahi ya agregué la barra, un poco menos alta porque sino va a quedar el contenido muy vertical cuando la barra ideal sería la horizontal en ese caso.

**Comment by FAAREIA** [comment]
@mkreyness En la variable de "porcentaje" en el bloque de "Alcanzaste" también aplicale la lógica de 1 decimal, sino no entra el % en la barra.

**Comment by mkreyness** [comment]
No entiendo, segun el programa esta con 1 decimal. Mostrame donde se ve mal.

**Comment by FAAREIA** [comment]
http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=corralonsanmartinshmogliac-tavanni&clave=127976&torneo=1&tipo=C

Si voy a este link y veo la tabla de posiciones semestrales, en las barras te muestran el % con 2 decimales.

**Comment by mkreyness** [comment]
Ah pero esa no es la variable "porcentaje", es la variable "puntos" (porque antes ahi se mostraban puntos). Ahora lo ajusto.

**Comment by FAAREIA** [comment]
Gracias

**Comment by mkreyness** [comment]
Listo.

**Comment by FAAREIA** [comment]
Excelente, ya lo vi

**Comment by LeandroBraier** [comment]
Quedó muy bien chicos!! Al cliente le gustó.

Resolvamos el lunes qué pasa en esa barra del mes cuando se supera el 100% como ocurre en este caso:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=materiales-pedraza1311&clave=125745&torneo=1&tipo=C

abrazo y buen finde!

**Comment by FAAREIA** [comment]
Ahi ya lo corregí eso. Seguí la misma lógica que las otras barras, para demostrar que el 100% es la mitad solamente. @mkreyness habría que dividir el % como en las barras de la tabla de posiciones.

**Comment by mkreyness** [comment]
Listo, pero no se ve la marquita de 100%, con lo cual se siente raro:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=materiales-pedraza1311&clave=125745&torneo=1&tipo=C

**Comment by LeandroBraier** [comment]
Es cierto. Si pueden poner una marquita, aunque tenga el 100% chiquito,
ayuda.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-20 10:19 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Es que no se ve porque ya esta en el 100% justo. En una situación común, uno ve la marca todos los días hasta llegar y sobrepasarla.

**Comment by LeandroBraier** [comment]
Ah, perfecto.

abrazo

**Comment by LeandroBraier** [comment]
Fede, cuál es el acceso oficial hoy para el torneo de potenciados?

**Comment by FAAREIA** [comment]
Creo que es este Lea:
http://www.parexklaukol.com.ar/torneo-corralones/login.html
Necesito que @mkreyness confirme igualmente

**Comment by mkreyness** [comment]
Si, igual habia un error porque en el programa habia una referencia al nombre anterior de la carpeta (/torneos/login.html). 
Ya lo arregle.

**Comment by LeandroBraier** [comment]
@mkreyness algo anda mal.

Ingreso a este login que uds me pasaron:

http://www.parexklaukol.com.ar/torneo-corralones/login.html

Y me aparecen todos los datos en 0.

Pero cuando ingreso a este link:

http://www.parexklaukol.com.ar/cgi-bin/torneo-con-slide.pl?usuario=norbertocastello&clave=108811&torneo=1&tipo=C

Lo veo bien. Qué puede ser?

Tema 2: Al deslogearme (en realidad hacer clic en el nombre de usuario logeado) me lleva a un Login fallido de Vendedores. Hay que corregir eso también porfa.

abrazo

**Comment by mkreyness** [comment]
Porque esta todo mal lo que dice el login, esta mal copiado de lo que escribi aca, seguramente porque esto se come las variables (comentarios de HTML). Ahora lo arreglo y te aviso.

**Comment by mkreyness** [comment]
Ahi arregle el login. El problema es que norbertocastello no es un usuario de corralon, es un corredor.
No habria que mostrar el link de "perfil corralones" en el template de corredor.
De todos modos en el caso del corralon tampoco se supone que haga eso, deberia tener un menu desplegable en que aparezca "Mi Perfil" y "Logout".
Le saco por ahora el link equivoco, hasta que Fede solucione lo del menu ?
En el de corredor el menu solo tendria la opcion "Logout".

**Comment by LeandroBraier** [comment]
Exacto MK. Gracias por el arreglo!

abrazo

**Comment by mkreyness** [comment]
Ahi le saque el link a perfil corralon desde el usuario corredor.

**Comment by LeandroBraier** [comment]
Gracias MK!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Chicos, ya casi estamos. Ahora les paso modificaciones de la versión de Corredores en Ticket aparte para ser más prolijos. abrazo
