### ISSUE TITLE
Maquetación HTML Mailing Bienvenida. DEADLINE: 14/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#95]
Braulio, para mañana tranqui necesitaría que lo maquetes en HTML como hiciste con el newsletter. 

Así los próximos mailings de bienvenida van así y no como grupo de imágenes y también para tomar como base esta maquetación para futuros mailings parecidos.

abrazo

**Comment by braulio-evangelisti** [comment]
Ok, hay algun PSD o imagen de referencia como habia con el newsletter de novedades?

**Comment by LeandroBraier** [comment]
Si, yo le pasé uno a Fede. Yo lo tengo pero creo que él lo tiene con las últimas modificaciones.

@FAAREIA le mando el mio? O vos tenés uno más actualizado?

**Comment by FAAREIA** [comment]
No se de cual hablan, es el de vendedores?
Cual emailing esta en todo imágenes?

**Comment by LeandroBraier** [comment]
Si, el Mailing de Bienvenida de Vendedores es.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
El mailing es este:
http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Lea tené en cuenta que si se maqueta, hay cosas que se van a perder y las tipografías van a ser la Arial por lo que no va a quedar muy bien algunas cosas.

**Comment by braulio-evangelisti** [comment]
@LeandroBraier pasame tu psd por favor asi voy sacando elementos por separado siguiendo la estructura que armo fede

**Comment by LeandroBraier** [comment]
Si. Hagamosño lo mejor posible pero si.

**Comment by LeandroBraier** [comment]
Ahi te lo estoy mandando por wetransfer. Igual hacé un chequeo de diferencias que no hayamos actualziado nada después.

**Comment by LeandroBraier** [comment]
https://www.wetransfer.com/downloads/ada98004d751acf076e82f0e276c8ddd20150713191126/10c387

Ese es el link. Puede ser para mañana esto.

**Comment by FAAREIA** [comment]
Este no es el PSD Lea, ese ya esta maquetado

**Comment by FAAREIA** [comment]
Va, esta maquetado pero es algo distinto. Pero no es el de bienvenida de vendedores

**Comment by LeandroBraier** [comment]
Ahi está la cuestión. Vos lo trabajaste en la versión final. Yo no tengo
ese PSD. El que mandé es el último que tengo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Pero bajatelo, ese no es el PSD. Ese es el newletter de Julio.

**Comment by FAAREIA** [comment]
Aca encontré un PSD que me sirve para lo que necesitaba. Con eso estoy creo.
Abrazo

**Comment by LeandroBraier** [comment]
Genial. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

**Comment by LeandroBraier** [comment]
Gracias Fede! Excelente!

**Comment by LeandroBraier** [comment]
Fede, MK me hizo acordar que falta un cambio. Puede ser para mañana sin problemas.

Necesito cambiar el premio de arriba de todo. Debe decir: ESTE MES PARTICIPÁ UNA PLAYSTATION 4. Te paso la gráfica. Decime si necesitás el PSD también.

![slide-premio-de-julio](https://cloud.githubusercontent.com/assets/6719872/8687491/34228b78-2a67-11e5-8443-6c7b7052f96d.png)

![preview-premio-de-julio](https://cloud.githubusercontent.com/assets/6719872/8687514/62193108-2a67-11e5-8234-d173fc1e0fdd.png)

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Fede, gracias por la rapidez pero quedó horrible la adaptación. 

Esperaba una adaptación en el estilo de la que teníamos antes pero en negro y con el texto así. Con todo respecto, queda para el culo esta jeje Ponele el header curvado de antes pero en negro y con la misma tipografía del texto de antes.

abrazo

**Comment by FAAREIA** [comment]
Oka, pasame el psd mejor, sino no tengo mucho margen

**Comment by LeandroBraier** [comment]
No problem. Ahi va por WeTransfer!

abrazo

**Comment by LeandroBraier** [comment]
Ahi fue:

https://www.wetransfer.com/downloads/bd70b45201aeb00497e802df17dabc9220150715134928/e95c5a

**Comment by FAAREIA** [comment]
Olvidé avisar! Ya esta listo, dale F5 lea
Abrazo

**Comment by LeandroBraier** [comment]
Joya, gracias Fede!

abrazo
