### ISSUE TITLE
Mail Customizado desde MailChimp

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#96]
Sabés si es posible?

Por ejemplo, el mail de cadena de mails que cada link era diferente para saber de qué cliente era, se puede hacer a través de MailChimp?

**Comment by mkreyness** [comment]
Ni idea que deja y que no deja hacer mailchimp, pero si el mail tiene un formato fijo y lo que varia es una partecita, deben tener alguna herramienta para hacer el merge y mandar "customizado" el texto a cada destinatario, es lo minimo necesario para cualquier envio masivo, si no como trackearias quien lo abrio, etc. ?

**Comment by LeandroBraier** [comment]
Genial. Cómo se llamaría esa herramienta? Así la busco en el FAQ de MailChimp

**Comment by mkreyness** [comment]
```
algo asi como data merge, variable data, o cualquier referencia a
template.

El 13/07/2015 a las 13:21, LeandroBraier escribió:

  Genial. Cómo se llamaría esa herramienta? Así la busco en el
    FAQ de MailChimp
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Acá encontré esto:

https://apidocs.mailchimp.com/api/2.0/lists/merge-var-update.php

¿Puede servir?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Dice que la versión 2.0 no corre mas. 
De todos modos ni idea como se usaria el API, queres que me ponga a estudiarlo ? Necesitaría las credenciales de acceso a ver si lo tenemos habilitado 

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
No te preocupes. Organicemos una reunión en unos días y ahí te traes la
compu y te doy el acceso, porque tiene Validación de Google a través de una
app, viste como es eso?

Te da 30 segundos para ingresar un código, es un plomo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-13 15:44 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok. Pero entonces fijate primero si ves si tenemos habilitado el uso del 
API. A veces hay que pedirlo especialmente o anotarse como developer.

**Comment by LeandroBraier** [comment]
Dale, mañana consulto MK.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-13 15:52 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Confirmado. Tenemos acceso a la API. mira las capturas del dashboard:

<img width="1336" alt="captura de pantalla 2015-07-14 a la s 13 14 44" src="https://cloud.githubusercontent.com/assets/6719872/8678052/d34d5942-2a28-11e5-841d-7c8aadec057a.png">

<img width="1322" alt="captura de pantalla 2015-07-14 a la s 13 14 50" src="https://cloud.githubusercontent.com/assets/6719872/8678059/d6bf0486-2a28-11e5-912f-01ae974770aa.png">

**Comment by LeandroBraier** [comment]
Entonces quedó confirmado que lo tenés habilitado. Cuando puedas chequeá como se hace. Pensalo como una inversión de tiempo, así no te tengo que volver a pedir los envíos a vos, lo hago directo desde mailchimp, no?

**Comment by LeandroBraier** [comment]
MK, pudiste ver esto?

abrazo

**Comment by mkreyness** [comment]
No porque quedamos que cuando nos vieramos me pasabas la forma de acceder a la cuenta, me dijiste que tenia algo raro que validarse en el momento.

**Comment by LeandroBraier** [comment]
Ah, perfecto. Me lo anoto para la próxima reunión entonces. Quizá convenga hacerla la próxima semana, no? Para ajustar con Fede lo que se viene en Club de Colocadores (que ya va a estar en gran parte maquetado) y Academia ParexKlaukol.

**Comment by mkreyness** [comment]
Miercoles 5-ago a la mañana ?

**Comment by LeandroBraier** [comment]
Consulta con Fede en mail aparte y confirmo.

abrazo

**Comment by mkreyness** [comment]
Volviendo al tema de los mails, no creo que esto cambie mucho porque lo que lleva algo de tiempo es (en el caso de vendedores) cargar el excel en la base de datos. Una vez que esta cargado, los mails se mandan con un programa que no requiere mi atencion.

**Comment by LeandroBraier** [comment]
Ok. El único tema es que no nos registra qué porcentaje de mails se abrió etc, no? O hay forma de que nos diga algo de eso?

**Comment by mkreyness** [comment]
Podemos deducirlo de cuantos de ellos accedieron a la pagina.

**Comment by LeandroBraier** [comment]
Es que no es lo mismo. Los que acceden a la página son los que ademas de
abrir hicieron clic en el link.

Pero quizás hay muchos más que abren el mail y no entienden que tiene que
hacer, por eso no hacen clic. Ponele, por suponer un ejemplo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Entiendo perfectamente, pero igual cualquier estadistica que te diga que "abrieron el mail" es mentira.
Lo que se hace para eso es poner una imagen (invisible) en el cuerpo del mail propia de cada uno y ver si fue accedida. Con que solo el mail se muestre en una ventana de preview (sin que nadie lo lea) ya te lo da por abierto.

**Comment by LeandroBraier** [comment]
Mmm, interesante dato. Lo único que importa son los clics entonces no?

Bastaría entonces con rastrear via google analytics qué links siguieron, porque si son customizados podemos saber usuario y clave, no?

**Comment by mkreyness** [comment]
De google analytics no se nada, pero si, tenes el usuario en el URL

**Comment by LeandroBraier** [comment]
Perfecto etnonces. Gracias Marce!

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness estás disponible para que te pasemos el google authenticator y accedas a MailChimp? Estoy en reunión con Eze.

**Comment by mkreyness** [comment]
Hasta 12:15 si.
Decime que tengo que hacer.

**Comment by LeandroBraier** [comment]
No te preocupes, lo dejamos para más adelante. Por ahora no es urgente. abrazo
