### ISSUE TITLE
Lentitud en carga de Micrositio KIP

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#97]
@FAAREIA cuando abro tarda en cargar. Te fijás por qué?

http://parexklaukol.com.ar/klaukol-impermeable-potenciado/

**Comment by FAAREIA** [comment]
Es un sitio pesado, pesa 18,2MB y esta optimizadas las imágenes, lo que pasa es que son muchas. Las texturas tienen esas desventaja =/

**Comment by LeandroBraier** [comment]
Entiendo. Encima me parece que era la conexión de la produ, porque en casa me cargó en 20 segundos.

Dejemoslo así por ahora. Gracias!
