### ISSUE TITLE
Nuevo Mailing de Bienvenida

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#98]
Marce, a partir de ahora usá este nuevo mailing para enviar a los de bienvenida.

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Tenés posibilidad de saber los mails que rebotaron o fueron al spam?

**Comment by mkreyness** [comment]
Pero sigue diciendo que el premio es un viaje a Mendoza, y este mes el 
premio es una playstation.
Si fueron a spam, solo lo sabe el que lo recibio.
Los rebotes habran ido a la direccion de parexklaukol que usamos como 
sender, yo no tengo acceso.

En todo caso te puedo decir que gente a la que se le mando mail no se 
loggeo nunca.

**Comment by LeandroBraier** [comment]
Genial, eso sirve. A esos habría que mandarselo de vuelta pero con el nuevo
premio. Le pido a los chicos el cambio y te aviso.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-14 15:54 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
Listo Marce, aquí va corregido:

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Este mes usamos este. En Agosto te hago uno nuevo con el nuevo premio.

abrazo

**Comment by LeandroBraier** [comment]
Dale F5

**Comment by mkreyness** [comment]
ok, igual mientras Fede lo reemplace siempre en el mismo lugar y con el mismo nombre, para mi es transparente. Lo que necesito que me confirmes si queres que le remande ESTE contenido a todos aquellos a los que en realidad ya se les mando pero nunca accedieron.

**Comment by LeandroBraier** [comment]
Exacto.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-15 13:47 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Son 771 sobre 993 que tienen mail. Lo voy a ir espaciando en tandas de a 100, te parece ?

**Comment by mkreyness** [comment]
ya estan saliendo.

**Comment by LeandroBraier** [comment]
Excelente! Gracias!
