### ISSUE TITLE
Mailing de Olvidé mi contraseña. 15/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Klaukol#99]
@braulio-evangelisti , tomando como base este mailing:

http://parexklaukol.com.ar/_mailing/vendedores-bienvenida/vendedores-bienvenida.html

Necesito que armes una versión mucho más simple que diga:

Donde dice "Bienvenido a" que diga "Te recordamos tu contraseña para ingresar a:

Después quitale los siguientes fragmentos:
1. el header del premio de arriba de todo
2. Segmento de facebook con fondo celeste
3. segmento de Guía de Corralones

Todo lo demás queda como está.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate si algo asi puede ir @LeandroBraier 

http://parexklaukol.com.ar/_mailing/vendedores-recordar/vendedores-recordar.html

Abrazo

**Comment by LeandroBraier** [comment]
Visualmente y en contenido está perfecto. Hay posibilidad de reducir la cantidad de imágenes, maquetandolo un poco más en html y menos con imágenes recortadas?

Digo para evitar lo más posible caer en el spam.

abrazo

**Comment by LeandroBraier** [comment]
Quedó excelente Braulio, gracias!

Avisame nomás cuando esté terminado.

abrazo

**Comment by LeandroBraier** [comment]
Braulio: mañana cuando arranques simplemente corregí la palabra capaz en la imagen (está mal el texto "Capáz", va sin acento). OJO: corregilo cambiando la imagen solamente, no toques el HTML porque ya está en producción.

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea, ahi lo acomodé

http://parexklaukol.com.ar/_mailing/vendedores-recordar/img/como-participo.jpg

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto, Braulio. Gracias!
